/// Access to known geographies in Albania and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'albania_states.dart';

/// The country of `🇦🇱 Albania`, and its 47 states
const Country albania = Country(id: 3, name: "Albania", longitude: 20.0,
          latitude: 41.0, capital: "Tirana",
          currency: "ALL", currencySymbol: "Lek",
          emoji: "🇦🇱", emojiU: "U+1F1E6 U+1F1F1",
          iso2: "AL", iso3: "ALB",
          native: "Shqipëria", numericCode: "008",
          phoneCode: "355", region: "Europe",
          subregion: "Southern Europe", tld: ".al",
          states: [
            albaniaBeratCounty,
            albaniaBeratDistrict,
            albaniaBulqizeDistrict,
            albaniaDelvineDistrict,
            albaniaDevollDistrict,
            albaniaDiberCounty,
            albaniaDiberDistrict,
            albaniaDurresCounty,
            albaniaDurresDistrict,
            albaniaElbasanCounty,
            albaniaFierCounty,
            albaniaFierDistrict,
            albaniaGjirokasterCounty,
            albaniaGjirokasterDistrict,
            albaniaGramshDistrict,
            albaniaHasDistrict,
            albaniaKavajeDistrict,
            albaniaKolonjeDistrict,
            albaniaKorceCounty,
            albaniaKorceDistrict,
            albaniaKrujeDistrict,
            albaniaKucoveDistrict,
            albaniaKukesCounty,
            albaniaKukesDistrict,
            albaniaKurbinDistrict,
            albaniaLezheCounty,
            albaniaLezheDistrict,
            albaniaLibrazhdDistrict,
            albaniaLushnjeDistrict,
            albaniaMalesiEeMadheDistrict,
            albaniaMallakasterDistrict,
            albaniaMatDistrict,
            albaniaMirditeDistrict,
            albaniaPeqinDistrict,
            albaniaPermetDistrict,
            albaniaPogradecDistrict,
            albaniaPukeDistrict,
            albaniaSarandeDistrict,
            albaniaShkoderCounty,
            albaniaShkoderDistrict,
            albaniaSkraparDistrict,
            albaniaTepeleneDistrict,
            albaniaTiranaCounty,
            albaniaTiranaDistrict,
            albaniaTropojeDistrict,
            albaniaVloreCounty,
            albaniaVloreDistrict
          ],
          timezones: [
            Timezone(abbreviation: "CET", gmtOffset: 3600, gmtOffsetName: "UTC+01:00",
                    tzName: "Central European Time", zoneName: "Europe/Tirane")
          ],
          translations: {
            "kr": "알바니아",
            "br": "Albânia",
            "pt": "Albânia",
            "nl": "Albanië",
            "hr": "Albanija",
            "fa": "آلبانی",
            "de": "Albanien",
            "es": "Albania",
            "fr": "Albanie",
            "ja": "アルバニア",
            "it": "Albania",
            "cn": "阿尔巴尼亚"
          });
