/// Access to known geographies in Argentina and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'argentina_cities.dart';

/// The 24 regions of `🇦🇷 Argentina`
const Region argentinaAutonomousCityOfBuenosAires = Region(
    id: 4880,
    parentId: 11,
    longitude: -58.3815591,
    latitude: -34.6036844,
    name: "Autonomous City Of Buenos Aires",
    type: null,
    stateCode: "C",
    cities: []);
const Region argentinaBuenosAiresProvince = Region(
    id: 3656,
    parentId: 11,
    longitude: -59.8410697,
    latitude: -37.2017285,
    name: "Buenos Aires Province",
    type: null,
    stateCode: "B",
    cities: [
      argentinaBuenosAiresProvinceBalvanera,
      argentinaBuenosAiresProvinceBarracas,
      argentinaBuenosAiresProvinceBelgrano,
      argentinaBuenosAiresProvinceBoedo,
      argentinaBuenosAiresProvinceBuenosAires,
      argentinaBuenosAiresProvinceColegiales,
      argentinaBuenosAiresProvinceRetiro,
      argentinaBuenosAiresProvinceVillaLugano,
      argentinaBuenosAiresProvinceVillaOrtuzar,
      argentinaBuenosAiresProvinceVillaSantaRita
    ]);
const Region argentinaCatamarcaProvince = Region(
    id: 3647,
    parentId: 11,
    longitude: -65.7877209,
    latitude: -28.4715877,
    name: "Catamarca Province",
    type: null,
    stateCode: "K",
    cities: [
      argentinaCatamarcaProvinceAncasti,
      argentinaCatamarcaProvinceAndalgala,
      argentinaCatamarcaProvinceAntofagastaDdeLlaSierra,
      argentinaCatamarcaProvinceCapayan,
      argentinaCatamarcaProvinceDepartamentoDdeAmbato,
      argentinaCatamarcaProvinceDepartamentoDdeAncasti,
      argentinaCatamarcaProvinceDepartamentoDdeAndalgala,
      argentinaCatamarcaProvinceDepartamentoDdeAntofagastaDdeLlaSierra,
      argentinaCatamarcaProvinceDepartamentoDdeCapayan,
      argentinaCatamarcaProvinceDepartamentoDdeCapital,
      argentinaCatamarcaProvinceDepartamentoDdeElAlto,
      argentinaCatamarcaProvinceDepartamentoDdeFrayMamertoEsquiu,
      argentinaCatamarcaProvinceDepartamentoDdeLaPaz,
      argentinaCatamarcaProvinceDepartamentoDdePoman,
      argentinaCatamarcaProvinceDepartamentoDdeSantaMaria,
      argentinaCatamarcaProvinceDepartamentoDdeSantaRosa,
      argentinaCatamarcaProvinceDepartamentoDdeTinogasta,
      argentinaCatamarcaProvinceDepartamentoDdeValleViejo,
      argentinaCatamarcaProvinceElRodeo,
      argentinaCatamarcaProvinceFiambala,
      argentinaCatamarcaProvinceHualfin,
      argentinaCatamarcaProvinceHuillapima,
      argentinaCatamarcaProvinceIcano,
      argentinaCatamarcaProvinceLaPuertaDdeSanJose,
      argentinaCatamarcaProvinceLondres,
      argentinaCatamarcaProvinceLosAltos,
      argentinaCatamarcaProvinceLosVarela,
      argentinaCatamarcaProvinceMutquin,
      argentinaCatamarcaProvincePoman,
      argentinaCatamarcaProvincePuertaDdeCorralQuemado,
      argentinaCatamarcaProvinceRecreo,
      argentinaCatamarcaProvinceSanAntonio,
      argentinaCatamarcaProvinceSanFernandoDdelValleDdeCatamarca,
      argentinaCatamarcaProvinceSantaMaria,
      argentinaCatamarcaProvinceTinogasta
    ]);
const Region argentinaChacoProvince = Region(
    id: 3640,
    parentId: 11,
    longitude: -59.0243784,
    latitude: -27.4257175,
    name: "Chaco Province",
    type: null,
    stateCode: "H",
    cities: [
      argentinaChacoProvinceAviaTerai,
      argentinaChacoProvinceBarranqueras,
      argentinaChacoProvinceBasail,
      argentinaChacoProvinceCampoLargo,
      argentinaChacoProvinceCapitanSolari,
      argentinaChacoProvinceCastelli,
      argentinaChacoProvinceCharadai,
      argentinaChacoProvinceCharata,
      argentinaChacoProvinceChorotis,
      argentinaChacoProvinceCiervoPetiso,
      argentinaChacoProvinceColoniaBenitez,
      argentinaChacoProvinceColoniaElisa,
      argentinaChacoProvinceColoniasUnidas,
      argentinaChacoProvinceConcepcionDdelBermejo,
      argentinaChacoProvinceCoronelDuGraty,
      argentinaChacoProvinceCorzuela,
      argentinaChacoProvinceCoteHypLai,
      argentinaChacoProvinceDepartamentoDdeAlmiranteBrown,
      argentinaChacoProvinceDepartamentoDdeBermejo,
      argentinaChacoProvinceDepartamentoDdeComandanteFernandez,
      argentinaChacoProvinceDepartamentoDdeDoceDdeOctubre,
      argentinaChacoProvinceDepartamentoDdeDosDdeAbril,
      argentinaChacoProvinceDepartamentoDdeGeneralDonovan,
      argentinaChacoProvinceDepartamentoDdeGeneralGuemes,
      argentinaChacoProvinceDepartamentoDdeIndependencia,
      argentinaChacoProvinceDepartamentoDdeLibertad,
      argentinaChacoProvinceDepartamentoDdeMaipu,
      argentinaChacoProvinceDepartamentoDdeNueveDdeJulio,
      argentinaChacoProvinceDepartamentoDdeOHiggins,
      argentinaChacoProvinceDepartamentoDdePresidenciaDdeLlaPlaza,
      argentinaChacoProvinceDepartamentoDdeQuitilipi,
      argentinaChacoProvinceDepartamentoDdeSanFernando,
      argentinaChacoProvinceDepartamentoDdeSanLorenzo,
      argentinaChacoProvinceDepartamentoDdeSargentoCabral,
      argentinaChacoProvinceDepartamentoDdeTapenaga,
      argentinaChacoProvinceFontana,
      argentinaChacoProvinceGancedo,
      argentinaChacoProvinceGeneralJoseDdeSanMartin,
      argentinaChacoProvinceGeneralPinedo,
      argentinaChacoProvinceGeneralVedia,
      argentinaChacoProvinceHermosoCampo,
      argentinaChacoProvinceLaClotilde,
      argentinaChacoProvinceLaEduvigis,
      argentinaChacoProvinceLaEscondida,
      argentinaChacoProvinceLaLeonesa,
      argentinaChacoProvinceLaTigra,
      argentinaChacoProvinceLaVerde,
      argentinaChacoProvinceLagunaLimpia,
      argentinaChacoProvinceLapachito,
      argentinaChacoProvinceLasBrenas,
      argentinaChacoProvinceLasGarcitas,
      argentinaChacoProvinceLosFrentones,
      argentinaChacoProvinceMachagai,
      argentinaChacoProvinceMakalle,
      argentinaChacoProvinceMargaritaBelen,
      argentinaChacoProvinceNapenay,
      argentinaChacoProvincePampaAlmiron,
      argentinaChacoProvincePampaDdelIndio,
      argentinaChacoProvincePampaDdelInfierno,
      argentinaChacoProvincePresidenciaDdeLlaPlaza,
      argentinaChacoProvincePresidenciaRoca,
      argentinaChacoProvincePresidenciaRoqueSaenzPena,
      argentinaChacoProvincePuertoBermejo,
      argentinaChacoProvincePuertoTirol,
      argentinaChacoProvincePuertoVilelas,
      argentinaChacoProvinceQuitilipi,
      argentinaChacoProvinceResistencia,
      argentinaChacoProvinceSamuhu,
      argentinaChacoProvinceSanBernardo,
      argentinaChacoProvinceSantaSylvina,
      argentinaChacoProvinceTacoPozo,
      argentinaChacoProvinceTresIsletas,
      argentinaChacoProvinceVillaAngela,
      argentinaChacoProvinceVillaBerthet
    ]);
const Region argentinaChubutProvince = Region(
    id: 3651,
    parentId: 11,
    longitude: -65.1114818,
    latitude: -43.2934246,
    name: "Chubut Province",
    type: null,
    stateCode: "U",
    cities: [
      argentinaChubutProvinceAltoRioSenguer,
      argentinaChubutProvinceCamarones,
      argentinaChubutProvinceComodoroRivadavia,
      argentinaChubutProvinceDepartamentoDdeBiedma,
      argentinaChubutProvinceDepartamentoDdeCushamen,
      argentinaChubutProvinceDepartamentoDdeEscalante,
      argentinaChubutProvinceDepartamentoDdeFlorentinoAmeghino,
      argentinaChubutProvinceDepartamentoDdeFutaleufu,
      argentinaChubutProvinceDepartamentoDdeGaiman,
      argentinaChubutProvinceDepartamentoDdeGastre,
      argentinaChubutProvinceDepartamentoDdeLanguineo,
      argentinaChubutProvinceDepartamentoDdeMartires,
      argentinaChubutProvinceDepartamentoDdePasoDdeIndios,
      argentinaChubutProvinceDepartamentoDdeRawson,
      argentinaChubutProvinceDepartamentoDdeRioSenguerr,
      argentinaChubutProvinceDepartamentoDdeSarmiento,
      argentinaChubutProvinceDepartamentoDdeTehuelches,
      argentinaChubutProvinceDepartamentoDdeTelsen,
      argentinaChubutProvinceDolavon,
      argentinaChubutProvinceElMaiten,
      argentinaChubutProvinceEsquel,
      argentinaChubutProvinceGaiman,
      argentinaChubutProvinceGastre,
      argentinaChubutProvinceGobernadorCosta,
      argentinaChubutProvinceHoyoDdeEpuyen,
      argentinaChubutProvinceJoseDdeSanMartin,
      argentinaChubutProvinceLagoPuelo,
      argentinaChubutProvinceLasPlumas,
      argentinaChubutProvincePuertoMadryn,
      argentinaChubutProvinceRadaTilly,
      argentinaChubutProvinceRawson,
      argentinaChubutProvinceRioMayo,
      argentinaChubutProvinceRioPico,
      argentinaChubutProvinceSarmiento,
      argentinaChubutProvinceTecka,
      argentinaChubutProvinceTrelew,
      argentinaChubutProvinceTrevelin
    ]);
const Region argentinaCordobaProvince = Region(
    id: 3642,
    parentId: 11,
    longitude: 1.7976931348623157e+308,
    latitude: 1.7976931348623157e+308,
    name: "Córdoba Province",
    type: null,
    stateCode: "X",
    cities: [
      argentinaCordobaProvinceAchiras,
      argentinaCordobaProvinceAdeliaMaria,
      argentinaCordobaProvinceAguaDdeOro,
      argentinaCordobaProvinceAlejandroRoca,
      argentinaCordobaProvinceAlejoLedesma,
      argentinaCordobaProvinceAlmafuerte,
      argentinaCordobaProvinceAltaGracia,
      argentinaCordobaProvinceAltosDdeChipion,
      argentinaCordobaProvinceArias,
      argentinaCordobaProvinceArroyito,
      argentinaCordobaProvinceArroyoCabral,
      argentinaCordobaProvinceBalnearia,
      argentinaCordobaProvinceBellVille,
      argentinaCordobaProvinceBerrotaran,
      argentinaCordobaProvinceBrinkmann,
      argentinaCordobaProvinceBuchardo,
      argentinaCordobaProvinceCamiloAldao,
      argentinaCordobaProvinceCanadaDdeLuque,
      argentinaCordobaProvinceCanals,
      argentinaCordobaProvinceCapillaDdelMonte,
      argentinaCordobaProvinceCarnerillo,
      argentinaCordobaProvinceCarrilobo,
      argentinaCordobaProvinceCavanagh,
      argentinaCordobaProvinceCharras,
      argentinaCordobaProvinceChazon,
      argentinaCordobaProvinceCintra,
      argentinaCordobaProvinceColoniaLaTordilla,
      argentinaCordobaProvinceColoniaSanBartolome,
      argentinaCordobaProvinceCordoba,
      argentinaCordobaProvinceCoronelBaigorria,
      argentinaCordobaProvinceCoronelMoldes,
      argentinaCordobaProvinceCorralDdeBustos,
      argentinaCordobaProvinceCorralito,
      argentinaCordobaProvinceCosquin,
      argentinaCordobaProvinceCostaSacate,
      argentinaCordobaProvinceCruzAlta,
      argentinaCordobaProvinceCruzDdelEje,
      argentinaCordobaProvinceCuestaBlanca,
      argentinaCordobaProvinceDalmacioVelezSarsfield,
      argentinaCordobaProvinceDeanFunes,
      argentinaCordobaProvinceDelCampillo,
      argentinaCordobaProvinceDepartamentoDdeCalamuchita,
      argentinaCordobaProvinceDepartamentoDdeColon,
      argentinaCordobaProvinceDepartamentoDdeCruzDdelEje,
      argentinaCordobaProvinceDepartamentoDdeGeneralRoca,
      argentinaCordobaProvinceDepartamentoDdeGeneralSanMartin,
      argentinaCordobaProvinceDepartamentoDdeJuarezCelman,
      argentinaCordobaProvinceDepartamentoDdeMarcosJuarez,
      argentinaCordobaProvinceDepartamentoDdeMinas,
      argentinaCordobaProvinceDepartamentoDdePresidenteRoqueSaenzPena,
      argentinaCordobaProvinceDepartamentoDdeRioCuarto,
      argentinaCordobaProvinceDepartamentoDdeRioPrimero,
      argentinaCordobaProvinceDepartamentoDdeRioSeco,
      argentinaCordobaProvinceDepartamentoDdeRioSegundo,
      argentinaCordobaProvinceDepartamentoDdeSanAlberto,
      argentinaCordobaProvinceDepartamentoDdeSanJavier,
      argentinaCordobaProvinceDepartamentoDdeSanJusto,
      argentinaCordobaProvinceDepartamentoDdeSobremonte,
      argentinaCordobaProvinceDepartamentoDdeTotoral,
      argentinaCordobaProvinceDepartamentoDdeTulumba,
      argentinaCordobaProvinceDepartamentoDdeUnion,
      argentinaCordobaProvinceDespenaderos,
      argentinaCordobaProvinceDevoto,
      argentinaCordobaProvinceElAranado,
      argentinaCordobaProvinceElTio,
      argentinaCordobaProvinceElena,
      argentinaCordobaProvinceEmbalse,
      argentinaCordobaProvinceEtruria,
      argentinaCordobaProvinceGeneralBaldissera,
      argentinaCordobaProvinceGeneralCabrera,
      argentinaCordobaProvinceGeneralLevalle,
      argentinaCordobaProvinceGeneralRoca,
      argentinaCordobaProvinceGuatimozin,
      argentinaCordobaProvinceHernando,
      argentinaCordobaProvinceHuanchillas,
      argentinaCordobaProvinceHuertaGrande,
      argentinaCordobaProvinceHuincaRenanco,
      argentinaCordobaProvinceIdiazabal,
      argentinaCordobaProvinceInriville,
      argentinaCordobaProvinceIslaVerde,
      argentinaCordobaProvinceItalo,
      argentinaCordobaProvinceJamesCraik,
      argentinaCordobaProvinceJesusMaria,
      argentinaCordobaProvinceJustinianoPosse,
      argentinaCordobaProvinceLaCalera,
      argentinaCordobaProvinceLaCarlota,
      argentinaCordobaProvinceLaCesira,
      argentinaCordobaProvinceLaCumbre,
      argentinaCordobaProvinceLaFalda,
      argentinaCordobaProvinceLaFrancia,
      argentinaCordobaProvinceLaGranja,
      argentinaCordobaProvinceLaPara,
      argentinaCordobaProvinceLaPlayosa,
      argentinaCordobaProvinceLaborde,
      argentinaCordobaProvinceLaboulaye,
      argentinaCordobaProvinceLagunaLarga,
      argentinaCordobaProvinceLasAcequias,
      argentinaCordobaProvinceLasHigueras,
      argentinaCordobaProvinceLasJunturas,
      argentinaCordobaProvinceLasPerdices,
      argentinaCordobaProvinceLasVaras,
      argentinaCordobaProvinceLasVarillas,
      argentinaCordobaProvinceLeones,
      argentinaCordobaProvinceLosCocos,
      argentinaCordobaProvinceLosCondores,
      argentinaCordobaProvinceLosSurgentes,
      argentinaCordobaProvinceMalagueno,
      argentinaCordobaProvinceMalvinasArgentinas,
      argentinaCordobaProvinceMarcosJuarez,
      argentinaCordobaProvinceMarull,
      argentinaCordobaProvinceMattaldi,
      argentinaCordobaProvinceMendiolaza,
      argentinaCordobaProvinceMinaClavero,
      argentinaCordobaProvinceMiramar,
      argentinaCordobaProvinceMonteBuey,
      argentinaCordobaProvinceMonteCristo,
      argentinaCordobaProvinceMonteMaiz,
      argentinaCordobaProvinceMorrison,
      argentinaCordobaProvinceMorteros,
      argentinaCordobaProvinceNoetinger,
      argentinaCordobaProvinceObispoTrejo,
      argentinaCordobaProvinceOliva,
      argentinaCordobaProvinceOncativo,
      argentinaCordobaProvinceOrdonez,
      argentinaCordobaProvincePascanas,
      argentinaCordobaProvincePasco,
      argentinaCordobaProvincePilar,
      argentinaCordobaProvincePiquillin,
      argentinaCordobaProvincePortena,
      argentinaCordobaProvincePozoDdelMolle,
      argentinaCordobaProvinceQuilino,
      argentinaCordobaProvinceRioCeballos,
      argentinaCordobaProvinceRioCuarto,
      argentinaCordobaProvinceRioSegundo,
      argentinaCordobaProvinceRioTercero,
      argentinaCordobaProvinceSacanta,
      argentinaCordobaProvinceSaldan,
      argentinaCordobaProvinceSalsacate,
      argentinaCordobaProvinceSalsipuedes,
      argentinaCordobaProvinceSampacho,
      argentinaCordobaProvinceSanAgustin,
      argentinaCordobaProvinceSanAntonioDdeLitin,
      argentinaCordobaProvinceSanBasilio,
      argentinaCordobaProvinceSanCarlos,
      argentinaCordobaProvinceSanFrancisco,
      argentinaCordobaProvinceSanFranciscoDdelChanar,
      argentinaCordobaProvinceSanJoseDdeLlaDormida,
      argentinaCordobaProvinceSantaEufemia,
      argentinaCordobaProvinceSantaMagdalena,
      argentinaCordobaProvinceSantaRosaDdeCalamuchita,
      argentinaCordobaProvinceSantaRosaDdeRioPrimero,
      argentinaCordobaProvinceSantiagoTemple,
      argentinaCordobaProvinceSaturninoMDotLaspiur,
      argentinaCordobaProvinceSebastianElcano,
      argentinaCordobaProvinceSerrano,
      argentinaCordobaProvinceSerrezuela,
      argentinaCordobaProvinceTancacha,
      argentinaCordobaProvinceTicino,
      argentinaCordobaProvinceTioPujio,
      argentinaCordobaProvinceToledo,
      argentinaCordobaProvinceUcacha,
      argentinaCordobaProvinceUnquillo,
      argentinaCordobaProvinceValleHermoso,
      argentinaCordobaProvinceViamonte,
      argentinaCordobaProvinceVicunaMackenna,
      argentinaCordobaProvinceVillaAllende,
      argentinaCordobaProvinceVillaAscasubi,
      argentinaCordobaProvinceVillaBerna,
      argentinaCordobaProvinceVillaCarlosPaz,
      argentinaCordobaProvinceVillaConcepcionDdelTio,
      argentinaCordobaProvinceVillaCuraBrochero,
      argentinaCordobaProvinceVillaDdeSoto,
      argentinaCordobaProvinceVillaDdelDique,
      argentinaCordobaProvinceVillaDdelRosario,
      argentinaCordobaProvinceVillaDdelTotoral,
      argentinaCordobaProvinceVillaDolores,
      argentinaCordobaProvinceVillaGeneralBelgrano,
      argentinaCordobaProvinceVillaGiardino,
      argentinaCordobaProvinceVillaHuidobro,
      argentinaCordobaProvinceVillaLasRosas,
      argentinaCordobaProvinceVillaMaria,
      argentinaCordobaProvinceVillaNueva,
      argentinaCordobaProvinceVillaReduccion,
      argentinaCordobaProvinceVillaRumipal,
      argentinaCordobaProvinceVillaTulumba,
      argentinaCordobaProvinceVillaValeria,
      argentinaCordobaProvinceWenceslaoEscalante
    ]);
const Region argentinaCorrientes = Region(
    id: 3638,
    parentId: 11,
    longitude: -58.8306349,
    latitude: -27.4692131,
    name: "Corrientes",
    type: null,
    stateCode: "W",
    cities: [
      argentinaCorrientesAlvear,
      argentinaCorrientesBeronDdeAstrada,
      argentinaCorrientesBonpland,
      argentinaCorrientesChavarria,
      argentinaCorrientesConcepcion,
      argentinaCorrientesCorrientes,
      argentinaCorrientesCruzDdeLlosMilagros,
      argentinaCorrientesCuruzuCuatia,
      argentinaCorrientesDepartamentoDdeBellaVista,
      argentinaCorrientesDepartamentoDdeBeronDdeAstrada,
      argentinaCorrientesDepartamentoDdeCapital,
      argentinaCorrientesDepartamentoDdeConcepcion,
      argentinaCorrientesDepartamentoDdeCuruzuCuatia,
      argentinaCorrientesDepartamentoDdeEmpedrado,
      argentinaCorrientesDepartamentoDdeEsquina,
      argentinaCorrientesDepartamentoDdeGeneralAlvear,
      argentinaCorrientesDepartamentoDdeGeneralPaz,
      argentinaCorrientesDepartamentoDdeGoya,
      argentinaCorrientesDepartamentoDdeItati,
      argentinaCorrientesDepartamentoDdeItuzaingo,
      argentinaCorrientesDepartamentoDdeLavalle,
      argentinaCorrientesDepartamentoDdeMburucuya,
      argentinaCorrientesDepartamentoDdeMercedes,
      argentinaCorrientesDepartamentoDdeMonteCaseros,
      argentinaCorrientesDepartamentoDdePasoDdeLlosLibres,
      argentinaCorrientesDepartamentoDdeSaladas,
      argentinaCorrientesDepartamentoDdeSanCosme,
      argentinaCorrientesDepartamentoDdeSanLuisDdelPalmar,
      argentinaCorrientesDepartamentoDdeSanMartin,
      argentinaCorrientesDepartamentoDdeSanMiguel,
      argentinaCorrientesDepartamentoDdeSanRoque,
      argentinaCorrientesDepartamentoDdeSantoTome,
      argentinaCorrientesDepartamentoDdeSauce,
      argentinaCorrientesEmpedrado,
      argentinaCorrientesEsquina,
      argentinaCorrientesFelipeYofre,
      argentinaCorrientesGarruchos,
      argentinaCorrientesGobernadorJuanEDotMartinez,
      argentinaCorrientesGobernadorVirasora,
      argentinaCorrientesGoya,
      argentinaCorrientesHerlitzka,
      argentinaCorrientesItaIbate,
      argentinaCorrientesItati,
      argentinaCorrientesItuzaingo,
      argentinaCorrientesJuanPujol,
      argentinaCorrientesLaCruz,
      argentinaCorrientesLibertad,
      argentinaCorrientesLomasDdeVallejos,
      argentinaCorrientesLoreto,
      argentinaCorrientesMarianoIDotLoza,
      argentinaCorrientesMburucuya,
      argentinaCorrientesMercedes,
      argentinaCorrientesMocoreta,
      argentinaCorrientesMonteCaseros,
      argentinaCorrientesNuestraSenoraDdelRosarioDdeCaaCati,
      argentinaCorrientesNueveDdeJulio,
      argentinaCorrientesPalmarGrande,
      argentinaCorrientesPasoDdeLlaPatria,
      argentinaCorrientesPasoDdeLlosLibres,
      argentinaCorrientesPedroRDotFernandez,
      argentinaCorrientesPerugorria,
      argentinaCorrientesPuebloLibertador,
      argentinaCorrientesRiachuelo,
      argentinaCorrientesSaladas,
      argentinaCorrientesSanCarlos,
      argentinaCorrientesSanCosme,
      argentinaCorrientesSanLorenzo,
      argentinaCorrientesSanLuisDdelPalmar,
      argentinaCorrientesSanMiguel,
      argentinaCorrientesSantaLucia,
      argentinaCorrientesSantaRosa,
      argentinaCorrientesSantoTome,
      argentinaCorrientesYapeyu,
      argentinaCorrientesYataityCalle
    ]);
const Region argentinaEntreRiosProvince = Region(
    id: 3654,
    parentId: 11,
    longitude: -60.4956461,
    latitude: -31.7746654,
    name: "Entre Ríos Province",
    type: null,
    stateCode: "E",
    cities: [
      argentinaEntreRiosProvinceAldeaSanAntonio,
      argentinaEntreRiosProvinceAranguren,
      argentinaEntreRiosProvinceBovril,
      argentinaEntreRiosProvinceCaseros,
      argentinaEntreRiosProvinceCeibas,
      argentinaEntreRiosProvinceChajari,
      argentinaEntreRiosProvinceColon,
      argentinaEntreRiosProvinceColoniaElia,
      argentinaEntreRiosProvinceConcepcionDdelUruguay,
      argentinaEntreRiosProvinceConcordia,
      argentinaEntreRiosProvinceConscriptoBernardi,
      argentinaEntreRiosProvinceCrespo,
      argentinaEntreRiosProvinceDepartamentoDdeGualeguaychu,
      argentinaEntreRiosProvinceDepartamentoDdeParana,
      argentinaEntreRiosProvinceDiamante,
      argentinaEntreRiosProvinceDominguez,
      argentinaEntreRiosProvinceFederacion,
      argentinaEntreRiosProvinceFederal,
      argentinaEntreRiosProvinceGeneralCampos,
      argentinaEntreRiosProvinceGeneralGalarza,
      argentinaEntreRiosProvinceGeneralRamirez,
      argentinaEntreRiosProvinceGobernadorMansilla,
      argentinaEntreRiosProvinceGualeguay,
      argentinaEntreRiosProvinceGualeguaychu,
      argentinaEntreRiosProvinceHasenkamp,
      argentinaEntreRiosProvinceHernandez,
      argentinaEntreRiosProvinceHerrera,
      argentinaEntreRiosProvinceLaCriolla,
      argentinaEntreRiosProvinceLaPaz,
      argentinaEntreRiosProvinceLarroque,
      argentinaEntreRiosProvinceLosCharruas,
      argentinaEntreRiosProvinceLosConquistadores,
      argentinaEntreRiosProvinceLucasGonzalez,
      argentinaEntreRiosProvinceMacia,
      argentinaEntreRiosProvinceNogoya,
      argentinaEntreRiosProvinceOroVerde,
      argentinaEntreRiosProvinceParana,
      argentinaEntreRiosProvincePiedrasBlancas,
      argentinaEntreRiosProvincePronunciamiento,
      argentinaEntreRiosProvincePuertoIbicuy,
      argentinaEntreRiosProvincePuertoYerua,
      argentinaEntreRiosProvinceRosarioDdelTala,
      argentinaEntreRiosProvinceSanBenito,
      argentinaEntreRiosProvinceSanGustavo,
      argentinaEntreRiosProvinceSanJoseDdeFeliciano,
      argentinaEntreRiosProvinceSanJusto,
      argentinaEntreRiosProvinceSanSalvador,
      argentinaEntreRiosProvinceSantaAna,
      argentinaEntreRiosProvinceSantaAnita,
      argentinaEntreRiosProvinceSantaElena,
      argentinaEntreRiosProvinceSauceDdeLuna,
      argentinaEntreRiosProvinceSegui,
      argentinaEntreRiosProvinceTabossi,
      argentinaEntreRiosProvinceUbajay,
      argentinaEntreRiosProvinceUrdinarrain,
      argentinaEntreRiosProvinceViale,
      argentinaEntreRiosProvinceVictoria,
      argentinaEntreRiosProvinceVillaDdelRosario,
      argentinaEntreRiosProvinceVillaElisa,
      argentinaEntreRiosProvinceVillaHernandarias,
      argentinaEntreRiosProvinceVillaMantero,
      argentinaEntreRiosProvinceVillaMariaGrande,
      argentinaEntreRiosProvinceVillaParanacito,
      argentinaEntreRiosProvinceVillaUrquiza,
      argentinaEntreRiosProvinceVillaguay
    ]);
const Region argentinaFormosaProvince = Region(
    id: 3652,
    parentId: 11,
    longitude: -58.2242806,
    latitude: -26.1894804,
    name: "Formosa Province",
    type: null,
    stateCode: "P",
    cities: [
      argentinaFormosaProvinceClorinda,
      argentinaFormosaProvinceComandanteFontana,
      argentinaFormosaProvinceDepartamentoDdePilcomayo,
      argentinaFormosaProvinceElColorado,
      argentinaFormosaProvinceEstanislaoDdelCampo,
      argentinaFormosaProvinceFormosa,
      argentinaFormosaProvinceGeneralEnriqueMosconi,
      argentinaFormosaProvinceHerradura,
      argentinaFormosaProvinceIbarreta,
      argentinaFormosaProvinceIngenieroGuillermoNDotJuarez,
      argentinaFormosaProvinceLagunaNaickHypNeck,
      argentinaFormosaProvinceLagunaYema,
      argentinaFormosaProvinceLasLomitas,
      argentinaFormosaProvincePaloSanto,
      argentinaFormosaProvincePirane,
      argentinaFormosaProvincePozoDdelTigre,
      argentinaFormosaProvinceRiachoEhHypEh,
      argentinaFormosaProvinceSanFranciscoDdeLaishi,
      argentinaFormosaProvinceVillaEscolar,
      argentinaFormosaProvinceVillaGeneralGuemes
    ]);
const Region argentinaJujuyProvince = Region(
    id: 3645,
    parentId: 11,
    longitude: -65.302177,
    latitude: -24.1843397,
    name: "Jujuy Province",
    type: null,
    stateCode: "Y",
    cities: [
      argentinaJujuyProvinceAbraPampa,
      argentinaJujuyProvinceCaimancito,
      argentinaJujuyProvinceCalilegua,
      argentinaJujuyProvinceDepartamentoDdeCochinoca,
      argentinaJujuyProvinceDepartamentoDdeRinconada,
      argentinaJujuyProvinceDepartamentoDdeTumbaya,
      argentinaJujuyProvinceElAguilar,
      argentinaJujuyProvinceFrailePintado,
      argentinaJujuyProvinceHumahuaca,
      argentinaJujuyProvinceIngenioLaEsperanza,
      argentinaJujuyProvinceLaMendieta,
      argentinaJujuyProvinceLaQuiaca,
      argentinaJujuyProvinceLibertadorGeneralSanMartin,
      argentinaJujuyProvinceMaimara,
      argentinaJujuyProvincePalmaSola,
      argentinaJujuyProvincePalpala,
      argentinaJujuyProvinceSanPedroDdeJujuy,
      argentinaJujuyProvinceSanSalvadorDdeJujuy,
      argentinaJujuyProvinceSantaClara,
      argentinaJujuyProvinceTilcara,
      argentinaJujuyProvinceYuto
    ]);
const Region argentinaLaPampa = Region(
    id: 3655,
    parentId: 11,
    longitude: -64.2839209,
    latitude: -36.6147573,
    name: "La Pampa",
    type: null,
    stateCode: "L",
    cities: [
      argentinaLaPampaAlpachiri,
      argentinaLaPampaAltaItalia,
      argentinaLaPampaAnguil,
      argentinaLaPampaArata,
      argentinaLaPampaBernardoLarroude,
      argentinaLaPampaBernasconi,
      argentinaLaPampaCaleufu,
      argentinaLaPampaCatrilo,
      argentinaLaPampaColoniaBaron,
      argentinaLaPampaDepartamentoDdeCaleuHypCaleu,
      argentinaLaPampaDepartamentoDdeToay,
      argentinaLaPampaDoblas,
      argentinaLaPampaEduardoCastex,
      argentinaLaPampaEmbajadorMartini,
      argentinaLaPampaGeneralAcha,
      argentinaLaPampaGeneralManuelJDotCampos,
      argentinaLaPampaGeneralPico,
      argentinaLaPampaGeneralSanMartin,
      argentinaLaPampaGuatrache,
      argentinaLaPampaIngenieroLuiggi,
      argentinaLaPampaIntendenteAlvear,
      argentinaLaPampaJacintoArauz,
      argentinaLaPampaLaAdela,
      argentinaLaPampaLaMaruja,
      argentinaLaPampaLonquimay,
      argentinaLaPampaMacachin,
      argentinaLaPampaMiguelRiglos,
      argentinaLaPampaParera,
      argentinaLaPampaQuemuQuemu,
      argentinaLaPampaRancul,
      argentinaLaPampaRealico,
      argentinaLaPampaSantaIsabel,
      argentinaLaPampaSantaRosa,
      argentinaLaPampaTelen,
      argentinaLaPampaTrenel,
      argentinaLaPampaUriburu,
      argentinaLaPampaVeinticincoDdeMayo,
      argentinaLaPampaVictorica,
      argentinaLaPampaWinifreda
    ]);
const Region argentinaLaRiojaProvince = Region(
    id: 3653,
    parentId: 11,
    longitude: -66.8559932,
    latitude: -29.4193793,
    name: "La Rioja Province",
    type: null,
    stateCode: "F",
    cities: [
      argentinaLaRiojaProvinceArauco,
      argentinaLaRiojaProvinceCastroBarros,
      argentinaLaRiojaProvinceChamical,
      argentinaLaRiojaProvinceChilecito,
      argentinaLaRiojaProvinceDepartamentoDdeArauco,
      argentinaLaRiojaProvinceDepartamentoDdeGeneralLamadrid,
      argentinaLaRiojaProvinceDepartamentoDdeIndependencia,
      argentinaLaRiojaProvinceLaRioja,
      argentinaLaRiojaProvinceVillaBustos,
      argentinaLaRiojaProvinceVinchina
    ]);
const Region argentinaMendoza = Region(
    id: 3646,
    parentId: 11,
    longitude: -68.8458386,
    latitude: -32.8894587,
    name: "Mendoza",
    type: null,
    stateCode: "M",
    cities: [
      argentinaMendozaDepartamentoDdeCapital,
      argentinaMendozaDepartamentoDdeGeneralAlvear,
      argentinaMendozaDepartamentoDdeGodoyCruz,
      argentinaMendozaDepartamentoDdeGuaymallen,
      argentinaMendozaDepartamentoDdeLaPaz,
      argentinaMendozaDepartamentoDdeLasHeras,
      argentinaMendozaDepartamentoDdeLavalle,
      argentinaMendozaDepartamentoDdeLujan,
      argentinaMendozaDepartamentoDdeMaipu,
      argentinaMendozaDepartamentoDdeMalargue,
      argentinaMendozaDepartamentoDdeRivadavia,
      argentinaMendozaDepartamentoDdeSanCarlos,
      argentinaMendozaDepartamentoDdeSanMartin,
      argentinaMendozaDepartamentoDdeSanRafael,
      argentinaMendozaDepartamentoDdeSantaRosa,
      argentinaMendozaDepartamentoDdeTunuyan,
      argentinaMendozaDepartamentoDdeTupungato,
      argentinaMendozaGodoyCruz,
      argentinaMendozaLasHeras,
      argentinaMendozaMendoza,
      argentinaMendozaSanMartin,
      argentinaMendozaSanRafael
    ]);
const Region argentinaMisionesProvince = Region(
    id: 3644,
    parentId: 11,
    longitude: -55.9467076,
    latitude: -27.4269255,
    name: "Misiones Province",
    type: null,
    stateCode: "N",
    cities: [
      argentinaMisionesProvinceAlbaPosse,
      argentinaMisionesProvinceAlmafuerte,
      argentinaMisionesProvinceAristobuloDdelValle,
      argentinaMisionesProvinceArroyoDdelMedio,
      argentinaMisionesProvinceAzara,
      argentinaMisionesProvinceBernardoDdeIrigoyen,
      argentinaMisionesProvinceBonpland,
      argentinaMisionesProvinceCampoGrande,
      argentinaMisionesProvinceCampoRamon,
      argentinaMisionesProvinceCampoViera,
      argentinaMisionesProvinceCandelaria,
      argentinaMisionesProvinceCapiovi,
      argentinaMisionesProvinceCaraguatay,
      argentinaMisionesProvinceCerroAzul,
      argentinaMisionesProvinceCerroCora,
      argentinaMisionesProvinceColoniaAurora,
      argentinaMisionesProvinceConcepcionDdeLlaSierra,
      argentinaMisionesProvinceDepartamentoDdeApostoles,
      argentinaMisionesProvinceDepartamentoDdeCainguas,
      argentinaMisionesProvinceDepartamentoDdeCandelaria,
      argentinaMisionesProvinceDepartamentoDdeCapital,
      argentinaMisionesProvinceDepartamentoDdeConcepcionDdeLlaSierra,
      argentinaMisionesProvinceDepartamentoDdeEldorado,
      argentinaMisionesProvinceDepartamentoDdeGeneralManuelBelgrano,
      argentinaMisionesProvinceDepartamentoDdeGuarani,
      argentinaMisionesProvinceDepartamentoDdeIguazu,
      argentinaMisionesProvinceDepartamentoDdeLeandroNDotAlem,
      argentinaMisionesProvinceDepartamentoDdeLibertadorGeneralSanMartin,
      argentinaMisionesProvinceDepartamentoDdeMontecarlo,
      argentinaMisionesProvinceDepartamentoDdeObera,
      argentinaMisionesProvinceDepartamentoDdeSanIgnacio,
      argentinaMisionesProvinceDepartamentoDdeSanJavier,
      argentinaMisionesProvinceDepartamentoDdeSanPedro,
      argentinaMisionesProvinceDepartamentoDdeVeinticincoDdeMayo,
      argentinaMisionesProvinceDosArroyos,
      argentinaMisionesProvinceDosDdeMayo,
      argentinaMisionesProvinceElAlcazar,
      argentinaMisionesProvinceElSoberbio,
      argentinaMisionesProvinceFlorentinoAmeghino,
      argentinaMisionesProvinceGaruhape,
      argentinaMisionesProvinceGarupa,
      argentinaMisionesProvinceGeneralAlvear,
      argentinaMisionesProvinceGobernadorRoca,
      argentinaMisionesProvinceGuarani,
      argentinaMisionesProvinceJardinAmerica,
      argentinaMisionesProvinceLoreto,
      argentinaMisionesProvinceLosHelechos,
      argentinaMisionesProvinceMartires,
      argentinaMisionesProvinceMojonGrande,
      argentinaMisionesProvinceMontecarlo,
      argentinaMisionesProvinceObera,
      argentinaMisionesProvincePanambi,
      argentinaMisionesProvincePicadaGobernadorLopez,
      argentinaMisionesProvincePosadas,
      argentinaMisionesProvincePuertoEldorado,
      argentinaMisionesProvincePuertoEsperanza,
      argentinaMisionesProvincePuertoIguazu,
      argentinaMisionesProvincePuertoLeoni,
      argentinaMisionesProvincePuertoLibertad,
      argentinaMisionesProvincePuertoPiray,
      argentinaMisionesProvincePuertoRico,
      argentinaMisionesProvinceRuizDdeMontoya,
      argentinaMisionesProvinceSanJose,
      argentinaMisionesProvinceSanPedro,
      argentinaMisionesProvinceSanVicente,
      argentinaMisionesProvinceSantaMaria,
      argentinaMisionesProvinceSantoPipo,
      argentinaMisionesProvinceTresCapones,
      argentinaMisionesProvinceVeinticincoDdeMayo,
      argentinaMisionesProvinceWanda
    ]);
const Region argentinaNeuquenProvince = Region(
    id: 3648,
    parentId: 11,
    longitude: -68.0730925,
    latitude: -38.94587,
    name: "Neuquén Province",
    type: null,
    stateCode: "Q",
    cities: [
      argentinaNeuquenProvinceAlumine,
      argentinaNeuquenProvinceAndacollo,
      argentinaNeuquenProvinceAnelo,
      argentinaNeuquenProvinceBarrancas,
      argentinaNeuquenProvinceButaRanquil,
      argentinaNeuquenProvinceCentenario,
      argentinaNeuquenProvinceChosMalal,
      argentinaNeuquenProvinceCutralHypCo,
      argentinaNeuquenProvinceDepartamentoDdeAlumine,
      argentinaNeuquenProvinceDepartamentoDdeAnelo,
      argentinaNeuquenProvinceDepartamentoDdeCatanHypLil,
      argentinaNeuquenProvinceDepartamentoDdeChosHypMalal,
      argentinaNeuquenProvinceDepartamentoDdeCollonHypCura,
      argentinaNeuquenProvinceDepartamentoDdeConfluencia,
      argentinaNeuquenProvinceDepartamentoDdeLacar,
      argentinaNeuquenProvinceDepartamentoDdeMinas,
      argentinaNeuquenProvinceDepartamentoDdeZapala,
      argentinaNeuquenProvinceElHuecu,
      argentinaNeuquenProvinceJuninDdeLlosAndes,
      argentinaNeuquenProvinceLasColoradas,
      argentinaNeuquenProvinceLasLajas,
      argentinaNeuquenProvinceLasOvejas,
      argentinaNeuquenProvinceLoncopue,
      argentinaNeuquenProvinceMarianoMoreno,
      argentinaNeuquenProvinceNeuquen,
      argentinaNeuquenProvincePicunLeufu,
      argentinaNeuquenProvincePiedraDdelAguila,
      argentinaNeuquenProvincePlazaHuincul,
      argentinaNeuquenProvincePlottier,
      argentinaNeuquenProvinceSanMartinDdeLlosAndes,
      argentinaNeuquenProvinceSenillosa,
      argentinaNeuquenProvinceVillaLaAngostura,
      argentinaNeuquenProvinceVistaAlegre,
      argentinaNeuquenProvinceZapala
    ]);
const Region argentinaRioNegroProvince = Region(
    id: 3639,
    parentId: 11,
    longitude: -63.0266339,
    latitude: -40.8261434,
    name: "Río Negro Province",
    type: null,
    stateCode: "R",
    cities: [
      argentinaRioNegroProvinceAllen,
      argentinaRioNegroProvinceCatriel,
      argentinaRioNegroProvinceCervantes,
      argentinaRioNegroProvinceChichinales,
      argentinaRioNegroProvinceChimpay,
      argentinaRioNegroProvinceChoeleChoel,
      argentinaRioNegroProvinceCincoSaltos,
      argentinaRioNegroProvinceCipolletti,
      argentinaRioNegroProvinceComallo,
      argentinaRioNegroProvinceContraalmiranteCordero,
      argentinaRioNegroProvinceCoronelBelisle,
      argentinaRioNegroProvinceDarwin,
      argentinaRioNegroProvinceDepartamentoDdeAvellaneda,
      argentinaRioNegroProvinceDepartamentoDdeVeinticincoDdeMayo,
      argentinaRioNegroProvinceElBolson,
      argentinaRioNegroProvinceElCuy,
      argentinaRioNegroProvinceFrayLuisBeltran,
      argentinaRioNegroProvinceGeneralConesa,
      argentinaRioNegroProvinceGeneralEnriqueGodoy,
      argentinaRioNegroProvinceGeneralFernandezOro,
      argentinaRioNegroProvinceGeneralRoca,
      argentinaRioNegroProvinceIngenieroJacobacci,
      argentinaRioNegroProvinceIngenieroLuisADotHuergo,
      argentinaRioNegroProvinceLamarque,
      argentinaRioNegroProvinceLosMenucos,
      argentinaRioNegroProvinceMainque,
      argentinaRioNegroProvinceMaquinchao,
      argentinaRioNegroProvinceNorquinco,
      argentinaRioNegroProvincePilcaniyeu,
      argentinaRioNegroProvinceRioColorado,
      argentinaRioNegroProvinceSanAntonioOeste,
      argentinaRioNegroProvinceSanCarlosDdeBariloche,
      argentinaRioNegroProvinceSierraColorada,
      argentinaRioNegroProvinceSierraGrande,
      argentinaRioNegroProvinceValcheta,
      argentinaRioNegroProvinceViedma,
      argentinaRioNegroProvinceVillaRegina
    ]);
const Region argentinaSaltaProvince = Region(
    id: 3643,
    parentId: 11,
    longitude: -65.4150367,
    latitude: -24.7997688,
    name: "Salta Province",
    type: null,
    stateCode: "A",
    cities: [
      argentinaSaltaProvinceApolinarioSaravia,
      argentinaSaltaProvinceCachi,
      argentinaSaltaProvinceCafayate,
      argentinaSaltaProvinceCampoQuijano,
      argentinaSaltaProvinceChicoana,
      argentinaSaltaProvinceDepartamentoCapital,
      argentinaSaltaProvinceDepartamentoDdeAnta,
      argentinaSaltaProvinceDepartamentoDdeCerrillos,
      argentinaSaltaProvinceDepartamentoDdeChicoana,
      argentinaSaltaProvinceDepartamentoDdeGeneralGuemes,
      argentinaSaltaProvinceDepartamentoDdeGuachipas,
      argentinaSaltaProvinceDepartamentoDdeIruya,
      argentinaSaltaProvinceDepartamentoDdeLaPoma,
      argentinaSaltaProvinceDepartamentoDdeLaVina,
      argentinaSaltaProvinceDepartamentoDdeLosAndes,
      argentinaSaltaProvinceDepartamentoDdeMetan,
      argentinaSaltaProvinceDepartamentoDdeRivadavia,
      argentinaSaltaProvinceDepartamentoDdeRosarioDdeLlaFrontera,
      argentinaSaltaProvinceDepartamentoDdeRosarioDdeLerma,
      argentinaSaltaProvinceDepartamentoDdeSanCarlos,
      argentinaSaltaProvinceElCarril,
      argentinaSaltaProvinceElGalpon,
      argentinaSaltaProvinceElQuebrachal,
      argentinaSaltaProvinceEmbarcacion,
      argentinaSaltaProvinceGeneralEnriqueMosconi,
      argentinaSaltaProvinceJoaquinVDotGonzalez,
      argentinaSaltaProvinceLaCaldera,
      argentinaSaltaProvinceLasLajitas,
      argentinaSaltaProvinceSalta,
      argentinaSaltaProvinceSanAntonioDdeLlosCobres,
      argentinaSaltaProvinceSanRamonDdeLlaNuevaOran,
      argentinaSaltaProvinceSantaRosaDdeTastil,
      argentinaSaltaProvinceTartagal
    ]);
const Region argentinaSanJuanProvince = Region(
    id: 3634,
    parentId: 11,
    longitude: 1.7976931348623157e+308,
    latitude: 1.7976931348623157e+308,
    name: "San Juan Province",
    type: null,
    stateCode: "J",
    cities: [
      argentinaSanJuanProvinceAlbardon,
      argentinaSanJuanProvinceCalingasta,
      argentinaSanJuanProvinceCaucete,
      argentinaSanJuanProvinceChimbas,
      argentinaSanJuanProvinceDepartamentoDdeAlbardon,
      argentinaSanJuanProvinceDepartamentoDdeAngaco,
      argentinaSanJuanProvinceDepartamentoDdeCalingasta,
      argentinaSanJuanProvinceDepartamentoDdeCapital,
      argentinaSanJuanProvinceDepartamentoDdeCaucete,
      argentinaSanJuanProvinceDepartamentoDdeChimbas,
      argentinaSanJuanProvinceDepartamentoDdeIglesia,
      argentinaSanJuanProvinceDepartamentoDdeJachal,
      argentinaSanJuanProvinceDepartamentoDdeNueveDdeJulio,
      argentinaSanJuanProvinceDepartamentoDdeRawson,
      argentinaSanJuanProvinceDepartamentoDdeRivadavia,
      argentinaSanJuanProvinceDepartamentoDdeSanMartin,
      argentinaSanJuanProvinceDepartamentoDdeSantaLucia,
      argentinaSanJuanProvinceDepartamentoDdeSarmiento,
      argentinaSanJuanProvinceDepartamentoDdeUllum,
      argentinaSanJuanProvinceDepartamentoDdeZonda,
      argentinaSanJuanProvinceNueveDdeJulio,
      argentinaSanJuanProvincePocito,
      argentinaSanJuanProvinceSanAgustinDdeValleFertil,
      argentinaSanJuanProvinceSanJoseDdeJachal,
      argentinaSanJuanProvinceSanJuan,
      argentinaSanJuanProvinceSanMartin,
      argentinaSanJuanProvinceSantaLucia,
      argentinaSanJuanProvinceVillaBasilioNievas,
      argentinaSanJuanProvinceVillaPaulaDdeSarmiento
    ]);
const Region argentinaSanLuisProvince = Region(
    id: 3636,
    parentId: 11,
    longitude: -66.3294948,
    latitude: -33.2962042,
    name: "San Luis Province",
    type: null,
    stateCode: "D",
    cities: [
      argentinaSanLuisProvinceBuenaEsperanza,
      argentinaSanLuisProvinceCandelaria,
      argentinaSanLuisProvinceConcaran,
      argentinaSanLuisProvinceJuanMartinDdePueyrredon,
      argentinaSanLuisProvinceJustoDaract,
      argentinaSanLuisProvinceLaPunta,
      argentinaSanLuisProvinceLaToma,
      argentinaSanLuisProvinceLujan,
      argentinaSanLuisProvinceMerlo,
      argentinaSanLuisProvinceNaschel,
      argentinaSanLuisProvinceSanFranciscoDdelMonteDdeOro,
      argentinaSanLuisProvinceSanLuis,
      argentinaSanLuisProvinceSantaRosaDdelConlara,
      argentinaSanLuisProvinceTilisarao,
      argentinaSanLuisProvinceUnion,
      argentinaSanLuisProvinceVillaGeneralRoca,
      argentinaSanLuisProvinceVillaMercedes
    ]);
const Region argentinaSantaCruzProvince = Region(
    id: 3649,
    parentId: 11,
    longitude: -69.2474353,
    latitude: -51.6352821,
    name: "Santa Cruz Province",
    type: null,
    stateCode: "Z",
    cities: [
      argentinaSantaCruzProvince28DdeNoviembre,
      argentinaSantaCruzProvinceCaletaOlivia,
      argentinaSantaCruzProvinceComandanteLuisPiedraBuena,
      argentinaSantaCruzProvinceDepartamentoDdeDeseado,
      argentinaSantaCruzProvinceDepartamentoDdeGuerAike,
      argentinaSantaCruzProvinceDepartamentoDdeLagoArgentino,
      argentinaSantaCruzProvinceDepartamentoDdeMagallanes,
      argentinaSantaCruzProvinceDepartamentoDdeRioChico,
      argentinaSantaCruzProvinceElCalafate,
      argentinaSantaCruzProvinceGobernadorGregores,
      argentinaSantaCruzProvinceLasHeras,
      argentinaSantaCruzProvinceLosAntiguos,
      argentinaSantaCruzProvincePeritoMoreno,
      argentinaSantaCruzProvincePicoTruncado,
      argentinaSantaCruzProvincePuertoDeseado,
      argentinaSantaCruzProvincePuertoSantaCruz,
      argentinaSantaCruzProvinceRioGallegos,
      argentinaSantaCruzProvinceRioTurbio,
      argentinaSantaCruzProvinceSanJulian,
      argentinaSantaCruzProvinceYacimientoRioTurbio
    ]);
const Region argentinaSantaFeProvince = Region(
    id: 3641,
    parentId: 11,
    longitude: -60.7238016,
    latitude: -31.5855109,
    name: "Santa Fe Province",
    type: null,
    stateCode: "S",
    cities: [
      argentinaSantaFeProvinceArmstrong,
      argentinaSantaFeProvinceArroyoSeco,
      argentinaSantaFeProvinceArrufo,
      argentinaSantaFeProvinceAvellaneda,
      argentinaSantaFeProvinceBellaItalia,
      argentinaSantaFeProvinceCalchaqui,
      argentinaSantaFeProvinceCanadaDdeGomez,
      argentinaSantaFeProvinceCapitanBermudez,
      argentinaSantaFeProvinceCarcarana,
      argentinaSantaFeProvinceCasilda,
      argentinaSantaFeProvinceCeres,
      argentinaSantaFeProvinceChanarLadeado,
      argentinaSantaFeProvinceCoronda,
      argentinaSantaFeProvinceDepartamentoDdeBelgrano,
      argentinaSantaFeProvinceDepartamentoDdeCaseros,
      argentinaSantaFeProvinceDepartamentoDdeCastellanos,
      argentinaSantaFeProvinceDepartamentoDdeConstitucion,
      argentinaSantaFeProvinceDepartamentoDdeLaCapital,
      argentinaSantaFeProvinceDepartamentoDdeNueveDdeJulio,
      argentinaSantaFeProvinceDepartamentoDdeSanCristobal,
      argentinaSantaFeProvinceDepartamentoDdeSanJavier,
      argentinaSantaFeProvinceDepartamentoDdeSanJusto,
      argentinaSantaFeProvinceDepartamentoDdeSanLorenzo,
      argentinaSantaFeProvinceDepartamentoDdeSanMartin,
      argentinaSantaFeProvinceDepartamentoDdeVera,
      argentinaSantaFeProvinceElTrebol,
      argentinaSantaFeProvinceEsperanza,
      argentinaSantaFeProvinceFirmat,
      argentinaSantaFeProvinceFrayLuisADotBeltran,
      argentinaSantaFeProvinceFunes,
      argentinaSantaFeProvinceGalvez,
      argentinaSantaFeProvinceGatoColorado,
      argentinaSantaFeProvinceGobernadorGalvez,
      argentinaSantaFeProvinceGranaderoBaigorria,
      argentinaSantaFeProvinceHelvecia,
      argentinaSantaFeProvinceHersilia,
      argentinaSantaFeProvinceIriondoDepartment,
      argentinaSantaFeProvinceLagunaPaiva,
      argentinaSantaFeProvinceLasParejas,
      argentinaSantaFeProvinceLasRosas,
      argentinaSantaFeProvinceLasToscas,
      argentinaSantaFeProvinceLosLaureles,
      argentinaSantaFeProvinceMalabrigo,
      argentinaSantaFeProvinceMelincue,
      argentinaSantaFeProvincePerez,
      argentinaSantaFeProvinceRafaela,
      argentinaSantaFeProvinceReconquista,
      argentinaSantaFeProvinceRecreo,
      argentinaSantaFeProvinceRoldan,
      argentinaSantaFeProvinceRosario,
      argentinaSantaFeProvinceRufino,
      argentinaSantaFeProvinceSanCarlosCentro,
      argentinaSantaFeProvinceSanCristobal,
      argentinaSantaFeProvinceSanJavier,
      argentinaSantaFeProvinceSanJorge,
      argentinaSantaFeProvinceSanJusto,
      argentinaSantaFeProvinceSantaFe,
      argentinaSantaFeProvinceSantoTome,
      argentinaSantaFeProvinceSastre,
      argentinaSantaFeProvinceSunchales,
      argentinaSantaFeProvinceTacuarendi,
      argentinaSantaFeProvinceTostado,
      argentinaSantaFeProvinceTotoras,
      argentinaSantaFeProvinceVenadoTuerto,
      argentinaSantaFeProvinceVera,
      argentinaSantaFeProvinceVillaCanas,
      argentinaSantaFeProvinceVillaConstitucion,
      argentinaSantaFeProvinceVillaMugueta,
      argentinaSantaFeProvinceVillaOcampo,
      argentinaSantaFeProvinceVillaTrinidad
    ]);
const Region argentinaSantiagoDdelEsteroProvince = Region(
    id: 3635,
    parentId: 11,
    longitude: -64.264167,
    latitude: -27.7833574,
    name: "Santiago del Estero Province",
    type: null,
    stateCode: "G",
    cities: [
      argentinaSantiagoDdelEsteroProvinceAnatuya,
      argentinaSantiagoDdelEsteroProvinceBeltran,
      argentinaSantiagoDdelEsteroProvinceCampoGallo,
      argentinaSantiagoDdelEsteroProvinceClodomira,
      argentinaSantiagoDdelEsteroProvinceColoniaDora,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeAguirre,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeBanda,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeChoya,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeGuasayan,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeLoreto,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeMoreno,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeRioHondo,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeRobles,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeSanMartin,
      argentinaSantiagoDdelEsteroProvinceDepartamentoDdeSarmiento,
      argentinaSantiagoDdelEsteroProvinceElHoyo,
      argentinaSantiagoDdelEsteroProvinceLaBanda,
      argentinaSantiagoDdelEsteroProvinceLosJuries,
      argentinaSantiagoDdelEsteroProvinceLosTelares,
      argentinaSantiagoDdelEsteroProvincePampaDdeLlosGuanacos,
      argentinaSantiagoDdelEsteroProvinceQuimili,
      argentinaSantiagoDdelEsteroProvinceSanPedro,
      argentinaSantiagoDdelEsteroProvinceSantiagoDdelEstero,
      argentinaSantiagoDdelEsteroProvinceSumampa,
      argentinaSantiagoDdelEsteroProvinceSunchoCorral,
      argentinaSantiagoDdelEsteroProvinceTermasDdeRioHondo,
      argentinaSantiagoDdelEsteroProvinceTintina,
      argentinaSantiagoDdelEsteroProvinceVillaAtamisqui,
      argentinaSantiagoDdelEsteroProvinceVillaGeneralMitre,
      argentinaSantiagoDdelEsteroProvinceVillaOjoDdeAgua
    ]);
const Region argentinaTierraDdelFuegoProvince = Region(
    id: 3650,
    parentId: 11,
    longitude: -68.3242061,
    latitude: -54.8053998,
    name: "Tierra del Fuego Province",
    type: null,
    stateCode: "V",
    cities: [
      argentinaTierraDdelFuegoProvinceRioGrande,
      argentinaTierraDdelFuegoProvinceTolhuin,
      argentinaTierraDdelFuegoProvinceUshuaia
    ]);
const Region argentinaTucumanProvince = Region(
    id: 3637,
    parentId: 11,
    longitude: -65.2192903,
    latitude: -26.8221127,
    name: "Tucumán Province",
    type: null,
    stateCode: "T",
    cities: [
      argentinaTucumanProvinceAguilares,
      argentinaTucumanProvinceAlderetes,
      argentinaTucumanProvinceBellaVista,
      argentinaTucumanProvinceBurruyacu,
      argentinaTucumanProvinceDepartamentoDdeBurruyacu,
      argentinaTucumanProvinceDepartamentoDdeCapital,
      argentinaTucumanProvinceDepartamentoDdeCruzAlta,
      argentinaTucumanProvinceDepartamentoDdeFamailla,
      argentinaTucumanProvinceDepartamentoDdeGraneros,
      argentinaTucumanProvinceDepartamentoDdeLaCocha,
      argentinaTucumanProvinceDepartamentoDdeLules,
      argentinaTucumanProvinceDepartamentoDdeMonteros,
      argentinaTucumanProvinceDepartamentoDdeRioChico,
      argentinaTucumanProvinceDepartamentoDdeSimoca,
      argentinaTucumanProvinceDepartamentoDdeTrancas,
      argentinaTucumanProvinceDepartamentoDdeYerbaBuena,
      argentinaTucumanProvinceFamailla,
      argentinaTucumanProvinceGraneros,
      argentinaTucumanProvinceLaCocha,
      argentinaTucumanProvinceMonteros,
      argentinaTucumanProvinceSanMiguelDdeTucuman,
      argentinaTucumanProvinceSimoca,
      argentinaTucumanProvinceTafiDdelValle,
      argentinaTucumanProvinceTafiViejo,
      argentinaTucumanProvinceTrancas,
      argentinaTucumanProvinceYerbaBuena
    ]);

const argentinaStates = <int, Region>{
  4880: argentinaAutonomousCityOfBuenosAires,
  3656: argentinaBuenosAiresProvince,
  3647: argentinaCatamarcaProvince,
  3640: argentinaChacoProvince,
  3651: argentinaChubutProvince,
  3642: argentinaCordobaProvince,
  3638: argentinaCorrientes,
  3654: argentinaEntreRiosProvince,
  3652: argentinaFormosaProvince,
  3645: argentinaJujuyProvince,
  3655: argentinaLaPampa,
  3653: argentinaLaRiojaProvince,
  3646: argentinaMendoza,
  3644: argentinaMisionesProvince,
  3648: argentinaNeuquenProvince,
  3639: argentinaRioNegroProvince,
  3643: argentinaSaltaProvince,
  3634: argentinaSanJuanProvince,
  3636: argentinaSanLuisProvince,
  3649: argentinaSantaCruzProvince,
  3641: argentinaSantaFeProvince,
  3635: argentinaSantiagoDdelEsteroProvince,
  3650: argentinaTierraDdelFuegoProvince,
  3637: argentinaTucumanProvince
};
