/// Access to known geographies in `Argentina` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.
library;

import '../base.dart';
import 'argentina_cities.dart';

/// The `Buenos Aires` region in `Argentina`
const Region argentinaBuenosAiresProvince = Region(
  id: 3656,
  parentId: 11,
  longitude: -59.8410697,
  latitude: -37.2017285,
  name: "Buenos Aires",
  type: "province",
  stateCode: "B",
  cities: [
    buenosAiresProvinceBalvaneraCity,
    buenosAiresProvinceBarracasCity,
    buenosAiresProvinceBelgranoCity,
    buenosAiresProvinceBoedoCity,
    buenosAiresProvinceBuenosAiresCity,
    buenosAiresProvinceColegialesCity,
    buenosAiresProvinceRetiroCity,
    buenosAiresProvinceVillaLuganoCity,
    buenosAiresProvinceVillaOrtuzarCity,
    buenosAiresProvinceVillaSantaRitaCity
  ]);

/// The `Catamarca` region in `Argentina`
const Region argentinaCatamarcaProvince = Region(
  id: 3647,
  parentId: 11,
  longitude: -65.7877209,
  latitude: -28.4715877,
  name: "Catamarca",
  type: "province",
  stateCode: "K",
  cities: [
    catamarcaProvinceAncastiCity,
    catamarcaProvinceAndalgalaCity,
    catamarcaProvinceAntofagastaDeLaSierraCity,
    catamarcaProvinceCapayanCity,
    catamarcaProvinceDepartamentoDeAmbatoCity,
    catamarcaProvinceDepartamentoDeAncastiCity,
    catamarcaProvinceDepartamentoDeAndalgalaCity,
    catamarcaProvinceDepartamentoDeAntofagastaDeLaSierraCity,
    catamarcaProvinceDepartamentoDeCapayanCity,
    catamarcaProvinceDepartamentoDeCapitalCity,
    catamarcaProvinceDepartamentoDeElAltoCity,
    catamarcaProvinceDepartamentoDeFrayMamertoEsquiuCity,
    catamarcaProvinceDepartamentoDeLaPazCity,
    catamarcaProvinceDepartamentoDePomanCity,
    catamarcaProvinceDepartamentoDeSantaMariaCity,
    catamarcaProvinceDepartamentoDeSantaRosaCity,
    catamarcaProvinceDepartamentoDeTinogastaCity,
    catamarcaProvinceDepartamentoDeValleViejoCity,
    catamarcaProvinceElRodeoCity,
    catamarcaProvinceFiambalaCity,
    catamarcaProvinceHualfinCity,
    catamarcaProvinceHuillapimaCity,
    catamarcaProvinceIcanoCity,
    catamarcaProvinceLaPuertaDeSanJoseCity,
    catamarcaProvinceLondresCity,
    catamarcaProvinceLosAltosCity,
    catamarcaProvinceLosVarelaCity,
    catamarcaProvinceMutquinCity,
    catamarcaProvincePomanCity,
    catamarcaProvincePuertaDeCorralQuemadoCity,
    catamarcaProvinceRecreoCity,
    catamarcaProvinceSanAntonioCity,
    catamarcaProvinceSanFernandoDelValleDeCatamarcaCity,
    catamarcaProvinceSantaMariaCity,
    catamarcaProvinceTinogastaCity
  ]);

/// The `Chaco` region in `Argentina`
const Region argentinaChacoProvince = Region(
  id: 3640,
  parentId: 11,
  longitude: -59.0243784,
  latitude: -27.4257175,
  name: "Chaco",
  type: "province",
  stateCode: "H",
  cities: [
    chacoProvinceAviaTeraiCity,
    chacoProvinceBarranquerasCity,
    chacoProvinceBasailCity,
    chacoProvinceCampoLargoCity,
    chacoProvinceCapitanSolariCity,
    chacoProvinceCastelliCity,
    chacoProvinceCharadaiCity,
    chacoProvinceCharataCity,
    chacoProvinceChorotisCity,
    chacoProvinceCiervoPetisoCity,
    chacoProvinceColoniaBenitezCity,
    chacoProvinceColoniaElisaCity,
    chacoProvinceColoniasUnidasCity,
    chacoProvinceConcepcionDelBermejoCity,
    chacoProvinceCoronelDuGratyCity,
    chacoProvinceCorzuelaCity,
    chacoProvinceCoteHyplaiCity,
    chacoProvinceDepartamentoDeAlmiranteBrownCity,
    chacoProvinceDepartamentoDeBermejoCity,
    chacoProvinceDepartamentoDeComandanteFernandezCity,
    chacoProvinceDepartamentoDeDoceDeOctubreCity,
    chacoProvinceDepartamentoDeDosDeAbrilCity,
    chacoProvinceDepartamentoDeGeneralDonovanCity,
    chacoProvinceDepartamentoDeGeneralGuemesCity,
    chacoProvinceDepartamentoDeIndependenciaCity,
    chacoProvinceDepartamentoDeLibertadCity,
    chacoProvinceDepartamentoDeMaipuCity,
    chacoProvinceDepartamentoDeNueveDeJulioCity,
    chacoProvinceDepartamentoDeOhigginsCity,
    chacoProvinceDepartamentoDePresidenciaDeLaPlazaCity,
    chacoProvinceDepartamentoDeQuitilipiCity,
    chacoProvinceDepartamentoDeSanFernandoCity,
    chacoProvinceDepartamentoDeSanLorenzoCity,
    chacoProvinceDepartamentoDeSargentoCabralCity,
    chacoProvinceDepartamentoDeTapenagaCity,
    chacoProvinceFontanaCity,
    chacoProvinceGancedoCity,
    chacoProvinceGeneralJoseDeSanMartinCity,
    chacoProvinceGeneralPinedoCity,
    chacoProvinceGeneralVediaCity,
    chacoProvinceHermosoCampoCity,
    chacoProvinceLaClotildeCity,
    chacoProvinceLaEduvigisCity,
    chacoProvinceLaEscondidaCity,
    chacoProvinceLaLeonesaCity,
    chacoProvinceLaTigraCity,
    chacoProvinceLaVerdeCity,
    chacoProvinceLagunaLimpiaCity,
    chacoProvinceLapachitoCity,
    chacoProvinceLasBrenasCity,
    chacoProvinceLasGarcitasCity,
    chacoProvinceLosFrentonesCity,
    chacoProvinceMachagaiCity,
    chacoProvinceMakalleCity,
    chacoProvinceMargaritaBelenCity,
    chacoProvinceNapenayCity,
    chacoProvincePampaAlmironCity,
    chacoProvincePampaDelIndioCity,
    chacoProvincePampaDelInfiernoCity,
    chacoProvincePresidenciaDeLaPlazaCity,
    chacoProvincePresidenciaRocaCity,
    chacoProvincePresidenciaRoqueSaenzPenaCity,
    chacoProvincePuertoBermejoCity,
    chacoProvincePuertoTirolCity,
    chacoProvincePuertoVilelasCity,
    chacoProvinceQuitilipiCity,
    chacoProvinceResistenciaCity,
    chacoProvinceSamuhuCity,
    chacoProvinceSanBernardoCity,
    chacoProvinceSantaSylvinaCity,
    chacoProvinceTacoPozoCity,
    chacoProvinceTresIsletasCity,
    chacoProvinceVillaAngelaCity,
    chacoProvinceVillaBerthetCity
  ]);

/// The `Chubut` region in `Argentina`
const Region argentinaChubutProvince = Region(
  id: 3651,
  parentId: 11,
  longitude: -65.1114818,
  latitude: -43.2934246,
  name: "Chubut",
  type: "province",
  stateCode: "U",
  cities: [
    chubutProvinceAltoRioSenguerCity,
    chubutProvinceCamaronesCity,
    chubutProvinceComodoroRivadaviaCity,
    chubutProvinceDepartamentoDeBiedmaCity,
    chubutProvinceDepartamentoDeCushamenCity,
    chubutProvinceDepartamentoDeEscalanteCity,
    chubutProvinceDepartamentoDeFlorentinoAmeghinoCity,
    chubutProvinceDepartamentoDeFutaleufuCity,
    chubutProvinceDepartamentoDeGaimanCity,
    chubutProvinceDepartamentoDeGastreCity,
    chubutProvinceDepartamentoDeLanguineoCity,
    chubutProvinceDepartamentoDeMartiresCity,
    chubutProvinceDepartamentoDePasoDeIndiosCity,
    chubutProvinceDepartamentoDeRawsonCity,
    chubutProvinceDepartamentoDeRioSenguerrCity,
    chubutProvinceDepartamentoDeSarmientoCity,
    chubutProvinceDepartamentoDeTehuelchesCity,
    chubutProvinceDepartamentoDeTelsenCity,
    chubutProvinceDolavonCity,
    chubutProvinceElMaitenCity,
    chubutProvinceEsquelCity,
    chubutProvinceGaimanCity,
    chubutProvinceGastreCity,
    chubutProvinceGobernadorCostaCity,
    chubutProvinceHoyoDeEpuyenCity,
    chubutProvinceJoseDeSanMartinCity,
    chubutProvinceLagoPueloCity,
    chubutProvinceLasPlumasCity,
    chubutProvincePuertoMadrynCity,
    chubutProvinceRadaTillyCity,
    chubutProvinceRawsonCity,
    chubutProvinceRioMayoCity,
    chubutProvinceRioPicoCity,
    chubutProvinceSarmientoCity,
    chubutProvinceTeckaCity,
    chubutProvinceTrelewCity,
    chubutProvinceTrevelinCity
  ]);

/// The `Ciudad Autónoma de Buenos Aires` region in `Argentina`
const Region argentinaCiudadAutonomaDeBuenosAiresCity = Region(
  id: 4880,
  parentId: 11,
  longitude: -58.3815591,
  latitude: -34.6036844,
  name: "Ciudad Autónoma de Buenos Aires",
  type: "city",
  stateCode: "C",
  cities: []);

/// The `Córdoba` region in `Argentina`
const Region argentinaCordobaProvince = Region(
  id: 3642,
  parentId: 11,
  longitude: -64.2643842,
  latitude: -31.3992876,
  name: "Córdoba",
  type: "province",
  stateCode: "X",
  cities: [
    cordobaProvinceAchirasCity,
    cordobaProvinceAdeliaMariaCity,
    cordobaProvinceAguaDeOroCity,
    cordobaProvinceAlejandroRocaCity,
    cordobaProvinceAlejoLedesmaCity,
    cordobaProvinceAlmafuerteCity,
    cordobaProvinceAltaGraciaCity,
    cordobaProvinceAltosDeChipionCity,
    cordobaProvinceAriasCity,
    cordobaProvinceArroyitoCity,
    cordobaProvinceArroyoCabralCity,
    cordobaProvinceBalneariaCity,
    cordobaProvinceBellVilleCity,
    cordobaProvinceBerrotaranCity,
    cordobaProvinceBrinkmannCity,
    cordobaProvinceBuchardoCity,
    cordobaProvinceCamiloAldaoCity,
    cordobaProvinceCanadaDeLuqueCity,
    cordobaProvinceCanalsCity,
    cordobaProvinceCapillaDelMonteCity,
    cordobaProvinceCarnerilloCity,
    cordobaProvinceCarriloboCity,
    cordobaProvinceCavanaghCity,
    cordobaProvinceCharrasCity,
    cordobaProvinceChazonCity,
    cordobaProvinceCintraCity,
    cordobaProvinceColoniaLaTordillaCity,
    cordobaProvinceColoniaSanBartolomeCity,
    cordobaProvinceCordobaCity,
    cordobaProvinceCoronelBaigorriaCity,
    cordobaProvinceCoronelMoldesCity,
    cordobaProvinceCorralDeBustosCity,
    cordobaProvinceCorralitoCity,
    cordobaProvinceCosquinCity,
    cordobaProvinceCostaSacateCity,
    cordobaProvinceCruzAltaCity,
    cordobaProvinceCruzDelEjeCity,
    cordobaProvinceCuestaBlancaCity,
    cordobaProvinceDalmacioVelezSarsfieldCity,
    cordobaProvinceDeanFunesCity,
    cordobaProvinceDelCampilloCity,
    cordobaProvinceDepartamentoDeCalamuchitaCity,
    cordobaProvinceDepartamentoDeColonCity,
    cordobaProvinceDepartamentoDeCruzDelEjeCity,
    cordobaProvinceDepartamentoDeGeneralRocaCity,
    cordobaProvinceDepartamentoDeGeneralSanMartinCity,
    cordobaProvinceDepartamentoDeJuarezCelmanCity,
    cordobaProvinceDepartamentoDeMarcosJuarezCity,
    cordobaProvinceDepartamentoDeMinasCity,
    cordobaProvinceDepartamentoDePresidenteRoqueSaenzPenaCity,
    cordobaProvinceDepartamentoDeRioCuartoCity,
    cordobaProvinceDepartamentoDeRioPrimeroCity,
    cordobaProvinceDepartamentoDeRioSecoCity,
    cordobaProvinceDepartamentoDeRioSegundoCity,
    cordobaProvinceDepartamentoDeSanAlbertoCity,
    cordobaProvinceDepartamentoDeSanJavierCity,
    cordobaProvinceDepartamentoDeSanJustoCity,
    cordobaProvinceDepartamentoDeSobremonteCity,
    cordobaProvinceDepartamentoDeTotoralCity,
    cordobaProvinceDepartamentoDeTulumbaCity,
    cordobaProvinceDepartamentoDeUnionCity,
    cordobaProvinceDespenaderosCity,
    cordobaProvinceDevotoCity,
    cordobaProvinceElAranadoCity,
    cordobaProvinceElTioCity,
    cordobaProvinceElenaCity,
    cordobaProvinceEmbalseCity,
    cordobaProvinceEtruriaCity,
    cordobaProvinceGeneralBaldisseraCity,
    cordobaProvinceGeneralCabreraCity,
    cordobaProvinceGeneralLevalleCity,
    cordobaProvinceGeneralRocaCity,
    cordobaProvinceGuatimozinCity,
    cordobaProvinceHernandoCity,
    cordobaProvinceHuanchillasCity,
    cordobaProvinceHuertaGrandeCity,
    cordobaProvinceHuincaRenancoCity,
    cordobaProvinceIdiazabalCity,
    cordobaProvinceInrivilleCity,
    cordobaProvinceIslaVerdeCity,
    cordobaProvinceItaloCity,
    cordobaProvinceJamesCraikCity,
    cordobaProvinceJesusMariaCity,
    cordobaProvinceJustinianoPosseCity,
    cordobaProvinceLaCaleraCity,
    cordobaProvinceLaCarlotaCity,
    cordobaProvinceLaCesiraCity,
    cordobaProvinceLaCumbreCity,
    cordobaProvinceLaFaldaCity,
    cordobaProvinceLaFranciaCity,
    cordobaProvinceLaGranjaCity,
    cordobaProvinceLaParaCity,
    cordobaProvinceLaPlayosaCity,
    cordobaProvinceLabordeCity,
    cordobaProvinceLaboulayeCity,
    cordobaProvinceLagunaLargaCity,
    cordobaProvinceLasAcequiasCity,
    cordobaProvinceLasHiguerasCity,
    cordobaProvinceLasJunturasCity,
    cordobaProvinceLasPerdicesCity,
    cordobaProvinceLasVarasCity,
    cordobaProvinceLasVarillasCity,
    cordobaProvinceLeonesCity,
    cordobaProvinceLosCocosCity,
    cordobaProvinceLosCondoresCity,
    cordobaProvinceLosSurgentesCity,
    cordobaProvinceMalaguenoCity,
    cordobaProvinceMalvinasArgentinasCity,
    cordobaProvinceMarcosJuarezCity,
    cordobaProvinceMarullCity,
    cordobaProvinceMattaldiCity,
    cordobaProvinceMendiolazaCity,
    cordobaProvinceMinaClaveroCity,
    cordobaProvinceMiramarCity,
    cordobaProvinceMonteBueyCity,
    cordobaProvinceMonteCristoCity,
    cordobaProvinceMonteMaizCity,
    cordobaProvinceMorrisonCity,
    cordobaProvinceMorterosCity,
    cordobaProvinceNoetingerCity,
    cordobaProvinceObispoTrejoCity,
    cordobaProvinceOlivaCity,
    cordobaProvinceOncativoCity,
    cordobaProvinceOrdonezCity,
    cordobaProvincePascanasCity,
    cordobaProvincePascoCity,
    cordobaProvincePilarCity,
    cordobaProvincePiquillinCity,
    cordobaProvincePortenaCity,
    cordobaProvincePozoDelMolleCity,
    cordobaProvinceQuilinoCity,
    cordobaProvinceRioCeballosCity,
    cordobaProvinceRioCuartoCity,
    cordobaProvinceRioSegundoCity,
    cordobaProvinceRioTerceroCity,
    cordobaProvinceSacantaCity,
    cordobaProvinceSaldanCity,
    cordobaProvinceSalsacateCity,
    cordobaProvinceSalsipuedesCity,
    cordobaProvinceSampachoCity,
    cordobaProvinceSanAgustinCity,
    cordobaProvinceSanAntonioDeLitinCity,
    cordobaProvinceSanBasilioCity,
    cordobaProvinceSanCarlosCity,
    cordobaProvinceSanFranciscoCity,
    cordobaProvinceSanFranciscoDelChanarCity,
    cordobaProvinceSanJoseDeLaDormidaCity,
    cordobaProvinceSantaEufemiaCity,
    cordobaProvinceSantaMagdalenaCity,
    cordobaProvinceSantaRosaDeCalamuchitaCity,
    cordobaProvinceSantaRosaDeRioPrimeroCity,
    cordobaProvinceSantiagoTempleCity,
    cordobaProvinceSaturninoMLaspiurCity,
    cordobaProvinceSebastianElcanoCity,
    cordobaProvinceSerranoCity,
    cordobaProvinceSerrezuelaCity,
    cordobaProvinceTancachaCity,
    cordobaProvinceTicinoCity,
    cordobaProvinceTioPujioCity,
    cordobaProvinceToledoCity,
    cordobaProvinceUcachaCity,
    cordobaProvinceUnquilloCity,
    cordobaProvinceValleHermosoCity,
    cordobaProvinceViamonteCity,
    cordobaProvinceVicunaMackennaCity,
    cordobaProvinceVillaAllendeCity,
    cordobaProvinceVillaAscasubiCity,
    cordobaProvinceVillaBernaCity,
    cordobaProvinceVillaCarlosPazCity,
    cordobaProvinceVillaConcepcionDelTioCity,
    cordobaProvinceVillaCuraBrocheroCity,
    cordobaProvinceVillaDeSotoCity,
    cordobaProvinceVillaDelDiqueCity,
    cordobaProvinceVillaDelRosarioCity,
    cordobaProvinceVillaDelTotoralCity,
    cordobaProvinceVillaDoloresCity,
    cordobaProvinceVillaGeneralBelgranoCity,
    cordobaProvinceVillaGiardinoCity,
    cordobaProvinceVillaHuidobroCity,
    cordobaProvinceVillaLasRosasCity,
    cordobaProvinceVillaMariaCity,
    cordobaProvinceVillaNuevaCity,
    cordobaProvinceVillaReduccionCity,
    cordobaProvinceVillaRumipalCity,
    cordobaProvinceVillaTulumbaCity,
    cordobaProvinceVillaValeriaCity,
    cordobaProvinceWenceslaoEscalanteCity
  ]);

/// The `Corrientes` region in `Argentina`
const Region argentinaCorrientesProvince = Region(
  id: 3638,
  parentId: 11,
  longitude: -58.8306349,
  latitude: -27.4692131,
  name: "Corrientes",
  type: "province",
  stateCode: "W",
  cities: [
    corrientesProvinceAlvearCity,
    corrientesProvinceBeronDeAstradaCity,
    corrientesProvinceBonplandCity,
    corrientesProvinceChavarriaCity,
    corrientesProvinceConcepcionCity,
    corrientesProvinceCorrientesCity,
    corrientesProvinceCruzDeLosMilagrosCity,
    corrientesProvinceCuruzuCuatiaCity,
    corrientesProvinceDepartamentoDeBellaVistaCity,
    corrientesProvinceDepartamentoDeBeronDeAstradaCity,
    corrientesProvinceDepartamentoDeCapitalCity,
    corrientesProvinceDepartamentoDeConcepcionCity,
    corrientesProvinceDepartamentoDeCuruzuCuatiaCity,
    corrientesProvinceDepartamentoDeEmpedradoCity,
    corrientesProvinceDepartamentoDeEsquinaCity,
    corrientesProvinceDepartamentoDeGeneralAlvearCity,
    corrientesProvinceDepartamentoDeGeneralPazCity,
    corrientesProvinceDepartamentoDeGoyaCity,
    corrientesProvinceDepartamentoDeItatiCity,
    corrientesProvinceDepartamentoDeItuzaingoCity,
    corrientesProvinceDepartamentoDeLavalleCity,
    corrientesProvinceDepartamentoDeMburucuyaCity,
    corrientesProvinceDepartamentoDeMercedesCity,
    corrientesProvinceDepartamentoDeMonteCaserosCity,
    corrientesProvinceDepartamentoDePasoDeLosLibresCity,
    corrientesProvinceDepartamentoDeSaladasCity,
    corrientesProvinceDepartamentoDeSanCosmeCity,
    corrientesProvinceDepartamentoDeSanLuisDelPalmarCity,
    corrientesProvinceDepartamentoDeSanMartinCity,
    corrientesProvinceDepartamentoDeSanMiguelCity,
    corrientesProvinceDepartamentoDeSanRoqueCity,
    corrientesProvinceDepartamentoDeSantoTomeCity,
    corrientesProvinceDepartamentoDeSauceCity,
    corrientesProvinceEmpedradoCity,
    corrientesProvinceEsquinaCity,
    corrientesProvinceFelipeYofreCity,
    corrientesProvinceGarruchosCity,
    corrientesProvinceGobernadorJuanEMartinezCity,
    corrientesProvinceGobernadorVirasoraCity,
    corrientesProvinceGoyaCity,
    corrientesProvinceHerlitzkaCity,
    corrientesProvinceItaIbateCity,
    corrientesProvinceItatiCity,
    corrientesProvinceItuzaingoCity,
    corrientesProvinceJuanPujolCity,
    corrientesProvinceLaCruzCity,
    corrientesProvinceLibertadCity,
    corrientesProvinceLomasDeVallejosCity,
    corrientesProvinceLoretoCity,
    corrientesProvinceMarianoILozaCity,
    corrientesProvinceMburucuyaCity,
    corrientesProvinceMercedesCity,
    corrientesProvinceMocoretaCity,
    corrientesProvinceMonteCaserosCity,
    corrientesProvinceNuestraSenoraDelRosarioDeCaaCatiCity,
    corrientesProvinceNueveDeJulioCity,
    corrientesProvincePalmarGrandeCity,
    corrientesProvincePasoDeLaPatriaCity,
    corrientesProvincePasoDeLosLibresCity,
    corrientesProvincePedroRFernandezCity,
    corrientesProvincePerugorriaCity,
    corrientesProvincePuebloLibertadorCity,
    corrientesProvinceRiachueloCity,
    corrientesProvinceSaladasCity,
    corrientesProvinceSanCarlosCity,
    corrientesProvinceSanCosmeCity,
    corrientesProvinceSanLorenzoCity,
    corrientesProvinceSanLuisDelPalmarCity,
    corrientesProvinceSanMiguelCity,
    corrientesProvinceSantaLuciaCity,
    corrientesProvinceSantaRosaCity,
    corrientesProvinceSantoTomeCity,
    corrientesProvinceYapeyuCity,
    corrientesProvinceYataityCalleCity
  ]);

/// The `Entre Ríos` region in `Argentina`
const Region argentinaEntreRiosProvince = Region(
  id: 3654,
  parentId: 11,
  longitude: -60.4956461,
  latitude: -31.7746654,
  name: "Entre Ríos",
  type: "province",
  stateCode: "E",
  cities: [
    entreRiosProvinceAldeaSanAntonioCity,
    entreRiosProvinceArangurenCity,
    entreRiosProvinceBovrilCity,
    entreRiosProvinceCaserosCity,
    entreRiosProvinceCeibasCity,
    entreRiosProvinceChajariCity,
    entreRiosProvinceColonCity,
    entreRiosProvinceColoniaEliaCity,
    entreRiosProvinceConcepcionDelUruguayCity,
    entreRiosProvinceConcordiaCity,
    entreRiosProvinceConscriptoBernardiCity,
    entreRiosProvinceCrespoCity,
    entreRiosProvinceDepartamentoDeGualeguaychuCity,
    entreRiosProvinceDepartamentoDeParanaCity,
    entreRiosProvinceDiamanteCity,
    entreRiosProvinceDominguezCity,
    entreRiosProvinceFederacionCity,
    entreRiosProvinceFederalCity,
    entreRiosProvinceGeneralCamposCity,
    entreRiosProvinceGeneralGalarzaCity,
    entreRiosProvinceGeneralRamirezCity,
    entreRiosProvinceGobernadorMansillaCity,
    entreRiosProvinceGualeguayCity,
    entreRiosProvinceGualeguaychuCity,
    entreRiosProvinceHasenkampCity,
    entreRiosProvinceHernandezCity,
    entreRiosProvinceHerreraCity,
    entreRiosProvinceLaCriollaCity,
    entreRiosProvinceLaPazCity,
    entreRiosProvinceLarroqueCity,
    entreRiosProvinceLosCharruasCity,
    entreRiosProvinceLosConquistadoresCity,
    entreRiosProvinceLucasGonzalezCity,
    entreRiosProvinceMaciaCity,
    entreRiosProvinceNogoyaCity,
    entreRiosProvinceOroVerdeCity,
    entreRiosProvinceParanaCity,
    entreRiosProvincePiedrasBlancasCity,
    entreRiosProvincePronunciamientoCity,
    entreRiosProvincePuertoIbicuyCity,
    entreRiosProvincePuertoYeruaCity,
    entreRiosProvinceRosarioDelTalaCity,
    entreRiosProvinceSanBenitoCity,
    entreRiosProvinceSanGustavoCity,
    entreRiosProvinceSanJoseDeFelicianoCity,
    entreRiosProvinceSanJustoCity,
    entreRiosProvinceSanSalvadorCity,
    entreRiosProvinceSantaAnaCity,
    entreRiosProvinceSantaAnitaCity,
    entreRiosProvinceSantaElenaCity,
    entreRiosProvinceSauceDeLunaCity,
    entreRiosProvinceSeguiCity,
    entreRiosProvinceTabossiCity,
    entreRiosProvinceUbajayCity,
    entreRiosProvinceUrdinarrainCity,
    entreRiosProvinceVialeCity,
    entreRiosProvinceVictoriaCity,
    entreRiosProvinceVillaDelRosarioCity,
    entreRiosProvinceVillaElisaCity,
    entreRiosProvinceVillaHernandariasCity,
    entreRiosProvinceVillaManteroCity,
    entreRiosProvinceVillaMariaGrandeCity,
    entreRiosProvinceVillaParanacitoCity,
    entreRiosProvinceVillaUrquizaCity,
    entreRiosProvinceVillaguayCity
  ]);

/// The `Formosa` region in `Argentina`
const Region argentinaFormosaProvince = Region(
  id: 3652,
  parentId: 11,
  longitude: -58.2242806,
  latitude: -26.1894804,
  name: "Formosa",
  type: "province",
  stateCode: "P",
  cities: [
    formosaProvinceClorindaCity,
    formosaProvinceComandanteFontanaCity,
    formosaProvinceDepartamentoDePilcomayoCity,
    formosaProvinceElColoradoCity,
    formosaProvinceEstanislaoDelCampoCity,
    formosaProvinceFormosaCity,
    formosaProvinceGeneralEnriqueMosconiCity,
    formosaProvinceHerraduraCity,
    formosaProvinceIbarretaCity,
    formosaProvinceIngenieroGuillermoNJuarezCity,
    formosaProvinceLagunaNaickHypneckCity,
    formosaProvinceLagunaYemaCity,
    formosaProvinceLasLomitasCity,
    formosaProvincePaloSantoCity,
    formosaProvincePiraneCity,
    formosaProvincePozoDelTigreCity,
    formosaProvinceRiachoEhHypehCity,
    formosaProvinceSanFranciscoDeLaishiCity,
    formosaProvinceVillaEscolarCity,
    formosaProvinceVillaGeneralGuemesCity
  ]);

/// The `Jujuy` region in `Argentina`
const Region argentinaJujuyProvince = Region(
  id: 3645,
  parentId: 11,
  longitude: -65.302177,
  latitude: -24.1843397,
  name: "Jujuy",
  type: "province",
  stateCode: "Y",
  cities: [
    jujuyProvinceAbraPampaCity,
    jujuyProvinceCaimancitoCity,
    jujuyProvinceCalileguaCity,
    jujuyProvinceDepartamentoDeCochinocaCity,
    jujuyProvinceDepartamentoDeRinconadaCity,
    jujuyProvinceDepartamentoDeTumbayaCity,
    jujuyProvinceElAguilarCity,
    jujuyProvinceFrailePintadoCity,
    jujuyProvinceHumahuacaCity,
    jujuyProvinceIngenioLaEsperanzaCity,
    jujuyProvinceLaMendietaCity,
    jujuyProvinceLaQuiacaCity,
    jujuyProvinceLibertadorGeneralSanMartinCity,
    jujuyProvinceMaimaraCity,
    jujuyProvincePalmaSolaCity,
    jujuyProvincePalpalaCity,
    jujuyProvinceSanPedroDeJujuyCity,
    jujuyProvinceSanSalvadorDeJujuyCity,
    jujuyProvinceSantaClaraCity,
    jujuyProvinceTilcaraCity,
    jujuyProvinceYutoCity
  ]);

/// The `La Pampa` region in `Argentina`
const Region argentinaLaPampaProvince = Region(
  id: 3655,
  parentId: 11,
  longitude: -64.2839209,
  latitude: -36.6147573,
  name: "La Pampa",
  type: "province",
  stateCode: "L",
  cities: [
    laPampaProvinceAlpachiriCity,
    laPampaProvinceAltaItaliaCity,
    laPampaProvinceAnguilCity,
    laPampaProvinceArataCity,
    laPampaProvinceBernardoLarroudeCity,
    laPampaProvinceBernasconiCity,
    laPampaProvinceCaleufuCity,
    laPampaProvinceCatriloCity,
    laPampaProvinceColoniaBaronCity,
    laPampaProvinceDepartamentoDeCaleuHypcaleuCity,
    laPampaProvinceDepartamentoDeToayCity,
    laPampaProvinceDoblasCity,
    laPampaProvinceEduardoCastexCity,
    laPampaProvinceEmbajadorMartiniCity,
    laPampaProvinceGeneralAchaCity,
    laPampaProvinceGeneralManuelJCamposCity,
    laPampaProvinceGeneralPicoCity,
    laPampaProvinceGeneralSanMartinCity,
    laPampaProvinceGuatracheCity,
    laPampaProvinceIngenieroLuiggiCity,
    laPampaProvinceIntendenteAlvearCity,
    laPampaProvinceJacintoArauzCity,
    laPampaProvinceLaAdelaCity,
    laPampaProvinceLaMarujaCity,
    laPampaProvinceLonquimayCity,
    laPampaProvinceMacachinCity,
    laPampaProvinceMiguelRiglosCity,
    laPampaProvincePareraCity,
    laPampaProvinceQuemuQuemuCity,
    laPampaProvinceRanculCity,
    laPampaProvinceRealicoCity,
    laPampaProvinceSantaIsabelCity,
    laPampaProvinceSantaRosaCity,
    laPampaProvinceTelenCity,
    laPampaProvinceTrenelCity,
    laPampaProvinceUriburuCity,
    laPampaProvinceVeinticincoDeMayoCity,
    laPampaProvinceVictoricaCity,
    laPampaProvinceWinifredaCity
  ]);

/// The `La Rioja` region in `Argentina`
const Region argentinaLaRiojaProvince = Region(
  id: 3653,
  parentId: 11,
  longitude: -66.8559932,
  latitude: -29.4193793,
  name: "La Rioja",
  type: "province",
  stateCode: "F",
  cities: [
    laRiojaProvinceAraucoCity,
    laRiojaProvinceCastroBarrosCity,
    laRiojaProvinceChamicalCity,
    laRiojaProvinceChilecitoCity,
    laRiojaProvinceDepartamentoDeAraucoCity,
    laRiojaProvinceDepartamentoDeGeneralLamadridCity,
    laRiojaProvinceDepartamentoDeIndependenciaCity,
    laRiojaProvinceLaRiojaCity,
    laRiojaProvinceVillaBustosCity,
    laRiojaProvinceVinchinaCity
  ]);

/// The `Mendoza` region in `Argentina`
const Region argentinaMendozaProvince = Region(
  id: 3646,
  parentId: 11,
  longitude: -68.8458386,
  latitude: -32.8894587,
  name: "Mendoza",
  type: "province",
  stateCode: "M",
  cities: [
    mendozaProvinceDepartamentoDeCapitalCity,
    mendozaProvinceDepartamentoDeGeneralAlvearCity,
    mendozaProvinceDepartamentoDeGodoyCruzCity,
    mendozaProvinceDepartamentoDeGuaymallenCity,
    mendozaProvinceDepartamentoDeLaPazCity,
    mendozaProvinceDepartamentoDeLasHerasCity,
    mendozaProvinceDepartamentoDeLavalleCity,
    mendozaProvinceDepartamentoDeLujanCity,
    mendozaProvinceDepartamentoDeMaipuCity,
    mendozaProvinceDepartamentoDeMalargueCity,
    mendozaProvinceDepartamentoDeRivadaviaCity,
    mendozaProvinceDepartamentoDeSanCarlosCity,
    mendozaProvinceDepartamentoDeSanMartinCity,
    mendozaProvinceDepartamentoDeSanRafaelCity,
    mendozaProvinceDepartamentoDeSantaRosaCity,
    mendozaProvinceDepartamentoDeTunuyanCity,
    mendozaProvinceDepartamentoDeTupungatoCity,
    mendozaProvinceGodoyCruzCity,
    mendozaProvinceLasHerasCity,
    mendozaProvinceMendozaCity,
    mendozaProvinceSanMartinCity,
    mendozaProvinceSanRafaelCity
  ]);

/// The `Misiones` region in `Argentina`
const Region argentinaMisionesProvince = Region(
  id: 3644,
  parentId: 11,
  longitude: -55.9467076,
  latitude: -27.4269255,
  name: "Misiones",
  type: "province",
  stateCode: "N",
  cities: [
    misionesProvinceAlbaPosseCity,
    misionesProvinceAlmafuerteCity,
    misionesProvinceAristobuloDelValleCity,
    misionesProvinceArroyoDelMedioCity,
    misionesProvinceAzaraCity,
    misionesProvinceBernardoDeIrigoyenCity,
    misionesProvinceBonplandCity,
    misionesProvinceCampoGrandeCity,
    misionesProvinceCampoRamonCity,
    misionesProvinceCampoVieraCity,
    misionesProvinceCandelariaCity,
    misionesProvinceCapioviCity,
    misionesProvinceCaraguatayCity,
    misionesProvinceCerroAzulCity,
    misionesProvinceCerroCoraCity,
    misionesProvinceColoniaAuroraCity,
    misionesProvinceConcepcionDeLaSierraCity,
    misionesProvinceDepartamentoDeApostolesCity,
    misionesProvinceDepartamentoDeCainguasCity,
    misionesProvinceDepartamentoDeCandelariaCity,
    misionesProvinceDepartamentoDeCapitalCity,
    misionesProvinceDepartamentoDeConcepcionDeLaSierraCity,
    misionesProvinceDepartamentoDeEldoradoCity,
    misionesProvinceDepartamentoDeGeneralManuelBelgranoCity,
    misionesProvinceDepartamentoDeGuaraniCity,
    misionesProvinceDepartamentoDeIguazuCity,
    misionesProvinceDepartamentoDeLeandroNAlemCity,
    misionesProvinceDepartamentoDeLibertadorGeneralSanMartinCity,
    misionesProvinceDepartamentoDeMontecarloCity,
    misionesProvinceDepartamentoDeOberaCity,
    misionesProvinceDepartamentoDeSanIgnacioCity,
    misionesProvinceDepartamentoDeSanJavierCity,
    misionesProvinceDepartamentoDeSanPedroCity,
    misionesProvinceDepartamentoDeVeinticincoDeMayoCity,
    misionesProvinceDosArroyosCity,
    misionesProvinceDosDeMayoCity,
    misionesProvinceElAlcazarCity,
    misionesProvinceElSoberbioCity,
    misionesProvinceFlorentinoAmeghinoCity,
    misionesProvinceGaruhapeCity,
    misionesProvinceGarupaCity,
    misionesProvinceGeneralAlvearCity,
    misionesProvinceGobernadorRocaCity,
    misionesProvinceGuaraniCity,
    misionesProvinceJardinAmericaCity,
    misionesProvinceLoretoCity,
    misionesProvinceLosHelechosCity,
    misionesProvinceMartiresCity,
    misionesProvinceMojonGrandeCity,
    misionesProvinceMontecarloCity,
    misionesProvinceOberaCity,
    misionesProvincePanambiCity,
    misionesProvincePicadaGobernadorLopezCity,
    misionesProvincePosadasCity,
    misionesProvincePuertoEldoradoCity,
    misionesProvincePuertoEsperanzaCity,
    misionesProvincePuertoIguazuCity,
    misionesProvincePuertoLeoniCity,
    misionesProvincePuertoLibertadCity,
    misionesProvincePuertoPirayCity,
    misionesProvincePuertoRicoCity,
    misionesProvinceRuizDeMontoyaCity,
    misionesProvinceSanJoseCity,
    misionesProvinceSanPedroCity,
    misionesProvinceSanVicenteCity,
    misionesProvinceSantaMariaCity,
    misionesProvinceSantoPipoCity,
    misionesProvinceTresCaponesCity,
    misionesProvinceVeinticincoDeMayoCity,
    misionesProvinceWandaCity
  ]);

/// The `Neuquén` region in `Argentina`
const Region argentinaNeuquenProvince = Region(
  id: 3648,
  parentId: 11,
  longitude: -68.0730925,
  latitude: -38.94587,
  name: "Neuquén",
  type: "province",
  stateCode: "Q",
  cities: [
    neuquenProvinceAlumineCity,
    neuquenProvinceAndacolloCity,
    neuquenProvinceAneloCity,
    neuquenProvinceBarrancasCity,
    neuquenProvinceButaRanquilCity,
    neuquenProvinceCentenarioCity,
    neuquenProvinceChosMalalCity,
    neuquenProvinceCutralHypcoCity,
    neuquenProvinceDepartamentoDeAlumineCity,
    neuquenProvinceDepartamentoDeAneloCity,
    neuquenProvinceDepartamentoDeCatanHyplilCity,
    neuquenProvinceDepartamentoDeChosHypmalalCity,
    neuquenProvinceDepartamentoDeCollonHypcuraCity,
    neuquenProvinceDepartamentoDeConfluenciaCity,
    neuquenProvinceDepartamentoDeLacarCity,
    neuquenProvinceDepartamentoDeMinasCity,
    neuquenProvinceDepartamentoDeZapalaCity,
    neuquenProvinceElHuecuCity,
    neuquenProvinceJuninDeLosAndesCity,
    neuquenProvinceLasColoradasCity,
    neuquenProvinceLasLajasCity,
    neuquenProvinceLasOvejasCity,
    neuquenProvinceLoncopueCity,
    neuquenProvinceMarianoMorenoCity,
    neuquenProvinceNeuquenCity,
    neuquenProvincePicunLeufuCity,
    neuquenProvincePiedraDelAguilaCity,
    neuquenProvincePlazaHuinculCity,
    neuquenProvincePlottierCity,
    neuquenProvinceSanMartinDeLosAndesCity,
    neuquenProvinceSenillosaCity,
    neuquenProvinceVillaLaAngosturaCity,
    neuquenProvinceVistaAlegreCity,
    neuquenProvinceZapalaCity
  ]);

/// The `Río Negro` region in `Argentina`
const Region argentinaRioNegroProvince = Region(
  id: 3639,
  parentId: 11,
  longitude: -63.0266339,
  latitude: -40.8261434,
  name: "Río Negro",
  type: "province",
  stateCode: "R",
  cities: [
    rioNegroProvinceAllenCity,
    rioNegroProvinceCatrielCity,
    rioNegroProvinceCervantesCity,
    rioNegroProvinceChichinalesCity,
    rioNegroProvinceChimpayCity,
    rioNegroProvinceChoeleChoelCity,
    rioNegroProvinceCincoSaltosCity,
    rioNegroProvinceCipollettiCity,
    rioNegroProvinceComalloCity,
    rioNegroProvinceContraalmiranteCorderoCity,
    rioNegroProvinceCoronelBelisleCity,
    rioNegroProvinceDarwinCity,
    rioNegroProvinceDepartamentoDeAvellanedaCity,
    rioNegroProvinceDepartamentoDeVeinticincoDeMayoCity,
    rioNegroProvinceElBolsonCity,
    rioNegroProvinceElCuyCity,
    rioNegroProvinceFrayLuisBeltranCity,
    rioNegroProvinceGeneralConesaCity,
    rioNegroProvinceGeneralEnriqueGodoyCity,
    rioNegroProvinceGeneralFernandezOroCity,
    rioNegroProvinceGeneralRocaCity,
    rioNegroProvinceIngenieroJacobacciCity,
    rioNegroProvinceIngenieroLuisAHuergoCity,
    rioNegroProvinceLamarqueCity,
    rioNegroProvinceLosMenucosCity,
    rioNegroProvinceMainqueCity,
    rioNegroProvinceMaquinchaoCity,
    rioNegroProvinceNorquincoCity,
    rioNegroProvincePilcaniyeuCity,
    rioNegroProvinceRioColoradoCity,
    rioNegroProvinceSanAntonioOesteCity,
    rioNegroProvinceSanCarlosDeBarilocheCity,
    rioNegroProvinceSierraColoradaCity,
    rioNegroProvinceSierraGrandeCity,
    rioNegroProvinceValchetaCity,
    rioNegroProvinceViedmaCity,
    rioNegroProvinceVillaReginaCity
  ]);

/// The `Salta` region in `Argentina`
const Region argentinaSaltaProvince = Region(
  id: 3643,
  parentId: 11,
  longitude: -65.4150367,
  latitude: -24.7997688,
  name: "Salta",
  type: "province",
  stateCode: "A",
  cities: [
    saltaProvinceApolinarioSaraviaCity,
    saltaProvinceCachiCity,
    saltaProvinceCafayateCity,
    saltaProvinceCampoQuijanoCity,
    saltaProvinceChicoanaCity,
    saltaProvinceDepartamentoCapitalCity,
    saltaProvinceDepartamentoDeAntaCity,
    saltaProvinceDepartamentoDeCerrillosCity,
    saltaProvinceDepartamentoDeChicoanaCity,
    saltaProvinceDepartamentoDeGeneralGuemesCity,
    saltaProvinceDepartamentoDeGuachipasCity,
    saltaProvinceDepartamentoDeIruyaCity,
    saltaProvinceDepartamentoDeLaPomaCity,
    saltaProvinceDepartamentoDeLaVinaCity,
    saltaProvinceDepartamentoDeLosAndesCity,
    saltaProvinceDepartamentoDeMetanCity,
    saltaProvinceDepartamentoDeRivadaviaCity,
    saltaProvinceDepartamentoDeRosarioDeLaFronteraCity,
    saltaProvinceDepartamentoDeRosarioDeLermaCity,
    saltaProvinceDepartamentoDeSanCarlosCity,
    saltaProvinceElCarrilCity,
    saltaProvinceElGalponCity,
    saltaProvinceElQuebrachalCity,
    saltaProvinceEmbarcacionCity,
    saltaProvinceGeneralEnriqueMosconiCity,
    saltaProvinceJoaquinVGonzalezCity,
    saltaProvinceLaCalderaCity,
    saltaProvinceLasLajitasCity,
    saltaProvinceSaltaCity,
    saltaProvinceSanAntonioDeLosCobresCity,
    saltaProvinceSanRamonDeLaNuevaOranCity,
    saltaProvinceSantaRosaDeTastilCity,
    saltaProvinceTartagalCity
  ]);

/// The `San Juan` region in `Argentina`
const Region argentinaSanJuanProvince = Region(
  id: 3634,
  parentId: 11,
  longitude: -68.5676962,
  latitude: -31.5316976,
  name: "San Juan",
  type: "province",
  stateCode: "J",
  cities: [
    sanJuanProvinceAlbardonCity,
    sanJuanProvinceCalingastaCity,
    sanJuanProvinceCauceteCity,
    sanJuanProvinceChimbasCity,
    sanJuanProvinceDepartamentoDeAlbardonCity,
    sanJuanProvinceDepartamentoDeAngacoCity,
    sanJuanProvinceDepartamentoDeCalingastaCity,
    sanJuanProvinceDepartamentoDeCapitalCity,
    sanJuanProvinceDepartamentoDeCauceteCity,
    sanJuanProvinceDepartamentoDeChimbasCity,
    sanJuanProvinceDepartamentoDeIglesiaCity,
    sanJuanProvinceDepartamentoDeJachalCity,
    sanJuanProvinceDepartamentoDeNueveDeJulioCity,
    sanJuanProvinceDepartamentoDeRawsonCity,
    sanJuanProvinceDepartamentoDeRivadaviaCity,
    sanJuanProvinceDepartamentoDeSanMartinCity,
    sanJuanProvinceDepartamentoDeSantaLuciaCity,
    sanJuanProvinceDepartamentoDeSarmientoCity,
    sanJuanProvinceDepartamentoDeUllumCity,
    sanJuanProvinceDepartamentoDeZondaCity,
    sanJuanProvinceNueveDeJulioCity,
    sanJuanProvincePocitoCity,
    sanJuanProvinceSanAgustinDeValleFertilCity,
    sanJuanProvinceSanJoseDeJachalCity,
    sanJuanProvinceSanJuanCity,
    sanJuanProvinceSanMartinCity,
    sanJuanProvinceSantaLuciaCity,
    sanJuanProvinceVillaBasilioNievasCity,
    sanJuanProvinceVillaPaulaDeSarmientoCity
  ]);

/// The `San Luis` region in `Argentina`
const Region argentinaSanLuisProvince = Region(
  id: 3636,
  parentId: 11,
  longitude: -66.3294948,
  latitude: -33.2962042,
  name: "San Luis",
  type: "province",
  stateCode: "D",
  cities: [
    sanLuisProvinceBuenaEsperanzaCity,
    sanLuisProvinceCandelariaCity,
    sanLuisProvinceConcaranCity,
    sanLuisProvinceJuanMartinDePueyrredonCity,
    sanLuisProvinceJustoDaractCity,
    sanLuisProvinceLaPuntaCity,
    sanLuisProvinceLaTomaCity,
    sanLuisProvinceLujanCity,
    sanLuisProvinceMerloCity,
    sanLuisProvinceNaschelCity,
    sanLuisProvinceSanFranciscoDelMonteDeOroCity,
    sanLuisProvinceSanLuisCity,
    sanLuisProvinceSantaRosaDelConlaraCity,
    sanLuisProvinceTilisaraoCity,
    sanLuisProvinceUnionCity,
    sanLuisProvinceVillaGeneralRocaCity,
    sanLuisProvinceVillaMercedesCity
  ]);

/// The `Santa Cruz` region in `Argentina`
const Region argentinaSantaCruzProvince = Region(
  id: 3649,
  parentId: 11,
  longitude: -69.2474353,
  latitude: -51.6352821,
  name: "Santa Cruz",
  type: "province",
  stateCode: "Z",
  cities: [
    santaCruzProvince28DeNoviembreCity,
    santaCruzProvinceCaletaOliviaCity,
    santaCruzProvinceComandanteLuisPiedraBuenaCity,
    santaCruzProvinceDepartamentoDeDeseadoCity,
    santaCruzProvinceDepartamentoDeGuerAikeCity,
    santaCruzProvinceDepartamentoDeLagoArgentinoCity,
    santaCruzProvinceDepartamentoDeMagallanesCity,
    santaCruzProvinceDepartamentoDeRioChicoCity,
    santaCruzProvinceElCalafateCity,
    santaCruzProvinceGobernadorGregoresCity,
    santaCruzProvinceLasHerasCity,
    santaCruzProvinceLosAntiguosCity,
    santaCruzProvincePeritoMorenoCity,
    santaCruzProvincePicoTruncadoCity,
    santaCruzProvincePuertoDeseadoCity,
    santaCruzProvincePuertoSantaCruzCity,
    santaCruzProvinceRioGallegosCity,
    santaCruzProvinceRioTurbioCity,
    santaCruzProvinceSanJulianCity,
    santaCruzProvinceYacimientoRioTurbioCity
  ]);

/// The `Santa Fe` region in `Argentina`
const Region argentinaSantaFeProvince = Region(
  id: 3641,
  parentId: 11,
  longitude: -60.7238016,
  latitude: -31.5855109,
  name: "Santa Fe",
  type: "province",
  stateCode: "S",
  cities: [
    santaFeProvinceArmstrongCity,
    santaFeProvinceArroyoSecoCity,
    santaFeProvinceArrufoCity,
    santaFeProvinceAvellanedaCity,
    santaFeProvinceBellaItaliaCity,
    santaFeProvinceCalchaquiCity,
    santaFeProvinceCanadaDeGomezCity,
    santaFeProvinceCapitanBermudezCity,
    santaFeProvinceCarcaranaCity,
    santaFeProvinceCasildaCity,
    santaFeProvinceCeresCity,
    santaFeProvinceChanarLadeadoCity,
    santaFeProvinceCorondaCity,
    santaFeProvinceDepartamentoDeBelgranoCity,
    santaFeProvinceDepartamentoDeCaserosCity,
    santaFeProvinceDepartamentoDeCastellanosCity,
    santaFeProvinceDepartamentoDeConstitucionCity,
    santaFeProvinceDepartamentoDeLaCapitalCity,
    santaFeProvinceDepartamentoDeNueveDeJulioCity,
    santaFeProvinceDepartamentoDeSanCristobalCity,
    santaFeProvinceDepartamentoDeSanJavierCity,
    santaFeProvinceDepartamentoDeSanJustoCity,
    santaFeProvinceDepartamentoDeSanLorenzoCity,
    santaFeProvinceDepartamentoDeSanMartinCity,
    santaFeProvinceDepartamentoDeVeraCity,
    santaFeProvinceElTrebolCity,
    santaFeProvinceEsperanzaCity,
    santaFeProvinceFirmatCity,
    santaFeProvinceFrayLuisABeltranCity,
    santaFeProvinceFunesCity,
    santaFeProvinceGalvezCity,
    santaFeProvinceGatoColoradoCity,
    santaFeProvinceGobernadorGalvezCity,
    santaFeProvinceGranaderoBaigorriaCity,
    santaFeProvinceHelveciaCity,
    santaFeProvinceHersiliaCity,
    santaFeProvinceIriondoDepartmentCity,
    santaFeProvinceLagunaPaivaCity,
    santaFeProvinceLasParejasCity,
    santaFeProvinceLasRosasCity,
    santaFeProvinceLasToscasCity,
    santaFeProvinceLosLaurelesCity,
    santaFeProvinceMalabrigoCity,
    santaFeProvinceMelincueCity,
    santaFeProvincePerezCity,
    santaFeProvinceRafaelaCity,
    santaFeProvinceReconquistaCity,
    santaFeProvinceRecreoCity,
    santaFeProvinceRoldanCity,
    santaFeProvinceRosarioCity,
    santaFeProvinceRufinoCity,
    santaFeProvinceSanCarlosCentroCity,
    santaFeProvinceSanCristobalCity,
    santaFeProvinceSanJavierCity,
    santaFeProvinceSanJorgeCity,
    santaFeProvinceSanJustoCity,
    santaFeProvinceSantaFeCity,
    santaFeProvinceSantoTomeCity,
    santaFeProvinceSastreCity,
    santaFeProvinceSunchalesCity,
    santaFeProvinceTacuarendiCity,
    santaFeProvinceTostadoCity,
    santaFeProvinceTotorasCity,
    santaFeProvinceVenadoTuertoCity,
    santaFeProvinceVeraCity,
    santaFeProvinceVillaCanasCity,
    santaFeProvinceVillaConstitucionCity,
    santaFeProvinceVillaMuguetaCity,
    santaFeProvinceVillaOcampoCity,
    santaFeProvinceVillaTrinidadCity
  ]);

/// The `Santiago del Estero` region in `Argentina`
const Region argentinaSantiagoDelEsteroProvince = Region(
  id: 3635,
  parentId: 11,
  longitude: -64.264167,
  latitude: -27.7833574,
  name: "Santiago del Estero",
  type: "province",
  stateCode: "G",
  cities: [
    santiagoDelEsteroProvinceAnatuyaCity,
    santiagoDelEsteroProvinceBeltranCity,
    santiagoDelEsteroProvinceCampoGalloCity,
    santiagoDelEsteroProvinceClodomiraCity,
    santiagoDelEsteroProvinceColoniaDoraCity,
    santiagoDelEsteroProvinceDepartamentoDeAguirreCity,
    santiagoDelEsteroProvinceDepartamentoDeBandaCity,
    santiagoDelEsteroProvinceDepartamentoDeChoyaCity,
    santiagoDelEsteroProvinceDepartamentoDeGuasayanCity,
    santiagoDelEsteroProvinceDepartamentoDeLoretoCity,
    santiagoDelEsteroProvinceDepartamentoDeMorenoCity,
    santiagoDelEsteroProvinceDepartamentoDeRioHondoCity,
    santiagoDelEsteroProvinceDepartamentoDeRoblesCity,
    santiagoDelEsteroProvinceDepartamentoDeSanMartinCity,
    santiagoDelEsteroProvinceDepartamentoDeSarmientoCity,
    santiagoDelEsteroProvinceElHoyoCity,
    santiagoDelEsteroProvinceLaBandaCity,
    santiagoDelEsteroProvinceLosJuriesCity,
    santiagoDelEsteroProvinceLosTelaresCity,
    santiagoDelEsteroProvincePampaDeLosGuanacosCity,
    santiagoDelEsteroProvinceQuimiliCity,
    santiagoDelEsteroProvinceSanPedroCity,
    santiagoDelEsteroProvinceSantiagoDelEsteroCity,
    santiagoDelEsteroProvinceSumampaCity,
    santiagoDelEsteroProvinceSunchoCorralCity,
    santiagoDelEsteroProvinceTermasDeRioHondoCity,
    santiagoDelEsteroProvinceTintinaCity,
    santiagoDelEsteroProvinceVillaAtamisquiCity,
    santiagoDelEsteroProvinceVillaGeneralMitreCity,
    santiagoDelEsteroProvinceVillaOjoDeAguaCity
  ]);

/// The `Tierra del Fuego` region in `Argentina`
const Region argentinaTierraDelFuegoProvince = Region(
  id: 3650,
  parentId: 11,
  longitude: -68.3242061,
  latitude: -54.8053998,
  name: "Tierra del Fuego",
  type: "province",
  stateCode: "V",
  cities: [
    tierraDelFuegoProvinceRioGrandeCity,
    tierraDelFuegoProvinceTolhuinCity,
    tierraDelFuegoProvinceUshuaiaCity
  ]);

/// The `Tucumán` region in `Argentina`
const Region argentinaTucumanProvince = Region(
  id: 3637,
  parentId: 11,
  longitude: -65.2192903,
  latitude: -26.8221127,
  name: "Tucumán",
  type: "province",
  stateCode: "T",
  cities: [
    tucumanProvinceAguilaresCity,
    tucumanProvinceAlderetesCity,
    tucumanProvinceBellaVistaCity,
    tucumanProvinceBurruyacuCity,
    tucumanProvinceDepartamentoDeBurruyacuCity,
    tucumanProvinceDepartamentoDeCapitalCity,
    tucumanProvinceDepartamentoDeCruzAltaCity,
    tucumanProvinceDepartamentoDeFamaillaCity,
    tucumanProvinceDepartamentoDeGranerosCity,
    tucumanProvinceDepartamentoDeLaCochaCity,
    tucumanProvinceDepartamentoDeLulesCity,
    tucumanProvinceDepartamentoDeMonterosCity,
    tucumanProvinceDepartamentoDeRioChicoCity,
    tucumanProvinceDepartamentoDeSimocaCity,
    tucumanProvinceDepartamentoDeTrancasCity,
    tucumanProvinceDepartamentoDeYerbaBuenaCity,
    tucumanProvinceFamaillaCity,
    tucumanProvinceGranerosCity,
    tucumanProvinceLaCochaCity,
    tucumanProvinceMonterosCity,
    tucumanProvinceSanMiguelDeTucumanCity,
    tucumanProvinceSimocaCity,
    tucumanProvinceTafiDelValleCity,
    tucumanProvinceTafiViejoCity,
    tucumanProvinceTrancasCity,
    tucumanProvinceYerbaBuenaCity
  ]);

/// The 24 states of `Argentina` keyed by their id.
const Map<int, Region> argentinaStates = <int, Region>{
    3656: argentinaBuenosAiresProvince,
    3647: argentinaCatamarcaProvince,
    3640: argentinaChacoProvince,
    3651: argentinaChubutProvince,
    4880: argentinaCiudadAutonomaDeBuenosAiresCity,
    3642: argentinaCordobaProvince,
    3638: argentinaCorrientesProvince,
    3654: argentinaEntreRiosProvince,
    3652: argentinaFormosaProvince,
    3645: argentinaJujuyProvince,
    3655: argentinaLaPampaProvince,
    3653: argentinaLaRiojaProvince,
    3646: argentinaMendozaProvince,
    3644: argentinaMisionesProvince,
    3648: argentinaNeuquenProvince,
    3639: argentinaRioNegroProvince,
    3643: argentinaSaltaProvince,
    3634: argentinaSanJuanProvince,
    3636: argentinaSanLuisProvince,
    3649: argentinaSantaCruzProvince,
    3641: argentinaSantaFeProvince,
    3635: argentinaSantiagoDelEsteroProvince,
    3650: argentinaTierraDelFuegoProvince,
    3637: argentinaTucumanProvince
  };
