/// Access to known geographies in `Armenia` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'armenia_cities.dart';

/// The `Aragatsotn Region` region in `Armenia`
const Region armeniaAragatsotnRegion = Region(
  id: 2023,
  parentId: 12,
  longitude: 44.3748296,
  latitude: 40.3347301,
  name: "Aragatsotn Region",
  type: null,
  stateCode: "AG",
  cities: [
    aragatsotnRegionAgarakavanCity,
    aragatsotnRegionAparanCity,
    aragatsotnRegionAragatsCity,
    aragatsotnRegionArteniCity,
    aragatsotnRegionAshnakCity,
    aragatsotnRegionAshtarakCity,
    aragatsotnRegionByurakanCity,
    aragatsotnRegionHnaberdCity,
    aragatsotnRegionKarbiCity,
    aragatsotnRegionKasakhCity,
    aragatsotnRegionKoshCity,
    aragatsotnRegionNorYerznkaCity,
    aragatsotnRegionOshakanCity,
    aragatsotnRegionSasunikCity,
    aragatsotnRegionShenavanCity,
    aragatsotnRegionTalinCity,
    aragatsotnRegionTsaghkahovitCity,
    aragatsotnRegionUshiCity,
    aragatsotnRegionVoskevazCity,
    aragatsotnRegionZovuniCity
  ]);

/// The `Ararat Province` region in `Armenia`
const Region armeniaAraratProvince = Region(
  id: 2024,
  parentId: 12,
  longitude: 44.7200004,
  latitude: 39.9139415,
  name: "Ararat Province",
  type: null,
  stateCode: "AR",
  cities: [
    araratProvinceAbovyanCity,
    araratProvinceAralezCity,
    araratProvinceAraratCity,
    araratProvinceArevabuyrCity,
    araratProvinceArevshatCity,
    araratProvinceArmashCity,
    araratProvinceArtashatCity,
    araratProvinceAvsharCity,
    araratProvinceAygavanCity,
    araratProvinceAygepatCity,
    araratProvinceAygestanCity,
    araratProvinceAygezardCity,
    araratProvinceBardzrashenCity,
    araratProvinceBerkanushCity,
    araratProvinceBurastanCity,
    araratProvinceByuravanCity,
    araratProvinceDalarCity,
    araratProvinceDarakertCity,
    araratProvinceDashtavanCity,
    araratProvinceDimitrovCity,
    araratProvinceDvinCity,
    araratProvinceGetazatCity,
    araratProvinceGhukasavanCity,
    araratProvinceGoravanCity,
    araratProvinceHayanistCity,
    araratProvinceHovtashatCity,
    araratProvinceHovtashenCity,
    araratProvinceJrahovitCity,
    araratProvinceLusarratCity,
    araratProvinceMarmarashenCity,
    araratProvinceMasisCity,
    araratProvinceMrganushCity,
    araratProvinceMrgavanCity,
    araratProvinceMrgavetCity,
    araratProvinceNizamiCity,
    araratProvinceNorabatsCity,
    araratProvinceNoramargCity,
    araratProvinceNorashenCity,
    araratProvinceNoyakertCity,
    araratProvinceNshavanCity,
    araratProvinceSayatHypnovaCity,
    araratProvinceShahumyanCity,
    araratProvinceSisCity,
    araratProvinceSisavanCity,
    araratProvinceSurenavanCity,
    araratProvinceVediCity,
    araratProvinceVerinArtashatCity,
    araratProvinceVerinDvinCity,
    araratProvinceVosketapCity,
    araratProvinceVostanCity,
    araratProvinceYeghegnavanCity,
    araratProvinceZangakatunCity,
    araratProvinceZorakCity
  ]);

/// The `Armavir Region` region in `Armenia`
const Region armeniaArmavirRegion = Region(
  id: 2026,
  parentId: 12,
  longitude: 44.0372446,
  latitude: 40.1554631,
  name: "Armavir Region",
  type: null,
  stateCode: "AV",
  cities: [
    armavirRegionAghavnatunCity,
    armavirRegionAknalichCity,
    armavirRegionAknashenCity,
    armavirRegionAlashkertCity,
    armavirRegionApagaCity,
    armavirRegionAraksCity,
    armavirRegionArazapCity,
    armavirRegionArbatCity,
    armavirRegionArevashatCity,
    armavirRegionArevikCity,
    armavirRegionArgavandCity,
    armavirRegionArmavirCity,
    armavirRegionArshaluysCity,
    armavirRegionArtimetCity,
    armavirRegionAygekCity,
    armavirRegionAygeshatCity,
    armavirRegionBaghramyanCity,
    armavirRegionBambakashatCity,
    armavirRegionDalarikCity,
    armavirRegionDoghsCity,
    armavirRegionGayCity,
    armavirRegionGeghakertCity,
    armavirRegionGeghanistCity,
    armavirRegionGetashenCity,
    armavirRegionGmbetCity,
    armavirRegionGriboyedovCity,
    armavirRegionHaykashenCity,
    armavirRegionHovtamejCity,
    armavirRegionJanfidaCity,
    armavirRegionKhoronkCity,
    armavirRegionLenughiCity,
    armavirRegionLukashinCity,
    armavirRegionMargaraCity,
    armavirRegionMayisyanCity,
    armavirRegionMerdzavanCity,
    armavirRegionMetsamorCity,
    armavirRegionMrgashatCity,
    armavirRegionMusalerrCity,
    armavirRegionMyasnikyanCity,
    armavirRegionNalbandyanCity,
    armavirRegionNorArmavirCity,
    armavirRegionNorakertCity,
    armavirRegionPshatavanCity,
    armavirRegionPtghunkCity,
    armavirRegionSardarapatCity,
    armavirRegionShenavanCity,
    armavirRegionTandzutCity,
    armavirRegionTaronikCity,
    armavirRegionTsaghkunkCity,
    armavirRegionTsiatsanCity,
    armavirRegionVagharshapatCity,
    armavirRegionVoskehatCity,
    armavirRegionYeghegnutCity,
    armavirRegionYeraskhahunCity
  ]);

/// The `Gegharkunik Province` region in `Armenia`
const Region armeniaGegharkunikProvince = Region(
  id: 2028,
  parentId: 12,
  longitude: 45.1260414,
  latitude: 40.3526426,
  name: "Gegharkunik Province",
  type: null,
  stateCode: "GR",
  cities: [
    gegharkunikProvinceAkunkCity,
    gegharkunikProvinceAstghadzorCity,
    gegharkunikProvinceChambarakCity,
    gegharkunikProvinceDdmashenCity,
    gegharkunikProvinceDrakhtikCity,
    gegharkunikProvinceDzoragyughCity,
    gegharkunikProvinceGagarinCity,
    gegharkunikProvinceGandzakCity,
    gegharkunikProvinceGavarrCity,
    gegharkunikProvinceGeghamasarCity,
    gegharkunikProvinceGeghamavanCity,
    gegharkunikProvinceKaranlukhCity,
    gegharkunikProvinceKarchaghbyurCity,
    gegharkunikProvinceLanjaghbyurCity,
    gegharkunikProvinceLchapCity,
    gegharkunikProvinceLchashenCity,
    gegharkunikProvinceLichkCity,
    gegharkunikProvinceMadinaCity,
    gegharkunikProvinceMartuniCity,
    gegharkunikProvinceMetsMasrikCity,
    gegharkunikProvinceNerkinGetashenCity,
    gegharkunikProvinceNoratusCity,
    gegharkunikProvinceSarukhanCity,
    gegharkunikProvinceSevanCity,
    gegharkunikProvinceTsovagyughCity,
    gegharkunikProvinceTsovakCity,
    gegharkunikProvinceTsovasarCity,
    gegharkunikProvinceTsovazardCity,
    gegharkunikProvinceTsovinarCity,
    gegharkunikProvinceVaghashenCity,
    gegharkunikProvinceVahanCity,
    gegharkunikProvinceVardenikCity,
    gegharkunikProvinceVardenisCity,
    gegharkunikProvinceVarserCity,
    gegharkunikProvinceVerinGetashenCity,
    gegharkunikProvinceYeranosCity
  ]);

/// The `Kotayk Region` region in `Armenia`
const Region armeniaKotaykRegion = Region(
  id: 2033,
  parentId: 12,
  longitude: 44.7690148,
  latitude: 40.5410214,
  name: "Kotayk Region",
  type: null,
  stateCode: "KT",
  cities: [
    kotaykRegionAbovyanCity,
    kotaykRegionAghavnadzorCity,
    kotaykRegionAkunkCity,
    kotaykRegionAramusCity,
    kotaykRegionArgelCity,
    kotaykRegionArzakanCity,
    kotaykRegionArzniCity,
    kotaykRegionBalahovitCity,
    kotaykRegionBjniCity,
    kotaykRegionBuzhakanCity,
    kotaykRegionByureghavanCity,
    kotaykRegionDzoraghbyurCity,
    kotaykRegionFantanCity,
    kotaykRegionGarrniCity,
    kotaykRegionGoghtCity,
    kotaykRegionHrazdanCity,
    kotaykRegionKaputanCity,
    kotaykRegionKotaykCity,
    kotaykRegionLerrnanistCity,
    kotaykRegionMayakovskiCity,
    kotaykRegionMeghradzorCity,
    kotaykRegionMrgashenCity,
    kotaykRegionNorGeghiCity,
    kotaykRegionNorGyughCity,
    kotaykRegionPrroshyanCity,
    kotaykRegionPtghniCity,
    kotaykRegionSolakCity,
    kotaykRegionTsaghkadzorCity,
    kotaykRegionYeghvardCity,
    kotaykRegionZarrCity,
    kotaykRegionZoravanCity,
    kotaykRegionZovaberCity
  ]);

/// The `Lori Region` region in `Armenia`
const Region armeniaLoriRegion = Region(
  id: 2029,
  parentId: 12,
  longitude: 44.4900138,
  latitude: 40.9698452,
  name: "Lori Region",
  type: null,
  stateCode: "LO",
  cities: [
    loriRegionAgarakCity,
    loriRegionAkhtalaCity,
    loriRegionAlaverdiCity,
    loriRegionArevashoghCity,
    loriRegionBazumCity,
    loriRegionChochkanCity,
    loriRegionDarpasCity,
    loriRegionDseghCity,
    loriRegionFioletovoCity,
    loriRegionGogaranCity,
    loriRegionGugarkCity,
    loriRegionGyulagarakCity,
    loriRegionJrashenCity,
    loriRegionLerrnantskCity,
    loriRegionLerrnapatCity,
    loriRegionLerrnavanCity,
    loriRegionLorutCity,
    loriRegionMargahovitCity,
    loriRegionMetsParniCity,
    loriRegionMetsavanCity,
    loriRegionNorashenCity,
    loriRegionOdzunCity,
    loriRegionSarahartCity,
    loriRegionSaramejCity,
    loriRegionShahumyanCity,
    loriRegionShirakamutCity,
    loriRegionShnoghCity,
    loriRegionSpitakCity,
    loriRegionStepanavanCity,
    loriRegionTashirCity,
    loriRegionTsaghkaberCity,
    loriRegionUrrutCity,
    loriRegionVahagniCity,
    loriRegionVanadzorCity,
    loriRegionVardablurCity,
    loriRegionYeghegnutCity
  ]);

/// The `Shirak Region` region in `Armenia`
const Region armeniaShirakRegion = Region(
  id: 2031,
  parentId: 12,
  longitude: 43.8102461,
  latitude: 40.9630814,
  name: "Shirak Region",
  type: null,
  stateCode: "SH",
  cities: [
    shirakRegionAkhuryanCity,
    shirakRegionAmasiaCity,
    shirakRegionAnushavanCity,
    shirakRegionArevikCity,
    shirakRegionArevshatCity,
    shirakRegionArrapiCity,
    shirakRegionAzatanCity,
    shirakRegionBasenCity,
    shirakRegionDzithankovCity,
    shirakRegionGyumriCity,
    shirakRegionHaykavanCity,
    shirakRegionHorromCity,
    shirakRegionKamoCity,
    shirakRegionLerrnakertCity,
    shirakRegionMaralikCity,
    shirakRegionMarmashenCity,
    shirakRegionMayisyanCity,
    shirakRegionMeghrashenCity,
    shirakRegionMetsMantashCity,
    shirakRegionPokrMantashCity,
    shirakRegionPemzashenCity,
    shirakRegionSaratakCity,
    shirakRegionShirakCity,
    shirakRegionSpandaryanCity,
    shirakRegionVoskehaskCity,
    shirakRegionYerazgavorsCity
  ]);

/// The `Syunik Province` region in `Armenia`
const Region armeniaSyunikProvince = Region(
  id: 2027,
  parentId: 12,
  longitude: 46.3393234,
  latitude: 39.5133112,
  name: "Syunik Province",
  type: null,
  stateCode: "SU",
  cities: [
    syunikProvinceAgarakCity,
    syunikProvinceAknerCity,
    syunikProvinceAngeghakotCity,
    syunikProvinceBrrnakotCity,
    syunikProvinceDzorastanCity,
    syunikProvinceGorisCity,
    syunikProvinceHatsavanCity,
    syunikProvinceKapanCity,
    syunikProvinceKhndzoreskCity,
    syunikProvinceMeghriCity,
    syunikProvinceShaghatCity,
    syunikProvinceShinuhayrCity,
    syunikProvinceTeghCity,
    syunikProvinceVerishenCity
  ]);

/// The `Tavush Region` region in `Armenia`
const Region armeniaTavushRegion = Region(
  id: 2032,
  parentId: 12,
  longitude: 45.339349,
  latitude: 40.8866296,
  name: "Tavush Region",
  type: null,
  stateCode: "TV",
  cities: [
    tavushRegionArchisCity,
    tavushRegionArtsvaberdCity,
    tavushRegionAygehovitCity,
    tavushRegionAzatamutCity,
    tavushRegionBagratashenCity,
    tavushRegionBerdCity,
    tavushRegionBerdavanCity,
    tavushRegionDilijanCity,
    tavushRegionHaghartsinCity,
    tavushRegionIjevanCity,
    tavushRegionKhashtarrakCity,
    tavushRegionMosesgeghCity,
    tavushRegionNavurCity,
    tavushRegionNoyemberyanCity,
    tavushRegionParravakarCity,
    tavushRegionSarigyughCity,
    tavushRegionVoskevanCity
  ]);

/// The `Vayots Dzor Region` region in `Armenia`
const Region armeniaVayotsDzorRegion = Region(
  id: 2025,
  parentId: 12,
  longitude: 45.3337528,
  latitude: 39.7641996,
  name: "Vayots Dzor Region",
  type: null,
  stateCode: "VD",
  cities: [
    vayotsDzorRegionAgarakadzorCity,
    vayotsDzorRegionAghavnadzorCity,
    vayotsDzorRegionAreniCity,
    vayotsDzorRegionGetapCity,
    vayotsDzorRegionGladzorCity,
    vayotsDzorRegionJermukCity,
    vayotsDzorRegionMalishkaCity,
    vayotsDzorRegionRrindCity,
    vayotsDzorRegionShatinCity,
    vayotsDzorRegionVaykCity,
    vayotsDzorRegionVernashenCity,
    vayotsDzorRegionYeghegisCity,
    vayotsDzorRegionYeghegnadzorCity,
    vayotsDzorRegionZarritapCity
  ]);

/// The `Yerevan` region in `Armenia`
const Region armeniaYerevan = Region(
  id: 2030,
  parentId: 12,
  longitude: 44.515209,
  latitude: 40.1872023,
  name: "Yerevan",
  type: null,
  stateCode: "ER",
  cities: [
    yerevanArabkirCity,
    yerevanArgavandCity,
    yerevanJrashenCity,
    yerevanKanakerravanCity,
    yerevanVardadzorCity,
    yerevanYerevanCity
  ]);

/// The 11 states of `Armenia` keyed by their id.
const Map<int, Region> armeniaStates = <int, Region>{
    2023: armeniaAragatsotnRegion,
    2024: armeniaAraratProvince,
    2026: armeniaArmavirRegion,
    2028: armeniaGegharkunikProvince,
    2033: armeniaKotaykRegion,
    2029: armeniaLoriRegion,
    2031: armeniaShirakRegion,
    2027: armeniaSyunikProvince,
    2032: armeniaTavushRegion,
    2025: armeniaVayotsDzorRegion,
    2030: armeniaYerevan
  };
