/// Access to known geographies in Azerbaijan and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'azerbaijan_states.dart';

/// The country of `🇦🇿 Azerbaijan`, and its 75 states
const Country azerbaijan = Country(id: 16, name: "Azerbaijan", longitude: 47.5,
          latitude: 40.5, capital: "Baku",
          currency: "AZN", currencySymbol: "m",
          emoji: "🇦🇿", emojiU: "U+1F1E6 U+1F1FF",
          iso2: "AZ", iso3: "AZE",
          native: "Azərbaycan", numericCode: "031",
          phoneCode: "994", region: "Asia",
          subregion: "Western Asia", tld: ".az",
          states: [
            azerbaijanAbsheronDistrict,
            azerbaijanAgdamDistrict,
            azerbaijanAgdashDistrict,
            azerbaijanAghjabadiDistrict,
            azerbaijanAgstafaDistrict,
            azerbaijanAgsuDistrict,
            azerbaijanAstaraDistrict,
            azerbaijanBabekDistrict,
            azerbaijanBaku,
            azerbaijanBalakanDistrict,
            azerbaijanBardaDistrict,
            azerbaijanBeylaganDistrict,
            azerbaijanBilasuvarDistrict,
            azerbaijanDashkasanDistrict,
            azerbaijanFizuliDistrict,
            azerbaijanGanja,
            azerbaijanGdby,
            azerbaijanGobustanDistrict,
            azerbaijanGoranboyDistrict,
            azerbaijanGoychay,
            azerbaijanGoygolDistrict,
            azerbaijanHajigabulDistrict,
            azerbaijanImishliDistrict,
            azerbaijanIsmailliDistrict,
            azerbaijanJabrayilDistrict,
            azerbaijanJalilabadDistrict,
            azerbaijanJulfaDistrict,
            azerbaijanKalbajarDistrict,
            azerbaijanKangarliDistrict,
            azerbaijanKhachmazDistrict,
            azerbaijanKhiziDistrict,
            azerbaijanKhojaliDistrict,
            azerbaijanKurdamirDistrict,
            azerbaijanLachinDistrict,
            azerbaijanLankaran,
            azerbaijanLankaranDistrict,
            azerbaijanLerikDistrict,
            azerbaijanMartuni,
            azerbaijanMasallyDistrict,
            azerbaijanMingachevir,
            azerbaijanNakhchivanAutonomousRepublic,
            azerbaijanNeftchalaDistrict,
            azerbaijanOghuzDistrict,
            azerbaijanOrdubadDistrict,
            azerbaijanQabalaDistrict,
            azerbaijanQakhDistrict,
            azerbaijanQazakhDistrict,
            azerbaijanQubaDistrict,
            azerbaijanQubadliDistrict,
            azerbaijanQusarDistrict,
            azerbaijanSaatlyDistrict,
            azerbaijanSabirabadDistrict,
            azerbaijanSadarakDistrict,
            azerbaijanSalyanDistrict,
            azerbaijanSamukhDistrict,
            azerbaijanShabranDistrict,
            azerbaijanShahbuzDistrict,
            azerbaijanShaki,
            azerbaijanShakiDistrict,
            azerbaijanShamakhiDistrict,
            azerbaijanShamkirDistrict,
            azerbaijanSharurDistrict,
            azerbaijanShirvan,
            azerbaijanShushaDistrict,
            azerbaijanSiazanDistrict,
            azerbaijanSumqayit,
            azerbaijanTartarDistrict,
            azerbaijanTovuzDistrict,
            azerbaijanUjarDistrict,
            azerbaijanYardymliDistrict,
            azerbaijanYevlakh,
            azerbaijanYevlakhDistrict,
            azerbaijanZangilanDistrict,
            azerbaijanZaqatalaDistrict,
            azerbaijanZardabDistrict
          ],
          timezones: [
            Timezone(abbreviation: "AZT", gmtOffset: 14400, gmtOffsetName: "UTC+04:00",
                    tzName: "Azerbaijan Time", zoneName: "Asia/Baku")
          ],
          translations: {
            "kr": "아제르바이잔",
            "br": "Azerbaijão",
            "pt": "Azerbaijão",
            "nl": "Azerbeidzjan",
            "hr": "Azerbajdžan",
            "fa": "آذربایجان",
            "de": "Aserbaidschan",
            "es": "Azerbaiyán",
            "fr": "Azerbaïdjan",
            "ja": "アゼルバイジャン",
            "it": "Azerbaijan",
            "cn": "阿塞拜疆"
          });
