/// Access to known geographies in Bangladesh and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'bangladesh_cities.dart';

/// The 70 regions of `🇧🇩 Bangladesh`
const Region bangladeshBagerhatDistrict = Region(
    id: 796,
    parentId: 19,
    longitude: 89.7895478,
    latitude: 22.6602436,
    name: "Bagerhat District",
    type: null,
    stateCode: "05",
    cities: []);
const Region bangladeshBahadia = Region(
    id: 802,
    parentId: 19,
    longitude: 90.1671483,
    latitude: 23.7898712,
    name: "Bahadia",
    type: null,
    stateCode: "33",
    cities: []);
const Region bangladeshBandarbanDistrict = Region(
    id: 752,
    parentId: 19,
    longitude: 92.3686321,
    latitude: 21.8311002,
    name: "Bandarban District",
    type: null,
    stateCode: "01",
    cities: []);
const Region bangladeshBargunaDistrict = Region(
    id: 784,
    parentId: 19,
    longitude: 90.1120696,
    latitude: 22.0952915,
    name: "Barguna District",
    type: null,
    stateCode: "02",
    cities: []);
const Region bangladeshBarisalDistrict = Region(
    id: 818,
    parentId: 19,
    longitude: 90.3696316,
    latitude: 22.7022098,
    name: "Barisal District",
    type: null,
    stateCode: "06",
    cities: [
      bangladeshBarisalDistrictBarguna,
      bangladeshBarisalDistrictBarisal,
      bangladeshBarisalDistrictBhandaria,
      bangladeshBarisalDistrictBhola,
      bangladeshBarisalDistrictBurhanuddin,
      bangladeshBarisalDistrictGaurnadi,
      bangladeshBarisalDistrictJhalokati,
      bangladeshBarisalDistrictLalmohan,
      bangladeshBarisalDistrictMathba,
      bangladeshBarisalDistrictMehendiganj,
      bangladeshBarisalDistrictNalchiti,
      bangladeshBarisalDistrictPatuakhali,
      bangladeshBarisalDistrictPirojpur
    ]);
const Region bangladeshBarisalDivision = Region(
    id: 807,
    parentId: 19,
    longitude: 90.3371889,
    latitude: 22.3811131,
    name: "Barisal Division",
    type: null,
    stateCode: "A",
    cities: []);
const Region bangladeshBholaDistrict = Region(
    id: 756,
    parentId: 19,
    longitude: 90.7101023,
    latitude: 22.1785315,
    name: "Bhola District",
    type: null,
    stateCode: "07",
    cities: []);
const Region bangladeshBograDistrict = Region(
    id: 797,
    parentId: 19,
    longitude: 89.3697225,
    latitude: 24.8510402,
    name: "Bogra District",
    type: null,
    stateCode: "03",
    cities: []);
const Region bangladeshBrahmanbariaDistrict = Region(
    id: 810,
    parentId: 19,
    longitude: 91.1115014,
    latitude: 23.9608181,
    name: "Brahmanbaria District",
    type: null,
    stateCode: "04",
    cities: []);
const Region bangladeshChandpurDistrict = Region(
    id: 768,
    parentId: 19,
    longitude: 90.8517846,
    latitude: 23.2513148,
    name: "Chandpur District",
    type: null,
    stateCode: "09",
    cities: []);
const Region bangladeshChapaiNawabganjDistrict = Region(
    id: 761,
    parentId: 19,
    longitude: 88.2912069,
    latitude: 24.7413111,
    name: "Chapai Nawabganj District",
    type: null,
    stateCode: "45",
    cities: []);
const Region bangladeshChittagongDistrict = Region(
    id: 785,
    parentId: 19,
    longitude: 91.7538817,
    latitude: 22.5150105,
    name: "Chittagong District",
    type: null,
    stateCode: "10",
    cities: []);
const Region bangladeshChittagongDivision = Region(
    id: 803,
    parentId: 19,
    longitude: 91.9881527,
    latitude: 23.1793157,
    name: "Chittagong Division",
    type: null,
    stateCode: "B",
    cities: [
      bangladeshChittagongDivisionBandarban,
      bangladeshChittagongDivisionBibirHat,
      bangladeshChittagongDivisionBrahmanbaria,
      bangladeshChittagongDivisionChandpur,
      bangladeshChittagongDivisionChhagalnaiya,
      bangladeshChittagongDivisionChittagong,
      bangladeshChittagongDivisionComilla,
      bangladeshChittagongDivisionCoxsBazar,
      bangladeshChittagongDivisionCoxsBazar,
      bangladeshChittagongDivisionFeni,
      bangladeshChittagongDivisionHajiganj,
      bangladeshChittagongDivisionKhagrachhari,
      bangladeshChittagongDivisionLaksham,
      bangladeshChittagongDivisionLakshmipur,
      bangladeshChittagongDivisionManikchari,
      bangladeshChittagongDivisionNabinagar,
      bangladeshChittagongDivisionNoakhali,
      bangladeshChittagongDivisionPatiya,
      bangladeshChittagongDivisionRaipur,
      bangladeshChittagongDivisionRamganj,
      bangladeshChittagongDivisionRangamati,
      bangladeshChittagongDivisionRaojan,
      bangladeshChittagongDivisionSandwip,
      bangladeshChittagongDivisionSatkania,
      bangladeshChittagongDivisionTeknaf
    ]);
const Region bangladeshChuadangaDistrict = Region(
    id: 788,
    parentId: 19,
    longitude: 88.8263006,
    latitude: 23.6160512,
    name: "Chuadanga District",
    type: null,
    stateCode: "12",
    cities: []);
const Region bangladeshComillaDistrict = Region(
    id: 763,
    parentId: 19,
    longitude: 91.1808996,
    latitude: 23.4575667,
    name: "Comilla District",
    type: null,
    stateCode: "08",
    cities: []);
const Region bangladeshCoxsBazarDistrict = Region(
    id: 751,
    parentId: 19,
    longitude: 92.0282129,
    latitude: 21.5640626,
    name: "Cox's Bazar District",
    type: null,
    stateCode: "11",
    cities: []);
const Region bangladeshDhakaDistrict = Region(
    id: 771,
    parentId: 19,
    longitude: 90.3371889,
    latitude: 23.810514,
    name: "Dhaka District",
    type: null,
    stateCode: "13",
    cities: [
      bangladeshDhakaDistrictAzimpur,
      bangladeshDhakaDistrictBajitpur,
      bangladeshDhakaDistrictBhairabBazar,
      bangladeshDhakaDistrictCharBhadrasan,
      bangladeshDhakaDistrictCharGolora,
      bangladeshDhakaDistrictDhaka,
      bangladeshDhakaDistrictDohar,
      bangladeshDhakaDistrictFaridpur,
      bangladeshDhakaDistrictGazipur,
      bangladeshDhakaDistrictGopalganj,
      bangladeshDhakaDistrictJoymontop,
      bangladeshDhakaDistrictKhanbaniara,
      bangladeshDhakaDistrictKishoregonj,
      bangladeshDhakaDistrictKishorganj,
      bangladeshDhakaDistrictMadaripur,
      bangladeshDhakaDistrictManikganj,
      bangladeshDhakaDistrictMirzapur,
      bangladeshDhakaDistrictMunshiganj,
      bangladeshDhakaDistrictNagarpur,
      bangladeshDhakaDistrictNarayanganj,
      bangladeshDhakaDistrictNarsingdi,
      bangladeshDhakaDistrictPalang,
      bangladeshDhakaDistrictPaltan,
      bangladeshDhakaDistrictParvezAli,
      bangladeshDhakaDistrictParvezAliHossain,
      bangladeshDhakaDistrictRajbari,
      bangladeshDhakaDistrictRamnagar,
      bangladeshDhakaDistrictSakhipur,
      bangladeshDhakaDistrictSayani,
      bangladeshDhakaDistrictShariatpur,
      bangladeshDhakaDistrictSonargaon,
      bangladeshDhakaDistrictTangail,
      bangladeshDhakaDistrictTungi,
      bangladeshDhakaDistrictTungipara
    ]);
const Region bangladeshDhakaDivision = Region(
    id: 760,
    parentId: 19,
    longitude: 90.1494988,
    latitude: 23.9535742,
    name: "Dhaka Division",
    type: null,
    stateCode: "C",
    cities: []);
const Region bangladeshDinajpurDistrict = Region(
    id: 783,
    parentId: 19,
    longitude: 88.6331758,
    latitude: 25.6279123,
    name: "Dinajpur District",
    type: null,
    stateCode: "14",
    cities: []);
const Region bangladeshFaridpurDistrict = Region(
    id: 762,
    parentId: 19,
    longitude: 89.6308921,
    latitude: 23.5423919,
    name: "Faridpur District",
    type: null,
    stateCode: "15",
    cities: []);
const Region bangladeshFeniDistrict = Region(
    id: 816,
    parentId: 19,
    longitude: 91.4066646,
    latitude: 22.9408784,
    name: "Feni District",
    type: null,
    stateCode: "16",
    cities: []);
const Region bangladeshGaibandhaDistrict = Region(
    id: 795,
    parentId: 19,
    longitude: 89.5429652,
    latitude: 25.3296928,
    name: "Gaibandha District",
    type: null,
    stateCode: "19",
    cities: []);
const Region bangladeshGazipurDistrict = Region(
    id: 798,
    parentId: 19,
    longitude: 90.4125181,
    latitude: 24.0958171,
    name: "Gazipur District",
    type: null,
    stateCode: "18",
    cities: []);
const Region bangladeshGopalganjDistrict = Region(
    id: 792,
    parentId: 19,
    longitude: 84.43655,
    latitude: 26.4831584,
    name: "Gopalganj District",
    type: null,
    stateCode: "17",
    cities: []);
const Region bangladeshHabiganjDistrict = Region(
    id: 805,
    parentId: 19,
    longitude: 91.4506565,
    latitude: 24.4771236,
    name: "Habiganj District",
    type: null,
    stateCode: "20",
    cities: []);
const Region bangladeshJamalpurDistrict = Region(
    id: 808,
    parentId: 19,
    longitude: 89.7853218,
    latitude: 25.0830926,
    name: "Jamalpur District",
    type: null,
    stateCode: "21",
    cities: []);
const Region bangladeshJessoreDistrict = Region(
    id: 757,
    parentId: 19,
    longitude: 89.2181664,
    latitude: 23.1634014,
    name: "Jessore District",
    type: null,
    stateCode: "22",
    cities: []);
const Region bangladeshJhalokatiDistrict = Region(
    id: 778,
    parentId: 19,
    longitude: 90.1869644,
    latitude: 22.57208,
    name: "Jhalokati District",
    type: null,
    stateCode: "25",
    cities: []);
const Region bangladeshJhenaidahDistrict = Region(
    id: 789,
    parentId: 19,
    longitude: 89.1726031,
    latitude: 23.5449873,
    name: "Jhenaidah District",
    type: null,
    stateCode: "23",
    cities: []);
const Region bangladeshJoypurhatDistrict = Region(
    id: 806,
    parentId: 19,
    longitude: 89.0944937,
    latitude: 25.0947349,
    name: "Joypurhat District",
    type: null,
    stateCode: "24",
    cities: []);
const Region bangladeshKhagrachariDistrict = Region(
    id: 786,
    parentId: 19,
    longitude: 91.949021,
    latitude: 23.1321751,
    name: "Khagrachari District",
    type: null,
    stateCode: "29",
    cities: []);
const Region bangladeshKhulnaDistrict = Region(
    id: 811,
    parentId: 19,
    longitude: 89.3966581,
    latitude: 22.6737735,
    name: "Khulna District",
    type: null,
    stateCode: "27",
    cities: [
      bangladeshKhulnaDistrictBagerhat,
      bangladeshKhulnaDistrictBhatparaAbhaynagar,
      bangladeshKhulnaDistrictBheramara,
      bangladeshKhulnaDistrictChuadanga,
      bangladeshKhulnaDistrictJessore,
      bangladeshKhulnaDistrictJhenaidah,
      bangladeshKhulnaDistrictJhingergacha,
      bangladeshKhulnaDistrictKalia,
      bangladeshKhulnaDistrictKaliganj,
      bangladeshKhulnaDistrictKesabpur,
      bangladeshKhulnaDistrictKhulna,
      bangladeshKhulnaDistrictKushtia,
      bangladeshKhulnaDistrictMagura,
      bangladeshKhulnaDistrictMeherpur,
      bangladeshKhulnaDistrictMorrelgonj,
      bangladeshKhulnaDistrictNarail,
      bangladeshKhulnaDistrictNowlamary,
      bangladeshKhulnaDistrictPhultala,
      bangladeshKhulnaDistrictSarankhola,
      bangladeshKhulnaDistrictSatkhira,
      bangladeshKhulnaDistrictUjalpur,
      bangladeshKhulnaDistrictUttarCharFasson
    ]);
const Region bangladeshKhulnaDivision = Region(
    id: 775,
    parentId: 19,
    longitude: 89.2467191,
    latitude: 22.8087816,
    name: "Khulna Division",
    type: null,
    stateCode: "D",
    cities: []);
const Region bangladeshKishoreganjDistrict = Region(
    id: 779,
    parentId: 19,
    longitude: 90.9820668,
    latitude: 24.4260457,
    name: "Kishoreganj District",
    type: null,
    stateCode: "26",
    cities: []);
const Region bangladeshKurigramDistrict = Region(
    id: 793,
    parentId: 19,
    longitude: 89.6294746,
    latitude: 25.8072414,
    name: "Kurigram District",
    type: null,
    stateCode: "28",
    cities: []);
const Region bangladeshKushtiaDistrict = Region(
    id: 774,
    parentId: 19,
    longitude: 89.1099368,
    latitude: 23.8906995,
    name: "Kushtia District",
    type: null,
    stateCode: "30",
    cities: []);
const Region bangladeshLakshmipurDistrict = Region(
    id: 819,
    parentId: 19,
    longitude: 90.8281907,
    latitude: 22.9446744,
    name: "Lakshmipur District",
    type: null,
    stateCode: "31",
    cities: []);
const Region bangladeshLalmonirhatDistrict = Region(
    id: 780,
    parentId: 19,
    longitude: 89.2847251,
    latitude: 25.9923398,
    name: "Lalmonirhat District",
    type: null,
    stateCode: "32",
    cities: []);
const Region bangladeshMadaripurDistrict = Region(
    id: 817,
    parentId: 19,
    longitude: 90.1869644,
    latitude: 23.2393346,
    name: "Madaripur District",
    type: null,
    stateCode: "36",
    cities: []);
const Region bangladeshMeherpurDistrict = Region(
    id: 776,
    parentId: 19,
    longitude: 88.6723578,
    latitude: 23.8051991,
    name: "Meherpur District",
    type: null,
    stateCode: "39",
    cities: []);
const Region bangladeshMoulvibazarDistrict = Region(
    id: 794,
    parentId: 19,
    longitude: 91.7314903,
    latitude: 24.3095344,
    name: "Moulvibazar District",
    type: null,
    stateCode: "38",
    cities: []);
const Region bangladeshMunshiganjDistrict = Region(
    id: 790,
    parentId: 19,
    longitude: 90.4126621,
    latitude: 23.4980931,
    name: "Munshiganj District",
    type: null,
    stateCode: "35",
    cities: []);
const Region bangladeshMymensinghDistrict = Region(
    id: 766,
    parentId: 19,
    longitude: 90.4072919,
    latitude: 24.7538575,
    name: "Mymensingh District",
    type: null,
    stateCode: "34",
    cities: [
      bangladeshMymensinghDistrictGafargaon,
      bangladeshMymensinghDistrictJamalpur,
      bangladeshMymensinghDistrictMuktagacha,
      bangladeshMymensinghDistrictMymensingh,
      bangladeshMymensinghDistrictNetrakona,
      bangladeshMymensinghDistrictSarishabari,
      bangladeshMymensinghDistrictSherpur
    ]);
const Region bangladeshMymensinghDivision = Region(
    id: 758,
    parentId: 19,
    longitude: 90.4502368,
    latitude: 24.71362,
    name: "Mymensingh Division",
    type: null,
    stateCode: "H",
    cities: []);
const Region bangladeshNaogaonDistrict = Region(
    id: 814,
    parentId: 19,
    longitude: 88.7530952,
    latitude: 24.9131597,
    name: "Naogaon District",
    type: null,
    stateCode: "48",
    cities: []);
const Region bangladeshNarailDistrict = Region(
    id: 769,
    parentId: 19,
    longitude: 89.5840404,
    latitude: 23.1162929,
    name: "Narail District",
    type: null,
    stateCode: "43",
    cities: []);
const Region bangladeshNarayanganjDistrict = Region(
    id: 770,
    parentId: 19,
    longitude: 90.563609,
    latitude: 23.7146601,
    name: "Narayanganj District",
    type: null,
    stateCode: "40",
    cities: []);
const Region bangladeshNatoreDistrict = Region(
    id: 787,
    parentId: 19,
    longitude: 89.0076177,
    latitude: 24.410243,
    name: "Natore District",
    type: null,
    stateCode: "44",
    cities: []);
const Region bangladeshNetrokonaDistrict = Region(
    id: 764,
    parentId: 19,
    longitude: 90.8656415,
    latitude: 24.8103284,
    name: "Netrokona District",
    type: null,
    stateCode: "41",
    cities: []);
const Region bangladeshNilphamariDistrict = Region(
    id: 772,
    parentId: 19,
    longitude: 88.9414134,
    latitude: 25.8482798,
    name: "Nilphamari District",
    type: null,
    stateCode: "46",
    cities: []);
const Region bangladeshNoakhaliDistrict = Region(
    id: 815,
    parentId: 19,
    longitude: 91.0973184,
    latitude: 22.8723789,
    name: "Noakhali District",
    type: null,
    stateCode: "47",
    cities: []);
const Region bangladeshPabnaDistrict = Region(
    id: 754,
    parentId: 19,
    longitude: 89.4480718,
    latitude: 24.158505,
    name: "Pabna District",
    type: null,
    stateCode: "49",
    cities: []);
const Region bangladeshPanchagarhDistrict = Region(
    id: 800,
    parentId: 19,
    longitude: 88.5951751,
    latitude: 26.2708705,
    name: "Panchagarh District",
    type: null,
    stateCode: "52",
    cities: []);
const Region bangladeshPatuakhaliDistrict = Region(
    id: 777,
    parentId: 19,
    longitude: 90.4547503,
    latitude: 22.2248632,
    name: "Patuakhali District",
    type: null,
    stateCode: "51",
    cities: []);
const Region bangladeshPirojpurDistrict = Region(
    id: 791,
    parentId: 19,
    longitude: 89.9759264,
    latitude: 22.5790744,
    name: "Pirojpur District",
    type: null,
    stateCode: "50",
    cities: []);
const Region bangladeshRajbariDistrict = Region(
    id: 773,
    parentId: 19,
    longitude: 89.5874819,
    latitude: 23.715134,
    name: "Rajbari District",
    type: null,
    stateCode: "53",
    cities: []);
const Region bangladeshRajshahiDistrict = Region(
    id: 813,
    parentId: 19,
    longitude: 88.6048716,
    latitude: 24.3733087,
    name: "Rajshahi District",
    type: null,
    stateCode: "54",
    cities: [
      bangladeshRajshahiDistrictBera,
      bangladeshRajshahiDistrictBogra,
      bangladeshRajshahiDistrictChapaiNababganj,
      bangladeshRajshahiDistrictIshurdi,
      bangladeshRajshahiDistrictJoypurHat,
      bangladeshRajshahiDistrictJoypurhat,
      bangladeshRajshahiDistrictMahasthangarh,
      bangladeshRajshahiDistrictNaogaon,
      bangladeshRajshahiDistrictNatore,
      bangladeshRajshahiDistrictNawabganj,
      bangladeshRajshahiDistrictPabna,
      bangladeshRajshahiDistrictParNaogaon,
      bangladeshRajshahiDistrictPuthia,
      bangladeshRajshahiDistrictRajshahi,
      bangladeshRajshahiDistrictSaidpur,
      bangladeshRajshahiDistrictShahzadpur,
      bangladeshRajshahiDistrictShibganj,
      bangladeshRajshahiDistrictSirajganj
    ]);
const Region bangladeshRajshahiDivision = Region(
    id: 753,
    parentId: 19,
    longitude: 88.9413865,
    latitude: 24.7105776,
    name: "Rajshahi Division",
    type: null,
    stateCode: "E",
    cities: []);
const Region bangladeshRangamatiHillDistrict = Region(
    id: 809,
    parentId: 19,
    longitude: 92.2985134,
    latitude: 22.7324173,
    name: "Rangamati Hill District",
    type: null,
    stateCode: "56",
    cities: []);
const Region bangladeshRangpurDistrict = Region(
    id: 759,
    parentId: 19,
    longitude: 89.2508335,
    latitude: 25.7467925,
    name: "Rangpur District",
    type: null,
    stateCode: "55",
    cities: [
      bangladeshRangpurDistrictBadarganj,
      bangladeshRangpurDistrictChilmari,
      bangladeshRangpurDistrictDinajpur,
      bangladeshRangpurDistrictGaibandha,
      bangladeshRangpurDistrictKurigram,
      bangladeshRangpurDistrictLalmonirhat,
      bangladeshRangpurDistrictLalmonirhatDistrict,
      bangladeshRangpurDistrictNageswari,
      bangladeshRangpurDistrictNilphamariZila,
      bangladeshRangpurDistrictPanchagarh,
      bangladeshRangpurDistrictParbatipur,
      bangladeshRangpurDistrictPirgaaj,
      bangladeshRangpurDistrictRangpur,
      bangladeshRangpurDistrictThakurgaon
    ]);
const Region bangladeshRangpurDivision = Region(
    id: 750,
    parentId: 19,
    longitude: 88.9413865,
    latitude: 25.8483388,
    name: "Rangpur Division",
    type: null,
    stateCode: "F",
    cities: []);
const Region bangladeshSatkhiraDistrict = Region(
    id: 799,
    parentId: 19,
    longitude: 89.1114525,
    latitude: 22.3154812,
    name: "Satkhira District",
    type: null,
    stateCode: "58",
    cities: []);
const Region bangladeshShariatpurDistrict = Region(
    id: 801,
    parentId: 19,
    longitude: 90.4347711,
    latitude: 23.2423214,
    name: "Shariatpur District",
    type: null,
    stateCode: "62",
    cities: []);
const Region bangladeshSherpurDistrict = Region(
    id: 755,
    parentId: 19,
    longitude: 90.1494904,
    latitude: 25.0746235,
    name: "Sherpur District",
    type: null,
    stateCode: "57",
    cities: []);
const Region bangladeshSirajganjDistrict = Region(
    id: 781,
    parentId: 19,
    longitude: 89.5699615,
    latitude: 24.3141115,
    name: "Sirajganj District",
    type: null,
    stateCode: "59",
    cities: []);
const Region bangladeshSunamganjDistrict = Region(
    id: 812,
    parentId: 19,
    longitude: 91.3991627,
    latitude: 25.0714535,
    name: "Sunamganj District",
    type: null,
    stateCode: "61",
    cities: []);
const Region bangladeshSylhetDistrict = Region(
    id: 767,
    parentId: 19,
    longitude: 91.8700473,
    latitude: 24.8993357,
    name: "Sylhet District",
    type: null,
    stateCode: "60",
    cities: [
      bangladeshSylhetDistrictBaniachang,
      bangladeshSylhetDistrictChhatak,
      bangladeshSylhetDistrictHabiganj,
      bangladeshSylhetDistrictJahedpur,
      bangladeshSylhetDistrictMaulaviBazar,
      bangladeshSylhetDistrictMaulvibazar,
      bangladeshSylhetDistrictSunamganj,
      bangladeshSylhetDistrictSylhet
    ]);
const Region bangladeshSylhetDivision = Region(
    id: 765,
    parentId: 19,
    longitude: 91.6760691,
    latitude: 24.7049811,
    name: "Sylhet Division",
    type: null,
    stateCode: "G",
    cities: []);
const Region bangladeshTangailDistrict = Region(
    id: 782,
    parentId: 19,
    longitude: 89.9948257,
    latitude: 24.3917427,
    name: "Tangail District",
    type: null,
    stateCode: "63",
    cities: []);
const Region bangladeshThakurgaonDistrict = Region(
    id: 804,
    parentId: 19,
    longitude: 88.4282616,
    latitude: 26.0418392,
    name: "Thakurgaon District",
    type: null,
    stateCode: "64",
    cities: []);

const bangladeshStates = <int, Region>{
  796: bangladeshBagerhatDistrict,
  802: bangladeshBahadia,
  752: bangladeshBandarbanDistrict,
  784: bangladeshBargunaDistrict,
  818: bangladeshBarisalDistrict,
  807: bangladeshBarisalDivision,
  756: bangladeshBholaDistrict,
  797: bangladeshBograDistrict,
  810: bangladeshBrahmanbariaDistrict,
  768: bangladeshChandpurDistrict,
  761: bangladeshChapaiNawabganjDistrict,
  785: bangladeshChittagongDistrict,
  803: bangladeshChittagongDivision,
  788: bangladeshChuadangaDistrict,
  763: bangladeshComillaDistrict,
  751: bangladeshCoxsBazarDistrict,
  771: bangladeshDhakaDistrict,
  760: bangladeshDhakaDivision,
  783: bangladeshDinajpurDistrict,
  762: bangladeshFaridpurDistrict,
  816: bangladeshFeniDistrict,
  795: bangladeshGaibandhaDistrict,
  798: bangladeshGazipurDistrict,
  792: bangladeshGopalganjDistrict,
  805: bangladeshHabiganjDistrict,
  808: bangladeshJamalpurDistrict,
  757: bangladeshJessoreDistrict,
  778: bangladeshJhalokatiDistrict,
  789: bangladeshJhenaidahDistrict,
  806: bangladeshJoypurhatDistrict,
  786: bangladeshKhagrachariDistrict,
  811: bangladeshKhulnaDistrict,
  775: bangladeshKhulnaDivision,
  779: bangladeshKishoreganjDistrict,
  793: bangladeshKurigramDistrict,
  774: bangladeshKushtiaDistrict,
  819: bangladeshLakshmipurDistrict,
  780: bangladeshLalmonirhatDistrict,
  817: bangladeshMadaripurDistrict,
  776: bangladeshMeherpurDistrict,
  794: bangladeshMoulvibazarDistrict,
  790: bangladeshMunshiganjDistrict,
  766: bangladeshMymensinghDistrict,
  758: bangladeshMymensinghDivision,
  814: bangladeshNaogaonDistrict,
  769: bangladeshNarailDistrict,
  770: bangladeshNarayanganjDistrict,
  787: bangladeshNatoreDistrict,
  764: bangladeshNetrokonaDistrict,
  772: bangladeshNilphamariDistrict,
  815: bangladeshNoakhaliDistrict,
  754: bangladeshPabnaDistrict,
  800: bangladeshPanchagarhDistrict,
  777: bangladeshPatuakhaliDistrict,
  791: bangladeshPirojpurDistrict,
  773: bangladeshRajbariDistrict,
  813: bangladeshRajshahiDistrict,
  753: bangladeshRajshahiDivision,
  809: bangladeshRangamatiHillDistrict,
  759: bangladeshRangpurDistrict,
  750: bangladeshRangpurDivision,
  799: bangladeshSatkhiraDistrict,
  801: bangladeshShariatpurDistrict,
  755: bangladeshSherpurDistrict,
  781: bangladeshSirajganjDistrict,
  812: bangladeshSunamganjDistrict,
  767: bangladeshSylhetDistrict,
  765: bangladeshSylhetDivision,
  782: bangladeshTangailDistrict,
  804: bangladeshThakurgaonDistrict
};
