/// Access to known geographies in Bosnia and Herzegovina and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'bosnia_and_herzegovina_cities.dart';

/// The 13 regions of `🇧🇦 Bosnia and Herzegovina`
const Region bosniaAandHerzegovinaBosnianPodrinjeCanton = Region(id: 472, parentId: 28, longitude: 18.8244394, latitude: 43.68749,
          name: "Bosnian Podrinje Canton", type: null, stateCode: "05",
          cities: []);
const Region bosniaAandHerzegovinaBrckoDistrict = Region(id: 460, parentId: 28, longitude: 18.742153, latitude: 44.8405944,
          name: "Brčko District", type: null, stateCode: "BRC",
          cities: [
            bosniaAandHerzegovinaBrckoDistrictBrcko,
            bosniaAandHerzegovinaBrckoDistrictBrka
          ]);
const Region bosniaAandHerzegovinaCanton10 = Region(id: 471, parentId: 28, longitude: 16.9425187, latitude: 43.9534155,
          name: "Canton 10", type: null, stateCode: "10",
          cities: []);
const Region bosniaAandHerzegovinaCentralBosniaCanton = Region(id: 462, parentId: 28, longitude: 17.6866714, latitude: 44.1381856,
          name: "Central Bosnia Canton", type: null, stateCode: "06",
          cities: []);
const Region bosniaAandHerzegovinaFederationOofBosniaAandHerzegovina = Region(id: 467, parentId: 28, longitude: 17.842793, latitude: 43.8874897,
          name: "Federation of Bosnia and Herzegovina", type: null, stateCode: "BIH",
          cities: [
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBanovici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBarice,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBihac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBijela,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBila,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBlagaj,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBosanskaKrupa,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBosanskiPetrovac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBosanskoGrahovo,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBreza,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBugojno,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBusovaca,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaBuzim,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaCapljina,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaCazin,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaCelic,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaCim,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaCitluk,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaCoralici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaCrnici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDivicani,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDobrinje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDomaljevac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDonjaDubica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDonjaMahala,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDonjaMedida,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDonjiVakuf,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDreznica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDrinovci,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDrvar,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDubraveDonje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDubraveGornje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaDubravica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaFojnica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGlamoc,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGnojnica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGorazde,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGorica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGornjaBreza,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGornjaKoprivna,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGornjaTuzla,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGornjeMostre,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGornjeZivinice,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGornjiVakuf,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGostovici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGracanica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGradacac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGromiljak,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaGrude,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaHadzici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaHercegovackoHypNeretvanskiKanton,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaHotonj,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaIlici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaIlijas,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaIzacic,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaJablanica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaJajce,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaJelah,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaJezerski,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKacuni,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKakanj,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKantonSarajevo,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKaradaglije,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKiseljak,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKladanj,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKljuc,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKobiljaGlava,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKocerin,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKonjic,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaKovaci,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaLijesnica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaLivno,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaLjubuski,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaLokvine,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaLukavac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaLukavica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaMaglaj,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaMahala,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaMalaKladusa,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaMalesici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaMionica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaMostar,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaMramor,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaNeum,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaNoviSeher,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaNoviTravnik,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOdzak,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOlovo,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOmanjska,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOrahovicaDonja,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOrasac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOrasje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOrguz,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOstrozac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaOtoka,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPajicPolje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPazaric,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPeci,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPecigrad,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPjanici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPodhum,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPodzvizd,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPolje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPoljeHypBijela,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPotoci,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaProzor,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaPuracic,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaRadisici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaRodoc,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaRumboci,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSanica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSanskiMost,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSapna,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSarajevo,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSerici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSirokiBrijeg,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSkokovi,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSladna,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSolina,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSrebrenik,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaStijena,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaStjepanHypPolje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaStolac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSturlic,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaSumatac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTasovcici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTesanj,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTesanjka,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTodorovo,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTojsici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTomislavgrad,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTravnik,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTrzackaRastela,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTurbe,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaTuzla,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaUstikolina,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVares,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVaroskaRijeka,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVelagici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVelikaKladusa,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVidosi,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVisoko,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVitez,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVitina,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVogosca,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVoljevac,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVrnograc,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaVukovijeDonje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaZabrisce,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaZavidovici,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaZboriste,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaZeljeznoPolje,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaZenica,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaZepce,
            bosniaAandHerzegovinaFederationOofBosniaAandHerzegovinaZivinice
          ]);
const Region bosniaAandHerzegovinaHerzegovinaHypNeretvaCanton = Region(id: 463, parentId: 28, longitude: 17.763621, latitude: 43.5265159,
          name: "Herzegovina-Neretva Canton", type: null, stateCode: "07",
          cities: []);
const Region bosniaAandHerzegovinaPosavinaCanton = Region(id: 464, parentId: 28, longitude: 18.3776304, latitude: 45.0752094,
          name: "Posavina Canton", type: null, stateCode: "02",
          cities: []);
const Region bosniaAandHerzegovinaRepublikaSrpska = Region(id: 470, parentId: 28, longitude: 17.3148136, latitude: 44.7280186,
          name: "Republika Srpska", type: null, stateCode: "SRP",
          cities: [
            bosniaAandHerzegovinaRepublikaSrpskaBalatun,
            bosniaAandHerzegovinaRepublikaSrpskaBanjaLuka,
            bosniaAandHerzegovinaRepublikaSrpskaBijeljina,
            bosniaAandHerzegovinaRepublikaSrpskaBileca,
            bosniaAandHerzegovinaRepublikaSrpskaBlatnica,
            bosniaAandHerzegovinaRepublikaSrpskaBrod,
            bosniaAandHerzegovinaRepublikaSrpskaBronzaniMajdan,
            bosniaAandHerzegovinaRepublikaSrpskaCajnice,
            bosniaAandHerzegovinaRepublikaSrpskaCecava,
            bosniaAandHerzegovinaRepublikaSrpskaCelinac,
            bosniaAandHerzegovinaRepublikaSrpskaDerventa,
            bosniaAandHerzegovinaRepublikaSrpskaDoboj,
            bosniaAandHerzegovinaRepublikaSrpskaDobrljin,
            bosniaAandHerzegovinaRepublikaSrpskaDvorovi,
            bosniaAandHerzegovinaRepublikaSrpskaFoca,
            bosniaAandHerzegovinaRepublikaSrpskaGacko,
            bosniaAandHerzegovinaRepublikaSrpskaGradiska,
            bosniaAandHerzegovinaRepublikaSrpskaHiseti,
            bosniaAandHerzegovinaRepublikaSrpskaIstocniMostar,
            bosniaAandHerzegovinaRepublikaSrpskaJanja,
            bosniaAandHerzegovinaRepublikaSrpskaKalenderovciDonji,
            bosniaAandHerzegovinaRepublikaSrpskaKnezevo,
            bosniaAandHerzegovinaRepublikaSrpskaKnezica,
            bosniaAandHerzegovinaRepublikaSrpskaKoran,
            bosniaAandHerzegovinaRepublikaSrpskaKostajnica,
            bosniaAandHerzegovinaRepublikaSrpskaKotorVaros,
            bosniaAandHerzegovinaRepublikaSrpskaKozarskaDubica,
            bosniaAandHerzegovinaRepublikaSrpskaKrupaNnaVrbasu,
            bosniaAandHerzegovinaRepublikaSrpskaLaktasi,
            bosniaAandHerzegovinaRepublikaSrpskaLamovita,
            bosniaAandHerzegovinaRepublikaSrpskaLjubinje,
            bosniaAandHerzegovinaRepublikaSrpskaLopare,
            bosniaAandHerzegovinaRepublikaSrpskaMaglajani,
            bosniaAandHerzegovinaRepublikaSrpskaMaricka,
            bosniaAandHerzegovinaRepublikaSrpskaMaslovare,
            bosniaAandHerzegovinaRepublikaSrpskaMejdanHypObilicevo,
            bosniaAandHerzegovinaRepublikaSrpskaMilici,
            bosniaAandHerzegovinaRepublikaSrpskaModrica,
            bosniaAandHerzegovinaRepublikaSrpskaMrkonjicGrad,
            bosniaAandHerzegovinaRepublikaSrpskaNevesinje,
            bosniaAandHerzegovinaRepublikaSrpskaNoviGrad,
            bosniaAandHerzegovinaRepublikaSrpskaObudovac,
            bosniaAandHerzegovinaRepublikaSrpskaOmarska,
            bosniaAandHerzegovinaRepublikaSrpskaOpstinaOstraLuka,
            bosniaAandHerzegovinaRepublikaSrpskaOpstinaVisegrad,
            bosniaAandHerzegovinaRepublikaSrpskaOstraLuka,
            bosniaAandHerzegovinaRepublikaSrpskaPale,
            bosniaAandHerzegovinaRepublikaSrpskaPelagicevo,
            bosniaAandHerzegovinaRepublikaSrpskaPetkovci,
            bosniaAandHerzegovinaRepublikaSrpskaPiskavica,
            bosniaAandHerzegovinaRepublikaSrpskaPodbrdo,
            bosniaAandHerzegovinaRepublikaSrpskaPopovi,
            bosniaAandHerzegovinaRepublikaSrpskaPribinic,
            bosniaAandHerzegovinaRepublikaSrpskaPriboj,
            bosniaAandHerzegovinaRepublikaSrpskaPrijedor,
            bosniaAandHerzegovinaRepublikaSrpskaRogatica,
            bosniaAandHerzegovinaRepublikaSrpskaRudo,
            bosniaAandHerzegovinaRepublikaSrpskaSamac,
            bosniaAandHerzegovinaRepublikaSrpskaSekovici,
            bosniaAandHerzegovinaRepublikaSrpskaSipovo,
            bosniaAandHerzegovinaRepublikaSrpskaSokolac,
            bosniaAandHerzegovinaRepublikaSrpskaSrbac,
            bosniaAandHerzegovinaRepublikaSrpskaSrebrenica,
            bosniaAandHerzegovinaRepublikaSrpskaStanari,
            bosniaAandHerzegovinaRepublikaSrpskaStarcevica,
            bosniaAandHerzegovinaRepublikaSrpskaSvodna,
            bosniaAandHerzegovinaRepublikaSrpskaTeslic,
            bosniaAandHerzegovinaRepublikaSrpskaTrebinje,
            bosniaAandHerzegovinaRepublikaSrpskaTrn,
            bosniaAandHerzegovinaRepublikaSrpskaUgljevik,
            bosniaAandHerzegovinaRepublikaSrpskaVelikaObarska,
            bosniaAandHerzegovinaRepublikaSrpskaVisegrad,
            bosniaAandHerzegovinaRepublikaSrpskaVlasenica,
            bosniaAandHerzegovinaRepublikaSrpskaZivinice,
            bosniaAandHerzegovinaRepublikaSrpskaZvornik
          ]);
const Region bosniaAandHerzegovinaSarajevoCanton = Region(id: 466, parentId: 28, longitude: 18.2953442, latitude: 43.8512564,
          name: "Sarajevo Canton", type: null, stateCode: "09",
          cities: []);
const Region bosniaAandHerzegovinaTuzlaCanton = Region(id: 461, parentId: 28, longitude: 18.6972797, latitude: 44.5343463,
          name: "Tuzla Canton", type: null, stateCode: "03",
          cities: []);
const Region bosniaAandHerzegovinaUnaHypSanaCanton = Region(id: 465, parentId: 28, longitude: 16.3171629, latitude: 44.6503116,
          name: "Una-Sana Canton", type: null, stateCode: "01",
          cities: []);
const Region bosniaAandHerzegovinaWestHerzegovinaCanton = Region(id: 469, parentId: 28, longitude: 17.3848831, latitude: 43.4369244,
          name: "West Herzegovina Canton", type: null, stateCode: "08",
          cities: []);
const Region bosniaAandHerzegovinaZenicaHypDobojCanton = Region(id: 468, parentId: 28, longitude: 18.1604625, latitude: 44.2127109,
          name: "Zenica-Doboj Canton", type: null, stateCode: "04",
          cities: []);

const bosniaAandHerzegovinaStates = <int, Region>{
    472: bosniaAandHerzegovinaBosnianPodrinjeCanton,
    460: bosniaAandHerzegovinaBrckoDistrict,
    471: bosniaAandHerzegovinaCanton10,
    462: bosniaAandHerzegovinaCentralBosniaCanton,
    467: bosniaAandHerzegovinaFederationOofBosniaAandHerzegovina,
    463: bosniaAandHerzegovinaHerzegovinaHypNeretvaCanton,
    464: bosniaAandHerzegovinaPosavinaCanton,
    470: bosniaAandHerzegovinaRepublikaSrpska,
    466: bosniaAandHerzegovinaSarajevoCanton,
    461: bosniaAandHerzegovinaTuzlaCanton,
    465: bosniaAandHerzegovinaUnaHypSanaCanton,
    469: bosniaAandHerzegovinaWestHerzegovinaCanton,
    468: bosniaAandHerzegovinaZenicaHypDobojCanton
  };
