/// Access to known geographies in `Bosnia and Herzegovina` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.
library;

import '../base.dart';
import 'bosniaaandherzegovina_cities.dart';

/// The `Bosnian Podrinje Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaBosnianPodrinjeCanton = Region(
  id: 472,
  parentId: 28,
  longitude: 18.8244394,
  latitude: 43.68749,
  name: "Bosnian Podrinje Canton",
  type: null,
  stateCode: "05",
  cities: []);

/// The `Brčko District` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaBrckoDistrict = Region(
  id: 460,
  parentId: 28,
  longitude: 18.742153,
  latitude: 44.8405944,
  name: "Brčko District",
  type: null,
  stateCode: "BRC",
  cities: [
    brckoDistrictBrckoCity,
    brckoDistrictBrkaCity
  ]);

/// The `Canton 10` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaCanton10 = Region(
  id: 471,
  parentId: 28,
  longitude: 16.9425187,
  latitude: 43.9534155,
  name: "Canton 10",
  type: null,
  stateCode: "10",
  cities: []);

/// The `Central Bosnia Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaCentralBosniaCanton = Region(
  id: 462,
  parentId: 28,
  longitude: 17.6866714,
  latitude: 44.1381856,
  name: "Central Bosnia Canton",
  type: null,
  stateCode: "06",
  cities: []);

/// The `Federation of Bosnia and Herzegovina` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaFederationOfBosniaAndHerzegovina = Region(
  id: 467,
  parentId: 28,
  longitude: 17.842793,
  latitude: 43.8874897,
  name: "Federation of Bosnia and Herzegovina",
  type: null,
  stateCode: "BIH",
  cities: [
    federationOfBosniaAndHerzegovinaBanoviciCity,
    federationOfBosniaAndHerzegovinaBariceCity,
    federationOfBosniaAndHerzegovinaBihacCity,
    federationOfBosniaAndHerzegovinaBijelaCity,
    federationOfBosniaAndHerzegovinaBilaCity,
    federationOfBosniaAndHerzegovinaBlagajCity,
    federationOfBosniaAndHerzegovinaBosanskaKrupaCity,
    federationOfBosniaAndHerzegovinaBosanskiPetrovacCity,
    federationOfBosniaAndHerzegovinaBosanskoGrahovoCity,
    federationOfBosniaAndHerzegovinaBrezaCity,
    federationOfBosniaAndHerzegovinaBugojnoCity,
    federationOfBosniaAndHerzegovinaBusovacaCity,
    federationOfBosniaAndHerzegovinaBuzimCity,
    federationOfBosniaAndHerzegovinaCapljinaCity,
    federationOfBosniaAndHerzegovinaCazinCity,
    federationOfBosniaAndHerzegovinaCelicCity,
    federationOfBosniaAndHerzegovinaCimCity,
    federationOfBosniaAndHerzegovinaCitlukCity,
    federationOfBosniaAndHerzegovinaCoraliciCity,
    federationOfBosniaAndHerzegovinaCrniciCity,
    federationOfBosniaAndHerzegovinaDivicaniCity,
    federationOfBosniaAndHerzegovinaDobrinjeCity,
    federationOfBosniaAndHerzegovinaDomaljevacCity,
    federationOfBosniaAndHerzegovinaDonjaDubicaCity,
    federationOfBosniaAndHerzegovinaDonjaMahalaCity,
    federationOfBosniaAndHerzegovinaDonjaMedidaCity,
    federationOfBosniaAndHerzegovinaDonjiVakufCity,
    federationOfBosniaAndHerzegovinaDreznicaCity,
    federationOfBosniaAndHerzegovinaDrinovciCity,
    federationOfBosniaAndHerzegovinaDrvarCity,
    federationOfBosniaAndHerzegovinaDubraveDonjeCity,
    federationOfBosniaAndHerzegovinaDubraveGornjeCity,
    federationOfBosniaAndHerzegovinaDubravicaCity,
    federationOfBosniaAndHerzegovinaFojnicaCity,
    federationOfBosniaAndHerzegovinaGlamocCity,
    federationOfBosniaAndHerzegovinaGnojnicaCity,
    federationOfBosniaAndHerzegovinaGorazdeCity,
    federationOfBosniaAndHerzegovinaGoricaCity,
    federationOfBosniaAndHerzegovinaGornjaBrezaCity,
    federationOfBosniaAndHerzegovinaGornjaKoprivnaCity,
    federationOfBosniaAndHerzegovinaGornjaTuzlaCity,
    federationOfBosniaAndHerzegovinaGornjeMostreCity,
    federationOfBosniaAndHerzegovinaGornjeZiviniceCity,
    federationOfBosniaAndHerzegovinaGornjiVakufCity,
    federationOfBosniaAndHerzegovinaGostoviciCity,
    federationOfBosniaAndHerzegovinaGracanicaCity,
    federationOfBosniaAndHerzegovinaGradacacCity,
    federationOfBosniaAndHerzegovinaGromiljakCity,
    federationOfBosniaAndHerzegovinaGrudeCity,
    federationOfBosniaAndHerzegovinaHadziciCity,
    federationOfBosniaAndHerzegovinaHercegovackoHypneretvanskiKantonCity,
    federationOfBosniaAndHerzegovinaHotonjCity,
    federationOfBosniaAndHerzegovinaIliciCity,
    federationOfBosniaAndHerzegovinaIlijasCity,
    federationOfBosniaAndHerzegovinaIzacicCity,
    federationOfBosniaAndHerzegovinaJablanicaCity,
    federationOfBosniaAndHerzegovinaJajceCity,
    federationOfBosniaAndHerzegovinaJelahCity,
    federationOfBosniaAndHerzegovinaJezerskiCity,
    federationOfBosniaAndHerzegovinaKacuniCity,
    federationOfBosniaAndHerzegovinaKakanjCity,
    federationOfBosniaAndHerzegovinaKantonSarajevoCity,
    federationOfBosniaAndHerzegovinaKaradaglijeCity,
    federationOfBosniaAndHerzegovinaKiseljakCity,
    federationOfBosniaAndHerzegovinaKladanjCity,
    federationOfBosniaAndHerzegovinaKljucCity,
    federationOfBosniaAndHerzegovinaKobiljaGlavaCity,
    federationOfBosniaAndHerzegovinaKocerinCity,
    federationOfBosniaAndHerzegovinaKonjicCity,
    federationOfBosniaAndHerzegovinaKovaciCity,
    federationOfBosniaAndHerzegovinaLijesnicaCity,
    federationOfBosniaAndHerzegovinaLivnoCity,
    federationOfBosniaAndHerzegovinaLjubuskiCity,
    federationOfBosniaAndHerzegovinaLokvineCity,
    federationOfBosniaAndHerzegovinaLukavacCity,
    federationOfBosniaAndHerzegovinaLukavicaCity,
    federationOfBosniaAndHerzegovinaMaglajCity,
    federationOfBosniaAndHerzegovinaMahalaCity,
    federationOfBosniaAndHerzegovinaMalaKladusaCity,
    federationOfBosniaAndHerzegovinaMalesiciCity,
    federationOfBosniaAndHerzegovinaMionicaCity,
    federationOfBosniaAndHerzegovinaMostarCity,
    federationOfBosniaAndHerzegovinaMramorCity,
    federationOfBosniaAndHerzegovinaNeumCity,
    federationOfBosniaAndHerzegovinaNoviSeherCity,
    federationOfBosniaAndHerzegovinaNoviTravnikCity,
    federationOfBosniaAndHerzegovinaOdzakCity,
    federationOfBosniaAndHerzegovinaOlovoCity,
    federationOfBosniaAndHerzegovinaOmanjskaCity,
    federationOfBosniaAndHerzegovinaOrahovicaDonjaCity,
    federationOfBosniaAndHerzegovinaOrasacCity,
    federationOfBosniaAndHerzegovinaOrasjeCity,
    federationOfBosniaAndHerzegovinaOrguzCity,
    federationOfBosniaAndHerzegovinaOstrozacCity,
    federationOfBosniaAndHerzegovinaOtokaCity,
    federationOfBosniaAndHerzegovinaPajicPoljeCity,
    federationOfBosniaAndHerzegovinaPazaricCity,
    federationOfBosniaAndHerzegovinaPeciCity,
    federationOfBosniaAndHerzegovinaPecigradCity,
    federationOfBosniaAndHerzegovinaPjaniciCity,
    federationOfBosniaAndHerzegovinaPodhumCity,
    federationOfBosniaAndHerzegovinaPodzvizdCity,
    federationOfBosniaAndHerzegovinaPoljeCity,
    federationOfBosniaAndHerzegovinaPoljeHypbijelaCity,
    federationOfBosniaAndHerzegovinaPotociCity,
    federationOfBosniaAndHerzegovinaProzorCity,
    federationOfBosniaAndHerzegovinaPuracicCity,
    federationOfBosniaAndHerzegovinaRadisiciCity,
    federationOfBosniaAndHerzegovinaRodocCity,
    federationOfBosniaAndHerzegovinaRumbociCity,
    federationOfBosniaAndHerzegovinaSanicaCity,
    federationOfBosniaAndHerzegovinaSanskiMostCity,
    federationOfBosniaAndHerzegovinaSapnaCity,
    federationOfBosniaAndHerzegovinaSarajevoCity,
    federationOfBosniaAndHerzegovinaSericiCity,
    federationOfBosniaAndHerzegovinaSirokiBrijegCity,
    federationOfBosniaAndHerzegovinaSkokoviCity,
    federationOfBosniaAndHerzegovinaSladnaCity,
    federationOfBosniaAndHerzegovinaSolinaCity,
    federationOfBosniaAndHerzegovinaSrebrenikCity,
    federationOfBosniaAndHerzegovinaStijenaCity,
    federationOfBosniaAndHerzegovinaStjepanHyppoljeCity,
    federationOfBosniaAndHerzegovinaStolacCity,
    federationOfBosniaAndHerzegovinaSturlicCity,
    federationOfBosniaAndHerzegovinaSumatacCity,
    federationOfBosniaAndHerzegovinaTasovciciCity,
    federationOfBosniaAndHerzegovinaTesanjCity,
    federationOfBosniaAndHerzegovinaTesanjkaCity,
    federationOfBosniaAndHerzegovinaTodorovoCity,
    federationOfBosniaAndHerzegovinaTojsiciCity,
    federationOfBosniaAndHerzegovinaTomislavgradCity,
    federationOfBosniaAndHerzegovinaTravnikCity,
    federationOfBosniaAndHerzegovinaTrzackaRastelaCity,
    federationOfBosniaAndHerzegovinaTurbeCity,
    federationOfBosniaAndHerzegovinaTuzlaCity,
    federationOfBosniaAndHerzegovinaUstikolinaCity,
    federationOfBosniaAndHerzegovinaVaresCity,
    federationOfBosniaAndHerzegovinaVaroskaRijekaCity,
    federationOfBosniaAndHerzegovinaVelagiciCity,
    federationOfBosniaAndHerzegovinaVelikaKladusaCity,
    federationOfBosniaAndHerzegovinaVidosiCity,
    federationOfBosniaAndHerzegovinaVisokoCity,
    federationOfBosniaAndHerzegovinaVitezCity,
    federationOfBosniaAndHerzegovinaVitinaCity,
    federationOfBosniaAndHerzegovinaVogoscaCity,
    federationOfBosniaAndHerzegovinaVoljevacCity,
    federationOfBosniaAndHerzegovinaVrnogracCity,
    federationOfBosniaAndHerzegovinaVukovijeDonjeCity,
    federationOfBosniaAndHerzegovinaZabrisceCity,
    federationOfBosniaAndHerzegovinaZavidoviciCity,
    federationOfBosniaAndHerzegovinaZboristeCity,
    federationOfBosniaAndHerzegovinaZeljeznoPoljeCity,
    federationOfBosniaAndHerzegovinaZenicaCity,
    federationOfBosniaAndHerzegovinaZepceCity,
    federationOfBosniaAndHerzegovinaZiviniceCity
  ]);

/// The `Herzegovina-Neretva Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaHerzegovinaHypneretvaCanton = Region(
  id: 463,
  parentId: 28,
  longitude: 17.763621,
  latitude: 43.5265159,
  name: "Herzegovina-Neretva Canton",
  type: null,
  stateCode: "07",
  cities: []);

/// The `Posavina Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaPosavinaCanton = Region(
  id: 464,
  parentId: 28,
  longitude: 18.3776304,
  latitude: 45.0752094,
  name: "Posavina Canton",
  type: null,
  stateCode: "02",
  cities: []);

/// The `Republika Srpska` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaRepublikaSrpska = Region(
  id: 470,
  parentId: 28,
  longitude: 17.3148136,
  latitude: 44.7280186,
  name: "Republika Srpska",
  type: null,
  stateCode: "SRP",
  cities: [
    republikaSrpskaBalatunCity,
    republikaSrpskaBanjaLukaCity,
    republikaSrpskaBijeljinaCity,
    republikaSrpskaBilecaCity,
    republikaSrpskaBlatnicaCity,
    republikaSrpskaBrodCity,
    republikaSrpskaBronzaniMajdanCity,
    republikaSrpskaCajniceCity,
    republikaSrpskaCecavaCity,
    republikaSrpskaCelinacCity,
    republikaSrpskaDerventaCity,
    republikaSrpskaDobojCity,
    republikaSrpskaDobrljinCity,
    republikaSrpskaDvoroviCity,
    republikaSrpskaFocaCity,
    republikaSrpskaGackoCity,
    republikaSrpskaGradiskaCity,
    republikaSrpskaHisetiCity,
    republikaSrpskaIstocniMostarCity,
    republikaSrpskaJanjaCity,
    republikaSrpskaKalenderovciDonjiCity,
    republikaSrpskaKnezevoCity,
    republikaSrpskaKnezicaCity,
    republikaSrpskaKoranCity,
    republikaSrpskaKostajnicaCity,
    republikaSrpskaKotorVarosCity,
    republikaSrpskaKozarskaDubicaCity,
    republikaSrpskaKrupaNaVrbasuCity,
    republikaSrpskaLaktasiCity,
    republikaSrpskaLamovitaCity,
    republikaSrpskaLjubinjeCity,
    republikaSrpskaLopareCity,
    republikaSrpskaMaglajaniCity,
    republikaSrpskaMarickaCity,
    republikaSrpskaMaslovareCity,
    republikaSrpskaMejdanHypObilicevoCity,
    republikaSrpskaMiliciCity,
    republikaSrpskaModricaCity,
    republikaSrpskaMrkonjicGradCity,
    republikaSrpskaNevesinjeCity,
    republikaSrpskaNoviGradCity,
    republikaSrpskaObudovacCity,
    republikaSrpskaOmarskaCity,
    republikaSrpskaOpstinaOstraLukaCity,
    republikaSrpskaOpstinaVisegradCity,
    republikaSrpskaOstraLukaCity,
    republikaSrpskaPaleCity,
    republikaSrpskaPelagicevoCity,
    republikaSrpskaPetkovciCity,
    republikaSrpskaPiskavicaCity,
    republikaSrpskaPodbrdoCity,
    republikaSrpskaPopoviCity,
    republikaSrpskaPribinicCity,
    republikaSrpskaPribojCity,
    republikaSrpskaPrijedorCity,
    republikaSrpskaRogaticaCity,
    republikaSrpskaRudoCity,
    republikaSrpskaSamacCity,
    republikaSrpskaSekoviciCity,
    republikaSrpskaSipovoCity,
    republikaSrpskaSokolacCity,
    republikaSrpskaSrbacCity,
    republikaSrpskaSrebrenicaCity,
    republikaSrpskaStanariCity,
    republikaSrpskaStarcevicaCity,
    republikaSrpskaSvodnaCity,
    republikaSrpskaTeslicCity,
    republikaSrpskaTrebinjeCity,
    republikaSrpskaTrnCity,
    republikaSrpskaUgljevikCity,
    republikaSrpskaVelikaObarskaCity,
    republikaSrpskaVisegradCity,
    republikaSrpskaVlasenicaCity,
    republikaSrpskaZiviniceCity,
    republikaSrpskaZvornikCity
  ]);

/// The `Sarajevo Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaSarajevoCanton = Region(
  id: 466,
  parentId: 28,
  longitude: 18.2953442,
  latitude: 43.8512564,
  name: "Sarajevo Canton",
  type: null,
  stateCode: "09",
  cities: []);

/// The `Tuzla Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaTuzlaCanton = Region(
  id: 461,
  parentId: 28,
  longitude: 18.6972797,
  latitude: 44.5343463,
  name: "Tuzla Canton",
  type: null,
  stateCode: "03",
  cities: []);

/// The `Una-Sana Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaUnaHypsanaCanton = Region(
  id: 465,
  parentId: 28,
  longitude: 16.3171629,
  latitude: 44.6503116,
  name: "Una-Sana Canton",
  type: null,
  stateCode: "01",
  cities: []);

/// The `West Herzegovina Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaWestHerzegovinaCanton = Region(
  id: 469,
  parentId: 28,
  longitude: 17.3848831,
  latitude: 43.4369244,
  name: "West Herzegovina Canton",
  type: null,
  stateCode: "08",
  cities: []);

/// The `Zenica-Doboj Canton` region in `Bosnia and Herzegovina`
const Region bosniaAndHerzegovinaZenicaHypdobojCanton = Region(
  id: 468,
  parentId: 28,
  longitude: 18.1604625,
  latitude: 44.2127109,
  name: "Zenica-Doboj Canton",
  type: null,
  stateCode: "04",
  cities: []);

/// The 13 states of `Bosnia and Herzegovina` keyed by their id.
const Map<int, Region> bosniaAndHerzegovinaStates = <int, Region>{
    472: bosniaAndHerzegovinaBosnianPodrinjeCanton,
    460: bosniaAndHerzegovinaBrckoDistrict,
    471: bosniaAndHerzegovinaCanton10,
    462: bosniaAndHerzegovinaCentralBosniaCanton,
    467: bosniaAndHerzegovinaFederationOfBosniaAndHerzegovina,
    463: bosniaAndHerzegovinaHerzegovinaHypneretvaCanton,
    464: bosniaAndHerzegovinaPosavinaCanton,
    470: bosniaAndHerzegovinaRepublikaSrpska,
    466: bosniaAndHerzegovinaSarajevoCanton,
    461: bosniaAndHerzegovinaTuzlaCanton,
    465: bosniaAndHerzegovinaUnaHypsanaCanton,
    469: bosniaAndHerzegovinaWestHerzegovinaCanton,
    468: bosniaAndHerzegovinaZenicaHypdobojCanton
  };
