/// Access to known geographies in Bulgaria and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'bulgaria_cities.dart';

/// The 28 regions of `🇧🇬 Bulgaria`
const Region bulgariaBlagoevgradProvince = Region(
    id: 4699,
    parentId: 34,
    longitude: 23.0943356,
    latitude: 42.0208614,
    name: "Blagoevgrad Province",
    type: null,
    stateCode: "01",
    cities: [
      bulgariaBlagoevgradProvinceBansko,
      bulgariaBlagoevgradProvinceBelitsa,
      bulgariaBlagoevgradProvinceBlagoevgrad,
      bulgariaBlagoevgradProvinceGarmen,
      bulgariaBlagoevgradProvinceGotseDelchev,
      bulgariaBlagoevgradProvinceHadzhidimovo,
      bulgariaBlagoevgradProvinceKolarovo,
      bulgariaBlagoevgradProvinceKresna,
      bulgariaBlagoevgradProvinceObshtinaBansko,
      bulgariaBlagoevgradProvinceObshtinaBelitsa,
      bulgariaBlagoevgradProvinceObshtinaBlagoevgrad,
      bulgariaBlagoevgradProvinceObshtinaGarmen,
      bulgariaBlagoevgradProvinceObshtinaGotseDelchev,
      bulgariaBlagoevgradProvinceObshtinaKresna,
      bulgariaBlagoevgradProvinceObshtinaPetrich,
      bulgariaBlagoevgradProvinceObshtinaRazlog,
      bulgariaBlagoevgradProvinceObshtinaSandanski,
      bulgariaBlagoevgradProvinceObshtinaSatovcha,
      bulgariaBlagoevgradProvinceObshtinaSimitli,
      bulgariaBlagoevgradProvinceObshtinaStrumyani,
      bulgariaBlagoevgradProvinceObshtinaYakoruda,
      bulgariaBlagoevgradProvincePetrich,
      bulgariaBlagoevgradProvinceRazlog,
      bulgariaBlagoevgradProvinceSandanski,
      bulgariaBlagoevgradProvinceSatovcha,
      bulgariaBlagoevgradProvinceSimitli,
      bulgariaBlagoevgradProvinceStaraKresna,
      bulgariaBlagoevgradProvinceStrumyani,
      bulgariaBlagoevgradProvinceYakoruda
    ]);
const Region bulgariaBurgasProvince = Region(
    id: 4715,
    parentId: 34,
    longitude: 27.4626079,
    latitude: 42.5048,
    name: "Burgas Province",
    type: null,
    stateCode: "02",
    cities: [
      bulgariaBurgasProvinceAheloy,
      bulgariaBurgasProvinceAhtopol,
      bulgariaBurgasProvinceAytos,
      bulgariaBurgasProvinceBata,
      bulgariaBurgasProvinceBurgas,
      bulgariaBurgasProvinceChernomorets,
      bulgariaBurgasProvinceKameno,
      bulgariaBurgasProvinceKarnobat,
      bulgariaBurgasProvinceKiten,
      bulgariaBurgasProvinceMalkoTarnovo,
      bulgariaBurgasProvinceNesebar,
      bulgariaBurgasProvinceObshtinaAytos,
      bulgariaBurgasProvinceObshtinaBurgas,
      bulgariaBurgasProvinceObshtinaKameno,
      bulgariaBurgasProvinceObshtinaKarnobat,
      bulgariaBurgasProvinceObshtinaMalkoTarnovo,
      bulgariaBurgasProvinceObshtinaNesebar,
      bulgariaBurgasProvinceObshtinaPomorie,
      bulgariaBurgasProvinceObshtinaPrimorsko,
      bulgariaBurgasProvinceObshtinaSozopol,
      bulgariaBurgasProvinceObshtinaSungurlare,
      bulgariaBurgasProvinceObzor,
      bulgariaBurgasProvincePomorie,
      bulgariaBurgasProvincePrimorsko,
      bulgariaBurgasProvinceRavda,
      bulgariaBurgasProvinceRuen,
      bulgariaBurgasProvinceSarafovo,
      bulgariaBurgasProvinceSozopol,
      bulgariaBurgasProvinceSredets,
      bulgariaBurgasProvinceSungurlare,
      bulgariaBurgasProvinceSvetiVlas,
      bulgariaBurgasProvinceTsarevo
    ]);
const Region bulgariaDobrichProvince = Region(
    id: 4718,
    parentId: 34,
    longitude: 27.8272802,
    latitude: 43.572786,
    name: "Dobrich Province",
    type: null,
    stateCode: "08",
    cities: [
      bulgariaDobrichProvinceBalchik,
      bulgariaDobrichProvinceDobrich,
      bulgariaDobrichProvinceGeneralToshevo,
      bulgariaDobrichProvinceKavarna,
      bulgariaDobrichProvinceKrushari,
      bulgariaDobrichProvinceObshtinaBalchik,
      bulgariaDobrichProvinceObshtinaDobrich,
      bulgariaDobrichProvinceObshtinaDobrichHypSelska,
      bulgariaDobrichProvinceObshtinaGeneralToshevo,
      bulgariaDobrichProvinceObshtinaKavarna,
      bulgariaDobrichProvinceObshtinaKrushari,
      bulgariaDobrichProvinceObshtinaShabla,
      bulgariaDobrichProvinceObshtinaTervel,
      bulgariaDobrichProvinceShabla,
      bulgariaDobrichProvinceTervel
    ]);
const Region bulgariaGabrovoProvince = Region(
    id: 4693,
    parentId: 34,
    longitude: 25.316889,
    latitude: 42.86847,
    name: "Gabrovo Province",
    type: null,
    stateCode: "07",
    cities: [
      bulgariaGabrovoProvinceDryanovo,
      bulgariaGabrovoProvinceGabrovo,
      bulgariaGabrovoProvinceObshtinaDryanovo,
      bulgariaGabrovoProvinceObshtinaGabrovo,
      bulgariaGabrovoProvinceObshtinaSevlievo,
      bulgariaGabrovoProvinceObshtinaTryavna,
      bulgariaGabrovoProvinceSevlievo,
      bulgariaGabrovoProvinceTryavna
    ]);
const Region bulgariaHaskovoProvince = Region(
    id: 4704,
    parentId: 34,
    longitude: 25.5554672,
    latitude: 41.9344178,
    name: "Haskovo Province",
    type: null,
    stateCode: "26",
    cities: [
      bulgariaHaskovoProvinceDimitrovgrad,
      bulgariaHaskovoProvinceHarmanli,
      bulgariaHaskovoProvinceHaskovo,
      bulgariaHaskovoProvinceIvaylovgrad,
      bulgariaHaskovoProvinceLyubimets,
      bulgariaHaskovoProvinceMadzharovo,
      bulgariaHaskovoProvinceMineralniBani,
      bulgariaHaskovoProvinceObshtinaDimitrovgrad,
      bulgariaHaskovoProvinceObshtinaHarmanli,
      bulgariaHaskovoProvinceObshtinaHaskovo,
      bulgariaHaskovoProvinceObshtinaIvaylovgrad,
      bulgariaHaskovoProvinceObshtinaMadzharovo,
      bulgariaHaskovoProvinceObshtinaMineralniBani,
      bulgariaHaskovoProvinceObshtinaStambolovo,
      bulgariaHaskovoProvinceObshtinaSvilengrad,
      bulgariaHaskovoProvinceObshtinaTopolovgrad,
      bulgariaHaskovoProvinceSimeonovgrad,
      bulgariaHaskovoProvinceSvilengrad,
      bulgariaHaskovoProvinceTopolovgrad
    ]);
const Region bulgariaKardzhaliProvince = Region(
    id: 4702,
    parentId: 34,
    longitude: 25.3776687,
    latitude: 41.6338416,
    name: "Kardzhali Province",
    type: null,
    stateCode: "09",
    cities: [
      bulgariaKardzhaliProvinceArdino,
      bulgariaKardzhaliProvinceDzhebel,
      bulgariaKardzhaliProvinceKardzhali,
      bulgariaKardzhaliProvinceKirkovo,
      bulgariaKardzhaliProvinceKrumovgrad,
      bulgariaKardzhaliProvinceObshtinaArdino,
      bulgariaKardzhaliProvinceObshtinaChernoochene,
      bulgariaKardzhaliProvinceObshtinaDzhebel,
      bulgariaKardzhaliProvinceObshtinaKardzhali,
      bulgariaKardzhaliProvinceObshtinaKirkovo,
      bulgariaKardzhaliProvinceObshtinaMomchilgrad
    ]);
const Region bulgariaKyustendilProvince = Region(
    id: 4703,
    parentId: 34,
    longitude: 22.6939635,
    latitude: 42.2868799,
    name: "Kyustendil Province",
    type: null,
    stateCode: "10",
    cities: [
      bulgariaKyustendilProvinceBoboshevo,
      bulgariaKyustendilProvinceBobovDol,
      bulgariaKyustendilProvinceDupnitsa,
      bulgariaKyustendilProvinceKocherinovo,
      bulgariaKyustendilProvinceKyustendil,
      bulgariaKyustendilProvinceNevestino,
      bulgariaKyustendilProvinceObshtinaBoboshevo,
      bulgariaKyustendilProvinceObshtinaBobovDol,
      bulgariaKyustendilProvinceObshtinaDupnitsa,
      bulgariaKyustendilProvinceObshtinaKocherinovo,
      bulgariaKyustendilProvinceObshtinaKyustendil,
      bulgariaKyustendilProvinceObshtinaNevestino,
      bulgariaKyustendilProvinceObshtinaRila,
      bulgariaKyustendilProvinceObshtinaSaparevaBanya,
      bulgariaKyustendilProvinceObshtinaTreklyano,
      bulgariaKyustendilProvinceRila,
      bulgariaKyustendilProvinceSaparevaBanya
    ]);
const Region bulgariaLovechProvince = Region(
    id: 4710,
    parentId: 34,
    longitude: 24.7139335,
    latitude: 43.1367798,
    name: "Lovech Province",
    type: null,
    stateCode: "11",
    cities: [
      bulgariaLovechProvinceApriltsi,
      bulgariaLovechProvinceLetnitsa,
      bulgariaLovechProvinceLovech,
      bulgariaLovechProvinceLukovit,
      bulgariaLovechProvinceObshtinaLovech,
      bulgariaLovechProvinceObshtinaTeteven,
      bulgariaLovechProvinceObshtinaUgarchin,
      bulgariaLovechProvinceTeteven,
      bulgariaLovechProvinceTroyan,
      bulgariaLovechProvinceUgarchin,
      bulgariaLovechProvinceYablanitsa
    ]);
const Region bulgariaMontanaProvince = Region(
    id: 4696,
    parentId: 34,
    longitude: 23.2257589,
    latitude: 43.4085148,
    name: "Montana Province",
    type: null,
    stateCode: "12",
    cities: [
      bulgariaMontanaProvinceBerkovitsa,
      bulgariaMontanaProvinceBoychinovtsi,
      bulgariaMontanaProvinceBrusartsi,
      bulgariaMontanaProvinceChiprovtsi,
      bulgariaMontanaProvinceLom,
      bulgariaMontanaProvinceMedkovets,
      bulgariaMontanaProvinceMontana,
      bulgariaMontanaProvinceObshtinaBoychinovtsi,
      bulgariaMontanaProvinceObshtinaChiprovtsi,
      bulgariaMontanaProvinceObshtinaGeorgiDamyanovo,
      bulgariaMontanaProvinceObshtinaLom,
      bulgariaMontanaProvinceObshtinaMontana,
      bulgariaMontanaProvinceObshtinaValchedram,
      bulgariaMontanaProvinceObshtinaVarshets,
      bulgariaMontanaProvinceObshtinaYakimovo,
      bulgariaMontanaProvinceValchedram,
      bulgariaMontanaProvinceVarshets,
      bulgariaMontanaProvinceYakimovo
    ]);
const Region bulgariaPazardzhikProvince = Region(
    id: 4712,
    parentId: 34,
    longitude: 24.3336226,
    latitude: 42.1927567,
    name: "Pazardzhik Province",
    type: null,
    stateCode: "13",
    cities: [
      bulgariaPazardzhikProvinceBatak,
      bulgariaPazardzhikProvinceBelovo,
      bulgariaPazardzhikProvinceBratsigovo,
      bulgariaPazardzhikProvinceLesichovo,
      bulgariaPazardzhikProvinceObshtinaBatak,
      bulgariaPazardzhikProvinceObshtinaBelovo,
      bulgariaPazardzhikProvinceObshtinaBratsigovo,
      bulgariaPazardzhikProvinceObshtinaLesichovo,
      bulgariaPazardzhikProvinceObshtinaPanagyurishte,
      bulgariaPazardzhikProvinceObshtinaPazardzhik,
      bulgariaPazardzhikProvinceObshtinaPeshtera,
      bulgariaPazardzhikProvinceObshtinaRakitovo,
      bulgariaPazardzhikProvinceObshtinaSeptemvri,
      bulgariaPazardzhikProvinceObshtinaStrelcha,
      bulgariaPazardzhikProvinceObshtinaVelingrad,
      bulgariaPazardzhikProvincePanagyurishte,
      bulgariaPazardzhikProvincePazardzhik,
      bulgariaPazardzhikProvincePeshtera,
      bulgariaPazardzhikProvinceRakitovo,
      bulgariaPazardzhikProvinceSarnitsa,
      bulgariaPazardzhikProvinceSarnitsaObshtina,
      bulgariaPazardzhikProvinceSeptemvri,
      bulgariaPazardzhikProvinceStrelcha,
      bulgariaPazardzhikProvinceVelingrad
    ]);
const Region bulgariaPernikProvince = Region(
    id: 4695,
    parentId: 34,
    longitude: 23.0377916,
    latitude: 42.605199,
    name: "Pernik Province",
    type: null,
    stateCode: "14",
    cities: [
      bulgariaPernikProvinceBatanovtsi,
      bulgariaPernikProvinceBreznik,
      bulgariaPernikProvinceObshtinaKovachevtsi,
      bulgariaPernikProvinceObshtinaPernik,
      bulgariaPernikProvinceObshtinaRadomir,
      bulgariaPernikProvinceObshtinaZemen,
      bulgariaPernikProvincePernik,
      bulgariaPernikProvinceRadomir,
      bulgariaPernikProvinceTran,
      bulgariaPernikProvinceZemen
    ]);
const Region bulgariaPlevenProvince = Region(
    id: 4706,
    parentId: 34,
    longitude: 24.6066708,
    latitude: 43.4170169,
    name: "Pleven Province",
    type: null,
    stateCode: "15",
    cities: [
      bulgariaPlevenProvinceBelene,
      bulgariaPlevenProvinceChervenBryag,
      bulgariaPlevenProvinceDolnaMitropolia,
      bulgariaPlevenProvinceDolniDabnik,
      bulgariaPlevenProvinceGulyantsi,
      bulgariaPlevenProvinceIskar,
      bulgariaPlevenProvinceKnezha,
      bulgariaPlevenProvinceKoynare,
      bulgariaPlevenProvinceLevski,
      bulgariaPlevenProvinceNikopol,
      bulgariaPlevenProvinceObshtinaBelene,
      bulgariaPlevenProvinceObshtinaChervenBryag,
      bulgariaPlevenProvinceObshtinaDolnaMitropolia,
      bulgariaPlevenProvinceObshtinaDolniDabnik,
      bulgariaPlevenProvinceObshtinaGulyantsi,
      bulgariaPlevenProvinceObshtinaIskar,
      bulgariaPlevenProvinceObshtinaKnezha,
      bulgariaPlevenProvinceObshtinaLevski,
      bulgariaPlevenProvinceObshtinaNikopol,
      bulgariaPlevenProvinceObshtinaPleven,
      bulgariaPlevenProvinceObshtinaPordim,
      bulgariaPlevenProvincePleven,
      bulgariaPlevenProvincePordim,
      bulgariaPlevenProvinceSlavyanovo
    ]);
const Region bulgariaPlovdivProvince = Region(
    id: 4701,
    parentId: 34,
    longitude: 24.7452904,
    latitude: 42.1354079,
    name: "Plovdiv Province",
    type: null,
    stateCode: "16",
    cities: [
      bulgariaPlovdivProvinceAsenovgrad,
      bulgariaPlovdivProvinceBrezovo,
      bulgariaPlovdivProvinceHisarya,
      bulgariaPlovdivProvinceKalofer,
      bulgariaPlovdivProvinceKaloyanovo,
      bulgariaPlovdivProvinceKarlovo,
      bulgariaPlovdivProvinceKlisura,
      bulgariaPlovdivProvinceKrichim,
      bulgariaPlovdivProvinceLaki,
      bulgariaPlovdivProvinceObshtinaAsenovgrad,
      bulgariaPlovdivProvinceObshtinaHisarya,
      bulgariaPlovdivProvinceObshtinaKaloyanovo,
      bulgariaPlovdivProvinceObshtinaKarlovo,
      bulgariaPlovdivProvinceObshtinaKrichim,
      bulgariaPlovdivProvinceObshtinaKuklen,
      bulgariaPlovdivProvinceObshtinaLaki,
      bulgariaPlovdivProvinceObshtinaMaritsa,
      bulgariaPlovdivProvinceObshtinaParvomay,
      bulgariaPlovdivProvinceObshtinaPerushtitsa,
      bulgariaPlovdivProvinceObshtinaPlovdiv,
      bulgariaPlovdivProvinceObshtinaRakovski,
      bulgariaPlovdivProvinceObshtinaRodopi,
      bulgariaPlovdivProvinceObshtinaSadovo,
      bulgariaPlovdivProvinceObshtinaSaedinenie,
      bulgariaPlovdivProvinceObshtinaSopot,
      bulgariaPlovdivProvinceObshtinaStamboliyski,
      bulgariaPlovdivProvinceParvomay,
      bulgariaPlovdivProvincePerushtitsa,
      bulgariaPlovdivProvincePlovdiv,
      bulgariaPlovdivProvinceRakovski,
      bulgariaPlovdivProvinceSadovo,
      bulgariaPlovdivProvinceSaedinenie,
      bulgariaPlovdivProvinceStamboliyski,
      bulgariaPlovdivProvinceTopolovo
    ]);
const Region bulgariaRazgradProvince = Region(
    id: 4698,
    parentId: 34,
    longitude: 26.5241228,
    latitude: 43.5271705,
    name: "Razgrad Province",
    type: null,
    stateCode: "17",
    cities: [
      bulgariaRazgradProvinceIsperih,
      bulgariaRazgradProvinceKubrat,
      bulgariaRazgradProvinceLoznitsa,
      bulgariaRazgradProvinceMedovene,
      bulgariaRazgradProvinceObshtinaIsperih,
      bulgariaRazgradProvinceObshtinaKubrat,
      bulgariaRazgradProvinceObshtinaLoznitsa,
      bulgariaRazgradProvinceObshtinaRazgrad,
      bulgariaRazgradProvinceObshtinaSamuil,
      bulgariaRazgradProvinceObshtinaTsarKaloyan,
      bulgariaRazgradProvinceObshtinaZavet,
      bulgariaRazgradProvinceRazgrad,
      bulgariaRazgradProvinceSamuil,
      bulgariaRazgradProvinceTsarKaloyan,
      bulgariaRazgradProvinceZavet
    ]);
const Region bulgariaRuseProvince = Region(
    id: 4713,
    parentId: 34,
    longitude: 25.9656144,
    latitude: 43.8355964,
    name: "Ruse Province",
    type: null,
    stateCode: "18",
    cities: [
      bulgariaRuseProvinceBorovo,
      bulgariaRuseProvinceDveMogili,
      bulgariaRuseProvinceIvanovo,
      bulgariaRuseProvinceObshtinaBorovo,
      bulgariaRuseProvinceObshtinaByala,
      bulgariaRuseProvinceObshtinaDveMogili,
      bulgariaRuseProvinceObshtinaIvanovo,
      bulgariaRuseProvinceObshtinaRuse,
      bulgariaRuseProvinceObshtinaSlivoPole,
      bulgariaRuseProvinceObshtinaTsenovo,
      bulgariaRuseProvinceObshtinaVetovo,
      bulgariaRuseProvinceRuse,
      bulgariaRuseProvinceSenovo,
      bulgariaRuseProvinceSlivoPole,
      bulgariaRuseProvinceTsenovo,
      bulgariaRuseProvinceVetovo
    ]);
const Region bulgariaShumen = Region(
    id: 4882,
    parentId: 34,
    longitude: 26.9361286,
    latitude: 43.2712398,
    name: "Shumen",
    type: null,
    stateCode: "27",
    cities: [bulgariaShumenShumen]);
const Region bulgariaSilistraProvince = Region(
    id: 4708,
    parentId: 34,
    longitude: 27.2671454,
    latitude: 44.1147101,
    name: "Silistra Province",
    type: null,
    stateCode: "19",
    cities: [
      bulgariaSilistraProvinceAlfatar,
      bulgariaSilistraProvinceDulovo,
      bulgariaSilistraProvinceGlavinitsa,
      bulgariaSilistraProvinceKaynardzha,
      bulgariaSilistraProvinceObshtinaAlfatar,
      bulgariaSilistraProvinceObshtinaDulovo,
      bulgariaSilistraProvinceObshtinaGlavinitsa,
      bulgariaSilistraProvinceObshtinaKaynardzha,
      bulgariaSilistraProvinceObshtinaSilistra,
      bulgariaSilistraProvinceObshtinaSitovo,
      bulgariaSilistraProvinceObshtinaTutrakan,
      bulgariaSilistraProvinceSilistra,
      bulgariaSilistraProvinceSitovo,
      bulgariaSilistraProvinceTutrakan
    ]);
const Region bulgariaSlivenProvince = Region(
    id: 4700,
    parentId: 34,
    longitude: 26.3228569,
    latitude: 42.6816702,
    name: "Sliven Province",
    type: null,
    stateCode: "20",
    cities: [
      bulgariaSlivenProvinceKermen,
      bulgariaSlivenProvinceKotel,
      bulgariaSlivenProvinceNovaZagora,
      bulgariaSlivenProvinceObshtinaKotel,
      bulgariaSlivenProvinceObshtinaNovaZagora,
      bulgariaSlivenProvinceObshtinaSliven,
      bulgariaSlivenProvinceObshtinaTvarditsa,
      bulgariaSlivenProvinceSliven,
      bulgariaSlivenProvinceTvarditsa
    ]);
const Region bulgariaSmolyanProvince = Region(
    id: 4694,
    parentId: 34,
    longitude: 24.7010871,
    latitude: 41.5774148,
    name: "Smolyan Province",
    type: null,
    stateCode: "21",
    cities: [
      bulgariaSmolyanProvinceBanite,
      bulgariaSmolyanProvinceBorino,
      bulgariaSmolyanProvinceChepelare,
      bulgariaSmolyanProvinceDevin,
      bulgariaSmolyanProvinceDospat,
      bulgariaSmolyanProvinceGyovren,
      bulgariaSmolyanProvinceMadan,
      bulgariaSmolyanProvinceNedelino,
      bulgariaSmolyanProvinceObshtinaBanite,
      bulgariaSmolyanProvinceObshtinaBorino,
      bulgariaSmolyanProvinceObshtinaChepelare,
      bulgariaSmolyanProvinceObshtinaDevin,
      bulgariaSmolyanProvinceObshtinaDospat,
      bulgariaSmolyanProvinceObshtinaMadan,
      bulgariaSmolyanProvinceObshtinaNedelino,
      bulgariaSmolyanProvinceObshtinaRudozem,
      bulgariaSmolyanProvinceObshtinaSmolyan,
      bulgariaSmolyanProvinceObshtinaZlatograd,
      bulgariaSmolyanProvinceRudozem,
      bulgariaSmolyanProvinceSmolyan,
      bulgariaSmolyanProvinceZlatograd
    ]);
const Region bulgariaSofiaCityProvince = Region(
    id: 4705,
    parentId: 34,
    longitude: 23.4504683,
    latitude: 42.7570109,
    name: "Sofia City Province",
    type: null,
    stateCode: "22",
    cities: [
      bulgariaSofiaCityProvinceBuhovo,
      bulgariaSofiaCityProvinceSofia,
      bulgariaSofiaCityProvinceStolichnaObshtina
    ]);
const Region bulgariaSofiaProvince = Region(
    id: 4719,
    parentId: 34,
    longitude: 23.8334937,
    latitude: 42.67344,
    name: "Sofia Province",
    type: null,
    stateCode: "23",
    cities: [
      bulgariaSofiaProvinceAnton,
      bulgariaSofiaProvinceBotevgrad,
      bulgariaSofiaProvinceBozhurishte,
      bulgariaSofiaProvinceChavdar,
      bulgariaSofiaProvinceChelopech,
      bulgariaSofiaProvinceDolnaBanya,
      bulgariaSofiaProvinceDragoman,
      bulgariaSofiaProvinceElinPelin,
      bulgariaSofiaProvinceEtropole,
      bulgariaSofiaProvinceGodech,
      bulgariaSofiaProvinceGornaMalina,
      bulgariaSofiaProvinceIhtiman,
      bulgariaSofiaProvinceKoprivshtitsa,
      bulgariaSofiaProvinceKostinbrod,
      bulgariaSofiaProvinceLakatnik,
      bulgariaSofiaProvinceMirkovo,
      bulgariaSofiaProvinceObshtinaAnton,
      bulgariaSofiaProvinceObshtinaBotevgrad,
      bulgariaSofiaProvinceObshtinaBozhurishte,
      bulgariaSofiaProvinceObshtinaChavdar,
      bulgariaSofiaProvinceObshtinaChelopech,
      bulgariaSofiaProvinceObshtinaDolnaBanya,
      bulgariaSofiaProvinceObshtinaDragoman,
      bulgariaSofiaProvinceObshtinaElinPelin,
      bulgariaSofiaProvinceObshtinaEtropole,
      bulgariaSofiaProvinceObshtinaGornaMalina,
      bulgariaSofiaProvinceObshtinaKoprivshtitsa,
      bulgariaSofiaProvinceObshtinaKostenets,
      bulgariaSofiaProvinceObshtinaKostinbrod,
      bulgariaSofiaProvinceObshtinaMirkovo,
      bulgariaSofiaProvinceObshtinaPirdop,
      bulgariaSofiaProvinceObshtinaPravets,
      bulgariaSofiaProvinceObshtinaSamokov,
      bulgariaSofiaProvinceObshtinaSlivnitsa,
      bulgariaSofiaProvinceObshtinaSvoge,
      bulgariaSofiaProvinceObshtinaZlatitsa,
      bulgariaSofiaProvincePirdop,
      bulgariaSofiaProvincePravets,
      bulgariaSofiaProvinceSamokov,
      bulgariaSofiaProvinceSlivnitsa,
      bulgariaSofiaProvinceSvoge,
      bulgariaSofiaProvinceZlatitsa
    ]);
const Region bulgariaStaraZagoraProvince = Region(
    id: 4707,
    parentId: 34,
    longitude: 25.6344855,
    latitude: 42.4257709,
    name: "Stara Zagora Province",
    type: null,
    stateCode: "24",
    cities: [
      bulgariaStaraZagoraProvinceAsen,
      bulgariaStaraZagoraProvinceChirpan,
      bulgariaStaraZagoraProvinceGulubovo,
      bulgariaStaraZagoraProvinceGurkovo,
      bulgariaStaraZagoraProvinceKazanlak,
      bulgariaStaraZagoraProvinceMaglizh,
      bulgariaStaraZagoraProvinceNikolaevo,
      bulgariaStaraZagoraProvinceObshtinaBratyaDaskalovi,
      bulgariaStaraZagoraProvinceObshtinaChirpan,
      bulgariaStaraZagoraProvinceObshtinaGalabovo,
      bulgariaStaraZagoraProvinceObshtinaGurkovo,
      bulgariaStaraZagoraProvinceObshtinaKazanluk,
      bulgariaStaraZagoraProvinceObshtinaMaglizh,
      bulgariaStaraZagoraProvinceObshtinaNikolaevo,
      bulgariaStaraZagoraProvinceObshtinaOpan,
      bulgariaStaraZagoraProvinceObshtinaPavelBanya,
      bulgariaStaraZagoraProvinceObshtinaRadnevo,
      bulgariaStaraZagoraProvinceObshtinaStaraZagora,
      bulgariaStaraZagoraProvincePavelBanya,
      bulgariaStaraZagoraProvinceRadnevo,
      bulgariaStaraZagoraProvinceShipka,
      bulgariaStaraZagoraProvinceStaraZagora
    ]);
const Region bulgariaTargovishteProvince = Region(
    id: 4714,
    parentId: 34,
    longitude: 26.5691251,
    latitude: 43.2462349,
    name: "Targovishte Province",
    type: null,
    stateCode: "25",
    cities: [
      bulgariaTargovishteProvinceAntonovo,
      bulgariaTargovishteProvinceObshtinaAntonovo,
      bulgariaTargovishteProvinceObshtinaOmurtag,
      bulgariaTargovishteProvinceObshtinaOpaka,
      bulgariaTargovishteProvinceObshtinaPopovo,
      bulgariaTargovishteProvinceObshtinaTargovishte,
      bulgariaTargovishteProvinceOmurtag,
      bulgariaTargovishteProvinceOpaka,
      bulgariaTargovishteProvincePopovo,
      bulgariaTargovishteProvinceTargovishte
    ]);
const Region bulgariaVarnaProvince = Region(
    id: 4717,
    parentId: 34,
    longitude: 27.9105488,
    latitude: 43.2046477,
    name: "Varna Province",
    type: null,
    stateCode: "03",
    cities: [
      bulgariaVarnaProvinceAksakovo,
      bulgariaVarnaProvinceAsparuhovo,
      bulgariaVarnaProvinceBalgarevo,
      bulgariaVarnaProvinceBeloslav,
      bulgariaVarnaProvinceByala,
      bulgariaVarnaProvinceDalgopol,
      bulgariaVarnaProvinceDevnya,
      bulgariaVarnaProvinceDolniChiflik,
      bulgariaVarnaProvinceKiten,
      bulgariaVarnaProvinceObshtinaAksakovo,
      bulgariaVarnaProvinceObshtinaAvren,
      bulgariaVarnaProvinceObshtinaBeloslav,
      bulgariaVarnaProvinceObshtinaByala,
      bulgariaVarnaProvinceObshtinaDalgopol,
      bulgariaVarnaProvinceObshtinaDevnya,
      bulgariaVarnaProvinceObshtinaDolniChiflik,
      bulgariaVarnaProvinceObshtinaProvadia,
      bulgariaVarnaProvinceObshtinaSuvorovo,
      bulgariaVarnaProvinceObshtinaValchidol,
      bulgariaVarnaProvinceObshtinaVarna,
      bulgariaVarnaProvinceObshtinaVetrino,
      bulgariaVarnaProvinceProvadia,
      bulgariaVarnaProvinceSuvorovo,
      bulgariaVarnaProvinceValchidol,
      bulgariaVarnaProvinceVarna,
      bulgariaVarnaProvinceVetrino,
      bulgariaVarnaProvinceZlatniPyasatsi
    ]);
const Region bulgariaVelikoTarnovoProvince = Region(
    id: 4709,
    parentId: 34,
    longitude: 25.61715,
    latitude: 43.0756539,
    name: "Veliko Tarnovo Province",
    type: null,
    stateCode: "04",
    cities: [
      bulgariaVelikoTarnovoProvinceByalaCherkva,
      bulgariaVelikoTarnovoProvinceDebelets,
      bulgariaVelikoTarnovoProvinceElena,
      bulgariaVelikoTarnovoProvinceGornaOryahovitsa,
      bulgariaVelikoTarnovoProvinceKilifarevo,
      bulgariaVelikoTarnovoProvinceLyaskovets,
      bulgariaVelikoTarnovoProvinceObshtinaElena,
      bulgariaVelikoTarnovoProvinceObshtinaGornaOryahovitsa,
      bulgariaVelikoTarnovoProvinceObshtinaLyaskovets,
      bulgariaVelikoTarnovoProvinceObshtinaPavlikeni,
      bulgariaVelikoTarnovoProvinceObshtinaPolskiTrambesh,
      bulgariaVelikoTarnovoProvinceObshtinaStrazhitsa,
      bulgariaVelikoTarnovoProvinceObshtinaSuhindol,
      bulgariaVelikoTarnovoProvinceObshtinaSvishtov,
      bulgariaVelikoTarnovoProvinceObshtinaVelikoTurnovo,
      bulgariaVelikoTarnovoProvinceObshtinaZlataritsa,
      bulgariaVelikoTarnovoProvinceParvomaytsi,
      bulgariaVelikoTarnovoProvincePavlikeni,
      bulgariaVelikoTarnovoProvincePolskiTrambesh,
      bulgariaVelikoTarnovoProvinceStrazhitsa,
      bulgariaVelikoTarnovoProvinceSuhindol,
      bulgariaVelikoTarnovoProvinceSvishtov,
      bulgariaVelikoTarnovoProvinceVelikoTurnovo,
      bulgariaVelikoTarnovoProvinceZlataritsa
    ]);
const Region bulgariaVidinProvince = Region(
    id: 4697,
    parentId: 34,
    longitude: 22.8679515,
    latitude: 43.9961739,
    name: "Vidin Province",
    type: null,
    stateCode: "05",
    cities: [
      bulgariaVidinProvinceBelogradchik,
      bulgariaVidinProvinceBoynitsa,
      bulgariaVidinProvinceBregovo,
      bulgariaVidinProvinceChuprene,
      bulgariaVidinProvinceDimovo,
      bulgariaVidinProvinceDrenovets,
      bulgariaVidinProvinceDunavtsi,
      bulgariaVidinProvinceGramada,
      bulgariaVidinProvinceKula,
      bulgariaVidinProvinceMakresh,
      bulgariaVidinProvinceNovoSelo,
      bulgariaVidinProvinceObshtinaBelogradchik,
      bulgariaVidinProvinceObshtinaBoynitsa,
      bulgariaVidinProvinceObshtinaDimovo,
      bulgariaVidinProvinceObshtinaGramada,
      bulgariaVidinProvinceObshtinaKula,
      bulgariaVidinProvinceObshtinaRuzhintsi,
      bulgariaVidinProvinceObshtinaVidin,
      bulgariaVidinProvinceRuzhintsi,
      bulgariaVidinProvinceVidin
    ]);
const Region bulgariaVratsaProvince = Region(
    id: 4711,
    parentId: 34,
    longitude: 23.552921,
    latitude: 43.2101806,
    name: "Vratsa Province",
    type: null,
    stateCode: "06",
    cities: [
      bulgariaVratsaProvinceBorovan,
      bulgariaVratsaProvinceByalaSlatina,
      bulgariaVratsaProvinceHayredin,
      bulgariaVratsaProvinceKozloduy,
      bulgariaVratsaProvinceKrivodol,
      bulgariaVratsaProvinceMezdra,
      bulgariaVratsaProvinceMizia,
      bulgariaVratsaProvinceObshtinaBorovan,
      bulgariaVratsaProvinceObshtinaHayredin,
      bulgariaVratsaProvinceObshtinaKozloduy,
      bulgariaVratsaProvinceObshtinaKrivodol,
      bulgariaVratsaProvinceObshtinaMezdra,
      bulgariaVratsaProvinceObshtinaMizia,
      bulgariaVratsaProvinceObshtinaOryahovo,
      bulgariaVratsaProvinceObshtinaRoman,
      bulgariaVratsaProvinceObshtinaVratsa,
      bulgariaVratsaProvinceOryahovo,
      bulgariaVratsaProvinceRoman,
      bulgariaVratsaProvinceVratsa
    ]);
const Region bulgariaYambolProvince = Region(
    id: 4716,
    parentId: 34,
    longitude: 26.5035296,
    latitude: 42.4841494,
    name: "Yambol Province",
    type: null,
    stateCode: "28",
    cities: [
      bulgariaYambolProvinceBolyarovo,
      bulgariaYambolProvinceElhovo,
      bulgariaYambolProvinceObshtinaBolyarovo,
      bulgariaYambolProvinceObshtinaElhovo,
      bulgariaYambolProvinceObshtinaStraldzha,
      bulgariaYambolProvinceObshtinaTundzha,
      bulgariaYambolProvinceObshtinaYambol,
      bulgariaYambolProvinceStraldzha,
      bulgariaYambolProvinceYambol
    ]);

const bulgariaStates = <int, Region>{
  4699: bulgariaBlagoevgradProvince,
  4715: bulgariaBurgasProvince,
  4718: bulgariaDobrichProvince,
  4693: bulgariaGabrovoProvince,
  4704: bulgariaHaskovoProvince,
  4702: bulgariaKardzhaliProvince,
  4703: bulgariaKyustendilProvince,
  4710: bulgariaLovechProvince,
  4696: bulgariaMontanaProvince,
  4712: bulgariaPazardzhikProvince,
  4695: bulgariaPernikProvince,
  4706: bulgariaPlevenProvince,
  4701: bulgariaPlovdivProvince,
  4698: bulgariaRazgradProvince,
  4713: bulgariaRuseProvince,
  4882: bulgariaShumen,
  4708: bulgariaSilistraProvince,
  4700: bulgariaSlivenProvince,
  4694: bulgariaSmolyanProvince,
  4705: bulgariaSofiaCityProvince,
  4719: bulgariaSofiaProvince,
  4707: bulgariaStaraZagoraProvince,
  4714: bulgariaTargovishteProvince,
  4717: bulgariaVarnaProvince,
  4709: bulgariaVelikoTarnovoProvince,
  4697: bulgariaVidinProvince,
  4711: bulgariaVratsaProvince,
  4716: bulgariaYambolProvince
};
