/// Access to known geographies in `Chile` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'chile_cities.dart';

/// The `Aisén del General Carlos Ibañez del Campo` region in `Chile`
const Region chileAisenDelGeneralCarlosIbanezDelCampo = Region(
  id: 2828,
  parentId: 44,
  longitude: -72.3007623,
  latitude: -46.378345,
  name: "Aisén del General Carlos Ibañez del Campo",
  type: null,
  stateCode: "AI",
  cities: [
    aisenDelGeneralCarlosIbanezDelCampoAysenCity,
    aisenDelGeneralCarlosIbanezDelCampoChileChicoCity,
    aisenDelGeneralCarlosIbanezDelCampoCisnesCity,
    aisenDelGeneralCarlosIbanezDelCampoCochraneCity,
    aisenDelGeneralCarlosIbanezDelCampoCoyhaiqueCity,
    aisenDelGeneralCarlosIbanezDelCampoGuaitecasCity,
    aisenDelGeneralCarlosIbanezDelCampoLagoVerdeCity,
    aisenDelGeneralCarlosIbanezDelCampoOhigginsCity,
    aisenDelGeneralCarlosIbanezDelCampoRioIbanezCity,
    aisenDelGeneralCarlosIbanezDelCampoTortelCity
  ]);

/// The `Antofagasta` region in `Chile`
const Region chileAntofagasta = Region(
  id: 2832,
  parentId: 44,
  longitude: -69.2877535,
  latitude: -23.8369104,
  name: "Antofagasta",
  type: null,
  stateCode: "AN",
  cities: [
    antofagastaAntofagastaCity,
    antofagastaCalamaCity,
    antofagastaMariaElenaCity,
    antofagastaMejillonesCity,
    antofagastaOllagueCity,
    antofagastaSanPedroDeAtacamaCity,
    antofagastaSierraGordaCity,
    antofagastaTaltalCity,
    antofagastaTocopillaCity
  ]);

/// The `Arica y Parinacota` region in `Chile`
const Region chileAricaYParinacota = Region(
  id: 2829,
  parentId: 44,
  longitude: -69.4784541,
  latitude: -18.5940485,
  name: "Arica y Parinacota",
  type: null,
  stateCode: "AP",
  cities: [
    aricaYParinacotaAricaCity,
    aricaYParinacotaCamaronesCity,
    aricaYParinacotaGeneralLagosCity,
    aricaYParinacotaPutreCity
  ]);

/// The `Atacama` region in `Chile`
const Region chileAtacama = Region(
  id: 2823,
  parentId: 44,
  longitude: -70.050314,
  latitude: -27.5660558,
  name: "Atacama",
  type: null,
  stateCode: "AT",
  cities: [
    atacamaAltoDelCarmenCity,
    atacamaCalderaCity,
    atacamaChanaralCity,
    atacamaCopiapoCity,
    atacamaDiegoDeAlmagroCity,
    atacamaFreirinaCity,
    atacamaHuascoCity,
    atacamaTierraAmarillaCity,
    atacamaVallenarCity
  ]);

/// The `Biobío` region in `Chile`
const Region chileBiobio = Region(
  id: 2827,
  parentId: 44,
  longitude: -72.1416132,
  latitude: -37.4464428,
  name: "Biobío",
  type: null,
  stateCode: "BI",
  cities: [
    biobioAltoBiobioCity,
    biobioAntucoCity,
    biobioAraucoCity,
    biobioCabreroCity,
    biobioCaneteCity,
    biobioChiguayanteCity,
    biobioConcepcionCity,
    biobioContulmoCity,
    biobioCoronelCity,
    biobioCuranilahueCity,
    biobioFloridaCity,
    biobioHualpenCity,
    biobioHualquiCity,
    biobioLajaCity,
    biobioLebuCity,
    biobioLosAlamosCity,
    biobioLosAngelesCity,
    biobioLotaCity,
    biobioMulchenCity,
    biobioNacimientoCity,
    biobioNegreteCity,
    biobioPencoCity,
    biobioQuilacoCity,
    biobioQuillecoCity,
    biobioSanPedroDeLaPazCity,
    biobioSanRosendoCity,
    biobioSantaBarbaraCity,
    biobioSantaJuanaCity,
    biobioTalcahuanoCity,
    biobioTiruaCity,
    biobioTomeCity,
    biobioTucapelCity,
    biobioYumbelCity
  ]);

/// The `Coquimbo` region in `Chile`
const Region chileCoquimbo = Region(
  id: 2825,
  parentId: 44,
  longitude: -70.8119953,
  latitude: -30.540181,
  name: "Coquimbo",
  type: null,
  stateCode: "CO",
  cities: [
    coquimboAndacolloCity,
    coquimboCanelaCity,
    coquimboCombarbalaCity,
    coquimboCoquimboCity,
    coquimboIllapelCity,
    coquimboLaHigueraCity,
    coquimboLaSerenaCity,
    coquimboLosVilosCity,
    coquimboMontePatriaCity,
    coquimboOvalleCity,
    coquimboPaihuanoCity,
    coquimboPunitaquiCity,
    coquimboRioHurtadoCity,
    coquimboSalamancaCity,
    coquimboVicunaCity
  ]);

/// The `La Araucanía` region in `Chile`
const Region chileLaAraucania = Region(
  id: 2826,
  parentId: 44,
  longitude: -72.331113,
  latitude: -38.948921,
  name: "La Araucanía",
  type: null,
  stateCode: "AR",
  cities: [
    laAraucaniaAngolCity,
    laAraucaniaCarahueCity,
    laAraucaniaCholcholCity,
    laAraucaniaCollipulliCity,
    laAraucaniaCuncoCity,
    laAraucaniaCuracautinCity,
    laAraucaniaCurarrehueCity,
    laAraucaniaErcillaCity,
    laAraucaniaFreireCity,
    laAraucaniaGalvarinoCity,
    laAraucaniaGorbeaCity,
    laAraucaniaLautaroCity,
    laAraucaniaLoncocheCity,
    laAraucaniaLonquimayCity,
    laAraucaniaLosSaucesCity,
    laAraucaniaLumacoCity,
    laAraucaniaMelipeucoCity,
    laAraucaniaNuevaImperialCity,
    laAraucaniaPadreLasCasasCity,
    laAraucaniaPerquencoCity,
    laAraucaniaPitrufquenCity,
    laAraucaniaPuconCity,
    laAraucaniaPurenCity,
    laAraucaniaRenaicoCity,
    laAraucaniaSaavedraCity,
    laAraucaniaTemucoCity,
    laAraucaniaTeodoroSchmidtCity,
    laAraucaniaToltenCity,
    laAraucaniaTraiguenCity,
    laAraucaniaVictoriaCity,
    laAraucaniaVilcunCity,
    laAraucaniaVillarricaCity
  ]);

/// The `Libertador General Bernardo O'Higgins` region in `Chile`
const Region chileLibertadorGeneralBernardoOhiggins = Region(
  id: 2838,
  parentId: 44,
  longitude: -71.0022311,
  latitude: -34.5755374,
  name: "Libertador General Bernardo O'Higgins",
  type: null,
  stateCode: "LI",
  cities: [
    libertadorGeneralBernardoOhigginsChepicaCity,
    libertadorGeneralBernardoOhigginsChimbarongoCity,
    libertadorGeneralBernardoOhigginsCodeguaCity,
    libertadorGeneralBernardoOhigginsCoincoCity,
    libertadorGeneralBernardoOhigginsColtaucoCity,
    libertadorGeneralBernardoOhigginsDonihueCity,
    libertadorGeneralBernardoOhigginsGranerosCity,
    libertadorGeneralBernardoOhigginsLaEstrellaCity,
    libertadorGeneralBernardoOhigginsLasCabrasCity,
    libertadorGeneralBernardoOhigginsLituecheCity,
    libertadorGeneralBernardoOhigginsLololCity,
    libertadorGeneralBernardoOhigginsMachaliCity,
    libertadorGeneralBernardoOhigginsMalloaCity,
    libertadorGeneralBernardoOhigginsMarchigueCity,
    libertadorGeneralBernardoOhigginsMostazalCity,
    libertadorGeneralBernardoOhigginsNancaguaCity,
    libertadorGeneralBernardoOhigginsNavidadCity,
    libertadorGeneralBernardoOhigginsOlivarCity,
    libertadorGeneralBernardoOhigginsPalmillaCity,
    libertadorGeneralBernardoOhigginsParedonesCity,
    libertadorGeneralBernardoOhigginsPeralilloCity,
    libertadorGeneralBernardoOhigginsPeumoCity,
    libertadorGeneralBernardoOhigginsPichideguaCity,
    libertadorGeneralBernardoOhigginsPichilemuCity,
    libertadorGeneralBernardoOhigginsPlacillaCity,
    libertadorGeneralBernardoOhigginsPumanqueCity,
    libertadorGeneralBernardoOhigginsQuintaDeTilcocoCity,
    libertadorGeneralBernardoOhigginsRancaguaCity,
    libertadorGeneralBernardoOhigginsRengoCity,
    libertadorGeneralBernardoOhigginsRequinoaCity,
    libertadorGeneralBernardoOhigginsSanFernandoCity,
    libertadorGeneralBernardoOhigginsSanVicenteCity,
    libertadorGeneralBernardoOhigginsSantaCruzCity
  ]);

/// The `Los Lagos` region in `Chile`
const Region chileLosLagos = Region(
  id: 2835,
  parentId: 44,
  longitude: -72.1416132,
  latitude: -41.9197779,
  name: "Los Lagos",
  type: null,
  stateCode: "LL",
  cities: [
    losLagosAncudCity,
    losLagosCalbucoCity,
    losLagosCastroCity,
    losLagosChaitenCity,
    losLagosChonchiCity,
    losLagosCochamoCity,
    losLagosCuracoDeVelezCity,
    losLagosDalcahueCity,
    losLagosFresiaCity,
    losLagosFrutillarCity,
    losLagosFutaleufuCity,
    losLagosHualaihueCity,
    losLagosLlanquihueCity,
    losLagosLosMuermosCity,
    losLagosMaullinCity,
    losLagosOsornoCity,
    losLagosPalenaCity,
    losLagosPuertoMonttCity,
    losLagosPuertoOctayCity,
    losLagosPuertoVarasCity,
    losLagosPuqueldonCity,
    losLagosPurranqueCity,
    losLagosPuyehueCity,
    losLagosQueilenCity,
    losLagosQuellonCity,
    losLagosQuemchiCity,
    losLagosQuinchaoCity,
    losLagosRioNegroCity,
    losLagosSanJuanDeLaCostaCity,
    losLagosSanPabloCity
  ]);

/// The `Los Ríos` region in `Chile`
const Region chileLosRios = Region(
  id: 2834,
  parentId: 44,
  longitude: -72.331113,
  latitude: -40.2310217,
  name: "Los Ríos",
  type: null,
  stateCode: "LR",
  cities: [
    losRiosCorralCity,
    losRiosFutronoCity,
    losRiosLaUnionCity,
    losRiosLagoRancoCity,
    losRiosLancoCity,
    losRiosLosLagosCity,
    losRiosMafilCity,
    losRiosMariquinaCity,
    losRiosPaillacoCity,
    losRiosPanguipulliCity,
    losRiosRioBuenoCity,
    losRiosValdiviaCity
  ]);

/// The `Magallanes y de la Antártica Chilena` region in `Chile`
const Region chileMagallanesYDeLaAntarticaChilena = Region(
  id: 2836,
  parentId: 44,
  longitude: -72.1685001,
  latitude: -52.2064316,
  name: "Magallanes y de la Antártica Chilena",
  type: null,
  stateCode: "MA",
  cities: [
    magallanesYDeLaAntarticaChilenaAntarticaCity,
    magallanesYDeLaAntarticaChilenaCaboDeHornosCity,
    magallanesYDeLaAntarticaChilenaLagunaBlancaCity,
    magallanesYDeLaAntarticaChilenaNatalesCity,
    magallanesYDeLaAntarticaChilenaPorvenirCity,
    magallanesYDeLaAntarticaChilenaPrimaveraCity,
    magallanesYDeLaAntarticaChilenaPuntaArenasCity,
    magallanesYDeLaAntarticaChilenaRioVerdeCity,
    magallanesYDeLaAntarticaChilenaSanGregorioCity,
    magallanesYDeLaAntarticaChilenaTimaukelCity,
    magallanesYDeLaAntarticaChilenaTorresDelPaineCity
  ]);

/// The `Maule` region in `Chile`
const Region chileMaule = Region(
  id: 2833,
  parentId: 44,
  longitude: -71.5723953,
  latitude: -35.5163603,
  name: "Maule",
  type: null,
  stateCode: "ML",
  cities: [
    mauleCauquenesCity,
    mauleChancoCity,
    mauleColbunCity,
    mauleConstitucionCity,
    mauleCureptoCity,
    mauleCuricoCity,
    mauleEmpedradoCity,
    mauleHualaneCity,
    mauleLicantenCity,
    mauleLinaresCity,
    mauleLongaviCity,
    mauleMauleCity,
    mauleMolinaCity,
    mauleParralCity,
    maulePelarcoCity,
    maulePelluhueCity,
    maulePencahueCity,
    mauleRaucoCity,
    mauleRetiroCity,
    mauleRioClaroCity,
    mauleRomeralCity,
    mauleSagradaFamiliaCity,
    mauleSanClementeCity,
    mauleSanJavierCity,
    mauleSanRafaelCity,
    mauleTalcaCity,
    mauleTenoCity,
    mauleVichuquenCity,
    mauleVillaAlegreCity,
    mauleYerbasBuenasCity
  ]);

/// The `Ñuble` region in `Chile`
const Region chileNuble = Region(
  id: 2831,
  parentId: 44,
  longitude: -71.7622481,
  latitude: -36.7225743,
  name: "Ñuble",
  type: null,
  stateCode: "NB",
  cities: [
    nubleBulnesCity,
    nubleChillanCity,
    nubleChillanViejoCity,
    nubleCobquecuraCity,
    nubleCoelemuCity,
    nubleCoihuecoCity,
    nubleElCarmenCity,
    nubleNinhueCity,
    nubleNiquenCity,
    nublePemucoCity,
    nublePintoCity,
    nublePortezueloCity,
    nubleQuillonCity,
    nubleQuirihueCity,
    nubleRanquilCity,
    nubleSanCarlosCity,
    nubleSanFabianCity,
    nubleSanIgnacioCity,
    nubleSanNicolasCity,
    nubleTreguacoCity,
    nubleYungayCity
  ]);

/// The `Región Metropolitana de Santiago` region in `Chile`
const Region chileRegionMetropolitanaDeSantiago = Region(
  id: 2824,
  parentId: 44,
  longitude: -70.6504896,
  latitude: -33.4375545,
  name: "Región Metropolitana de Santiago",
  type: null,
  stateCode: "RM",
  cities: [
    regionMetropolitanaDeSantiagoAlhueCity,
    regionMetropolitanaDeSantiagoBuinCity,
    regionMetropolitanaDeSantiagoCaleraDeTangoCity,
    regionMetropolitanaDeSantiagoCerrillosCity,
    regionMetropolitanaDeSantiagoCerroNaviaCity,
    regionMetropolitanaDeSantiagoColinaCity,
    regionMetropolitanaDeSantiagoConchaliCity,
    regionMetropolitanaDeSantiagoCuracaviCity,
    regionMetropolitanaDeSantiagoElBosqueCity,
    regionMetropolitanaDeSantiagoElMonteCity,
    regionMetropolitanaDeSantiagoEstacionCentralCity,
    regionMetropolitanaDeSantiagoHuechurabaCity,
    regionMetropolitanaDeSantiagoIndependenciaCity,
    regionMetropolitanaDeSantiagoIslaDeMaipoCity,
    regionMetropolitanaDeSantiagoLaCisternaCity,
    regionMetropolitanaDeSantiagoLaFloridaCity,
    regionMetropolitanaDeSantiagoLaGranjaCity,
    regionMetropolitanaDeSantiagoLaPintanaCity,
    regionMetropolitanaDeSantiagoLaReinaCity,
    regionMetropolitanaDeSantiagoLampaCity,
    regionMetropolitanaDeSantiagoLasCondesCity,
    regionMetropolitanaDeSantiagoLoBarnecheaCity,
    regionMetropolitanaDeSantiagoLoEspejoCity,
    regionMetropolitanaDeSantiagoLoPradoCity,
    regionMetropolitanaDeSantiagoMaculCity,
    regionMetropolitanaDeSantiagoMaipuCity,
    regionMetropolitanaDeSantiagoMariaPintoCity,
    regionMetropolitanaDeSantiagoMelipillaCity,
    regionMetropolitanaDeSantiagoNunoaCity,
    regionMetropolitanaDeSantiagoPadreHurtadoCity,
    regionMetropolitanaDeSantiagoPaineCity,
    regionMetropolitanaDeSantiagoPedroAguirreCerdaCity,
    regionMetropolitanaDeSantiagoPenaflorCity,
    regionMetropolitanaDeSantiagoPenalolenCity,
    regionMetropolitanaDeSantiagoPirqueCity,
    regionMetropolitanaDeSantiagoProvidenciaCity,
    regionMetropolitanaDeSantiagoPudahuelCity,
    regionMetropolitanaDeSantiagoPuenteAltoCity,
    regionMetropolitanaDeSantiagoQuilicuraCity,
    regionMetropolitanaDeSantiagoQuintaNormalCity,
    regionMetropolitanaDeSantiagoRecoletaCity,
    regionMetropolitanaDeSantiagoRencaCity,
    regionMetropolitanaDeSantiagoSanBernardoCity,
    regionMetropolitanaDeSantiagoSanJoaquinCity,
    regionMetropolitanaDeSantiagoSanJoseDeMaipoCity,
    regionMetropolitanaDeSantiagoSanMiguelCity,
    regionMetropolitanaDeSantiagoSanPedroCity,
    regionMetropolitanaDeSantiagoSanRamonCity,
    regionMetropolitanaDeSantiagoSantiagoCity,
    regionMetropolitanaDeSantiagoTalaganteCity,
    regionMetropolitanaDeSantiagoTiltilCity,
    regionMetropolitanaDeSantiagoVitacuraCity
  ]);

/// The `Tarapacá` region in `Chile`
const Region chileTarapaca = Region(
  id: 2837,
  parentId: 44,
  longitude: -69.2877535,
  latitude: -20.2028799,
  name: "Tarapacá",
  type: null,
  stateCode: "TA",
  cities: [
    tarapacaAltoHospicioCity,
    tarapacaCaminaCity,
    tarapacaColchaneCity,
    tarapacaHuaraCity,
    tarapacaIquiqueCity,
    tarapacaPicaCity,
    tarapacaPozoAlmonteCity
  ]);

/// The `Valparaíso` region in `Chile`
const Region chileValparaiso = Region(
  id: 2830,
  parentId: 44,
  longitude: -71.6126885,
  latitude: -33.047238,
  name: "Valparaíso",
  type: null,
  stateCode: "VS",
  cities: [
    valparaisoAlgarroboCity,
    valparaisoCabildoCity,
    valparaisoCalleLargaCity,
    valparaisoCartagenaCity,
    valparaisoCasablancaCity,
    valparaisoCatemuCity,
    valparaisoConconCity,
    valparaisoElQuiscoCity,
    valparaisoElTaboCity,
    valparaisoHijuelasCity,
    valparaisoIslaDePascuaCity,
    valparaisoJuanFernandezCity,
    valparaisoLaCaleraCity,
    valparaisoLaCruzCity,
    valparaisoLaLiguaCity,
    valparaisoLimacheCity,
    valparaisoLlaillayCity,
    valparaisoLosAndesCity,
    valparaisoNogalesCity,
    valparaisoOlmueCity,
    valparaisoPanquehueCity,
    valparaisoPapudoCity,
    valparaisoPetorcaCity,
    valparaisoPuchuncaviCity,
    valparaisoPutaendoCity,
    valparaisoQuillotaCity,
    valparaisoQuilpueCity,
    valparaisoQuinteroCity,
    valparaisoRinconadaCity,
    valparaisoSanAntonioCity,
    valparaisoSanEstebanCity,
    valparaisoSanFelipeCity,
    valparaisoSantaMariaCity,
    valparaisoSantoDomingoCity,
    valparaisoValparaisoCity,
    valparaisoVillaAlemanaCity,
    valparaisoVinaDelMarCity,
    valparaisoZapallarCity
  ]);

/// The 16 states of `Chile` keyed by their id.
const Map<int, Region> chileStates = <int, Region>{
    2828: chileAisenDelGeneralCarlosIbanezDelCampo,
    2832: chileAntofagasta,
    2829: chileAricaYParinacota,
    2823: chileAtacama,
    2827: chileBiobio,
    2825: chileCoquimbo,
    2826: chileLaAraucania,
    2838: chileLibertadorGeneralBernardoOhiggins,
    2835: chileLosLagos,
    2834: chileLosRios,
    2836: chileMagallanesYDeLaAntarticaChilena,
    2833: chileMaule,
    2831: chileNuble,
    2824: chileRegionMetropolitanaDeSantiago,
    2837: chileTarapaca,
    2830: chileValparaiso
  };
