/// Access to known geographies in Chile and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'chile_cities.dart';

/// The 16 regions of `🇨🇱 Chile`
const Region chileAisenDdelGeneralCarlosIbanezDdelCampo = Region(
    id: 2828,
    parentId: 44,
    longitude: -72.3007623,
    latitude: -46.378345,
    name: "Aisén del General Carlos Ibañez del Campo",
    type: null,
    stateCode: "AI",
    cities: [
      chileAisenDdelGeneralCarlosIbanezDdelCampoAysen,
      chileAisenDdelGeneralCarlosIbanezDdelCampoChileChico,
      chileAisenDdelGeneralCarlosIbanezDdelCampoCisnes,
      chileAisenDdelGeneralCarlosIbanezDdelCampoCochrane,
      chileAisenDdelGeneralCarlosIbanezDdelCampoCoyhaique,
      chileAisenDdelGeneralCarlosIbanezDdelCampoGuaitecas,
      chileAisenDdelGeneralCarlosIbanezDdelCampoLagoVerde,
      chileAisenDdelGeneralCarlosIbanezDdelCampoOHiggins,
      chileAisenDdelGeneralCarlosIbanezDdelCampoRioIbanez,
      chileAisenDdelGeneralCarlosIbanezDdelCampoTortel
    ]);
const Region chileAntofagasta = Region(
    id: 2832,
    parentId: 44,
    longitude: -69.2877535,
    latitude: -23.8369104,
    name: "Antofagasta",
    type: null,
    stateCode: "AN",
    cities: [
      chileAntofagastaAntofagasta,
      chileAntofagastaCalama,
      chileAntofagastaMariaElena,
      chileAntofagastaMejillones,
      chileAntofagastaOllague,
      chileAntofagastaSanPedroDdeAtacama,
      chileAntofagastaSierraGorda,
      chileAntofagastaTaltal,
      chileAntofagastaTocopilla
    ]);
const Region chileAricaYyParinacota = Region(
    id: 2829,
    parentId: 44,
    longitude: -69.4784541,
    latitude: -18.5940485,
    name: "Arica y Parinacota",
    type: null,
    stateCode: "AP",
    cities: [
      chileAricaYyParinacotaArica,
      chileAricaYyParinacotaCamarones,
      chileAricaYyParinacotaGeneralLagos,
      chileAricaYyParinacotaPutre
    ]);
const Region chileAtacama = Region(
    id: 2823,
    parentId: 44,
    longitude: -70.050314,
    latitude: -27.5660558,
    name: "Atacama",
    type: null,
    stateCode: "AT",
    cities: [
      chileAtacamaAltoDdelCarmen,
      chileAtacamaCaldera,
      chileAtacamaChanaral,
      chileAtacamaCopiapo,
      chileAtacamaDiegoDdeAlmagro,
      chileAtacamaFreirina,
      chileAtacamaHuasco,
      chileAtacamaTierraAmarilla,
      chileAtacamaVallenar
    ]);
const Region chileBiobio = Region(
    id: 2827,
    parentId: 44,
    longitude: -72.1416132,
    latitude: -37.4464428,
    name: "Biobío",
    type: null,
    stateCode: "BI",
    cities: [
      chileBiobioAltoBiobio,
      chileBiobioAntuco,
      chileBiobioArauco,
      chileBiobioCabrero,
      chileBiobioCanete,
      chileBiobioChiguayante,
      chileBiobioConcepcion,
      chileBiobioContulmo,
      chileBiobioCoronel,
      chileBiobioCuranilahue,
      chileBiobioFlorida,
      chileBiobioHualpen,
      chileBiobioHualqui,
      chileBiobioLaja,
      chileBiobioLebu,
      chileBiobioLosAlamos,
      chileBiobioLosAngeles,
      chileBiobioLota,
      chileBiobioMulchen,
      chileBiobioNacimiento,
      chileBiobioNegrete,
      chileBiobioPenco,
      chileBiobioQuilaco,
      chileBiobioQuilleco,
      chileBiobioSanPedroDdeLlaPaz,
      chileBiobioSanRosendo,
      chileBiobioSantaBarbara,
      chileBiobioSantaJuana,
      chileBiobioTalcahuano,
      chileBiobioTirua,
      chileBiobioTome,
      chileBiobioTucapel,
      chileBiobioYumbel
    ]);
const Region chileCoquimbo = Region(
    id: 2825,
    parentId: 44,
    longitude: -70.8119953,
    latitude: -30.540181,
    name: "Coquimbo",
    type: null,
    stateCode: "CO",
    cities: [
      chileCoquimboAndacollo,
      chileCoquimboCanela,
      chileCoquimboCombarbala,
      chileCoquimboCoquimbo,
      chileCoquimboIllapel,
      chileCoquimboLaHiguera,
      chileCoquimboLaSerena,
      chileCoquimboLosVilos,
      chileCoquimboMontePatria,
      chileCoquimboOvalle,
      chileCoquimboPaihuano,
      chileCoquimboPunitaqui,
      chileCoquimboRioHurtado,
      chileCoquimboSalamanca,
      chileCoquimboVicuna
    ]);
const Region chileLaAraucania = Region(
    id: 2826,
    parentId: 44,
    longitude: -72.331113,
    latitude: -38.948921,
    name: "La Araucanía",
    type: null,
    stateCode: "AR",
    cities: [
      chileLaAraucaniaAngol,
      chileLaAraucaniaCarahue,
      chileLaAraucaniaCholchol,
      chileLaAraucaniaCollipulli,
      chileLaAraucaniaCunco,
      chileLaAraucaniaCuracautin,
      chileLaAraucaniaCurarrehue,
      chileLaAraucaniaErcilla,
      chileLaAraucaniaFreire,
      chileLaAraucaniaGalvarino,
      chileLaAraucaniaGorbea,
      chileLaAraucaniaLautaro,
      chileLaAraucaniaLoncoche,
      chileLaAraucaniaLonquimay,
      chileLaAraucaniaLosSauces,
      chileLaAraucaniaLumaco,
      chileLaAraucaniaMelipeuco,
      chileLaAraucaniaNuevaImperial,
      chileLaAraucaniaPadreLasCasas,
      chileLaAraucaniaPerquenco,
      chileLaAraucaniaPitrufquen,
      chileLaAraucaniaPucon,
      chileLaAraucaniaPuren,
      chileLaAraucaniaRenaico,
      chileLaAraucaniaSaavedra,
      chileLaAraucaniaTemuco,
      chileLaAraucaniaTeodoroSchmidt,
      chileLaAraucaniaTolten,
      chileLaAraucaniaTraiguen,
      chileLaAraucaniaVictoria,
      chileLaAraucaniaVilcun,
      chileLaAraucaniaVillarrica
    ]);
const Region chileLibertadorGeneralBernardoOHiggins = Region(
    id: 2838,
    parentId: 44,
    longitude: -71.0022311,
    latitude: -34.5755374,
    name: "Libertador General Bernardo O'Higgins",
    type: null,
    stateCode: "LI",
    cities: [
      chileLibertadorGeneralBernardoOHigginsChepica,
      chileLibertadorGeneralBernardoOHigginsChimbarongo,
      chileLibertadorGeneralBernardoOHigginsCodegua,
      chileLibertadorGeneralBernardoOHigginsCoinco,
      chileLibertadorGeneralBernardoOHigginsColtauco,
      chileLibertadorGeneralBernardoOHigginsDonihue,
      chileLibertadorGeneralBernardoOHigginsGraneros,
      chileLibertadorGeneralBernardoOHigginsLaEstrella,
      chileLibertadorGeneralBernardoOHigginsLasCabras,
      chileLibertadorGeneralBernardoOHigginsLitueche,
      chileLibertadorGeneralBernardoOHigginsLolol,
      chileLibertadorGeneralBernardoOHigginsMachali,
      chileLibertadorGeneralBernardoOHigginsMalloa,
      chileLibertadorGeneralBernardoOHigginsMarchigue,
      chileLibertadorGeneralBernardoOHigginsMostazal,
      chileLibertadorGeneralBernardoOHigginsNancagua,
      chileLibertadorGeneralBernardoOHigginsNavidad,
      chileLibertadorGeneralBernardoOHigginsOlivar,
      chileLibertadorGeneralBernardoOHigginsPalmilla,
      chileLibertadorGeneralBernardoOHigginsParedones,
      chileLibertadorGeneralBernardoOHigginsPeralillo,
      chileLibertadorGeneralBernardoOHigginsPeumo,
      chileLibertadorGeneralBernardoOHigginsPichidegua,
      chileLibertadorGeneralBernardoOHigginsPichilemu,
      chileLibertadorGeneralBernardoOHigginsPlacilla,
      chileLibertadorGeneralBernardoOHigginsPumanque,
      chileLibertadorGeneralBernardoOHigginsQuintaDdeTilcoco,
      chileLibertadorGeneralBernardoOHigginsRancagua,
      chileLibertadorGeneralBernardoOHigginsRengo,
      chileLibertadorGeneralBernardoOHigginsRequinoa,
      chileLibertadorGeneralBernardoOHigginsSanFernando,
      chileLibertadorGeneralBernardoOHigginsSanVicente,
      chileLibertadorGeneralBernardoOHigginsSantaCruz
    ]);
const Region chileLosLagos = Region(
    id: 2835,
    parentId: 44,
    longitude: -72.1416132,
    latitude: -41.9197779,
    name: "Los Lagos",
    type: null,
    stateCode: "LL",
    cities: [
      chileLosLagosAncud,
      chileLosLagosCalbuco,
      chileLosLagosCastro,
      chileLosLagosChaiten,
      chileLosLagosChonchi,
      chileLosLagosCochamo,
      chileLosLagosCuracoDdeVelez,
      chileLosLagosDalcahue,
      chileLosLagosFresia,
      chileLosLagosFrutillar,
      chileLosLagosFutaleufu,
      chileLosLagosHualaihue,
      chileLosLagosLlanquihue,
      chileLosLagosLosMuermos,
      chileLosLagosMaullin,
      chileLosLagosOsorno,
      chileLosLagosPalena,
      chileLosLagosPuertoMontt,
      chileLosLagosPuertoOctay,
      chileLosLagosPuertoVaras,
      chileLosLagosPuqueldon,
      chileLosLagosPurranque,
      chileLosLagosPuyehue,
      chileLosLagosQueilen,
      chileLosLagosQuellon,
      chileLosLagosQuemchi,
      chileLosLagosQuinchao,
      chileLosLagosRioNegro,
      chileLosLagosSanJuanDdeLlaCosta,
      chileLosLagosSanPablo
    ]);
const Region chileLosRios = Region(
    id: 2834,
    parentId: 44,
    longitude: -72.331113,
    latitude: -40.2310217,
    name: "Los Ríos",
    type: null,
    stateCode: "LR",
    cities: [
      chileLosRiosCorral,
      chileLosRiosFutrono,
      chileLosRiosLaUnion,
      chileLosRiosLagoRanco,
      chileLosRiosLanco,
      chileLosRiosLosLagos,
      chileLosRiosMafil,
      chileLosRiosMariquina,
      chileLosRiosPaillaco,
      chileLosRiosPanguipulli,
      chileLosRiosRioBueno,
      chileLosRiosValdivia
    ]);
const Region chileMagallanesYyDdeLlaAntarticaChilena = Region(
    id: 2836,
    parentId: 44,
    longitude: -72.1685001,
    latitude: -52.2064316,
    name: "Magallanes y de la Antártica Chilena",
    type: null,
    stateCode: "MA",
    cities: [
      chileMagallanesYyDdeLlaAntarticaChilenaAntartica,
      chileMagallanesYyDdeLlaAntarticaChilenaCaboDdeHornos,
      chileMagallanesYyDdeLlaAntarticaChilenaLagunaBlanca,
      chileMagallanesYyDdeLlaAntarticaChilenaNatales,
      chileMagallanesYyDdeLlaAntarticaChilenaPorvenir,
      chileMagallanesYyDdeLlaAntarticaChilenaPrimavera,
      chileMagallanesYyDdeLlaAntarticaChilenaPuntaArenas,
      chileMagallanesYyDdeLlaAntarticaChilenaRioVerde,
      chileMagallanesYyDdeLlaAntarticaChilenaSanGregorio,
      chileMagallanesYyDdeLlaAntarticaChilenaTimaukel,
      chileMagallanesYyDdeLlaAntarticaChilenaTorresDdelPaine
    ]);
const Region chileMaule = Region(
    id: 2833,
    parentId: 44,
    longitude: -71.5723953,
    latitude: -35.5163603,
    name: "Maule",
    type: null,
    stateCode: "ML",
    cities: [
      chileMauleCauquenes,
      chileMauleChanco,
      chileMauleColbun,
      chileMauleConstitucion,
      chileMauleCurepto,
      chileMauleCurico,
      chileMauleEmpedrado,
      chileMauleHualane,
      chileMauleLicanten,
      chileMauleLinares,
      chileMauleLongavi,
      chileMauleMaule,
      chileMauleMolina,
      chileMauleParral,
      chileMaulePelarco,
      chileMaulePelluhue,
      chileMaulePencahue,
      chileMauleRauco,
      chileMauleRetiro,
      chileMauleRioClaro,
      chileMauleRomeral,
      chileMauleSagradaFamilia,
      chileMauleSanClemente,
      chileMauleSanJavier,
      chileMauleSanRafael,
      chileMauleTalca,
      chileMauleTeno,
      chileMauleVichuquen,
      chileMauleVillaAlegre,
      chileMauleYerbasBuenas
    ]);
const Region chileNuble = Region(
    id: 2831,
    parentId: 44,
    longitude: -71.7622481,
    latitude: -36.7225743,
    name: "Ñuble",
    type: null,
    stateCode: "NB",
    cities: [
      chileNubleBulnes,
      chileNubleChillan,
      chileNubleChillanViejo,
      chileNubleCobquecura,
      chileNubleCoelemu,
      chileNubleCoihueco,
      chileNubleElCarmen,
      chileNubleNinhue,
      chileNubleNiquen,
      chileNublePemuco,
      chileNublePinto,
      chileNublePortezuelo,
      chileNubleQuillon,
      chileNubleQuirihue,
      chileNubleRanquil,
      chileNubleSanCarlos,
      chileNubleSanFabian,
      chileNubleSanIgnacio,
      chileNubleSanNicolas,
      chileNubleTreguaco,
      chileNubleYungay
    ]);
const Region chileRegionMetropolitanaDdeSantiago = Region(
    id: 2824,
    parentId: 44,
    longitude: -70.6504896,
    latitude: -33.4375545,
    name: "Región Metropolitana de Santiago",
    type: null,
    stateCode: "RM",
    cities: [
      chileRegionMetropolitanaDdeSantiagoAlhue,
      chileRegionMetropolitanaDdeSantiagoBuin,
      chileRegionMetropolitanaDdeSantiagoCaleraDdeTango,
      chileRegionMetropolitanaDdeSantiagoCerrillos,
      chileRegionMetropolitanaDdeSantiagoCerroNavia,
      chileRegionMetropolitanaDdeSantiagoColina,
      chileRegionMetropolitanaDdeSantiagoConchali,
      chileRegionMetropolitanaDdeSantiagoCuracavi,
      chileRegionMetropolitanaDdeSantiagoElBosque,
      chileRegionMetropolitanaDdeSantiagoElMonte,
      chileRegionMetropolitanaDdeSantiagoEstacionCentral,
      chileRegionMetropolitanaDdeSantiagoHuechuraba,
      chileRegionMetropolitanaDdeSantiagoIndependencia,
      chileRegionMetropolitanaDdeSantiagoIslaDdeMaipo,
      chileRegionMetropolitanaDdeSantiagoLaCisterna,
      chileRegionMetropolitanaDdeSantiagoLaFlorida,
      chileRegionMetropolitanaDdeSantiagoLaGranja,
      chileRegionMetropolitanaDdeSantiagoLaPintana,
      chileRegionMetropolitanaDdeSantiagoLaReina,
      chileRegionMetropolitanaDdeSantiagoLampa,
      chileRegionMetropolitanaDdeSantiagoLasCondes,
      chileRegionMetropolitanaDdeSantiagoLoBarnechea,
      chileRegionMetropolitanaDdeSantiagoLoEspejo,
      chileRegionMetropolitanaDdeSantiagoLoPrado,
      chileRegionMetropolitanaDdeSantiagoMacul,
      chileRegionMetropolitanaDdeSantiagoMaipu,
      chileRegionMetropolitanaDdeSantiagoMariaPinto,
      chileRegionMetropolitanaDdeSantiagoMelipilla,
      chileRegionMetropolitanaDdeSantiagoNunoa,
      chileRegionMetropolitanaDdeSantiagoPadreHurtado,
      chileRegionMetropolitanaDdeSantiagoPaine,
      chileRegionMetropolitanaDdeSantiagoPedroAguirreCerda,
      chileRegionMetropolitanaDdeSantiagoPenaflor,
      chileRegionMetropolitanaDdeSantiagoPenalolen,
      chileRegionMetropolitanaDdeSantiagoPirque,
      chileRegionMetropolitanaDdeSantiagoProvidencia,
      chileRegionMetropolitanaDdeSantiagoPudahuel,
      chileRegionMetropolitanaDdeSantiagoPuenteAlto,
      chileRegionMetropolitanaDdeSantiagoQuilicura,
      chileRegionMetropolitanaDdeSantiagoQuintaNormal,
      chileRegionMetropolitanaDdeSantiagoRecoleta,
      chileRegionMetropolitanaDdeSantiagoRenca,
      chileRegionMetropolitanaDdeSantiagoSanBernardo,
      chileRegionMetropolitanaDdeSantiagoSanJoaquin,
      chileRegionMetropolitanaDdeSantiagoSanJoseDdeMaipo,
      chileRegionMetropolitanaDdeSantiagoSanMiguel,
      chileRegionMetropolitanaDdeSantiagoSanPedro,
      chileRegionMetropolitanaDdeSantiagoSanRamon,
      chileRegionMetropolitanaDdeSantiagoSantiago,
      chileRegionMetropolitanaDdeSantiagoTalagante,
      chileRegionMetropolitanaDdeSantiagoTiltil,
      chileRegionMetropolitanaDdeSantiagoVitacura
    ]);
const Region chileTarapaca = Region(
    id: 2837,
    parentId: 44,
    longitude: -69.2877535,
    latitude: -20.2028799,
    name: "Tarapacá",
    type: null,
    stateCode: "TA",
    cities: [
      chileTarapacaAltoHospicio,
      chileTarapacaCamina,
      chileTarapacaColchane,
      chileTarapacaHuara,
      chileTarapacaIquique,
      chileTarapacaPica,
      chileTarapacaPozoAlmonte
    ]);
const Region chileValparaiso = Region(
    id: 2830,
    parentId: 44,
    longitude: -71.6126885,
    latitude: -33.047238,
    name: "Valparaíso",
    type: null,
    stateCode: "VS",
    cities: [
      chileValparaisoAlgarrobo,
      chileValparaisoCabildo,
      chileValparaisoCalleLarga,
      chileValparaisoCartagena,
      chileValparaisoCasablanca,
      chileValparaisoCatemu,
      chileValparaisoConcon,
      chileValparaisoElQuisco,
      chileValparaisoElTabo,
      chileValparaisoHijuelas,
      chileValparaisoIslaDdePascua,
      chileValparaisoJuanFernandez,
      chileValparaisoLaCalera,
      chileValparaisoLaCruz,
      chileValparaisoLaLigua,
      chileValparaisoLimache,
      chileValparaisoLlaillay,
      chileValparaisoLosAndes,
      chileValparaisoNogales,
      chileValparaisoOlmue,
      chileValparaisoPanquehue,
      chileValparaisoPapudo,
      chileValparaisoPetorca,
      chileValparaisoPuchuncavi,
      chileValparaisoPutaendo,
      chileValparaisoQuillota,
      chileValparaisoQuilpue,
      chileValparaisoQuintero,
      chileValparaisoRinconada,
      chileValparaisoSanAntonio,
      chileValparaisoSanEsteban,
      chileValparaisoSanFelipe,
      chileValparaisoSantaMaria,
      chileValparaisoSantoDomingo,
      chileValparaisoValparaiso,
      chileValparaisoVillaAlemana,
      chileValparaisoVinaDdelMar,
      chileValparaisoZapallar
    ]);

const chileStates = <int, Region>{
  2828: chileAisenDdelGeneralCarlosIbanezDdelCampo,
  2832: chileAntofagasta,
  2829: chileAricaYyParinacota,
  2823: chileAtacama,
  2827: chileBiobio,
  2825: chileCoquimbo,
  2826: chileLaAraucania,
  2838: chileLibertadorGeneralBernardoOHiggins,
  2835: chileLosLagos,
  2834: chileLosRios,
  2836: chileMagallanesYyDdeLlaAntarticaChilena,
  2833: chileMaule,
  2831: chileNuble,
  2824: chileRegionMetropolitanaDdeSantiago,
  2837: chileTarapaca,
  2830: chileValparaiso
};
