/// Access to known geographies in Colombia and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'colombia_cities.dart';

/// The 33 regions of `🇨🇴 Colombia`
const Region colombiaAmazonas = Region(id: 2895, parentId: 48, longitude: -71.5723953, latitude: -1.4429123,
          name: "Amazonas", type: null, stateCode: "AMA",
          cities: [
            colombiaAmazonasElEncanto,
            colombiaAmazonasLaChorrera,
            colombiaAmazonasLaPedrera,
            colombiaAmazonasLaVictoria,
            colombiaAmazonasLeticia,
            colombiaAmazonasMiritiHypParana,
            colombiaAmazonasPuertoAlegria,
            colombiaAmazonasPuertoArica,
            colombiaAmazonasPuertoNarino,
            colombiaAmazonasPuertoSantander,
            colombiaAmazonasTarapaca
          ]);
const Region colombiaAntioquia = Region(id: 2890, parentId: 48, longitude: -75.3412179, latitude: 7.1986064,
          name: "Antioquia", type: null, stateCode: "ANT",
          cities: [
            colombiaAntioquiaAbejorral,
            colombiaAntioquiaAbriaqui,
            colombiaAntioquiaAlejandria,
            colombiaAntioquiaAmaga,
            colombiaAntioquiaAmalfi,
            colombiaAntioquiaAndes,
            colombiaAntioquiaAngelopolis,
            colombiaAntioquiaAngostura,
            colombiaAntioquiaAnza,
            colombiaAntioquiaApartado,
            colombiaAntioquiaArboletes,
            colombiaAntioquiaArgelia,
            colombiaAntioquiaArmenia,
            colombiaAntioquiaBarbosa,
            colombiaAntioquiaBello,
            colombiaAntioquiaBelmira,
            colombiaAntioquiaBetania,
            colombiaAntioquiaBetulia,
            colombiaAntioquiaBriceno,
            colombiaAntioquiaBuritica,
            colombiaAntioquiaCaceres,
            colombiaAntioquiaCaicedo,
            colombiaAntioquiaCaldas,
            colombiaAntioquiaCampamento,
            colombiaAntioquiaCanasgordas,
            colombiaAntioquiaCaracoli,
            colombiaAntioquiaCaramanta,
            colombiaAntioquiaCarepa,
            colombiaAntioquiaCarmenDdeViboral,
            colombiaAntioquiaCarolina,
            colombiaAntioquiaCaucasia,
            colombiaAntioquiaChigorodo,
            colombiaAntioquiaCisneros,
            colombiaAntioquiaCiudadBolivar,
            colombiaAntioquiaCocorna,
            colombiaAntioquiaConcepcion,
            colombiaAntioquiaConcordia,
            colombiaAntioquiaCopacabana,
            colombiaAntioquiaCrucesDdeAnori,
            colombiaAntioquiaDabeiba,
            colombiaAntioquiaDonMatias,
            colombiaAntioquiaDonmatias,
            colombiaAntioquiaEbejico,
            colombiaAntioquiaElBagre,
            colombiaAntioquiaElCarmenDdeViboral,
            colombiaAntioquiaElSantuario,
            colombiaAntioquiaEntrerrios,
            colombiaAntioquiaEnvigado,
            colombiaAntioquiaFredonia,
            colombiaAntioquiaFrontino,
            colombiaAntioquiaGiraldo,
            colombiaAntioquiaGirardota,
            colombiaAntioquiaGomezPlata,
            colombiaAntioquiaGranada,
            colombiaAntioquiaGuadalupe,
            colombiaAntioquiaGuarne,
            colombiaAntioquiaGuatape,
            colombiaAntioquiaHeliconia,
            colombiaAntioquiaHispania,
            colombiaAntioquiaItagui,
            colombiaAntioquiaItuango,
            colombiaAntioquiaJardin,
            colombiaAntioquiaJerico,
            colombiaAntioquiaLaCeja,
            colombiaAntioquiaLaEstrella,
            colombiaAntioquiaLaPintada,
            colombiaAntioquiaLaUnion,
            colombiaAntioquiaLiborina,
            colombiaAntioquiaMaceo,
            colombiaAntioquiaMarinilla,
            colombiaAntioquiaMedellin,
            colombiaAntioquiaMontebello,
            colombiaAntioquiaMunicipioDdeSanPedroDdeLlosMilagros,
            colombiaAntioquiaMurindo,
            colombiaAntioquiaMutata,
            colombiaAntioquiaNarino,
            colombiaAntioquiaNechi,
            colombiaAntioquiaNecocli,
            colombiaAntioquiaOlaya,
            colombiaAntioquiaPenol,
            colombiaAntioquiaPeque,
            colombiaAntioquiaPueblorrico,
            colombiaAntioquiaPuertoBerrio,
            colombiaAntioquiaPuertoNare,
            colombiaAntioquiaPuertoTriunfo,
            colombiaAntioquiaRemedios,
            colombiaAntioquiaRetiro,
            colombiaAntioquiaRionegro,
            colombiaAntioquiaSabanalarga,
            colombiaAntioquiaSabaneta,
            colombiaAntioquiaSalgar,
            colombiaAntioquiaSanAndres,
            colombiaAntioquiaSanAndresDdeCuerquia,
            colombiaAntioquiaSanCarlos,
            colombiaAntioquiaSanFrancisco,
            colombiaAntioquiaSanJeronimo,
            colombiaAntioquiaSanJoseDdeLlaMontana,
            colombiaAntioquiaSanJuanDdeUraba,
            colombiaAntioquiaSanPedro,
            colombiaAntioquiaSanPedroDdeUraba,
            colombiaAntioquiaSanRafael,
            colombiaAntioquiaSanRoque,
            colombiaAntioquiaSanVicente,
            colombiaAntioquiaSanVicenteFerrer,
            colombiaAntioquiaSantaBarbara,
            colombiaAntioquiaSantaFeDdeAntioquia,
            colombiaAntioquiaSantaRosaDdeOsos,
            colombiaAntioquiaSantafeDdeAntioquia,
            colombiaAntioquiaSantoDomingo,
            colombiaAntioquiaSantuario,
            colombiaAntioquiaSegovia,
            colombiaAntioquiaSonson,
            colombiaAntioquiaSopetran,
            colombiaAntioquiaTamesis,
            colombiaAntioquiaTaraza,
            colombiaAntioquiaTarso,
            colombiaAntioquiaTitiribi,
            colombiaAntioquiaToledo,
            colombiaAntioquiaTurbo,
            colombiaAntioquiaUramita,
            colombiaAntioquiaUrrao,
            colombiaAntioquiaValdivia,
            colombiaAntioquiaValparaiso,
            colombiaAntioquiaVegachi,
            colombiaAntioquiaVenecia,
            colombiaAntioquiaVigiaDdelFuerte,
            colombiaAntioquiaYali,
            colombiaAntioquiaYarumal,
            colombiaAntioquiaYolombo,
            colombiaAntioquiaYondo,
            colombiaAntioquiaZaragoza
          ]);
const Region colombiaArauca = Region(id: 2881, parentId: 48, longitude: -71.0022311, latitude: 6.547306,
          name: "Arauca", type: null, stateCode: "ARA",
          cities: [
            colombiaAraucaArauca,
            colombiaAraucaArauquita,
            colombiaAraucaCravoNorte,
            colombiaAraucaFortul,
            colombiaAraucaPuertoRondon,
            colombiaAraucaSaravena,
            colombiaAraucaTame
          ]);
const Region colombiaAtlantico = Region(id: 2880, parentId: 48, longitude: -74.8741045, latitude: 10.6966159,
          name: "Atlántico", type: null, stateCode: "ATL",
          cities: [
            colombiaAtlanticoBaranoa,
            colombiaAtlanticoBarranquilla,
            colombiaAtlanticoCampoDdeLlaCruz,
            colombiaAtlanticoCandelaria,
            colombiaAtlanticoGalapa,
            colombiaAtlanticoJuanDdeAcosta,
            colombiaAtlanticoLuruaco,
            colombiaAtlanticoMalambo,
            colombiaAtlanticoManati,
            colombiaAtlanticoPalmarDdeVarela,
            colombiaAtlanticoPiojo,
            colombiaAtlanticoPolonuevo,
            colombiaAtlanticoPonedera,
            colombiaAtlanticoPuertoColombia,
            colombiaAtlanticoRepelon,
            colombiaAtlanticoSabanagrande,
            colombiaAtlanticoSabanalarga,
            colombiaAtlanticoSantaLucia,
            colombiaAtlanticoSantoTomas,
            colombiaAtlanticoSoledad,
            colombiaAtlanticoSuan,
            colombiaAtlanticoTubara,
            colombiaAtlanticoUsiacuri
          ]);
const Region colombiaBogota = Region(id: 4921, parentId: 48, longitude: -74.5027042, latitude: 4.2820415,
          name: "Bogotá", type: null, stateCode: "DC",
          cities: []);
const Region colombiaBolivar = Region(id: 2893, parentId: 48, longitude: -74.0300122, latitude: 8.6704382,
          name: "Bolívar", type: null, stateCode: "BOL",
          cities: [
            colombiaBolivarAchi,
            colombiaBolivarAltosDdelRosario,
            colombiaBolivarArenal,
            colombiaBolivarArjona,
            colombiaBolivarArroyohondo,
            colombiaBolivarBarrancoDdeLoba,
            colombiaBolivarCalamar,
            colombiaBolivarCantagallo,
            colombiaBolivarCartagena,
            colombiaBolivarCicuco,
            colombiaBolivarClemencia,
            colombiaBolivarCordoba,
            colombiaBolivarElCarmenDdeBolivar,
            colombiaBolivarElGuamo,
            colombiaBolivarElPenon,
            colombiaBolivarHatilloDdeLoba,
            colombiaBolivarMagangue,
            colombiaBolivarMahates,
            colombiaBolivarMargarita,
            colombiaBolivarMariaLlaBaja,
            colombiaBolivarMompos,
            colombiaBolivarMontecristo,
            colombiaBolivarMorales,
            colombiaBolivarMunicipioDdeCartagenaDdeIndias,
            colombiaBolivarMunicipioDdeMariaLlaBaja,
            colombiaBolivarNorosi,
            colombiaBolivarPinillos,
            colombiaBolivarRegidor,
            colombiaBolivarRioViejo,
            colombiaBolivarSanCristobal,
            colombiaBolivarSanEstanislao,
            colombiaBolivarSanFernando,
            colombiaBolivarSanJacinto,
            colombiaBolivarSanJacintoDdelCauca,
            colombiaBolivarSanJuanNepomuceno,
            colombiaBolivarSanMartinDdeLoba,
            colombiaBolivarSanPablo,
            colombiaBolivarSantaCatalina,
            colombiaBolivarSantaRosa,
            colombiaBolivarSantaRosaDdelSur,
            colombiaBolivarSimiti,
            colombiaBolivarSoplaviento,
            colombiaBolivarTalaiguaNuevo,
            colombiaBolivarTalaiguaViejo,
            colombiaBolivarTiquisio,
            colombiaBolivarTurbaco,
            colombiaBolivarTurbana,
            colombiaBolivarVillanueva,
            colombiaBolivarZambrano
          ]);
const Region colombiaBoyaca = Region(id: 2903, parentId: 48, longitude: -73.362003, latitude: 5.454511,
          name: "Boyacá", type: null, stateCode: "BOY",
          cities: [
            colombiaBoyacaAlmeida,
            colombiaBoyacaAquitania,
            colombiaBoyacaArcabuco,
            colombiaBoyacaBelen,
            colombiaBoyacaBerbeo,
            colombiaBoyacaBeteitiva,
            colombiaBoyacaBoavita,
            colombiaBoyacaBoyaca,
            colombiaBoyacaBriceno,
            colombiaBoyacaBuenavista,
            colombiaBoyacaBusbanza,
            colombiaBoyacaCaldas,
            colombiaBoyacaCampohermoso,
            colombiaBoyacaCerinza,
            colombiaBoyacaChinavita,
            colombiaBoyacaChiquinquira,
            colombiaBoyacaChiquiza,
            colombiaBoyacaChiscas,
            colombiaBoyacaChita,
            colombiaBoyacaChitaraque,
            colombiaBoyacaChivata,
            colombiaBoyacaChivor,
            colombiaBoyacaCienega,
            colombiaBoyacaCombita,
            colombiaBoyacaCoper,
            colombiaBoyacaCorrales,
            colombiaBoyacaCovarachia,
            colombiaBoyacaCubara,
            colombiaBoyacaCucaita,
            colombiaBoyacaCuitiva,
            colombiaBoyacaDuitama,
            colombiaBoyacaElCocuy,
            colombiaBoyacaElEspino,
            colombiaBoyacaFiravitoba,
            colombiaBoyacaFloresta,
            colombiaBoyacaGachantiva,
            colombiaBoyacaGameza,
            colombiaBoyacaGaragoa,
            colombiaBoyacaGuacamayas,
            colombiaBoyacaGuateque,
            colombiaBoyacaGuayata,
            colombiaBoyacaGuican,
            colombiaBoyacaIza,
            colombiaBoyacaJenesano,
            colombiaBoyacaJerico,
            colombiaBoyacaLaCapilla,
            colombiaBoyacaLaUvita,
            colombiaBoyacaLaVictoria,
            colombiaBoyacaLabranzagrande,
            colombiaBoyacaMacanal,
            colombiaBoyacaMaripi,
            colombiaBoyacaMiraflores,
            colombiaBoyacaMongua,
            colombiaBoyacaMongui,
            colombiaBoyacaMoniquira,
            colombiaBoyacaMotavita,
            colombiaBoyacaMuzo,
            colombiaBoyacaNobsa,
            colombiaBoyacaNuevoColon,
            colombiaBoyacaOicata,
            colombiaBoyacaOtanche,
            colombiaBoyacaPachavita,
            colombiaBoyacaPaez,
            colombiaBoyacaPaipa,
            colombiaBoyacaPajarito,
            colombiaBoyacaPanqueba,
            colombiaBoyacaPauna,
            colombiaBoyacaPaya,
            colombiaBoyacaPazDdeRio,
            colombiaBoyacaPesca,
            colombiaBoyacaPisba,
            colombiaBoyacaPuertoBoyaca,
            colombiaBoyacaQuipama,
            colombiaBoyacaRamiriqui,
            colombiaBoyacaRaquira,
            colombiaBoyacaRondon,
            colombiaBoyacaSaboya,
            colombiaBoyacaSachica,
            colombiaBoyacaSamaca,
            colombiaBoyacaSanEduardo,
            colombiaBoyacaSanJoseDdePare,
            colombiaBoyacaSanLuisDdeGaceno,
            colombiaBoyacaSanMateo,
            colombiaBoyacaSanMiguelDdeSema,
            colombiaBoyacaSanPabloDdeBorbur,
            colombiaBoyacaSantaMaria,
            colombiaBoyacaSantaRosaDdeViterbo,
            colombiaBoyacaSantaSofia,
            colombiaBoyacaSantana,
            colombiaBoyacaSativanorte,
            colombiaBoyacaSativasur,
            colombiaBoyacaSiachoque,
            colombiaBoyacaSoata,
            colombiaBoyacaSocha,
            colombiaBoyacaSochaViejo,
            colombiaBoyacaSocota,
            colombiaBoyacaSogamoso,
            colombiaBoyacaSomondoco,
            colombiaBoyacaSora,
            colombiaBoyacaSoraca,
            colombiaBoyacaSotaquira,
            colombiaBoyacaSusacon,
            colombiaBoyacaSutamarchan,
            colombiaBoyacaSutatenza,
            colombiaBoyacaTasco,
            colombiaBoyacaTenza,
            colombiaBoyacaTibana,
            colombiaBoyacaTibasosa,
            colombiaBoyacaTinjaca,
            colombiaBoyacaTipacoque,
            colombiaBoyacaToca,
            colombiaBoyacaTogui,
            colombiaBoyacaTopaga,
            colombiaBoyacaTota,
            colombiaBoyacaTunja,
            colombiaBoyacaTunungua,
            colombiaBoyacaTurmeque,
            colombiaBoyacaTuta,
            colombiaBoyacaTutaza,
            colombiaBoyacaUmbita,
            colombiaBoyacaVentaquemada,
            colombiaBoyacaVillaDdeLeyva,
            colombiaBoyacaViracacha,
            colombiaBoyacaZetaquira
          ]);
const Region colombiaCaldas = Region(id: 2887, parentId: 48, longitude: -75.2479061, latitude: 5.29826,
          name: "Caldas", type: null, stateCode: "CAL",
          cities: [
            colombiaCaldasAguadas,
            colombiaCaldasAnserma,
            colombiaCaldasAranzazu,
            colombiaCaldasBelalcazar,
            colombiaCaldasChinchina,
            colombiaCaldasFiladelfia,
            colombiaCaldasLaDorada,
            colombiaCaldasLaMerced,
            colombiaCaldasManizales,
            colombiaCaldasManzanares,
            colombiaCaldasMarmato,
            colombiaCaldasMarquetalia,
            colombiaCaldasMarulanda,
            colombiaCaldasNeira,
            colombiaCaldasNorcasia,
            colombiaCaldasPacora,
            colombiaCaldasPalestina,
            colombiaCaldasPensilvania,
            colombiaCaldasRiosucio,
            colombiaCaldasRisaralda,
            colombiaCaldasSalamina,
            colombiaCaldasSamana,
            colombiaCaldasSanJose,
            colombiaCaldasSupia,
            colombiaCaldasVictoria,
            colombiaCaldasVillamaria,
            colombiaCaldasViterbo
          ]);
const Region colombiaCaqueta = Region(id: 2891, parentId: 48, longitude: -73.8419063, latitude: 0.869892,
          name: "Caquetá", type: null, stateCode: "CAQ",
          cities: [
            colombiaCaquetaAlbania,
            colombiaCaquetaBelenDdeLosAndaquies,
            colombiaCaquetaCartagenaDdelChaira,
            colombiaCaquetaCurillo,
            colombiaCaquetaElDoncello,
            colombiaCaquetaElPaujil,
            colombiaCaquetaFlorencia,
            colombiaCaquetaLaMontanita,
            colombiaCaquetaMilan,
            colombiaCaquetaMorelia,
            colombiaCaquetaPuertoRico,
            colombiaCaquetaSanJoseDdelFragua,
            colombiaCaquetaSolano,
            colombiaCaquetaValparaiso
          ]);
const Region colombiaCasanare = Region(id: 2892, parentId: 48, longitude: -71.5723953, latitude: 5.7589269,
          name: "Casanare", type: null, stateCode: "CAS",
          cities: [
            colombiaCasanareAguazul,
            colombiaCasanareChameza,
            colombiaCasanareHatoCorozal,
            colombiaCasanareMani,
            colombiaCasanareMonterrey,
            colombiaCasanareMunicipioHatoCorozal,
            colombiaCasanareNunchia,
            colombiaCasanareOrocue,
            colombiaCasanarePore,
            colombiaCasanareRecetor,
            colombiaCasanareSabanalarga,
            colombiaCasanareSacama,
            colombiaCasanareSanLuisDdePalenque,
            colombiaCasanareTamara,
            colombiaCasanareTauramena,
            colombiaCasanareTrinidad,
            colombiaCasanareVillanueva,
            colombiaCasanareYopal
          ]);
const Region colombiaCauca = Region(id: 2884, parentId: 48, longitude: -76.8259652, latitude: 2.7049813,
          name: "Cauca", type: null, stateCode: "CAU",
          cities: [
            colombiaCaucaAlmaguer,
            colombiaCaucaArgelia,
            colombiaCaucaBalboa,
            colombiaCaucaBelalcazar,
            colombiaCaucaBolivar,
            colombiaCaucaBuenosAires,
            colombiaCaucaCajibio,
            colombiaCaucaCaldono,
            colombiaCaucaCaloto,
            colombiaCaucaCorinto,
            colombiaCaucaElBordo,
            colombiaCaucaElTambo,
            colombiaCaucaFlorencia,
            colombiaCaucaGuapi,
            colombiaCaucaInza,
            colombiaCaucaJambalo,
            colombiaCaucaLaSierra,
            colombiaCaucaLaVega,
            colombiaCaucaLopez,
            colombiaCaucaMercaderes,
            colombiaCaucaMiranda,
            colombiaCaucaMorales,
            colombiaCaucaMunicipioDdeLopezDdeMicay,
            colombiaCaucaPadilla,
            colombiaCaucaPaez,
            colombiaCaucaPaispamba,
            colombiaCaucaPatia,
            colombiaCaucaPiendamo,
            colombiaCaucaPopayan,
            colombiaCaucaPuertoTejada,
            colombiaCaucaPurace,
            colombiaCaucaRosas,
            colombiaCaucaSanSebastian,
            colombiaCaucaSantanderDdeQuilichao,
            colombiaCaucaSilvia,
            colombiaCaucaSotara,
            colombiaCaucaSuarez,
            colombiaCaucaSucre,
            colombiaCaucaTimbiqui,
            colombiaCaucaToribio,
            colombiaCaucaTotoro,
            colombiaCaucaVillaRica
          ]);
const Region colombiaCesar = Region(id: 2899, parentId: 48, longitude: -73.6536209, latitude: 9.3372948,
          name: "Cesar", type: null, stateCode: "CES",
          cities: [
            colombiaCesarAguachica,
            colombiaCesarAgustinCodazzi,
            colombiaCesarAriguani,
            colombiaCesarAstrea,
            colombiaCesarBecerril,
            colombiaCesarChimichagua,
            colombiaCesarChiriguana,
            colombiaCesarCurumani,
            colombiaCesarElCopey,
            colombiaCesarElPaso,
            colombiaCesarGamarra,
            colombiaCesarGonzalez,
            colombiaCesarLaGloria,
            colombiaCesarLaJaguaDdeIbirico,
            colombiaCesarLaPaz,
            colombiaCesarManaure,
            colombiaCesarManaureBalconDdelCesar,
            colombiaCesarPailitas,
            colombiaCesarPelaya,
            colombiaCesarRioDdeOro,
            colombiaCesarSanAlberto,
            colombiaCesarSanDiego,
            colombiaCesarSanMartin,
            colombiaCesarTamalameque,
            colombiaCesarValledupar
          ]);
const Region colombiaChoco = Region(id: 2876, parentId: 48, longitude: -76.8259652, latitude: 5.2528033,
          name: "Chocó", type: null, stateCode: "CHO",
          cities: [
            colombiaChocoAcandi,
            colombiaChocoAltoBaudo,
            colombiaChocoAtrato,
            colombiaChocoBagado,
            colombiaChocoBahiaSolano,
            colombiaChocoBajoBaudo,
            colombiaChocoBellavista,
            colombiaChocoBojaya,
            colombiaChocoCarmenDdelDarien,
            colombiaChocoCertegui,
            colombiaChocoCondoto,
            colombiaChocoElCantonDdeSanPablo,
            colombiaChocoElCantonDdelSanPablo,
            colombiaChocoElCarmen,
            colombiaChocoElCarmenDdeAtrato,
            colombiaChocoElLitoralDdelSanJuan,
            colombiaChocoIstmina,
            colombiaChocoJurado,
            colombiaChocoLloro,
            colombiaChocoMedioAtrato,
            colombiaChocoMedioBaudo,
            colombiaChocoMedioSanJuan,
            colombiaChocoNovita,
            colombiaChocoNuqui,
            colombiaChocoPieDdePato,
            colombiaChocoPizarro,
            colombiaChocoQuibdo,
            colombiaChocoRioIro,
            colombiaChocoRioQuito,
            colombiaChocoRiosucio,
            colombiaChocoSanJoseDdelPalmar,
            colombiaChocoSantaGenovevaDdeDocordo,
            colombiaChocoSipi,
            colombiaChocoTado,
            colombiaChocoUnguia,
            colombiaChocoUnionPanamericana
          ]);
const Region colombiaCordoba = Region(id: 2898, parentId: 48, longitude: -75.57405, latitude: 8.049293,
          name: "Córdoba", type: null, stateCode: "COR",
          cities: [
            colombiaCordobaAyapel,
            colombiaCordobaBuenavista,
            colombiaCordobaCanalete,
            colombiaCordobaCerete,
            colombiaCordobaChima,
            colombiaCordobaChinu,
            colombiaCordobaCienagaDdeOro,
            colombiaCordobaCotorra,
            colombiaCordobaLaApartada,
            colombiaCordobaLorica,
            colombiaCordobaLosCordobas,
            colombiaCordobaMomil,
            colombiaCordobaMonitos,
            colombiaCordobaMontelibano,
            colombiaCordobaMonteria,
            colombiaCordobaPlanetaRica,
            colombiaCordobaPuebloNuevo,
            colombiaCordobaPuertoEscondido,
            colombiaCordobaPuertoLibertador,
            colombiaCordobaPurisima,
            colombiaCordobaPurisimaDdeLlaConcepcion,
            colombiaCordobaSahagun,
            colombiaCordobaSanAndresSotavento,
            colombiaCordobaSanAntero,
            colombiaCordobaSanBernardoDdelViento,
            colombiaCordobaSanCarlos,
            colombiaCordobaSanPelayo,
            colombiaCordobaTierralta,
            colombiaCordobaValencia
          ]);
const Region colombiaCundinamarca = Region(id: 2875, parentId: 48, longitude: -74.0300122, latitude: 5.026003,
          name: "Cundinamarca", type: null, stateCode: "CUN",
          cities: [
            colombiaCundinamarcaAguaDdeDios,
            colombiaCundinamarcaAlban,
            colombiaCundinamarcaAnapoima,
            colombiaCundinamarcaAnolaima,
            colombiaCundinamarcaApulo,
            colombiaCundinamarcaArbelaez,
            colombiaCundinamarcaBarrioSanLuis,
            colombiaCundinamarcaBeltran,
            colombiaCundinamarcaBituima,
            colombiaCundinamarcaBogota,
            colombiaCundinamarcaBojaca,
            colombiaCundinamarcaCabrera,
            colombiaCundinamarcaCachipay,
            colombiaCundinamarcaCajica,
            colombiaCundinamarcaCaparrapi,
            colombiaCundinamarcaCaqueza,
            colombiaCundinamarcaCarmenDdeCarupa,
            colombiaCundinamarcaChaguani,
            colombiaCundinamarcaChia,
            colombiaCundinamarcaChipaque,
            colombiaCundinamarcaChoachi,
            colombiaCundinamarcaChoconta,
            colombiaCundinamarcaCogua,
            colombiaCundinamarcaCota,
            colombiaCundinamarcaCucunuba,
            colombiaCundinamarcaElColegio,
            colombiaCundinamarcaElMariachi,
            colombiaCundinamarcaElPenon,
            colombiaCundinamarcaElRosal,
            colombiaCundinamarcaFacatativa,
            colombiaCundinamarcaFomeque,
            colombiaCundinamarcaFosca,
            colombiaCundinamarcaFunza,
            colombiaCundinamarcaFuquene,
            colombiaCundinamarcaFusagasuga,
            colombiaCundinamarcaGachala,
            colombiaCundinamarcaGachancipa,
            colombiaCundinamarcaGacheta,
            colombiaCundinamarcaGama,
            colombiaCundinamarcaGirardot,
            colombiaCundinamarcaGranada,
            colombiaCundinamarcaGuacheta,
            colombiaCundinamarcaGuaduas,
            colombiaCundinamarcaGuasca,
            colombiaCundinamarcaGuataqui,
            colombiaCundinamarcaGuatavita,
            colombiaCundinamarcaGuayabalDdeSiquima,
            colombiaCundinamarcaGuayabetal,
            colombiaCundinamarcaGutierrez,
            colombiaCundinamarcaJerusalen,
            colombiaCundinamarcaJunin,
            colombiaCundinamarcaLaCalera,
            colombiaCundinamarcaLaMesa,
            colombiaCundinamarcaLaPalma,
            colombiaCundinamarcaLaPena,
            colombiaCundinamarcaLaVega,
            colombiaCundinamarcaLenguazaque,
            colombiaCundinamarcaMacheta,
            colombiaCundinamarcaMadrid,
            colombiaCundinamarcaManta,
            colombiaCundinamarcaMedina,
            colombiaCundinamarcaMosquera,
            colombiaCundinamarcaNarino,
            colombiaCundinamarcaNemocon,
            colombiaCundinamarcaNilo,
            colombiaCundinamarcaNimaima,
            colombiaCundinamarcaNocaima,
            colombiaCundinamarcaPaime,
            colombiaCundinamarcaPandi,
            colombiaCundinamarcaParatebueno,
            colombiaCundinamarcaPasca,
            colombiaCundinamarcaPuertoBogota,
            colombiaCundinamarcaPuertoSalgar,
            colombiaCundinamarcaPuli,
            colombiaCundinamarcaQuebradanegra,
            colombiaCundinamarcaQuetame,
            colombiaCundinamarcaQuipile,
            colombiaCundinamarcaRicaurte,
            colombiaCundinamarcaSanAntonioDdelTequendama,
            colombiaCundinamarcaSanBernardo,
            colombiaCundinamarcaSanCayetano,
            colombiaCundinamarcaSanFrancisco,
            colombiaCundinamarcaSanJuanDdeRioSeco,
            colombiaCundinamarcaSasaima,
            colombiaCundinamarcaSesquile,
            colombiaCundinamarcaSibate,
            colombiaCundinamarcaSilvania,
            colombiaCundinamarcaSimijaca,
            colombiaCundinamarcaSoacha,
            colombiaCundinamarcaSopo,
            colombiaCundinamarcaSubachoque,
            colombiaCundinamarcaSuesca,
            colombiaCundinamarcaSupata,
            colombiaCundinamarcaSusa,
            colombiaCundinamarcaSutatausa,
            colombiaCundinamarcaTabio,
            colombiaCundinamarcaTausa,
            colombiaCundinamarcaTena,
            colombiaCundinamarcaTenjo,
            colombiaCundinamarcaTibacuy,
            colombiaCundinamarcaTibirita,
            colombiaCundinamarcaTocaima,
            colombiaCundinamarcaTocancipa,
            colombiaCundinamarcaTopaipi,
            colombiaCundinamarcaUbala,
            colombiaCundinamarcaUbaque,
            colombiaCundinamarcaUne,
            colombiaCundinamarcaUtica,
            colombiaCundinamarcaVenecia,
            colombiaCundinamarcaVergara,
            colombiaCundinamarcaViani,
            colombiaCundinamarcaVillaDdeSanDiegoDdeUbate,
            colombiaCundinamarcaVillagomez,
            colombiaCundinamarcaVillapinzon,
            colombiaCundinamarcaVilleta,
            colombiaCundinamarcaViota,
            colombiaCundinamarcaYacopi,
            colombiaCundinamarcaZipacon,
            colombiaCundinamarcaZipaquira
          ]);
const Region colombiaGuainia = Region(id: 2882, parentId: 48, longitude: -68.5247149, latitude: 2.585393,
          name: "Guainía", type: null, stateCode: "GUA",
          cities: [
            colombiaGuainiaBarrancoMinas,
            colombiaGuainiaCacahual,
            colombiaGuainiaInirida,
            colombiaGuainiaLaGuadalupe,
            colombiaGuainiaMapiripana,
            colombiaGuainiaMorichal,
            colombiaGuainiaPanaPana,
            colombiaGuainiaPuertoColombia,
            colombiaGuainiaSanFelipe
          ]);
const Region colombiaGuaviare = Region(id: 2888, parentId: 48, longitude: -72.331113, latitude: 2.043924,
          name: "Guaviare", type: null, stateCode: "GUV",
          cities: [
            colombiaGuaviareCalamar,
            colombiaGuaviareElRetorno,
            colombiaGuaviareMiraflores,
            colombiaGuaviareSanJoseDdelGuaviare
          ]);
const Region colombiaHuila = Region(id: 4871, parentId: 48, longitude: -75.5276699, latitude: 2.5359349,
          name: "Huila", type: null, stateCode: "HUI",
          cities: [
            colombiaHuilaAcevedo,
            colombiaHuilaAipe,
            colombiaHuilaAlgeciras,
            colombiaHuilaAltamira,
            colombiaHuilaBaraya,
            colombiaHuilaCampoalegre,
            colombiaHuilaColombia,
            colombiaHuilaElAgrado,
            colombiaHuilaElias,
            colombiaHuilaGarzon,
            colombiaHuilaGigante,
            colombiaHuilaGuadalupe,
            colombiaHuilaHobo,
            colombiaHuilaIquira,
            colombiaHuilaIsnos,
            colombiaHuilaLaPlata,
            colombiaHuilaNataga,
            colombiaHuilaNeiva,
            colombiaHuilaOporapa,
            colombiaHuilaPaicol,
            colombiaHuilaPalermo,
            colombiaHuilaPalestina,
            colombiaHuilaPital,
            colombiaHuilaPitalito,
            colombiaHuilaRivera,
            colombiaHuilaSaladoblanco,
            colombiaHuilaSanAgustin,
            colombiaHuilaSantaMaria,
            colombiaHuilaSuaza,
            colombiaHuilaTarqui,
            colombiaHuilaTello,
            colombiaHuilaTeruel,
            colombiaHuilaTesalia,
            colombiaHuilaTimana,
            colombiaHuilaVillavieja,
            colombiaHuilaYaguara
          ]);
const Region colombiaLaGuajira = Region(id: 2889, parentId: 48, longitude: -72.5204827, latitude: 11.3547743,
          name: "La Guajira", type: null, stateCode: "LAG",
          cities: [
            colombiaLaGuajiraAlbania,
            colombiaLaGuajiraBarrancas,
            colombiaLaGuajiraDibulla,
            colombiaLaGuajiraDistraccion,
            colombiaLaGuajiraElMolino,
            colombiaLaGuajiraFonseca,
            colombiaLaGuajiraHatonuevo,
            colombiaLaGuajiraLaJaguaDdelPilar,
            colombiaLaGuajiraMaicao,
            colombiaLaGuajiraManaure,
            colombiaLaGuajiraRiohacha,
            colombiaLaGuajiraSanJuanDdelCesar,
            colombiaLaGuajiraUribia,
            colombiaLaGuajiraUrumita,
            colombiaLaGuajiraVillanueva
          ]);
const Region colombiaMagdalena = Region(id: 2886, parentId: 48, longitude: -74.4056612, latitude: 10.4113014,
          name: "Magdalena", type: null, stateCode: "MAG",
          cities: [
            colombiaMagdalenaAlgarrobo,
            colombiaMagdalenaAracataca,
            colombiaMagdalenaAriguani,
            colombiaMagdalenaBuenavista,
            colombiaMagdalenaCerroDdeSanAntonio,
            colombiaMagdalenaCerroSanAntonio,
            colombiaMagdalenaChibolo,
            colombiaMagdalenaChivolo,
            colombiaMagdalenaCienaga,
            colombiaMagdalenaConcordia,
            colombiaMagdalenaElBanco,
            colombiaMagdalenaElPinon,
            colombiaMagdalenaElReten,
            colombiaMagdalenaFundacion,
            colombiaMagdalenaGuamal,
            colombiaMagdalenaNuevaGranada,
            colombiaMagdalenaPedraza,
            colombiaMagdalenaPijinoDdelCarmen,
            colombiaMagdalenaPivijay,
            colombiaMagdalenaPlato,
            colombiaMagdalenaPuebloviejo,
            colombiaMagdalenaRemolino,
            colombiaMagdalenaSabanasDdeSanAngel,
            colombiaMagdalenaSalamina,
            colombiaMagdalenaSanAntonio,
            colombiaMagdalenaSanZenon,
            colombiaMagdalenaSantaAna,
            colombiaMagdalenaSantaBarbaraDdePinto,
            colombiaMagdalenaSantaMarta,
            colombiaMagdalenaSitionuevo,
            colombiaMagdalenaTenerife,
            colombiaMagdalenaZapayan,
            colombiaMagdalenaZonaBananera
          ]);
const Region colombiaMeta = Region(id: 2878, parentId: 48, longitude: -104.9753595, latitude: 39.7673258,
          name: "Meta", type: null, stateCode: "MET",
          cities: [
            colombiaMetaAcacias,
            colombiaMetaBarrancaDdeUpia,
            colombiaMetaCabuyaro,
            colombiaMetaCastillaLlaNueva,
            colombiaMetaCubarral,
            colombiaMetaCumaral,
            colombiaMetaElCalvario,
            colombiaMetaElCastillo,
            colombiaMetaFuenteDdeOro,
            colombiaMetaGranada,
            colombiaMetaGuamal,
            colombiaMetaLaMacarena,
            colombiaMetaLejanias,
            colombiaMetaMapiripan,
            colombiaMetaMesetas,
            colombiaMetaPuertoConcordia,
            colombiaMetaPuertoGaitan,
            colombiaMetaPuertoLleras,
            colombiaMetaPuertoLopez,
            colombiaMetaPuertoRico,
            colombiaMetaPuertoYuca,
            colombiaMetaRestrepo,
            colombiaMetaSanCarlosDdeGuaroa,
            colombiaMetaSanJuanDdeArama,
            colombiaMetaSanMartin,
            colombiaMetaVillavicencio,
            colombiaMetaVistahermosa
          ]);
const Region colombiaNarino = Region(id: 2897, parentId: 48, longitude: -77.35794, latitude: 1.289151,
          name: "Nariño", type: null, stateCode: "NAR",
          cities: [
            colombiaNarinoAlban,
            colombiaNarinoAldana,
            colombiaNarinoAncuya,
            colombiaNarinoArboleda,
            colombiaNarinoBarbacoas,
            colombiaNarinoBelen,
            colombiaNarinoBuesaco,
            colombiaNarinoCarlosama,
            colombiaNarinoCartago,
            colombiaNarinoChachagui,
            colombiaNarinoColon,
            colombiaNarinoConsaca,
            colombiaNarinoContadero,
            colombiaNarinoCordoba,
            colombiaNarinoCuaspud,
            colombiaNarinoCumbal,
            colombiaNarinoCumbitara,
            colombiaNarinoElCharco,
            colombiaNarinoElPenol,
            colombiaNarinoElRosario,
            colombiaNarinoElTablon,
            colombiaNarinoElTablonDdeGomez,
            colombiaNarinoElTambo,
            colombiaNarinoFranciscoPizarro,
            colombiaNarinoFunes,
            colombiaNarinoGenova,
            colombiaNarinoGuachucal,
            colombiaNarinoGuaitarilla,
            colombiaNarinoGualmatan,
            colombiaNarinoIles,
            colombiaNarinoImues,
            colombiaNarinoIpiales,
            colombiaNarinoIscuande,
            colombiaNarinoLaCruz,
            colombiaNarinoLaFlorida,
            colombiaNarinoLaLlanada,
            colombiaNarinoLaTola,
            colombiaNarinoLaUnion,
            colombiaNarinoLeiva,
            colombiaNarinoLinares,
            colombiaNarinoLosAndes,
            colombiaNarinoMagui,
            colombiaNarinoMallama,
            colombiaNarinoMosquera,
            colombiaNarinoNarino,
            colombiaNarinoOlayaHerrera,
            colombiaNarinoOspina,
            colombiaNarinoPasto,
            colombiaNarinoPayan,
            colombiaNarinoPiedrancha,
            colombiaNarinoPolicarpa,
            colombiaNarinoPotosi,
            colombiaNarinoPuerres,
            colombiaNarinoPupiales,
            colombiaNarinoRicaurte,
            colombiaNarinoRobertoPayan,
            colombiaNarinoSalahonda,
            colombiaNarinoSamaniego,
            colombiaNarinoSanAndresDdeTumaco,
            colombiaNarinoSanBernardo,
            colombiaNarinoSanJose,
            colombiaNarinoSanLorenzo,
            colombiaNarinoSanPablo,
            colombiaNarinoSanPedroDdeCartago,
            colombiaNarinoSandona,
            colombiaNarinoSantaBarbara,
            colombiaNarinoSantacruz,
            colombiaNarinoSapuyes,
            colombiaNarinoSotomayor,
            colombiaNarinoTaminango,
            colombiaNarinoTangua,
            colombiaNarinoTumaco,
            colombiaNarinoTuquerres,
            colombiaNarinoYacuanquer
          ]);
const Region colombiaNorteDdeSantander = Region(id: 2877, parentId: 48, longitude: -72.8988069, latitude: 7.9462831,
          name: "Norte de Santander", type: null, stateCode: "NSA",
          cities: [
            colombiaNorteDdeSantanderAbrego,
            colombiaNorteDdeSantanderArboledas,
            colombiaNorteDdeSantanderBochalema,
            colombiaNorteDdeSantanderBucarasica,
            colombiaNorteDdeSantanderCachira,
            colombiaNorteDdeSantanderCacota,
            colombiaNorteDdeSantanderChinacota,
            colombiaNorteDdeSantanderChitaga,
            colombiaNorteDdeSantanderConvencion,
            colombiaNorteDdeSantanderCucuta,
            colombiaNorteDdeSantanderCucutilla,
            colombiaNorteDdeSantanderDurania,
            colombiaNorteDdeSantanderElCarmen,
            colombiaNorteDdeSantanderElTarra,
            colombiaNorteDdeSantanderElZulia,
            colombiaNorteDdeSantanderGramalote,
            colombiaNorteDdeSantanderHacari,
            colombiaNorteDdeSantanderHerran,
            colombiaNorteDdeSantanderLaEsperanza,
            colombiaNorteDdeSantanderLaPlaya,
            colombiaNorteDdeSantanderLabateca,
            colombiaNorteDdeSantanderLosPatios,
            colombiaNorteDdeSantanderLourdes,
            colombiaNorteDdeSantanderMutiscua,
            colombiaNorteDdeSantanderOcana,
            colombiaNorteDdeSantanderPamplona,
            colombiaNorteDdeSantanderPamplonita,
            colombiaNorteDdeSantanderPuertoSantander,
            colombiaNorteDdeSantanderRagonvalia,
            colombiaNorteDdeSantanderSalazar,
            colombiaNorteDdeSantanderSanCalixto,
            colombiaNorteDdeSantanderSanCayetano,
            colombiaNorteDdeSantanderSantiago,
            colombiaNorteDdeSantanderSardinata,
            colombiaNorteDdeSantanderSilos,
            colombiaNorteDdeSantanderTibu,
            colombiaNorteDdeSantanderToledo,
            colombiaNorteDdeSantanderVillaDdelRosario
          ]);
const Region colombiaPutumayo = Region(id: 2896, parentId: 48, longitude: -75.5276699, latitude: 0.4359506,
          name: "Putumayo", type: null, stateCode: "PUT",
          cities: [
            colombiaPutumayoColon,
            colombiaPutumayoLaDorada,
            colombiaPutumayoLeguizamo,
            colombiaPutumayoMocoa,
            colombiaPutumayoOrito,
            colombiaPutumayoPuertoAsis,
            colombiaPutumayoPuertoGuzman,
            colombiaPutumayoPuertoLeguizamo,
            colombiaPutumayoSanFrancisco,
            colombiaPutumayoSanMiguel,
            colombiaPutumayoSantiago,
            colombiaPutumayoSibundoy,
            colombiaPutumayoValleDdelGuamuez,
            colombiaPutumayoVillagarzon
          ]);
const Region colombiaQuindio = Region(id: 2874, parentId: 48, longitude: -75.667356, latitude: 4.4610191,
          name: "Quindío", type: null, stateCode: "QUI",
          cities: [
            colombiaQuindioArmenia,
            colombiaQuindioBuenavista,
            colombiaQuindioCalarca,
            colombiaQuindioCircasia,
            colombiaQuindioCordoba,
            colombiaQuindioFilandia,
            colombiaQuindioGenova,
            colombiaQuindioLaTebaida,
            colombiaQuindioMontenegro,
            colombiaQuindioPijao,
            colombiaQuindioQuimbaya,
            colombiaQuindioSalento
          ]);
const Region colombiaRisaralda = Region(id: 2879, parentId: 48, longitude: -75.9927652, latitude: 5.3158475,
          name: "Risaralda", type: null, stateCode: "RIS",
          cities: [
            colombiaRisaraldaAnserma,
            colombiaRisaraldaApia,
            colombiaRisaraldaBalboa,
            colombiaRisaraldaBelenDdeUmbria,
            colombiaRisaraldaDosquebradas,
            colombiaRisaraldaGuatica,
            colombiaRisaraldaLaCelia,
            colombiaRisaraldaLaMerced,
            colombiaRisaraldaLaVirginia,
            colombiaRisaraldaMarsella,
            colombiaRisaraldaMistrato,
            colombiaRisaraldaPereira,
            colombiaRisaraldaPuebloRico,
            colombiaRisaraldaQuinchia,
            colombiaRisaraldaSantaRosaDdeCabal,
            colombiaRisaraldaSantuario
          ]);
const Region colombiaSanAndresProvidenciaYySantaCatalina = Region(id: 2900, parentId: 48, longitude: -81.7185253, latitude: 12.5567324,
          name: "San Andrés, Providencia y Santa Catalina", type: null, stateCode: "SAP",
          cities: [
            colombiaSanAndresProvidenciaYySantaCatalinaMountain,
            colombiaSanAndresProvidenciaYySantaCatalinaProvidencia,
            colombiaSanAndresProvidenciaYySantaCatalinaSanAndres
          ]);
const Region colombiaSantander = Region(id: 2901, parentId: 48, longitude: -73.6536209, latitude: 6.6437076,
          name: "Santander", type: null, stateCode: "SAN",
          cities: [
            colombiaSantanderAguada,
            colombiaSantanderAlbania,
            colombiaSantanderAratoca,
            colombiaSantanderBarbosa,
            colombiaSantanderBarichara,
            colombiaSantanderBarrancabermeja,
            colombiaSantanderBetulia,
            colombiaSantanderBolivar,
            colombiaSantanderBucaramanga,
            colombiaSantanderCabrera,
            colombiaSantanderCalifornia,
            colombiaSantanderCapitanejo,
            colombiaSantanderCarcasi,
            colombiaSantanderCepita,
            colombiaSantanderCerrito,
            colombiaSantanderCharala,
            colombiaSantanderCharta,
            colombiaSantanderChima,
            colombiaSantanderChipata,
            colombiaSantanderCimitarra,
            colombiaSantanderConcepcion,
            colombiaSantanderConfines,
            colombiaSantanderContratacion,
            colombiaSantanderCoromoro,
            colombiaSantanderCuriti,
            colombiaSantanderElCarmenDdeChucuri,
            colombiaSantanderElGuacamayo,
            colombiaSantanderElPenon,
            colombiaSantanderElPlayon,
            colombiaSantanderEncino,
            colombiaSantanderEnciso,
            colombiaSantanderFlorian,
            colombiaSantanderFloridablanca,
            colombiaSantanderGalan,
            colombiaSantanderGambita,
            colombiaSantanderGiron,
            colombiaSantanderGuaca,
            colombiaSantanderGuadalupe,
            colombiaSantanderGuapota,
            colombiaSantanderGuavata,
            colombiaSantanderGuepsa,
            colombiaSantanderHato,
            colombiaSantanderJesusMaria,
            colombiaSantanderJordan,
            colombiaSantanderLaBelleza,
            colombiaSantanderLaPaz,
            colombiaSantanderLandazuri,
            colombiaSantanderLebrija,
            colombiaSantanderLosSantos,
            colombiaSantanderMacaravita,
            colombiaSantanderMalaga,
            colombiaSantanderMatanza,
            colombiaSantanderMogotes,
            colombiaSantanderMolagavita,
            colombiaSantanderOcamonte,
            colombiaSantanderOiba,
            colombiaSantanderOnzaga,
            colombiaSantanderPalmar,
            colombiaSantanderPalmasDdelSocorro,
            colombiaSantanderParamo,
            colombiaSantanderPiedecuesta,
            colombiaSantanderPinchote,
            colombiaSantanderPuenteNacional,
            colombiaSantanderPuertoParra,
            colombiaSantanderPuertoWilches,
            colombiaSantanderRionegro,
            colombiaSantanderSabanaDdeTorres,
            colombiaSantanderSanAndres,
            colombiaSantanderSanBenito,
            colombiaSantanderSanGil,
            colombiaSantanderSanJoaquin,
            colombiaSantanderSanJoseDdeMiranda,
            colombiaSantanderSanMiguel,
            colombiaSantanderSanVicenteDdeChucuri,
            colombiaSantanderSantaBarbara,
            colombiaSantanderSimacota,
            colombiaSantanderSocorro,
            colombiaSantanderSuaita,
            colombiaSantanderSucre,
            colombiaSantanderSurata,
            colombiaSantanderTona,
            colombiaSantanderValleDdeSanJose,
            colombiaSantanderVelez,
            colombiaSantanderVetas,
            colombiaSantanderVillanueva,
            colombiaSantanderZapatoca
          ]);
const Region colombiaSucre = Region(id: 2902, parentId: 48, longitude: -74.723283, latitude: 8.813977,
          name: "Sucre", type: null, stateCode: "SUC",
          cities: [
            colombiaSucreCaimito,
            colombiaSucreChalan,
            colombiaSucreColoso,
            colombiaSucreCorozal,
            colombiaSucreCovenas,
            colombiaSucreElRoble,
            colombiaSucreGaleras,
            colombiaSucreGuaranda,
            colombiaSucreLaUnion,
            colombiaSucreLosPalmitos,
            colombiaSucreMajagual,
            colombiaSucreMorroa,
            colombiaSucreOvejas,
            colombiaSucrePalmito,
            colombiaSucreSampues,
            colombiaSucreSanBenitoAbad,
            colombiaSucreSanJuanDdeBetulia,
            colombiaSucreSanLuisDdeSince,
            colombiaSucreSanMarcos,
            colombiaSucreSanOnofre,
            colombiaSucreSanPedro,
            colombiaSucreSantiagoDdeTolu,
            colombiaSucreSincelejo,
            colombiaSucreSucre,
            colombiaSucreToluViejo
          ]);
const Region colombiaTolima = Region(id: 2883, parentId: 48, longitude: -75.1545381, latitude: 4.0925168,
          name: "Tolima", type: null, stateCode: "TOL",
          cities: [
            colombiaTolimaAlpujarra,
            colombiaTolimaAlvarado,
            colombiaTolimaAmbalema,
            colombiaTolimaAnaime,
            colombiaTolimaAnzoategui,
            colombiaTolimaArmero,
            colombiaTolimaArmeroHypGuyabal,
            colombiaTolimaAtaco,
            colombiaTolimaCajamarca,
            colombiaTolimaCampoAlegre,
            colombiaTolimaCarmenDdeApicala,
            colombiaTolimaCasabianca,
            colombiaTolimaChaparral,
            colombiaTolimaChicoral,
            colombiaTolimaCoello,
            colombiaTolimaCoyaima,
            colombiaTolimaCunday,
            colombiaTolimaDoima,
            colombiaTolimaDolores,
            colombiaTolimaEspinal,
            colombiaTolimaFalan,
            colombiaTolimaFlandes,
            colombiaTolimaFresno,
            colombiaTolimaFrias,
            colombiaTolimaGaitania,
            colombiaTolimaGuamo,
            colombiaTolimaGuayabal,
            colombiaTolimaHerveo,
            colombiaTolimaHonda,
            colombiaTolimaIbague,
            colombiaTolimaIcononzo,
            colombiaTolimaJunin,
            colombiaTolimaLaChamba,
            colombiaTolimaLaureles,
            colombiaTolimaLerida,
            colombiaTolimaLibano,
            colombiaTolimaMelgar,
            colombiaTolimaMunicipioDdeSanSebastianDdeMariquita,
            colombiaTolimaMurillo,
            colombiaTolimaNatagaima,
            colombiaTolimaOrtega,
            colombiaTolimaPadua,
            colombiaTolimaPalocabildo,
            colombiaTolimaPayande,
            colombiaTolimaPiedras,
            colombiaTolimaPlanadas,
            colombiaTolimaPlayarrica,
            colombiaTolimaPrado,
            colombiaTolimaPurificacion,
            colombiaTolimaRioblanco,
            colombiaTolimaRoncesvalles,
            colombiaTolimaRovira,
            colombiaTolimaSaldana,
            colombiaTolimaSanAntonio,
            colombiaTolimaSanLuis,
            colombiaTolimaSanSebastianDdeMariquita,
            colombiaTolimaSantaIsabel,
            colombiaTolimaSantiagoPerez,
            colombiaTolimaSuarez,
            colombiaTolimaTresEsquinas,
            colombiaTolimaValleDdeSanJuan,
            colombiaTolimaVenadillo,
            colombiaTolimaVillahermosa,
            colombiaTolimaVillarrica
          ]);
const Region colombiaValleDdelCauca = Region(id: 2904, parentId: 48, longitude: -76.6412712, latitude: 3.8008893,
          name: "Valle del Cauca", type: null, stateCode: "VAC",
          cities: [
            colombiaValleDdelCaucaAlcala,
            colombiaValleDdelCaucaAndalucia,
            colombiaValleDdelCaucaAnsermanuevo,
            colombiaValleDdelCaucaArgelia,
            colombiaValleDdelCaucaBolivar,
            colombiaValleDdelCaucaBuenaventura,
            colombiaValleDdelCaucaBugalagrande,
            colombiaValleDdelCaucaCaicedonia,
            colombiaValleDdelCaucaCali,
            colombiaValleDdelCaucaCalima,
            colombiaValleDdelCaucaCandelaria,
            colombiaValleDdelCaucaCartago,
            colombiaValleDdelCaucaDagua,
            colombiaValleDdelCaucaDarien,
            colombiaValleDdelCaucaElAguila,
            colombiaValleDdelCaucaElCairo,
            colombiaValleDdelCaucaElCerrito,
            colombiaValleDdelCaucaElDovio,
            colombiaValleDdelCaucaFlorida,
            colombiaValleDdelCaucaGinebra,
            colombiaValleDdelCaucaGuacari,
            colombiaValleDdelCaucaGuadalajaraDdeBuga,
            colombiaValleDdelCaucaJamundi,
            colombiaValleDdelCaucaLaCumbre,
            colombiaValleDdelCaucaLaUnion,
            colombiaValleDdelCaucaLaVictoria,
            colombiaValleDdelCaucaObando,
            colombiaValleDdelCaucaPalmira,
            colombiaValleDdelCaucaPradera,
            colombiaValleDdelCaucaRestrepo,
            colombiaValleDdelCaucaRiofrio,
            colombiaValleDdelCaucaRoldanillo,
            colombiaValleDdelCaucaSanPedro,
            colombiaValleDdelCaucaSevilla,
            colombiaValleDdelCaucaToro,
            colombiaValleDdelCaucaTrujillo,
            colombiaValleDdelCaucaTulua,
            colombiaValleDdelCaucaUlloa,
            colombiaValleDdelCaucaVersalles,
            colombiaValleDdelCaucaVijes,
            colombiaValleDdelCaucaYotoco,
            colombiaValleDdelCaucaYumbo,
            colombiaValleDdelCaucaZarzal
          ]);
const Region colombiaVaupes = Region(id: 2885, parentId: 48, longitude: -70.8119953, latitude: 0.8553561,
          name: "Vaupés", type: null, stateCode: "VAU",
          cities: [
            colombiaVaupesCaruru,
            colombiaVaupesMitu,
            colombiaVaupesPacoa,
            colombiaVaupesPapunaua,
            colombiaVaupesTaraira,
            colombiaVaupesYavarate
          ]);
const Region colombiaVichada = Region(id: 2894, parentId: 48, longitude: -69.2877535, latitude: 4.4234452,
          name: "Vichada", type: null, stateCode: "VID",
          cities: [
            colombiaVichadaCumaribo,
            colombiaVichadaLaPrimavera,
            colombiaVichadaPuertoCarreno,
            colombiaVichadaSantaRosalia
          ]);

const colombiaStates = <int, Region>{
    2895: colombiaAmazonas,
    2890: colombiaAntioquia,
    2881: colombiaArauca,
    2880: colombiaAtlantico,
    4921: colombiaBogota,
    2893: colombiaBolivar,
    2903: colombiaBoyaca,
    2887: colombiaCaldas,
    2891: colombiaCaqueta,
    2892: colombiaCasanare,
    2884: colombiaCauca,
    2899: colombiaCesar,
    2876: colombiaChoco,
    2898: colombiaCordoba,
    2875: colombiaCundinamarca,
    2882: colombiaGuainia,
    2888: colombiaGuaviare,
    4871: colombiaHuila,
    2889: colombiaLaGuajira,
    2886: colombiaMagdalena,
    2878: colombiaMeta,
    2897: colombiaNarino,
    2877: colombiaNorteDdeSantander,
    2896: colombiaPutumayo,
    2874: colombiaQuindio,
    2879: colombiaRisaralda,
    2900: colombiaSanAndresProvidenciaYySantaCatalina,
    2901: colombiaSantander,
    2902: colombiaSucre,
    2883: colombiaTolima,
    2904: colombiaValleDdelCauca,
    2885: colombiaVaupes,
    2894: colombiaVichada
  };
