/// Access to known geographies in Comoros and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'comoros_cities.dart';

/// The 3 regions of `🇰🇲 Comoros`
const Region comorosAnjouan = Region(
    id: 2821,
    parentId: 49,
    longitude: 44.4370606,
    latitude: -12.2138145,
    name: "Anjouan",
    type: null,
    stateCode: "A",
    cities: [
      comorosAnjouanAddaHypDoueni,
      comorosAnjouanAntsahe,
      comorosAnjouanAssimpao,
      comorosAnjouanBambao,
      comorosAnjouanBandajou,
      comorosAnjouanBarakani,
      comorosAnjouanBimbini,
      comorosAnjouanBoungoueni,
      comorosAnjouanChandra,
      comorosAnjouanChironkamba,
      comorosAnjouanChitrouni,
      comorosAnjouanDaji,
      comorosAnjouanDomoni,
      comorosAnjouanDziani,
      comorosAnjouanHajoho,
      comorosAnjouanHarembo,
      comorosAnjouanKangani,
      comorosAnjouanKavani,
      comorosAnjouanKoki,
      comorosAnjouanKoniHypDjodjo,
      comorosAnjouanKoniHypNgani,
      comorosAnjouanKyo,
      comorosAnjouanLimbi,
      comorosAnjouanLingoni,
      comorosAnjouanMagnassiniHypNindri,
      comorosAnjouanMarahare,
      comorosAnjouanMirontsi,
      comorosAnjouanMjamaoue,
      comorosAnjouanMjimandra,
      comorosAnjouanMoutsamoudou,
      comorosAnjouanMoya,
      comorosAnjouanMramani,
      comorosAnjouanMremani,
      comorosAnjouanOngoni,
      comorosAnjouanOuani,
      comorosAnjouanOuzini,
      comorosAnjouanPaje,
      comorosAnjouanPatsi,
      comorosAnjouanSima,
      comorosAnjouanTsimbeo,
      comorosAnjouanVouani
    ]);
const Region comorosGrandeComore = Region(
    id: 2822,
    parentId: 49,
    longitude: 43.3680788,
    latitude: -11.7167338,
    name: "Grande Comore",
    type: null,
    stateCode: "G",
    cities: [
      comorosGrandeComoreBahani,
      comorosGrandeComoreBambadjani,
      comorosGrandeComoreBouni,
      comorosGrandeComoreChezani,
      comorosGrandeComoreChindini,
      comorosGrandeComoreChouani,
      comorosGrandeComoreDembeni,
      comorosGrandeComoreDouniani,
      comorosGrandeComoreDzahadjou,
      comorosGrandeComoreFoumbouni,
      comorosGrandeComoreHantsindzi,
      comorosGrandeComoreHeroumbili,
      comorosGrandeComoreItsandra,
      comorosGrandeComoreItsandzeni,
      comorosGrandeComoreIvouani,
      comorosGrandeComoreKoua,
      comorosGrandeComoreMadjeoueni,
      comorosGrandeComoreMandza,
      comorosGrandeComoreMavingouni,
      comorosGrandeComoreMbeni,
      comorosGrandeComoreMitsamiouli,
      comorosGrandeComoreMitsoudje,
      comorosGrandeComoreMnoungou,
      comorosGrandeComoreMohoro,
      comorosGrandeComoreMoroni,
      comorosGrandeComoreMtsamdou,
      comorosGrandeComoreMvouni,
      comorosGrandeComoreNioumamilima,
      comorosGrandeComoreNtsaoueni,
      comorosGrandeComoreNtsoudjini,
      comorosGrandeComoreOuellah,
      comorosGrandeComoreOuhozi,
      comorosGrandeComoreOuroveni,
      comorosGrandeComoreOussivo,
      comorosGrandeComoreSalimani,
      comorosGrandeComoreSelea,
      comorosGrandeComoreSingani,
      comorosGrandeComoreTsidje,
      comorosGrandeComoreVanadjou,
      comorosGrandeComoreVanambouani
    ]);
const Region comorosMoheli = Region(
    id: 2820,
    parentId: 49,
    longitude: 43.7334089,
    latitude: -12.3377376,
    name: "Mohéli",
    type: null,
    stateCode: "M",
    cities: [
      comorosMoheliDjoyezi,
      comorosMoheliFomboni,
      comorosMoheliHoani,
      comorosMoheliMtakoudja,
      comorosMoheliNioumachoua,
      comorosMoheliOuanani,
      comorosMoheliZiroudani
    ]);

const comorosStates = <int, Region>{
  2821: comorosAnjouan,
  2822: comorosGrandeComore,
  2820: comorosMoheli
};
