/// Access to known geographies in Costa Rica and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'costa_rica_cities.dart';

/// The 7 regions of `🇨🇷 Costa Rica`
const Region costaRicaAlajuelaProvince = Region(
    id: 1215,
    parentId: 53,
    longitude: -84.4382721,
    latitude: 10.391583,
    name: "Alajuela Province",
    type: null,
    stateCode: "A",
    cities: [
      costaRicaAlajuelaProvinceAlajuela,
      costaRicaAlajuelaProvinceAtenas,
      costaRicaAlajuelaProvinceBijagua,
      costaRicaAlajuelaProvinceCarrillos,
      costaRicaAlajuelaProvinceDesamparados,
      costaRicaAlajuelaProvinceEsquipulas,
      costaRicaAlajuelaProvinceGrecia,
      costaRicaAlajuelaProvinceGuatuso,
      costaRicaAlajuelaProvinceLaFortuna,
      costaRicaAlajuelaProvinceLosChiles,
      costaRicaAlajuelaProvinceNaranjo,
      costaRicaAlajuelaProvinceOrotina,
      costaRicaAlajuelaProvincePalmares,
      costaRicaAlajuelaProvincePital,
      costaRicaAlajuelaProvincePoas,
      costaRicaAlajuelaProvincePocosol,
      costaRicaAlajuelaProvinceQuesada,
      costaRicaAlajuelaProvinceRioSegundo,
      costaRicaAlajuelaProvinceSabanilla,
      costaRicaAlajuelaProvinceSanCarlos,
      costaRicaAlajuelaProvinceSanJose,
      costaRicaAlajuelaProvinceSanJuan,
      costaRicaAlajuelaProvinceSanMateo,
      costaRicaAlajuelaProvinceSanRafael,
      costaRicaAlajuelaProvinceSanRamon,
      costaRicaAlajuelaProvinceSantiago,
      costaRicaAlajuelaProvinceUpala,
      costaRicaAlajuelaProvinceValverdeVega,
      costaRicaAlajuelaProvinceZarcero
    ]);
const Region costaRicaGuanacasteProvince = Region(
    id: 1209,
    parentId: 53,
    longitude: -85.4436706,
    latitude: 10.6267399,
    name: "Guanacaste Province",
    type: null,
    stateCode: "G",
    cities: [
      costaRicaGuanacasteProvinceAbangares,
      costaRicaGuanacasteProvinceBagaces,
      costaRicaGuanacasteProvinceBelen,
      costaRicaGuanacasteProvinceCanas,
      costaRicaGuanacasteProvinceCarrillo,
      costaRicaGuanacasteProvinceFortuna,
      costaRicaGuanacasteProvinceHojancha,
      costaRicaGuanacasteProvinceJuntas,
      costaRicaGuanacasteProvinceLaCruz,
      costaRicaGuanacasteProvinceLiberia,
      costaRicaGuanacasteProvinceNandayure,
      costaRicaGuanacasteProvinceNicoya,
      costaRicaGuanacasteProvinceSamara,
      costaRicaGuanacasteProvinceSantaCruz,
      costaRicaGuanacasteProvinceSardinal,
      costaRicaGuanacasteProvinceTilaran
    ]);
const Region costaRicaHerediaProvince = Region(
    id: 1212,
    parentId: 53,
    longitude: -84.0167423,
    latitude: 10.473523,
    name: "Heredia Province",
    type: null,
    stateCode: "H",
    cities: [
      costaRicaHerediaProvinceAngeles,
      costaRicaHerediaProvinceBarva,
      costaRicaHerediaProvinceBelen,
      costaRicaHerediaProvinceFlores,
      costaRicaHerediaProvinceHeredia,
      costaRicaHerediaProvinceLaAsuncion,
      costaRicaHerediaProvinceLlorente,
      costaRicaHerediaProvinceMercedes,
      costaRicaHerediaProvinceSanAntonio,
      costaRicaHerediaProvinceSanFrancisco,
      costaRicaHerediaProvinceSanIsidro,
      costaRicaHerediaProvinceSanJosecito,
      costaRicaHerediaProvinceSanPablo,
      costaRicaHerediaProvinceSanRafael,
      costaRicaHerediaProvinceSantaBarbara,
      costaRicaHerediaProvinceSantoDomingo,
      costaRicaHerediaProvinceSarapiqui
    ]);
const Region costaRicaLimonProvince = Region(
    id: 1213,
    parentId: 53,
    longitude: -83.0332417,
    latitude: 9.9896398,
    name: "Limón Province",
    type: null,
    stateCode: "L",
    cities: [
      costaRicaLimonProvinceBatan,
      costaRicaLimonProvinceGuacimo,
      costaRicaLimonProvinceGuapiles,
      costaRicaLimonProvinceLimon,
      costaRicaLimonProvinceMatina,
      costaRicaLimonProvincePococi,
      costaRicaLimonProvincePocora,
      costaRicaLimonProvinceRoxana,
      costaRicaLimonProvinceSiquirres,
      costaRicaLimonProvinceSixaola,
      costaRicaLimonProvinceTalamanca
    ]);
const Region costaRicaProvinciaDdeCartago = Region(
    id: 1211,
    parentId: 53,
    longitude: -83.9214187,
    latitude: 9.8622311,
    name: "Provincia de Cartago",
    type: null,
    stateCode: "C",
    cities: [
      costaRicaProvinciaDdeCartagoAlvarado,
      costaRicaProvinciaDdeCartagoCartago,
      costaRicaProvinciaDdeCartagoConcepcion,
      costaRicaProvinciaDdeCartagoCot,
      costaRicaProvinciaDdeCartagoElGuarco,
      costaRicaProvinciaDdeCartagoJimenez,
      costaRicaProvinciaDdeCartagoLaSuiza,
      costaRicaProvinciaDdeCartagoLaUnion,
      costaRicaProvinciaDdeCartagoOreamuno,
      costaRicaProvinciaDdeCartagoOrosi,
      costaRicaProvinciaDdeCartagoPacayas,
      costaRicaProvinciaDdeCartagoParaiso,
      costaRicaProvinciaDdeCartagoPejibaye,
      costaRicaProvinciaDdeCartagoSanDiego,
      costaRicaProvinciaDdeCartagoTobosi,
      costaRicaProvinciaDdeCartagoTresRios,
      costaRicaProvinciaDdeCartagoTucurrique,
      costaRicaProvinciaDdeCartagoTurrialba
    ]);
const Region costaRicaPuntarenasProvince = Region(
    id: 1210,
    parentId: 53,
    longitude: -83.336188,
    latitude: 9.2169531,
    name: "Puntarenas Province",
    type: null,
    stateCode: "P",
    cities: [
      costaRicaPuntarenasProvinceBuenosAires,
      costaRicaPuntarenasProvinceCanoas,
      costaRicaPuntarenasProvinceChacarita,
      costaRicaPuntarenasProvinceCiudadCortes,
      costaRicaPuntarenasProvinceCorredor,
      costaRicaPuntarenasProvinceCorredores,
      costaRicaPuntarenasProvinceCotoBrus,
      costaRicaPuntarenasProvinceEsparza,
      costaRicaPuntarenasProvinceGarabito,
      costaRicaPuntarenasProvinceGolfito,
      costaRicaPuntarenasProvinceJaco,
      costaRicaPuntarenasProvinceMiramar,
      costaRicaPuntarenasProvinceMontesDdeOro,
      costaRicaPuntarenasProvinceOsa,
      costaRicaPuntarenasProvincePaquera,
      costaRicaPuntarenasProvinceParrita,
      costaRicaPuntarenasProvincePuntarenas,
      costaRicaPuntarenasProvinceQuepos,
      costaRicaPuntarenasProvinceSanVito
    ]);
const Region costaRicaSanJoseProvince = Region(
    id: 1214,
    parentId: 53,
    longitude: -84.0768294,
    latitude: 9.9129727,
    name: "San José Province",
    type: null,
    stateCode: "SJ",
    cities: [
      costaRicaSanJoseProvinceAcosta,
      costaRicaSanJoseProvinceAlajuelita,
      costaRicaSanJoseProvinceAserri,
      costaRicaSanJoseProvinceCalleBlancos,
      costaRicaSanJoseProvinceColima,
      costaRicaSanJoseProvinceColon,
      costaRicaSanJoseProvinceCurridabat,
      costaRicaSanJoseProvinceDanielFlores,
      costaRicaSanJoseProvinceDesamparados,
      costaRicaSanJoseProvinceDota,
      costaRicaSanJoseProvinceEscazu,
      costaRicaSanJoseProvinceGoicoechea,
      costaRicaSanJoseProvinceGranadilla,
      costaRicaSanJoseProvinceGuadalupe,
      costaRicaSanJoseProvinceIpis,
      costaRicaSanJoseProvinceLeonCortes,
      costaRicaSanJoseProvinceMercedes,
      costaRicaSanJoseProvinceMontesDdeOca,
      costaRicaSanJoseProvinceMora,
      costaRicaSanJoseProvinceMoravia,
      costaRicaSanJoseProvincePalmichal,
      costaRicaSanJoseProvincePatarra,
      costaRicaSanJoseProvincePerezZeledon,
      costaRicaSanJoseProvincePuriscal,
      costaRicaSanJoseProvincePurral,
      costaRicaSanJoseProvinceSabanilla,
      costaRicaSanJoseProvinceSalitral,
      costaRicaSanJoseProvinceSalitrillos,
      costaRicaSanJoseProvinceSanFelipe,
      costaRicaSanJoseProvinceSanIgnacio,
      costaRicaSanJoseProvinceSanIsidro,
      costaRicaSanJoseProvinceSanJose,
      costaRicaSanJoseProvinceSanJuan,
      costaRicaSanJoseProvinceSanJuanDdeDios,
      costaRicaSanJoseProvinceSanMarcos,
      costaRicaSanJoseProvinceSanMiguel,
      costaRicaSanJoseProvinceSanPedro,
      costaRicaSanJoseProvinceSanRafael,
      costaRicaSanJoseProvinceSanRafaelAbajo,
      costaRicaSanJoseProvinceSanRafaelArriba,
      costaRicaSanJoseProvinceSanVicente,
      costaRicaSanJoseProvinceSanVicenteDdeMoravia,
      costaRicaSanJoseProvinceSantaAna,
      costaRicaSanJoseProvinceSantiago,
      costaRicaSanJoseProvinceTarrazu,
      costaRicaSanJoseProvinceTejar,
      costaRicaSanJoseProvinceTibas,
      costaRicaSanJoseProvinceTurrubares,
      costaRicaSanJoseProvinceVazquezDdeCoronado
    ]);

const costaRicaStates = <int, Region>{
  1215: costaRicaAlajuelaProvince,
  1209: costaRicaGuanacasteProvince,
  1212: costaRicaHerediaProvince,
  1213: costaRicaLimonProvince,
  1211: costaRicaProvinciaDdeCartago,
  1210: costaRicaPuntarenasProvince,
  1214: costaRicaSanJoseProvince
};
