/// Access to known geographies in Czech Republic and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'czechrepublic_states.dart';

/// The country of `Czech Republic`, and its 90 states
const Country czechRepublic = Country(
  id: 58,
  name: "Czech Republic",
  longitude: 15.5,
  latitude: 49.75,
  capital: "Prague",
  currency: "CZK",
  currencySymbol: "Kč",
  currencyName: "Czech koruna",
  emoji: "🇨🇿",
  emojiU: "U+1F1E8 U+1F1FF",
  iso2: "CZ",
  iso3: "CZE",
  native: "Česká republika",
  numericCode: "203",
  nationality: "Czech",
  phoneCode: "420",
  region: "Europe",
  subregion: "Eastern Europe",
  tld: ".cz",
  states: [
    czechRepublicBenesov,
    czechRepublicBeroun,
    czechRepublicBlansko,
    czechRepublicBreclav,
    czechRepublicBrnoHypmesto,
    czechRepublicBrnoHypvenkov,
    czechRepublicBruntal,
    czechRepublicCeskaLipa,
    czechRepublicCeskeBudejovice,
    czechRepublicCeskyKrumlov,
    czechRepublicCheb,
    czechRepublicChomutov,
    czechRepublicChrudim,
    czechRepublicDecin,
    czechRepublicDomazlice,
    czechRepublicFrydekHypmistek,
    czechRepublicHavlickuvBrod,
    czechRepublicHodonin,
    czechRepublicHradecKralove,
    czechRepublicJablonecNadNisou,
    czechRepublicJesenik,
    czechRepublicJicin,
    czechRepublicJihlava,
    czechRepublicJihoceskyKraj,
    czechRepublicJihomoravskyKraj,
    czechRepublicJindrichuvHradec,
    czechRepublicKarlovarskyKraj,
    czechRepublicKarlovyVary,
    czechRepublicKarvina,
    czechRepublicKladno,
    czechRepublicKlatovy,
    czechRepublicKolin,
    czechRepublicKrajVysocina,
    czechRepublicKralovehradeckyKraj,
    czechRepublicKromeriz,
    czechRepublicKutnaHora,
    czechRepublicLiberec,
    czechRepublicLibereckyKraj,
    czechRepublicLitomerice,
    czechRepublicLouny,
    czechRepublicMelnik,
    czechRepublicMladaBoleslav,
    czechRepublicMoravskoslezskyKraj,
    czechRepublicMost,
    czechRepublicNachod,
    czechRepublicNovyJicin,
    czechRepublicNymburk,
    czechRepublicOlomouc,
    czechRepublicOlomouckyKraj,
    czechRepublicOpava,
    czechRepublicOstravaHypmesto,
    czechRepublicPardubice,
    czechRepublicPardubickyKraj,
    czechRepublicPelhrimov,
    czechRepublicPisek,
    czechRepublicPlzenHypjih,
    czechRepublicPlzenHypmesto,
    czechRepublicPlzenHypsever,
    czechRepublicPlzenskyKraj,
    czechRepublicPrachatice,
    czechRepublicPrahaHypvychod,
    czechRepublicPrahaHypzapad,
    czechRepublicPrahaHlavniMesto,
    czechRepublicPrerov,
    czechRepublicPribram,
    czechRepublicProstejov,
    czechRepublicRakovnik,
    czechRepublicRokycany,
    czechRepublicRychnovNadKneznou,
    czechRepublicSemily,
    czechRepublicSokolov,
    czechRepublicStrakonice,
    czechRepublicStredoceskyKraj,
    czechRepublicSumperk,
    czechRepublicSvitavy,
    czechRepublicTabor,
    czechRepublicTachov,
    czechRepublicTeplice,
    czechRepublicTrebic,
    czechRepublicTrutnov,
    czechRepublicUherskeHradiste,
    czechRepublicUsteckyKraj,
    czechRepublicUstiNadLabem,
    czechRepublicUstiNadOrlici,
    czechRepublicVsetin,
    czechRepublicVyskov,
    czechRepublicZdarNadSazavou,
    czechRepublicZlin,
    czechRepublicZlinskyKraj,
    czechRepublicZnojmo
  ],
  timezones: [],
  translations: {
    "kr": "체코",
    "pt-BR": "República Tcheca",
    "pt": "República Checa",
    "nl": "Tsjechië",
    "hr": "Češka",
    "fa": "جمهوری چک",
    "de": "Tschechische Republik",
    "es": "República Checa",
    "fr": "République tchèque",
    "ja": "チェコ",
    "it": "Repubblica Ceca",
    "cn": "捷克",
    "tr": "Çekya"
  });
