/// Access to known geographies in Finland and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'finland_cities.dart';

/// The 21 regions of `🇫🇮 Finland`
const Region finlandAlandIslands = Region(
    id: 1509,
    parentId: 74,
    longitude: 19.9156105,
    latitude: 60.1785247,
    name: "Åland Islands",
    type: null,
    stateCode: "01",
    cities: []);
const Region finlandCentralFinland = Region(
    id: 1511,
    parentId: 74,
    longitude: 25.5549445,
    latitude: 62.5666743,
    name: "Central Finland",
    type: null,
    stateCode: "08",
    cities: [
      finlandCentralFinlandAanekoski,
      finlandCentralFinlandHankasalmi,
      finlandCentralFinlandJamsa,
      finlandCentralFinlandJamsankoski,
      finlandCentralFinlandJoutsa,
      finlandCentralFinlandJyvaskyla,
      finlandCentralFinlandKannonkoski,
      finlandCentralFinlandKarstula,
      finlandCentralFinlandKeuruu,
      finlandCentralFinlandKinnula,
      finlandCentralFinlandKivijarvi,
      finlandCentralFinlandKonnevesi,
      finlandCentralFinlandKorpilahti,
      finlandCentralFinlandKuhmoinen,
      finlandCentralFinlandKyyjarvi,
      finlandCentralFinlandLaukaa,
      finlandCentralFinlandLeivonmaki,
      finlandCentralFinlandLuhanka,
      finlandCentralFinlandMultia,
      finlandCentralFinlandMuurame,
      finlandCentralFinlandPetajavesi,
      finlandCentralFinlandPihtipudas,
      finlandCentralFinlandPylkonmaki,
      finlandCentralFinlandSaarijarvi,
      finlandCentralFinlandSaynatsalo,
      finlandCentralFinlandSumiainen,
      finlandCentralFinlandSuolahti,
      finlandCentralFinlandToivakka,
      finlandCentralFinlandUurainen,
      finlandCentralFinlandViitasaari
    ]);
const Region finlandCentralOstrobothnia = Region(
    id: 1494,
    parentId: 74,
    longitude: 24.0013631,
    latitude: 63.5621735,
    name: "Central Ostrobothnia",
    type: null,
    stateCode: "07",
    cities: [
      finlandCentralOstrobothniaHalsua,
      finlandCentralOstrobothniaKalvia,
      finlandCentralOstrobothniaKannus,
      finlandCentralOstrobothniaKaustinen,
      finlandCentralOstrobothniaKokkola,
      finlandCentralOstrobothniaLestijarvi,
      finlandCentralOstrobothniaLohtaja,
      finlandCentralOstrobothniaPerho,
      finlandCentralOstrobothniaToholampi,
      finlandCentralOstrobothniaUllava,
      finlandCentralOstrobothniaVeteli
    ]);
const Region finlandEasternFinlandProvince = Region(
    id: 1492,
    parentId: 74,
    longitude: 28.5024042,
    latitude: 62.5633891,
    name: "Eastern Finland Province",
    type: null,
    stateCode: "IS",
    cities: []);
const Region finlandFinlandProper = Region(
    id: 1507,
    parentId: 74,
    longitude: 22.4439369,
    latitude: 60.3627914,
    name: "Finland Proper",
    type: null,
    stateCode: "19",
    cities: [
      finlandFinlandProperAlastaro,
      finlandFinlandProperAskainen,
      finlandFinlandProperAura,
      finlandFinlandProperDragsfjard,
      finlandFinlandProperHalikko,
      finlandFinlandProperHoutskar,
      finlandFinlandProperInio,
      finlandFinlandProperKaarina,
      finlandFinlandProperKarinainen,
      finlandFinlandProperKiikala,
      finlandFinlandProperKimito,
      finlandFinlandProperKisko,
      finlandFinlandProperKustavi,
      finlandFinlandProperKuusjoki,
      finlandFinlandProperLaitila,
      finlandFinlandProperLemu,
      finlandFinlandProperLieto,
      finlandFinlandProperMarttila,
      finlandFinlandProperMasku,
      finlandFinlandProperMellila,
      finlandFinlandProperMerimasku,
      finlandFinlandProperMietoinen,
      finlandFinlandProperMuurla,
      finlandFinlandProperMynamaki,
      finlandFinlandProperNaantali,
      finlandFinlandProperNagu,
      finlandFinlandProperNousiainen,
      finlandFinlandProperOripaa,
      finlandFinlandProperPaimio,
      finlandFinlandProperPargas,
      finlandFinlandProperPernio,
      finlandFinlandProperPertteli,
      finlandFinlandProperPiikkio,
      finlandFinlandProperPoytya,
      finlandFinlandProperPyharanta,
      finlandFinlandProperRaisio,
      finlandFinlandProperRusko,
      finlandFinlandProperRymattyla,
      finlandFinlandProperSalo,
      finlandFinlandProperSarkisalo,
      finlandFinlandProperSauvo,
      finlandFinlandProperSomero,
      finlandFinlandProperSuomusjarvi,
      finlandFinlandProperTaivassalo,
      finlandFinlandProperTarvasjoki,
      finlandFinlandProperTurku,
      finlandFinlandProperUusikaupunki,
      finlandFinlandProperVahto,
      finlandFinlandProperVastaboland,
      finlandFinlandProperVastanfjard,
      finlandFinlandProperVehmaa,
      finlandFinlandProperVelkua,
      finlandFinlandProperYlane
    ]);
const Region finlandKainuu = Region(
    id: 1496,
    parentId: 74,
    longitude: 28.7437475,
    latitude: 64.3736564,
    name: "Kainuu",
    type: null,
    stateCode: "05",
    cities: [
      finlandKainuuHyrynsalmi,
      finlandKainuuKajaani,
      finlandKainuuKuhmo,
      finlandKainuuPaltamo,
      finlandKainuuPuolanka,
      finlandKainuuRistijarvi,
      finlandKainuuSotkamo,
      finlandKainuuSuomussalmi,
      finlandKainuuVaala,
      finlandKainuuVuokatti,
      finlandKainuuVuolijoki
    ]);
const Region finlandKymenlaakso = Region(
    id: 1512,
    parentId: 74,
    longitude: 26.8829336,
    latitude: 60.780512,
    name: "Kymenlaakso",
    type: null,
    stateCode: "09",
    cities: [
      finlandKymenlaaksoAnjala,
      finlandKymenlaaksoElimaki,
      finlandKymenlaaksoHamina,
      finlandKymenlaaksoIitti,
      finlandKymenlaaksoJaala,
      finlandKymenlaaksoKarhula,
      finlandKymenlaaksoKotka,
      finlandKymenlaaksoKouvola,
      finlandKymenlaaksoMiehikkala,
      finlandKymenlaaksoPyhtaa,
      finlandKymenlaaksoVirojoki
    ]);
const Region finlandLapland = Region(
    id: 1500,
    parentId: 74,
    longitude: 26.5046438,
    latitude: 67.9222304,
    name: "Lapland",
    type: null,
    stateCode: "LL",
    cities: [
      finlandLaplandEnontekio,
      finlandLaplandInari,
      finlandLaplandIvalo,
      finlandLaplandKemi,
      finlandLaplandKemijarvi,
      finlandLaplandKeminmaa,
      finlandLaplandKittila,
      finlandLaplandKolari,
      finlandLaplandMuonio,
      finlandLaplandPelkosenniemi,
      finlandLaplandPello,
      finlandLaplandPosio,
      finlandLaplandPyhajarvi,
      finlandLaplandRanua,
      finlandLaplandRovaniemi,
      finlandLaplandSalla,
      finlandLaplandSavukoski,
      finlandLaplandSimo,
      finlandLaplandSodankyla,
      finlandLaplandTervola,
      finlandLaplandTornio,
      finlandLaplandUtsjoki,
      finlandLaplandYlitornio
    ]);
const Region finlandNorthKarelia = Region(
    id: 1504,
    parentId: 74,
    longitude: 30.1553887,
    latitude: 62.8062078,
    name: "North Karelia",
    type: null,
    stateCode: "13",
    cities: [
      finlandNorthKareliaEno,
      finlandNorthKareliaIlomantsi,
      finlandNorthKareliaJoensuu,
      finlandNorthKareliaJuuka,
      finlandNorthKareliaKesalahti,
      finlandNorthKareliaKiihtelysvaara,
      finlandNorthKareliaKitee,
      finlandNorthKareliaKontiolahti,
      finlandNorthKareliaLieksa,
      finlandNorthKareliaLiperi,
      finlandNorthKareliaNurmes,
      finlandNorthKareliaOutokumpu,
      finlandNorthKareliaPolvijarvi,
      finlandNorthKareliaPyhaselka,
      finlandNorthKareliaRaakkyla,
      finlandNorthKareliaTohmajarvi,
      finlandNorthKareliaTuupovaara,
      finlandNorthKareliaValtimo
    ]);
const Region finlandNorthernOstrobothnia = Region(
    id: 1505,
    parentId: 74,
    longitude: 26.2890417,
    latitude: 65.279493,
    name: "Northern Ostrobothnia",
    type: null,
    stateCode: "14",
    cities: [
      finlandNorthernOstrobothniaAlavieska,
      finlandNorthernOstrobothniaHaapajarvi,
      finlandNorthernOstrobothniaHaapavesi,
      finlandNorthernOstrobothniaHailuoto,
      finlandNorthernOstrobothniaHaukipudas,
      finlandNorthernOstrobothniaHimanka,
      finlandNorthernOstrobothniaIi,
      finlandNorthernOstrobothniaKalajoki,
      finlandNorthernOstrobothniaKarsamaki,
      finlandNorthernOstrobothniaKempele,
      finlandNorthernOstrobothniaKestila,
      finlandNorthernOstrobothniaKiiminki,
      finlandNorthernOstrobothniaKuivaniemi,
      finlandNorthernOstrobothniaKuusamo,
      finlandNorthernOstrobothniaLiminka,
      finlandNorthernOstrobothniaLumijoki,
      finlandNorthernOstrobothniaMerijarvi,
      finlandNorthernOstrobothniaMuhos,
      finlandNorthernOstrobothniaNivala,
      finlandNorthernOstrobothniaOulainen,
      finlandNorthernOstrobothniaOulu,
      finlandNorthernOstrobothniaOulunsalo,
      finlandNorthernOstrobothniaPiippola,
      finlandNorthernOstrobothniaPudasjarvi,
      finlandNorthernOstrobothniaPulkkila,
      finlandNorthernOstrobothniaPyhajarvi,
      finlandNorthernOstrobothniaPyhajoki,
      finlandNorthernOstrobothniaPyhanta,
      finlandNorthernOstrobothniaRaahe,
      finlandNorthernOstrobothniaRantsila,
      finlandNorthernOstrobothniaReisjarvi,
      finlandNorthernOstrobothniaRuukki,
      finlandNorthernOstrobothniaSievi,
      finlandNorthernOstrobothniaSiikajoki,
      finlandNorthernOstrobothniaTaivalkoski,
      finlandNorthernOstrobothniaTyrnava,
      finlandNorthernOstrobothniaUtajarvi,
      finlandNorthernOstrobothniaVihanti,
      finlandNorthernOstrobothniaYliHypIi,
      finlandNorthernOstrobothniaYlikiiminki,
      finlandNorthernOstrobothniaYlivieska
    ]);
const Region finlandNorthernSavonia = Region(
    id: 1503,
    parentId: 74,
    longitude: 27.0253504,
    latitude: 63.08448,
    name: "Northern Savonia",
    type: null,
    stateCode: "15",
    cities: []);
const Region finlandOstrobothnia = Region(
    id: 1508,
    parentId: 74,
    longitude: 21.9061062,
    latitude: 63.1181757,
    name: "Ostrobothnia",
    type: null,
    stateCode: "12",
    cities: [
      finlandOstrobothniaHietalahti,
      finlandOstrobothniaIsokyro,
      finlandOstrobothniaJakobstad,
      finlandOstrobothniaKaskinen,
      finlandOstrobothniaKorsholm,
      finlandOstrobothniaKorsnas,
      finlandOstrobothniaKristinestad,
      finlandOstrobothniaKronoby,
      finlandOstrobothniaLaihia,
      finlandOstrobothniaLarsmo,
      finlandOstrobothniaMalax,
      finlandOstrobothniaNykarleby,
      finlandOstrobothniaOravais,
      finlandOstrobothniaPedersore,
      finlandOstrobothniaReplot,
      finlandOstrobothniaRistinummi,
      finlandOstrobothniaTeeriniemi,
      finlandOstrobothniaVaasa,
      finlandOstrobothniaVahakyro,
      finlandOstrobothniaVora
    ]);
const Region finlandOuluProvince = Region(
    id: 1499,
    parentId: 74,
    longitude: 25.4650496,
    latitude: 65.0120748,
    name: "Oulu Province",
    type: null,
    stateCode: "OL",
    cities: []);
const Region finlandPaijanneTavastia = Region(
    id: 1502,
    parentId: 74,
    longitude: 25.7322496,
    latitude: 61.3230041,
    name: "Päijänne Tavastia",
    type: null,
    stateCode: "16",
    cities: [
      finlandPaijanneTavastiaArtjarvi,
      finlandPaijanneTavastiaAsikkala,
      finlandPaijanneTavastiaAuttoinen,
      finlandPaijanneTavastiaHameenkoski,
      finlandPaijanneTavastiaHartola,
      finlandPaijanneTavastiaHeinola,
      finlandPaijanneTavastiaHollola,
      finlandPaijanneTavastiaLahti,
      finlandPaijanneTavastiaNastola,
      finlandPaijanneTavastiaOrimattila,
      finlandPaijanneTavastiaPadasjoki,
      finlandPaijanneTavastiaSysma
    ]);
const Region finlandPirkanmaa = Region(
    id: 1506,
    parentId: 74,
    longitude: 23.7895598,
    latitude: 61.6986918,
    name: "Pirkanmaa",
    type: null,
    stateCode: "11",
    cities: [
      finlandPirkanmaaIisalmi,
      finlandPirkanmaaJuankoski,
      finlandPirkanmaaKaavi,
      finlandPirkanmaaKangaslampi,
      finlandPirkanmaaKarttula,
      finlandPirkanmaaKeitele,
      finlandPirkanmaaKiuruvesi,
      finlandPirkanmaaKuopio,
      finlandPirkanmaaLapinlahti,
      finlandPirkanmaaLeppavirta,
      finlandPirkanmaaMaaninka,
      finlandPirkanmaaNilsia,
      finlandPirkanmaaPielavesi,
      finlandPirkanmaaRautalampi,
      finlandPirkanmaaRautavaara,
      finlandPirkanmaaSiilinjarvi,
      finlandPirkanmaaSonkajarvi,
      finlandPirkanmaaSuonenjoki,
      finlandPirkanmaaTervo,
      finlandPirkanmaaTuusniemi,
      finlandPirkanmaaVarkaus,
      finlandPirkanmaaVarpaisjarvi,
      finlandPirkanmaaVehmersalmi,
      finlandPirkanmaaVesanto,
      finlandPirkanmaaVierema
    ]);
const Region finlandSatakunta = Region(
    id: 1501,
    parentId: 74,
    longitude: 22.1483081,
    latitude: 61.5932758,
    name: "Satakunta",
    type: null,
    stateCode: "17",
    cities: [
      finlandSatakuntaEura,
      finlandSatakuntaEurajoki,
      finlandSatakuntaHarjavalta,
      finlandSatakuntaHuittinen,
      finlandSatakuntaJamijarvi,
      finlandSatakuntaKankaanpaa,
      finlandSatakuntaKarvia,
      finlandSatakuntaKiukainen,
      finlandSatakuntaKokemaki,
      finlandSatakuntaKoylio,
      finlandSatakuntaKullaa,
      finlandSatakuntaLangelmaki,
      finlandSatakuntaLappi,
      finlandSatakuntaLavia,
      finlandSatakuntaLuvia,
      finlandSatakuntaMerikarvia,
      finlandSatakuntaNakkila,
      finlandSatakuntaNoormarkku,
      finlandSatakuntaPomarkku,
      finlandSatakuntaPori,
      finlandSatakuntaRauma,
      finlandSatakuntaSakyla,
      finlandSatakuntaSiikainen,
      finlandSatakuntaUlvila,
      finlandSatakuntaVampula
    ]);
const Region finlandSouthKarelia = Region(
    id: 1497,
    parentId: 74,
    longitude: 28.1024372,
    latitude: 61.1181949,
    name: "South Karelia",
    type: null,
    stateCode: "02",
    cities: [
      finlandSouthKareliaImatra,
      finlandSouthKareliaJoutseno,
      finlandSouthKareliaLappeenranta,
      finlandSouthKareliaLemi,
      finlandSouthKareliaLuumaki,
      finlandSouthKareliaNuijamaa,
      finlandSouthKareliaParikkala,
      finlandSouthKareliaRautjarvi,
      finlandSouthKareliaRuokolahti,
      finlandSouthKareliaSaari,
      finlandSouthKareliaSavitaipale,
      finlandSouthKareliaTaipalsaari,
      finlandSouthKareliaYlamaa
    ]);
const Region finlandSouthernOstrobothnia = Region(
    id: 1498,
    parentId: 74,
    longitude: 23.5285267,
    latitude: 62.9433099,
    name: "Southern Ostrobothnia",
    type: null,
    stateCode: "03",
    cities: [
      finlandSouthernOstrobothniaAhtari,
      finlandSouthernOstrobothniaAlaharma,
      finlandSouthernOstrobothniaAlajarvi,
      finlandSouthernOstrobothniaAlavus,
      finlandSouthernOstrobothniaEvijarvi,
      finlandSouthernOstrobothniaIlmajoki,
      finlandSouthernOstrobothniaIsojoki,
      finlandSouthernOstrobothniaJalasjarvi,
      finlandSouthernOstrobothniaJurva,
      finlandSouthernOstrobothniaKarijoki,
      finlandSouthernOstrobothniaKauhajoki,
      finlandSouthernOstrobothniaKauhava,
      finlandSouthernOstrobothniaKortesjarvi,
      finlandSouthernOstrobothniaKuortane,
      finlandSouthernOstrobothniaKurikka,
      finlandSouthernOstrobothniaLappajarvi,
      finlandSouthernOstrobothniaLapua,
      finlandSouthernOstrobothniaLehtimaki,
      finlandSouthernOstrobothniaNurmo,
      finlandSouthernOstrobothniaSeinajoki,
      finlandSouthernOstrobothniaSoini,
      finlandSouthernOstrobothniaTeuva,
      finlandSouthernOstrobothniaToysa,
      finlandSouthernOstrobothniaVimpeli,
      finlandSouthernOstrobothniaYliharma,
      finlandSouthernOstrobothniaYlistaro
    ]);
const Region finlandSouthernSavonia = Region(
    id: 1495,
    parentId: 74,
    longitude: 27.8005015,
    latitude: 61.6945148,
    name: "Southern Savonia",
    type: null,
    stateCode: "04",
    cities: [
      finlandSouthernSavoniaEnonkoski,
      finlandSouthernSavoniaHaukivuori,
      finlandSouthernSavoniaHeinavesi,
      finlandSouthernSavoniaHirvensalmi,
      finlandSouthernSavoniaJappila,
      finlandSouthernSavoniaJoroinen,
      finlandSouthernSavoniaJuva,
      finlandSouthernSavoniaKangasniemi,
      finlandSouthernSavoniaKerimaki,
      finlandSouthernSavoniaMantyharju,
      finlandSouthernSavoniaMikkeli,
      finlandSouthernSavoniaPertunmaa,
      finlandSouthernSavoniaPieksamaki,
      finlandSouthernSavoniaPunkaharju,
      finlandSouthernSavoniaPuumala,
      finlandSouthernSavoniaRantasalmi,
      finlandSouthernSavoniaRistiina,
      finlandSouthernSavoniaSavonlinna,
      finlandSouthernSavoniaSavonranta,
      finlandSouthernSavoniaSulkava,
      finlandSouthernSavoniaVirtasalmi
    ]);
const Region finlandTavastiaProper = Region(
    id: 1493,
    parentId: 74,
    longitude: 24.3005498,
    latitude: 60.907015,
    name: "Tavastia Proper",
    type: null,
    stateCode: "06",
    cities: [
      finlandTavastiaProperForssa,
      finlandTavastiaProperHameenlinna,
      finlandTavastiaProperHauho,
      finlandTavastiaProperHausjarvi,
      finlandTavastiaProperHumppila,
      finlandTavastiaProperJanakkala,
      finlandTavastiaProperJokioinen,
      finlandTavastiaProperKalvola,
      finlandTavastiaProperLammi,
      finlandTavastiaProperLoppi,
      finlandTavastiaProperRenko,
      finlandTavastiaProperRiihimaki,
      finlandTavastiaProperTammela,
      finlandTavastiaProperTervakoski,
      finlandTavastiaProperTuulos,
      finlandTavastiaProperYpaja
    ]);
const Region finlandUusimaa = Region(
    id: 1510,
    parentId: 74,
    longitude: 25.271621,
    latitude: 60.21872,
    name: "Uusimaa",
    type: null,
    stateCode: "18",
    cities: [
      finlandUusimaaAskola,
      finlandUusimaaEkenas,
      finlandUusimaaEspoo,
      finlandUusimaaGumbole,
      finlandUusimaaHanko,
      finlandUusimaaHelsinki,
      finlandUusimaaHyvinge,
      finlandUusimaaInga,
      finlandUusimaaJarvenpaa,
      finlandUusimaaKaarela,
      finlandUusimaaKallio,
      finlandUusimaaKaris,
      finlandUusimaaKarjalohja,
      finlandUusimaaKarkkila,
      finlandUusimaaKarkola,
      finlandUusimaaKauniainen,
      finlandUusimaaKellokoski,
      finlandUusimaaKerava,
      finlandUusimaaKilo,
      finlandUusimaaKirkkonummi,
      finlandUusimaaKoukkuniemi,
      finlandUusimaaLapinjarvi,
      finlandUusimaaLauttasaari,
      finlandUusimaaLiljendal,
      finlandUusimaaLohja,
      finlandUusimaaLovisa,
      finlandUusimaaMantsala,
      finlandUusimaaMellunkyla,
      finlandUusimaaMunkkiniemi,
      finlandUusimaaMyrskyla,
      finlandUusimaaNurmijarvi,
      finlandUusimaaOtaniemi,
      finlandUusimaaPerna,
      finlandUusimaaPohja,
      finlandUusimaaPornainen,
      finlandUusimaaPorvoo,
      finlandUusimaaPukkila,
      finlandUusimaaRaaseporin,
      finlandUusimaaRuotsinpyhtaa,
      finlandUusimaaSammatti,
      finlandUusimaaSibbo,
      finlandUusimaaSiuntio,
      finlandUusimaaTuusula,
      finlandUusimaaVantaa,
      finlandUusimaaVihti,
      finlandUusimaaVuosaari
    ]);

const finlandStates = <int, Region>{
  1509: finlandAlandIslands,
  1511: finlandCentralFinland,
  1494: finlandCentralOstrobothnia,
  1492: finlandEasternFinlandProvince,
  1507: finlandFinlandProper,
  1496: finlandKainuu,
  1512: finlandKymenlaakso,
  1500: finlandLapland,
  1504: finlandNorthKarelia,
  1505: finlandNorthernOstrobothnia,
  1503: finlandNorthernSavonia,
  1508: finlandOstrobothnia,
  1499: finlandOuluProvince,
  1502: finlandPaijanneTavastia,
  1506: finlandPirkanmaa,
  1501: finlandSatakunta,
  1497: finlandSouthKarelia,
  1498: finlandSouthernOstrobothnia,
  1495: finlandSouthernSavonia,
  1493: finlandTavastiaProper,
  1510: finlandUusimaa
};
