/// Access to known geographies in Greece and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'greece_cities.dart';

/// The 38 regions of `🇬🇷 Greece`
const Region greeceAchaeaRegionalUnit = Region(id: 2116, parentId: 85, longitude: 21.9522491, latitude: 38.1158729,
          name: "Achaea Regional Unit", type: null, stateCode: "13",
          cities: []);
const Region greeceAetoliaHypAcarnaniaRegionalUnit = Region(id: 2123, parentId: 85, longitude: 21.3798928, latitude: 38.7084386,
          name: "Aetolia-Acarnania Regional Unit", type: null, stateCode: "01",
          cities: []);
const Region greeceArcadiaPrefecture = Region(id: 2098, parentId: 85, longitude: 22.3337769, latitude: 37.5557825,
          name: "Arcadia Prefecture", type: null, stateCode: "12",
          cities: []);
const Region greeceArgolisRegionalUnit = Region(id: 2105, parentId: 85, longitude: 1.7976931348623157e+308, latitude: 1.7976931348623157e+308,
          name: "Argolis Regional Unit", type: null, stateCode: "11",
          cities: []);
const Region greeceAtticaRegion = Region(id: 2122, parentId: 85, longitude: 23.8584737, latitude: 38.0457568,
          name: "Attica Region", type: null, stateCode: "I",
          cities: [
            greeceAtticaRegionAcharnes,
            greeceAtticaRegionAegina,
            greeceAtticaRegionAfidnes,
            greeceAtticaRegionAghiosPanteleimon,
            greeceAtticaRegionAgiaMarina,
            greeceAtticaRegionAgiaParaskevi,
            greeceAtticaRegionAgiaVarvara,
            greeceAtticaRegionAgioiAnargyroi,
            greeceAtticaRegionAgiosDimitrios,
            greeceAtticaRegionAgiosDimitriosKropias,
            greeceAtticaRegionAgiosIoannisRentis,
            greeceAtticaRegionAgiosStefanos,
            greeceAtticaRegionAianteio,
            greeceAtticaRegionAigaleo,
            greeceAtticaRegionAlimos,
            greeceAtticaRegionAmpelakia,
            greeceAtticaRegionAnavyssos,
            greeceAtticaRegionAnoLiosia,
            greeceAtticaRegionAnoixi,
            greeceAtticaRegionAnthousa,
            greeceAtticaRegionArgithea,
            greeceAtticaRegionArgyroupoli,
            greeceAtticaRegionArtemida,
            greeceAtticaRegionAspropyrgos,
            greeceAtticaRegionAthens,
            greeceAtticaRegionAvlonas,
            greeceAtticaRegionAyioiApostoloi,
            greeceAtticaRegionChaidari,
            greeceAtticaRegionCholargos,
            greeceAtticaRegionDhafni,
            greeceAtticaRegionDhrafi,
            greeceAtticaRegionDioni,
            greeceAtticaRegionDionysos,
            greeceAtticaRegionDrapetsona,
            greeceAtticaRegionDrosia,
            greeceAtticaRegionEkali,
            greeceAtticaRegionElefsina,
            greeceAtticaRegionElliniko,
            greeceAtticaRegionErythres,
            greeceAtticaRegionFilothei,
            greeceAtticaRegionFyli,
            greeceAtticaRegionGalatas,
            greeceAtticaRegionGalatsi,
            greeceAtticaRegionGerakas,
            greeceAtticaRegionGlyfada,
            greeceAtticaRegionGrammatiko,
            greeceAtticaRegionIlion,
            greeceAtticaRegionIlioupoli,
            greeceAtticaRegionIrakleio,
            greeceAtticaRegionKaisariani,
            greeceAtticaRegionKalamos,
            greeceAtticaRegionKallithea,
            greeceAtticaRegionKalyviaThorikou,
            greeceAtticaRegionKamateron,
            greeceAtticaRegionKapandriti,
            greeceAtticaRegionKarellas,
            greeceAtticaRegionKatoSoulion,
            greeceAtticaRegionKeratea,
            greeceAtticaRegionKeratsini,
            greeceAtticaRegionKhalandrion,
            greeceAtticaRegionKhalkoutsion,
            greeceAtticaRegionKifisia,
            greeceAtticaRegionKineta,
            greeceAtticaRegionKipseli,
            greeceAtticaRegionKitsi,
            greeceAtticaRegionKoropi,
            greeceAtticaRegionKorydallos,
            greeceAtticaRegionKouvaras,
            greeceAtticaRegionKryoneri,
            greeceAtticaRegionKypseli,
            greeceAtticaRegionKythira,
            greeceAtticaRegionLavrio,
            greeceAtticaRegionLeondarion,
            greeceAtticaRegionLiminMesoyaias,
            greeceAtticaRegionLykovrysi,
            greeceAtticaRegionMagoula,
            greeceAtticaRegionMandra,
            greeceAtticaRegionMarathonas,
            greeceAtticaRegionMarkopoulo,
            greeceAtticaRegionMarkopouloOropou,
            greeceAtticaRegionMarousi,
            greeceAtticaRegionMegalochori,
            greeceAtticaRegionMegara,
            greeceAtticaRegionMelissia,
            greeceAtticaRegionMetamorfosi,
            greeceAtticaRegionMoskhaton,
            greeceAtticaRegionNeaChalkidona,
            greeceAtticaRegionNeaErythraia,
            greeceAtticaRegionNeaFiladelfeia,
            greeceAtticaRegionNeaIonia,
            greeceAtticaRegionNeaMakri,
            greeceAtticaRegionNeaPalatia,
            greeceAtticaRegionNeaPenteli,
            greeceAtticaRegionNeaPeramos,
            greeceAtticaRegionNeaSmyrni,
            greeceAtticaRegionNeoPsychiko,
            greeceAtticaRegionNeosVoutzas,
            greeceAtticaRegionNikaia,
            greeceAtticaRegionOropos,
            greeceAtticaRegionPaiania,
            greeceAtticaRegionPalaiaFokaia,
            greeceAtticaRegionPalaioFaliro,
            greeceAtticaRegionPallini,
            greeceAtticaRegionPapagou,
            greeceAtticaRegionPefki,
            greeceAtticaRegionPenteli,
            greeceAtticaRegionPerama,
            greeceAtticaRegionPeristeri,
            greeceAtticaRegionPetroupolis,
            greeceAtticaRegionPikermi,
            greeceAtticaRegionPiraeus,
            greeceAtticaRegionPolydendri,
            greeceAtticaRegionPoros,
            greeceAtticaRegionPsychiko,
            greeceAtticaRegionRafina,
            greeceAtticaRegionRodopoli,
            greeceAtticaRegionSalamina,
            greeceAtticaRegionSaronida,
            greeceAtticaRegionSelinia,
            greeceAtticaRegionSkalaOropou,
            greeceAtticaRegionSkarmagkas,
            greeceAtticaRegionSpata,
            greeceAtticaRegionSpetses,
            greeceAtticaRegionStamata,
            greeceAtticaRegionTavros,
            greeceAtticaRegionThrakomakedones,
            greeceAtticaRegionVari,
            greeceAtticaRegionVarnavas,
            greeceAtticaRegionVarybobi,
            greeceAtticaRegionVathy,
            greeceAtticaRegionVilia,
            greeceAtticaRegionVlychada,
            greeceAtticaRegionVoula,
            greeceAtticaRegionVouliagmeni,
            greeceAtticaRegionVrana,
            greeceAtticaRegionVrilissia,
            greeceAtticaRegionVyronas,
            greeceAtticaRegionYdra,
            greeceAtticaRegionYmittos,
            greeceAtticaRegionZefyri,
            greeceAtticaRegionZografos
          ]);
const Region greeceBoeotiaRegionalUnit = Region(id: 2126, parentId: 85, longitude: 23.0965064, latitude: 38.3663664,
          name: "Boeotia Regional Unit", type: null, stateCode: "03",
          cities: []);
const Region greeceCentralGreeceRegion = Region(id: 2128, parentId: 85, longitude: 22.7152131, latitude: 38.6043984,
          name: "Central Greece Region", type: null, stateCode: "H",
          cities: [
            greeceCentralGreeceRegionAfration,
            greeceCentralGreeceRegionAgiaTriada,
            greeceCentralGreeceRegionAgiosGeorgios,
            greeceCentralGreeceRegionAidipsos,
            greeceCentralGreeceRegionAkraifnia,
            greeceCentralGreeceRegionAliartos,
            greeceCentralGreeceRegionAliveri,
            greeceCentralGreeceRegionAmarynthos,
            greeceCentralGreeceRegionAmfikleia,
            greeceCentralGreeceRegionAmfissa,
            greeceCentralGreeceRegionAnthili,
            greeceCentralGreeceRegionAntikyra,
            greeceCentralGreeceRegionArachova,
            greeceCentralGreeceRegionArma,
            greeceCentralGreeceRegionAsopia,
            greeceCentralGreeceRegionAtalanti,
            greeceCentralGreeceRegionAyiosKonstandinos,
            greeceCentralGreeceRegionAyiosNikolaos,
            greeceCentralGreeceRegionAyiosThomas,
            greeceCentralGreeceRegionChaironeia,
            greeceCentralGreeceRegionChalkida,
            greeceCentralGreeceRegionDelphi,
            greeceCentralGreeceRegionDhrosia,
            greeceCentralGreeceRegionDilesi,
            greeceCentralGreeceRegionDistomo,
            greeceCentralGreeceRegionDomokos,
            greeceCentralGreeceRegionDomvraina,
            greeceCentralGreeceRegionElateia,
            greeceCentralGreeceRegionEretria,
            greeceCentralGreeceRegionFaros,
            greeceCentralGreeceRegionFilla,
            greeceCentralGreeceRegionGalaxidhion,
            greeceCentralGreeceRegionIstiaia,
            greeceCentralGreeceRegionItea,
            greeceCentralGreeceRegionKainouryion,
            greeceCentralGreeceRegionKamenaVourla,
            greeceCentralGreeceRegionKaparellion,
            greeceCentralGreeceRegionKarpenisi,
            greeceCentralGreeceRegionKarystos,
            greeceCentralGreeceRegionKastella,
            greeceCentralGreeceRegionKatoTithorea,
            greeceCentralGreeceRegionKerasochori,
            greeceCentralGreeceRegionKirra,
            greeceCentralGreeceRegionKymi,
            greeceCentralGreeceRegionKyriaki,
            greeceCentralGreeceRegionLamia,
            greeceCentralGreeceRegionLianokladhion,
            greeceCentralGreeceRegionLidoriki,
            greeceCentralGreeceRegionLimni,
            greeceCentralGreeceRegionLivadeia,
            greeceCentralGreeceRegionLivanates,
            greeceCentralGreeceRegionLoukisia,
            greeceCentralGreeceRegionLoutraAidhipsou,
            greeceCentralGreeceRegionMagoula,
            greeceCentralGreeceRegionMakrakomi,
            greeceCentralGreeceRegionMalakonta,
            greeceCentralGreeceRegionMalesina,
            greeceCentralGreeceRegionMantoudi,
            greeceCentralGreeceRegionMarmarion,
            greeceCentralGreeceRegionMartinon,
            greeceCentralGreeceRegionMolos,
            greeceCentralGreeceRegionMytikas,
            greeceCentralGreeceRegionNeaArtaki,
            greeceCentralGreeceRegionNeaLampsakos,
            greeceCentralGreeceRegionNeaStira,
            greeceCentralGreeceRegionNeonMonastirion,
            greeceCentralGreeceRegionNomosEvrytanias,
            greeceCentralGreeceRegionNomosFokidos,
            greeceCentralGreeceRegionOinofyta,
            greeceCentralGreeceRegionOmvriaki,
            greeceCentralGreeceRegionOrchomenos,
            greeceCentralGreeceRegionOreoi,
            greeceCentralGreeceRegionOxilithos,
            greeceCentralGreeceRegionParaliaAvlidhos,
            greeceCentralGreeceRegionPelasgia,
            greeceCentralGreeceRegionPlakaDilesi,
            greeceCentralGreeceRegionPolitika,
            greeceCentralGreeceRegionProkopi,
            greeceCentralGreeceRegionPsachna,
            greeceCentralGreeceRegionRodhitsa,
            greeceCentralGreeceRegionRovies,
            greeceCentralGreeceRegionSchimatari,
            greeceCentralGreeceRegionSkyros,
            greeceCentralGreeceRegionSpercheiada,
            greeceCentralGreeceRegionStavros,
            greeceCentralGreeceRegionSteiri,
            greeceCentralGreeceRegionStylida,
            greeceCentralGreeceRegionThespies,
            greeceCentralGreeceRegionThivai,
            greeceCentralGreeceRegionVagia,
            greeceCentralGreeceRegionVasilikon,
            greeceCentralGreeceRegionVathi,
            greeceCentralGreeceRegionYimnon
          ]);
const Region greeceCentralMacedonia = Region(id: 2125, parentId: 85, longitude: 23.1918021, latitude: 40.621173,
          name: "Central Macedonia", type: null, stateCode: "B",
          cities: [
            greeceCentralMacedoniaAdendro,
            greeceCentralMacedoniaAfytos,
            greeceCentralMacedoniaAgiaParaskevi,
            greeceCentralMacedoniaAgiaTriada,
            greeceCentralMacedoniaAgioPnevma,
            greeceCentralMacedoniaAgiosAthanasios,
            greeceCentralMacedoniaAgiosGeorgios,
            greeceCentralMacedoniaAgiosLoukas,
            greeceCentralMacedoniaAgiosNikolaos,
            greeceCentralMacedoniaAgiosPavlos,
            greeceCentralMacedoniaAgiosPetros,
            greeceCentralMacedoniaAgiosSpyridon,
            greeceCentralMacedoniaAgiosVasileios,
            greeceCentralMacedoniaAgkathia,
            greeceCentralMacedoniaAiginio,
            greeceCentralMacedoniaAkrolimni,
            greeceCentralMacedoniaAlexandreia,
            greeceCentralMacedoniaAlistrati,
            greeceCentralMacedoniaAmpeleies,
            greeceCentralMacedoniaAmpelokipoi,
            greeceCentralMacedoniaAnatoliko,
            greeceCentralMacedoniaAngelochori,
            greeceCentralMacedoniaApsalos,
            greeceCentralMacedoniaAravissos,
            greeceCentralMacedoniaAridaia,
            greeceCentralMacedoniaArnaia,
            greeceCentralMacedoniaArnissa,
            greeceCentralMacedoniaArsenio,
            greeceCentralMacedoniaAskos,
            greeceCentralMacedoniaAsprovalta,
            greeceCentralMacedoniaAssiros,
            greeceCentralMacedoniaAsvestochori,
            greeceCentralMacedoniaAthyra,
            greeceCentralMacedoniaAxioupoli,
            greeceCentralMacedoniaAxos,
            greeceCentralMacedoniaChalastra,
            greeceCentralMacedoniaChalkidona,
            greeceCentralMacedoniaCharopo,
            greeceCentralMacedoniaChortiatis,
            greeceCentralMacedoniaChryso,
            greeceCentralMacedoniaChrysochorafa,
            greeceCentralMacedoniaDiavata,
            greeceCentralMacedoniaDiavatos,
            greeceCentralMacedoniaDion,
            greeceCentralMacedoniaDraviskos,
            greeceCentralMacedoniaDrymos,
            greeceCentralMacedoniaEdessa,
            greeceCentralMacedoniaEfkarpia,
            greeceCentralMacedoniaEirinoupoli,
            greeceCentralMacedoniaEpanomi,
            greeceCentralMacedoniaEpiskopi,
            greeceCentralMacedoniaEvosmos,
            greeceCentralMacedoniaEvropos,
            greeceCentralMacedoniaExaplatanos,
            greeceCentralMacedoniaFiliro,
            greeceCentralMacedoniaGalatades,
            greeceCentralMacedoniaGalatista,
            greeceCentralMacedoniaGazoros,
            greeceCentralMacedoniaGefyra,
            greeceCentralMacedoniaGerakarou,
            greeceCentralMacedoniaGiannitsa,
            greeceCentralMacedoniaGoumenissa,
            greeceCentralMacedoniaIerissos,
            greeceCentralMacedoniaIrakleia,
            greeceCentralMacedoniaKalaDendra,
            greeceCentralMacedoniaKalamaria,
            greeceCentralMacedoniaKali,
            greeceCentralMacedoniaKallithea,
            greeceCentralMacedoniaKalochori,
            greeceCentralMacedoniaKalyvesPolygyrou,
            greeceCentralMacedoniaKalyvia,
            greeceCentralMacedoniaKampanis,
            greeceCentralMacedoniaKardia,
            greeceCentralMacedoniaKaritsa,
            greeceCentralMacedoniaKaryotissa,
            greeceCentralMacedoniaKassandreia,
            greeceCentralMacedoniaKaterini,
            greeceCentralMacedoniaKatoKamila,
            greeceCentralMacedoniaKatoLipochori,
            greeceCentralMacedoniaKatoMilia,
            greeceCentralMacedoniaKatoScholari,
            greeceCentralMacedoniaKavallari,
            greeceCentralMacedoniaKilkis,
            greeceCentralMacedoniaKitros,
            greeceCentralMacedoniaKleidi,
            greeceCentralMacedoniaKoimisi,
            greeceCentralMacedoniaKolchikon,
            greeceCentralMacedoniaKolindros,
            greeceCentralMacedoniaKontariotissa,
            greeceCentralMacedoniaKopanos,
            greeceCentralMacedoniaKorinos,
            greeceCentralMacedoniaKoryfi,
            greeceCentralMacedoniaKoufalia,
            greeceCentralMacedoniaKouloura,
            greeceCentralMacedoniaKrithia,
            greeceCentralMacedoniaKryaVrysi,
            greeceCentralMacedoniaKymina,
            greeceCentralMacedoniaLagkadas,
            greeceCentralMacedoniaLagyna,
            greeceCentralMacedoniaLakkoma,
            greeceCentralMacedoniaLefkonas,
            greeceCentralMacedoniaLeptokarya,
            greeceCentralMacedoniaLianovergi,
            greeceCentralMacedoniaLiti,
            greeceCentralMacedoniaLitochoro,
            greeceCentralMacedoniaLofos,
            greeceCentralMacedoniaLoutraki,
            greeceCentralMacedoniaLoutros,
            greeceCentralMacedoniaMakrochori,
            greeceCentralMacedoniaMakrygialos,
            greeceCentralMacedoniaMandalo,
            greeceCentralMacedoniaMarina,
            greeceCentralMacedoniaMavrothalassa,
            greeceCentralMacedoniaMavrovouni,
            greeceCentralMacedoniaMegaliPanagia,
            greeceCentralMacedoniaMeliki,
            greeceCentralMacedoniaMelissi,
            greeceCentralMacedoniaMelissochori,
            greeceCentralMacedoniaMenemeni,
            greeceCentralMacedoniaMesimeri,
            greeceCentralMacedoniaMikroMonastiri,
            greeceCentralMacedoniaMitrousi,
            greeceCentralMacedoniaNaousa,
            greeceCentralMacedoniaNeaApollonia,
            greeceCentralMacedoniaNeaEfesos,
            greeceCentralMacedoniaNeaFlogita,
            greeceCentralMacedoniaNeaFokaia,
            greeceCentralMacedoniaNeaKallikrateia,
            greeceCentralMacedoniaNeaMagnisia,
            greeceCentralMacedoniaNeaMalgara,
            greeceCentralMacedoniaNeaMesimvria,
            greeceCentralMacedoniaNeaMichaniona,
            greeceCentralMacedoniaNeaMoudhania,
            greeceCentralMacedoniaNeaPella,
            greeceCentralMacedoniaNeaPlagia,
            greeceCentralMacedoniaNeaPoteidaia,
            greeceCentralMacedoniaNeaPotidhaia,
            greeceCentralMacedoniaNeaRoda,
            greeceCentralMacedoniaNeaSanta,
            greeceCentralMacedoniaNeaTriglia,
            greeceCentralMacedoniaNeaVrasna,
            greeceCentralMacedoniaNeaZichni,
            greeceCentralMacedoniaNeapoli,
            greeceCentralMacedoniaNeoAgioneri,
            greeceCentralMacedoniaNeoPetritsi,
            greeceCentralMacedoniaNeoRysi,
            greeceCentralMacedoniaNeoSouli,
            greeceCentralMacedoniaNeochori,
            greeceCentralMacedoniaNeochorouda,
            greeceCentralMacedoniaNeoiEpivates,
            greeceCentralMacedoniaNeosMarmaras,
            greeceCentralMacedoniaNeosMylotopos,
            greeceCentralMacedoniaNeosSkopos,
            greeceCentralMacedoniaNigrita,
            greeceCentralMacedoniaNikiti,
            greeceCentralMacedoniaNisi,
            greeceCentralMacedoniaNomosChalkidikis,
            greeceCentralMacedoniaNomosPellis,
            greeceCentralMacedoniaNomosThessalonikis,
            greeceCentralMacedoniaOlynthos,
            greeceCentralMacedoniaOraiokastro,
            greeceCentralMacedoniaOrmylia,
            greeceCentralMacedoniaOuranoupolis,
            greeceCentralMacedoniaPalaifyto,
            greeceCentralMacedoniaPalaiochori,
            greeceCentralMacedoniaPalaiokomi,
            greeceCentralMacedoniaPanorama,
            greeceCentralMacedoniaParalia,
            greeceCentralMacedoniaPatrida,
            greeceCentralMacedoniaPefka,
            greeceCentralMacedoniaPefkochori,
            greeceCentralMacedoniaPella,
            greeceCentralMacedoniaPentalofos,
            greeceCentralMacedoniaPentaplatano,
            greeceCentralMacedoniaPeraia,
            greeceCentralMacedoniaPeristasi,
            greeceCentralMacedoniaPeristera,
            greeceCentralMacedoniaPlagiari,
            greeceCentralMacedoniaPlaty,
            greeceCentralMacedoniaPolichni,
            greeceCentralMacedoniaPolygyros,
            greeceCentralMacedoniaPolykarpi,
            greeceCentralMacedoniaPolykastro,
            greeceCentralMacedoniaPontismeno,
            greeceCentralMacedoniaPortaria,
            greeceCentralMacedoniaProchoma,
            greeceCentralMacedoniaProfitisIlias,
            greeceCentralMacedoniaPromachoi,
            greeceCentralMacedoniaProti,
            greeceCentralMacedoniaProvatas,
            greeceCentralMacedoniaPylaia,
            greeceCentralMacedoniaRitini,
            greeceCentralMacedoniaRizari,
            greeceCentralMacedoniaRizo,
            greeceCentralMacedoniaRizomata,
            greeceCentralMacedoniaRodolivos,
            greeceCentralMacedoniaSarti,
            greeceCentralMacedoniaSerres,
            greeceCentralMacedoniaSevastiana,
            greeceCentralMacedoniaSfendami,
            greeceCentralMacedoniaSidirokastro,
            greeceCentralMacedoniaSimantra,
            greeceCentralMacedoniaSindos,
            greeceCentralMacedoniaSkotoussa,
            greeceCentralMacedoniaSkoutari,
            greeceCentralMacedoniaSkydra,
            greeceCentralMacedoniaSochos,
            greeceCentralMacedoniaSosandra,
            greeceCentralMacedoniaSouroti,
            greeceCentralMacedoniaStathmosMourion,
            greeceCentralMacedoniaStavros,
            greeceCentralMacedoniaStavroupoli,
            greeceCentralMacedoniaStratonion,
            greeceCentralMacedoniaStrymoniko,
            greeceCentralMacedoniaSvoronos,
            greeceCentralMacedoniaSykia,
            greeceCentralMacedoniaSykies,
            greeceCentralMacedoniaTerpni,
            greeceCentralMacedoniaThermi,
            greeceCentralMacedoniaThessaloniki,
            greeceCentralMacedoniaTriandria,
            greeceCentralMacedoniaTrikala,
            greeceCentralMacedoniaTrilofos,
            greeceCentralMacedoniaValtero,
            greeceCentralMacedoniaVamvakofyto,
            greeceCentralMacedoniaVasilika,
            greeceCentralMacedoniaVathylakkos,
            greeceCentralMacedoniaVergina,
            greeceCentralMacedoniaVeroia,
            greeceCentralMacedoniaVrontou,
            greeceCentralMacedoniaXilopolis
          ]);
const Region greeceChaniaRegionalUnit = Region(id: 2115, parentId: 85, longitude: 24.0180367, latitude: 35.5138298,
          name: "Chania Regional Unit", type: null, stateCode: "94",
          cities: []);
const Region greeceCorfuPrefecture = Region(id: 2124, parentId: 85, longitude: 19.9223461, latitude: 39.6249838,
          name: "Corfu Prefecture", type: null, stateCode: "22",
          cities: [
            greeceCorfuPrefectureFarkadona,
            greeceCorfuPrefectureFiki,
            greeceCorfuPrefectureGomfoi,
            greeceCorfuPrefectureGrizano,
            greeceCorfuPrefectureKalampaka,
            greeceCorfuPrefectureKastraki,
            greeceCorfuPrefectureMegalaKalyvia,
            greeceCorfuPrefectureMegalochori,
            greeceCorfuPrefectureOichalia,
            greeceCorfuPrefecturePalaiomonastiro,
            greeceCorfuPrefecturePalaiopyrgos,
            greeceCorfuPrefecturePigi,
            greeceCorfuPrefecturePyli,
            greeceCorfuPrefecturePyrgetos,
            greeceCorfuPrefectureRizoma,
            greeceCorfuPrefectureTaxiarches,
            greeceCorfuPrefectureTrikala,
            greeceCorfuPrefectureVasiliki,
            greeceCorfuPrefectureZarkos
          ]);
const Region greeceCorinthiaRegionalUnit = Region(id: 2129, parentId: 85, longitude: 1.7976931348623157e+308, latitude: 1.7976931348623157e+308,
          name: "Corinthia Regional Unit", type: null, stateCode: "15",
          cities: []);
const Region greeceCreteRegion = Region(id: 2109, parentId: 85, longitude: 24.8092691, latitude: 35.240117,
          name: "Crete Region", type: null, stateCode: "M",
          cities: [
            greeceCreteRegionAgiaFoteini,
            greeceCreteRegionAgiaGalini,
            greeceCreteRegionAgiaMarina,
            greeceCreteRegionAgiaVarvara,
            greeceCreteRegionAgioiDeka,
            greeceCreteRegionAgiosNikolaos,
            greeceCreteRegionAnoArhanes,
            greeceCreteRegionAnogeia,
            greeceCreteRegionArkalochori,
            greeceCreteRegionAsimion,
            greeceCreteRegionAtsipopoulo,
            greeceCreteRegionChania,
            greeceCreteRegionChoraSfakion,
            greeceCreteRegionDaratsos,
            greeceCreteRegionElounda,
            greeceCreteRegionGalatas,
            greeceCreteRegionGazi,
            greeceCreteRegionGeorgioupolis,
            greeceCreteRegionGerani,
            greeceCreteRegionGergeri,
            greeceCreteRegionGournes,
            greeceCreteRegionGraLiyia,
            greeceCreteRegionIerapetra,
            greeceCreteRegionIrakleion,
            greeceCreteRegionKalyves,
            greeceCreteRegionKastelli,
            greeceCreteRegionKastri,
            greeceCreteRegionKatoAsitai,
            greeceCreteRegionKatoGouves,
            greeceCreteRegionKentri,
            greeceCreteRegionKissamos,
            greeceCreteRegionKokkiniChani,
            greeceCreteRegionKolympari,
            greeceCreteRegionKritsa,
            greeceCreteRegionKrouson,
            greeceCreteRegionLiminKhersonisou,
            greeceCreteRegionMalia,
            greeceCreteRegionMoires,
            greeceCreteRegionMokhos,
            greeceCreteRegionMournies,
            greeceCreteRegionMouzouras,
            greeceCreteRegionNeaAlikarnassos,
            greeceCreteRegionNeaAnatoli,
            greeceCreteRegionNeapoli,
            greeceCreteRegionNerokouros,
            greeceCreteRegionNomosIrakleiou,
            greeceCreteRegionNomosRethymnis,
            greeceCreteRegionPalaiochora,
            greeceCreteRegionPalekastro,
            greeceCreteRegionPanormos,
            greeceCreteRegionPerama,
            greeceCreteRegionPerivolia,
            greeceCreteRegionPithari,
            greeceCreteRegionProfitisIlias,
            greeceCreteRegionPyrgos,
            greeceCreteRegionRethymno,
            greeceCreteRegionSchismaEloundas,
            greeceCreteRegionSision,
            greeceCreteRegionSitia,
            greeceCreteRegionSkalanion,
            greeceCreteRegionSouda,
            greeceCreteRegionStalis,
            greeceCreteRegionThrapsanon,
            greeceCreteRegionTilisos,
            greeceCreteRegionTsikalaria,
            greeceCreteRegionTympaki,
            greeceCreteRegionVioliCharaki,
            greeceCreteRegionVryses,
            greeceCreteRegionZaros,
            greeceCreteRegionZoniana
          ]);
const Region greeceDramaRegionalUnit = Region(id: 2130, parentId: 85, longitude: 24.2390498, latitude: 41.2340023,
          name: "Drama Regional Unit", type: null, stateCode: "52",
          cities: []);
const Region greeceEastAtticaRegionalUnit = Region(id: 2120, parentId: 85, longitude: 23.8584737, latitude: 38.2054093,
          name: "East Attica Regional Unit", type: null, stateCode: "A2",
          cities: [
            greeceEastAtticaRegionalUnitAgiosAthanasios,
            greeceEastAtticaRegionalUnitAlexandroupoli,
            greeceEastAtticaRegionalUnitAmygdaleonas,
            greeceEastAtticaRegionalUnitAratos,
            greeceEastAtticaRegionalUnitArisvi,
            greeceEastAtticaRegionalUnitArriana,
            greeceEastAtticaRegionalUnitAvato,
            greeceEastAtticaRegionalUnitChoristi,
            greeceEastAtticaRegionalUnitChrysochori,
            greeceEastAtticaRegionalUnitChrysoupolis,
            greeceEastAtticaRegionalUnitDidymoteicho,
            greeceEastAtticaRegionalUnitDrama,
            greeceEastAtticaRegionalUnitEchinos,
            greeceEastAtticaRegionalUnitElaiochori,
            greeceEastAtticaRegionalUnitEleftheres,
            greeceEastAtticaRegionalUnitEleftheroupolis,
            greeceEastAtticaRegionalUnitEvlalo,
            greeceEastAtticaRegionalUnitFeres,
            greeceEastAtticaRegionalUnitFillyra,
            greeceEastAtticaRegionalUnitFotolivos,
            greeceEastAtticaRegionalUnitFtelia,
            greeceEastAtticaRegionalUnitGenissea,
            greeceEastAtticaRegionalUnitIasmos,
            greeceEastAtticaRegionalUnitIliokentima,
            greeceEastAtticaRegionalUnitKalampaki,
            greeceEastAtticaRegionalUnitKaliVrysi,
            greeceEastAtticaRegionalUnitKallifytos,
            greeceEastAtticaRegionalUnitKalosAgros,
            greeceEastAtticaRegionalUnitKamariotissa,
            greeceEastAtticaRegionalUnitKastanies,
            greeceEastAtticaRegionalUnitKatoNevrokopi,
            greeceEastAtticaRegionalUnitKavala,
            greeceEastAtticaRegionalUnitKavyli,
            greeceEastAtticaRegionalUnitKeramoti,
            greeceEastAtticaRegionalUnitKimmeria,
            greeceEastAtticaRegionalUnitKokkinochoma,
            greeceEastAtticaRegionalUnitKomotini,
            greeceEastAtticaRegionalUnitKrinides,
            greeceEastAtticaRegionalUnitKyprinos,
            greeceEastAtticaRegionalUnitKyria,
            greeceEastAtticaRegionalUnitLagos,
            greeceEastAtticaRegionalUnitLavara,
            greeceEastAtticaRegionalUnitLimenaria,
            greeceEastAtticaRegionalUnitLykeio,
            greeceEastAtticaRegionalUnitMikropolis,
            greeceEastAtticaRegionalUnitMyki,
            greeceEastAtticaRegionalUnitNeaIraklitsa,
            greeceEastAtticaRegionalUnitNeaKarvali,
            greeceEastAtticaRegionalUnitNeaKarya,
            greeceEastAtticaRegionalUnitNeaPeramos,
            greeceEastAtticaRegionalUnitNeaVyssa,
            greeceEastAtticaRegionalUnitNeochori,
            greeceEastAtticaRegionalUnitNikisiani,
            greeceEastAtticaRegionalUnitOrestiada,
            greeceEastAtticaRegionalUnitPachni,
            greeceEastAtticaRegionalUnitPalaioTsifliki,
            greeceEastAtticaRegionalUnitPalaiochori,
            greeceEastAtticaRegionalUnitParaliaOfryniou,
            greeceEastAtticaRegionalUnitParanesti,
            greeceEastAtticaRegionalUnitPeplos,
            greeceEastAtticaRegionalUnitPeteinos,
            greeceEastAtticaRegionalUnitPetrochori,
            greeceEastAtticaRegionalUnitPetroussa,
            greeceEastAtticaRegionalUnitPotamia,
            greeceEastAtticaRegionalUnitPrinos,
            greeceEastAtticaRegionalUnitProsotsani,
            greeceEastAtticaRegionalUnitRizia,
            greeceEastAtticaRegionalUnitSamothraki,
            greeceEastAtticaRegionalUnitSapes,
            greeceEastAtticaRegionalUnitSelero,
            greeceEastAtticaRegionalUnitSitagroi,
            greeceEastAtticaRegionalUnitSminthi,
            greeceEastAtticaRegionalUnitSoufli,
            greeceEastAtticaRegionalUnitThasos,
            greeceEastAtticaRegionalUnitTychero,
            greeceEastAtticaRegionalUnitVolakas,
            greeceEastAtticaRegionalUnitXanthi,
            greeceEastAtticaRegionalUnitXiropotamos,
            greeceEastAtticaRegionalUnitXylagani,
            greeceEastAtticaRegionalUnitZygos
          ]);
const Region greeceEastMacedoniaAandThrace = Region(id: 2117, parentId: 85, longitude: 24.8877191, latitude: 41.1295126,
          name: "East Macedonia and Thrace", type: null, stateCode: "A",
          cities: []);
const Region greeceEpirusRegion = Region(id: 2110, parentId: 85, longitude: 20.7642843, latitude: 39.5706413,
          name: "Epirus Region", type: null, stateCode: "D",
          cities: [
            greeceEpirusRegionAgiaKyriaki,
            greeceEpirusRegionAnatoli,
            greeceEpirusRegionAneza,
            greeceEpirusRegionAnoKalentini,
            greeceEpirusRegionArta,
            greeceEpirusRegionAsprangeloi,
            greeceEpirusRegionChalkiades,
            greeceEpirusRegionEksochi,
            greeceEpirusRegionEleousa,
            greeceEpirusRegionFiliates,
            greeceEpirusRegionFilippiada,
            greeceEpirusRegionGraikochori,
            greeceEpirusRegionGrammenitsa,
            greeceEpirusRegionIgoumenitsa,
            greeceEpirusRegionIoannina,
            greeceEpirusRegionKalamia,
            greeceEpirusRegionKalpaki,
            greeceEpirusRegionKanalaki,
            greeceEpirusRegionKardamitsia,
            greeceEpirusRegionKatsikas,
            greeceEpirusRegionKompoti,
            greeceEpirusRegionKonitsa,
            greeceEpirusRegionKostakioi,
            greeceEpirusRegionKoutselio,
            greeceEpirusRegionLouros,
            greeceEpirusRegionMetsovo,
            greeceEpirusRegionNeaSelefkeia,
            greeceEpirusRegionNeochori,
            greeceEpirusRegionNeochoropoulo,
            greeceEpirusRegionNeosOropos,
            greeceEpirusRegionNomosIoanninon,
            greeceEpirusRegionPappadates,
            greeceEpirusRegionParamythia,
            greeceEpirusRegionParapotamos,
            greeceEpirusRegionParga,
            greeceEpirusRegionPedini,
            greeceEpirusRegionPerama,
            greeceEpirusRegionPerdika,
            greeceEpirusRegionPeta,
            greeceEpirusRegionPlataria,
            greeceEpirusRegionPramanta,
            greeceEpirusRegionPreveza,
            greeceEpirusRegionRodotopi,
            greeceEpirusRegionStavraki,
            greeceEpirusRegionThesprotiko,
            greeceEpirusRegionTsiflikopoulo,
            greeceEpirusRegionVoulgareli,
            greeceEpirusRegionVounoplagia
          ]);
const Region greeceEuboea = Region(id: 2101, parentId: 85, longitude: 23.8584737, latitude: 38.5236036,
          name: "Euboea", type: null, stateCode: "04",
          cities: []);
const Region greeceGrevenaPrefecture = Region(id: 2102, parentId: 85, longitude: 21.4273299, latitude: 40.0837626,
          name: "Grevena Prefecture", type: null, stateCode: "51",
          cities: []);
const Region greeceImathiaRegionalUnit = Region(id: 2099, parentId: 85, longitude: 22.1430215, latitude: 40.6060067,
          name: "Imathia Regional Unit", type: null, stateCode: "53",
          cities: []);
const Region greeceIoanninaRegionalUnit = Region(id: 2113, parentId: 85, longitude: 20.8537466, latitude: 39.6650288,
          name: "Ioannina Regional Unit", type: null, stateCode: "33",
          cities: []);
const Region greeceIonianIslandsRegion = Region(id: 2131, parentId: 85, longitude: 21.3802372, latitude: 37.9694898,
          name: "Ionian Islands Region", type: null, stateCode: "F",
          cities: [
            greeceIonianIslandsRegionAcharavi,
            greeceIonianIslandsRegionAgiosGeorgis,
            greeceIonianIslandsRegionAgiosMatthaios,
            greeceIonianIslandsRegionAlepou,
            greeceIonianIslandsRegionAmbelokipoi,
            greeceIonianIslandsRegionArgostolion,
            greeceIonianIslandsRegionCorfu,
            greeceIonianIslandsRegionGaios,
            greeceIonianIslandsRegionGaitanion,
            greeceIonianIslandsRegionIthaki,
            greeceIonianIslandsRegionKanali,
            greeceIonianIslandsRegionKatastarion,
            greeceIonianIslandsRegionKontokali,
            greeceIonianIslandsRegionKynopiastes,
            greeceIonianIslandsRegionLefkada,
            greeceIonianIslandsRegionLefkimmi,
            greeceIonianIslandsRegionLithakia,
            greeceIonianIslandsRegionLixouri,
            greeceIonianIslandsRegionMouzaki,
            greeceIonianIslandsRegionNomosKerkyras,
            greeceIonianIslandsRegionNomosZakynthou,
            greeceIonianIslandsRegionPerama,
            greeceIonianIslandsRegionPerivoli,
            greeceIonianIslandsRegionPoros,
            greeceIonianIslandsRegionPotamos,
            greeceIonianIslandsRegionSami,
            greeceIonianIslandsRegionValsamata,
            greeceIonianIslandsRegionVanaton,
            greeceIonianIslandsRegionViros,
            greeceIonianIslandsRegionZakynthos
          ]);
const Region greeceKarditsaRegionalUnit = Region(id: 2095, parentId: 85, longitude: 21.9214049, latitude: 39.3640258,
          name: "Karditsa Regional Unit", type: null, stateCode: "41",
          cities: []);
const Region greeceKastoriaRegionalUnit = Region(id: 2100, parentId: 85, longitude: 21.2687171, latitude: 40.5192691,
          name: "Kastoria Regional Unit", type: null, stateCode: "56",
          cities: []);
const Region greeceKefaloniaPrefecture = Region(id: 2127, parentId: 85, longitude: 20.5692179, latitude: 38.1753675,
          name: "Kefalonia Prefecture", type: null, stateCode: "23",
          cities: [
            greeceKefaloniaPrefectureAgiaTriada,
            greeceKefaloniaPrefectureAgnantero,
            greeceKefaloniaPrefectureAnavra,
            greeceKefaloniaPrefectureAnthiro,
            greeceKefaloniaPrefectureArtesiano,
            greeceKefaloniaPrefectureItea,
            greeceKefaloniaPrefectureKallifoni,
            greeceKefaloniaPrefectureKallithiro,
            greeceKefaloniaPrefectureKarditsa,
            greeceKefaloniaPrefectureKarditsomagoula,
            greeceKefaloniaPrefectureKarpochori,
            greeceKefaloniaPrefectureMagoula,
            greeceKefaloniaPrefectureMakrychori,
            greeceKefaloniaPrefectureMavrommati,
            greeceKefaloniaPrefectureMitropoli,
            greeceKefaloniaPrefectureMorfovouni,
            greeceKefaloniaPrefectureMouzaki,
            greeceKefaloniaPrefecturePalamas,
            greeceKefaloniaPrefectureProastio,
            greeceKefaloniaPrefectureSofades
          ]);
const Region greeceKilkisRegionalUnit = Region(id: 2111, parentId: 85, longitude: 22.8753674, latitude: 40.9937071,
          name: "Kilkis Regional Unit", type: null, stateCode: "57",
          cities: []);
const Region greeceKozaniPrefecture = Region(id: 2112, parentId: 85, longitude: 21.7887737, latitude: 40.3005586,
          name: "Kozani Prefecture", type: null, stateCode: "58",
          cities: []);
const Region greeceLaconia = Region(id: 2106, parentId: 85, longitude: -71.4703509, latitude: 43.5278546,
          name: "Laconia", type: null, stateCode: "16",
          cities: []);
const Region greeceLarissaPrefecture = Region(id: 2132, parentId: 85, longitude: 22.4191254, latitude: 39.6390224,
          name: "Larissa Prefecture", type: null, stateCode: "42",
          cities: []);
const Region greeceLefkadaRegionalUnit = Region(id: 2104, parentId: 85, longitude: 20.7069108, latitude: 38.8333663,
          name: "Lefkada Regional Unit", type: null, stateCode: "24",
          cities: [
            greeceLefkadaRegionalUnitAgria,
            greeceLefkadaRegionalUnitAlliMeria,
            greeceLefkadaRegionalUnitAlmyros,
            greeceLefkadaRegionalUnitAnakasia,
            greeceLefkadaRegionalUnitAnoLekhonia,
            greeceLefkadaRegionalUnitArgalasti,
            greeceLefkadaRegionalUnitEvxinoupolis,
            greeceLefkadaRegionalUnitKanalia,
            greeceLefkadaRegionalUnitKatoLekhonia,
            greeceLefkadaRegionalUnitNeaAnchialos,
            greeceLefkadaRegionalUnitNeaIonia,
            greeceLefkadaRegionalUnitPatitirion,
            greeceLefkadaRegionalUnitPortaria,
            greeceLefkadaRegionalUnitPteleos,
            greeceLefkadaRegionalUnitRizomylos,
            greeceLefkadaRegionalUnitSkiathos,
            greeceLefkadaRegionalUnitSkopelos,
            greeceLefkadaRegionalUnitSourpi,
            greeceLefkadaRegionalUnitStefanovikeio,
            greeceLefkadaRegionalUnitTrikeri,
            greeceLefkadaRegionalUnitVelestino,
            greeceLefkadaRegionalUnitVolos,
            greeceLefkadaRegionalUnitZagora
          ]);
const Region greecePellaRegionalUnit = Region(id: 2107, parentId: 85, longitude: 22.1430215, latitude: 40.9148039,
          name: "Pella Regional Unit", type: null, stateCode: "59",
          cities: []);
const Region greecePeloponneseRegion = Region(id: 2119, parentId: 85, longitude: 22.37349, latitude: 37.5079472,
          name: "Peloponnese Region", type: null, stateCode: "J",
          cities: [
            greecePeloponneseRegionAgioiTheodoroi,
            greecePeloponneseRegionAgiosAndreas,
            greecePeloponneseRegionArfara,
            greecePeloponneseRegionArgos,
            greecePeloponneseRegionAria,
            greecePeloponneseRegionAris,
            greecePeloponneseRegionArkhaiaKorinthos,
            greecePeloponneseRegionAsini,
            greecePeloponneseRegionAsopos,
            greecePeloponneseRegionAssos,
            greecePeloponneseRegionAstros,
            greecePeloponneseRegionAthikia,
            greecePeloponneseRegionAyiaTrias,
            greecePeloponneseRegionAyiosAdhrianos,
            greecePeloponneseRegionAyiosVasilios,
            greecePeloponneseRegionChora,
            greecePeloponneseRegionDidyma,
            greecePeloponneseRegionDimitsana,
            greecePeloponneseRegionDrepanon,
            greecePeloponneseRegionErmioni,
            greecePeloponneseRegionExamilia,
            greecePeloponneseRegionFiliatra,
            greecePeloponneseRegionGargalianoi,
            greecePeloponneseRegionGefyra,
            greecePeloponneseRegionGeraki,
            greecePeloponneseRegionGytheio,
            greecePeloponneseRegionIsthmia,
            greecePeloponneseRegionKalamata,
            greecePeloponneseRegionKardamyli,
            greecePeloponneseRegionKaryes,
            greecePeloponneseRegionKatoDhiminio,
            greecePeloponneseRegionKatoGlykovrysi,
            greecePeloponneseRegionKhiliomodhi,
            greecePeloponneseRegionKiato,
            greecePeloponneseRegionKoilas,
            greecePeloponneseRegionKokkonion,
            greecePeloponneseRegionKopanaki,
            greecePeloponneseRegionKorinthos,
            greecePeloponneseRegionKoroni,
            greecePeloponneseRegionKoutsopodi,
            greecePeloponneseRegionKranidi,
            greecePeloponneseRegionKrokees,
            greecePeloponneseRegionKyparissia,
            greecePeloponneseRegionKyrasVrysi,
            greecePeloponneseRegionLangadhia,
            greecePeloponneseRegionLekhaio,
            greecePeloponneseRegionLeonidio,
            greecePeloponneseRegionLevidion,
            greecePeloponneseRegionLigourion,
            greecePeloponneseRegionLoutraOraiasElenis,
            greecePeloponneseRegionLoutraki,
            greecePeloponneseRegionMagoula,
            greecePeloponneseRegionMegalopoli,
            greecePeloponneseRegionMeligalas,
            greecePeloponneseRegionMessini,
            greecePeloponneseRegionMethoni,
            greecePeloponneseRegionMolaoi,
            greecePeloponneseRegionMoulki,
            greecePeloponneseRegionNafplio,
            greecePeloponneseRegionNeaKios,
            greecePeloponneseRegionNeaTirins,
            greecePeloponneseRegionNemea,
            greecePeloponneseRegionNomosArkadias,
            greecePeloponneseRegionPalaiaEpidavros,
            greecePeloponneseRegionParaliaVergas,
            greecePeloponneseRegionPasion,
            greecePeloponneseRegionPerachora,
            greecePeloponneseRegionPeriyiali,
            greecePeloponneseRegionPortoCheli,
            greecePeloponneseRegionPylos,
            greecePeloponneseRegionSikyon,
            greecePeloponneseRegionSkala,
            greecePeloponneseRegionSofikon,
            greecePeloponneseRegionSparti,
            greecePeloponneseRegionSperchogeia,
            greecePeloponneseRegionSykia,
            greecePeloponneseRegionThouria,
            greecePeloponneseRegionTolon,
            greecePeloponneseRegionTraganon,
            greecePeloponneseRegionTripoli,
            greecePeloponneseRegionVelo,
            greecePeloponneseRegionVlachiotis,
            greecePeloponneseRegionVlachopoulo,
            greecePeloponneseRegionVokhaiko,
            greecePeloponneseRegionVrakhati,
            greecePeloponneseRegionXylokastro,
            greecePeloponneseRegionZevgolateio
          ]);
const Region greecePhthiotisPrefecture = Region(id: 2114, parentId: 85, longitude: 22.3337769, latitude: 38.999785,
          name: "Phthiotis Prefecture", type: null, stateCode: "06",
          cities: []);
const Region greecePrevezaPrefecture = Region(id: 2103, parentId: 85, longitude: 20.7517155, latitude: 38.9592649,
          name: "Preveza Prefecture", type: null, stateCode: "34",
          cities: []);
const Region greeceSerresPrefecture = Region(id: 2121, parentId: 85, longitude: 23.5483819, latitude: 41.0863854,
          name: "Serres Prefecture", type: null, stateCode: "62",
          cities: []);
const Region greeceSouthAegean = Region(id: 2118, parentId: 85, longitude: 25.1489215, latitude: 37.0855302,
          name: "South Aegean", type: null, stateCode: "L",
          cities: [
            greeceSouthAegeanAdamas,
            greeceSouthAegeanAfantou,
            greeceSouthAegeanAgiaMarina,
            greeceSouthAegeanAmorgos,
            greeceSouthAegeanAnafi,
            greeceSouthAegeanAndros,
            greeceSouthAegeanAnoMera,
            greeceSouthAegeanAnoSyros,
            greeceSouthAegeanAntimacheia,
            greeceSouthAegeanAntiparos,
            greeceSouthAegeanArchangelos,
            greeceSouthAegeanAstypalaia,
            greeceSouthAegeanChalki,
            greeceSouthAegeanEmponas,
            greeceSouthAegeanEmporeio,
            greeceSouthAegeanErmoupolis,
            greeceSouthAegeanFaliraki,
            greeceSouthAegeanFilotion,
            greeceSouthAegeanFira,
            greeceSouthAegeanFolegandros,
            greeceSouthAegeanFry,
            greeceSouthAegeanIalysos,
            greeceSouthAegeanIos,
            greeceSouthAegeanKalymnos,
            greeceSouthAegeanKardamaina,
            greeceSouthAegeanKarpathos,
            greeceSouthAegeanKefalos,
            greeceSouthAegeanKimolos,
            greeceSouthAegeanKos,
            greeceSouthAegeanKremasti,
            greeceSouthAegeanKythnos,
            greeceSouthAegeanLakki,
            greeceSouthAegeanLardos,
            greeceSouthAegeanMandraki,
            greeceSouthAegeanMegaloChorio,
            greeceSouthAegeanMegisti,
            greeceSouthAegeanMesaria,
            greeceSouthAegeanMilos,
            greeceSouthAegeanMykonos,
            greeceSouthAegeanNaousa,
            greeceSouthAegeanNaxos,
            greeceSouthAegeanNomosKykladon,
            greeceSouthAegeanOia,
            greeceSouthAegeanOrnos,
            greeceSouthAegeanPanormos,
            greeceSouthAegeanParos,
            greeceSouthAegeanPatmos,
            greeceSouthAegeanPyli,
            greeceSouthAegeanRodos,
            greeceSouthAegeanSerifos,
            greeceSouthAegeanSkala,
            greeceSouthAegeanSymi,
            greeceSouthAegeanTinos,
            greeceSouthAegeanVari,
            greeceSouthAegeanZipari
          ]);
const Region greeceThessalonikiRegionalUnit = Region(id: 2097, parentId: 85, longitude: 22.9444191, latitude: 40.6400629,
          name: "Thessaloniki Regional Unit", type: null, stateCode: "54",
          cities: []);
const Region greeceWestGreeceRegion = Region(id: 2096, parentId: 85, longitude: 21.5706786, latitude: 38.5115496,
          name: "West Greece Region", type: null, stateCode: "G",
          cities: [
            greeceWestGreeceRegionAgrinio,
            greeceWestGreeceRegionAigio,
            greeceWestGreeceRegionAitoliko,
            greeceWestGreeceRegionAiyira,
            greeceWestGreeceRegionAkrata,
            greeceWestGreeceRegionAktaio,
            greeceWestGreeceRegionAlfeiousa,
            greeceWestGreeceRegionAmaliada,
            greeceWestGreeceRegionAmfilochia,
            greeceWestGreeceRegionAndravida,
            greeceWestGreeceRegionAngelokastro,
            greeceWestGreeceRegionAnoKastritsi,
            greeceWestGreeceRegionAntirrio,
            greeceWestGreeceRegionArchaiaOlympia,
            greeceWestGreeceRegionArchontochori,
            greeceWestGreeceRegionArkoudi,
            greeceWestGreeceRegionAstakos,
            greeceWestGreeceRegionAyiosKonstandinos,
            greeceWestGreeceRegionChalandritsa,
            greeceWestGreeceRegionChavari,
            greeceWestGreeceRegionDhokimion,
            greeceWestGreeceRegionEpitalio,
            greeceWestGreeceRegionFyteies,
            greeceWestGreeceRegionGalatas,
            greeceWestGreeceRegionGastouni,
            greeceWestGreeceRegionGavalou,
            greeceWestGreeceRegionGoumero,
            greeceWestGreeceRegionKainouryion,
            greeceWestGreeceRegionKalavryta,
            greeceWestGreeceRegionKamarai,
            greeceWestGreeceRegionKandila,
            greeceWestGreeceRegionKaratoula,
            greeceWestGreeceRegionKardamas,
            greeceWestGreeceRegionKatoAchaia,
            greeceWestGreeceRegionKatoMazaraki,
            greeceWestGreeceRegionKatochi,
            greeceWestGreeceRegionKatouna,
            greeceWestGreeceRegionKavasila,
            greeceWestGreeceRegionKrestena,
            greeceWestGreeceRegionKrikellos,
            greeceWestGreeceRegionKyllini,
            greeceWestGreeceRegionLalas,
            greeceWestGreeceRegionLapas,
            greeceWestGreeceRegionLechaina,
            greeceWestGreeceRegionLepenou,
            greeceWestGreeceRegionLimnokhorion,
            greeceWestGreeceRegionMakrisia,
            greeceWestGreeceRegionManolada,
            greeceWestGreeceRegionMataranga,
            greeceWestGreeceRegionMegaliKhora,
            greeceWestGreeceRegionMenidi,
            greeceWestGreeceRegionMesolongi,
            greeceWestGreeceRegionMindiloglion,
            greeceWestGreeceRegionMonastiraki,
            greeceWestGreeceRegionMyrsini,
            greeceWestGreeceRegionNafpaktos,
            greeceWestGreeceRegionNeaManolada,
            greeceWestGreeceRegionNeapolis,
            greeceWestGreeceRegionNeochori,
            greeceWestGreeceRegionNeochorion,
            greeceWestGreeceRegionNomosAchaias,
            greeceWestGreeceRegionNomosAitoliasKkaiAkarnanias,
            greeceWestGreeceRegionNomosIleias,
            greeceWestGreeceRegionOvria,
            greeceWestGreeceRegionPalairos,
            greeceWestGreeceRegionPanaitolion,
            greeceWestGreeceRegionPappadhatai,
            greeceWestGreeceRegionParalia,
            greeceWestGreeceRegionParavola,
            greeceWestGreeceRegionPatra,
            greeceWestGreeceRegionPelopi,
            greeceWestGreeceRegionPlatanos,
            greeceWestGreeceRegionPyrgos,
            greeceWestGreeceRegionRio,
            greeceWestGreeceRegionRododafni,
            greeceWestGreeceRegionRoyitika,
            greeceWestGreeceRegionSardinia,
            greeceWestGreeceRegionSavalia,
            greeceWestGreeceRegionStanos,
            greeceWestGreeceRegionSylivainiotika,
            greeceWestGreeceRegionSynoikismosChavariou,
            greeceWestGreeceRegionTemeni,
            greeceWestGreeceRegionThermo,
            greeceWestGreeceRegionTriandaiika,
            greeceWestGreeceRegionVarda,
            greeceWestGreeceRegionVartholomio,
            greeceWestGreeceRegionVarvasaina,
            greeceWestGreeceRegionVonitsa,
            greeceWestGreeceRegionVrachnaiika,
            greeceWestGreeceRegionZacharo
          ]);
const Region greeceWestMacedoniaRegion = Region(id: 2108, parentId: 85, longitude: 21.7903559, latitude: 40.3004058,
          name: "West Macedonia Region", type: null, stateCode: "C",
          cities: [
            greeceWestMacedoniaRegionAiani,
            greeceWestMacedoniaRegionAkrini,
            greeceWestMacedoniaRegionAmmochori,
            greeceWestMacedoniaRegionAmyntaio,
            greeceWestMacedoniaRegionAnarachi,
            greeceWestMacedoniaRegionAnoKomi,
            greeceWestMacedoniaRegionArgosOrestiko,
            greeceWestMacedoniaRegionChloi,
            greeceWestMacedoniaRegionDeskati,
            greeceWestMacedoniaRegionEmporio,
            greeceWestMacedoniaRegionEratyra,
            greeceWestMacedoniaRegionFilotas,
            greeceWestMacedoniaRegionFlorina,
            greeceWestMacedoniaRegionGalatini,
            greeceWestMacedoniaRegionGrevena,
            greeceWestMacedoniaRegionKastoria,
            greeceWestMacedoniaRegionKleitos,
            greeceWestMacedoniaRegionKoila,
            greeceWestMacedoniaRegionKomnina,
            greeceWestMacedoniaRegionKozani,
            greeceWestMacedoniaRegionKrokos,
            greeceWestMacedoniaRegionLaimos,
            greeceWestMacedoniaRegionLechovo,
            greeceWestMacedoniaRegionLivadero,
            greeceWestMacedoniaRegionManiakoi,
            greeceWestMacedoniaRegionMavrochori,
            greeceWestMacedoniaRegionMeliti,
            greeceWestMacedoniaRegionMesopotamia,
            greeceWestMacedoniaRegionNeaLava,
            greeceWestMacedoniaRegionNestorio,
            greeceWestMacedoniaRegionNomosKozanis,
            greeceWestMacedoniaRegionPlatanorevma,
            greeceWestMacedoniaRegionPtolemaida,
            greeceWestMacedoniaRegionServia,
            greeceWestMacedoniaRegionSiatista,
            greeceWestMacedoniaRegionTsotili,
            greeceWestMacedoniaRegionVelventos,
            greeceWestMacedoniaRegionXinoNero
          ]);

const greeceStates = <int, Region>{
    2116: greeceAchaeaRegionalUnit,
    2123: greeceAetoliaHypAcarnaniaRegionalUnit,
    2098: greeceArcadiaPrefecture,
    2105: greeceArgolisRegionalUnit,
    2122: greeceAtticaRegion,
    2126: greeceBoeotiaRegionalUnit,
    2128: greeceCentralGreeceRegion,
    2125: greeceCentralMacedonia,
    2115: greeceChaniaRegionalUnit,
    2124: greeceCorfuPrefecture,
    2129: greeceCorinthiaRegionalUnit,
    2109: greeceCreteRegion,
    2130: greeceDramaRegionalUnit,
    2120: greeceEastAtticaRegionalUnit,
    2117: greeceEastMacedoniaAandThrace,
    2110: greeceEpirusRegion,
    2101: greeceEuboea,
    2102: greeceGrevenaPrefecture,
    2099: greeceImathiaRegionalUnit,
    2113: greeceIoanninaRegionalUnit,
    2131: greeceIonianIslandsRegion,
    2095: greeceKarditsaRegionalUnit,
    2100: greeceKastoriaRegionalUnit,
    2127: greeceKefaloniaPrefecture,
    2111: greeceKilkisRegionalUnit,
    2112: greeceKozaniPrefecture,
    2106: greeceLaconia,
    2132: greeceLarissaPrefecture,
    2104: greeceLefkadaRegionalUnit,
    2107: greecePellaRegionalUnit,
    2119: greecePeloponneseRegion,
    2114: greecePhthiotisPrefecture,
    2103: greecePrevezaPrefecture,
    2121: greeceSerresPrefecture,
    2118: greeceSouthAegean,
    2097: greeceThessalonikiRegionalUnit,
    2096: greeceWestGreeceRegion,
    2108: greeceWestMacedoniaRegion
  };
