/// Access to known geographies in Guatemala and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'guatemala_cities.dart';

/// The 21 regions of `🇬🇹 Guatemala`
const Region guatemalaAltaVerapazDepartment = Region(id: 3671, parentId: 90, longitude: -90.1494988, latitude: 15.5942883,
          name: "Alta Verapaz Department", type: null, stateCode: "AV",
          cities: [
            guatemalaAltaVerapazDepartmentCahabon,
            guatemalaAltaVerapazDepartmentChahalGuatemala,
            guatemalaAltaVerapazDepartmentChisec,
            guatemalaAltaVerapazDepartmentCoban,
            guatemalaAltaVerapazDepartmentLaTinta,
            guatemalaAltaVerapazDepartmentLanquin,
            guatemalaAltaVerapazDepartmentPanzos,
            guatemalaAltaVerapazDepartmentSanCristobalVerapaz,
            guatemalaAltaVerapazDepartmentSanJuanChamelco,
            guatemalaAltaVerapazDepartmentSanPedroCarcha,
            guatemalaAltaVerapazDepartmentSantaCruzVerapaz,
            guatemalaAltaVerapazDepartmentSenahu,
            guatemalaAltaVerapazDepartmentTactic,
            guatemalaAltaVerapazDepartmentTamahu,
            guatemalaAltaVerapazDepartmentTucuru
          ]);
const Region guatemalaBajaVerapazDepartment = Region(id: 3674, parentId: 90, longitude: -90.3748354, latitude: 15.1255867,
          name: "Baja Verapaz Department", type: null, stateCode: "BV",
          cities: [
            guatemalaBajaVerapazDepartmentCubulco,
            guatemalaBajaVerapazDepartmentElChol,
            guatemalaBajaVerapazDepartmentGranados,
            guatemalaBajaVerapazDepartmentPurulha,
            guatemalaBajaVerapazDepartmentRabinal,
            guatemalaBajaVerapazDepartmentSalama,
            guatemalaBajaVerapazDepartmentSanJeronimo,
            guatemalaBajaVerapazDepartmentSanMiguelChicaj
          ]);
const Region guatemalaChimaltenangoDepartment = Region(id: 3675, parentId: 90, longitude: -90.9820668, latitude: 14.5634787,
          name: "Chimaltenango Department", type: null, stateCode: "CM",
          cities: [
            guatemalaChimaltenangoDepartmentAcatenango,
            guatemalaChimaltenangoDepartmentChimaltenango,
            guatemalaChimaltenangoDepartmentComalapa,
            guatemalaChimaltenangoDepartmentElTejar,
            guatemalaChimaltenangoDepartmentParramos,
            guatemalaChimaltenangoDepartmentPatzicia,
            guatemalaChimaltenangoDepartmentPatzun,
            guatemalaChimaltenangoDepartmentPochuta,
            guatemalaChimaltenangoDepartmentSanAndresItzapa,
            guatemalaChimaltenangoDepartmentSanJosePoaquil,
            guatemalaChimaltenangoDepartmentSanMartinJilotepeque,
            guatemalaChimaltenangoDepartmentSantaApolonia,
            guatemalaChimaltenangoDepartmentSantaCruzBalanya,
            guatemalaChimaltenangoDepartmentTecpanGuatemala,
            guatemalaChimaltenangoDepartmentYepocapa,
            guatemalaChimaltenangoDepartmentZaragoza
          ]);
const Region guatemalaChiquimulaDepartment = Region(id: 3666, parentId: 90, longitude: -89.4742177, latitude: 14.7514999,
          name: "Chiquimula Department", type: null, stateCode: "CQ",
          cities: [
            guatemalaChiquimulaDepartmentCamotan,
            guatemalaChiquimulaDepartmentChiquimula,
            guatemalaChiquimulaDepartmentConcepcionLasMinas,
            guatemalaChiquimulaDepartmentEsquipulas,
            guatemalaChiquimulaDepartmentIpala,
            guatemalaChiquimulaDepartmentJocotan,
            guatemalaChiquimulaDepartmentOlopa,
            guatemalaChiquimulaDepartmentQuezaltepeque,
            guatemalaChiquimulaDepartmentSanJacinto,
            guatemalaChiquimulaDepartmentSanJoseLaArada,
            guatemalaChiquimulaDepartmentSanJuanErmita
          ]);
const Region guatemalaElProgresoDepartment = Region(id: 3662, parentId: 90, longitude: -90.0746767, latitude: 14.9388732,
          name: "El Progreso Department", type: null, stateCode: "PR",
          cities: [
            guatemalaElProgresoDepartmentElJicaro,
            guatemalaElProgresoDepartmentGuastatoya,
            guatemalaElProgresoDepartmentMorazan,
            guatemalaElProgresoDepartmentSanAgustinAcasaguastlan,
            guatemalaElProgresoDepartmentSanAntonioLaPaz,
            guatemalaElProgresoDepartmentSanCristobalAcasaguastlan,
            guatemalaElProgresoDepartmentSanarate,
            guatemalaElProgresoDepartmentSansare
          ]);
const Region guatemalaEscuintlaDepartment = Region(id: 3677, parentId: 90, longitude: -90.9820668, latitude: 14.1910912,
          name: "Escuintla Department", type: null, stateCode: "ES",
          cities: [
            guatemalaEscuintlaDepartmentEscuintla,
            guatemalaEscuintlaDepartmentGuanagazapa,
            guatemalaEscuintlaDepartmentIztapa,
            guatemalaEscuintlaDepartmentLaDemocracia,
            guatemalaEscuintlaDepartmentLaGomera,
            guatemalaEscuintlaDepartmentMasagua,
            guatemalaEscuintlaDepartmentNuevaConcepcion,
            guatemalaEscuintlaDepartmentPalin,
            guatemalaEscuintlaDepartmentPuertoSanJose,
            guatemalaEscuintlaDepartmentSanVicentePacaya,
            guatemalaEscuintlaDepartmentSantaLuciaCotzumalguapa,
            guatemalaEscuintlaDepartmentSiquinala,
            guatemalaEscuintlaDepartmentTiquisate
          ]);
const Region guatemalaGuatemalaDepartment = Region(id: 3672, parentId: 90, longitude: -90.5257823, latitude: 14.5649401,
          name: "Guatemala Department", type: null, stateCode: "GU",
          cities: [
            guatemalaGuatemalaDepartmentAmatitlan,
            guatemalaGuatemalaDepartmentChinautla,
            guatemalaGuatemalaDepartmentChuarrancho,
            guatemalaGuatemalaDepartmentFraijanes,
            guatemalaGuatemalaDepartmentGuatemalaCity,
            guatemalaGuatemalaDepartmentMixco,
            guatemalaGuatemalaDepartmentPalencia,
            guatemalaGuatemalaDepartmentPetapa,
            guatemalaGuatemalaDepartmentSanJoseDdelGolfo,
            guatemalaGuatemalaDepartmentSanJosePinula,
            guatemalaGuatemalaDepartmentSanJuanSacatepequez,
            guatemalaGuatemalaDepartmentSanPedroAyampuc,
            guatemalaGuatemalaDepartmentSanPedroSacatepequez,
            guatemalaGuatemalaDepartmentSanRaimundo,
            guatemalaGuatemalaDepartmentSantaCatarinaPinula,
            guatemalaGuatemalaDepartmentVillaCanales,
            guatemalaGuatemalaDepartmentVillaNueva
          ]);
const Region guatemalaHuehuetenangoDepartment = Region(id: 3670, parentId: 90, longitude: -91.6760691, latitude: 15.5879914,
          name: "Huehuetenango Department", type: null, stateCode: "HU",
          cities: [
            guatemalaHuehuetenangoDepartmentAguacatan,
            guatemalaHuehuetenangoDepartmentBarillas,
            guatemalaHuehuetenangoDepartmentChiantla,
            guatemalaHuehuetenangoDepartmentColotenango,
            guatemalaHuehuetenangoDepartmentConcepcionHuista,
            guatemalaHuehuetenangoDepartmentCuilco,
            guatemalaHuehuetenangoDepartmentHuehuetenango,
            guatemalaHuehuetenangoDepartmentIxtahuacan,
            guatemalaHuehuetenangoDepartmentJacaltenango,
            guatemalaHuehuetenangoDepartmentLaLibertad,
            guatemalaHuehuetenangoDepartmentMalacatancito,
            guatemalaHuehuetenangoDepartmentNenton,
            guatemalaHuehuetenangoDepartmentSanAntonioHuista,
            guatemalaHuehuetenangoDepartmentSanGasparIxchil,
            guatemalaHuehuetenangoDepartmentSanJuanAtitan,
            guatemalaHuehuetenangoDepartmentSanJuanIxcoy,
            guatemalaHuehuetenangoDepartmentSanMateoIxtatan,
            guatemalaHuehuetenangoDepartmentSanMiguelAcatan,
            guatemalaHuehuetenangoDepartmentSanPedroNecta,
            guatemalaHuehuetenangoDepartmentSanRafaelLaIndependencia,
            guatemalaHuehuetenangoDepartmentSanRafaelPetzal,
            guatemalaHuehuetenangoDepartmentSanSebastianCoatan,
            guatemalaHuehuetenangoDepartmentSanSebastianHuehuetenango,
            guatemalaHuehuetenangoDepartmentSantaAnaHuista,
            guatemalaHuehuetenangoDepartmentSantaBarbara,
            guatemalaHuehuetenangoDepartmentSantaEulalia,
            guatemalaHuehuetenangoDepartmentSantiagoChimaltenango,
            guatemalaHuehuetenangoDepartmentSoloma,
            guatemalaHuehuetenangoDepartmentTectitan,
            guatemalaHuehuetenangoDepartmentTodosSantosCuchumatan
          ]);
const Region guatemalaIzabalDepartment = Region(id: 3659, parentId: 90, longitude: -88.864698, latitude: 15.4976517,
          name: "Izabal Department", type: null, stateCode: "IZ",
          cities: [
            guatemalaIzabalDepartmentElEstor,
            guatemalaIzabalDepartmentLivingston,
            guatemalaIzabalDepartmentLosAmates,
            guatemalaIzabalDepartmentMorales,
            guatemalaIzabalDepartmentMunicipioDdeMorales,
            guatemalaIzabalDepartmentMunicipioDdePuertoBarrios,
            guatemalaIzabalDepartmentPuertoBarrios
          ]);
const Region guatemalaJalapaDepartment = Region(id: 3658, parentId: 90, longitude: -89.9626799, latitude: 14.6121446,
          name: "Jalapa Department", type: null, stateCode: "JA",
          cities: [
            guatemalaJalapaDepartmentJalapa,
            guatemalaJalapaDepartmentMataquescuintla,
            guatemalaJalapaDepartmentMonjas,
            guatemalaJalapaDepartmentMunicipioDdeJalapa,
            guatemalaJalapaDepartmentMunicipioDdeMataquescuintla,
            guatemalaJalapaDepartmentSanLuisJilotepeque,
            guatemalaJalapaDepartmentSanManuelChaparron,
            guatemalaJalapaDepartmentSanPedroPinula
          ]);
const Region guatemalaJutiapaDepartment = Region(id: 3673, parentId: 90, longitude: -89.9253233, latitude: 14.1930802,
          name: "Jutiapa Department", type: null, stateCode: "JU",
          cities: [
            guatemalaJutiapaDepartmentAguaBlanca,
            guatemalaJutiapaDepartmentAsuncionMita,
            guatemalaJutiapaDepartmentAtescatempa,
            guatemalaJutiapaDepartmentComapa,
            guatemalaJutiapaDepartmentConguaco,
            guatemalaJutiapaDepartmentElAdelanto,
            guatemalaJutiapaDepartmentElProgreso,
            guatemalaJutiapaDepartmentJalpatagua,
            guatemalaJutiapaDepartmentJerez,
            guatemalaJutiapaDepartmentJutiapa,
            guatemalaJutiapaDepartmentMoyuta,
            guatemalaJutiapaDepartmentMunicipioDdeAsuncionMita,
            guatemalaJutiapaDepartmentPasaco,
            guatemalaJutiapaDepartmentQuesada,
            guatemalaJutiapaDepartmentSanJoseAcatempa,
            guatemalaJutiapaDepartmentSantaCatarinaMita,
            guatemalaJutiapaDepartmentYupiltepeque,
            guatemalaJutiapaDepartmentZapotitlan
          ]);
const Region guatemalaPetenDepartment = Region(id: 3669, parentId: 90, longitude: -90.2995785, latitude: 16.912033,
          name: "Petén Department", type: null, stateCode: "PE",
          cities: [
            guatemalaPetenDepartmentDolores,
            guatemalaPetenDepartmentFlores,
            guatemalaPetenDepartmentLaLibertad,
            guatemalaPetenDepartmentMelchorDdeMencos,
            guatemalaPetenDepartmentMunicipioDdeFlores,
            guatemalaPetenDepartmentMunicipioDdePoptun,
            guatemalaPetenDepartmentMunicipioDdeSanAndres,
            guatemalaPetenDepartmentMunicipioDdeSanBenito,
            guatemalaPetenDepartmentMunicipioDdeSanFrancisco,
            guatemalaPetenDepartmentMunicipioDdeSantaAna,
            guatemalaPetenDepartmentMunicipioDdeSayaxche,
            guatemalaPetenDepartmentPoptun,
            guatemalaPetenDepartmentSanAndres,
            guatemalaPetenDepartmentSanBenito,
            guatemalaPetenDepartmentSanFrancisco,
            guatemalaPetenDepartmentSanJose,
            guatemalaPetenDepartmentSanLuis,
            guatemalaPetenDepartmentSantaAna,
            guatemalaPetenDepartmentSayaxche
          ]);
const Region guatemalaQuetzaltenangoDepartment = Region(id: 3668, parentId: 90, longitude: -91.714958, latitude: 14.792433,
          name: "Quetzaltenango Department", type: null, stateCode: "QZ",
          cities: [
            guatemalaQuetzaltenangoDepartmentAlmolonga,
            guatemalaQuetzaltenangoDepartmentCabrican,
            guatemalaQuetzaltenangoDepartmentCajola,
            guatemalaQuetzaltenangoDepartmentCantel,
            guatemalaQuetzaltenangoDepartmentCoatepeque,
            guatemalaQuetzaltenangoDepartmentColomba,
            guatemalaQuetzaltenangoDepartmentConcepcionChiquirichapa,
            guatemalaQuetzaltenangoDepartmentElPalmar,
            guatemalaQuetzaltenangoDepartmentFloresCostaCuca,
            guatemalaQuetzaltenangoDepartmentGenova,
            guatemalaQuetzaltenangoDepartmentHuitan,
            guatemalaQuetzaltenangoDepartmentLaEsperanza,
            guatemalaQuetzaltenangoDepartmentMunicipioDdeAlmolonga,
            guatemalaQuetzaltenangoDepartmentMunicipioDdeCabrican,
            guatemalaQuetzaltenangoDepartmentMunicipioDdeCantel,
            guatemalaQuetzaltenangoDepartmentMunicipioDdeCoatepeque,
            guatemalaQuetzaltenangoDepartmentMunicipioDdeColomba,
            guatemalaQuetzaltenangoDepartmentMunicipioDdeConcepcionChiquirichapa,
            guatemalaQuetzaltenangoDepartmentMunicipioDdeFloresCostaCuca,
            guatemalaQuetzaltenangoDepartmentMunicipioDdeSanJuanOstuncalco,
            guatemalaQuetzaltenangoDepartmentOlintepeque,
            guatemalaQuetzaltenangoDepartmentOstuncalco,
            guatemalaQuetzaltenangoDepartmentPalestinaDdeLlosAltos,
            guatemalaQuetzaltenangoDepartmentQuetzaltenango,
            guatemalaQuetzaltenangoDepartmentSalcaja,
            guatemalaQuetzaltenangoDepartmentSamayac,
            guatemalaQuetzaltenangoDepartmentSanCarlosSija,
            guatemalaQuetzaltenangoDepartmentSanFranciscoLlaUnion,
            guatemalaQuetzaltenangoDepartmentSanMartinSacatepequez,
            guatemalaQuetzaltenangoDepartmentSanMateo,
            guatemalaQuetzaltenangoDepartmentSanMiguelSiguila,
            guatemalaQuetzaltenangoDepartmentSibilia,
            guatemalaQuetzaltenangoDepartmentZunil
          ]);
const Region guatemalaQuicheDepartment = Region(id: 3657, parentId: 90, longitude: -90.9820668, latitude: 15.4983808,
          name: "Quiché Department", type: null, stateCode: "QC",
          cities: [
            guatemalaQuicheDepartmentCanilla,
            guatemalaQuicheDepartmentChajul,
            guatemalaQuicheDepartmentChicaman,
            guatemalaQuicheDepartmentChiche,
            guatemalaQuicheDepartmentChichicastenango,
            guatemalaQuicheDepartmentChinique,
            guatemalaQuicheDepartmentCunen,
            guatemalaQuicheDepartmentJoyabaj,
            guatemalaQuicheDepartmentMunicipioDdeCanilla,
            guatemalaQuicheDepartmentMunicipioDdeChajul,
            guatemalaQuicheDepartmentMunicipioDdeChicaman,
            guatemalaQuicheDepartmentMunicipioDdeChiche,
            guatemalaQuicheDepartmentMunicipioDdeChichicastenango,
            guatemalaQuicheDepartmentMunicipioDdeChinique,
            guatemalaQuicheDepartmentMunicipioDdeCunen,
            guatemalaQuicheDepartmentMunicipioDdeIxcan,
            guatemalaQuicheDepartmentMunicipioDdeJoyabaj,
            guatemalaQuicheDepartmentMunicipioDdePachalum,
            guatemalaQuicheDepartmentMunicipioDdePatzite,
            guatemalaQuicheDepartmentMunicipioDdeSanAndresSajcabaja,
            guatemalaQuicheDepartmentMunicipioDdeSanAntonioIlotenango,
            guatemalaQuicheDepartmentMunicipioDdeSanJuanCotzal,
            guatemalaQuicheDepartmentMunicipioDdeSanPedroJocopilas,
            guatemalaQuicheDepartmentMunicipioDdeUspantan,
            guatemalaQuicheDepartmentMunicipioDdeZacualpa,
            guatemalaQuicheDepartmentNebaj,
            guatemalaQuicheDepartmentPachalum,
            guatemalaQuicheDepartmentPatzite,
            guatemalaQuicheDepartmentPlayaGrande,
            guatemalaQuicheDepartmentSacapulas,
            guatemalaQuicheDepartmentSanAndresSajcabaja,
            guatemalaQuicheDepartmentSanAntonioIlotenango,
            guatemalaQuicheDepartmentSanBartolomeJocotenango,
            guatemalaQuicheDepartmentSanJuanCotzal,
            guatemalaQuicheDepartmentSanLuisIxcan,
            guatemalaQuicheDepartmentSanPedroJocopilas,
            guatemalaQuicheDepartmentSantaCruzDdelQuiche,
            guatemalaQuicheDepartmentUspantan,
            guatemalaQuicheDepartmentZacualpa
          ]);
const Region guatemalaRetalhuleuDepartment = Region(id: 3664, parentId: 90, longitude: -91.685788, latitude: 14.5245485,
          name: "Retalhuleu Department", type: null, stateCode: "RE",
          cities: [
            guatemalaRetalhuleuDepartmentChamperico,
            guatemalaRetalhuleuDepartmentElAsintal,
            guatemalaRetalhuleuDepartmentMunicipioDdeSanFelipe,
            guatemalaRetalhuleuDepartmentNuevoSanCarlos,
            guatemalaRetalhuleuDepartmentRetalhuleu,
            guatemalaRetalhuleuDepartmentSanAndresVillaSeca,
            guatemalaRetalhuleuDepartmentSanFelipe,
            guatemalaRetalhuleuDepartmentSanMartinZapotitlan,
            guatemalaRetalhuleuDepartmentSanSebastian,
            guatemalaRetalhuleuDepartmentSantaCruzMulua
          ]);
const Region guatemalaSacatepequezDepartment = Region(id: 3676, parentId: 90, longitude: -90.7152749, latitude: 14.5178379,
          name: "Sacatepéquez Department", type: null, stateCode: "SA",
          cities: [
            guatemalaSacatepequezDepartmentAlotenango,
            guatemalaSacatepequezDepartmentAntiguaGuatemala,
            guatemalaSacatepequezDepartmentCiudadVieja,
            guatemalaSacatepequezDepartmentJocotenango,
            guatemalaSacatepequezDepartmentMagdalenaMilpasAltas,
            guatemalaSacatepequezDepartmentMunicipioDdeAlotenango,
            guatemalaSacatepequezDepartmentMunicipioDdeAntiguaGuatemala,
            guatemalaSacatepequezDepartmentMunicipioDdeCiudadVieja,
            guatemalaSacatepequezDepartmentMunicipioDdeJocotenango,
            guatemalaSacatepequezDepartmentMunicipioDdeMagdalenaMilpasAltas,
            guatemalaSacatepequezDepartmentMunicipioDdeSantaLuciaMilpasAltas,
            guatemalaSacatepequezDepartmentMunicipioDdeSantaMariaDdeJesus,
            guatemalaSacatepequezDepartmentPastores,
            guatemalaSacatepequezDepartmentSanAntonioAguasCalientes,
            guatemalaSacatepequezDepartmentSanBartolomeMilpasAltas,
            guatemalaSacatepequezDepartmentSanLucasSacatepequez,
            guatemalaSacatepequezDepartmentSanMiguelDuenas,
            guatemalaSacatepequezDepartmentSantaCatarinaBarahona,
            guatemalaSacatepequezDepartmentSantaLuciaMilpasAltas,
            guatemalaSacatepequezDepartmentSantaMariaDdeJesus,
            guatemalaSacatepequezDepartmentSantiagoSacatepequez,
            guatemalaSacatepequezDepartmentSantoDomingoXenacoj,
            guatemalaSacatepequezDepartmentSumpango
          ]);
const Region guatemalaSanMarcosDepartment = Region(id: 3667, parentId: 90, longitude: -91.9099238, latitude: 14.9309569,
          name: "San Marcos Department", type: null, stateCode: "SM",
          cities: [
            guatemalaSanMarcosDepartmentCatarina,
            guatemalaSanMarcosDepartmentCiudadTecunUman,
            guatemalaSanMarcosDepartmentComitancillo,
            guatemalaSanMarcosDepartmentConcepcionTutuapa,
            guatemalaSanMarcosDepartmentElQuetzal,
            guatemalaSanMarcosDepartmentElRodeo,
            guatemalaSanMarcosDepartmentElTumbador,
            guatemalaSanMarcosDepartmentEsquipulasPaloGordo,
            guatemalaSanMarcosDepartmentIxchiguan,
            guatemalaSanMarcosDepartmentLaReforma,
            guatemalaSanMarcosDepartmentMalacatan,
            guatemalaSanMarcosDepartmentMunicipioDdeConcepcionTutuapa,
            guatemalaSanMarcosDepartmentMunicipioDdeMalacatan,
            guatemalaSanMarcosDepartmentMunicipioDdeSipacapa,
            guatemalaSanMarcosDepartmentMunicipioDdeTejutla,
            guatemalaSanMarcosDepartmentNuevoProgreso,
            guatemalaSanMarcosDepartmentOcos,
            guatemalaSanMarcosDepartmentPajapita,
            guatemalaSanMarcosDepartmentRioBlanco,
            guatemalaSanMarcosDepartmentSanAntonioSacatepequez,
            guatemalaSanMarcosDepartmentSanCristobalCucho,
            guatemalaSanMarcosDepartmentSanJoseOjetenam,
            guatemalaSanMarcosDepartmentSanJoseOjetenan,
            guatemalaSanMarcosDepartmentSanLorenzo,
            guatemalaSanMarcosDepartmentSanMarcos,
            guatemalaSanMarcosDepartmentSanMiguelIxtahuacan,
            guatemalaSanMarcosDepartmentSanPablo,
            guatemalaSanMarcosDepartmentSanPedroSacatepequez,
            guatemalaSanMarcosDepartmentSanRafaelPieDdeLlaCuesta,
            guatemalaSanMarcosDepartmentSibinal,
            guatemalaSanMarcosDepartmentSipacapa,
            guatemalaSanMarcosDepartmentTacana,
            guatemalaSanMarcosDepartmentTajumulco,
            guatemalaSanMarcosDepartmentTejutla
          ]);
const Region guatemalaSantaRosaDepartment = Region(id: 3665, parentId: 90, longitude: -122.7037543, latitude: 38.4405759,
          name: "Santa Rosa Department", type: null, stateCode: "SR",
          cities: [
            guatemalaSantaRosaDepartmentBarberena,
            guatemalaSantaRosaDepartmentCasillas,
            guatemalaSantaRosaDepartmentChiquimulilla,
            guatemalaSantaRosaDepartmentCuilapa,
            guatemalaSantaRosaDepartmentGuazacapan,
            guatemalaSantaRosaDepartmentMunicipioDdeCasillas,
            guatemalaSantaRosaDepartmentMunicipioDdeChiquimulilla,
            guatemalaSantaRosaDepartmentMunicipioDdeGuazacapan,
            guatemalaSantaRosaDepartmentNuevaSantaRosa,
            guatemalaSantaRosaDepartmentOratorio,
            guatemalaSantaRosaDepartmentPuebloNuevoVinas,
            guatemalaSantaRosaDepartmentSanJuanTecuaco,
            guatemalaSantaRosaDepartmentSanRafaelLasFlores,
            guatemalaSantaRosaDepartmentSantaCruzNaranjo,
            guatemalaSantaRosaDepartmentSantaMariaIxhuatan,
            guatemalaSantaRosaDepartmentSantaRosaDdeLima,
            guatemalaSantaRosaDepartmentTaxisco
          ]);
const Region guatemalaSololaDepartment = Region(id: 3661, parentId: 90, longitude: -91.2891036, latitude: 14.748523,
          name: "Sololá Department", type: null, stateCode: "SO",
          cities: [
            guatemalaSololaDepartmentConcepcion,
            guatemalaSololaDepartmentMunicipioDdeNahuala,
            guatemalaSololaDepartmentMunicipioDdePanajachel,
            guatemalaSololaDepartmentMunicipioDdeSantaCatarinaPalopo,
            guatemalaSololaDepartmentMunicipioDdeSantaCruzLaLaguna,
            guatemalaSololaDepartmentNahuala,
            guatemalaSololaDepartmentPanajachel,
            guatemalaSololaDepartmentSanAndresSemetabaj,
            guatemalaSololaDepartmentSanAntonioPalopo,
            guatemalaSololaDepartmentSanJoseChacaya,
            guatemalaSololaDepartmentSanJuanLaLaguna,
            guatemalaSololaDepartmentSanLucasToliman,
            guatemalaSololaDepartmentSanMarcosLaLaguna,
            guatemalaSololaDepartmentSanPabloLaLaguna,
            guatemalaSololaDepartmentSanPedroLaLaguna,
            guatemalaSololaDepartmentSantaCatarinaIxtahuacan,
            guatemalaSololaDepartmentSantaCatarinaPalopo,
            guatemalaSololaDepartmentSantaClaraLaLaguna,
            guatemalaSololaDepartmentSantaCruzLaLaguna,
            guatemalaSololaDepartmentSantaLuciaUtatlan,
            guatemalaSololaDepartmentSantaMariaVisitacion,
            guatemalaSololaDepartmentSantiagoAtitlan,
            guatemalaSololaDepartmentSolola
          ]);
const Region guatemalaSuchitepequezDepartment = Region(id: 3660, parentId: 90, longitude: -91.4048249, latitude: 14.4215982,
          name: "Suchitepéquez Department", type: null, stateCode: "SU",
          cities: [
            guatemalaSuchitepequezDepartmentChicacao,
            guatemalaSuchitepequezDepartmentCuyotenango,
            guatemalaSuchitepequezDepartmentMazatenango,
            guatemalaSuchitepequezDepartmentMunicipioDdeSanAntonioSuchitepequez,
            guatemalaSuchitepequezDepartmentMunicipioDdeSanMiguelPanan,
            guatemalaSuchitepequezDepartmentMunicipioDdeSantaBarbara,
            guatemalaSuchitepequezDepartmentPatulul,
            guatemalaSuchitepequezDepartmentPuebloNuevo,
            guatemalaSuchitepequezDepartmentRioBravo,
            guatemalaSuchitepequezDepartmentSanAntonioSuchitepequez,
            guatemalaSuchitepequezDepartmentSanBernardino,
            guatemalaSuchitepequezDepartmentSanFranciscoZapotitlan,
            guatemalaSuchitepequezDepartmentSanGabriel,
            guatemalaSuchitepequezDepartmentSanJoseElIdolo,
            guatemalaSuchitepequezDepartmentSanJuanBautista,
            guatemalaSuchitepequezDepartmentSanLorenzo,
            guatemalaSuchitepequezDepartmentSanMiguelPanan,
            guatemalaSuchitepequezDepartmentSanPabloJocopilas,
            guatemalaSuchitepequezDepartmentSantaBarbara,
            guatemalaSuchitepequezDepartmentSantoDomingoSuchitepequez,
            guatemalaSuchitepequezDepartmentSantoTomasLaUnion,
            guatemalaSuchitepequezDepartmentZunilito
          ]);
const Region guatemalaTotonicapanDepartment = Region(id: 3663, parentId: 90, longitude: -91.3613923, latitude: 14.9173402,
          name: "Totonicapán Department", type: null, stateCode: "TO",
          cities: [
            guatemalaTotonicapanDepartmentMomostenango,
            guatemalaTotonicapanDepartmentMunicipioDdeMomostenango,
            guatemalaTotonicapanDepartmentMunicipioDdeSantaMariaChiquimula,
            guatemalaTotonicapanDepartmentMunicipioDdeTotonicapan,
            guatemalaTotonicapanDepartmentSanAndresXecul,
            guatemalaTotonicapanDepartmentSanBartolo,
            guatemalaTotonicapanDepartmentSanCristobalTotonicapan,
            guatemalaTotonicapanDepartmentSanFranciscoElAlto,
            guatemalaTotonicapanDepartmentSantaLuciaLaReforma,
            guatemalaTotonicapanDepartmentSantaMariaChiquimula,
            guatemalaTotonicapanDepartmentTotonicapan
          ]);

const guatemalaStates = <int, Region>{
    3671: guatemalaAltaVerapazDepartment,
    3674: guatemalaBajaVerapazDepartment,
    3675: guatemalaChimaltenangoDepartment,
    3666: guatemalaChiquimulaDepartment,
    3662: guatemalaElProgresoDepartment,
    3677: guatemalaEscuintlaDepartment,
    3672: guatemalaGuatemalaDepartment,
    3670: guatemalaHuehuetenangoDepartment,
    3659: guatemalaIzabalDepartment,
    3658: guatemalaJalapaDepartment,
    3673: guatemalaJutiapaDepartment,
    3669: guatemalaPetenDepartment,
    3668: guatemalaQuetzaltenangoDepartment,
    3657: guatemalaQuicheDepartment,
    3664: guatemalaRetalhuleuDepartment,
    3676: guatemalaSacatepequezDepartment,
    3667: guatemalaSanMarcosDepartment,
    3665: guatemalaSantaRosaDepartment,
    3661: guatemalaSololaDepartment,
    3660: guatemalaSuchitepequezDepartment,
    3663: guatemalaTotonicapanDepartment
  };
