/// Access to known geographies in `Honduras` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'honduras_cities.dart';

/// The `Atlántida Department` region in `Honduras`
const Region hondurasAtlantidaDepartment = Region(
  id: 4047,
  parentId: 97,
  longitude: -87.1422895,
  latitude: 15.6696283,
  name: "Atlántida Department",
  type: null,
  stateCode: "AT",
  cities: [
    atlantidaDepartmentArizonaCity,
    atlantidaDepartmentAtenasDeSanCristobalCity,
    atlantidaDepartmentCorozalCity,
    atlantidaDepartmentElPinoCity,
    atlantidaDepartmentElPorvenirCity,
    atlantidaDepartmentElTriunfoDeLaCruzCity,
    atlantidaDepartmentEspartaCity,
    atlantidaDepartmentJutiapaCity,
    atlantidaDepartmentLaCeibaCity,
    atlantidaDepartmentLaMasicaCity,
    atlantidaDepartmentLaUnionCity,
    atlantidaDepartmentMezapaCity,
    atlantidaDepartmentNuevaArmeniaCity,
    atlantidaDepartmentSamboCreekCity,
    atlantidaDepartmentSanAntonioCity,
    atlantidaDepartmentSanFranciscoCity,
    atlantidaDepartmentSanJuanPuebloCity,
    atlantidaDepartmentSantaAnaCity,
    atlantidaDepartmentTelaCity,
    atlantidaDepartmentTornabeCity
  ]);

/// The `Bay Islands Department` region in `Honduras`
const Region hondurasBayIslandsDepartment = Region(
  id: 4045,
  parentId: 97,
  longitude: -85.8793252,
  latitude: 16.4826614,
  name: "Bay Islands Department",
  type: null,
  stateCode: "IB",
  cities: [
    bayIslandsDepartmentCoxenHoleCity,
    bayIslandsDepartmentFrenchHarborCity,
    bayIslandsDepartmentGuanajaCity,
    bayIslandsDepartmentJoseSantosGuardiolaCity,
    bayIslandsDepartmentRoatanCity,
    bayIslandsDepartmentSandyBayCity,
    bayIslandsDepartmentSavannahBightCity,
    bayIslandsDepartmentUtilaCity
  ]);

/// The `Choluteca Department` region in `Honduras`
const Region hondurasCholutecaDepartment = Region(
  id: 4041,
  parentId: 97,
  longitude: -87.1422895,
  latitude: 13.2504325,
  name: "Choluteca Department",
  type: null,
  stateCode: "CH",
  cities: [
    cholutecaDepartmentApacilaguaCity,
    cholutecaDepartmentCholutecaCity,
    cholutecaDepartmentCiudadCholutecaCity,
    cholutecaDepartmentConcepcionDeMariaCity,
    cholutecaDepartmentCorpusCity,
    cholutecaDepartmentDuyureCity,
    cholutecaDepartmentElCorpusCity,
    cholutecaDepartmentElObrajeCity,
    cholutecaDepartmentElPuenteCity,
    cholutecaDepartmentElTriunfoCity,
    cholutecaDepartmentLosLlanitosCity,
    cholutecaDepartmentMarcoviaCity,
    cholutecaDepartmentMonjarasCity,
    cholutecaDepartmentMorolicaCity,
    cholutecaDepartmentNamasigueCity,
    cholutecaDepartmentOrocuinaCity,
    cholutecaDepartmentPespireCity,
    cholutecaDepartmentSanAntonioDeFloresCity,
    cholutecaDepartmentSanIsidroCity,
    cholutecaDepartmentSanJeronimoCity,
    cholutecaDepartmentSanJoseCity,
    cholutecaDepartmentSanJoseDeLasConchasCity,
    cholutecaDepartmentSanMarcosDeColonCity,
    cholutecaDepartmentSantaAnaDeYusguareCity,
    cholutecaDepartmentSantaCruzCity
  ]);

/// The `Colón Department` region in `Honduras`
const Region hondurasColonDepartment = Region(
  id: 4051,
  parentId: 97,
  longitude: -85.520024,
  latitude: 15.6425965,
  name: "Colón Department",
  type: null,
  stateCode: "CL",
  cities: [
    colonDepartmentBalfateCity,
    colonDepartmentBonitoOrientalCity,
    colonDepartmentCorocitoCity,
    colonDepartmentCusunaCity,
    colonDepartmentElixirCity,
    colonDepartmentFranciaCity,
    colonDepartmentIrionaCity,
    colonDepartmentJericoCity,
    colonDepartmentLaBreaCity,
    colonDepartmentLaEsperanzaCity,
    colonDepartmentLimonCity,
    colonDepartmentMunicipioDeSabaCity,
    colonDepartmentPrietaCity,
    colonDepartmentPuertoCastillaCity,
    colonDepartmentPuntaPiedraCity,
    colonDepartmentQuebradaDeArenaCity,
    colonDepartmentRioEstebanCity,
    colonDepartmentSabaCity,
    colonDepartmentSalamaCity,
    colonDepartmentSantaFeCity,
    colonDepartmentSantaRosaDeAguanCity,
    colonDepartmentSonagueraCity,
    colonDepartmentTaujicaCity,
    colonDepartmentTocoaCity,
    colonDepartmentTrujilloCity,
    colonDepartmentZamoraCity
  ]);

/// The `Comayagua Department` region in `Honduras`
const Region hondurasComayaguaDepartment = Region(
  id: 4042,
  parentId: 97,
  longitude: -87.6186379,
  latitude: 14.5534828,
  name: "Comayagua Department",
  type: null,
  stateCode: "CM",
  cities: [
    comayaguaDepartmentAguasDelPadreCity,
    comayaguaDepartmentAjuteriqueCity,
    comayaguaDepartmentCerroBlancoCity,
    comayaguaDepartmentComayaguaCity,
    comayaguaDepartmentConcepcionDeGuasistaguaCity,
    comayaguaDepartmentElAguaDulcitaCity,
    comayaguaDepartmentElPorvenirCity,
    comayaguaDepartmentElRanchoCity,
    comayaguaDepartmentElRinconCity,
    comayaguaDepartmentElRosarioCity,
    comayaguaDepartmentElSauceCity,
    comayaguaDepartmentElSocorroCity,
    comayaguaDepartmentEsquiasCity,
    comayaguaDepartmentFloresCity,
    comayaguaDepartmentHumuyaCity,
    comayaguaDepartmentJamaltecaCity,
    comayaguaDepartmentLaLibertadCity,
    comayaguaDepartmentLaTrinidadCity,
    comayaguaDepartmentLamaniCity,
    comayaguaDepartmentLasLajasCity,
    comayaguaDepartmentLejamaniCity,
    comayaguaDepartmentMeambarCity,
    comayaguaDepartmentMinasDeOroCity,
    comayaguaDepartmentOjosDeAguaCity,
    comayaguaDepartmentPotrerillosCity,
    comayaguaDepartmentRioBonitoCity,
    comayaguaDepartmentSanAntonioDeLaCuestaCity,
    comayaguaDepartmentSanJeronimoCity,
    comayaguaDepartmentSanJoseDeComayaguaCity,
    comayaguaDepartmentSanJoseDelPotreroCity,
    comayaguaDepartmentSanLuisCity,
    comayaguaDepartmentSanSebastianCity,
    comayaguaDepartmentSiguatepequeCity,
    comayaguaDepartmentTaulabeCity,
    comayaguaDepartmentValleDeAngelesCity,
    comayaguaDepartmentVillaDeSanAntonioCity
  ]);

/// The `Copán Department` region in `Honduras`
const Region hondurasCopanDepartment = Region(
  id: 4049,
  parentId: 97,
  longitude: -88.864698,
  latitude: 14.9360838,
  name: "Copán Department",
  type: null,
  stateCode: "CP",
  cities: [
    copanDepartmentAguaCalienteCity,
    copanDepartmentBuenosAiresCity,
    copanDepartmentCabanasCity,
    copanDepartmentChalmecaCity,
    copanDepartmentConcepcionCity,
    copanDepartmentConcepcionDeLaBarrancaCity,
    copanDepartmentCopanCity,
    copanDepartmentCopanRuinasCity,
    copanDepartmentCorquinCity,
    copanDepartmentCucuyaguaCity,
    copanDepartmentDoloresCity,
    copanDepartmentDulceNombreCity,
    copanDepartmentElCorpusCity,
    copanDepartmentElOcotonCity,
    copanDepartmentElParaisoCity,
    copanDepartmentFloridaCity,
    copanDepartmentLaEntradaCity,
    copanDepartmentLaJiguaCity,
    copanDepartmentLaPlayonaCity,
    copanDepartmentLaUnionCity,
    copanDepartmentLaZumbadoraCity,
    copanDepartmentLosTangosCity,
    copanDepartmentNuevaArcadiaCity,
    copanDepartmentOjosDeAguaCity,
    copanDepartmentPuebloNuevoCity,
    copanDepartmentQuezailicaCity,
    copanDepartmentSanAgustinCity,
    copanDepartmentSanAntonioCity,
    copanDepartmentSanJeronimoCity,
    copanDepartmentSanJoaquinCity,
    copanDepartmentSanJoseCity,
    copanDepartmentSanJoseDeCopanCity,
    copanDepartmentSanJuanDeOpoaCity,
    copanDepartmentSanJuanDePlanesCity,
    copanDepartmentSanNicolasCity,
    copanDepartmentSanPedroDeCopanCity,
    copanDepartmentSantaRitaCity,
    copanDepartmentSantaRitaCopanCity,
    copanDepartmentSantaRosaDeCopanCity,
    copanDepartmentTrinidadDeCopanCity,
    copanDepartmentVeracruzCity
  ]);

/// The `Cortés Department` region in `Honduras`
const Region hondurasCortesDepartment = Region(
  id: 4046,
  parentId: 97,
  longitude: -88.0900762,
  latitude: 15.4923508,
  name: "Cortés Department",
  type: null,
  stateCode: "CR",
  cities: [
    cortesDepartmentAguaAzulCity,
    cortesDepartmentAguaAzulRanchoCity,
    cortesDepartmentArmentaCity,
    cortesDepartmentBajaMarCity,
    cortesDepartmentBaracoaCity,
    cortesDepartmentBejucoCity,
    cortesDepartmentCanaveralCity,
    cortesDepartmentCasaQuemadaCity,
    cortesDepartmentChivanaCity,
    cortesDepartmentCholomaCity,
    cortesDepartmentChotepeCity,
    cortesDepartmentCofradiaCity,
    cortesDepartmentCuyamelCity,
    cortesDepartmentElLlanoCity,
    cortesDepartmentElMaranonCity,
    cortesDepartmentElMilagroCity,
    cortesDepartmentElOlivarCity,
    cortesDepartmentElPericoCity,
    cortesDepartmentElPlanCity,
    cortesDepartmentElPorvenirCity,
    cortesDepartmentElRanchoCity,
    cortesDepartmentElTigreCity,
    cortesDepartmentElZapotalDelNorteCity,
    cortesDepartmentLaGuamaCity,
    cortesDepartmentLaHuesaCity,
    cortesDepartmentLaJutosaCity,
    cortesDepartmentLaLimaCity,
    cortesDepartmentLaSabanaCity,
    cortesDepartmentLosCaminosCity,
    cortesDepartmentLosNaranjosCity,
    cortesDepartmentMonterreyCity,
    cortesDepartmentNuevoChameleconCity,
    cortesDepartmentOmoaCity,
    cortesDepartmentOropendolasCity,
    cortesDepartmentPenaBlancaCity,
    cortesDepartmentPimientaCity,
    cortesDepartmentPimientaViejaCity,
    cortesDepartmentPotrerillosCity,
    cortesDepartmentPuebloNuevoCity,
    cortesDepartmentPuertoAltoCity,
    cortesDepartmentPuertoCortesCity,
    cortesDepartmentPuertoCortezCity,
    cortesDepartmentQuebradaSecaCity,
    cortesDepartmentRioBlanquitoCity,
    cortesDepartmentRioChiquitoCity,
    cortesDepartmentRioLindoCity,
    cortesDepartmentSanAntonioDeCortesCity,
    cortesDepartmentSanBuenaventuraCity,
    cortesDepartmentSanFranciscoDeYojoaCity,
    cortesDepartmentSanJoseDelBoqueronCity,
    cortesDepartmentSanManuelCity,
    cortesDepartmentSanPedroSulaCity,
    cortesDepartmentSantaCruzDeYojoaCity,
    cortesDepartmentSantaElenaCity,
    cortesDepartmentTravesiaCity,
    cortesDepartmentVillanuevaCity
  ]);

/// The `El Paraíso Department` region in `Honduras`
const Region hondurasElParaisoDepartment = Region(
  id: 4043,
  parentId: 97,
  longitude: -86.4996546,
  latitude: 13.9821294,
  name: "El Paraíso Department",
  type: null,
  stateCode: "EP",
  cities: [
    elParaisoDepartmentAlaucaCity,
    elParaisoDepartmentArauliCity,
    elParaisoDepartmentCuyaliCity,
    elParaisoDepartmentDanliCity,
    elParaisoDepartmentElBenqueCity,
    elParaisoDepartmentElChichicasteCity,
    elParaisoDepartmentElObrajeCity,
    elParaisoDepartmentElParaisoCity,
    elParaisoDepartmentGuinopeCity,
    elParaisoDepartmentJacaleapaCity,
    elParaisoDepartmentJutiapaCity,
    elParaisoDepartmentLasAnimasCity,
    elParaisoDepartmentLasTrojesCity,
    elParaisoDepartmentLiureCity,
    elParaisoDepartmentMoroceliCity,
    elParaisoDepartmentMunicipioDeTexiguatCity,
    elParaisoDepartmentOjoDeAguaCity,
    elParaisoDepartmentOropoliCity,
    elParaisoDepartmentPotrerillosCity,
    elParaisoDepartmentQuebradaLargaCity,
    elParaisoDepartmentSanAntonioDeFloresCity,
    elParaisoDepartmentSanDiegoCity,
    elParaisoDepartmentSanLucasCity,
    elParaisoDepartmentSanMatiasCity,
    elParaisoDepartmentSantaCruzCity,
    elParaisoDepartmentSoledadCity,
    elParaisoDepartmentTeupasentiCity,
    elParaisoDepartmentTexiguatCity,
    elParaisoDepartmentTrojesCity,
    elParaisoDepartmentVadoAnchoCity,
    elParaisoDepartmentYauyupeCity,
    elParaisoDepartmentYuscaranCity
  ]);

/// The `Francisco Morazán Department` region in `Honduras`
const Region hondurasFranciscoMorazanDepartment = Region(
  id: 4052,
  parentId: 97,
  longitude: -87.0624261,
  latitude: 14.45411,
  name: "Francisco Morazán Department",
  type: null,
  stateCode: "FM",
  cities: [
    franciscoMorazanDepartmentAgaltecaCity,
    franciscoMorazanDepartmentAlubarenCity,
    franciscoMorazanDepartmentCedrosCity,
    franciscoMorazanDepartmentCerroGrandeCity,
    franciscoMorazanDepartmentCofradiaCity,
    franciscoMorazanDepartmentCurarenCity,
    franciscoMorazanDepartmentDistritoCentralCity,
    franciscoMorazanDepartmentElChimboCity,
    franciscoMorazanDepartmentElEscanitoCity,
    franciscoMorazanDepartmentElEscanoDeTepaleCity,
    franciscoMorazanDepartmentElGuanteCity,
    franciscoMorazanDepartmentElGuantilloCity,
    franciscoMorazanDepartmentElGuapinolCity,
    franciscoMorazanDepartmentElLoloCity,
    franciscoMorazanDepartmentElPedernalCity,
    franciscoMorazanDepartmentElPorvenirCity,
    franciscoMorazanDepartmentElSuyatalCity,
    franciscoMorazanDepartmentElTablonCity,
    franciscoMorazanDepartmentElTerreroCity,
    franciscoMorazanDepartmentGuaimacaCity,
    franciscoMorazanDepartmentLaErmitaCity,
    franciscoMorazanDepartmentLaLibertadCity,
    franciscoMorazanDepartmentLaVentaCity,
    franciscoMorazanDepartmentLepateriqueCity,
    franciscoMorazanDepartmentMaraitaCity,
    franciscoMorazanDepartmentMaraleCity,
    franciscoMorazanDepartmentMataDePlatanoCity,
    franciscoMorazanDepartmentMateoCity,
    franciscoMorazanDepartmentNuevaArmeniaCity,
    franciscoMorazanDepartmentOjojonaCity,
    franciscoMorazanDepartmentOricaCity,
    franciscoMorazanDepartmentQuebradasCity,
    franciscoMorazanDepartmentReitocaCity,
    franciscoMorazanDepartmentRioAbajoCity,
    franciscoMorazanDepartmentSabanagrandeCity,
    franciscoMorazanDepartmentSanAntonioDeOrienteCity,
    franciscoMorazanDepartmentSanBuenaventuraCity,
    franciscoMorazanDepartmentSanIgnacioCity,
    franciscoMorazanDepartmentSanJuanDeFloresCity,
    franciscoMorazanDepartmentSanMiguelitoCity,
    franciscoMorazanDepartmentSantaAnaCity,
    franciscoMorazanDepartmentSantaLuciaCity,
    franciscoMorazanDepartmentTalangaCity,
    franciscoMorazanDepartmentTamaraCity,
    franciscoMorazanDepartmentTatumblaCity,
    franciscoMorazanDepartmentTegucigalpaCity,
    franciscoMorazanDepartmentValleDeAngelesCity,
    franciscoMorazanDepartmentVallecilloCity,
    franciscoMorazanDepartmentVillaDeSanFranciscoCity,
    franciscoMorazanDepartmentVillaNuevaCity,
    franciscoMorazanDepartmentYaguacireCity,
    franciscoMorazanDepartmentZambranoCity
  ]);

/// The `Gracias a Dios Department` region in `Honduras`
const Region hondurasGraciasADiosDepartment = Region(
  id: 4048,
  parentId: 97,
  longitude: -84.6060449,
  latitude: 15.341806,
  name: "Gracias a Dios Department",
  type: null,
  stateCode: "GD",
  cities: [
    graciasADiosDepartmentAhuasCity,
    graciasADiosDepartmentAuasCity,
    graciasADiosDepartmentAukaCity,
    graciasADiosDepartmentBarraPatucaCity,
    graciasADiosDepartmentBrusLagunaCity,
    graciasADiosDepartmentIralayaCity,
    graciasADiosDepartmentJuanFranciscoBulnesCity,
    graciasADiosDepartmentPaptalayaCity,
    graciasADiosDepartmentPuertoLempiraCity,
    graciasADiosDepartmentVilledaMoralesCity,
    graciasADiosDepartmentWampusirpiCity,
    graciasADiosDepartmentWawinaCity
  ]);

/// The `Intibucá Department` region in `Honduras`
const Region hondurasIntibucaDepartment = Region(
  id: 4044,
  parentId: 97,
  longitude: -88.2461183,
  latitude: 14.372734,
  name: "Intibucá Department",
  type: null,
  stateCode: "IN",
  cities: [
    intibucaDepartmentCamascaCity,
    intibucaDepartmentColomoncaguaCity,
    intibucaDepartmentConcepcionCity,
    intibucaDepartmentDoloresCity,
    intibucaDepartmentIntibucaCity,
    intibucaDepartmentJesusDeOtoroCity,
    intibucaDepartmentJiquinlacaCity,
    intibucaDepartmentLaEsperanzaCity,
    intibucaDepartmentMagdalenaCity,
    intibucaDepartmentMasaguaraCity,
    intibucaDepartmentSanAntonioCity,
    intibucaDepartmentSanFranciscoDeOpalacaCity,
    intibucaDepartmentSanIsidroCity,
    intibucaDepartmentSanJuanCity,
    intibucaDepartmentSanMarcosDeLaSierraCity,
    intibucaDepartmentSanMiguelitoCity,
    intibucaDepartmentSantaLuciaCity,
    intibucaDepartmentYamaranguilaCity
  ]);

/// The `La Paz Department` region in `Honduras`
const Region hondurasLaPazDepartment = Region(
  id: 4058,
  parentId: 97,
  longitude: -68.5247149,
  latitude: -15.0892416,
  name: "La Paz Department",
  type: null,
  stateCode: "LP",
  cities: [
    laPazDepartmentAguanqueteriqueCity,
    laPazDepartmentCabanasCity,
    laPazDepartmentCaneCity,
    laPazDepartmentChinaclaCity,
    laPazDepartmentGuajiquiroCity,
    laPazDepartmentLaPazCity,
    laPazDepartmentLauteriqueCity,
    laPazDepartmentLosPlanesCity,
    laPazDepartmentMarcalaCity,
    laPazDepartmentMercedesDeOrienteCity,
    laPazDepartmentOpatoroCity,
    laPazDepartmentSanAntonioDelNorteCity,
    laPazDepartmentSanJoseCity,
    laPazDepartmentSanJuanCity,
    laPazDepartmentSanPedroDeTutuleCity,
    laPazDepartmentSantaAnaCity,
    laPazDepartmentSantaElenaCity,
    laPazDepartmentSantaMariaCity,
    laPazDepartmentSantiagoPuringlaCity,
    laPazDepartmentTepanguareCity,
    laPazDepartmentYarulaCity,
    laPazDepartmentYarumelaCity
  ]);

/// The `Lempira Department` region in `Honduras`
const Region hondurasLempiraDepartment = Region(
  id: 4054,
  parentId: 97,
  longitude: -88.556531,
  latitude: 14.1887698,
  name: "Lempira Department",
  type: null,
  stateCode: "LE",
  cities: [
    lempiraDepartmentBelenCity,
    lempiraDepartmentCandelariaCity,
    lempiraDepartmentCololacaCity,
    lempiraDepartmentElAchiotalCity,
    lempiraDepartmentErandiqueCity,
    lempiraDepartmentGraciasCity,
    lempiraDepartmentGualcinceCity,
    lempiraDepartmentGuaritaCity,
    lempiraDepartmentLaCampaCity,
    lempiraDepartmentLaIgualaCity,
    lempiraDepartmentLaLibertadCity,
    lempiraDepartmentLaUnionCity,
    lempiraDepartmentLaVirtudCity,
    lempiraDepartmentLasFloresCity,
    lempiraDepartmentLasTejerasCity,
    lempiraDepartmentLepaeraCity,
    lempiraDepartmentMapulacaCity,
    lempiraDepartmentPiraeraCity,
    lempiraDepartmentSanAndresCity,
    lempiraDepartmentSanFranciscoCity,
    lempiraDepartmentSanJuanGuaritaCity,
    lempiraDepartmentSanManuelColoheteCity,
    lempiraDepartmentSanMarcosDeCaiquinCity,
    lempiraDepartmentSanRafaelCity,
    lempiraDepartmentSanSebastianCity,
    lempiraDepartmentSantaCruzCity,
    lempiraDepartmentTalguaCity,
    lempiraDepartmentTamblaCity,
    lempiraDepartmentTaragualCity,
    lempiraDepartmentTomalaCity,
    lempiraDepartmentValladolidCity,
    lempiraDepartmentVirginiaCity
  ]);

/// The `Ocotepeque Department` region in `Honduras`
const Region hondurasOcotepequeDepartment = Region(
  id: 4056,
  parentId: 97,
  longitude: -89.0561532,
  latitude: 14.5170347,
  name: "Ocotepeque Department",
  type: null,
  stateCode: "OC",
  cities: [
    ocotepequeDepartmentAntiguaOcotepequeCity,
    ocotepequeDepartmentBelenGualchoCity,
    ocotepequeDepartmentConcepcionCity,
    ocotepequeDepartmentDoloresMerendonCity,
    ocotepequeDepartmentElTransitoCity,
    ocotepequeDepartmentFraternidadCity,
    ocotepequeDepartmentLaEncarnacionCity,
    ocotepequeDepartmentLaLaborCity,
    ocotepequeDepartmentLucernaCity,
    ocotepequeDepartmentMercedesCity,
    ocotepequeDepartmentNuevaOcotepequeCity,
    ocotepequeDepartmentSanFernandoCity,
    ocotepequeDepartmentSanFranciscoDeConesCity,
    ocotepequeDepartmentSanFranciscoDelValleCity,
    ocotepequeDepartmentSanJorgeCity,
    ocotepequeDepartmentSanMarcosCity,
    ocotepequeDepartmentSantaFeCity,
    ocotepequeDepartmentSantaLuciaCity,
    ocotepequeDepartmentSensentiCity,
    ocotepequeDepartmentSinuapaCity,
    ocotepequeDepartmentYaruchelCity
  ]);

/// The `Olancho Department` region in `Honduras`
const Region hondurasOlanchoDepartment = Region(
  id: 4050,
  parentId: 97,
  longitude: -85.7666645,
  latitude: 14.8067406,
  name: "Olancho Department",
  type: null,
  stateCode: "OL",
  cities: [
    olanchoDepartmentArimisCity,
    olanchoDepartmentCampamentoCity,
    olanchoDepartmentCatacamasCity,
    olanchoDepartmentConcordiaCity,
    olanchoDepartmentDulceNombreDeCulmiCity,
    olanchoDepartmentElGuayabitoCity,
    olanchoDepartmentElRosarioCity,
    olanchoDepartmentElRusioCity,
    olanchoDepartmentEsquipulasDelNorteCity,
    olanchoDepartmentGualacoCity,
    olanchoDepartmentGuarizamaCity,
    olanchoDepartmentGuataCity,
    olanchoDepartmentGuayapeCity,
    olanchoDepartmentJanoCity,
    olanchoDepartmentJuticalpaCity,
    olanchoDepartmentJutiquileCity,
    olanchoDepartmentLaConcepcionCity,
    olanchoDepartmentLaEstanciaCity,
    olanchoDepartmentLaGuataCity,
    olanchoDepartmentLaUnionCity,
    olanchoDepartmentLagunaSecaCity,
    olanchoDepartmentMangulileCity,
    olanchoDepartmentMantoCity,
    olanchoDepartmentMunicipioDeSanFranciscoDeLaPazCity,
    olanchoDepartmentPatucaCity,
    olanchoDepartmentPunuareCity,
    olanchoDepartmentSalamaCity,
    olanchoDepartmentSanEstebanCity,
    olanchoDepartmentSanFranciscoDeBecerraCity,
    olanchoDepartmentSanFranciscoDeLaPazCity,
    olanchoDepartmentSanJoseDeRioTintoCity,
    olanchoDepartmentSanNicolasCity,
    olanchoDepartmentSantaMariaDelRealCity,
    olanchoDepartmentSilcaCity,
    olanchoDepartmentYoconCity,
    olanchoDepartmentZopilotepeCity
  ]);

/// The `Santa Bárbara Department` region in `Honduras`
const Region hondurasSantaBarbaraDepartment = Region(
  id: 4053,
  parentId: 97,
  longitude: -88.4016041,
  latitude: 15.1202795,
  name: "Santa Bárbara Department",
  type: null,
  stateCode: "SB",
  cities: [
    santaBarbaraDepartmentAgualoteCity,
    santaBarbaraDepartmentAradaCity,
    santaBarbaraDepartmentAtimaCity,
    santaBarbaraDepartmentAzacualpaCity,
    santaBarbaraDepartmentBerlinCity,
    santaBarbaraDepartmentCallejonesCity,
    santaBarbaraDepartmentCamaloteCity,
    santaBarbaraDepartmentCasaQuemadaCity,
    santaBarbaraDepartmentCeguacaCity,
    santaBarbaraDepartmentChindaCity,
    santaBarbaraDepartmentConcepcionDelNorteCity,
    santaBarbaraDepartmentConcepcionDelSurCity,
    santaBarbaraDepartmentCorrederosCity,
    santaBarbaraDepartmentElCirueloCity,
    santaBarbaraDepartmentElCorozalCity,
    santaBarbaraDepartmentElMochitoCity,
    santaBarbaraDepartmentElNisperoCity,
    santaBarbaraDepartmentGuacamayaCity,
    santaBarbaraDepartmentGualalaCity,
    santaBarbaraDepartmentGualjocoCity,
    santaBarbaraDepartmentIlamaCity,
    santaBarbaraDepartmentJoconalCity,
    santaBarbaraDepartmentLaFlechaCity,
    santaBarbaraDepartmentLagunaVerdeCity,
    santaBarbaraDepartmentLasVegasCity,
    santaBarbaraDepartmentLasVegasSantaBarbaraCity,
    santaBarbaraDepartmentLomaAltaCity,
    santaBarbaraDepartmentMacuelizoCity,
    santaBarbaraDepartmentNacoCity,
    santaBarbaraDepartmentNaranjitoCity,
    santaBarbaraDepartmentNuevaFronteraCity,
    santaBarbaraDepartmentNuevaJalapaCity,
    santaBarbaraDepartmentNuevoCelilacCity,
    santaBarbaraDepartmentPetoaCity,
    santaBarbaraDepartmentPinalejoCity,
    santaBarbaraDepartmentProteccionCity,
    santaBarbaraDepartmentQuimistanCity,
    santaBarbaraDepartmentSanFranciscoDeOjueraCity,
    santaBarbaraDepartmentSanJoseDeColinasCity,
    santaBarbaraDepartmentSanJoseDeTarrosCity,
    santaBarbaraDepartmentSanLuisCity,
    santaBarbaraDepartmentSanLuisDePlanesCity,
    santaBarbaraDepartmentSanMarcosCity,
    santaBarbaraDepartmentSanNicolasCity,
    santaBarbaraDepartmentSanPedroZacapaCity,
    santaBarbaraDepartmentSanVicenteCentenarioCity,
    santaBarbaraDepartmentSantaBarbaraCity,
    santaBarbaraDepartmentSantaRitaCity,
    santaBarbaraDepartmentSulaCity,
    santaBarbaraDepartmentTrasCerrosCity,
    santaBarbaraDepartmentTrinidadCity
  ]);

/// The `Valle Department` region in `Honduras`
const Region hondurasValleDepartment = Region(
  id: 4055,
  parentId: 97,
  longitude: -87.5791287,
  latitude: 13.5782936,
  name: "Valle Department",
  type: null,
  stateCode: "VA",
  cities: [
    valleDepartmentAguaFriaCity,
    valleDepartmentAlianzaCity,
    valleDepartmentAmapalaCity,
    valleDepartmentAramecinaCity,
    valleDepartmentCaridadCity,
    valleDepartmentElCuboleroCity,
    valleDepartmentElTularCity,
    valleDepartmentGoascoranCity,
    valleDepartmentJicaroGalanCity,
    valleDepartmentLaAlianzaCity,
    valleDepartmentLaCribaCity,
    valleDepartmentLangueCity,
    valleDepartmentNacaomeCity,
    valleDepartmentSanFranciscoDeCorayCity,
    valleDepartmentSanLorenzoCity
  ]);

/// The `Yoro Department` region in `Honduras`
const Region hondurasYoroDepartment = Region(
  id: 4057,
  parentId: 97,
  longitude: -87.1422895,
  latitude: 15.2949679,
  name: "Yoro Department",
  type: null,
  stateCode: "YO",
  cities: [
    yoroDepartmentAguaBlancaSurCity,
    yoroDepartmentArenalCity,
    yoroDepartmentArmeniaCity,
    yoroDepartmentAyapaCity,
    yoroDepartmentBalsamoOrientalCity,
    yoroDepartmentCarbajalesCity,
    yoroDepartmentCoyolesCentralCity,
    yoroDepartmentElBalsamoCity,
    yoroDepartmentElJuncalCity,
    yoroDepartmentElNegritoCity,
    yoroDepartmentElOcoteCity,
    yoroDepartmentElProgresoCity,
    yoroDepartmentGuaimitasCity,
    yoroDepartmentJoconCity,
    yoroDepartmentLaEstanciaCity,
    yoroDepartmentLaGuacamayaCity,
    yoroDepartmentLaMinaCity,
    yoroDepartmentLaRosaCity,
    yoroDepartmentLaSarrosaCity,
    yoroDepartmentLaTrinidadCity,
    yoroDepartmentLasVegasCity,
    yoroDepartmentLomitasCity,
    yoroDepartmentMojimanCity,
    yoroDepartmentMorazanCity,
    yoroDepartmentNombreDeJesusCity,
    yoroDepartmentNuevaEsperanzaCity,
    yoroDepartmentOcotePaulinoCity,
    yoroDepartmentOlanchitoCity,
    yoroDepartmentPaujilesCity,
    yoroDepartmentPuntaOcoteCity,
    yoroDepartmentSanAntonioCity,
    yoroDepartmentSanJoseCity,
    yoroDepartmentSantaRitaCity,
    yoroDepartmentSubiranaCity,
    yoroDepartmentSulacoCity,
    yoroDepartmentTeguajinalCity,
    yoroDepartmentTepustecaCity,
    yoroDepartmentToyosCity,
    yoroDepartmentTrojasCity,
    yoroDepartmentVictoriaCity,
    yoroDepartmentYoritoCity,
    yoroDepartmentYoroCity
  ]);

/// The 18 states of `Honduras` keyed by their id.
const Map<int, Region> hondurasStates = <int, Region>{
    4047: hondurasAtlantidaDepartment,
    4045: hondurasBayIslandsDepartment,
    4041: hondurasCholutecaDepartment,
    4051: hondurasColonDepartment,
    4042: hondurasComayaguaDepartment,
    4049: hondurasCopanDepartment,
    4046: hondurasCortesDepartment,
    4043: hondurasElParaisoDepartment,
    4052: hondurasFranciscoMorazanDepartment,
    4048: hondurasGraciasADiosDepartment,
    4044: hondurasIntibucaDepartment,
    4058: hondurasLaPazDepartment,
    4054: hondurasLempiraDepartment,
    4056: hondurasOcotepequeDepartment,
    4050: hondurasOlanchoDepartment,
    4053: hondurasSantaBarbaraDepartment,
    4055: hondurasValleDepartment,
    4057: hondurasYoroDepartment
  };
