/// Access to known geographies in Hong Kong S.A.R. and their meta data.
library geography;

import '../base.dart';

// ignore: slash_for_doc_comments
/** BEGIN AUTO_GENERATED CODE **/

const Country hongKongSAR = Country(id: 98, name: "Hong Kong S.A.R.", longitude: 114.16666666,
          latitude: 22.25, capital: "Hong Kong",
          currency: "HKD", currencySymbol: "\$",
          emoji: "🇭🇰", emojiU: "U+1F1ED U+1F1F0",
          iso2: "HK", iso3: "HKG",
          native: "香港", numericCode: "344",
          phoneCode: "852", region: "Asia",
          subregion: "Eastern Asia", tld: ".hk",
          states: [
            Region(id: 4889, longitude: 114.15497, latitude: 22.28666,
                    name: "Central and Western District", type: null, stateCode: "HCW",
                    cities: []),
            Region(id: 4891, longitude: 114.22414, latitude: 22.28411,
                    name: "Eastern", type: null, stateCode: "HEA",
                    cities: []),
            Region(id: 4888, longitude: 113.94608, latitude: 22.26114,
                    name: "Islands District", type: null, stateCode: "NIS",
                    cities: []),
            Region(id: 4895, longitude: 114.19155, latitude: 22.3282,
                    name: "Kowloon City", type: null, stateCode: "KKC",
                    cities: []),
            Region(id: 4898, longitude: 114.08401, latitude: 22.35488,
                    name: "Kwai Tsing", type: null, stateCode: "NKT",
                    cities: []),
            Region(id: 4897, longitude: 114.22581, latitude: 22.31326,
                    name: "Kwun Tong", type: null, stateCode: "KKT",
                    cities: []),
            Region(id: 4900, longitude: 114.13812, latitude: 22.49471,
                    name: "North", type: null, stateCode: "NNO",
                    cities: []),
            Region(id: 4887, longitude: 114.27052, latitude: 22.38143,
                    name: "Sai Kung District", type: null, stateCode: "NSK",
                    cities: []),
            Region(id: 4901, longitude: 114.19534, latitude: 22.38715,
                    name: "Sha Tin", type: null, stateCode: "NST",
                    cities: []),
            Region(id: 4894, longitude: 114.1622, latitude: 22.33074,
                    name: "Sham Shui Po", type: null, stateCode: "KSS",
                    cities: []),
            Region(id: 4892, longitude: 114.15884, latitude: 22.24725,
                    name: "Southern", type: null, stateCode: "HSO",
                    cities: []),
            Region(id: 4885, longitude: 114.16422, latitude: 22.45085,
                    name: "Tai Po District", type: null, stateCode: "NTP",
                    cities: []),
            Region(id: 4884, longitude: 114.12907, latitude: 22.36281,
                    name: "Tsuen Wan District", type: null, stateCode: "NTW",
                    cities: []),
            Region(id: 4899, longitude: 113.9770885, latitude: 22.39163,
                    name: "Tuen Mun", type: null, stateCode: "NTM",
                    cities: []),
            Region(id: 4890, longitude: 114.17168, latitude: 22.27968,
                    name: "Wan Chai", type: null, stateCode: "HWC",
                    cities: []),
            Region(id: 4896, longitude: 114.19686, latitude: 22.33353,
                    name: "Wong Tai Sin", type: null, stateCode: "KWT",
                    cities: []),
            Region(id: 4893, longitude: 114.1726, latitude: 22.32138,
                    name: "Yau Tsim Mong", type: null, stateCode: "KYT",
                    cities: []),
            Region(id: 4883, longitude: 114.02218, latitude: 22.44559,
                    name: "Yuen Long District", type: null, stateCode: "NYL",
                    cities: [])
          ],
          timezones: [
            Timezone(abbreviation: "HKT", gmtOffset: 28800, gmtOffsetName: "UTC+08:00",
                    tzName: "Hong Kong Time", zoneName: "Asia/Hong_Kong")
          ],
          translations: {
            "kr": "홍콩",
            "br": "Hong Kong",
            "pt": "Hong Kong",
            "nl": "Hongkong",
            "hr": "Hong Kong",
            "fa": "هنگ‌کنگ",
            "de": "Hong Kong",
            "es": "Hong Kong",
            "fr": "Hong Kong",
            "ja": "香港",
            "it": "Hong Kong",
            "cn": "中国香港"
          });
