/// Access to known geographies in `Hungary` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.
library;

import '../base.dart';
import 'hungary_cities.dart';

/// The `Bács-Kiskun` region in `Hungary`
const Region hungaryBacsHypkiskunCounty = Region(
  id: 1048,
  parentId: 99,
  longitude: 19.4272464,
  latitude: 46.5661437,
  name: "Bács-Kiskun",
  type: "county",
  stateCode: "BK",
  cities: [
    bacsHypkiskunCountyAgasegyhazaCity,
    bacsHypkiskunCountyAkasztoCity,
    bacsHypkiskunCountyApostagCity,
    bacsHypkiskunCountyBacsalmasCity,
    bacsHypkiskunCountyBacsalmasiJarasCity,
    bacsHypkiskunCountyBacsbokodCity,
    bacsHypkiskunCountyBajaCity,
    bacsHypkiskunCountyBajaiJarasCity,
    bacsHypkiskunCountyBalloszogCity,
    bacsHypkiskunCountyBatyaCity,
    bacsHypkiskunCountyBugacCity,
    bacsHypkiskunCountyCsaszartoltesCity,
    bacsHypkiskunCountyCsavolyCity,
    bacsHypkiskunCountyCsengodCity,
    bacsHypkiskunCountyDavodCity,
    bacsHypkiskunCountyDunapatajCity,
    bacsHypkiskunCountyDunavecseCity,
    bacsHypkiskunCountyDusnokCity,
    bacsHypkiskunCountyErsekcsanadCity,
    bacsHypkiskunCountyFelsoszentivanCity,
    bacsHypkiskunCountyFulopjakabCity,
    bacsHypkiskunCountyFulopszallasCity,
    bacsHypkiskunCountyGaraCity,
    bacsHypkiskunCountyHajosCity,
    bacsHypkiskunCountyHartaCity,
    bacsHypkiskunCountyHelveciaCity,
    bacsHypkiskunCountyHercegszantoCity,
    bacsHypkiskunCountyIzsakCity,
    bacsHypkiskunCountyJanoshalmaCity,
    bacsHypkiskunCountyJanoshalmaiJarasCity,
    bacsHypkiskunCountyJaszszentlaszloCity,
    bacsHypkiskunCountyKalocsaCity,
    bacsHypkiskunCountyKalocsaiJarasCity,
    bacsHypkiskunCountyKatymarCity,
    bacsHypkiskunCountyKecelCity,
    bacsHypkiskunCountyKecskemetCity,
    bacsHypkiskunCountyKecskemetiJarasCity,
    bacsHypkiskunCountyKelebiaCity,
    bacsHypkiskunCountyKerekegyhazaCity,
    bacsHypkiskunCountyKiskorosCity,
    bacsHypkiskunCountyKiskorosiJarasCity,
    bacsHypkiskunCountyKiskunfelegyhazaCity,
    bacsHypkiskunCountyKiskunfelegyhaziJarasCity,
    bacsHypkiskunCountyKiskunhalasCity,
    bacsHypkiskunCountyKiskunhalasiJarasCity,
    bacsHypkiskunCountyKiskunmajsaCity,
    bacsHypkiskunCountyKiskunmajsaiJarasCity,
    bacsHypkiskunCountyKisszallasCity,
    bacsHypkiskunCountyKunfehertoCity,
    bacsHypkiskunCountyKunszentmiklosCity,
    bacsHypkiskunCountyKunszentmiklosiJarasCity,
    bacsHypkiskunCountyLajosmizseCity,
    bacsHypkiskunCountyLakitelekCity,
    bacsHypkiskunCountyMadarasCity,
    bacsHypkiskunCountyMelykutCity,
    bacsHypkiskunCountyNagybaracskaCity,
    bacsHypkiskunCountyNemesnadudvarCity,
    bacsHypkiskunCountyNyarlorincCity,
    bacsHypkiskunCountyOrgovanyCity,
    bacsHypkiskunCountyPalmonostoraCity,
    bacsHypkiskunCountySoltCity,
    bacsHypkiskunCountySoltvadkertCity,
    bacsHypkiskunCountySukosdCity,
    bacsHypkiskunCountySzabadszallasCity,
    bacsHypkiskunCountySzalkszentmartonCity,
    bacsHypkiskunCountySzankCity,
    bacsHypkiskunCountySzentkiralyCity,
    bacsHypkiskunCountyTassCity,
    bacsHypkiskunCountyTazlarCity,
    bacsHypkiskunCountyTiszaalparCity,
    bacsHypkiskunCountyTiszakecskeCity,
    bacsHypkiskunCountyTiszakecskeiJarasCity,
    bacsHypkiskunCountyTompaCity,
    bacsHypkiskunCountyVarosfoldCity,
    bacsHypkiskunCountyVaskutCity
  ]);

/// The `Baranya` region in `Hungary`
const Region hungaryBaranyaCounty = Region(
  id: 1055,
  parentId: 99,
  longitude: 18.2719173,
  latitude: 46.0484585,
  name: "Baranya",
  type: "county",
  stateCode: "BA",
  cities: [
    baranyaCountyBeremendCity,
    baranyaCountyBolyCity,
    baranyaCountyBolyiJarasCity,
    baranyaCountyBukkosdCity,
    baranyaCountyDunaszekcsoCity,
    baranyaCountyHarkanyCity,
    baranyaCountyHegyhatiJarasCity,
    baranyaCountyHidasCity,
    baranyaCountyHosszuhetenyCity,
    baranyaCountyKomloCity,
    baranyaCountyKomloiJarasCity,
    baranyaCountyKozarmislenyCity,
    baranyaCountyLanycsokCity,
    baranyaCountyMagocsCity,
    baranyaCountyMecseknadasdCity,
    baranyaCountyMohacsCity,
    baranyaCountyMohacsiJarasCity,
    baranyaCountyPecsCity,
    baranyaCountyPecsiJarasCity,
    baranyaCountyPecsvaradCity,
    baranyaCountyPecsvaradiJarasCity,
    baranyaCountyPellerdCity,
    baranyaCountySasdCity,
    baranyaCountySellyeCity,
    baranyaCountySellyeiJarasCity,
    baranyaCountySiklosCity,
    baranyaCountySiklosiJarasCity,
    baranyaCountySzaszvarCity,
    baranyaCountySzentlorincCity,
    baranyaCountySzentlorinciJarasCity,
    baranyaCountySzigetvarCity,
    baranyaCountySzigetvariJarasCity,
    baranyaCountyVajszloCity,
    baranyaCountyVillanyCity
  ]);

/// The `Békés` region in `Hungary`
const Region hungaryBekesCounty = Region(
  id: 1060,
  parentId: 99,
  longitude: 21.0434996,
  latitude: 46.6704899,
  name: "Békés",
  type: "county",
  stateCode: "BE",
  cities: [
    bekesCountyBattonyaCity,
    bekesCountyBekesCity,
    bekesCountyBekescsabaCity,
    bekesCountyBekescsabaiJarasCity,
    bekesCountyBekesiJarasCity,
    bekesCountyBekessamsonCity,
    bekesCountyBekesszentandrasCity,
    bekesCountyBucsaCity,
    bekesCountyCsanadapacaCity,
    bekesCountyCsorvasCity,
    bekesCountyDevavanyaCity,
    bekesCountyDobozCity,
    bekesCountyDombegyhazCity,
    bekesCountyElekCity,
    bekesCountyFuzesgyarmatCity,
    bekesCountyGadorosCity,
    bekesCountyGyomaendrodCity,
    bekesCountyGyomaendrodiJarasCity,
    bekesCountyGyulaCity,
    bekesCountyGyulaiJarasCity,
    bekesCountyKaszaperCity,
    bekesCountyKetegyhazaCity,
    bekesCountyKevermesCity,
    bekesCountyKondorosCity,
    bekesCountyKorosladanyCity,
    bekesCountyKorostarcsaCity,
    bekesCountyKunagotaCity,
    bekesCountyLokoshazaCity,
    bekesCountyMagyarbanhegyesCity,
    bekesCountyMedgyesegyhazaCity,
    bekesCountyMehkerekCity,
    bekesCountyMezoberenyCity,
    bekesCountyMezohegyesCity,
    bekesCountyMezokovacshazaCity,
    bekesCountyMezokovacshazaiJarasCity,
    bekesCountyNagyszenasCity,
    bekesCountyOkanyCity,
    bekesCountyOroshazaCity,
    bekesCountyOroshaziJarasCity,
    bekesCountyPusztafoldvarCity,
    bekesCountySarkadCity,
    bekesCountySarkadiJarasCity,
    bekesCountySzabadkigyosCity,
    bekesCountySzarvasCity,
    bekesCountySzarvasiJarasCity,
    bekesCountySzeghalmiJarasCity,
    bekesCountySzeghalomCity,
    bekesCountyTotkomlosCity,
    bekesCountyUjkigyosCity,
    bekesCountyVesztoCity
  ]);

/// The `Békéscsaba` region in `Hungary`
const Region hungaryBekescsabaCityWithCountyRights = Region(
  id: 1036,
  parentId: 99,
  longitude: 21.0877309,
  latitude: 46.6735939,
  name: "Békéscsaba",
  type: "city with county rights",
  stateCode: "BC",
  cities: []);

/// The `Borsod-Abaúj-Zemplén` region in `Hungary`
const Region hungaryBorsodHypabaujHypzemplenCounty = Region(
  id: 1058,
  parentId: 99,
  longitude: 20.6934112,
  latitude: 48.2939401,
  name: "Borsod-Abaúj-Zemplén",
  type: "county",
  stateCode: "BZ",
  cities: [
    borsodHypabaujHypzemplenCountyAbaujszantoCity,
    borsodHypabaujHypzemplenCountyAlsozsolcaCity,
    borsodHypabaujHypzemplenCountyArloCity,
    borsodHypabaujHypzemplenCountyArnotCity,
    borsodHypabaujHypzemplenCountyAszaloCity,
    borsodHypabaujHypzemplenCountyBekecsCity,
    borsodHypabaujHypzemplenCountyBocsCity,
    borsodHypabaujHypzemplenCountyBogacsCity,
    borsodHypabaujHypzemplenCountyBoldvaCity,
    borsodHypabaujHypzemplenCountyBorsodnadasdCity,
    borsodHypabaujHypzemplenCountyCigandCity,
    borsodHypabaujHypzemplenCountyCigandiJarasCity,
    borsodHypabaujHypzemplenCountyEdelenyCity,
    borsodHypabaujHypzemplenCountyEdelenyiJarasCity,
    borsodHypabaujHypzemplenCountyEmodCity,
    borsodHypabaujHypzemplenCountyEncsCity,
    borsodHypabaujHypzemplenCountyEncsiJarasCity,
    borsodHypabaujHypzemplenCountyFarkaslyukCity,
    borsodHypabaujHypzemplenCountyFelsozsolcaCity,
    borsodHypabaujHypzemplenCountyGesztelyCity,
    borsodHypabaujHypzemplenCountyGoncCity,
    borsodHypabaujHypzemplenCountyGonciJarasCity,
    borsodHypabaujHypzemplenCountyHalmajCity,
    borsodHypabaujHypzemplenCountyHarsanyCity,
    borsodHypabaujHypzemplenCountyHejobabaCity,
    borsodHypabaujHypzemplenCountyHernadnemetiCity,
    borsodHypabaujHypzemplenCountyIzsofalvaCity,
    borsodHypabaujHypzemplenCountyJardanhazaCity,
    borsodHypabaujHypzemplenCountyKarcsaCity,
    borsodHypabaujHypzemplenCountyKazincbarcikaCity,
    borsodHypabaujHypzemplenCountyKazincbarcikaiJarasCity,
    borsodHypabaujHypzemplenCountyMadCity,
    borsodHypabaujHypzemplenCountyMalyiCity,
    borsodHypabaujHypzemplenCountyMegyaszoCity,
    borsodHypabaujHypzemplenCountyMezocsatCity,
    borsodHypabaujHypzemplenCountyMezocsatiJarasCity,
    borsodHypabaujHypzemplenCountyMezokeresztesCity,
    borsodHypabaujHypzemplenCountyMezokovesdCity,
    borsodHypabaujHypzemplenCountyMezokovesdiJarasCity,
    borsodHypabaujHypzemplenCountyMezozomborCity,
    borsodHypabaujHypzemplenCountyMiskolcCity,
    borsodHypabaujHypzemplenCountyMiskolciJarasCity,
    borsodHypabaujHypzemplenCountyMonokCity,
    borsodHypabaujHypzemplenCountyMucsonyCity,
    borsodHypabaujHypzemplenCountyNyekladhazaCity,
    borsodHypabaujHypzemplenCountyOlaszliszkaCity,
    borsodHypabaujHypzemplenCountyOngaCity,
    borsodHypabaujHypzemplenCountyOnodCity,
    borsodHypabaujHypzemplenCountyOzdCity,
    borsodHypabaujHypzemplenCountyOzdiJarasCity,
    borsodHypabaujHypzemplenCountyPrugyCity,
    borsodHypabaujHypzemplenCountyPutnokCity,
    borsodHypabaujHypzemplenCountyPutnokiJarasCity,
    borsodHypabaujHypzemplenCountyRicseCity,
    borsodHypabaujHypzemplenCountyRudabanyaCity,
    borsodHypabaujHypzemplenCountySajobabonyCity,
    borsodHypabaujHypzemplenCountySajokazaCity,
    borsodHypabaujHypzemplenCountySajoladCity,
    borsodHypabaujHypzemplenCountySajoorosCity,
    borsodHypabaujHypzemplenCountySajoszentpeterCity,
    borsodHypabaujHypzemplenCountySajoszogedCity,
    borsodHypabaujHypzemplenCountySajovamosCity,
    borsodHypabaujHypzemplenCountySalyCity,
    borsodHypabaujHypzemplenCountySarospatakCity,
    borsodHypabaujHypzemplenCountySarospatakiJarasCity,
    borsodHypabaujHypzemplenCountySatoraljaujhelyCity,
    borsodHypabaujHypzemplenCountySatoraljaujhelyiJarasCity,
    borsodHypabaujHypzemplenCountySzendroCity,
    borsodHypabaujHypzemplenCountySzentistvanCity,
    borsodHypabaujHypzemplenCountySzerencsCity,
    borsodHypabaujHypzemplenCountySzerencsiJarasCity,
    borsodHypabaujHypzemplenCountySzikszoCity,
    borsodHypabaujHypzemplenCountySzikszoiJarasCity,
    borsodHypabaujHypzemplenCountySzirmabesenyoCity,
    borsodHypabaujHypzemplenCountyTaktaharkanyCity,
    borsodHypabaujHypzemplenCountyTaktaszadaCity,
    borsodHypabaujHypzemplenCountyTallyaCity,
    borsodHypabaujHypzemplenCountyTarcalCity,
    borsodHypabaujHypzemplenCountyTiszakaradCity,
    borsodHypabaujHypzemplenCountyTiszakesziCity,
    borsodHypabaujHypzemplenCountyTiszalucCity,
    borsodHypabaujHypzemplenCountyTiszaujvarosCity,
    borsodHypabaujHypzemplenCountyTiszaujvarosiJarasCity,
    borsodHypabaujHypzemplenCountyTokajCity,
    borsodHypabaujHypzemplenCountyTokajiJarasCity,
    borsodHypabaujHypzemplenCountyTolcsvaCity
  ]);

/// The `Budapest` region in `Hungary`
const Region hungaryBudapestCapitalCity = Region(
  id: 1064,
  parentId: 99,
  longitude: 19.040235,
  latitude: 47.497912,
  name: "Budapest",
  type: "capital city",
  stateCode: "BU",
  cities: [
    budapestCapitalCityBudapestCity,
    budapestCapitalCityBudapestIKeruletCity,
    budapestCapitalCityBudapestIiKeruletCity,
    budapestCapitalCityBudapestIiiKeruletCity,
    budapestCapitalCityBudapestIvKeruletCity,
    budapestCapitalCityBudapestViKeruletCity,
    budapestCapitalCityBudapestViiiKeruletCity,
    budapestCapitalCityBudapestXKeruletCity,
    budapestCapitalCityBudapestXiKeruletCity,
    budapestCapitalCityBudapestXiiKeruletCity,
    budapestCapitalCityBudapestXiiiKeruletCity,
    budapestCapitalCityBudapestXvKeruletCity,
    budapestCapitalCityBudapestXviKeruletCity,
    budapestCapitalCityBudapestXviiKeruletCity,
    budapestCapitalCityBudapestXviiiKeruletCity,
    budapestCapitalCityBudapestXxKeruletCity,
    budapestCapitalCityBudapestXxiKeruletCity,
    budapestCapitalCityBudapestXxiiKeruletCity,
    budapestCapitalCityBudapestXxiiiKeruletCity,
    budapestCapitalCityErzsebetvarosCity,
    budapestCapitalCityJozsefvarosCity,
    budapestCapitalCityKispestCity,
    budapestCapitalCityZugloCity
  ]);

/// The `Csongrád County` region in `Hungary`
const Region hungaryCsongradCountyCounty = Region(
  id: 1031,
  parentId: 99,
  longitude: 20.2566161,
  latitude: 46.416705,
  name: "Csongrád County",
  type: "county",
  stateCode: "CS",
  cities: [
    csongradCountyCountyAlgyoCity,
    csongradCountyCountyApatfalvaCity,
    csongradCountyCountyAsotthalomCity,
    csongradCountyCountyBaksCity,
    csongradCountyCountyBalastyaCity,
    csongradCountyCountyBordanyCity,
    csongradCountyCountyCsanadpalotaCity,
    csongradCountyCountyCsanytelekCity,
    csongradCountyCountyCsengeleCity,
    csongradCountyCountyCsongradCity,
    csongradCountyCountyCsongradiJarasCity,
    csongradCountyCountyDeszkCity,
    csongradCountyCountyDomaszekCity,
    csongradCountyCountyFabiansebestyenCity,
    csongradCountyCountyFoldeakCity,
    csongradCountyCountyForraskutCity,
    csongradCountyCountyHodmezovasarhelyCity,
    csongradCountyCountyHodmezovasarhelyiJarasCity,
    csongradCountyCountyKistelekCity,
    csongradCountyCountyKistelekiJarasCity,
    csongradCountyCountyKiszomborCity,
    csongradCountyCountyMakoCity,
    csongradCountyCountyMakoiJarasCity,
    csongradCountyCountyMarosleleCity,
    csongradCountyCountyMindszentCity,
    csongradCountyCountyMorahalmiJarasCity,
    csongradCountyCountyMorahalomCity,
    csongradCountyCountyOpusztaszerCity,
    csongradCountyCountyPusztaszerCity,
    csongradCountyCountyRoszkeCity,
    csongradCountyCountyRuzsaCity,
    csongradCountyCountySandorfalvaCity,
    csongradCountyCountySzatymazCity,
    csongradCountyCountySzegedCity,
    csongradCountyCountySzegediJarasCity,
    csongradCountyCountySzegvarCity,
    csongradCountyCountySzekkutasCity,
    csongradCountyCountySzentesCity,
    csongradCountyCountySzentesiJarasCity,
    csongradCountyCountyTomorkenyCity,
    csongradCountyCountyUllesCity,
    csongradCountyCountyZakanyszekCity,
    csongradCountyCountyZsomboCity
  ]);

/// The `Debrecen` region in `Hungary`
const Region hungaryDebrecenCityWithCountyRights = Region(
  id: 1032,
  parentId: 99,
  longitude: 21.6273124,
  latitude: 47.5316049,
  name: "Debrecen",
  type: "city with county rights",
  stateCode: "DE",
  cities: []);

/// The `Dunaújváros` region in `Hungary`
const Region hungaryDunaujvarosCityWithCountyRights = Region(
  id: 1049,
  parentId: 99,
  longitude: 18.9355227,
  latitude: 46.9619059,
  name: "Dunaújváros",
  type: "city with county rights",
  stateCode: "DU",
  cities: []);

/// The `Eger` region in `Hungary`
const Region hungaryEgerCityWithCountyRights = Region(
  id: 1037,
  parentId: 99,
  longitude: 20.3772284,
  latitude: 47.9025348,
  name: "Eger",
  type: "city with county rights",
  stateCode: "EG",
  cities: []);

/// The `Érd` region in `Hungary`
const Region hungaryErdCityWithCountyRights = Region(
  id: 1028,
  parentId: 99,
  longitude: 18.904544,
  latitude: 47.3919718,
  name: "Érd",
  type: "city with county rights",
  stateCode: "ER",
  cities: []);

/// The `Fejér County` region in `Hungary`
const Region hungaryFejerCountyCounty = Region(
  id: 1044,
  parentId: 99,
  longitude: 18.5294815,
  latitude: 47.1217932,
  name: "Fejér County",
  type: "county",
  stateCode: "FE",
  cities: [
    fejerCountyCountyAbaCity,
    fejerCountyCountyAdonyCity,
    fejerCountyCountyAlapCity,
    fejerCountyCountyBakonycsernyeCity,
    fejerCountyCountyBaracsCity,
    fejerCountyCountyBaracskaCity,
    fejerCountyCountyBicskeCity,
    fejerCountyCountyBicskeiJarasCity,
    fejerCountyCountyBodajkCity,
    fejerCountyCountyCeceCity,
    fejerCountyCountyCsakvarCity,
    fejerCountyCountyDegCity,
    fejerCountyCountyDunaujvarosCity,
    fejerCountyCountyDunaujvarosiJarasCity,
    fejerCountyCountyEloszallasCity,
    fejerCountyCountyEnyingCity,
    fejerCountyCountyEnyingiJarasCity,
    fejerCountyCountyErcsiCity,
    fejerCountyCountyEtyekCity,
    fejerCountyCountyFehervarcsurgoCity,
    fejerCountyCountyGardonyCity,
    fejerCountyCountyGardonyiJarasCity,
    fejerCountyCountyIvancsaCity,
    fejerCountyCountyKalozCity,
    fejerCountyCountyKapolnasnyekCity,
    fejerCountyCountyKincsesbanyaCity,
    fejerCountyCountyKislangCity,
    fejerCountyCountyLajoskomaromCity,
    fejerCountyCountyLepsenyCity,
    fejerCountyCountyLovasberenyCity,
    fejerCountyCountyManyCity,
    fejerCountyCountyMartonvasarCity,
    fejerCountyCountyMartonvasariJarasCity,
    fejerCountyCountyMezofalvaCity,
    fejerCountyCountyMezoszilasCity,
    fejerCountyCountyMorCity,
    fejerCountyCountyMoriJarasCity,
    fejerCountyCountyPakozdCity,
    fejerCountyCountyPazmandCity,
    fejerCountyCountyPerkataCity,
    fejerCountyCountyPolgardiCity,
    fejerCountyCountyPusztaszabolcsCity,
    fejerCountyCountyPusztavamCity,
    fejerCountyCountyRacalmasCity,
    fejerCountyCountyRackereszturCity,
    fejerCountyCountySarbogardCity,
    fejerCountyCountySarbogardiJarasCity,
    fejerCountyCountySarkereszturCity,
    fejerCountyCountySarosdCity,
    fejerCountyCountySarszentmihalyCity,
    fejerCountyCountySeregelyesCity,
    fejerCountyCountySoponyaCity,
    fejerCountyCountySzabadbattyanCity,
    fejerCountyCountySzarligetCity,
    fejerCountyCountySzekesfehervarCity,
    fejerCountyCountySzekesfehervariJarasCity,
    fejerCountyCountyValCity,
    fejerCountyCountyVelenceCity,
    fejerCountyCountyZamolyCity
  ]);

/// The `Győr` region in `Hungary`
const Region hungaryGyorCityWithCountyRights = Region(
  id: 1041,
  parentId: 99,
  longitude: 17.6503974,
  latitude: 47.6874569,
  name: "Győr",
  type: "city with county rights",
  stateCode: "GY",
  cities: []);

/// The `Győr-Moson-Sopron County` region in `Hungary`
const Region hungaryGyorHypmosonHypsopronCountyCounty = Region(
  id: 1042,
  parentId: 99,
  longitude: 17.2505883,
  latitude: 47.6509285,
  name: "Győr-Moson-Sopron County",
  type: "county",
  stateCode: "GS",
  cities: [
    gyorHypmosonHypsopronCountyCountyAbdaCity,
    gyorHypmosonHypsopronCountyCountyAgfalvaCity,
    gyorHypmosonHypsopronCountyCountyAsvanyraroCity,
    gyorHypmosonHypsopronCountyCountyBakonyszentlaszloCity,
    gyorHypmosonHypsopronCountyCountyBeledCity,
    gyorHypmosonHypsopronCountyCountyBonyCity,
    gyorHypmosonHypsopronCountyCountyBosarkanyCity,
    gyorHypmosonHypsopronCountyCountyCsornaCity,
    gyorHypmosonHypsopronCountyCountyCsornaiJarasCity,
    gyorHypmosonHypsopronCountyCountyFaradCity,
    gyorHypmosonHypsopronCountyCountyFertodCity,
    gyorHypmosonHypsopronCountyCountyFertorakosCity,
    gyorHypmosonHypsopronCountyCountyFertoszentmiklosCity,
    gyorHypmosonHypsopronCountyCountyGyorCity,
    gyorHypmosonHypsopronCountyCountyGyoriJarasCity,
    gyorHypmosonHypsopronCountyCountyGyorszemereCity,
    gyorHypmosonHypsopronCountyCountyGyorujbaratCity,
    gyorHypmosonHypsopronCountyCountyHalasziCity,
    gyorHypmosonHypsopronCountyCountyJanossomorjaCity,
    gyorHypmosonHypsopronCountyCountyKapuvarCity,
    gyorHypmosonHypsopronCountyCountyKapuvariJarasCity,
    gyorHypmosonHypsopronCountyCountyKimleCity,
    gyorHypmosonHypsopronCountyCountyKonyCity,
    gyorHypmosonHypsopronCountyCountyLebenyCity,
    gyorHypmosonHypsopronCountyCountyMihalyiCity,
    gyorHypmosonHypsopronCountyCountyMosonmagyarovarCity,
    gyorHypmosonHypsopronCountyCountyMosonmagyarovariJarasCity,
    gyorHypmosonHypsopronCountyCountyMosonszentmiklosCity,
    gyorHypmosonHypsopronCountyCountyNagycenkCity,
    gyorHypmosonHypsopronCountyCountyNyulCity,
    gyorHypmosonHypsopronCountyCountyOttevenyCity,
    gyorHypmosonHypsopronCountyCountyPannonhalmaCity,
    gyorHypmosonHypsopronCountyCountyPannonhalmiJarasCity,
    gyorHypmosonHypsopronCountyCountyPerCity,
    gyorHypmosonHypsopronCountyCountyRabapatonaCity,
    gyorHypmosonHypsopronCountyCountyRajkaCity,
    gyorHypmosonHypsopronCountyCountySopronCity,
    gyorHypmosonHypsopronCountyCountySoproniJarasCity,
    gyorHypmosonHypsopronCountyCountySzanyCity,
    gyorHypmosonHypsopronCountyCountyTetCity,
    gyorHypmosonHypsopronCountyCountyTetiJarasCity,
    gyorHypmosonHypsopronCountyCountyToltestavaCity
  ]);

/// The `Hajdú-Bihar County` region in `Hungary`
const Region hungaryHajduHypbiharCountyCounty = Region(
  id: 1063,
  parentId: 99,
  longitude: 21.5453227,
  latitude: 47.4688355,
  name: "Hajdú-Bihar County",
  type: "county",
  stateCode: "HB",
  cities: [
    hajduHypbiharCountyCountyBagamerCity,
    hajduHypbiharCountyCountyBalmazujvarosCity,
    hajduHypbiharCountyCountyBalmazujvarosiJarasCity,
    hajduHypbiharCountyCountyBarandCity,
    hajduHypbiharCountyCountyBerettyoujfaluCity,
    hajduHypbiharCountyCountyBerettyoujfaluiJarasCity,
    hajduHypbiharCountyCountyBiharkeresztesCity,
    hajduHypbiharCountyCountyBiharnagybajomCity,
    hajduHypbiharCountyCountyCsokmoCity,
    hajduHypbiharCountyCountyDebrecenCity,
    hajduHypbiharCountyCountyDebreceniJarasCity,
    hajduHypbiharCountyCountyDerecskeCity,
    hajduHypbiharCountyCountyDerecskeiJarasCity,
    hajduHypbiharCountyCountyEbesCity,
    hajduHypbiharCountyCountyEgyekCity,
    hajduHypbiharCountyCountyFoldesCity,
    hajduHypbiharCountyCountyGorbehazaCity,
    hajduHypbiharCountyCountyHadjuszoboszloiJarasCity,
    hajduHypbiharCountyCountyHajdubagosCity,
    hajduHypbiharCountyCountyHajduboszormenyCity,
    hajduHypbiharCountyCountyHajduboszormenyiJarasCity,
    hajduHypbiharCountyCountyHajdudorogCity,
    hajduHypbiharCountyCountyHajduhadhazCity,
    hajduHypbiharCountyCountyHajduhadhaziJarasCity,
    hajduHypbiharCountyCountyHajdunanasCity,
    hajduHypbiharCountyCountyHajdunanasiJarasCity,
    hajduHypbiharCountyCountyHajdusamsonCity,
    hajduHypbiharCountyCountyHajduszoboszloCity,
    hajduHypbiharCountyCountyHajduszovatCity,
    hajduHypbiharCountyCountyHortobagyCity,
    hajduHypbiharCountyCountyHosszupalyiCity,
    hajduHypbiharCountyCountyKabaCity,
    hajduHypbiharCountyCountyKomadiCity,
    hajduHypbiharCountyCountyKonyarCity,
    hajduHypbiharCountyCountyLetavertesCity,
    hajduHypbiharCountyCountyMikepercsCity,
    hajduHypbiharCountyCountyMonostorpalyiCity,
    hajduHypbiharCountyCountyNadudvarCity,
    hajduHypbiharCountyCountyNagyrabeCity,
    hajduHypbiharCountyCountyNyirabranyCity,
    hajduHypbiharCountyCountyNyiracsadCity,
    hajduHypbiharCountyCountyNyiradonyCity,
    hajduHypbiharCountyCountyNyiradonyiJarasCity,
    hajduHypbiharCountyCountyNyirmartonfalvaCity,
    hajduHypbiharCountyCountyPocsajCity,
    hajduHypbiharCountyCountyPolgarCity,
    hajduHypbiharCountyCountyPuspokladanyCity,
    hajduHypbiharCountyCountyPuspokladanyiJarasCity,
    hajduHypbiharCountyCountySarandCity,
    hajduHypbiharCountyCountySarretudvariCity,
    hajduHypbiharCountyCountyTeglasCity,
    hajduHypbiharCountyCountyTiszacsegeCity,
    hajduHypbiharCountyCountyVamospercsCity
  ]);

/// The `Heves County` region in `Hungary`
const Region hungaryHevesCountyCounty = Region(
  id: 1040,
  parentId: 99,
  longitude: 20.2038559,
  latitude: 47.8057617,
  name: "Heves County",
  type: "county",
  stateCode: "HE",
  cities: [
    hevesCountyCountyAbasarCity,
    hevesCountyCountyAdacsCity,
    hevesCountyCountyAndornaktalyaCity,
    hevesCountyCountyApcCity,
    hevesCountyCountyBelapatfalvaCity,
    hevesCountyCountyBelapatfalvaiJarasCity,
    hevesCountyCountyBesenyotelekCity,
    hevesCountyCountyBoldogCity,
    hevesCountyCountyCsanyCity,
    hevesCountyCountyDomoszloCity,
    hevesCountyCountyEcsedCity,
    hevesCountyCountyEgerCity,
    hevesCountyCountyEgerszalokCity,
    hevesCountyCountyEgriJarasCity,
    hevesCountyCountyErdotelekCity,
    hevesCountyCountyFelsotarkanyCity,
    hevesCountyCountyFuzesabonyCity,
    hevesCountyCountyFuzesabonyiJarasCity,
    hevesCountyCountyGyongyosCity,
    hevesCountyCountyGyongyoshalaszCity,
    hevesCountyCountyGyongyosiJarasCity,
    hevesCountyCountyGyongyospataCity,
    hevesCountyCountyGyongyossolymosCity,
    hevesCountyCountyGyongyostarjanCity,
    hevesCountyCountyHatvanCity,
    hevesCountyCountyHatvaniJarasCity,
    hevesCountyCountyHeredCity,
    hevesCountyCountyHevesCity,
    hevesCountyCountyHevesiJarasCity,
    hevesCountyCountyHortCity,
    hevesCountyCountyKalCity,
    hevesCountyCountyKaracsondCity,
    hevesCountyCountyKerecsendCity,
    hevesCountyCountyKiskoreCity,
    hevesCountyCountyKompoltCity,
    hevesCountyCountyLorinciCity,
    hevesCountyCountyMaklarCity,
    hevesCountyCountyMatraderecskeCity,
    hevesCountyCountyNagyredeCity,
    hevesCountyCountyOstorosCity,
    hevesCountyCountyParadCity,
    hevesCountyCountyParadsasvarCity,
    hevesCountyCountyPetervasaraCity,
    hevesCountyCountyPetervasaraiJarasCity,
    hevesCountyCountyPetofibanyaCity,
    hevesCountyCountyPoroszloCity,
    hevesCountyCountyRecskCity,
    hevesCountyCountyRozsaszentmartonCity,
    hevesCountyCountySirokCity,
    hevesCountyCountySzihalomCity,
    hevesCountyCountySzilvasvaradCity,
    hevesCountyCountyTarnaleleszCity,
    hevesCountyCountyTarnaorsCity,
    hevesCountyCountyTiszananaCity,
    hevesCountyCountyVamosgyorkCity,
    hevesCountyCountyVerpeletCity,
    hevesCountyCountyZagyvaszantoCity
  ]);

/// The `Hódmezővásárhely` region in `Hungary`
const Region hungaryHodmezovasarhelyCityWithCountyRights = Region(
  id: 1027,
  parentId: 99,
  longitude: 20.3300315,
  latitude: 46.4181262,
  name: "Hódmezővásárhely",
  type: "city with county rights",
  stateCode: "HV",
  cities: []);

/// The `Jász-Nagykun-Szolnok County` region in `Hungary`
const Region hungaryJaszHypnagykunHypszolnokCountyCounty = Region(
  id: 1043,
  parentId: 99,
  longitude: 20.5232456,
  latitude: 47.2555579,
  name: "Jász-Nagykun-Szolnok County",
  type: "county",
  stateCode: "JN",
  cities: [
    jaszHypnagykunHypszolnokCountyCountyAbadszalokCity,
    jaszHypnagykunHypszolnokCountyCountyAlattyanCity,
    jaszHypnagykunHypszolnokCountyCountyBesenyszogCity,
    jaszHypnagykunHypszolnokCountyCountyCibakhazaCity,
    jaszHypnagykunHypszolnokCountyCountyCserkeszoloCity,
    jaszHypnagykunHypszolnokCountyCountyFegyvernekCity,
    jaszHypnagykunHypszolnokCountyCountyJanoshidaCity,
    jaszHypnagykunHypszolnokCountyCountyJaszalsoszentgyorgyCity,
    jaszHypnagykunHypszolnokCountyCountyJaszapatiCity,
    jaszHypnagykunHypszolnokCountyCountyJaszapatiJarasCity,
    jaszHypnagykunHypszolnokCountyCountyJaszarokszallasCity,
    jaszHypnagykunHypszolnokCountyCountyJaszberenyCity,
    jaszHypnagykunHypszolnokCountyCountyJaszberenyiJarasCity,
    jaszHypnagykunHypszolnokCountyCountyJaszdozsaCity,
    jaszHypnagykunHypszolnokCountyCountyJaszjakohalmaCity,
    jaszHypnagykunHypszolnokCountyCountyJaszkiserCity,
    jaszHypnagykunHypszolnokCountyCountyJaszladanyCity,
    jaszHypnagykunHypszolnokCountyCountyJaszszentandrasCity,
    jaszHypnagykunHypszolnokCountyCountyKarcagCity,
    jaszHypnagykunHypszolnokCountyCountyKarcagiJarasCity,
    jaszHypnagykunHypszolnokCountyCountyKenderesCity,
    jaszHypnagykunHypszolnokCountyCountyKengyelCity,
    jaszHypnagykunHypszolnokCountyCountyKisujszallasCity,
    jaszHypnagykunHypszolnokCountyCountyKunhegyesCity,
    jaszHypnagykunHypszolnokCountyCountyKunhegyesiJarasCity,
    jaszHypnagykunHypszolnokCountyCountyKunmadarasCity,
    jaszHypnagykunHypszolnokCountyCountyKunszentmartonCity,
    jaszHypnagykunHypszolnokCountyCountyKunszentmartoniJarasCity,
    jaszHypnagykunHypszolnokCountyCountyMezoturCity,
    jaszHypnagykunHypszolnokCountyCountyMezoturiJarasCity,
    jaszHypnagykunHypszolnokCountyCountyOcsodCity,
    jaszHypnagykunHypszolnokCountyCountyRakoczifalvaCity,
    jaszHypnagykunHypszolnokCountyCountyRakocziujfaluCity,
    jaszHypnagykunHypszolnokCountyCountySzajolCity,
    jaszHypnagykunHypszolnokCountyCountySzelevenyCity,
    jaszHypnagykunHypszolnokCountyCountySzolnokCity,
    jaszHypnagykunHypszolnokCountyCountySzolnokiJarasCity,
    jaszHypnagykunHypszolnokCountyCountyTiszaboCity,
    jaszHypnagykunHypszolnokCountyCountyTiszaburaCity,
    jaszHypnagykunHypszolnokCountyCountyTiszafoldvarCity,
    jaszHypnagykunHypszolnokCountyCountyTiszafuredCity,
    jaszHypnagykunHypszolnokCountyCountyTiszafurediJarasCity,
    jaszHypnagykunHypszolnokCountyCountyTiszapuspokiCity,
    jaszHypnagykunHypszolnokCountyCountyTiszaroffCity,
    jaszHypnagykunHypszolnokCountyCountyTiszasulyCity,
    jaszHypnagykunHypszolnokCountyCountyTiszaszentimreCity,
    jaszHypnagykunHypszolnokCountyCountyTiszaszolosCity,
    jaszHypnagykunHypszolnokCountyCountyTorokszentmiklosCity,
    jaszHypnagykunHypszolnokCountyCountyTorokszentmiklosiJarasCity,
    jaszHypnagykunHypszolnokCountyCountyToszegCity,
    jaszHypnagykunHypszolnokCountyCountyTurkeveCity,
    jaszHypnagykunHypszolnokCountyCountyUjszaszCity,
    jaszHypnagykunHypszolnokCountyCountyZagyvarekasCity
  ]);

/// The `Kaposvár` region in `Hungary`
const Region hungaryKaposvarCityWithCountyRights = Region(
  id: 1067,
  parentId: 99,
  longitude: 17.7967639,
  latitude: 46.3593606,
  name: "Kaposvár",
  type: "city with county rights",
  stateCode: "KV",
  cities: []);

/// The `Kecskemét` region in `Hungary`
const Region hungaryKecskemetCityWithCountyRights = Region(
  id: 1056,
  parentId: 99,
  longitude: 19.6896861,
  latitude: 46.8963711,
  name: "Kecskemét",
  type: "city with county rights",
  stateCode: "KM",
  cities: []);

/// The `Komárom-Esztergom` region in `Hungary`
const Region hungaryKomaromHypesztergomCounty = Region(
  id: 5085,
  parentId: 99,
  longitude: 18.1256855,
  latitude: 47.5779786,
  name: "Komárom-Esztergom",
  type: "county",
  stateCode: "KE",
  cities: [
    komaromHypesztergomCountyAcsCity,
    komaromHypesztergomCountyAkaCity,
    komaromHypesztergomCountyAlmasfuzitoCity,
    komaromHypesztergomCountyAszarCity,
    komaromHypesztergomCountyBabolnaCity,
    komaromHypesztergomCountyBajotCity,
    komaromHypesztergomCountyBakonybankCity,
    komaromHypesztergomCountyBakonysarkanyCity,
    komaromHypesztergomCountyBakonyszombathelyCity,
    komaromHypesztergomCountyBanaCity,
    komaromHypesztergomCountyBanhidaCity,
    komaromHypesztergomCountyBarsonyosCity,
    komaromHypesztergomCountyCsaszarCity,
    komaromHypesztergomCountyCsatkaCity,
    komaromHypesztergomCountyCsemCity,
    komaromHypesztergomCountyCsepCity,
    komaromHypesztergomCountyCsolnokCity,
    komaromHypesztergomCountyDadCity,
    komaromHypesztergomCountyDagCity,
    komaromHypesztergomCountyDomosCity,
    komaromHypesztergomCountyDorogCity,
    komaromHypesztergomCountyDunaalmasCity,
    komaromHypesztergomCountyDunaszentmiklosCity,
    komaromHypesztergomCountyEpolCity,
    komaromHypesztergomCountyEsztergomCity,
    komaromHypesztergomCountyEteCity,
    komaromHypesztergomCountyGyermelyCity,
    komaromHypesztergomCountyHeregCity,
    komaromHypesztergomCountyKecskedCity,
    komaromHypesztergomCountyKerektelekiCity,
    komaromHypesztergomCountyKesztolcCity,
    komaromHypesztergomCountyKisberCity,
    komaromHypesztergomCountyKisigmandCity,
    komaromHypesztergomCountyKocsCity,
    komaromHypesztergomCountyKomaromCity,
    komaromHypesztergomCountyKomlodCity,
    komaromHypesztergomCountyKornyeCity,
    komaromHypesztergomCountyLabatlanCity,
    komaromHypesztergomCountyLeanyvarCity,
    komaromHypesztergomCountyMariahalomCity,
    komaromHypesztergomCountyMocsaCity,
    komaromHypesztergomCountyMogyorosbanyaCity,
    komaromHypesztergomCountyNagyigmandCity,
    komaromHypesztergomCountyNagysapCity,
    komaromHypesztergomCountyNaszalyCity,
    komaromHypesztergomCountyNeszmelyCity,
    komaromHypesztergomCountyNyergesujfaluCity,
    komaromHypesztergomCountyOroszlanyCity,
    komaromHypesztergomCountyPiliscsevCity,
    komaromHypesztergomCountyPilismarotCity,
    komaromHypesztergomCountyRedeCity,
    komaromHypesztergomCountySarisapCity,
    komaromHypesztergomCountySurCity,
    komaromHypesztergomCountySuttoCity,
    komaromHypesztergomCountySzakszendCity,
    komaromHypesztergomCountySzomodCity,
    komaromHypesztergomCountySzomorCity,
    komaromHypesztergomCountySzonyCity,
    komaromHypesztergomCountyTardosCity,
    komaromHypesztergomCountyTarjanCity,
    komaromHypesztergomCountyTarkanyCity,
    komaromHypesztergomCountyTatabanyaCity,
    komaromHypesztergomCountyTokodaltaroCity,
    komaromHypesztergomCountyUnyCity,
    komaromHypesztergomCountyVargesztesCity,
    komaromHypesztergomCountyVerteskethelyCity,
    komaromHypesztergomCountyVertessomloCity,
    komaromHypesztergomCountyVertesszolosCity,
    komaromHypesztergomCountyVertestolnaCity
  ]);

/// The `Miskolc` region in `Hungary`
const Region hungaryMiskolcCityWithCountyRights = Region(
  id: 1065,
  parentId: 99,
  longitude: 20.7784384,
  latitude: 48.1034775,
  name: "Miskolc",
  type: "city with county rights",
  stateCode: "MI",
  cities: []);

/// The `Nagykanizsa` region in `Hungary`
const Region hungaryNagykanizsaCityWithCountyRights = Region(
  id: 1030,
  parentId: 99,
  longitude: 16.9896796,
  latitude: 46.4590218,
  name: "Nagykanizsa",
  type: "city with county rights",
  stateCode: "NK",
  cities: []);

/// The `Nógrád County` region in `Hungary`
const Region hungaryNogradCountyCounty = Region(
  id: 1051,
  parentId: 99,
  longitude: 19.0498504,
  latitude: 47.9041031,
  name: "Nógrád County",
  type: "county",
  stateCode: "NO",
  cities: [
    nogradCountyCountyBalassagyarmatCity,
    nogradCountyCountyBalassagyarmatiJarasCity,
    nogradCountyCountyBatonyterenyeCity,
    nogradCountyCountyBatonyterenyeiJarasCity,
    nogradCountyCountyBercelCity,
    nogradCountyCountyBujakCity,
    nogradCountyCountyDiosjenoCity,
    nogradCountyCountyErsekvadkertCity,
    nogradCountyCountyHehalomCity,
    nogradCountyCountyJobbagyiCity,
    nogradCountyCountyKarancskesziCity,
    nogradCountyCountyKarancslapujtoCity,
    nogradCountyCountyKazarCity,
    nogradCountyCountyMatranovakCity,
    nogradCountyCountyMatraterenyeCity,
    nogradCountyCountyMatraverebelyCity,
    nogradCountyCountyNagyorosziCity,
    nogradCountyCountyPalotasCity,
    nogradCountyCountyPasztoCity,
    nogradCountyCountyPasztoiJarasCity,
    nogradCountyCountyRetsagCity,
    nogradCountyCountyRetsagiJarasCity,
    nogradCountyCountyRimocCity,
    nogradCountyCountyRomhanyCity,
    nogradCountyCountySalgotarjanCity,
    nogradCountyCountySalgotarjaniJarasCity,
    nogradCountyCountySomoskoujfaluCity,
    nogradCountyCountySzecsenyCity,
    nogradCountyCountySzecsenyiJarasCity,
    nogradCountyCountySzurdokpuspokiCity,
    nogradCountyCountyTarCity
  ]);

/// The `Nyíregyháza` region in `Hungary`
const Region hungaryNyiregyhazaCityWithCountyRights = Region(
  id: 1034,
  parentId: 99,
  longitude: 21.7244053,
  latitude: 47.9495324,
  name: "Nyíregyháza",
  type: "city with county rights",
  stateCode: "NY",
  cities: []);

/// The `Pécs` region in `Hungary`
const Region hungaryPecsCityWithCountyRights = Region(
  id: 1053,
  parentId: 99,
  longitude: 18.232266,
  latitude: 46.0727345,
  name: "Pécs",
  type: "city with county rights",
  stateCode: "PS",
  cities: []);

/// The `Pest County` region in `Hungary`
const Region hungaryPestCountyCounty = Region(
  id: 1059,
  parentId: 99,
  longitude: 19.4618128,
  latitude: 47.4480001,
  name: "Pest County",
  type: "county",
  stateCode: "PE",
  cities: [
    pestCountyCountyAbonyCity,
    pestCountyCountyAcsaCity,
    pestCountyCountyAlbertirsaCity,
    pestCountyCountyAlsonemediCity,
    pestCountyCountyAszodCity,
    pestCountyCountyAszodiJarasCity,
    pestCountyCountyBagCity,
    pestCountyCountyBiatorbagyCity,
    pestCountyCountyBudakalaszCity,
    pestCountyCountyBudakesziCity,
    pestCountyCountyBudakesziJarasCity,
    pestCountyCountyBudaorsCity,
    pestCountyCountyBugyiCity,
    pestCountyCountyCegledCity,
    pestCountyCountyCegledbercelCity,
    pestCountyCountyCeglediJarasCity,
    pestCountyCountyCsemoCity,
    pestCountyCountyCsobankaCity,
    pestCountyCountyCsomorCity,
    pestCountyCountyDabasCity,
    pestCountyCountyDabasiJarasCity,
    pestCountyCountyDanszentmiklosCity,
    pestCountyCountyDanyCity,
    pestCountyCountyDelegyhazaCity,
    pestCountyCountyDiosdCity,
    pestCountyCountyDomonyCity,
    pestCountyCountyDomsodCity,
    pestCountyCountyDunabogdanyCity,
    pestCountyCountyDunaharasztiCity,
    pestCountyCountyDunakesziCity,
    pestCountyCountyDunakesziJarasCity,
    pestCountyCountyDunavarsanyCity,
    pestCountyCountyEcserCity,
    pestCountyCountyErdCity,
    pestCountyCountyErdiJarasCity,
    pestCountyCountyErdokertesCity,
    pestCountyCountyFarmosCity,
    pestCountyCountyFelsopakonyCity,
    pestCountyCountyForropusztaCity,
    pestCountyCountyFotCity,
    pestCountyCountyGalgahevizCity,
    pestCountyCountyGalgamacsaCity,
    pestCountyCountyGodCity,
    pestCountyCountyGodolloCity,
    pestCountyCountyGodolloiJarasCity,
    pestCountyCountyGombaCity,
    pestCountyCountyGyalCity,
    pestCountyCountyGyaliJarasCity,
    pestCountyCountyGyomroCity,
    pestCountyCountyHalasztelekCity,
    pestCountyCountyHernadCity,
    pestCountyCountyHevizgyorkCity,
    pestCountyCountyIkladCity,
    pestCountyCountyInarcsCity,
    pestCountyCountyIsaszegCity,
    pestCountyCountyJaszkarajenoCity,
    pestCountyCountyKakucsCity,
    pestCountyCountyKartalCity,
    pestCountyCountyKerepesCity,
    pestCountyCountyKiskunlachazaCity,
    pestCountyCountyKismarosCity,
    pestCountyCountyKistarcsaCity,
    pestCountyCountyKocserCity,
    pestCountyCountyKokaCity,
    pestCountyCountyKosdCity,
    pestCountyCountyLeanyfaluCity,
    pestCountyCountyMaglodCity,
    pestCountyCountyMendeCity,
    pestCountyCountyMogyorodCity,
    pestCountyCountyMonorCity,
    pestCountyCountyMonoriJarasCity,
    pestCountyCountyNagykataCity,
    pestCountyCountyNagykataiJarasCity,
    pestCountyCountyNagykorosCity,
    pestCountyCountyNagykorosiJarasCity,
    pestCountyCountyNagykovacsiCity,
    pestCountyCountyNagymarosCity,
    pestCountyCountyNagytarcsaCity,
    pestCountyCountyNyaregyhazaCity,
    pestCountyCountyOcsaCity,
    pestCountyCountyOrbottyanCity,
    pestCountyCountyOrkenyCity,
    pestCountyCountyPandCity,
    pestCountyCountyPatyCity,
    pestCountyCountyPecelCity,
    pestCountyCountyPerbalCity,
    pestCountyCountyPeteriCity,
    pestCountyCountyPilisCity,
    pestCountyCountyPilisborosjenoCity,
    pestCountyCountyPiliscsabaCity,
    pestCountyCountyPilisszantoCity,
    pestCountyCountyPilisszentivanCity,
    pestCountyCountyPilisszentkeresztCity,
    pestCountyCountyPilisvorosvarCity,
    pestCountyCountyPilisvorosvariJarasCity,
    pestCountyCountyPomazCity,
    pestCountyCountyRackeveCity,
    pestCountyCountyRackeveiJarasCity,
    pestCountyCountySolymarCity,
    pestCountyCountySoskutCity,
    pestCountyCountySulysapCity,
    pestCountyCountySzadaCity,
    pestCountyCountySzazhalombattaCity,
    pestCountyCountySzentendreCity,
    pestCountyCountySzentendreiJarasCity,
    pestCountyCountySzentlorinckataCity,
    pestCountyCountySzentmartonkataCity,
    pestCountyCountySzigetcsepCity,
    pestCountyCountySzigethalomCity,
    pestCountyCountySzigetszentmiklosCity,
    pestCountyCountySzigetszentmiklosiJarasCity,
    pestCountyCountySzigetujfaluCity,
    pestCountyCountySzobCity,
    pestCountyCountySzobiJarasCity,
    pestCountyCountySzodCity,
    pestCountyCountySzodligetCity,
    pestCountyCountyTaborfalvaCity,
    pestCountyCountyTahitotfaluCity,
    pestCountyCountyTaksonyCity,
    pestCountyCountyTapiobicskeCity,
    pestCountyCountyTapiogyorgyeCity,
    pestCountyCountyTapiosagCity,
    pestCountyCountyTapioszecsoCity,
    pestCountyCountyTapioszeleCity,
    pestCountyCountyTapioszentmartonCity,
    pestCountyCountyTapioszolosCity,
    pestCountyCountyTarnokCity,
    pestCountyCountyTelkiCity,
    pestCountyCountyToalmasCity,
    pestCountyCountyTokolCity,
    pestCountyCountyTorokbalintCity,
    pestCountyCountyTortelCity,
    pestCountyCountyTuraCity,
    pestCountyCountyUjhartyanCity,
    pestCountyCountyUjszilvasCity,
    pestCountyCountyUlloCity,
    pestCountyCountyUriCity,
    pestCountyCountyUromCity,
    pestCountyCountyVacCity,
    pestCountyCountyVaciJarasCity,
    pestCountyCountyVacszentlaszloCity,
    pestCountyCountyValkoCity,
    pestCountyCountyVecsesCity,
    pestCountyCountyVecsesiJarasCity,
    pestCountyCountyVeresegyhazCity,
    pestCountyCountyVeroceCity,
    pestCountyCountyVisegradCity,
    pestCountyCountyZsambekCity,
    pestCountyCountyZsambokCity
  ]);

/// The `Salgótarján` region in `Hungary`
const Region hungarySalgotarjanCityWithCountyRights = Region(
  id: 1068,
  parentId: 99,
  longitude: 19.7999813,
  latitude: 48.0935237,
  name: "Salgótarján",
  type: "city with county rights",
  stateCode: "ST",
  cities: []);

/// The `Somogy County` region in `Hungary`
const Region hungarySomogyCountyCounty = Region(
  id: 1035,
  parentId: 99,
  longitude: 17.5866732,
  latitude: 46.554859,
  name: "Somogy County",
  type: "county",
  stateCode: "SO",
  cities: [
    somogyCountyCountyAdandCity,
    somogyCountyCountyBabocsaCity,
    somogyCountyCountyBalatonberenyCity,
    somogyCountyCountyBalatonboglarCity,
    somogyCountyCountyBalatonfenyvesCity,
    somogyCountyCountyBalatonfoldvarCity,
    somogyCountyCountyBalatonlelleCity,
    somogyCountyCountyBalatonszabadiCity,
    somogyCountyCountyBalatonszarszoCity,
    somogyCountyCountyBarcsCity,
    somogyCountyCountyBarcsiJarasCity,
    somogyCountyCountyBerzenceCity,
    somogyCountyCountyBohonyeCity,
    somogyCountyCountyCsurgoCity,
    somogyCountyCountyCsurgoiJarasCity,
    somogyCountyCountyFonyodCity,
    somogyCountyCountyFonyodiJarasCity,
    somogyCountyCountyKadarkutCity,
    somogyCountyCountyKaposmeroCity,
    somogyCountyCountyKaposvarCity,
    somogyCountyCountyKaposvariJarasCity,
    somogyCountyCountyKaradCity,
    somogyCountyCountyKethelyCity,
    somogyCountyCountyLabodCity,
    somogyCountyCountyLengyeltotiCity,
    somogyCountyCountyMarcaliCity,
    somogyCountyCountyMarcaliJarasCity,
    somogyCountyCountyNagyatadCity,
    somogyCountyCountyNagyatadiJarasCity,
    somogyCountyCountyNagybajomCity,
    somogyCountyCountySegesdCity,
    somogyCountyCountySiofokCity,
    somogyCountyCountySiofokiJarasCity,
    somogyCountyCountySomogyvarCity,
    somogyCountyCountyTabCity,
    somogyCountyCountyTabiJarasCity,
    somogyCountyCountyTaszarCity,
    somogyCountyCountyZamardiCity
  ]);

/// The `Sopron` region in `Hungary`
const Region hungarySopronCityWithCountyRights = Region(
  id: 1057,
  parentId: 99,
  longitude: 16.5844795,
  latitude: 47.6816619,
  name: "Sopron",
  type: "city with county rights",
  stateCode: "SN",
  cities: []);

/// The `Szabolcs-Szatmár-Bereg County` region in `Hungary`
const Region hungarySzabolcsHypszatmarHypberegCountyCounty = Region(
  id: 1045,
  parentId: 99,
  longitude: 22.00333,
  latitude: 48.0394954,
  name: "Szabolcs-Szatmár-Bereg County",
  type: "county",
  stateCode: "SZ",
  cities: [
    szabolcsHypszatmarHypberegCountyCountyAjakCity,
    szabolcsHypszatmarHypberegCountyCountyAnarcsCity,
    szabolcsHypszatmarHypberegCountyCountyApagyCity,
    szabolcsHypszatmarHypberegCountyCountyAranyosapatiCity,
    szabolcsHypszatmarHypberegCountyCountyBaktaloranthazaCity,
    szabolcsHypszatmarHypberegCountyCountyBaktaloranthazaiJarasCity,
    szabolcsHypszatmarHypberegCountyCountyBalkanyCity,
    szabolcsHypszatmarHypberegCountyCountyBokonyCity,
    szabolcsHypszatmarHypberegCountyCountyBujCity,
    szabolcsHypszatmarHypberegCountyCountyCsengerCity,
    szabolcsHypszatmarHypberegCountyCountyCsengeriJarasCity,
    szabolcsHypszatmarHypberegCountyCountyDemecserCity,
    szabolcsHypszatmarHypberegCountyCountyDogeCity,
    szabolcsHypszatmarHypberegCountyCountyDombradCity,
    szabolcsHypszatmarHypberegCountyCountyEncsencsCity,
    szabolcsHypszatmarHypberegCountyCountyFehergyarmatCity,
    szabolcsHypszatmarHypberegCountyCountyFehergyarmatiJarasCity,
    szabolcsHypszatmarHypberegCountyCountyFenyeslitkeCity,
    szabolcsHypszatmarHypberegCountyCountyGegenyCity,
    szabolcsHypszatmarHypberegCountyCountyGyulahazaCity,
    szabolcsHypszatmarHypberegCountyCountyHodaszCity,
    szabolcsHypszatmarHypberegCountyCountyIbranyCity,
    szabolcsHypszatmarHypberegCountyCountyIbranyiJarasCity,
    szabolcsHypszatmarHypberegCountyCountyKallosemjenCity,
    szabolcsHypszatmarHypberegCountyCountyKalmanhazaCity,
    szabolcsHypszatmarHypberegCountyCountyKantorjanosiCity,
    szabolcsHypszatmarHypberegCountyCountyKekCity,
    szabolcsHypszatmarHypberegCountyCountyKemecseCity,
    szabolcsHypszatmarHypberegCountyCountyKemecseiJarasCity,
    szabolcsHypszatmarHypberegCountyCountyKisletaCity,
    szabolcsHypszatmarHypberegCountyCountyKisvardaCity,
    szabolcsHypszatmarHypberegCountyCountyKisvardaiJarasCity,
    szabolcsHypszatmarHypberegCountyCountyKocsordCity,
    szabolcsHypszatmarHypberegCountyCountyKotajCity,
    szabolcsHypszatmarHypberegCountyCountyLevelekCity,
    szabolcsHypszatmarHypberegCountyCountyMandokCity,
    szabolcsHypszatmarHypberegCountyCountyMariapocsCity,
    szabolcsHypszatmarHypberegCountyCountyMateszalkaCity,
    szabolcsHypszatmarHypberegCountyCountyMateszalkaiJarasCity,
    szabolcsHypszatmarHypberegCountyCountyMerkCity,
    szabolcsHypszatmarHypberegCountyCountyNagycserkeszCity,
    szabolcsHypszatmarHypberegCountyCountyNagydobosCity,
    szabolcsHypszatmarHypberegCountyCountyNagyecsedCity,
    szabolcsHypszatmarHypberegCountyCountyNagyhalaszCity,
    szabolcsHypszatmarHypberegCountyCountyNagykalloCity,
    szabolcsHypszatmarHypberegCountyCountyNagykalloiJarasCity,
    szabolcsHypszatmarHypberegCountyCountyNapkorCity,
    szabolcsHypszatmarHypberegCountyCountyNyirbatorCity,
    szabolcsHypszatmarHypberegCountyCountyNyirbatoriJarasCity,
    szabolcsHypszatmarHypberegCountyCountyNyirbeltekCity,
    szabolcsHypszatmarHypberegCountyCountyNyirbogatCity,
    szabolcsHypszatmarHypberegCountyCountyNyirbogdanyCity,
    szabolcsHypszatmarHypberegCountyCountyNyircsaholyCity,
    szabolcsHypszatmarHypberegCountyCountyNyiregyhazaCity,
    szabolcsHypszatmarHypberegCountyCountyNyiregyhaziJarasCity,
    szabolcsHypszatmarHypberegCountyCountyNyirgyulajCity,
    szabolcsHypszatmarHypberegCountyCountyNyirkaraszCity,
    szabolcsHypszatmarHypberegCountyCountyNyirlugosCity,
    szabolcsHypszatmarHypberegCountyCountyNyirmadaCity,
    szabolcsHypszatmarHypberegCountyCountyNyirmeggyesCity,
    szabolcsHypszatmarHypberegCountyCountyNyirmihalydiCity,
    szabolcsHypszatmarHypberegCountyCountyNyirpazonyCity,
    szabolcsHypszatmarHypberegCountyCountyNyirtassCity,
    szabolcsHypszatmarHypberegCountyCountyNyirtelekCity,
    szabolcsHypszatmarHypberegCountyCountyNyirvasvariCity,
    szabolcsHypszatmarHypberegCountyCountyOfehertoCity,
    szabolcsHypszatmarHypberegCountyCountyOkoritofulposCity,
    szabolcsHypszatmarHypberegCountyCountyOpalyiCity,
    szabolcsHypszatmarHypberegCountyCountyPatrohaCity,
    szabolcsHypszatmarHypberegCountyCountyPetnehazaCity,
    szabolcsHypszatmarHypberegCountyCountyPorcsalmaCity,
    szabolcsHypszatmarHypberegCountyCountyRakamazCity,
    szabolcsHypszatmarHypberegCountyCountySzakolyCity,
    szabolcsHypszatmarHypberegCountyCountySzamosszegCity,
    szabolcsHypszatmarHypberegCountyCountyTarpaCity,
    szabolcsHypszatmarHypberegCountyCountyTiszabercelCity,
    szabolcsHypszatmarHypberegCountyCountyTiszabezdedCity,
    szabolcsHypszatmarHypberegCountyCountyTiszadadaCity,
    szabolcsHypszatmarHypberegCountyCountyTiszadobCity,
    szabolcsHypszatmarHypberegCountyCountyTiszaeszlarCity,
    szabolcsHypszatmarHypberegCountyCountyTiszalokCity,
    szabolcsHypszatmarHypberegCountyCountyTiszanagyfaluCity,
    szabolcsHypszatmarHypberegCountyCountyTiszavasvariCity,
    szabolcsHypszatmarHypberegCountyCountyTiszavasvariJarasCity,
    szabolcsHypszatmarHypberegCountyCountyTornyospalcaCity,
    szabolcsHypszatmarHypberegCountyCountyTunyogmatolcsCity,
    szabolcsHypszatmarHypberegCountyCountyTuzserCity,
    szabolcsHypszatmarHypberegCountyCountyTyukodCity,
    szabolcsHypszatmarHypberegCountyCountyUjfehertoCity,
    szabolcsHypszatmarHypberegCountyCountyVajaCity,
    szabolcsHypszatmarHypberegCountyCountyVasarosnamenyCity,
    szabolcsHypszatmarHypberegCountyCountyVasarosnamenyiJarasCity,
    szabolcsHypszatmarHypberegCountyCountyZahonyCity,
    szabolcsHypszatmarHypberegCountyCountyZahonyiJarasCity
  ]);

/// The `Szeged` region in `Hungary`
const Region hungarySzegedCityWithCountyRights = Region(
  id: 1029,
  parentId: 99,
  longitude: 20.1414253,
  latitude: 46.2530102,
  name: "Szeged",
  type: "city with county rights",
  stateCode: "SD",
  cities: []);

/// The `Székesfehérvár` region in `Hungary`
const Region hungarySzekesfehervarCityWithCountyRights = Region(
  id: 1033,
  parentId: 99,
  longitude: 18.4221358,
  latitude: 47.1860262,
  name: "Székesfehérvár",
  type: "city with county rights",
  stateCode: "SF",
  cities: []);

/// The `Szekszárd` region in `Hungary`
const Region hungarySzekszardCityWithCountyRights = Region(
  id: 1061,
  parentId: 99,
  longitude: 18.7062293,
  latitude: 46.3474326,
  name: "Szekszárd",
  type: "city with county rights",
  stateCode: "SS",
  cities: []);

/// The `Szolnok` region in `Hungary`
const Region hungarySzolnokCityWithCountyRights = Region(
  id: 1047,
  parentId: 99,
  longitude: 20.1824712,
  latitude: 47.1621355,
  name: "Szolnok",
  type: "city with county rights",
  stateCode: "SK",
  cities: []);

/// The `Szombathely` region in `Hungary`
const Region hungarySzombathelyCityWithCountyRights = Region(
  id: 1052,
  parentId: 99,
  longitude: 16.6218441,
  latitude: 47.2306851,
  name: "Szombathely",
  type: "city with county rights",
  stateCode: "SH",
  cities: []);

/// The `Tatabánya` region in `Hungary`
const Region hungaryTatabanyaCityWithCountyRights = Region(
  id: 1066,
  parentId: 99,
  longitude: 18.404818,
  latitude: 47.569246,
  name: "Tatabánya",
  type: "city with county rights",
  stateCode: "TB",
  cities: []);

/// The `Tolna County` region in `Hungary`
const Region hungaryTolnaCountyCounty = Region(
  id: 1038,
  parentId: 99,
  longitude: 18.5570627,
  latitude: 46.4762754,
  name: "Tolna County",
  type: "county",
  stateCode: "TO",
  cities: [
    tolnaCountyCountyBataCity,
    tolnaCountyCountyBataszekCity,
    tolnaCountyCountyBogyiszloCity,
    tolnaCountyCountyBolcskeCity,
    tolnaCountyCountyBonyhadCity,
    tolnaCountyCountyBonyhadiJarasCity,
    tolnaCountyCountyDecsCity,
    tolnaCountyCountyDobrokozCity,
    tolnaCountyCountyDombovarCity,
    tolnaCountyCountyDombovariJarasCity,
    tolnaCountyCountyDunafoldvarCity,
    tolnaCountyCountyDunaszentgyorgyCity,
    tolnaCountyCountyFaddCity,
    tolnaCountyCountyGyonkCity,
    tolnaCountyCountyHogyeszCity,
    tolnaCountyCountyIregszemcseCity,
    tolnaCountyCountyMadocsaCity,
    tolnaCountyCountyNagydorogCity,
    tolnaCountyCountyNagymanyokCity,
    tolnaCountyCountyNemetkerCity,
    tolnaCountyCountyOcsenyCity,
    tolnaCountyCountyOzoraCity,
    tolnaCountyCountyPaksCity,
    tolnaCountyCountyPaksiJarasCity,
    tolnaCountyCountyPincehelyCity,
    tolnaCountyCountySimontornyaCity,
    tolnaCountyCountySzedresCity,
    tolnaCountyCountySzekszardCity,
    tolnaCountyCountySzekszardiJarasCity,
    tolnaCountyCountySzentgalpusztaCity,
    tolnaCountyCountyTamasiCity,
    tolnaCountyCountyTamasiJarasCity,
    tolnaCountyCountyTengelicCity,
    tolnaCountyCountyTolnaCity,
    tolnaCountyCountyTolnaiJarasCity,
    tolnaCountyCountyZombaCity
  ]);

/// The `Vas County` region in `Hungary`
const Region hungaryVasCountyCounty = Region(
  id: 1039,
  parentId: 99,
  longitude: 16.6812183,
  latitude: 47.0929111,
  name: "Vas County",
  type: "county",
  stateCode: "VA",
  cities: [
    vasCountyCountyBukCity,
    vasCountyCountyCelldomolkCity,
    vasCountyCountyCelldomolkiJarasCity,
    vasCountyCountyCsepregCity,
    vasCountyCountyGencsapatiCity,
    vasCountyCountyJakCity,
    vasCountyCountyJanoshazaCity,
    vasCountyCountyKormendCity,
    vasCountyCountyKormendiJarasCity,
    vasCountyCountyKoszegCity,
    vasCountyCountyKoszegiJarasCity,
    vasCountyCountyRepcelakCity,
    vasCountyCountySarvarCity,
    vasCountyCountySarvariJarasCity,
    vasCountyCountySzentgotthardCity,
    vasCountyCountySzentgotthardiJarasCity,
    vasCountyCountySzombathelyCity,
    vasCountyCountySzombathelyiJarasCity,
    vasCountyCountyTaplanszentkeresztCity,
    vasCountyCountyVasvarCity,
    vasCountyCountyVasvariJarasCity,
    vasCountyCountyVepCity
  ]);

/// The `Veszprém` region in `Hungary`
const Region hungaryVeszpremCityWithCountyRights = Region(
  id: 1062,
  parentId: 99,
  longitude: 17.9093019,
  latitude: 47.1028087,
  name: "Veszprém",
  type: "city with county rights",
  stateCode: "VM",
  cities: []);

/// The `Veszprém County` region in `Hungary`
const Region hungaryVeszpremCountyCounty = Region(
  id: 1054,
  parentId: 99,
  longitude: 17.9100763,
  latitude: 47.0930974,
  name: "Veszprém County",
  type: "county",
  stateCode: "VE",
  cities: [
    veszpremCountyCountyAjkaCity,
    veszpremCountyCountyAjkaiJarasCity,
    veszpremCountyCountyBadacsonytomajCity,
    veszpremCountyCountyBalatonalmadiCity,
    veszpremCountyCountyBalatonalmadiJarasCity,
    veszpremCountyCountyBalatonfuredCity,
    veszpremCountyCountyBalatonfurediJarasCity,
    veszpremCountyCountyBalatonkeneseCity,
    veszpremCountyCountyBerhidaCity,
    veszpremCountyCountyCsabrendekCity,
    veszpremCountyCountyCsetenyCity,
    veszpremCountyCountyCsopakCity,
    veszpremCountyCountyDevecserCity,
    veszpremCountyCountyDevecseriJarasCity,
    veszpremCountyCountyHajmaskerCity,
    veszpremCountyCountyHerendCity,
    veszpremCountyCountyLiterCity,
    veszpremCountyCountyNemesvamosCity,
    veszpremCountyCountyOsiCity,
    veszpremCountyCountyPapaCity,
    veszpremCountyCountyPapaiJarasCity,
    veszpremCountyCountyPetfurdoCity,
    veszpremCountyCountyRevfulopCity,
    veszpremCountyCountySumegCity,
    veszpremCountyCountySumegiJarasCity,
    veszpremCountyCountySzentkiralyszabadjaCity,
    veszpremCountyCountyTapolcaCity,
    veszpremCountyCountyTapolcaiJarasCity,
    veszpremCountyCountyTihanyCity,
    veszpremCountyCountyUrkutCity,
    veszpremCountyCountyVarpalotaCity,
    veszpremCountyCountyVarpalotaiJarasCity,
    veszpremCountyCountyVeszpremCity,
    veszpremCountyCountyVeszpremiJarasCity,
    veszpremCountyCountyZankaCity,
    veszpremCountyCountyZircCity,
    veszpremCountyCountyZirciJarasCity
  ]);

/// The `Zala County` region in `Hungary`
const Region hungaryZalaCountyCounty = Region(
  id: 1046,
  parentId: 99,
  longitude: 16.9152252,
  latitude: 46.7384404,
  name: "Zala County",
  type: "county",
  stateCode: "ZA",
  cities: [
    zalaCountyCountyBecsehelyCity,
    zalaCountyCountyCserszegtomajCity,
    zalaCountyCountyGyenesdiasCity,
    zalaCountyCountyHevizCity,
    zalaCountyCountyKeszthelyCity,
    zalaCountyCountyKeszthelyiJarasCity,
    zalaCountyCountyLentiCity,
    zalaCountyCountyLentiJarasCity,
    zalaCountyCountyLetenyeCity,
    zalaCountyCountyLetenyeiJarasCity,
    zalaCountyCountyMurakereszturCity,
    zalaCountyCountyNagykanizsaCity,
    zalaCountyCountyNagykanizsaiJarasCity,
    zalaCountyCountyPacsaCity,
    zalaCountyCountySarmellekCity,
    zalaCountyCountyTurjeCity,
    zalaCountyCountyVonyarcvashegyCity,
    zalaCountyCountyZalaegerszegCity,
    zalaCountyCountyZalaegerszegiJarasCity,
    zalaCountyCountyZalakomarCity,
    zalaCountyCountyZalalovoCity,
    zalaCountyCountyZalaszentgrotCity,
    zalaCountyCountyZalaszentgrotiJarasCity
  ]);

/// The `Zalaegerszeg` region in `Hungary`
const Region hungaryZalaegerszegCounty = Region(
  id: 1050,
  parentId: 99,
  longitude: 16.8416322,
  latitude: 46.8416936,
  name: "Zalaegerszeg",
  type: "county",
  stateCode: "ZE",
  cities: []);

/// The 43 states of `Hungary` keyed by their id.
const Map<int, Region> hungaryStates = <int, Region>{
    1048: hungaryBacsHypkiskunCounty,
    1055: hungaryBaranyaCounty,
    1060: hungaryBekesCounty,
    1036: hungaryBekescsabaCityWithCountyRights,
    1058: hungaryBorsodHypabaujHypzemplenCounty,
    1064: hungaryBudapestCapitalCity,
    1031: hungaryCsongradCountyCounty,
    1032: hungaryDebrecenCityWithCountyRights,
    1049: hungaryDunaujvarosCityWithCountyRights,
    1037: hungaryEgerCityWithCountyRights,
    1028: hungaryErdCityWithCountyRights,
    1044: hungaryFejerCountyCounty,
    1041: hungaryGyorCityWithCountyRights,
    1042: hungaryGyorHypmosonHypsopronCountyCounty,
    1063: hungaryHajduHypbiharCountyCounty,
    1040: hungaryHevesCountyCounty,
    1027: hungaryHodmezovasarhelyCityWithCountyRights,
    1043: hungaryJaszHypnagykunHypszolnokCountyCounty,
    1067: hungaryKaposvarCityWithCountyRights,
    1056: hungaryKecskemetCityWithCountyRights,
    5085: hungaryKomaromHypesztergomCounty,
    1065: hungaryMiskolcCityWithCountyRights,
    1030: hungaryNagykanizsaCityWithCountyRights,
    1051: hungaryNogradCountyCounty,
    1034: hungaryNyiregyhazaCityWithCountyRights,
    1053: hungaryPecsCityWithCountyRights,
    1059: hungaryPestCountyCounty,
    1068: hungarySalgotarjanCityWithCountyRights,
    1035: hungarySomogyCountyCounty,
    1057: hungarySopronCityWithCountyRights,
    1045: hungarySzabolcsHypszatmarHypberegCountyCounty,
    1029: hungarySzegedCityWithCountyRights,
    1033: hungarySzekesfehervarCityWithCountyRights,
    1061: hungarySzekszardCityWithCountyRights,
    1047: hungarySzolnokCityWithCountyRights,
    1052: hungarySzombathelyCityWithCountyRights,
    1066: hungaryTatabanyaCityWithCountyRights,
    1038: hungaryTolnaCountyCounty,
    1039: hungaryVasCountyCounty,
    1062: hungaryVeszpremCityWithCountyRights,
    1054: hungaryVeszpremCountyCounty,
    1046: hungaryZalaCountyCounty,
    1050: hungaryZalaegerszegCounty
  };
