/// Access to known geographies in Iran and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'iran_cities.dart';

/// The 31 regions of `🇮🇷 Iran`
const Region iranAlborzProvince = Region(
    id: 3929,
    parentId: 103,
    longitude: 50.9289246,
    latitude: 35.9960467,
    name: "Alborz Province",
    type: null,
    stateCode: "30",
    cities: [
      iranAlborzProvinceFardis,
      iranAlborzProvinceKaraj,
      iranAlborzProvinceNazarabad,
      iranAlborzProvinceShahrestanHypeEshtehard,
      iranAlborzProvinceShahrestanHypeNazarabad,
      iranAlborzProvinceShahrestanHypeSavojbolagh,
      iranAlborzProvinceShahrestanHypeTaleqan
    ]);
const Region iranArdabilProvince = Region(
    id: 3934,
    parentId: 103,
    longitude: 47.8911209,
    latitude: 38.4853276,
    name: "Ardabil Province",
    type: null,
    stateCode: "24",
    cities: [
      iranArdabilProvinceArdabil,
      iranArdabilProvinceBilehSavar,
      iranArdabilProvinceKhalkhal,
      iranArdabilProvinceOmidcheh,
      iranArdabilProvinceParsabad,
      iranArdabilProvinceShahrestanHypeArdabil,
      iranArdabilProvinceShahrestanHypeBilehSavar,
      iranArdabilProvinceShahrestanHypeGermi,
      iranArdabilProvinceShahrestanHypeKhalkhal,
      iranArdabilProvinceShahrestanHypeKowsar,
      iranArdabilProvinceShahrestanHypeMeshginShahr,
      iranArdabilProvinceShahrestanHypeNamin,
      iranArdabilProvinceShahrestanHypeNir,
      iranArdabilProvinceShahrestanHypeParsabad,
      iranArdabilProvinceShahrestanHypeSareyn
    ]);
const Region iranBushehrProvince = Region(
    id: 3932,
    parentId: 103,
    longitude: 51.5150077,
    latitude: 28.7620739,
    name: "Bushehr Province",
    type: null,
    stateCode: "18",
    cities: [
      iranBushehrProvinceAhram,
      iranBushehrProvinceBandarHypeGenaveh,
      iranBushehrProvinceBorazjan,
      iranBushehrProvinceBushehr,
      iranBushehrProvinceDeylam,
      iranBushehrProvinceKhark,
      iranBushehrProvinceShahrestanHypeAsaluyeh,
      iranBushehrProvinceShahrestanHypeBushehr,
      iranBushehrProvinceShahrestanHypeDashtestan,
      iranBushehrProvinceShahrestanHypeDashti,
      iranBushehrProvinceShahrestanHypeGenaveh,
      iranBushehrProvinceShahrestanHypeKangan,
      iranBushehrProvinceShahrestanHypeTangestan
    ]);
const Region iranChaharmahalAandBakhtiariProvince = Region(
    id: 3921,
    parentId: 103,
    longitude: 50.6613849,
    latitude: 31.9970419,
    name: "Chaharmahal and Bakhtiari Province",
    type: null,
    stateCode: "14",
    cities: [
      iranChaharmahalAandBakhtiariProvinceBen,
      iranChaharmahalAandBakhtiariProvinceBorujen,
      iranChaharmahalAandBakhtiariProvinceChelgard,
      iranChaharmahalAandBakhtiariProvinceFarrokhShahr,
      iranChaharmahalAandBakhtiariProvinceFarsan,
      iranChaharmahalAandBakhtiariProvinceSaman,
      iranChaharmahalAandBakhtiariProvinceShahrHypeKord,
      iranChaharmahalAandBakhtiariProvinceShahrekord,
      iranChaharmahalAandBakhtiariProvinceShahrestanHypeBorujen,
      iranChaharmahalAandBakhtiariProvinceShahrestanHypeFarsan,
      iranChaharmahalAandBakhtiariProvinceShahrestanHypeKiar,
      iranChaharmahalAandBakhtiariProvinceShahrestanHypeKuhrang,
      iranChaharmahalAandBakhtiariProvinceShahrestanHypeLordegan
    ]);
const Region iranEastAzerbaijanProvince = Region(
    id: 3944,
    parentId: 103,
    longitude: 46.2682109,
    latitude: 37.9035733,
    name: "East Azerbaijan Province",
    type: null,
    stateCode: "03",
    cities: [
      iranEastAzerbaijanProvinceAjabShir,
      iranEastAzerbaijanProvinceAhar,
      iranEastAzerbaijanProvinceBonab,
      iranEastAzerbaijanProvinceHashtrud,
      iranEastAzerbaijanProvinceMarand,
      iranEastAzerbaijanProvinceSarab,
      iranEastAzerbaijanProvinceShahrestanHypeAjabShir,
      iranEastAzerbaijanProvinceShahrestanHypeAzarshahr,
      iranEastAzerbaijanProvinceShahrestanHypeBonab,
      iranEastAzerbaijanProvinceShahrestanHypeBostanabad,
      iranEastAzerbaijanProvinceShahrestanHypeCharavimaq,
      iranEastAzerbaijanProvinceShahrestanHypeHashtrud,
      iranEastAzerbaijanProvinceShahrestanHypeHeris,
      iranEastAzerbaijanProvinceShahrestanHypeJolfa,
      iranEastAzerbaijanProvinceShahrestanHypeKhodaAfarin,
      iranEastAzerbaijanProvinceShahrestanHypeMalekan,
      iranEastAzerbaijanProvinceShahrestanHypeMaragheh,
      iranEastAzerbaijanProvinceShahrestanHypeMianeh,
      iranEastAzerbaijanProvinceShahrestanHypeOsku,
      iranEastAzerbaijanProvinceShahrestanHypeSarab,
      iranEastAzerbaijanProvinceShahrestanHypeTabriz,
      iranEastAzerbaijanProvinceShahrestanHypeVarzaqan,
      iranEastAzerbaijanProvinceTabriz
    ]);
const Region iranFarsProvince = Region(
    id: 3939,
    parentId: 103,
    longitude: 53.045893,
    latitude: 29.1043813,
    name: "Fars Province",
    type: null,
    stateCode: "07",
    cities: [
      iranFarsProvinceAbadeh,
      iranFarsProvinceAkbarabad,
      iranFarsProvinceDarab,
      iranFarsProvinceFasa,
      iranFarsProvinceFiruzabad,
      iranFarsProvinceGerash,
      iranFarsProvinceKazerun,
      iranFarsProvinceMamasani,
      iranFarsProvinceMarvdasht,
      iranFarsProvinceMohr,
      iranFarsProvinceNeyriz,
      iranFarsProvinceNurabad,
      iranFarsProvincePasargad,
      iranFarsProvinceRostam,
      iranFarsProvinceShahrHypeQadimHypeLar,
      iranFarsProvinceShahrestanHypeAbadeh,
      iranFarsProvinceShahrestanHypeArsanjan,
      iranFarsProvinceShahrestanHypeBavanat,
      iranFarsProvinceShahrestanHypeDarab,
      iranFarsProvinceShahrestanHypeEqlid,
      iranFarsProvinceShahrestanHypeEstahban,
      iranFarsProvinceShahrestanHypeFarashband,
      iranFarsProvinceShahrestanHypeFasa,
      iranFarsProvinceShahrestanHypeFiruzabad,
      iranFarsProvinceShahrestanHypeGerash,
      iranFarsProvinceShahrestanHypeKavar,
      iranFarsProvinceShahrestanHypeKazerun,
      iranFarsProvinceShahrestanHypeKherameh,
      iranFarsProvinceShahrestanHypeKhorrambid,
      iranFarsProvinceShahrestanHypeLamerd,
      iranFarsProvinceShahrestanHypeLarestan,
      iranFarsProvinceShahrestanHypeNeyriz,
      iranFarsProvinceShahrestanHypePasargad,
      iranFarsProvinceShahrestanHypeQirVvaKarzin,
      iranFarsProvinceShahrestanHypeSarvestan,
      iranFarsProvinceShahrestanHypeSepidan,
      iranFarsProvinceShahrestanHypeShiraz,
      iranFarsProvinceShahrestanHypeZarrinDasht,
      iranFarsProvinceShiraz
    ]);
const Region iranGilanProvince = Region(
    id: 3920,
    parentId: 103,
    longitude: 49.5924134,
    latitude: 37.2809455,
    name: "Gilan Province",
    type: null,
    stateCode: "01",
    cities: [
      iranGilanProvinceAstanehHypyeAshrafiyeh,
      iranGilanProvinceAstara,
      iranGilanProvinceBandarHypeAnzali,
      iranGilanProvinceFuman,
      iranGilanProvinceHashtpar,
      iranGilanProvinceLangarud,
      iranGilanProvincePadeganHypeManjil,
      iranGilanProvinceRasht,
      iranGilanProvinceRezvanshahr,
      iranGilanProvinceRudsar,
      iranGilanProvinceShahrestanHypeAstanehHypyeAshrafiyeh,
      iranGilanProvinceShahrestanHypeAstara,
      iranGilanProvinceShahrestanHypeBandarHypeAnzali,
      iranGilanProvinceShahrestanHypeFuman,
      iranGilanProvinceShahrestanHypeLahijan,
      iranGilanProvinceShahrestanHypeLangarud,
      iranGilanProvinceShahrestanHypeMasal,
      iranGilanProvinceShahrestanHypeRezvanshahr,
      iranGilanProvinceShahrestanHypeRudbar,
      iranGilanProvinceShahrestanHypeRudsar,
      iranGilanProvinceShahrestanHypeSiahkal,
      iranGilanProvinceShahrestanHypeSowmeehSara,
      iranGilanProvinceShahrestanHypeTalesh,
      iranGilanProvinceZiabarGaskar
    ]);
const Region iranGolestanProvince = Region(
    id: 3933,
    parentId: 103,
    longitude: 55.1375834,
    latitude: 37.2898123,
    name: "Golestan Province",
    type: null,
    stateCode: "27",
    cities: [
      iranGolestanProvinceAqQayeh,
      iranGolestanProvinceAzadshahr,
      iranGolestanProvinceGonbadHypeKavus,
      iranGolestanProvinceGorgan,
      iranGolestanProvinceKalaleh,
      iranGolestanProvinceQarnabad,
      iranGolestanProvinceShahrestanHypeAliabad,
      iranGolestanProvinceShahrestanHypeAqQala,
      iranGolestanProvinceShahrestanHypeAzadshahr,
      iranGolestanProvinceShahrestanHypeGalikesh,
      iranGolestanProvinceShahrestanHypeGomishan,
      iranGolestanProvinceShahrestanHypeGonbadHypeKavus,
      iranGolestanProvinceShahrestanHypeGorgan,
      iranGolestanProvinceShahrestanHypeKalaleh,
      iranGolestanProvinceShahrestanHypeKordkuy,
      iranGolestanProvinceShahrestanHypeMaravehTappeh,
      iranGolestanProvinceShahrestanHypeMinudasht,
      iranGolestanProvinceShahrestanHypeRamian,
      iranGolestanProvinceTorkaman
    ]);
const Region iranHamadanProvince = Region(
    id: 4920,
    parentId: 103,
    longitude: 47.4832925,
    latitude: 34.9193607,
    name: "Hamadan Province",
    type: null,
    stateCode: "13",
    cities: [
      iranHamadanProvinceAbMeshkin,
      iranHamadanProvinceAbarlaqHypeSofla,
      iranHamadanProvinceAbdalan,
      iranHamadanProvinceAbdolRahim,
      iranHamadanProvinceAbrumand,
      iranHamadanProvinceAbshineh,
      iranHamadanProvinceAbuOolFathabad,
      iranHamadanProvinceAghchehQayah,
      iranHamadanProvinceAhmadabadHypeTappeh,
      iranHamadanProvinceAhuTappeh,
      iranHamadanProvinceAjin,
      iranHamadanProvinceAjorlu,
      iranHamadanProvinceAkanlu,
      iranHamadanProvinceAkleh,
      iranHamadanProvinceAlanHypeSofla,
      iranHamadanProvinceAlanjeh,
      iranHamadanProvinceAlfavut,
      iranHamadanProvinceAliabadHypePoshtShahr,
      iranHamadanProvinceAmirabadHypeKord,
      iranHamadanProvinceAmzajerd,
      iranHamadanProvinceAngoshteh,
      iranHamadanProvinceAnjirBaghi,
      iranHamadanProvinceAnsarOolEmam,
      iranHamadanProvinceAnuch,
      iranHamadanProvinceAqBolaghHypeAqdaq,
      iranHamadanProvinceAqBolaghHypeLatgah,
      iranHamadanProvinceAqBolaghHypeMorshed,
      iranHamadanProvinceAqChay,
      iranHamadanProvinceAqaBolaghi,
      iranHamadanProvinceAqaJanBolaghi,
      iranHamadanProvinceAqaj,
      iranHamadanProvinceAqchehKharabeh,
      iranHamadanProvinceAqchelu,
      iranHamadanProvinceArgesHypeSofla,
      iranHamadanProvinceArikan,
      iranHamadanProvinceArpaDarreh,
      iranHamadanProvinceArtehBolagh,
      iranHamadanProvinceArtiman,
      iranHamadanProvinceArzanFud,
      iranHamadanProvinceArzuvaj,
      iranHamadanProvinceAsadabad,
      iranHamadanProvinceAshmizan,
      iranHamadanProvinceAvarzaman,
      iranHamadanProvinceAzandarian,
      iranHamadanProvinceAznahri,
      iranHamadanProvinceBabaKhanjar,
      iranHamadanProvinceBabaPir,
      iranHamadanProvinceBabaQasem,
      iranHamadanProvinceBabolqani,
      iranHamadanProvinceBadKhvoreh,
      iranHamadanProvinceBahar,
      iranHamadanProvinceBandAman,
      iranHamadanProvinceBanesareh,
      iranHamadanProvinceBaraband,
      iranHamadanProvinceBargecheh,
      iranHamadanProvinceBarrehFarakh,
      iranHamadanProvinceBarzul,
      iranHamadanProvinceBashqurtaran,
      iranHamadanProvinceBazeran,
      iranHamadanProvinceBehkandan,
      iranHamadanProvinceBelartu,
      iranHamadanProvinceBeshikTappeh,
      iranHamadanProvinceBiaj,
      iranHamadanProvinceBiatanHypeSofla,
      iranHamadanProvinceBidKorpehHypyeSofla,
      iranHamadanProvinceBidKorpehHypyeVosta,
      iranHamadanProvinceBifanaj,
      iranHamadanProvinceBighash,
      iranHamadanProvinceBishAghaj,
      iranHamadanProvinceBitervan,
      iranHamadanProvinceBorjaki,
      iranHamadanProvinceBoyukabad,
      iranHamadanProvinceBozchalu,
      iranHamadanProvinceBozinehJerd,
      iranHamadanProvinceBujin,
      iranHamadanProvinceBustandar,
      iranHamadanProvinceBuyaqchi,
      iranHamadanProvinceChaharBolagh,
      iranHamadanProvinceChalBoqa,
      iranHamadanProvinceChalehKand,
      iranHamadanProvinceCharoq,
      iranHamadanProvinceChashtKhvoreh,
      iranHamadanProvinceChenari,
      iranHamadanProvinceCheshmehMalek,
      iranHamadanProvinceCheshmehPahnHypeNanaj,
      iranHamadanProvinceCheshmehQandab,
      iranHamadanProvinceCheshmehQareh,
      iranHamadanProvinceCheshmehQassaban,
      iranHamadanProvinceCheshmehValad,
      iranHamadanProvinceCheshmehZowraq,
      iranHamadanProvinceChoqaSarahi,
      iranHamadanProvinceChowtash,
      iranHamadanProvinceChulakQapanuri,
      iranHamadanProvinceDahnejerd,
      iranHamadanProvinceDaliChu,
      iranHamadanProvinceDamaq,
      iranHamadanProvinceDaqdaqabad,
      iranHamadanProvinceDarQeshlaq,
      iranHamadanProvinceDaraniHypyeSofla,
      iranHamadanProvinceDarcham,
      iranHamadanProvinceDarrehChenar,
      iranHamadanProvinceDarrehMianehHypyeSofla,
      iranHamadanProvinceDarrehMirza,
      iranHamadanProvinceDarrehHypyeEbrahim,
      iranHamadanProvinceDarsibeh,
      iranHamadanProvinceDavijan,
      iranHamadanProvinceDehChaneh,
      iranHamadanProvinceDehDalian,
      iranHamadanProvinceDehFul,
      iranHamadanProvinceDehMianeh,
      iranHamadanProvinceDehNush,
      iranHamadanProvinceDehPiaz,
      iranHamadanProvinceDehHypeShaker,
      iranHamadanProvinceDehnowHypeAvarzaman,
      iranHamadanProvinceDingelehKahriz,
      iranHamadanProvinceDoRudan,
      iranHamadanProvinceDoraneh,
      iranHamadanProvinceDorudgaran,
      iranHamadanProvinceDowBaraleh,
      iranHamadanProvinceDowlatabadHypeHajjilu,
      iranHamadanProvinceDowlujerdinHypeBala,
      iranHamadanProvinceDurijan,
      iranHamadanProvinceDurnian,
      iranHamadanProvinceEmamzadehKhatun,
      iranHamadanProvinceEmamzadehPirNahan,
      iranHamadanProvinceEskanan,
      iranHamadanProvinceFahrumand,
      iranHamadanProvinceFamast,
      iranHamadanProvinceFamenin,
      iranHamadanProvinceFarasfaj,
      iranHamadanProvinceFarsban,
      iranHamadanProvinceFarvaz,
      iranHamadanProvinceFaryazan,
      iranHamadanProvinceFasijan,
      iranHamadanProvinceFiazaman,
      iranHamadanProvinceFiruzabadHypeSofla,
      iranHamadanProvinceFiruzan,
      iranHamadanProvinceGamasa,
      iranHamadanProvinceGamasb,
      iranHamadanProvinceGanjTappeh,
      iranHamadanProvinceGanjab,
      iranHamadanProvinceGashani,
      iranHamadanProvinceGavZaban,
      iranHamadanProvinceGavkaran,
      iranHamadanProvinceGhazyatan,
      iranHamadanProvinceGholamVeys,
      iranHamadanProvinceGivaki,
      iranHamadanProvinceGiyan,
      iranHamadanProvinceGolDarrehHypyeAnuch,
      iranHamadanProvinceGolHeydar,
      iranHamadanProvinceGolparabad,
      iranHamadanProvinceGolshir,
      iranHamadanProvinceGolushjerd,
      iranHamadanProvinceGomushBolagh,
      iranHamadanProvinceGonbadChay,
      iranHamadanProvinceGonbadHypeKabud,
      iranHamadanProvinceGostar,
      iranHamadanProvinceGozalAbdal,
      iranHamadanProvinceGugQash,
      iranHamadanProvinceGujak,
      iranHamadanProvinceGulvand,
      iranHamadanProvinceGunestan,
      iranHamadanProvinceGurGaz,
      iranHamadanProvinceGurjiu,
      iranHamadanProvinceGushalan,
      iranHamadanProvinceGushehHypyeKasavand,
      iranHamadanProvinceHajjiKheder,
      iranHamadanProvinceHajjiMaqsud,
      iranHamadanProvinceHajjiTu,
      iranHamadanProvinceHamadan,
      iranHamadanProvinceHamilabad,
      iranHamadanProvinceHamzehluHypyeSofla,
      iranHamadanProvinceHaramabad,
      iranHamadanProvinceHasanKusej,
      iranHamadanProvinceHasanTeymur,
      iranHamadanProvinceHasanabadHypeEmam,
      iranHamadanProvinceHasanabadHypeQushBolagh,
      iranHamadanProvinceHasanabadHypeSheverin,
      iranHamadanProvinceHeriraz,
      iranHamadanProvinceHesarHypeQarahBaghi,
      iranHamadanProvinceHesarHypeQujehBaghi,
      iranHamadanProvinceHeydarehHypyeDarHypeEmam,
      iranHamadanProvinceHeydarehHypyePoshtHypeShahr,
      iranHamadanProvinceHizaj,
      iranHamadanProvinceHolvarHypeSofla,
      iranHamadanProvinceHomHypeKhosrow,
      iranHamadanProvinceHorhoreh,
      iranHamadanProvinceHoseynabadHypeBahar,
      iranHamadanProvinceHoseynabadHypeNazem,
      iranHamadanProvinceHoseynabadHypeShamlu,
      iranHamadanProvinceHudaraj,
      iranHamadanProvinceIraneh,
      iranHamadanProvinceIstiBolagh,
      iranHamadanProvinceJamishlu,
      iranHamadanProvinceJaria,
      iranHamadanProvinceJavarSajin,
      iranHamadanProvinceJerbanlu,
      iranHamadanProvinceJighi,
      iranHamadanProvinceJijanKuh,
      iranHamadanProvinceJijianRud,
      iranHamadanProvinceJinTaraqayah,
      iranHamadanProvinceJuraqan,
      iranHamadanProvinceKaboodrahang,
      iranHamadanProvinceKahard,
      iranHamadanProvinceKahkadan,
      iranHamadanProvinceKahrizHypeBabaHoseyn,
      iranHamadanProvinceKahrizHypeBoqazi,
      iranHamadanProvinceKahrizHypeHoseynabadHypeNazem,
      iranHamadanProvinceKahrizHypeJamal,
      iranHamadanProvinceKahrizHypeSalim,
      iranHamadanProvinceKalKabud,
      iranHamadanProvinceKalbHesari,
      iranHamadanProvinceKalilabad,
      iranHamadanProvinceKamakHypeSofla,
      iranHamadanProvinceKamarBoneh,
      iranHamadanProvinceKamazan,
      iranHamadanProvinceKandHalan,
      iranHamadanProvinceKandTappeh,
      iranHamadanProvinceKandHypeBolaghi,
      iranHamadanProvinceKangavarHypeKohneh,
      iranHamadanProvinceKarafs,
      iranHamadanProvinceKarkHypeSofla,
      iranHamadanProvinceKartilabad,
      iranHamadanProvinceKasavand,
      iranHamadanProvinceKaslanQayah,
      iranHamadanProvinceKavanaj,
      iranHamadanProvinceKesb,
      iranHamadanProvinceKeykaleh,
      iranHamadanProvinceKeyniSayeh,
      iranHamadanProvinceKhabarArkhi,
      iranHamadanProvinceKhaku,
      iranHamadanProvinceKhaleqVerdi,
      iranHamadanProvinceKhalilKord,
      iranHamadanProvinceKheradmand,
      iranHamadanProvinceKheyrQoli,
      iranHamadanProvinceKhomeygan,
      iranHamadanProvinceKhvajehHesar,
      iranHamadanProvinceKhvajehHoseyni,
      iranHamadanProvinceKhvajehKandi,
      iranHamadanProvinceKhvoshabHypeSofla,
      iranHamadanProvinceKitu,
      iranHamadanProvinceKohnush,
      iranHamadanProvinceKolanjan,
      iranHamadanProvinceKonjineh,
      iranHamadanProvinceKordBolagh,
      iranHamadanProvinceKorzan,
      iranHamadanProvinceKowzareh,
      iranHamadanProvinceKuhani,
      iranHamadanProvinceKurKahriz,
      iranHamadanProvinceKusajKhalil,
      iranHamadanProvinceKutahDarreh,
      iranHamadanProvinceLalehDan,
      iranHamadanProvinceLalejin,
      iranHamadanProvinceLamiyan,
      iranHamadanProvinceLatgah,
      iranHamadanProvinceLavashan,
      iranHamadanProvinceLeyliYadegar,
      iranHamadanProvinceLuluhar,
      iranHamadanProvinceMahanabad,
      iranHamadanProvinceMahbar,
      iranHamadanProvinceMahdaviyeh,
      iranHamadanProvinceMahnian,
      iranHamadanProvinceMalayer,
      iranHamadanProvinceMalekHypeAshtar,
      iranHamadanProvinceMalusan,
      iranHamadanProvinceMangavi,
      iranHamadanProvinceMarvil,
      iranHamadanProvinceMaryanaj,
      iranHamadanProvinceMasjedin,
      iranHamadanProvinceMenjan,
      iranHamadanProvinceMesinak,
      iranHamadanProvinceMeyvaleh,
      iranHamadanProvinceMianzulan,
      iranHamadanProvinceMihamlehHypyeSofla,
      iranHamadanProvinceMilab,
      iranHamadanProvinceMirzaHesari,
      iranHamadanProvinceMishen,
      iranHamadanProvinceMobarakin,
      iranHamadanProvinceMohajeran,
      iranHamadanProvinceMohammadabadHypeChulak,
      iranHamadanProvinceMohammadiyehHypeSofla,
      iranHamadanProvinceMohara,
      iranHamadanProvinceMokarrabi,
      iranHamadanProvinceMolhamDarreh,
      iranHamadanProvinceMollaBodagh,
      iranHamadanProvinceMonavvarTappeh,
      iranHamadanProvinceMorghabad,
      iranHamadanProvinceMowdaran,
      iranHamadanProvinceMusaBolaghi,
      iranHamadanProvinceNahandar,
      iranHamadanProvinceNahavand,
      iranHamadanProvinceNajafiyeh,
      iranHamadanProvinceNakilabad,
      iranHamadanProvinceNakin,
      iranHamadanProvinceNamileh,
      iranHamadanProvinceNanaj,
      iranHamadanProvinceNazul,
      iranHamadanProvinceNegarKhatun,
      iranHamadanProvinceNegarabad,
      iranHamadanProvinceNehenjeh,
      iranHamadanProvinceNesar,
      iranHamadanProvinceNeshar,
      iranHamadanProvinceNiyanj,
      iranHamadanProvinceNosratabadHypeBehraz,
      iranHamadanProvinceNosratabadHypeLaklak,
      iranHamadanProvinceNurabadHypeSimineh,
      iranHamadanProvinceOjaq,
      iranHamadanProvinceOmmatlar,
      iranHamadanProvinceOshtoran,
      iranHamadanProvinceOshtorjin,
      iranHamadanProvinceOvraqin,
      iranHamadanProvinceOwrtehQamish,
      iranHamadanProvinceOwryad,
      iranHamadanProvincePahnabad,
      iranHamadanProvincePanbehDar,
      iranHamadanProvinceParluk,
      iranHamadanProvinceParvaraq,
      iranHamadanProvincePayandeh,
      iranHamadanProvincePeyhan,
      iranHamadanProvincePilehJin,
      iranHamadanProvincePirAnbar,
      iranHamadanProvincePirBadam,
      iranHamadanProvincePirKhodaverdi,
      iranHamadanProvincePirMalu,
      iranHamadanProvincePirMishan,
      iranHamadanProvincePirSavaran,
      iranHamadanProvincePirYusof,
      iranHamadanProvincePiruz,
      iranHamadanProvincePoshtjin,
      iranHamadanProvinceQabanqoli,
      iranHamadanProvinceQaderKhalaj,
      iranHamadanProvinceQadimi,
      iranHamadanProvinceQahavand,
      iranHamadanProvinceQajarAbHypeSofla,
      iranHamadanProvinceQarahDay,
      iranHamadanProvinceQarahTegini,
      iranHamadanProvinceQaranquDarreh,
      iranHamadanProvinceQasabestan,
      iranHamadanProvinceQasemabadHypeLaklak,
      iranHamadanProvinceQaterOwlan,
      iranHamadanProvinceQayesh,
      iranHamadanProvinceQazanQarah,
      iranHamadanProvinceQaziMardan,
      iranHamadanProvinceQeshlaqBabaRostam,
      iranHamadanProvinceQeshlaqHypeAnuch,
      iranHamadanProvinceQeshlaqHypeDehFul,
      iranHamadanProvinceQeshlaqHypeDehnow,
      iranHamadanProvinceQeshlaqHypeMohammadi,
      iranHamadanProvinceQeshlaqHypeNajaf,
      iranHamadanProvinceQeshlaqHypePustShuran,
      iranHamadanProvinceQeshlaqHypeQobad,
      iranHamadanProvinceQeshlaqHypeShirazi,
      iranHamadanProvinceQeshlaqHypeSofla,
      iranHamadanProvinceQeshlaqHypeValiollah,
      iranHamadanProvinceQeydliBolagh,
      iranHamadanProvinceQilab,
      iranHamadanProvinceQohurdHypeSofla,
      iranHamadanProvinceQoliLalehHypyeSofla,
      iranHamadanProvinceQolqolabad,
      iranHamadanProvinceQuchTappeh,
      iranHamadanProvinceQushjeh,
      iranHamadanProvinceRahmanabadMalayer,
      iranHamadanProvinceRamishan,
      iranHamadanProvinceRastguyan,
      iranHamadanProvinceRasulabadHypeSofla,
      iranHamadanProvinceRavandHypeVosta,
      iranHamadanProvinceRayeganHypeSofla,
      iranHamadanProvinceRazaj,
      iranHamadanProvinceRazan,
      iranHamadanProvinceRazini,
      iranHamadanProvinceRezaBaghi,
      iranHamadanProvinceRezvankadeh,
      iranHamadanProvinceRivasijan,
      iranHamadanProvinceRobatHypeSheverin,
      iranHamadanProvinceRudAvar,
      iranHamadanProvinceRudHypeHasanHypeSofla,
      iranHamadanProvinceSafaRiz,
      iranHamadanProvinceSahamabad,
      iranHamadanProvinceSalehabad,
      iranHamadanProvinceSalilak,
      iranHamadanProvinceSaluk,
      iranHamadanProvinceSamen,
      iranHamadanProvinceSanaj,
      iranHamadanProvinceSanjuzan,
      iranHamadanProvinceSarDuran,
      iranHamadanProvinceSarabHypeTajar,
      iranHamadanProvinceSaravak,
      iranHamadanProvinceSarayjuq,
      iranHamadanProvinceSarijlu,
      iranHamadanProvinceSarkan,
      iranHamadanProvinceSaziyan,
      iranHamadanProvinceSefidKhaneh,
      iranHamadanProvinceSegavi,
      iranHamadanProvinceSetaq,
      iranHamadanProvinceShademaneh,
      iranHamadanProvinceShanabad,
      iranHamadanProvinceShanjur,
      iranHamadanProvinceSharifabadHypeQuzan,
      iranHamadanProvinceSharifabadHypeTajar,
      iranHamadanProvinceShatzal,
      iranHamadanProvinceShavand,
      iranHamadanProvinceSheverin,
      iranHamadanProvinceSheykhJarrah,
      iranHamadanProvinceShilandarHypeSofla,
      iranHamadanProvinceShirBarat,
      iranHamadanProvinceShirinSu,
      iranHamadanProvinceShushAb,
      iranHamadanProvinceSiahGoleh,
      iranHamadanProvinceSibDar,
      iranHamadanProvinceSilvar,
      iranHamadanProvinceSiminHypeAbaru,
      iranHamadanProvinceSiminHypeZagheh,
      iranHamadanProvinceSiravand,
      iranHamadanProvinceSistaneh,
      iranHamadanProvinceSolulan,
      iranHamadanProvinceSorkhKand,
      iranHamadanProvinceSulijeh,
      iranHamadanProvinceSurtajin,
      iranHamadanProvinceSutlaq,
      iranHamadanProvinceTafrijan,
      iranHamadanProvinceTahunabad,
      iranHamadanProvinceTajarHypeSamen,
      iranHamadanProvinceTakhtiabad,
      iranHamadanProvinceTalehJerdHypeSofla,
      iranHamadanProvinceTamuzan,
      iranHamadanProvinceTappehYazdan,
      iranHamadanProvinceTappehHypyeDibi,
      iranHamadanProvinceTaraqayah,
      iranHamadanProvinceTarikDarrehHypyeBala,
      iranHamadanProvinceTarkhinabad,
      iranHamadanProvinceTasTappeh,
      iranHamadanProvinceTasbandi,
      iranHamadanProvinceTasran,
      iranHamadanProvinceTavaleh,
      iranHamadanProvinceTavaneh,
      iranHamadanProvinceTaveh,
      iranHamadanProvinceTavilanHypeSofla,
      iranHamadanProvinceTazehnabHypeSofla,
      iranHamadanProvinceTermianak,
      iranHamadanProvinceTimiJan,
      iranHamadanProvinceTuchaqaz,
      iranHamadanProvinceTulkiTappeh,
      iranHamadanProvinceTuskHypeSofla,
      iranHamadanProvinceTutal,
      iranHamadanProvinceTuyserkan,
      iranHamadanProvinceVafrHypeJin,
      iranHamadanProvinceVahandeh,
      iranHamadanProvinceVahman,
      iranHamadanProvinceVahnan,
      iranHamadanProvinceValiMohammad,
      iranHamadanProvinceValiSirAb,
      iranHamadanProvinceVandarabad,
      iranHamadanProvinceVarayeneh,
      iranHamadanProvinceVarazaneh,
      iranHamadanProvinceVarchaq,
      iranHamadanProvinceVardavardHypeSofla,
      iranHamadanProvinceVardavardHypeVosta,
      iranHamadanProvinceVarkaneh,
      iranHamadanProvinceVarqestan,
      iranHamadanProvinceVarvazin,
      iranHamadanProvinceVasaj,
      iranHamadanProvinceVashur,
      iranHamadanProvinceVasleh,
      iranHamadanProvinceVesht,
      iranHamadanProvinceVezendan,
      iranHamadanProvinceYalfan,
      iranHamadanProvinceYaromQayah,
      iranHamadanProvinceYaromjehBagh,
      iranHamadanProvinceYeganeh,
      iranHamadanProvinceYekanabad,
      iranHamadanProvinceYekleh,
      iranHamadanProvinceYeserlu,
      iranHamadanProvinceYunes,
      iranHamadanProvinceYunji,
      iranHamadanProvinceZaghehHypyeAnuch,
      iranHamadanProvinceZaghehHypyeTasbandi,
      iranHamadanProvinceZaghlijeh,
      iranHamadanProvinceZamanabadHypeMohammadabad,
      iranHamadanProvinceZangenehHypyeSofla,
      iranHamadanProvinceZapon,
      iranHamadanProvinceZaraminHypeSofla,
      iranHamadanProvinceZarrinBagh,
      iranHamadanProvinceZeraq,
      iranHamadanProvinceZirabiyeh
    ]);
const Region iranHormozganProvince = Region(
    id: 3937,
    parentId: 103,
    longitude: 55.1375834,
    latitude: 27.138723,
    name: "Hormozgan Province",
    type: null,
    stateCode: "22",
    cities: [
      iranHormozganProvinceBandarAbbas,
      iranHormozganProvinceBandarLengeh,
      iranHormozganProvinceBandarHypeLengeh,
      iranHormozganProvinceBastak,
      iranHormozganProvinceKish,
      iranHormozganProvinceMinab,
      iranHormozganProvinceQeshm,
      iranHormozganProvinceShahrestanHypeAbuMusa,
      iranHormozganProvinceShahrestanHypeBandarAbbas,
      iranHormozganProvinceShahrestanHypeBashagard,
      iranHormozganProvinceShahrestanHypeHajjiabad,
      iranHormozganProvinceShahrestanHypeJask,
      iranHormozganProvinceShahrestanHypeKhamir,
      iranHormozganProvinceShahrestanHypeMinab,
      iranHormozganProvinceShahrestanHypeParsian,
      iranHormozganProvinceShahrestanHypeRudan,
      iranHormozganProvinceShahrestanHypeSirik
    ]);
const Region iranIlamProvince = Region(
    id: 3918,
    parentId: 103,
    longitude: 46.670534,
    latitude: 33.2957618,
    name: "Ilam Province",
    type: null,
    stateCode: "16",
    cities: [
      iranIlamProvinceAbdanan,
      iranIlamProvinceBadreh,
      iranIlamProvinceChardavolCounty,
      iranIlamProvinceDarrehShahr,
      iranIlamProvinceDarrehshahr,
      iranIlamProvinceDehloran,
      iranIlamProvinceIlam,
      iranIlamProvinceMehran,
      iranIlamProvinceShahrestanHypeAbdanan,
      iranIlamProvinceShahrestanHypeDehloran,
      iranIlamProvinceShahrestanHypeEyvan,
      iranIlamProvinceShahrestanHypeIlam,
      iranIlamProvinceShahrestanHypeMalekshahi,
      iranIlamProvinceShahrestanHypeMehran,
      iranIlamProvinceSirvan
    ]);
const Region iranIsfahanProvince = Region(
    id: 3923,
    parentId: 103,
    longitude: 52.3613378,
    latitude: 33.2771073,
    name: "Isfahan Province",
    type: null,
    stateCode: "10",
    cities: [
      iranIsfahanProvinceAbrisham,
      iranIsfahanProvinceArdestan,
      iranIsfahanProvinceBuinVvaMiandasht,
      iranIsfahanProvinceChadegan,
      iranIsfahanProvinceDaran,
      iranIsfahanProvinceDehaqan,
      iranIsfahanProvinceDorchehPiaz,
      iranIsfahanProvinceDowlatabad,
      iranIsfahanProvinceFalavarjan,
      iranIsfahanProvinceFareydunshahr,
      iranIsfahanProvinceFereydan,
      iranIsfahanProvinceGolpayegan,
      iranIsfahanProvinceIsfahan,
      iranIsfahanProvinceKelishadVvaSudarjan,
      iranIsfahanProvinceKhomeyniShahr,
      iranIsfahanProvinceKhur,
      iranIsfahanProvinceKhvansar,
      iranIsfahanProvinceMobarakeh,
      iranIsfahanProvinceNain,
      iranIsfahanProvinceNajafabad,
      iranIsfahanProvinceNatanz,
      iranIsfahanProvinceQahderijan,
      iranIsfahanProvinceRehnan,
      iranIsfahanProvinceSemirom,
      iranIsfahanProvinceShahinShahr,
      iranIsfahanProvinceShahrestanHypeAranVvaBidgol,
      iranIsfahanProvinceShahrestanHypeArdestan,
      iranIsfahanProvinceShahrestanHypeBorkhvar,
      iranIsfahanProvinceShahrestanHypeChadegan,
      iranIsfahanProvinceShahrestanHypeDehaqan,
      iranIsfahanProvinceShahrestanHypeEsfahan,
      iranIsfahanProvinceShahrestanHypeFalavarjan,
      iranIsfahanProvinceShahrestanHypeFareydunshahr,
      iranIsfahanProvinceShahrestanHypeGolpayegan,
      iranIsfahanProvinceShahrestanHypeKashan,
      iranIsfahanProvinceShahrestanHypeKhomeyniShahr,
      iranIsfahanProvinceShahrestanHypeKhurVvaBiabanak,
      iranIsfahanProvinceShahrestanHypeKhvansar,
      iranIsfahanProvinceShahrestanHypeLenjan,
      iranIsfahanProvinceShahrestanHypeMobarakeh,
      iranIsfahanProvinceShahrestanHypeNain,
      iranIsfahanProvinceShahrestanHypeNajafabad,
      iranIsfahanProvinceShahrestanHypeNatanz,
      iranIsfahanProvinceShahrestanHypeSemirom,
      iranIsfahanProvinceShahrestanHypeShahinShahrVvaMeymeh,
      iranIsfahanProvinceShahrestanHypeShahreza,
      iranIsfahanProvinceShahrestanHypeTiranVvaKarvan,
      iranIsfahanProvinceShahreza,
      iranIsfahanProvinceTiran,
      iranIsfahanProvinceZarrinShahr
    ]);
const Region iranKermanProvince = Region(
    id: 3943,
    parentId: 103,
    longitude: 57.6439048,
    latitude: 29.4850089,
    name: "Kerman Province",
    type: null,
    stateCode: "08",
    cities: [
      iranKermanProvinceBaft,
      iranKermanProvinceBam,
      iranKermanProvinceBardsir,
      iranKermanProvinceKerman,
      iranKermanProvinceKuhSefid,
      iranKermanProvinceRafsanjan,
      iranKermanProvinceRavar,
      iranKermanProvinceRigan,
      iranKermanProvinceShahrHypeBabak,
      iranKermanProvinceShahrakHypePabedana,
      iranKermanProvinceShahrestanHypeAnbarabad,
      iranKermanProvinceShahrestanHypeAnar,
      iranKermanProvinceShahrestanHypeBaft,
      iranKermanProvinceShahrestanHypeBardsir,
      iranKermanProvinceShahrestanHypeFaryab,
      iranKermanProvinceShahrestanHypeJiroft,
      iranKermanProvinceShahrestanHypeKahnuj,
      iranKermanProvinceShahrestanHypeKerman,
      iranKermanProvinceShahrestanHypeKuhbanan,
      iranKermanProvinceShahrestanHypeManujan,
      iranKermanProvinceShahrestanHypeNarmashir,
      iranKermanProvinceShahrestanHypeOrzuiyeh,
      iranKermanProvinceShahrestanHypeQalehGanj,
      iranKermanProvinceShahrestanHypeRabor,
      iranKermanProvinceShahrestanHypeRafsanjan,
      iranKermanProvinceShahrestanHypeRudbarHypeJonubi,
      iranKermanProvinceShahrestanHypeShahrHypeBabak,
      iranKermanProvinceShahrestanHypeSirjan,
      iranKermanProvinceSirjan,
      iranKermanProvinceZarand
    ]);
const Region iranKermanshahProvince = Region(
    id: 3919,
    parentId: 103,
    longitude: 46.670534,
    latitude: 34.4576233,
    name: "Kermanshah Province",
    type: null,
    stateCode: "05",
    cities: [
      iranKermanshahProvinceHarsin,
      iranKermanshahProvinceJavanrud,
      iranKermanshahProvinceKahriz,
      iranKermanshahProvinceKangavar,
      iranKermanshahProvinceKermanshah,
      iranKermanshahProvincePaveh,
      iranKermanshahProvinceSarpolHypeZahab,
      iranKermanshahProvinceShahrestanHypeDalahu,
      iranKermanshahProvinceShahrestanHypeEslamabadHypeGharb,
      iranKermanshahProvinceShahrestanHypeGilanHypeGharb,
      iranKermanshahProvinceShahrestanHypeHarsin,
      iranKermanshahProvinceShahrestanHypeJavanrud,
      iranKermanshahProvinceShahrestanHypeKangavar,
      iranKermanshahProvinceShahrestanHypeKermanshah,
      iranKermanshahProvinceShahrestanHypePaveh,
      iranKermanshahProvinceShahrestanHypeQasrHypeShirin,
      iranKermanshahProvinceShahrestanHypeRavansar,
      iranKermanshahProvinceShahrestanHypeSahneh,
      iranKermanshahProvinceShahrestanHypeSalasHypeBabaJani,
      iranKermanshahProvinceShahrestanHypeSarpolHypeZahab,
      iranKermanshahProvinceSonqor
    ]);
const Region iranKhuzestanProvince = Region(
    id: 3917,
    parentId: 103,
    longitude: 49.041312,
    latitude: 31.4360149,
    name: "Khuzestan Province",
    type: null,
    stateCode: "06",
    cities: [
      iranKhuzestanProvinceAbadan,
      iranKhuzestanProvinceAghajari,
      iranKhuzestanProvinceAhvaz,
      iranKhuzestanProvinceBaghShahrestanHypeMalek,
      iranKhuzestanProvinceBehbahan,
      iranKhuzestanProvinceGotvand,
      iranKhuzestanProvinceHamidiyeh,
      iranKhuzestanProvinceJongiyeh,
      iranKhuzestanProvinceKarun,
      iranKhuzestanProvinceKhorramshahr,
      iranKhuzestanProvinceMasjedSoleyman,
      iranKhuzestanProvinceOmidiyeh,
      iranKhuzestanProvinceRamhormoz,
      iranKhuzestanProvinceRamshir,
      iranKhuzestanProvinceSsedeyenHypeYek,
      iranKhuzestanProvinceShadegan,
      iranKhuzestanProvinceShahrakHypeKuluri,
      iranKhuzestanProvinceShahrestanHypeAbadan,
      iranKhuzestanProvinceShahrestanHypeAhvaz,
      iranKhuzestanProvinceShahrestanHypeAndika,
      iranKhuzestanProvinceShahrestanHypeAndimeshk,
      iranKhuzestanProvinceShahrestanHypeBandarHypeMahshahr,
      iranKhuzestanProvinceShahrestanHypeBavi,
      iranKhuzestanProvinceShahrestanHypeBehbahan,
      iranKhuzestanProvinceShahrestanHypeDashtHypeAzadegan,
      iranKhuzestanProvinceShahrestanHypeDezful,
      iranKhuzestanProvinceShahrestanHypeHendijan,
      iranKhuzestanProvinceShahrestanHypeIzeh,
      iranKhuzestanProvinceShahrestanHypeLali,
      iranKhuzestanProvinceShahrestanHypeMasjedSoleyman,
      iranKhuzestanProvinceShahrestanHypeOmidiyeh,
      iranKhuzestanProvinceShahrestanHypeRamhormoz,
      iranKhuzestanProvinceShahrestanHypeRamshir,
      iranKhuzestanProvinceShahrestanHypeShadegan,
      iranKhuzestanProvinceShahrestanHypeShush,
      iranKhuzestanProvinceShahrestanHypeShushtar,
      iranKhuzestanProvinceShush,
      iranKhuzestanProvinceShushtar,
      iranKhuzestanProvinceSusangerd
    ]);
const Region iranKohgiluyehAandBoyerHypAhmadProvince = Region(
    id: 3926,
    parentId: 103,
    longitude: 50.8456323,
    latitude: 30.724586,
    name: "Kohgiluyeh and Boyer-Ahmad Province",
    type: null,
    stateCode: "17",
    cities: [
      iranKohgiluyehAandBoyerHypAhmadProvinceDehdasht,
      iranKohgiluyehAandBoyerHypAhmadProvinceDogonbadan,
      iranKohgiluyehAandBoyerHypAhmadProvinceLandeh,
      iranKohgiluyehAandBoyerHypAhmadProvinceShahrestanHypeBahmai,
      iranKohgiluyehAandBoyerHypAhmadProvinceShahrestanHypeBasht,
      iranKohgiluyehAandBoyerHypAhmadProvinceShahrestanHypeBowyerAhmad,
      iranKohgiluyehAandBoyerHypAhmadProvinceShahrestanHypeCharam,
      iranKohgiluyehAandBoyerHypAhmadProvinceShahrestanHypeDana,
      iranKohgiluyehAandBoyerHypAhmadProvinceShahrestanHypeGachsaran,
      iranKohgiluyehAandBoyerHypAhmadProvinceShahrestanHypeKohgiluyeh,
      iranKohgiluyehAandBoyerHypAhmadProvinceYasuj
    ]);
const Region iranKurdistanProvince = Region(
    id: 3935,
    parentId: 103,
    longitude: 47.1362125,
    latitude: 35.9553579,
    name: "Kurdistan Province",
    type: null,
    stateCode: "12",
    cities: [
      iranKurdistanProvinceBaneh,
      iranKurdistanProvinceBijar,
      iranKurdistanProvinceKamyaran,
      iranKurdistanProvinceMarivan,
      iranKurdistanProvinceQorveh,
      iranKurdistanProvinceSanandaj,
      iranKurdistanProvinceSaqqez,
      iranKurdistanProvinceShahrestanHypeBaneh,
      iranKurdistanProvinceShahrestanHypeBijar,
      iranKurdistanProvinceShahrestanHypeDehgolan,
      iranKurdistanProvinceShahrestanHypeDivandarreh,
      iranKurdistanProvinceShahrestanHypeKamyaran,
      iranKurdistanProvinceShahrestanHypeMarivan,
      iranKurdistanProvinceShahrestanHypeSarvabad
    ]);
const Region iranLorestanProvince = Region(
    id: 3928,
    parentId: 103,
    longitude: 48.3988186,
    latitude: 33.5818394,
    name: "Lorestan Province",
    type: null,
    stateCode: "15",
    cities: [
      iranLorestanProvinceAleshtar,
      iranLorestanProvinceAligudarz,
      iranLorestanProvinceAzna,
      iranLorestanProvinceBorujerd,
      iranLorestanProvinceDelfan,
      iranLorestanProvinceKhorramabad,
      iranLorestanProvinceKuhdasht,
      iranLorestanProvinceNurabad,
      iranLorestanProvincePolHypeDokhtar,
      iranLorestanProvinceRumeshkhanCounty,
      iranLorestanProvinceSelseleh,
      iranLorestanProvinceShahrestanHypeAligudarz,
      iranLorestanProvinceShahrestanHypeAzna,
      iranLorestanProvinceShahrestanHypeBorujerd,
      iranLorestanProvinceShahrestanHypeDureh,
      iranLorestanProvinceShahrestanHypeKhorramabad,
      iranLorestanProvinceShahrestanHypeKuhdasht,
      iranLorestanProvinceVasian
    ]);
const Region iranMarkaziProvince = Region(
    id: 3916,
    parentId: 103,
    longitude: 49.8547266,
    latitude: 34.612305,
    name: "Markazi Province",
    type: null,
    stateCode: "00",
    cities: [
      iranMarkaziProvinceAbyek,
      iranMarkaziProvinceArak,
      iranMarkaziProvinceDelijan,
      iranMarkaziProvinceKhomeyn,
      iranMarkaziProvinceKomijan,
      iranMarkaziProvinceSaveh,
      iranMarkaziProvinceShahrestanHypeArak,
      iranMarkaziProvinceShahrestanHypeAshtian,
      iranMarkaziProvinceShahrestanHypeDelijan,
      iranMarkaziProvinceShahrestanHypeFarahan,
      iranMarkaziProvinceShahrestanHypeKhondab,
      iranMarkaziProvinceShahrestanHypeKomijan,
      iranMarkaziProvinceShahrestanHypeMahallat,
      iranMarkaziProvinceShahrestanHypeSaveh,
      iranMarkaziProvinceShahrestanHypeShazand,
      iranMarkaziProvinceShahrestanHypeZarandiyeh,
      iranMarkaziProvinceTafresh
    ]);
const Region iranMazandaranProvince = Region(
    id: 3938,
    parentId: 103,
    longitude: 52.5318604,
    latitude: 36.2262393,
    name: "Mazandaran Province",
    type: null,
    stateCode: "02",
    cities: [
      iranMazandaranProvinceAmol,
      iranMazandaranProvinceBabol,
      iranMazandaranProvinceBabolsar,
      iranMazandaranProvinceBehshahr,
      iranMazandaranProvinceChalus,
      iranMazandaranProvinceFereydunkenar,
      iranMazandaranProvinceJuybar,
      iranMazandaranProvinceNashtarud,
      iranMazandaranProvinceNeka,
      iranMazandaranProvinceNowshahr,
      iranMazandaranProvinceSari,
      iranMazandaranProvinceSavadkuhHypeShomali,
      iranMazandaranProvinceShahrestanHypeAbbasabad,
      iranMazandaranProvinceShahrestanHypeAmol,
      iranMazandaranProvinceShahrestanHypeBabol,
      iranMazandaranProvinceShahrestanHypeBabolsar,
      iranMazandaranProvinceShahrestanHypeChalus,
      iranMazandaranProvinceShahrestanHypeFareydunkenar,
      iranMazandaranProvinceShahrestanHypeGalugah,
      iranMazandaranProvinceShahrestanHypeJuybar,
      iranMazandaranProvinceShahrestanHypeKalarDasht,
      iranMazandaranProvinceShahrestanHypeMahmudabad,
      iranMazandaranProvinceShahrestanHypeMiandorud,
      iranMazandaranProvinceShahrestanHypeNeka,
      iranMazandaranProvinceShahrestanHypeNur,
      iranMazandaranProvinceShahrestanHypeQaemShahr,
      iranMazandaranProvinceShahrestanHypeRamsar,
      iranMazandaranProvinceShahrestanHypeSari,
      iranMazandaranProvinceShahrestanHypeSavadkuh,
      iranMazandaranProvinceShahrestanHypeTonekabon,
      iranMazandaranProvinceSimorghCounty,
      iranMazandaranProvinceTonekabon
    ]);
const Region iranNorthKhorasanProvince = Region(
    id: 3942,
    parentId: 103,
    longitude: 57.1013188,
    latitude: 37.4710353,
    name: "North Khorasan Province",
    type: null,
    stateCode: "28",
    cities: [
      iranNorthKhorasanProvinceBojnurd,
      iranNorthKhorasanProvinceEsfarayen,
      iranNorthKhorasanProvinceRazAandJargalan,
      iranNorthKhorasanProvinceShahrestanHypeBojnurd,
      iranNorthKhorasanProvinceShahrestanHypeEsfarayen,
      iranNorthKhorasanProvinceShahrestanHypeFaruj,
      iranNorthKhorasanProvinceShahrestanHypeJajarm,
      iranNorthKhorasanProvinceShahrestanHypeManehVvaSamalqan,
      iranNorthKhorasanProvinceShahrestanHypeShirvan,
      iranNorthKhorasanProvinceShirvan
    ]);
const Region iranQazvinProvince = Region(
    id: 3941,
    parentId: 103,
    longitude: 49.8547266,
    latitude: 36.0881317,
    name: "Qazvin Province",
    type: null,
    stateCode: "26",
    cities: [
      iranQazvinProvinceAlborz,
      iranQazvinProvinceAlvand,
      iranQazvinProvinceAvaj,
      iranQazvinProvinceQazvin,
      iranQazvinProvinceShahrestanHypeBuinZahra,
      iranQazvinProvinceShahrestanHypeQazvin,
      iranQazvinProvinceShahrestanHypeTakestan,
      iranQazvinProvinceTakestan
    ]);
const Region iranQomProvince = Region(
    id: 3922,
    parentId: 103,
    longitude: 50.8746035,
    latitude: 34.6415764,
    name: "Qom Province",
    type: null,
    stateCode: "25",
    cities: [iranQomProvinceQom]);
const Region iranRazaviKhorasanProvince = Region(
    id: 3927,
    parentId: 103,
    longitude: 59.1041758,
    latitude: 35.1020253,
    name: "Razavi Khorasan Province",
    type: null,
    stateCode: "09",
    cities: [
      iranRazaviKhorasanProvinceBardaskan,
      iranRazaviKhorasanProvinceChenaran,
      iranRazaviKhorasanProvinceDargaz,
      iranRazaviKhorasanProvinceDavarzan,
      iranRazaviKhorasanProvinceGonabad,
      iranRazaviKhorasanProvinceJoveyn,
      iranRazaviKhorasanProvinceKashmar,
      iranRazaviKhorasanProvinceMashhad,
      iranRazaviKhorasanProvinceNeyshabur,
      iranRazaviKhorasanProvinceQuchan,
      iranRazaviKhorasanProvinceSabzevar,
      iranRazaviKhorasanProvinceSarakhs,
      iranRazaviKhorasanProvinceShahrestanHypeBajestan,
      iranRazaviKhorasanProvinceShahrestanHypeBakharz,
      iranRazaviKhorasanProvinceShahrestanHypeBinalud,
      iranRazaviKhorasanProvinceShahrestanHypeChenaran,
      iranRazaviKhorasanProvinceShahrestanHypeFariman,
      iranRazaviKhorasanProvinceShahrestanHypeFiruzeh,
      iranRazaviKhorasanProvinceShahrestanHypeGonabad,
      iranRazaviKhorasanProvinceShahrestanHypeJoghatay,
      iranRazaviKhorasanProvinceShahrestanHypeKalat,
      iranRazaviKhorasanProvinceShahrestanHypeKashmar,
      iranRazaviKhorasanProvinceShahrestanHypeKhalilabad,
      iranRazaviKhorasanProvinceShahrestanHypeKhowshab,
      iranRazaviKhorasanProvinceShahrestanHypeKhvaf,
      iranRazaviKhorasanProvinceShahrestanHypeMahVelat,
      iranRazaviKhorasanProvinceShahrestanHypeNeyshabur,
      iranRazaviKhorasanProvinceShahrestanHypeQuchan,
      iranRazaviKhorasanProvinceShahrestanHypeRoshtkhvar,
      iranRazaviKhorasanProvinceShahrestanHypeSabzevar,
      iranRazaviKhorasanProvinceShahrestanHypeTaybad,
      iranRazaviKhorasanProvinceShahrestanHypeTorbatHypeHeydariyeh,
      iranRazaviKhorasanProvinceShahrestanHypeTorbatHypeJam,
      iranRazaviKhorasanProvinceShahrestanHypeZaveh,
      iranRazaviKhorasanProvinceTaybad,
      iranRazaviKhorasanProvinceTorbatHypeHeydariyeh,
      iranRazaviKhorasanProvinceTorbatHypeJam
    ]);
const Region iranSemnanProvince = Region(
    id: 3940,
    parentId: 103,
    longitude: 54.4342138,
    latitude: 35.2255585,
    name: "Semnan Province",
    type: null,
    stateCode: "20",
    cities: [
      iranSemnanProvinceDamghan,
      iranSemnanProvinceIstgahHypeRahAhanHypeGarmsar,
      iranSemnanProvinceMahdishahr,
      iranSemnanProvinceSemnan,
      iranSemnanProvinceShahrestanHypeAradan,
      iranSemnanProvinceShahrestanHypeDamghan,
      iranSemnanProvinceShahrestanHypeGarmsar,
      iranSemnanProvinceShahrestanHypeMayamey,
      iranSemnanProvinceShahrestanHypeSemnan,
      iranSemnanProvinceShahrestanHypeShahrud,
      iranSemnanProvinceShahrud
    ]);
const Region iranSistanAandBaluchestan = Region(
    id: 3931,
    parentId: 103,
    longitude: 60.5820676,
    latitude: 27.5299906,
    name: "Sistan and Baluchestan",
    type: null,
    stateCode: "11",
    cities: [
      iranSistanAandBaluchestanChabahar,
      iranSistanAandBaluchestanFannuj,
      iranSistanAandBaluchestanFanuj,
      iranSistanAandBaluchestanHamoon,
      iranSistanAandBaluchestanIranshahr,
      iranSistanAandBaluchestanKhash,
      iranSistanAandBaluchestanMirjaveh,
      iranSistanAandBaluchestanNikshahr,
      iranSistanAandBaluchestanNimruz,
      iranSistanAandBaluchestanNosratabad,
      iranSistanAandBaluchestanQaserHypeQand,
      iranSistanAandBaluchestanQasrHypeQand,
      iranSistanAandBaluchestanShahrestanHypeChabahar,
      iranSistanAandBaluchestanShahrestanHypeDalgan,
      iranSistanAandBaluchestanShahrestanHypeHirmand,
      iranSistanAandBaluchestanShahrestanHypeIranshahr,
      iranSistanAandBaluchestanShahrestanHypeKhash,
      iranSistanAandBaluchestanShahrestanHypeKonarak,
      iranSistanAandBaluchestanShahrestanHypeMehrestan,
      iranSistanAandBaluchestanShahrestanHypeNikshahr,
      iranSistanAandBaluchestanShahrestanHypeSaravan,
      iranSistanAandBaluchestanShahrestanHypeSarbaz,
      iranSistanAandBaluchestanShahrestanHypeSibVvaSuran,
      iranSistanAandBaluchestanShahrestanHypeZabol,
      iranSistanAandBaluchestanShahrestanHypeZahedan,
      iranSistanAandBaluchestanZabol,
      iranSistanAandBaluchestanZahedan,
      iranSistanAandBaluchestanZehak
    ]);
const Region iranSouthKhorasanProvince = Region(
    id: 3930,
    parentId: 103,
    longitude: 59.1041758,
    latitude: 32.5175643,
    name: "South Khorasan Province",
    type: null,
    stateCode: "29",
    cities: [
      iranSouthKhorasanProvinceBirjand,
      iranSouthKhorasanProvinceBoshruyeh,
      iranSouthKhorasanProvinceQaen,
      iranSouthKhorasanProvinceShahrestanHypeBirjand,
      iranSouthKhorasanProvinceShahrestanHypeDarmian,
      iranSouthKhorasanProvinceShahrestanHypeKhusf,
      iranSouthKhorasanProvinceShahrestanHypeNehbandan,
      iranSouthKhorasanProvinceShahrestanHypeQaen,
      iranSouthKhorasanProvinceShahrestanHypeSarayan,
      iranSouthKhorasanProvinceShahrestanHypeSarbisheh,
      iranSouthKhorasanProvinceShahrestanHypeZirkuh,
      iranSouthKhorasanProvinceTabas
    ]);
const Region iranTehranProvince = Region(
    id: 3945,
    parentId: 103,
    longitude: 51.381653,
    latitude: 35.7248416,
    name: "Tehran Province",
    type: null,
    stateCode: "23",
    cities: [
      iranTehranProvinceDamavand,
      iranTehranProvinceEqbaliyeh,
      iranTehranProvinceEslamshahr,
      iranTehranProvinceMalard,
      iranTehranProvincePardis,
      iranTehranProvincePishva,
      iranTehranProvinceQarchak,
      iranTehranProvinceQods,
      iranTehranProvinceRey,
      iranTehranProvinceRobatKarim,
      iranTehranProvinceShahrakHypeEmamHasan,
      iranTehranProvinceShahreJadideAndisheh,
      iranTehranProvinceShahrestanHypeBaharestan,
      iranTehranProvinceShahrestanHypeDamavand,
      iranTehranProvinceShahrestanHypeEslamshahr,
      iranTehranProvinceShahrestanHypeFiruzkuh,
      iranTehranProvinceShahrestanHypeMalard,
      iranTehranProvinceShahrestanHypePakdasht,
      iranTehranProvinceShahrestanHypePishva,
      iranTehranProvinceShahrestanHypeRobatKarim,
      iranTehranProvinceShahrestanHypeShahriar,
      iranTehranProvinceShahrestanHypeShemiranat,
      iranTehranProvinceShahrestanHypeTehran,
      iranTehranProvinceShahrestanHypeVaramin,
      iranTehranProvinceShahriar,
      iranTehranProvinceSharifabad,
      iranTehranProvinceSolehBon,
      iranTehranProvinceTalebAabad,
      iranTehranProvinceTehran,
      iranTehranProvinceVaramin
    ]);
const Region iranWestAzarbaijanProvince = Region(
    id: 3924,
    parentId: 103,
    longitude: 45.0,
    latitude: 37.4550062,
    name: "West Azarbaijan Province",
    type: null,
    stateCode: "04",
    cities: [
      iranWestAzarbaijanProvinceBukan,
      iranWestAzarbaijanProvinceChaypareh,
      iranWestAzarbaijanProvinceKhowy,
      iranWestAzarbaijanProvinceMahabad,
      iranWestAzarbaijanProvinceMiandoab,
      iranWestAzarbaijanProvinceNaqadeh,
      iranWestAzarbaijanProvinceOrumiyeh,
      iranWestAzarbaijanProvinceOshnaviyeh,
      iranWestAzarbaijanProvincePiranshahr,
      iranWestAzarbaijanProvincePoldasht,
      iranWestAzarbaijanProvinceQarahZiaOodDin,
      iranWestAzarbaijanProvinceSalmas,
      iranWestAzarbaijanProvinceSardasht,
      iranWestAzarbaijanProvinceShahinDezh,
      iranWestAzarbaijanProvinceShahrestanHypeBukan,
      iranWestAzarbaijanProvinceShahrestanHypeChaldoran,
      iranWestAzarbaijanProvinceShahrestanHypeMahabad,
      iranWestAzarbaijanProvinceShahrestanHypeMaku,
      iranWestAzarbaijanProvinceShahrestanHypeMiandoab,
      iranWestAzarbaijanProvinceShahrestanHypeOrumiyeh,
      iranWestAzarbaijanProvinceShahrestanHypeOshnaviyeh,
      iranWestAzarbaijanProvinceShahrestanHypePiranshahr,
      iranWestAzarbaijanProvinceShahrestanHypeSalmas,
      iranWestAzarbaijanProvinceShahrestanHypeShahinDezh,
      iranWestAzarbaijanProvinceShahrestanHypeTakab,
      iranWestAzarbaijanProvinceTakab
    ]);
const Region iranYazdProvince = Region(
    id: 3936,
    parentId: 103,
    longitude: 54.4342138,
    latitude: 32.1006387,
    name: "Yazd Province",
    type: null,
    stateCode: "21",
    cities: [
      iranYazdProvinceArdakan,
      iranYazdProvinceBafq,
      iranYazdProvinceKhavasKuh,
      iranYazdProvinceMahriz,
      iranYazdProvinceMeybod,
      iranYazdProvinceShahrestanHypeAbarkuh,
      iranYazdProvinceShahrestanHypeArdakan,
      iranYazdProvinceShahrestanHypeAshkezar,
      iranYazdProvinceShahrestanHypeBafq,
      iranYazdProvinceShahrestanHypeBehabad,
      iranYazdProvinceShahrestanHypeKhatam,
      iranYazdProvinceShahrestanHypeMehriz,
      iranYazdProvinceShahrestanHypeYazd,
      iranYazdProvinceTabas,
      iranYazdProvinceTaft,
      iranYazdProvinceYazd
    ]);
const Region iranZanjanProvince = Region(
    id: 3925,
    parentId: 103,
    longitude: 48.3988186,
    latitude: 36.5018185,
    name: "Zanjan Province",
    type: null,
    stateCode: "19",
    cities: [
      iranZanjanProvinceAbhar,
      iranZanjanProvinceAlvand,
      iranZanjanProvinceKhorramdarreh,
      iranZanjanProvinceShahrestanHypeIjrud,
      iranZanjanProvinceShahrestanHypeKhodabandeh,
      iranZanjanProvinceShahrestanHypeMahneshan,
      iranZanjanProvinceShahrestanHypeTarom,
      iranZanjanProvinceShahrestanHypeZanjan,
      iranZanjanProvinceSoltaniyeh,
      iranZanjanProvinceZanjan
    ]);

const iranStates = <int, Region>{
  3929: iranAlborzProvince,
  3934: iranArdabilProvince,
  3932: iranBushehrProvince,
  3921: iranChaharmahalAandBakhtiariProvince,
  3944: iranEastAzerbaijanProvince,
  3939: iranFarsProvince,
  3920: iranGilanProvince,
  3933: iranGolestanProvince,
  4920: iranHamadanProvince,
  3937: iranHormozganProvince,
  3918: iranIlamProvince,
  3923: iranIsfahanProvince,
  3943: iranKermanProvince,
  3919: iranKermanshahProvince,
  3917: iranKhuzestanProvince,
  3926: iranKohgiluyehAandBoyerHypAhmadProvince,
  3935: iranKurdistanProvince,
  3928: iranLorestanProvince,
  3916: iranMarkaziProvince,
  3938: iranMazandaranProvince,
  3942: iranNorthKhorasanProvince,
  3941: iranQazvinProvince,
  3922: iranQomProvince,
  3927: iranRazaviKhorasanProvince,
  3940: iranSemnanProvince,
  3931: iranSistanAandBaluchestan,
  3930: iranSouthKhorasanProvince,
  3945: iranTehranProvince,
  3924: iranWestAzarbaijanProvince,
  3936: iranYazdProvince,
  3925: iranZanjanProvince
};
