/// Access to known geographies in Ireland and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'ireland_cities.dart';

/// The 29 regions of `🇮🇪 Ireland`
const Region irelandConnacht = Region(id: 1087, parentId: 105, longitude: -8.9584481, latitude: 53.8376243,
          name: "Connacht", type: null, stateCode: "C",
          cities: [
            irelandConnachtAthenry,
            irelandConnachtBallaghaderreen,
            irelandConnachtBallina,
            irelandConnachtBallinasloe,
            irelandConnachtBallinrobe,
            irelandConnachtBallisodare,
            irelandConnachtBallyhaunis,
            irelandConnachtBallymote,
            irelandConnachtBearna,
            irelandConnachtBelmullet,
            irelandConnachtBoyle,
            irelandConnachtCarrickHyponHypShannon,
            irelandConnachtCastlebar,
            irelandConnachtCastlerea,
            irelandConnachtClaregalway,
            irelandConnachtClaremorris,
            irelandConnachtClifden,
            irelandConnachtCollooney,
            irelandConnachtCountyGalway,
            irelandConnachtCountyLeitrim,
            irelandConnachtCrossmolina,
            irelandConnachtFoxford,
            irelandConnachtGaillimh,
            irelandConnachtGalwayCity,
            irelandConnachtGort,
            irelandConnachtInishcrone,
            irelandConnachtKiltamagh,
            irelandConnachtKinlough,
            irelandConnachtLoughrea,
            irelandConnachtManorhamilton,
            irelandConnachtMayoCounty,
            irelandConnachtMoycullen,
            irelandConnachtOranmore,
            irelandConnachtOughterard,
            irelandConnachtPortumna,
            irelandConnachtRoscommon,
            irelandConnachtSligo,
            irelandConnachtStrandhill,
            irelandConnachtSwinford,
            irelandConnachtTobercurry,
            irelandConnachtTuam,
            irelandConnachtWestport
          ]);
const Region irelandCountyCarlow = Region(id: 1095, parentId: 105, longitude: -6.8108295, latitude: 52.7232217,
          name: "County Carlow", type: null, stateCode: "CW",
          cities: []);
const Region irelandCountyCavan = Region(id: 1088, parentId: 105, longitude: -7.2996623, latitude: 53.9765424,
          name: "County Cavan", type: null, stateCode: "CN",
          cities: []);
const Region irelandCountyClare = Region(id: 1091, parentId: 105, longitude: -87.899581, latitude: 43.04664,
          name: "County Clare", type: null, stateCode: "CE",
          cities: []);
const Region irelandCountyCork = Region(id: 1074, parentId: 105, longitude: -8.4756035, latitude: 51.8985143,
          name: "County Cork", type: null, stateCode: "CO",
          cities: []);
const Region irelandCountyDonegal = Region(id: 1071, parentId: 105, longitude: -8.1040967, latitude: 54.6548993,
          name: "County Donegal", type: null, stateCode: "DL",
          cities: []);
const Region irelandCountyDublin = Region(id: 1072, parentId: 105, longitude: -6.2603097, latitude: 53.3498053,
          name: "County Dublin", type: null, stateCode: "D",
          cities: []);
const Region irelandCountyGalway = Region(id: 1079, parentId: 105, longitude: -8.8534113, latitude: 53.3564509,
          name: "County Galway", type: null, stateCode: "G",
          cities: []);
const Region irelandCountyKerry = Region(id: 1077, parentId: 105, longitude: -9.5668633, latitude: 52.1544607,
          name: "County Kerry", type: null, stateCode: "KY",
          cities: []);
const Region irelandCountyKildare = Region(id: 1082, parentId: 105, longitude: -6.8194708, latitude: 53.2120434,
          name: "County Kildare", type: null, stateCode: "KE",
          cities: []);
const Region irelandCountyKilkenny = Region(id: 1090, parentId: 105, longitude: -7.218002, latitude: 52.5776957,
          name: "County Kilkenny", type: null, stateCode: "KK",
          cities: []);
const Region irelandCountyLaois = Region(id: 1096, parentId: 105, longitude: -7.3323007, latitude: 52.994295,
          name: "County Laois", type: null, stateCode: "LS",
          cities: []);
const Region irelandCountyLimerick = Region(id: 1094, parentId: 105, longitude: -8.7474955, latitude: 52.5090517,
          name: "County Limerick", type: null, stateCode: "LK",
          cities: []);
const Region irelandCountyLongford = Region(id: 1076, parentId: 105, longitude: -7.7931527, latitude: 53.7274982,
          name: "County Longford", type: null, stateCode: "LD",
          cities: []);
const Region irelandCountyLouth = Region(id: 1083, parentId: 105, longitude: -6.4889423, latitude: 53.9252324,
          name: "County Louth", type: null, stateCode: "LH",
          cities: []);
const Region irelandCountyMayo = Region(id: 1084, parentId: 105, longitude: -9.4289369, latitude: 54.0152604,
          name: "County Mayo", type: null, stateCode: "MO",
          cities: []);
const Region irelandCountyMeath = Region(id: 1092, parentId: 105, longitude: -6.6564169, latitude: 53.605548,
          name: "County Meath", type: null, stateCode: "MH",
          cities: []);
const Region irelandCountyMonaghan = Region(id: 1075, parentId: 105, longitude: -6.9683132, latitude: 54.2492046,
          name: "County Monaghan", type: null, stateCode: "MN",
          cities: []);
const Region irelandCountyOffaly = Region(id: 1078, parentId: 105, longitude: -7.7122229, latitude: 53.2356871,
          name: "County Offaly", type: null, stateCode: "OY",
          cities: []);
const Region irelandCountyRoscommon = Region(id: 1081, parentId: 105, longitude: -8.2681621, latitude: 53.7592604,
          name: "County Roscommon", type: null, stateCode: "RN",
          cities: []);
const Region irelandCountySligo = Region(id: 1070, parentId: 105, longitude: -8.6064532, latitude: 54.1553277,
          name: "County Sligo", type: null, stateCode: "SO",
          cities: []);
const Region irelandCountyTipperary = Region(id: 1069, parentId: 105, longitude: -8.1618514, latitude: 52.4737894,
          name: "County Tipperary", type: null, stateCode: "TA",
          cities: []);
const Region irelandCountyWaterford = Region(id: 1089, parentId: 105, longitude: -7.6227512, latitude: 52.1943549,
          name: "County Waterford", type: null, stateCode: "WD",
          cities: []);
const Region irelandCountyWestmeath = Region(id: 1097, parentId: 105, longitude: -7.4653217, latitude: 53.5345308,
          name: "County Westmeath", type: null, stateCode: "WH",
          cities: []);
const Region irelandCountyWexford = Region(id: 1093, parentId: 105, longitude: -6.5839913, latitude: 52.4793603,
          name: "County Wexford", type: null, stateCode: "WX",
          cities: []);
const Region irelandCountyWicklow = Region(id: 1085, parentId: 105, longitude: -6.3672543, latitude: 52.9862313,
          name: "County Wicklow", type: null, stateCode: "WW",
          cities: []);
const Region irelandLeinster = Region(id: 1073, parentId: 105, longitude: -7.5140841, latitude: 53.3271538,
          name: "Leinster", type: null, stateCode: "L",
          cities: [
            irelandLeinsterAbbeyleix,
            irelandLeinsterAnIarmhi,
            irelandLeinsterAnLongfort,
            irelandLeinsterAnMhi,
            irelandLeinsterAnMuileannGgCearr,
            irelandLeinsterAnRos,
            irelandLeinsterArdee,
            irelandLeinsterArklow,
            irelandLeinsterArtane,
            irelandLeinsterAshbourne,
            irelandLeinsterAshford,
            irelandLeinsterAthboy,
            irelandLeinsterAthgarvan,
            irelandLeinsterAthlone,
            irelandLeinsterAthy,
            irelandLeinsterAughrim,
            irelandLeinsterBagenalstown,
            irelandLeinsterBalally,
            irelandLeinsterBalbriggan,
            irelandLeinsterBaldoyle,
            irelandLeinsterBallinroad,
            irelandLeinsterBallinteer,
            irelandLeinsterBallivor,
            irelandLeinsterBallyboden,
            irelandLeinsterBallyfermot,
            irelandLeinsterBallygerry,
            irelandLeinsterBallylinan,
            irelandLeinsterBallymahon,
            irelandLeinsterBallymun,
            irelandLeinsterBallyragget,
            irelandLeinsterBalrothery,
            irelandLeinsterBaltinglass,
            irelandLeinsterBanagher,
            irelandLeinsterBayside,
            irelandLeinsterBeaumont,
            irelandLeinsterBirr,
            irelandLeinsterBlackrock,
            irelandLeinsterBlanchardstown,
            irelandLeinsterBlessington,
            irelandLeinsterBonnybrook,
            irelandLeinsterBooterstown,
            irelandLeinsterBray,
            irelandLeinsterBunclody,
            irelandLeinsterCabinteely,
            irelandLeinsterCabra,
            irelandLeinsterCallan,
            irelandLeinsterCarlingford,
            irelandLeinsterCarlow,
            irelandLeinsterCarnew,
            irelandLeinsterCastlebellingham,
            irelandLeinsterCastlebridge,
            irelandLeinsterCastlecomer,
            irelandLeinsterCastledermot,
            irelandLeinsterCastleknock,
            irelandLeinsterCastlepollard,
            irelandLeinsterCastletown,
            irelandLeinsterCelbridge,
            irelandLeinsterChapelizod,
            irelandLeinsterCharlesland,
            irelandLeinsterCherryOrchard,
            irelandLeinsterCherryville,
            irelandLeinsterClane,
            irelandLeinsterClara,
            irelandLeinsterClogherhead,
            irelandLeinsterClondalkin,
            irelandLeinsterClonskeagh,
            irelandLeinsterConfey,
            irelandLeinsterCoolock,
            irelandLeinsterCountyCarlow,
            irelandLeinsterCourtown,
            irelandLeinsterCrumlin,
            irelandLeinsterDaingean,
            irelandLeinsterDalkey,
            irelandLeinsterDarndale,
            irelandLeinsterDerrinturn,
            irelandLeinsterDollymount,
            irelandLeinsterDonabate,
            irelandLeinsterDonaghmede,
            irelandLeinsterDonnybrook,
            irelandLeinsterDonnycarney,
            irelandLeinsterDrogheda,
            irelandLeinsterDroicheadNua,
            irelandLeinsterDromiskin,
            irelandLeinsterDrumcondra,
            irelandLeinsterDublin,
            irelandLeinsterDublinCity,
            irelandLeinsterDuleek,
            irelandLeinsterDunLaoghaire,
            irelandLeinsterDunLaoghaireHypRathdown,
            irelandLeinsterDunboyne,
            irelandLeinsterDundalk,
            irelandLeinsterDundrum,
            irelandLeinsterDunleer,
            irelandLeinsterDunshaughlin,
            irelandLeinsterEadestown,
            irelandLeinsterEdenderry,
            irelandLeinsterEdgeworthstown,
            irelandLeinsterEnfield,
            irelandLeinsterEnniscorthy,
            irelandLeinsterEnniskerry,
            irelandLeinsterFairview,
            irelandLeinsterFerbane,
            irelandLeinsterFerns,
            irelandLeinsterFingalCounty,
            irelandLeinsterFinglas,
            irelandLeinsterFirhouse,
            irelandLeinsterFoxrock,
            irelandLeinsterGlasnevin,
            irelandLeinsterGorey,
            irelandLeinsterGraiguenamanagh,
            irelandLeinsterGranard,
            irelandLeinsterGreenhills,
            irelandLeinsterGreystones,
            irelandLeinsterHartstown,
            irelandLeinsterHowth,
            irelandLeinsterJobstown,
            irelandLeinsterJohnstown,
            irelandLeinsterKells,
            irelandLeinsterKentstown,
            irelandLeinsterKilbeggan,
            irelandLeinsterKilcock,
            irelandLeinsterKilcoole,
            irelandLeinsterKilcullen,
            irelandLeinsterKildare,
            irelandLeinsterKilkenny,
            irelandLeinsterKill,
            irelandLeinsterKillester,
            irelandLeinsterKilmacanoge,
            irelandLeinsterKilpedder,
            irelandLeinsterKilquade,
            irelandLeinsterKinnegad,
            irelandLeinsterKinsealyHypDrinan,
            irelandLeinsterKnocklyon,
            irelandLeinsterLanesborough,
            irelandLeinsterLaois,
            irelandLeinsterLaytown,
            irelandLeinsterLeixlip,
            irelandLeinsterLittleBray,
            irelandLeinsterLochGarman,
            irelandLeinsterLongford,
            irelandLeinsterLongwood,
            irelandLeinsterLoughlinstown,
            irelandLeinsterLu,
            irelandLeinsterLucan,
            irelandLeinsterLusk,
            irelandLeinsterMalahide,
            irelandLeinsterMarino,
            irelandLeinsterMaynooth,
            irelandLeinsterMilltown,
            irelandLeinsterMoate,
            irelandLeinsterMonasterevin,
            irelandLeinsterMonkstown,
            irelandLeinsterMooncoin,
            irelandLeinsterMoone,
            irelandLeinsterMountMerrion,
            irelandLeinsterMountmellick,
            irelandLeinsterMountrath,
            irelandLeinsterNaas,
            irelandLeinsterNavan,
            irelandLeinsterNewRoss,
            irelandLeinsterNewcastle,
            irelandLeinsterNewtownTrim,
            irelandLeinsterNewtownmountkennedy,
            irelandLeinsterOldKilcullen,
            irelandLeinsterOldbawn,
            irelandLeinsterOldcastle,
            irelandLeinsterPalmerstown,
            irelandLeinsterPiltown,
            irelandLeinsterPortarlington,
            irelandLeinsterPortlaoise,
            irelandLeinsterPortmarnock,
            irelandLeinsterPortraine,
            irelandLeinsterProsperous,
            irelandLeinsterRaheny,
            irelandLeinsterRathangan,
            irelandLeinsterRathcoole,
            irelandLeinsterRathdowney,
            irelandLeinsterRathdrum,
            irelandLeinsterRathgar,
            irelandLeinsterRathmines,
            irelandLeinsterRathnew,
            irelandLeinsterRathwire,
            irelandLeinsterRatoath,
            irelandLeinsterRialto,
            irelandLeinsterRingsend,
            irelandLeinsterRochfortbridge,
            irelandLeinsterRosslare,
            irelandLeinsterSaggart,
            irelandLeinsterSallins,
            irelandLeinsterSallynoggin,
            irelandLeinsterSandyford,
            irelandLeinsterSandymount,
            irelandLeinsterShankill,
            irelandLeinsterSkerries,
            irelandLeinsterSlane,
            irelandLeinsterSouthDublin,
            irelandLeinsterStamullin,
            irelandLeinsterStradbally,
            irelandLeinsterSutton,
            irelandLeinsterSwords,
            irelandLeinsterTallaght,
            irelandLeinsterTempleogue,
            irelandLeinsterTerenure,
            irelandLeinsterTermonfeckin,
            irelandLeinsterThomastown,
            irelandLeinsterTrim,
            irelandLeinsterTullamore,
            irelandLeinsterTullow,
            irelandLeinsterTullyallen,
            irelandLeinsterUibhFhaili,
            irelandLeinsterValleymount,
            irelandLeinsterWicklow
          ]);
const Region irelandMunster = Region(id: 1080, parentId: 105, longitude: 7.584532, latitude: 51.9471197,
          name: "Munster", type: null, stateCode: "M",
          cities: [
            irelandMunsterAbbeyfeale,
            irelandMunsterAdare,
            irelandMunsterAghada,
            irelandMunsterAnClar,
            irelandMunsterAnnacotty,
            irelandMunsterArdnacrusha,
            irelandMunsterAskeaton,
            irelandMunsterBallina,
            irelandMunsterBallybunnion,
            irelandMunsterBandon,
            irelandMunsterBantry,
            irelandMunsterBlarney,
            irelandMunsterCaherconlish,
            irelandMunsterCahersiveen,
            irelandMunsterCahir,
            irelandMunsterCarrickHyponHypSuir,
            irelandMunsterCarrigaline,
            irelandMunsterCarrigtwohill,
            irelandMunsterCashel,
            irelandMunsterCastleconnell,
            irelandMunsterCastleisland,
            irelandMunsterCastlemartyr,
            irelandMunsterCiarrai,
            irelandMunsterCillAirne,
            irelandMunsterClonakilty,
            irelandMunsterCloyne,
            irelandMunsterCluainMeala,
            irelandMunsterCobh,
            irelandMunsterCork,
            irelandMunsterCorkCity,
            irelandMunsterCountyCork,
            irelandMunsterCountyTipperary,
            irelandMunsterCroom,
            irelandMunsterCrosshaven,
            irelandMunsterDerry,
            irelandMunsterDingle,
            irelandMunsterDungarvan,
            irelandMunsterDunmanway,
            irelandMunsterDunmoreEast,
            irelandMunsterEnnis,
            irelandMunsterFermoy,
            irelandMunsterFethard,
            irelandMunsterKanturk,
            irelandMunsterKenmare,
            irelandMunsterKillaloe,
            irelandMunsterKillorglin,
            irelandMunsterKillumney,
            irelandMunsterKilmallock,
            irelandMunsterKilrush,
            irelandMunsterKinsale,
            irelandMunsterListowel,
            irelandMunsterLuimneach,
            irelandMunsterMacroom,
            irelandMunsterMallow,
            irelandMunsterMidleton,
            irelandMunsterMillstreet,
            irelandMunsterMitchelstown,
            irelandMunsterMoroe,
            irelandMunsterMoyross,
            irelandMunsterNenagh,
            irelandMunsterNenaghBridge,
            irelandMunsterNewcastleWest,
            irelandMunsterNewmarketOonFergus,
            irelandMunsterNewport,
            irelandMunsterPassageWest,
            irelandMunsterPortlaw,
            irelandMunsterRathLuirc,
            irelandMunsterRathcormac,
            irelandMunsterRathkeale,
            irelandMunsterRoscrea,
            irelandMunsterShannon,
            irelandMunsterSixmilebridge,
            irelandMunsterSkibbereen,
            irelandMunsterTemplemore,
            irelandMunsterThurles,
            irelandMunsterTipperary,
            irelandMunsterTower,
            irelandMunsterTraMhor,
            irelandMunsterTralee,
            irelandMunsterWaterford,
            irelandMunsterWatergrasshill,
            irelandMunsterWhitegate,
            irelandMunsterYoughal
          ]);
const Region irelandUlster = Region(id: 1086, parentId: 105, longitude: -6.9612273, latitude: 54.7616555,
          name: "Ulster", type: null, stateCode: "U",
          cities: [
            irelandUlsterAnCabhan,
            irelandUlsterBailieborough,
            irelandUlsterBallybofey,
            irelandUlsterBallyconnell,
            irelandUlsterBallyjamesduff,
            irelandUlsterBallyshannon,
            irelandUlsterBelturbet,
            irelandUlsterBuncrana,
            irelandUlsterBundoran,
            irelandUlsterCarndonagh,
            irelandUlsterCarrickmacross,
            irelandUlsterCastleblayney,
            irelandUlsterCavan,
            irelandUlsterClones,
            irelandUlsterConvoy,
            irelandUlsterCootehill,
            irelandUlsterCountyDonegal,
            irelandUlsterCountyMonaghan,
            irelandUlsterDerrybeg,
            irelandUlsterDonegal,
            irelandUlsterDungloe,
            irelandUlsterDunlewy,
            irelandUlsterGweedore,
            irelandUlsterKillybegs,
            irelandUlsterKingscourt,
            irelandUlsterLeifear,
            irelandUlsterLetterkenny,
            irelandUlsterMonaghan,
            irelandUlsterMoville,
            irelandUlsterMuff,
            irelandUlsterMullagh,
            irelandUlsterNewtownCunningham,
            irelandUlsterRamelton,
            irelandUlsterRaphoe,
            irelandUlsterVirginia
          ]);

const irelandStates = <int, Region>{
    1087: irelandConnacht,
    1095: irelandCountyCarlow,
    1088: irelandCountyCavan,
    1091: irelandCountyClare,
    1074: irelandCountyCork,
    1071: irelandCountyDonegal,
    1072: irelandCountyDublin,
    1079: irelandCountyGalway,
    1077: irelandCountyKerry,
    1082: irelandCountyKildare,
    1090: irelandCountyKilkenny,
    1096: irelandCountyLaois,
    1094: irelandCountyLimerick,
    1076: irelandCountyLongford,
    1083: irelandCountyLouth,
    1084: irelandCountyMayo,
    1092: irelandCountyMeath,
    1075: irelandCountyMonaghan,
    1078: irelandCountyOffaly,
    1081: irelandCountyRoscommon,
    1070: irelandCountySligo,
    1069: irelandCountyTipperary,
    1089: irelandCountyWaterford,
    1097: irelandCountyWestmeath,
    1093: irelandCountyWexford,
    1085: irelandCountyWicklow,
    1073: irelandLeinster,
    1080: irelandMunster,
    1086: irelandUlster
  };
