/// Access to known geographies in Israel and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'israel_cities.dart';

/// The 6 regions of `🇮🇱 Israel`
const Region israelCentralDistrict = Region(
    id: 1367,
    parentId: 106,
    longitude: -122.2964235,
    latitude: 47.6087583,
    name: "Central District",
    type: null,
    stateCode: "M",
    cities: [
      israelCentralDistrictBetDagan,
      israelCentralDistrictBetYizhaq,
      israelCentralDistrictBneiAyish,
      israelCentralDistrictElyakhin,
      israelCentralDistrictEtTaiyiba,
      israelCentralDistrictEvenYehuda,
      israelCentralDistrictGanYavne,
      israelCentralDistrictGaneiTikva,
      israelCentralDistrictGedera,
      israelCentralDistrictHodHaSharon,
      israelCentralDistrictJaljulya,
      israelCentralDistrictKafrQasim,
      israelCentralDistrictKefarHabad,
      israelCentralDistrictKefarYona,
      israelCentralDistrictKfarSaba,
      israelCentralDistrictLapid,
      israelCentralDistrictLod,
      israelCentralDistrictMazkeretBatya,
      israelCentralDistrictModiinMakkabbimReut,
      israelCentralDistrictNehalim,
      israelCentralDistrictNessZiona,
      israelCentralDistrictNetanya,
      israelCentralDistrictNirit,
      israelCentralDistrictNofAyalon,
      israelCentralDistrictNordiyya,
      israelCentralDistrictPardesiyya,
      israelCentralDistrictPetahTiqwa,
      israelCentralDistrictQalansuwa,
      israelCentralDistrictRaanana,
      israelCentralDistrictRamla,
      israelCentralDistrictRehovot,
      israelCentralDistrictRishonLeZiyyon,
      israelCentralDistrictRoshHaAyin,
      israelCentralDistrictSavyon,
      israelCentralDistrictShoham,
      israelCentralDistrictTelMond,
      israelCentralDistrictTirah,
      israelCentralDistrictYavne,
      israelCentralDistrictYehud,
      israelCentralDistrictZurMoshe
    ]);
const Region israelHaifaDistrict = Region(
    id: 1369,
    parentId: 106,
    longitude: 34.994751,
    latitude: 32.4814111,
    name: "Haifa District",
    type: null,
    stateCode: "HA",
    cities: [
      israelHaifaDistrictAtlit,
      israelHaifaDistrictCaesarea,
      israelHaifaDistrictDaliyatAalKarmel,
      israelHaifaDistrictElFureidis,
      israelHaifaDistrictHadera,
      israelHaifaDistrictHaifa,
      israelHaifaDistrictIbtin,
      israelHaifaDistrictNesher,
      israelHaifaDistrictQiryatAta,
      israelHaifaDistrictQiryatBialik,
      israelHaifaDistrictQiryatMozqin,
      israelHaifaDistrictQiryatYam,
      israelHaifaDistrictRekhasim,
      israelHaifaDistrictTiratKarmel,
      israelHaifaDistrictUmmEelFahm
    ]);
const Region israelJerusalemDistrict = Region(
    id: 1370,
    parentId: 106,
    longitude: 34.994751,
    latitude: 31.7648243,
    name: "Jerusalem District",
    type: null,
    stateCode: "JM",
    cities: [
      israelJerusalemDistrictAbuGhaush,
      israelJerusalemDistrictBetShemesh,
      israelJerusalemDistrictHarAdar,
      israelJerusalemDistrictJerusalem,
      israelJerusalemDistrictMevasseretZiyyon,
      israelJerusalemDistrictModiinIlit,
      israelJerusalemDistrictWestJerusalem,
      israelJerusalemDistrictZurHadassa
    ]);
const Region israelNorthernDistrict = Region(
    id: 1366,
    parentId: 106,
    longitude: -95.9951763,
    latitude: 36.1511864,
    name: "Northern District",
    type: null,
    stateCode: "Z",
    cities: [
      israelNorthernDistrictEilabun,
      israelNorthernDistrictUzeir,
      israelNorthernDistrictAcre,
      israelNorthernDistrictAfula,
      israelNorthernDistrictBasmatTabun,
      israelNorthernDistrictBeitJann,
      israelNorthernDistrictBetShean,
      israelNorthernDistrictBirEelMaksur,
      israelNorthernDistrictBueina,
      israelNorthernDistrictBuqeia,
      israelNorthernDistrictDabburiya,
      israelNorthernDistrictDeirHanna,
      israelNorthernDistrictElMazraa,
      israelNorthernDistrictErReina,
      israelNorthernDistrictEshSheikhDannun,
      israelNorthernDistrictHurfeish,
      israelNorthernDistrictIksal,
      israelNorthernDistrictJish,
      israelNorthernDistrictJudeidaMakr,
      israelNorthernDistrictKabul,
      israelNorthernDistrictKafrKamma,
      israelNorthernDistrictKafrKanna,
      israelNorthernDistrictKafrManda,
      israelNorthernDistrictKafrMisr,
      israelNorthernDistrictKarmiel,
      israelNorthernDistrictKaukabAbuEelHija,
      israelNorthernDistrictKefarRoshHaNiqra,
      israelNorthernDistrictKefarTavor,
      israelNorthernDistrictKefarWeradim,
      israelNorthernDistrictKfarYasif,
      israelNorthernDistrictMmaalotTarshiha,
      israelNorthernDistrictMaghar,
      israelNorthernDistrictMetulla,
      israelNorthernDistrictMiilya,
      israelNorthernDistrictMigdalHaEmeq,
      israelNorthernDistrictNahariyya,
      israelNorthernDistrictNahf,
      israelNorthernDistrictNazareth,
      israelNorthernDistrictNefatAkko,
      israelNorthernDistrictNein,
      israelNorthernDistrictPasuta,
      israelNorthernDistrictQiryatShemona,
      israelNorthernDistrictRamatYishay,
      israelNorthernDistrictRoshPinna,
      israelNorthernDistrictRumatHeib,
      israelNorthernDistrictSafed,
      israelNorthernDistrictSajur,
      israelNorthernDistrictSakhnin,
      israelNorthernDistrictSallama,
      israelNorthernDistrictShelomi,
      israelNorthernDistrictShibli,
      israelNorthernDistrictSulam,
      israelNorthernDistrictTamra,
      israelNorthernDistrictTiberias,
      israelNorthernDistrictTimrat,
      israelNorthernDistrictYavneel
    ]);
const Region israelSouthernDistrict = Region(
    id: 1368,
    parentId: 106,
    longitude: -74.0009059,
    latitude: 40.7137586,
    name: "Southern District",
    type: null,
    stateCode: "D",
    cities: [
      israelSouthernDistrictEnBoqeq,
      israelSouthernDistrictArad,
      israelSouthernDistrictAshdod,
      israelSouthernDistrictAshkelon,
      israelSouthernDistrictBeersheba,
      israelSouthernDistrictDimona,
      israelSouthernDistrictEilat,
      israelSouthernDistrictLehavim,
      israelSouthernDistrictMidreshetBenHypGurion,
      israelSouthernDistrictMitzpeRamon,
      israelSouthernDistrictNetivot,
      israelSouthernDistrictOfaqim,
      israelSouthernDistrictQiryatGat,
      israelSouthernDistrictRahat,
      israelSouthernDistrictSederot,
      israelSouthernDistrictYeroham
    ]);
const Region israelTelAvivDistrict = Region(
    id: 1371,
    parentId: 106,
    longitude: 34.8072165,
    latitude: 32.0929075,
    name: "Tel Aviv District",
    type: null,
    stateCode: "TA",
    cities: [
      israelTelAvivDistrictAzor,
      israelTelAvivDistrictBatYam,
      israelTelAvivDistrictBneiBrak,
      israelTelAvivDistrictGivatShmuel,
      israelTelAvivDistrictGivatayim,
      israelTelAvivDistrictHerzliya,
      israelTelAvivDistrictHerzliyaPituah,
      israelTelAvivDistrictHolon,
      israelTelAvivDistrictJaffa,
      israelTelAvivDistrictKefarShemaryahu,
      israelTelAvivDistrictOrYehuda,
      israelTelAvivDistrictRamatGan,
      israelTelAvivDistrictRamatHaSharon,
      israelTelAvivDistrictTelAviv,
      israelTelAvivDistrictYehudHypMonosson
    ]);

const israelStates = <int, Region>{
  1367: israelCentralDistrict,
  1369: israelHaifaDistrict,
  1370: israelJerusalemDistrict,
  1366: israelNorthernDistrict,
  1368: israelSouthernDistrict,
  1371: israelTelAvivDistrict
};
