/// Access to known geographies in `Jamaica` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'jamaica_cities.dart';

/// The `Clarendon Parish` region in `Jamaica`
const Region jamaicaClarendonParish = Region(
  id: 3753,
  parentId: 108,
  longitude: -77.2405153,
  latitude: 17.9557183,
  name: "Clarendon Parish",
  type: null,
  stateCode: "13",
  cities: [
    clarendonParishAenonTownCity,
    clarendonParishAlleyCity,
    clarendonParishAlstonCity,
    clarendonParishAshleyCity,
    clarendonParishBanksCity,
    clarendonParishBeckfordKraalCity,
    clarendonParishBrandonHillCity,
    clarendonParishBrixtonHillCity,
    clarendonParishBucknorCity,
    clarendonParishBucksCommonCity,
    clarendonParishBushyParkCity,
    clarendonParishChapeltonCity,
    clarendonParishChateauCity,
    clarendonParishCockpitCity,
    clarendonParishCoffeePieceCity,
    clarendonParishColonelsRidgeCity,
    clarendonParishCoxswainCity,
    clarendonParishCroftsHillCity,
    clarendonParishCrookedRiverCity,
    clarendonParishCumberlandCity,
    clarendonParishCuratoeHillCity,
    clarendonParishDawkinsCity,
    clarendonParishEffortvilleCity,
    clarendonParishFourPathsCity,
    clarendonParishFrankfieldCity,
    clarendonParishFreetownCity,
    clarendonParishGimmeHypmeHypbitCity,
    clarendonParishGlenmuirCity,
    clarendonParishGranthamCity,
    clarendonParishGravelHillCity,
    clarendonParishHayesCity,
    clarendonParishHazardCity,
    clarendonParishInvernessCity,
    clarendonParishJamesHillCity,
    clarendonParishJohnsHallCity,
    clarendonParishKellitsCity,
    clarendonParishLimitCity,
    clarendonParishLionelTownCity,
    clarendonParishLongvilleParkCity,
    clarendonParishLongwoodCity,
    clarendonParishMayPenCity,
    clarendonParishMayPenProperCity,
    clarendonParishMilkRiverCity,
    clarendonParishMineralHeightsCity,
    clarendonParishMitchellTownCity,
    clarendonParishMooresCity,
    clarendonParishMorgansForestCity,
    clarendonParishMorgansPassCity,
    clarendonParishMountAiryCity,
    clarendonParishNewDenbighCity,
    clarendonParishNewLongsvilleCity,
    clarendonParishOldDenbighCity,
    clarendonParishOrangeHillCity,
    clarendonParishOsbourneStoreCity,
    clarendonParishPaisleyCity,
    clarendonParishPalmersCrossCity,
    clarendonParishPartOfBananaGroundCity,
    clarendonParishPartOfDouglasCastleCity,
    clarendonParishPartOfKellitsCity,
    clarendonParishPeckhamCity,
    clarendonParishPennantsCity,
    clarendonParishPleasantValleyCity,
    clarendonParishPortlandCottageCity,
    clarendonParishPorusCity,
    clarendonParishRaceCourseCity,
    clarendonParishRichmondParkCity,
    clarendonParishRitchiesCity,
    clarendonParishRockCity,
    clarendonParishRockRiverCity,
    clarendonParishRockyPointCity,
    clarendonParishSaltRiverCity,
    clarendonParishSandyBayCity,
    clarendonParishSanguinettiCity,
    clarendonParishSedgepondCity,
    clarendonParishSilentHillCity,
    clarendonParishSmithvilleCity,
    clarendonParishSpaldingsCity,
    clarendonParishSummerfieldCity,
    clarendonParishThompsonTownCity,
    clarendonParishTollgateCity,
    clarendonParishTreadlightCity,
    clarendonParishTroutHallCity,
    clarendonParishTurnersCity,
    clarendonParishWaterLaneCity,
    clarendonParishWoodhallCity,
    clarendonParishYorkTownCity
  ]);

/// The `Hanover Parish` region in `Jamaica`
const Region jamaicaHanoverParish = Region(
  id: 3749,
  parentId: 108,
  longitude: -78.133638,
  latitude: 18.4097707,
  name: "Hanover Parish",
  type: null,
  stateCode: "09",
  cities: [
    hanoverParishAskenishCity,
    hanoverParishCacoonCity,
    hanoverParishCacoonCastleCity,
    hanoverParishCascadeCity,
    hanoverParishCashHillCity,
    hanoverParishCauldwellCity,
    hanoverParishChambersPenCity,
    hanoverParishChesterCastleCity,
    hanoverParishCopseCity,
    hanoverParishCousinsCoveCity,
    hanoverParishDiasCity,
    hanoverParishGreatValleyCity,
    hanoverParishGreenIslandCity,
    hanoverParishHaddingtonCity,
    hanoverParishHopewellCity,
    hanoverParishJerichoCity,
    hanoverParishKendalCity,
    hanoverParishKingsvaleCity,
    hanoverParishLancesBayCity,
    hanoverParishLogwoodCity,
    hanoverParishLuceaCity,
    hanoverParishLuceaEastCity,
    hanoverParishLuceaWestCity,
    hanoverParishMarchTownCity,
    hanoverParishMarylandCity,
    hanoverParishMountPetoCity,
    hanoverParishOrangeBayCity,
    hanoverParishPellRiverCity,
    hanoverParishPondsideCity,
    hanoverParishRambleCity,
    hanoverParishRockSpringCity,
    hanoverParishSandyBayCity,
    hanoverParishSantoyCity,
    hanoverParishSuccessCity,
    hanoverParishWoodlandsCity,
    hanoverParishWoodsvilleCity
  ]);

/// The `Kingston Parish` region in `Jamaica`
const Region jamaicaKingstonParish = Region(
  id: 3748,
  parentId: 108,
  longitude: -76.782702,
  latitude: 17.9683271,
  name: "Kingston Parish",
  type: null,
  stateCode: "01",
  cities: [
    kingstonParishAllmanTownCity,
    kingstonParishBournemouthGardensCity,
    kingstonParishCampbellTownCity,
    kingstonParishCentralDownTownCity,
    kingstonParishDaguilarTownRennockLodgeCity,
    kingstonParishDenhamTownCity,
    kingstonParishEastDownTownCity,
    kingstonParishFletchersLandCity,
    kingstonParishFranklynTownCity,
    kingstonParishHannahTownCraigTownCity,
    kingstonParishJohnsonTownCity,
    kingstonParishKingstonCity,
    kingstonParishKingstonGardensCity,
    kingstonParishManleyMeadowsCity,
    kingstonParishNewportEastCity,
    kingstonParishNewtonSquareCity,
    kingstonParishNormanGardensCity,
    kingstonParishPassmoreTownCity,
    kingstonParishPortRoyalCity,
    kingstonParishRaeTownCity,
    kingstonParishRollingtonTownCity,
    kingstonParishSouthsideCity,
    kingstonParishSpringfieldCity,
    kingstonParishTivoliGardensCity,
    kingstonParishWestDownTownCity
  ]);

/// The `Manchester Parish` region in `Jamaica`
const Region jamaicaManchesterParish = Region(
  id: 3754,
  parentId: 108,
  longitude: -77.5160788,
  latitude: 18.0669654,
  name: "Manchester Parish",
  type: null,
  stateCode: "12",
  cities: [
    manchesterParishAlligatorPondCity,
    manchesterParishAsiapratvilleCity,
    manchesterParishAuchtembeddieCity,
    manchesterParishBellefieldCity,
    manchesterParishBethanyCity,
    manchesterParishBlueMountainCity,
    manchesterParishBombayCity,
    manchesterParishButtHypupCity,
    manchesterParishCedarGroveCity,
    manchesterParishChantillyCity,
    manchesterParishChristianaCity,
    manchesterParishChudleighCity,
    manchesterParishCobblaCity,
    manchesterParishColeyvilleCity,
    manchesterParishComfortCity,
    manchesterParishComfortHallCity,
    manchesterParishContentCity,
    manchesterParishCraigHeadCity,
    manchesterParishCrossKeysCity,
    manchesterParishDevonCity,
    manchesterParishDownsCity,
    manchesterParishEllenStreetCity,
    manchesterParishEvergreenCity,
    manchesterParishFairfieldCity,
    manchesterParishFrenchParkCity,
    manchesterParishGeorgesValleyCity,
    manchesterParishGoodIntentCity,
    manchesterParishGreenvaleCity,
    manchesterParishGrovePlaceCity,
    manchesterParishGroveTownCity,
    manchesterParishHarmonsCity,
    manchesterParishHarryWatchCity,
    manchesterParishHatfieldCity,
    manchesterParishHearteaseCity,
    manchesterParishHiberniaCity,
    manchesterParishHuntleyCity,
    manchesterParishKendalCity,
    manchesterParishKnockpatrickCity,
    manchesterParishLancasterCity,
    manchesterParishLitchfieldCity,
    manchesterParishMaidstoneCity,
    manchesterParishMandevilleCity,
    manchesterParishMandevilleProperCity,
    manchesterParishMarlieHillCity,
    manchesterParishMayDayCity,
    manchesterParishMedinaCity,
    manchesterParishMikeTownCity,
    manchesterParishMileGullyCity,
    manchesterParishNewForestCity,
    manchesterParishNewGreenCity,
    manchesterParishNewportCity,
    manchesterParishOldEnglandCity,
    manchesterParishPartOfBananaGroundCity,
    manchesterParishPartOfGuttersCity,
    manchesterParishPartOfSpaldingsCity,
    manchesterParishPikeCity,
    manchesterParishPlowdenCity,
    manchesterParishPorusCity,
    manchesterParishProspectCity,
    manchesterParishRichmondCity,
    manchesterParishRobinsHallCity,
    manchesterParishRoseHillCity,
    manchesterParishRoyalFlatCity,
    manchesterParishScottsPassCity,
    manchesterParishSnowdonCity,
    manchesterParishSomersetCity,
    manchesterParishSpringGroundCity,
    manchesterParishSpurTreeCity,
    manchesterParishStPaulsCity,
    manchesterParishSwabysHopeCity,
    manchesterParishTopHillCity,
    manchesterParishVictoriaTownCity,
    manchesterParishWalderstonCity,
    manchesterParishWathamCity,
    manchesterParishWilliamsfieldCity
  ]);

/// The `Portland Parish` region in `Jamaica`
const Region jamaicaPortlandParish = Region(
  id: 3752,
  parentId: 108,
  longitude: -76.4100267,
  latitude: 18.0844274,
  name: "Portland Parish",
  type: null,
  stateCode: "04",
  cities: [
    portlandParishBalcarresCity,
    portlandParishBangorRidgeCity,
    portlandParishBelvedereCity,
    portlandParishBlackHillCity,
    portlandParishBoundbrookCity,
    portlandParishBreastworksCity,
    portlandParishBuffBayCity,
    portlandParishBybrookCity,
    portlandParishCascadeCity,
    portlandParishCastleComfortCity,
    portlandParishCentralPortAntonioCity,
    portlandParishCharlesTownCity,
    portlandParishClavertyCottageCity,
    portlandParishComfortCastleCity,
    portlandParishDrapersCity,
    portlandParishDurhamCity,
    portlandParishFairyHillCity,
    portlandParishFellowshipCity,
    portlandParishFruitfulvaleCity,
    portlandParishHectorsRiverCity,
    portlandParishHopeBayCity,
    portlandParishKensingtonCity,
    portlandParishLongBayCity,
    portlandParishLongRoadCity,
    portlandParishManchionealCity,
    portlandParishMooreTownCity,
    portlandParishMountPleasantCity,
    portlandParishNonsuchCity,
    portlandParishNorwichCity,
    portlandParishOrangeBayCity,
    portlandParishPortAntonioCity,
    portlandParishProspectCity,
    portlandParishRockHallCity,
    portlandParishSherwoodForestCity,
    portlandParishShirleyCastleCity,
    portlandParishSkiboCity,
    portlandParishSnowHillCity,
    portlandParishSpringHillCity,
    portlandParishStMargaretsBayCity,
    portlandParishSwiftRiverCity,
    portlandParishTranquilityCity,
    portlandParishWindsorCity,
    portlandParishWindsorCastleCity,
    portlandParishWindsorForestCity
  ]);

/// The `Saint Andrew` region in `Jamaica`
const Region jamaicaSaintAndrew = Region(
  id: 3751,
  parentId: 108,
  longitude: -95.7021189,
  latitude: 37.2245103,
  name: "Saint Andrew",
  type: null,
  stateCode: "02",
  cities: [
    saintAndrewArcadiaCity,
    saintAndrewArleneGardensCity,
    saintAndrewArnettGardensCity,
    saintAndrewAugustTownCity,
    saintAndrewBarbicanCity,
    saintAndrewBeverleyHillsCity,
    saintAndrewBitoCity,
    saintAndrewBloxboroughCity,
    saintAndrewBoucherParkCity,
    saintAndrewBrandonHillCity,
    saintAndrewBullBaySevenMileCity,
    saintAndrewCaneRiverCity,
    saintAndrewCassiaParkCity,
    saintAndrewCavaliersCity,
    saintAndrewCherryGardensCity,
    saintAndrewCockburnGardensCity,
    saintAndrewConstantSpringCity,
    saintAndrewConstantSpringGardensCity,
    saintAndrewConstitutionHillCity,
    saintAndrewContentGapCity,
    saintAndrewCoorevilleGardensCity,
    saintAndrewCrossRoadsCity,
    saintAndrewDallasCity,
    saintAndrewDelacreeParkUnionGardensCity,
    saintAndrewDelacreePenCity,
    saintAndrewDrewslandCity,
    saintAndrewDrumblairCity,
    saintAndrewDuhaneyParkCity,
    saintAndrewEastwoodParkGardensCity,
    saintAndrewEllestonFlatsMonaCommonsCity,
    saintAndrewFerryCity,
    saintAndrewForestHillsGardensCity,
    saintAndrewForestHillsPlantationHeightCity,
    saintAndrewGoldenSpringCity,
    saintAndrewGordonTownCity,
    saintAndrewGrantsPenCity,
    saintAndrewGreenwichTownNewportWestCity,
    saintAndrewHalfWayTreeCity,
    saintAndrewHalfHypwayHyptreeCity,
    saintAndrewHarbourViewCity,
    saintAndrewHavendaleCity,
    saintAndrewHermitageCity,
    saintAndrewHopePasturesUtechCity,
    saintAndrewHopeTavernCity,
    saintAndrewHughendenCity,
    saintAndrewIrishTownCity,
    saintAndrewJacksHillCity,
    saintAndrewJonesTownCity,
    saintAndrewKencotCity,
    saintAndrewKintyreCity,
    saintAndrewLawrenceTavernCity,
    saintAndrewLiguaneaCity,
    saintAndrewMajesticGardensCity,
    saintAndrewManningsHillCity,
    saintAndrewManningsHillruralCity,
    saintAndrewMarverleyCity,
    saintAndrewMarylandCity,
    saintAndrewMavisBankCity,
    saintAndrewMaxfieldParkCity,
    saintAndrewMeadowbrookCity,
    saintAndrewMeadowbrookEstateCity,
    saintAndrewMolynesFourRoadsCity,
    saintAndrewMolynesGardensCity,
    saintAndrewMonaHeightsCity,
    saintAndrewMountJamesCity,
    saintAndrewMountainViewGardensCity,
    saintAndrewNannyvilleCity,
    saintAndrewNewHavenCity,
    saintAndrewNewKingstonCity,
    saintAndrewNorbrookCity,
    saintAndrewOaklandsCity,
    saintAndrewPapineCity,
    saintAndrewParksRoadCity,
    saintAndrewPatrickCityCity,
    saintAndrewPembrokeHallCity,
    saintAndrewPenwoodCity,
    saintAndrewQueensboroughTunbridgeCity,
    saintAndrewRedHillsruralCity,
    saintAndrewRedHillsGardensCity,
    saintAndrewRedHillsSterlingCastleCity,
    saintAndrewRichmondParkCity,
    saintAndrewRivertonCityCity,
    saintAndrewRoehamptonCity,
    saintAndrewRoseTownCity,
    saintAndrewSeaviewGardensCity,
    saintAndrewSeawardPenCity,
    saintAndrewSeymourLandsCity,
    saintAndrewStPetersCity,
    saintAndrewStadiumGardensCity,
    saintAndrewStonyHillCity,
    saintAndrewSwallowfieldCity,
    saintAndrewTempleHallCity,
    saintAndrewThreeOaksGlendaleCity,
    saintAndrewTowerHillCity,
    saintAndrewTrafalgarParkCity,
    saintAndrewTrenchTownCity,
    saintAndrewUniversityCity,
    saintAndrewVineyardTownCity,
    saintAndrewWalthamGardensCity,
    saintAndrewWashingtonGardensCity,
    saintAndrewWaterhouseCity,
    saintAndrewWhitehallCity,
    saintAndrewWhitfieldTownCity,
    saintAndrewWiltonGardensRemaCity,
    saintAndrewWoodfordCity,
    saintAndrewWoodfordParkCity,
    saintAndrewZaidieGardensCity
  ]);

/// The `Saint Ann Parish` region in `Jamaica`
const Region jamaicaSaintAnnParish = Region(
  id: 3744,
  parentId: 108,
  longitude: -77.4103533,
  latitude: 37.2871452,
  name: "Saint Ann Parish",
  type: null,
  stateCode: "06",
  cities: [
    saintAnnParishAboukirCity,
    saintAnnParishAldertonCity,
    saintAnnParishAlexandriaCity,
    saintAnnParishAlvaCity,
    saintAnnParishBambooCity,
    saintAnnParishBeecherTownCity,
    saintAnnParishBensontonCity,
    saintAnnParishBlackstonedgeCity,
    saintAnnParishBohemiaCity,
    saintAnnParishBorobridgeCity,
    saintAnnParishBrownsTownCity,
    saintAnnParishCalderwoodCity,
    saintAnnParishCascadeCity,
    saintAnnParishCaveValleyCity,
    saintAnnParishChalkyHillCity,
    saintAnnParishChesterCity,
    saintAnnParishClaremontCity,
    saintAnnParishColeGateCity,
    saintAnnParishContentGardenCity,
    saintAnnParishCuffieRidgeCity,
    saintAnnParishDiscoveryBayCity,
    saintAnnParishEpworthCity,
    saintAnnParishExchangeCity,
    saintAnnParishFaithsPenCity,
    saintAnnParishGibraltarCity,
    saintAnnParishGoldenGroveCity,
    saintAnnParishGreatPondCity,
    saintAnnParishHigginLandCity,
    saintAnnParishHindsTownCity,
    saintAnnParishInvernessCity,
    saintAnnParishLimeHallCity,
    saintAnnParishLimeTreeGardensCity,
    saintAnnParishLintonParkCity,
    saintAnnParishMacknieCity,
    saintAnnParishMadrasCity,
    saintAnnParishMansfieldCity,
    saintAnnParishMoneagueCity,
    saintAnnParishMountMoriahCity,
    saintAnnParishMountZionCity,
    saintAnnParishOchoRiosCity,
    saintAnnParishParryTownCity,
    saintAnnParishPhiladelphiaCity,
    saintAnnParishPimentoWalkCity,
    saintAnnParishPrioryCity,
    saintAnnParishRiverHeadCity,
    saintAnnParishRunawayBayCity,
    saintAnnParishSaintAnnsBayCity,
    saintAnnParishStAnnsBayCity,
    saintAnnParishStDacreCity,
    saintAnnParishSteerTownCity,
    saintAnnParishSturgeTownCity,
    saintAnnParishWalkersWoodCity,
    saintAnnParishWattTownCity,
    saintAnnParishYorkCastleCity
  ]);

/// The `Saint Catherine Parish` region in `Jamaica`
const Region jamaicaSaintCatherineParish = Region(
  id: 3746,
  parentId: 108,
  longitude: -77.0564464,
  latitude: 18.0364134,
  name: "Saint Catherine Parish",
  type: null,
  stateCode: "14",
  cities: [
    saintCatherineParishAboveRocksCity,
    saintCatherineParishBartonsCity,
    saintCatherineParishBellasGateCity,
    saintCatherineParishBogWalkCity,
    saintCatherineParishBogwalkCity,
    saintCatherineParishBraetonCity,
    saintCatherineParishBridgeportCity,
    saintCatherineParishBrownsHillCity,
    saintCatherineParishCaymanasCity,
    saintCatherineParishCentralVillageCity,
    saintCatherineParishCrescentCity,
    saintCatherineParishCromartyCity,
    saintCatherineParishCumberlandCity,
    saintCatherineParishEdgewaterCity,
    saintCatherineParishEnsomCity,
    saintCatherineParishEwartonCity,
    saintCatherineParishGingerRidgeCity,
    saintCatherineParishGlengoffeCity,
    saintCatherineParishGoldenAcresCity,
    saintCatherineParishGreaterPortmoreCity,
    saintCatherineParishGreendaleCity,
    saintCatherineParishGregoryParkCity,
    saintCatherineParishHamptonGreenCity,
    saintCatherineParishHarewoodCity,
    saintCatherineParishHarkersHallCity,
    saintCatherineParishHellshireCity,
    saintCatherineParishIndependenceCityCity,
    saintCatherineParishKeystoneCity,
    saintCatherineParishKitsonTownCity,
    saintCatherineParishLinsteadCity,
    saintCatherineParishLluidasValeCity,
    saintCatherineParishNaggoHeadCity,
    saintCatherineParishOldHarbourCity,
    saintCatherineParishOldHarbourBayCity,
    saintCatherineParishOldHarbourRoadCity,
    saintCatherineParishPartOfGuysHillCity,
    saintCatherineParishPartOfKeystoneCity,
    saintCatherineParishPartOfRockHallCity,
    saintCatherineParishPassageFortCity,
    saintCatherineParishPearTreeGroveCity,
    saintCatherineParishPointHillCity,
    saintCatherineParishPortmoreCity,
    saintCatherineParishRedwoodCity,
    saintCatherineParishRiversdaleCity,
    saintCatherineParishSligovilleCity,
    saintCatherineParishSpanishTownCity,
    saintCatherineParishSpanishTownCentralCity,
    saintCatherineParishStJohnsEastCity,
    saintCatherineParishStJohnsWestCity,
    saintCatherineParishTrojaCity,
    saintCatherineParishWaterfordCity,
    saintCatherineParishWatermountCity,
    saintCatherineParishWestCumberlandCity,
    saintCatherineParishWillowdeneCity
  ]);

/// The `Saint Elizabeth Parish` region in `Jamaica`
const Region jamaicaSaintElizabethParish = Region(
  id: 3743,
  parentId: 108,
  longitude: -94.58992,
  latitude: 38.9925308,
  name: "Saint Elizabeth Parish",
  type: null,
  stateCode: "11",
  cities: [
    saintElizabethParishAberdeenCity,
    saintElizabethParishAccompongCity,
    saintElizabethParishAlligatorPondCity,
    saintElizabethParishBalaclavaCity,
    saintElizabethParishBallardsValleyCity,
    saintElizabethParishBarbaryHallCity,
    saintElizabethParishBigwoodsCity,
    saintElizabethParishBlackRiverCity,
    saintElizabethParishBogueCity,
    saintElizabethParishBraesRiverCity,
    saintElizabethParishBrightonCity,
    saintElizabethParishBromptonCity,
    saintElizabethParishBullSavannaCity,
    saintElizabethParishBullSavannahCity,
    saintElizabethParishBurntSavannahCity,
    saintElizabethParishCarisbrookCity,
    saintElizabethParishCotterwoodCity,
    saintElizabethParishCrawfordCity,
    saintElizabethParishElderslieCity,
    saintElizabethParishFullerswoodCity,
    saintElizabethParishGiddyHallCity,
    saintElizabethParishGingerHillCity,
    saintElizabethParishGoshenCity,
    saintElizabethParishHollandCity,
    saintElizabethParishHopetonCity,
    saintElizabethParishJunctionCity,
    saintElizabethParishLacoviaCity,
    saintElizabethParishLeedsCity,
    saintElizabethParishLititzCity,
    saintElizabethParishMaggottyCity,
    saintElizabethParishMalvernCity,
    saintElizabethParishMerrywoodCity,
    saintElizabethParishMiddleQuartersCity,
    saintElizabethParishMountainsideCity,
    saintElizabethParishMulgraveCity,
    saintElizabethParishMyersvilleCity,
    saintElizabethParishNainCity,
    saintElizabethParishNewMarketCity,
    saintElizabethParishNewellCity,
    saintElizabethParishNewtonCity,
    saintElizabethParishParotteeCity,
    saintElizabethParishPedroPlainsCity,
    saintElizabethParishPepperCity,
    saintElizabethParishPisgahCity,
    saintElizabethParishPondsideCity,
    saintElizabethParishPotsdamCity,
    saintElizabethParishQuickStepCity,
    saintElizabethParishRedBankCity,
    saintElizabethParishRetirementCity,
    saintElizabethParishRoseHallCity,
    saintElizabethParishRusselsCity,
    saintElizabethParishSantaCruzCity,
    saintElizabethParishScholefieldCity,
    saintElizabethParishSiloahCity,
    saintElizabethParishSlipeCity,
    saintElizabethParishSouthfieldCity,
    saintElizabethParishSpringfieldCity,
    saintElizabethParishThorntonCity,
    saintElizabethParishTopHillCity,
    saintElizabethParishTreasureBeachCity,
    saintElizabethParishWarministerCity,
    saintElizabethParishWatchwellCity,
    saintElizabethParishWhiteHillCity
  ]);

/// The `Saint James Parish` region in `Jamaica`
const Region jamaicaSaintJamesParish = Region(
  id: 3745,
  parentId: 108,
  longitude: -90.7913227,
  latitude: 30.0179292,
  name: "Saint James Parish",
  type: null,
  stateCode: "08",
  cities: [
    saintJamesParishAdelphiCity,
    saintJamesParishAlbionCity,
    saintJamesParishAnchovyCity,
    saintJamesParishArcadiaCity,
    saintJamesParishBarrettTownCity,
    saintJamesParishBickerstethCity,
    saintJamesParishBogueCity,
    saintJamesParishBrandonHillCity,
    saintJamesParishCambridgeCity,
    saintJamesParishCanterburyCity,
    saintJamesParishCatadupaCity,
    saintJamesParishCatherineHallCity,
    saintJamesParishCatherineMountCity,
    saintJamesParishComfortHallCity,
    saintJamesParishCoralGardensCity,
    saintJamesParishCornwallCity,
    saintJamesParishDownTownMontegoBayCity,
    saintJamesParishDumfriesCity,
    saintJamesParishFairfieldCity,
    saintJamesParishFarmHeightsCity,
    saintJamesParishFlagstaffCity,
    saintJamesParishFlamsteadCity,
    saintJamesParishFlankersCity,
    saintJamesParishFlowerHillCity,
    saintJamesParishFriendshipCity,
    saintJamesParishGarlandsCity,
    saintJamesParishGlendevonCity,
    saintJamesParishGoodwillCity,
    saintJamesParishGranvilleCity,
    saintJamesParishGreenPondCity,
    saintJamesParishGreenwoodCity,
    saintJamesParishHopetonCity,
    saintJamesParishIronshoreCity,
    saintJamesParishIrwinCity,
    saintJamesParishJohnsHallCity,
    saintJamesParishLilliputCity,
    saintJamesParishLotteryCity,
    saintJamesParishMaldonCity,
    saintJamesParishMaroonTownCity,
    saintJamesParishMochoCity,
    saintJamesParishMontegoBayCity,
    saintJamesParishMontegoHillCity,
    saintJamesParishMontpelierCity,
    saintJamesParishMountCareyCity,
    saintJamesParishMountHorebCity,
    saintJamesParishMountSalemCity,
    saintJamesParishNiagaraCity,
    saintJamesParishNorwoodCity,
    saintJamesParishOrangeCity,
    saintJamesParishParadiseCity,
    saintJamesParishPitfourCity,
    saintJamesParishPortoBelloCity,
    saintJamesParishReadingCity,
    saintJamesParishRetirementCity,
    saintJamesParishRetrieveCity,
    saintJamesParishRoehamptonCity,
    saintJamesParishRoseHallCity,
    saintJamesParishRoseHeightsCity,
    saintJamesParishRoseMountGardenCity,
    saintJamesParishRosemountCity,
    saintJamesParishSaltSpringCity,
    saintJamesParishSevenRiversCity,
    saintJamesParishSomertonCity,
    saintJamesParishSpotValleyCity,
    saintJamesParishStonehengeCity,
    saintJamesParishSummerHillCity,
    saintJamesParishSunderlandCity,
    saintJamesParishTangleRiverCity,
    saintJamesParishTowerHillmoyHallCity,
    saintJamesParishTuckerCity,
    saintJamesParishUnityHallCity,
    saintJamesParishVaughnsfieldCity,
    saintJamesParishWelcomeHallCity,
    saintJamesParishWestGreenCity
  ]);

/// The `Saint Mary Parish` region in `Jamaica`
const Region jamaicaSaintMaryParish = Region(
  id: 3747,
  parentId: 108,
  longitude: -95.973844,
  latitude: 36.092522,
  name: "Saint Mary Parish",
  type: null,
  stateCode: "05",
  cities: [
    saintMaryParishAmielTownCity,
    saintMaryParishAnnottoBayCity,
    saintMaryParishBaileysValeCity,
    saintMaryParishBaxterMountainCity,
    saintMaryParishBelfieldCity,
    saintMaryParishBonnygateCity,
    saintMaryParishBrainerdCity,
    saintMaryParishBroadgateCity,
    saintMaryParishCamberwellCity,
    saintMaryParishCarronHallCity,
    saintMaryParishCastletonCity,
    saintMaryParishCharlesTownCity,
    saintMaryParishClonmelCity,
    saintMaryParishDevonPenCity,
    saintMaryParishDoverCity,
    saintMaryParishEnfieldCity,
    saintMaryParishEpsonCity,
    saintMaryParishFlintRiverCity,
    saintMaryParishFreeHillCity,
    saintMaryParishFriendshipGapCity,
    saintMaryParishGalinaCity,
    saintMaryParishGayleCity,
    saintMaryParishGuysHillCity,
    saintMaryParishHampsteadCity,
    saintMaryParishHighgateCity,
    saintMaryParishIslingtonCity,
    saintMaryParishJacksRiverCity,
    saintMaryParishJefferyTownCity,
    saintMaryParishLabyrinthCity,
    saintMaryParishLongRoadCity,
    saintMaryParishLuckyHillCity,
    saintMaryParishMangoValleyCity,
    saintMaryParishMartinCity,
    saintMaryParishMasonHallCity,
    saintMaryParishMileGullyCity,
    saintMaryParishOracabessaCity,
    saintMaryParishPortMariaCity,
    saintMaryParishProspectCity,
    saintMaryParishRetreatCity,
    saintMaryParishRichmondCity,
    saintMaryParishRobinsBayCity,
    saintMaryParishSandsideCity,
    saintMaryParishScottsHallCity,
    saintMaryParishWoodparkCity,
    saintMaryParishWoodsideCity
  ]);

/// The `Saint Thomas Parish` region in `Jamaica`
const Region jamaicaSaintThomasParish = Region(
  id: 3750,
  parentId: 108,
  longitude: -81.7402218,
  latitude: 41.4425389,
  name: "Saint Thomas Parish",
  type: null,
  stateCode: "03",
  cities: [
    saintThomasParishAiryCastleCity,
    saintThomasParishAlbionCity,
    saintThomasParishAmityHallCity,
    saintThomasParishArcadiaCity,
    saintThomasParishBaptistCity,
    saintThomasParishBarkingLodgeCity,
    saintThomasParishBathCity,
    saintThomasParishBethelCity,
    saintThomasParishCedarValleyCity,
    saintThomasParishChurchCornerCity,
    saintThomasParishDalveyCity,
    saintThomasParishDanversPenCity,
    saintThomasParishDuckenfieldCity,
    saintThomasParishDuhaneyPenCity,
    saintThomasParishEasingtonCity,
    saintThomasParishElevenMilesCity,
    saintThomasParishFontHillCity,
    saintThomasParishGoldenGroveCity,
    saintThomasParishHagleyGapCity,
    saintThomasParishHamptonCourtCity,
    saintThomasParishHayfieldCity,
    saintThomasParishHillsideCity,
    saintThomasParishJohnsTownCity,
    saintThomasParishJohnsonMountainCity,
    saintThomasParishJonesPenCity,
    saintThomasParishLeithHallCity,
    saintThomasParishLlandeweyCity,
    saintThomasParishLloydsCity,
    saintThomasParishLyssonsCity,
    saintThomasParishMiddletonCity,
    saintThomasParishMorantBayCity,
    saintThomasParishMountLebanusCity,
    saintThomasParishNewMonklandCity,
    saintThomasParishPamphretCity,
    saintThomasParishPearTreeCity,
    saintThomasParishPoormansCornerCity,
    saintThomasParishPortMorantCity,
    saintThomasParishProspectCity,
    saintThomasParishRambleCity,
    saintThomasParishRetreatCity,
    saintThomasParishRichmondValeCity,
    saintThomasParishRiverHeadCity,
    saintThomasParishRowlandsfieldCity,
    saintThomasParishSeaforthCity,
    saintThomasParishSomersetCity,
    saintThomasParishSpringBankCity,
    saintThomasParishSpringGardenCity,
    saintThomasParishSunningHillCity,
    saintThomasParishTrinityVilleCity,
    saintThomasParishTrinityvilleCity,
    saintThomasParishWheelerfieldCity,
    saintThomasParishWhiteHallCity,
    saintThomasParishWhiteHorsesCity,
    saintThomasParishWilmingtonCity,
    saintThomasParishWinchesterCity,
    saintThomasParishYallahsCity,
    saintThomasParishYorkCity
  ]);

/// The `Trelawny Parish` region in `Jamaica`
const Region jamaicaTrelawnyParish = Region(
  id: 3755,
  parentId: 108,
  longitude: -77.6077865,
  latitude: 18.3526143,
  name: "Trelawny Parish",
  type: null,
  stateCode: "07",
  cities: [
    trelawnyParishAlbertTownCity,
    trelawnyParishAlpsCity,
    trelawnyParishBountyHallCity,
    trelawnyParishBramptonCity,
    trelawnyParishBunkersHillCity,
    trelawnyParishClarksTownCity,
    trelawnyParishDanielTownCity,
    trelawnyParishDeesideCity,
    trelawnyParishDuanvaleCity,
    trelawnyParishDuncansCity,
    trelawnyParishFalmouthCity,
    trelawnyParishFreemansHallCity,
    trelawnyParishGranvilleCity,
    trelawnyParishHampdenCity,
    trelawnyParishJacksonTownCity,
    trelawnyParishJoeHutCity,
    trelawnyParishKinlossCity,
    trelawnyParishLorrimersCity,
    trelawnyParishMarthaBraeCity,
    trelawnyParishPerthTownCity,
    trelawnyParishRefugeCity,
    trelawnyParishRioBuenoCity,
    trelawnyParishSaltMarshCity,
    trelawnyParishSamuelsProspectCity,
    trelawnyParishSawyersCity,
    trelawnyParishSherwoodContentCity,
    trelawnyParishSpicyHillCity,
    trelawnyParishSpringGardenCity,
    trelawnyParishStVincentCity,
    trelawnyParishStettinCity,
    trelawnyParishStewartTownCity,
    trelawnyParishTroyCity,
    trelawnyParishUlsterSpringCity,
    trelawnyParishWaitHypaHypbitCity,
    trelawnyParishWakefieldCity,
    trelawnyParishWarsopCity,
    trelawnyParishWilsonsRunCity,
    trelawnyParishWirefenceCity
  ]);

/// The `Westmoreland Parish` region in `Jamaica`
const Region jamaicaWestmorelandParish = Region(
  id: 3742,
  parentId: 108,
  longitude: -78.1564432,
  latitude: 18.2944378,
  name: "Westmoreland Parish",
  type: null,
  stateCode: "10",
  cities: [
    westmorelandParish12thStreetCity,
    westmorelandParishAmityCity,
    westmorelandParishAshtonCity,
    westmorelandParishBarneysideCity,
    westmorelandParishBathCity,
    westmorelandParishBathMountainCity,
    westmorelandParishBeaufortCity,
    westmorelandParishBeestonSpringCity,
    westmorelandParishBelvedereCity,
    westmorelandParishBerkshireCity,
    westmorelandParishBethelTownCity,
    westmorelandParishBigBridgeCity,
    westmorelandParishBluefieldsCity,
    westmorelandParishBogCity,
    westmorelandParishBroughtonCity,
    westmorelandParishBurntSavannahCity,
    westmorelandParishCairnCurranCity,
    westmorelandParishCaledoniaCity,
    westmorelandParishCarmelCity,
    westmorelandParishCaveCity,
    westmorelandParishChantillyCity,
    westmorelandParishContentCity,
    westmorelandParishCornwallMountianCity,
    westmorelandParishDarlistonCity,
    westmorelandParishDelvelandCity,
    westmorelandParishDillionBigwoodsCity,
    westmorelandParishDundeeCity,
    westmorelandParishEnfieldCity,
    westmorelandParishFerrisCity,
    westmorelandParishFortWilliamsCity,
    westmorelandParishFromeCity,
    westmorelandParishFullersfieldCity,
    westmorelandParishGeorgesPlainCity,
    westmorelandParishGoodensRiverCity,
    westmorelandParishGrangeCity,
    westmorelandParishGrangeHillCity,
    westmorelandParishHaddoCity,
    westmorelandParishHarmonyTownCity,
    westmorelandParishHertfordCity,
    westmorelandParishJerusalemCity,
    westmorelandParishKentuckyCity,
    westmorelandParishKilmarnochCity,
    westmorelandParishLambsRiverCity,
    westmorelandParishLeamingtonCity,
    westmorelandParishLenoxBigwoodsCity,
    westmorelandParishLittleLondonCity,
    westmorelandParishLlandiloCity,
    westmorelandParishMackfieldCity,
    westmorelandParishMearnsvilleCity,
    westmorelandParishMountAiryCity,
    westmorelandParishMountStewartCity,
    westmorelandParishNegrilCity,
    westmorelandParishNewMarketOvalCity,
    westmorelandParishNewRoadsCity,
    westmorelandParishNewWorksCity,
    westmorelandParishOrangeHillCity,
    westmorelandParishPaulIslandCity,
    westmorelandParishPetersfieldCity,
    westmorelandParishPetersvilleCity,
    westmorelandParishPortersMountainCity,
    westmorelandParishRedHillsCity,
    westmorelandParishRevivalCity,
    westmorelandParishRoaringRiverCity,
    westmorelandParishRussiaCity,
    westmorelandParishSavannaHyplaHypmarCity,
    westmorelandParishSavannahHyplaHypmarBusinessDistCity,
    westmorelandParishSeafordTownCity,
    westmorelandParishSeatonCrescentCity,
    westmorelandParishShefieldCity,
    westmorelandParishShoalinGrottoCity,
    westmorelandParishSmithfieldCity,
    westmorelandParishStLeonardsCity,
    westmorelandParishStrathbogieCity,
    westmorelandParishStrawberryCity,
    westmorelandParishStruieCity,
    westmorelandParishThreeMileRiverCity,
    westmorelandParishTownHeadCity,
    westmorelandParishTruroCity,
    westmorelandParishWaterWorksCity,
    westmorelandParishWhitehouseCity,
    westmorelandParishWhithornCity,
    westmorelandParishWilliamsfieldCity
  ]);

/// The 14 states of `Jamaica` keyed by their id.
const Map<int, Region> jamaicaStates = <int, Region>{
    3753: jamaicaClarendonParish,
    3749: jamaicaHanoverParish,
    3748: jamaicaKingstonParish,
    3754: jamaicaManchesterParish,
    3752: jamaicaPortlandParish,
    3751: jamaicaSaintAndrew,
    3744: jamaicaSaintAnnParish,
    3746: jamaicaSaintCatherineParish,
    3743: jamaicaSaintElizabethParish,
    3745: jamaicaSaintJamesParish,
    3747: jamaicaSaintMaryParish,
    3750: jamaicaSaintThomasParish,
    3755: jamaicaTrelawnyParish,
    3742: jamaicaWestmorelandParish
  };
