/// Access to known geographies in Kazakhstan and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'kazakhstan_cities.dart';

/// The 17 regions of `🇰🇿 Kazakhstan`
const Region kazakhstanAkmolaRegion = Region(
    id: 145,
    parentId: 112,
    longitude: 69.4110494,
    latitude: 51.916532,
    name: "Akmola Region",
    type: null,
    stateCode: "AKM",
    cities: [
      kazakhstanAkmolaRegionAkkol,
      kazakhstanAkmolaRegionAkkol,
      kazakhstanAkmolaRegionAksu,
      kazakhstanAkmolaRegionAstrakhan,
      kazakhstanAkmolaRegionAtbasar,
      kazakhstanAkmolaRegionBalkashino,
      kazakhstanAkmolaRegionBestobe,
      kazakhstanAkmolaRegionDerzhavinsk,
      kazakhstanAkmolaRegionEgindikol,
      kazakhstanAkmolaRegionEsil,
      kazakhstanAkmolaRegionKokshetau,
      kazakhstanAkmolaRegionKrasnogorskiy,
      kazakhstanAkmolaRegionMakinsk,
      kazakhstanAkmolaRegionShantobe,
      kazakhstanAkmolaRegionShchuchinsk,
      kazakhstanAkmolaRegionShortandy,
      kazakhstanAkmolaRegionStepnogorsk,
      kazakhstanAkmolaRegionStepnyak,
      kazakhstanAkmolaRegionYermentau,
      kazakhstanAkmolaRegionZavodskoy,
      kazakhstanAkmolaRegionZhaqsy,
      kazakhstanAkmolaRegionZholymbet
    ]);
const Region kazakhstanAktobeRegion = Region(
    id: 151,
    parentId: 112,
    longitude: 57.9974378,
    latitude: 48.7797078,
    name: "Aktobe Region",
    type: null,
    stateCode: "AKT",
    cities: [
      kazakhstanAktobeRegionAktobe,
      kazakhstanAktobeRegionBatamshinskiy,
      kazakhstanAktobeRegionBayganin,
      kazakhstanAktobeRegionEmbi,
      kazakhstanAktobeRegionKandyagash,
      kazakhstanAktobeRegionKhromtau,
      kazakhstanAktobeRegionMartuk,
      kazakhstanAktobeRegionShalqar,
      kazakhstanAktobeRegionShubarkuduk,
      kazakhstanAktobeRegionShubarshi,
      kazakhstanAktobeRegionTemir,
      kazakhstanAktobeRegionYrghyz
    ]);
const Region kazakhstanAlmaty = Region(
    id: 152,
    parentId: 112,
    longitude: 76.8512485,
    latitude: 43.2220146,
    name: "Almaty",
    type: null,
    stateCode: "ALA",
    cities: [kazakhstanAlmatyAlmaty]);
const Region kazakhstanAlmatyRegion = Region(
    id: 143,
    parentId: 112,
    longitude: 78.4229392,
    latitude: 45.0119227,
    name: "Almaty Region",
    type: null,
    stateCode: "ALM",
    cities: [
      kazakhstanAlmatyRegionBakanas,
      kazakhstanAlmatyRegionBalpykBi,
      kazakhstanAlmatyRegionBurunday,
      kazakhstanAlmatyRegionChemolgan,
      kazakhstanAlmatyRegionDruzhba,
      kazakhstanAlmatyRegionEsik,
      kazakhstanAlmatyRegionKapshagay,
      kazakhstanAlmatyRegionKegen,
      kazakhstanAlmatyRegionLepsy,
      kazakhstanAlmatyRegionMatay,
      kazakhstanAlmatyRegionOtegenBatyra,
      kazakhstanAlmatyRegionPervomayka,
      kazakhstanAlmatyRegionSarkand,
      kazakhstanAlmatyRegionSaryozek,
      kazakhstanAlmatyRegionTaldykorgan,
      kazakhstanAlmatyRegionTalghar,
      kazakhstanAlmatyRegionTekeli,
      kazakhstanAlmatyRegionTurgen,
      kazakhstanAlmatyRegionUlken,
      kazakhstanAlmatyRegionUshHypTyube,
      kazakhstanAlmatyRegionZharkent
    ]);
const Region kazakhstanAtyrauRegion = Region(
    id: 153,
    parentId: 112,
    longitude: 51.914133,
    latitude: 47.1076188,
    name: "Atyrau Region",
    type: null,
    stateCode: "ATY",
    cities: [
      kazakhstanAtyrauRegionAkkol,
      kazakhstanAtyrauRegionAtyrau,
      kazakhstanAtyrauRegionBalykshi,
      kazakhstanAtyrauRegionBayshonas,
      kazakhstanAtyrauRegionDossor,
      kazakhstanAtyrauRegionInderbor,
      kazakhstanAtyrauRegionMakhambet,
      kazakhstanAtyrauRegionMaloyeGanyushkino,
      kazakhstanAtyrauRegionMaqat,
      kazakhstanAtyrauRegionMiyaly,
      kazakhstanAtyrauRegionQaraton,
      kazakhstanAtyrauRegionQulsary,
      kazakhstanAtyrauRegionShalkar
    ]);
const Region kazakhstanBaikonur = Region(
    id: 155,
    parentId: 112,
    longitude: 63.3052428,
    latitude: 45.9645851,
    name: "Baikonur",
    type: null,
    stateCode: "BAY",
    cities: [kazakhstanBaikonurBaikonur]);
const Region kazakhstanEastKazakhstanRegion = Region(
    id: 154,
    parentId: 112,
    longitude: 80.7922534,
    latitude: 48.7062687,
    name: "East Kazakhstan Region",
    type: null,
    stateCode: "VOS",
    cities: [
      kazakhstanEastKazakhstanRegionAltayskiy,
      kazakhstanEastKazakhstanRegionAqtoghay,
      kazakhstanEastKazakhstanRegionAsubulaq,
      kazakhstanEastKazakhstanRegionAuezov,
      kazakhstanEastKazakhstanRegionAyagoz,
      kazakhstanEastKazakhstanRegionBelogorskiy,
      kazakhstanEastKazakhstanRegionBelousovka,
      kazakhstanEastKazakhstanRegionBorodulikha,
      kazakhstanEastKazakhstanRegionGeorgievka,
      kazakhstanEastKazakhstanRegionGlubokoye,
      kazakhstanEastKazakhstanRegionKurchatov,
      kazakhstanEastKazakhstanRegionKurchum,
      kazakhstanEastKazakhstanRegionMaleyevsk,
      kazakhstanEastKazakhstanRegionOgnevka,
      kazakhstanEastKazakhstanRegionPriiskBoko,
      kazakhstanEastKazakhstanRegionQarauyl,
      kazakhstanEastKazakhstanRegionRidder,
      kazakhstanEastKazakhstanRegionSemey,
      kazakhstanEastKazakhstanRegionShar,
      kazakhstanEastKazakhstanRegionShemonaikha,
      kazakhstanEastKazakhstanRegionSuykbulak,
      kazakhstanEastKazakhstanRegionTughyl,
      kazakhstanEastKazakhstanRegionUrzhar,
      kazakhstanEastKazakhstanRegionUstHypKamenogorsk,
      kazakhstanEastKazakhstanRegionUstHypTalovka,
      kazakhstanEastKazakhstanRegionZaysan,
      kazakhstanEastKazakhstanRegionZhalghyztobe,
      kazakhstanEastKazakhstanRegionZhangaBuqtyrma,
      kazakhstanEastKazakhstanRegionZhezkent,
      kazakhstanEastKazakhstanRegionZyryanovsk
    ]);
const Region kazakhstanJambylRegion = Region(
    id: 147,
    parentId: 112,
    longitude: 72.3657967,
    latitude: 44.2220308,
    name: "Jambyl Region",
    type: null,
    stateCode: "ZHA",
    cities: [
      kazakhstanJambylRegionAqbaqay,
      kazakhstanJambylRegionChu,
      kazakhstanJambylRegionGeorgiyevka,
      kazakhstanJambylRegionGranitogorsk,
      kazakhstanJambylRegionKaratau,
      kazakhstanJambylRegionKhantau,
      kazakhstanJambylRegionLugovoy,
      kazakhstanJambylRegionLugovoye,
      kazakhstanJambylRegionMerke,
      kazakhstanJambylRegionMoyynkum,
      kazakhstanJambylRegionMynaral,
      kazakhstanJambylRegionOytal,
      kazakhstanJambylRegionSarykemer,
      kazakhstanJambylRegionShyghanaq,
      kazakhstanJambylRegionTaraz,
      kazakhstanJambylRegionZhangatas
    ]);
const Region kazakhstanKaragandaRegion = Region(
    id: 150,
    parentId: 112,
    longitude: 71.7706807,
    latitude: 47.9022182,
    name: "Karaganda Region",
    type: null,
    stateCode: "KAR",
    cities: [
      kazakhstanKaragandaRegionAbay,
      kazakhstanKaragandaRegionAbayQalasy,
      kazakhstanKaragandaRegionAksuHypAyuly,
      kazakhstanKaragandaRegionAktas,
      kazakhstanKaragandaRegionAktau,
      kazakhstanKaragandaRegionAktogay,
      kazakhstanKaragandaRegionAqadyr,
      kazakhstanKaragandaRegionAqshatau,
      kazakhstanKaragandaRegionAqtoghayAudany,
      kazakhstanKaragandaRegionAtasu,
      kazakhstanKaragandaRegionBalqash,
      kazakhstanKaragandaRegionBukharHypZhyrau,
      kazakhstanKaragandaRegionDolinka,
      kazakhstanKaragandaRegionKaragandy,
      kazakhstanKaragandaRegionKievka,
      kazakhstanKaragandaRegionKoktal,
      kazakhstanKaragandaRegionKushoky,
      kazakhstanKaragandaRegionKyzylzhar,
      kazakhstanKaragandaRegionMoyynty,
      kazakhstanKaragandaRegionNovodolinskiy,
      kazakhstanKaragandaRegionOsakarovka,
      kazakhstanKaragandaRegionPrigorodnoye,
      kazakhstanKaragandaRegionPriozersk,
      kazakhstanKaragandaRegionQarazhal,
      kazakhstanKaragandaRegionQarqaraly,
      kazakhstanKaragandaRegionSaryshaghan,
      kazakhstanKaragandaRegionSayaq,
      kazakhstanKaragandaRegionShakhan,
      kazakhstanKaragandaRegionShakhtinsk,
      kazakhstanKaragandaRegionShashubay,
      kazakhstanKaragandaRegionShubarkol,
      kazakhstanKaragandaRegionSoran,
      kazakhstanKaragandaRegionTemirtau,
      kazakhstanKaragandaRegionTokarevka,
      kazakhstanKaragandaRegionVerkhniyeKayrakty,
      kazakhstanKaragandaRegionZhambyl,
      kazakhstanKaragandaRegionZharyk,
      kazakhstanKaragandaRegionZhezqazghan
    ]);
const Region kazakhstanKostanayRegion = Region(
    id: 157,
    parentId: 112,
    longitude: 64.0479073,
    latitude: 51.5077096,
    name: "Kostanay Region",
    type: null,
    stateCode: "KUS",
    cities: [
      kazakhstanKostanayRegionArkalyk,
      kazakhstanKostanayRegionAyat,
      kazakhstanKostanayRegionBorovskoy,
      kazakhstanKostanayRegionDzhetygara,
      kazakhstanKostanayRegionFyodorovka,
      kazakhstanKostanayRegionKarasu,
      kazakhstanKostanayRegionKomsomolets,
      kazakhstanKostanayRegionKostanay,
      kazakhstanKostanayRegionLisakovsk,
      kazakhstanKostanayRegionOrdzhonikidze,
      kazakhstanKostanayRegionQashar,
      kazakhstanKostanayRegionQusmuryn,
      kazakhstanKostanayRegionRudnyy,
      kazakhstanKostanayRegionTobol,
      kazakhstanKostanayRegionTorghay,
      kazakhstanKostanayRegionTroyebratskiy
    ]);
const Region kazakhstanKyzylordaRegion = Region(
    id: 142,
    parentId: 112,
    longitude: 62.6571885,
    latitude: 44.6922613,
    name: "Kyzylorda Region",
    type: null,
    stateCode: "KZY",
    cities: [
      kazakhstanKyzylordaRegionAral,
      kazakhstanKyzylordaRegionAytekeBi,
      kazakhstanKyzylordaRegionBelkol,
      kazakhstanKyzylordaRegionDzhalagash,
      kazakhstanKyzylordaRegionKyzylorda,
      kazakhstanKyzylordaRegionQazaly,
      kazakhstanKyzylordaRegionSekseuil,
      kazakhstanKyzylordaRegionShalqiya,
      kazakhstanKyzylordaRegionShieli,
      kazakhstanKyzylordaRegionTasboget,
      kazakhstanKyzylordaRegionTerenozek,
      kazakhstanKyzylordaRegionYanykurgan,
      kazakhstanKyzylordaRegionZhosaly
    ]);
const Region kazakhstanMangystauRegion = Region(
    id: 141,
    parentId: 112,
    longitude: 53.8499508,
    latitude: 44.590802,
    name: "Mangystau Region",
    type: null,
    stateCode: "MAN",
    cities: [
      kazakhstanMangystauRegionAktau,
      kazakhstanMangystauRegionBautino,
      kazakhstanMangystauRegionBeyneu,
      kazakhstanMangystauRegionFortHypShevchenko,
      kazakhstanMangystauRegionMunayshy,
      kazakhstanMangystauRegionOmirzaq,
      kazakhstanMangystauRegionSayotesh,
      kazakhstanMangystauRegionShetpe,
      kazakhstanMangystauRegionTaushyq,
      kazakhstanMangystauRegionYeraliyev,
      kazakhstanMangystauRegionZhanaozen,
      kazakhstanMangystauRegionZhetibay
    ]);
const Region kazakhstanNorthKazakhstanRegion = Region(
    id: 144,
    parentId: 112,
    longitude: 69.9387071,
    latitude: 54.1622066,
    name: "North Kazakhstan Region",
    type: null,
    stateCode: "SEV",
    cities: [
      kazakhstanNorthKazakhstanRegionBirlestik,
      kazakhstanNorthKazakhstanRegionBishkul,
      kazakhstanNorthKazakhstanRegionBulayevo,
      kazakhstanNorthKazakhstanRegionBurabay,
      kazakhstanNorthKazakhstanRegionKzyltu,
      kazakhstanNorthKazakhstanRegionNovoishimskiy,
      kazakhstanNorthKazakhstanRegionPetropavl,
      kazakhstanNorthKazakhstanRegionSergeyevka,
      kazakhstanNorthKazakhstanRegionSmirnovo,
      kazakhstanNorthKazakhstanRegionTaiynsha,
      kazakhstanNorthKazakhstanRegionTalshik,
      kazakhstanNorthKazakhstanRegionTimiryazevo,
      kazakhstanNorthKazakhstanRegionVolodarskoye,
      kazakhstanNorthKazakhstanRegionYavlenka
    ]);
const Region kazakhstanNurHypSultan = Region(
    id: 156,
    parentId: 112,
    longitude: 71.4703558,
    latitude: 51.1605227,
    name: "Nur-Sultan",
    type: null,
    stateCode: "AST",
    cities: [kazakhstanNurHypSultanNurHypSultan]);
const Region kazakhstanPavlodarRegion = Region(
    id: 146,
    parentId: 112,
    longitude: 76.9733453,
    latitude: 52.2878444,
    name: "Pavlodar Region",
    type: null,
    stateCode: "PAV",
    cities: [
      kazakhstanPavlodarRegionAksu,
      kazakhstanPavlodarRegionBayanaul,
      kazakhstanPavlodarRegionBelogorye,
      kazakhstanPavlodarRegionEkibastuz,
      kazakhstanPavlodarRegionIrtyshsk,
      kazakhstanPavlodarRegionKalkaman,
      kazakhstanPavlodarRegionLeninskiy,
      kazakhstanPavlodarRegionMayqayyng,
      kazakhstanPavlodarRegionPavlodar,
      kazakhstanPavlodarRegionQashyr,
      kazakhstanPavlodarRegionZhelezinka
    ]);
const Region kazakhstanTurkestanRegion = Region(
    id: 149,
    parentId: 112,
    longitude: 68.4094405,
    latitude: 43.3666958,
    name: "Turkestan Region",
    type: null,
    stateCode: "YUZ",
    cities: [
      kazakhstanTurkestanRegionArys,
      kazakhstanTurkestanRegionAshchysay,
      kazakhstanTurkestanRegionAsyqata,
      kazakhstanTurkestanRegionAtakent,
      kazakhstanTurkestanRegionBayzhansay,
      kazakhstanTurkestanRegionBelyyeVody,
      kazakhstanTurkestanRegionChardara,
      kazakhstanTurkestanRegionChayan,
      kazakhstanTurkestanRegionChulakkurgan,
      kazakhstanTurkestanRegionKantagi,
      kazakhstanTurkestanRegionKentau,
      kazakhstanTurkestanRegionKokterek,
      kazakhstanTurkestanRegionLenger,
      kazakhstanTurkestanRegionLeninskoye,
      kazakhstanTurkestanRegionMaqtaaralAudany,
      kazakhstanTurkestanRegionMyrzakent,
      kazakhstanTurkestanRegionQogham,
      kazakhstanTurkestanRegionSaryaghash,
      kazakhstanTurkestanRegionSaryaghashAudany,
      kazakhstanTurkestanRegionSastobe,
      kazakhstanTurkestanRegionSozaqAudany,
      kazakhstanTurkestanRegionTemirlanovka,
      kazakhstanTurkestanRegionTurarRyskulov,
      kazakhstanTurkestanRegionTurkestan,
      kazakhstanTurkestanRegionTyulkubas,
      kazakhstanTurkestanRegionZhabagly
    ]);
const Region kazakhstanWestKazakhstanProvince = Region(
    id: 148,
    parentId: 112,
    longitude: 50.8066616,
    latitude: 49.5679727,
    name: "West Kazakhstan Province",
    type: null,
    stateCode: "ZAP",
    cities: [
      kazakhstanWestKazakhstanProvinceAqsay,
      kazakhstanWestKazakhstanProvinceBurlin,
      kazakhstanWestKazakhstanProvinceChapaev,
      kazakhstanWestKazakhstanProvinceChingirlau,
      kazakhstanWestKazakhstanProvinceDzhambeyty,
      kazakhstanWestKazakhstanProvinceFedorovka,
      kazakhstanWestKazakhstanProvinceKaztalovka,
      kazakhstanWestKazakhstanProvinceKrugloozernoe,
      kazakhstanWestKazakhstanProvinceOral,
      kazakhstanWestKazakhstanProvincePeremetnoe,
      kazakhstanWestKazakhstanProvinceSaykhin,
      kazakhstanWestKazakhstanProvinceTasqala,
      kazakhstanWestKazakhstanProvinceZhanibek
    ]);

const kazakhstanStates = <int, Region>{
  145: kazakhstanAkmolaRegion,
  151: kazakhstanAktobeRegion,
  152: kazakhstanAlmaty,
  143: kazakhstanAlmatyRegion,
  153: kazakhstanAtyrauRegion,
  155: kazakhstanBaikonur,
  154: kazakhstanEastKazakhstanRegion,
  147: kazakhstanJambylRegion,
  150: kazakhstanKaragandaRegion,
  157: kazakhstanKostanayRegion,
  142: kazakhstanKyzylordaRegion,
  141: kazakhstanMangystauRegion,
  144: kazakhstanNorthKazakhstanRegion,
  156: kazakhstanNurHypSultan,
  146: kazakhstanPavlodarRegion,
  149: kazakhstanTurkestanRegion,
  148: kazakhstanWestKazakhstanProvince
};
