/// Access to known geographies in Nigeria and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'nigeria_cities.dart';

/// The 37 regions of `🇳🇬 Nigeria`
const Region nigeriaAbiaSstate = Region(
    id: 303,
    parentId: 161,
    longitude: 7.5248414,
    latitude: 5.4527354,
    name: "Abia",
    type: "state",
    stateCode: "AB",
    cities: [
      nigeriaAbiaSstateAba,
      nigeriaAbiaSstateAmaigbo,
      nigeriaAbiaSstateArochukwu,
      nigeriaAbiaSstateBende,
      nigeriaAbiaSstateOhafiaHypIfigh,
      nigeriaAbiaSstateUmuahia
    ]);
const Region nigeriaAbujaFederalCapitalTerritoryCcapitalTterritory = Region(
    id: 293,
    parentId: 161,
    longitude: 7.1860402,
    latitude: 8.8940691,
    name: "Abuja Federal Capital Territory",
    type: "capital territory",
    stateCode: "FC",
    cities: [
      nigeriaAbujaFederalCapitalTerritoryCcapitalTterritoryAbuja,
      nigeriaAbujaFederalCapitalTerritoryCcapitalTterritoryKuje,
      nigeriaAbujaFederalCapitalTerritoryCcapitalTterritoryKwali,
      nigeriaAbujaFederalCapitalTerritoryCcapitalTterritoryMadala
    ]);
const Region nigeriaAdamawaSstate = Region(
    id: 320,
    parentId: 161,
    longitude: 12.3983853,
    latitude: 9.3264751,
    name: "Adamawa",
    type: "state",
    stateCode: "AD",
    cities: [
      nigeriaAdamawaSstateGanye,
      nigeriaAdamawaSstateGombi,
      nigeriaAdamawaSstateHolma,
      nigeriaAdamawaSstateJimeta,
      nigeriaAdamawaSstateMadagali,
      nigeriaAdamawaSstateMayoHypBelwa,
      nigeriaAdamawaSstateMubi,
      nigeriaAdamawaSstateNgurore,
      nigeriaAdamawaSstateNuman,
      nigeriaAdamawaSstateToungo,
      nigeriaAdamawaSstateYola
    ]);
const Region nigeriaAkwaIbomSstate = Region(
    id: 304,
    parentId: 161,
    longitude: 7.8536675,
    latitude: 4.9057371,
    name: "Akwa Ibom",
    type: "state",
    stateCode: "AK",
    cities: [
      nigeriaAkwaIbomSstateEket,
      nigeriaAkwaIbomSstateEsukOron,
      nigeriaAkwaIbomSstateIkotEkpene,
      nigeriaAkwaIbomSstateItu,
      nigeriaAkwaIbomSstateUyo
    ]);
const Region nigeriaAnambraSstate = Region(
    id: 315,
    parentId: 161,
    longitude: 6.9369559,
    latitude: 6.2208997,
    name: "Anambra",
    type: "state",
    stateCode: "AN",
    cities: [
      nigeriaAnambraSstateAgulu,
      nigeriaAnambraSstateAtani,
      nigeriaAnambraSstateAwka,
      nigeriaAnambraSstateEnuguHypUkwu,
      nigeriaAnambraSstateIgboHypUkwu,
      nigeriaAnambraSstateIhiala,
      nigeriaAnambraSstateNkpor,
      nigeriaAnambraSstateNnewi,
      nigeriaAnambraSstateOnitsha,
      nigeriaAnambraSstateOzubulu,
      nigeriaAnambraSstateUga,
      nigeriaAnambraSstateUruoboHypOkija
    ]);
const Region nigeriaBauchiSstate = Region(
    id: 312,
    parentId: 161,
    longitude: 9.9991943,
    latitude: 10.7760624,
    name: "Bauchi",
    type: "state",
    stateCode: "BA",
    cities: [
      nigeriaBauchiSstateAzare,
      nigeriaBauchiSstateBauchi,
      nigeriaBauchiSstateBoi,
      nigeriaBauchiSstateBununu,
      nigeriaBauchiSstateDarazo,
      nigeriaBauchiSstateDass,
      nigeriaBauchiSstateDindima,
      nigeriaBauchiSstateDisina,
      nigeriaBauchiSstateGabarin,
      nigeriaBauchiSstateGwaram,
      nigeriaBauchiSstateKari,
      nigeriaBauchiSstateLame,
      nigeriaBauchiSstateLere,
      nigeriaBauchiSstateMadara,
      nigeriaBauchiSstateMisau,
      nigeriaBauchiSstateSade,
      nigeriaBauchiSstateYamrat,
      nigeriaBauchiSstateYandaBayo,
      nigeriaBauchiSstateYuli,
      nigeriaBauchiSstateZadawa,
      nigeriaBauchiSstateZalanga
    ]);
const Region nigeriaBayelsaSstate = Region(
    id: 305,
    parentId: 161,
    longitude: 6.0698526,
    latitude: 4.7719071,
    name: "Bayelsa",
    type: "state",
    stateCode: "BY",
    cities: [
      nigeriaBayelsaSstateAmassoma,
      nigeriaBayelsaSstateTwonHypBrass,
      nigeriaBayelsaSstateYenagoa
    ]);
const Region nigeriaBenueSstate = Region(
    id: 291,
    parentId: 161,
    longitude: 8.7403687,
    latitude: 7.3369024,
    name: "Benue",
    type: "state",
    stateCode: "BE",
    cities: [
      nigeriaBenueSstateAliade,
      nigeriaBenueSstateBoju,
      nigeriaBenueSstateGboko,
      nigeriaBenueSstateIgbor,
      nigeriaBenueSstateMakurdi,
      nigeriaBenueSstateOchobo,
      nigeriaBenueSstateOtukpa,
      nigeriaBenueSstateTakum,
      nigeriaBenueSstateUgbokpo,
      nigeriaBenueSstateYandev,
      nigeriaBenueSstateZakiBiam
    ]);
const Region nigeriaBornoSstate = Region(
    id: 307,
    parentId: 161,
    longitude: 13.1519665,
    latitude: 11.8846356,
    name: "Borno",
    type: "state",
    stateCode: "BO",
    cities: [
      nigeriaBornoSstateBama,
      nigeriaBornoSstateBenisheikh,
      nigeriaBornoSstateBiu,
      nigeriaBornoSstateBornuYassu,
      nigeriaBornoSstateDamasak,
      nigeriaBornoSstateDamboa,
      nigeriaBornoSstateDikwa,
      nigeriaBornoSstateGamboru,
      nigeriaBornoSstateGwoza,
      nigeriaBornoSstateKukawa,
      nigeriaBornoSstateMagumeri,
      nigeriaBornoSstateMaiduguri,
      nigeriaBornoSstateMarte,
      nigeriaBornoSstateMiringa,
      nigeriaBornoSstateMonguno,
      nigeriaBornoSstateNgala,
      nigeriaBornoSstateShaffa,
      nigeriaBornoSstateShani,
      nigeriaBornoSstateTokombere,
      nigeriaBornoSstateUba,
      nigeriaBornoSstateWuyo,
      nigeriaBornoSstateYajiwa
    ]);
const Region nigeriaCrossRiverSstate = Region(
    id: 314,
    parentId: 161,
    longitude: 8.5988014,
    latitude: 5.8701724,
    name: "Cross River",
    type: "state",
    stateCode: "CR",
    cities: [
      nigeriaCrossRiverSstateAkankpa,
      nigeriaCrossRiverSstateCalabar,
      nigeriaCrossRiverSstateGakem,
      nigeriaCrossRiverSstateIkang,
      nigeriaCrossRiverSstateUgep
    ]);
const Region nigeriaDeltaSstate = Region(
    id: 316,
    parentId: 161,
    longitude: -90.7354508,
    latitude: 33.7453784,
    name: "Delta",
    type: "state",
    stateCode: "DE",
    cities: [
      nigeriaDeltaSstateAbraka,
      nigeriaDeltaSstateAgbor,
      nigeriaDeltaSstateAsaba,
      nigeriaDeltaSstateBomadi,
      nigeriaDeltaSstateBurutu,
      nigeriaDeltaSstateKwale,
      nigeriaDeltaSstateObiaruku,
      nigeriaDeltaSstateOgwashiHypUku,
      nigeriaDeltaSstateOrerokpe,
      nigeriaDeltaSstatePatani,
      nigeriaDeltaSstateSapele,
      nigeriaDeltaSstateUghelli,
      nigeriaDeltaSstateUmunede,
      nigeriaDeltaSstateWarri
    ]);
const Region nigeriaEbonyiSstate = Region(
    id: 311,
    parentId: 161,
    longitude: 8.0137302,
    latitude: 6.2649232,
    name: "Ebonyi",
    type: "state",
    stateCode: "EB",
    cities: [
      nigeriaEbonyiSstateAbakaliki,
      nigeriaEbonyiSstateAfikpo,
      nigeriaEbonyiSstateEffium,
      nigeriaEbonyiSstateEzzaHypOhu,
      nigeriaEbonyiSstateIsieke
    ]);
const Region nigeriaEdoSstate = Region(
    id: 318,
    parentId: 161,
    longitude: 5.9304056,
    latitude: 6.6341831,
    name: "Edo",
    type: "state",
    stateCode: "ED",
    cities: [
      nigeriaEdoSstateAgenebode,
      nigeriaEdoSstateAuchi,
      nigeriaEdoSstateBeninCity,
      nigeriaEdoSstateEkpoma,
      nigeriaEdoSstateIgarra,
      nigeriaEdoSstateIllushi,
      nigeriaEdoSstateSiluko,
      nigeriaEdoSstateUbiaja,
      nigeriaEdoSstateUromi
    ]);
const Region nigeriaEkitiSstate = Region(
    id: 309,
    parentId: 161,
    longitude: 5.3109505,
    latitude: 7.7189862,
    name: "Ekiti",
    type: "state",
    stateCode: "EK",
    cities: [
      nigeriaEkitiSstateAdoHypEkiti,
      nigeriaEkitiSstateAramokoHypEkiti,
      nigeriaEkitiSstateEfonHypAlaaye,
      nigeriaEkitiSstateEmureHypEkiti,
      nigeriaEkitiSstateIfaki,
      nigeriaEkitiSstateIgbaraHypOdo,
      nigeriaEkitiSstateIgedeHypEkiti,
      nigeriaEkitiSstateIjeroHypEkiti,
      nigeriaEkitiSstateIkereHypEkiti,
      nigeriaEkitiSstateIpoti,
      nigeriaEkitiSstateIseHypEkiti,
      nigeriaEkitiSstateOkeIla,
      nigeriaEkitiSstateOmuoHypEkiti
    ]);
const Region nigeriaEnuguSstate = Region(
    id: 289,
    parentId: 161,
    longitude: 7.4356194,
    latitude: 6.536353,
    name: "Enugu",
    type: "state",
    stateCode: "EN",
    cities: [
      nigeriaEnuguSstateAdani,
      nigeriaEnuguSstateAkeHypEze,
      nigeriaEnuguSstateAku,
      nigeriaEnuguSstateAmagunze,
      nigeriaEnuguSstateAwgu,
      nigeriaEnuguSstateEhaAmufu,
      nigeriaEnuguSstateEnugu,
      nigeriaEnuguSstateEnuguHypEzike,
      nigeriaEnuguSstateEte,
      nigeriaEnuguSstateIkem,
      nigeriaEnuguSstateMberubu,
      nigeriaEnuguSstateNsukka,
      nigeriaEnuguSstateOboloHypEke1,
      nigeriaEnuguSstateOpi,
      nigeriaEnuguSstateUdi
    ]);
const Region nigeriaGombeSstate = Region(
    id: 310,
    parentId: 161,
    longitude: 11.1927587,
    latitude: 10.3637795,
    name: "Gombe",
    type: "state",
    stateCode: "GO",
    cities: [
      nigeriaGombeSstateAkko,
      nigeriaGombeSstateBara,
      nigeriaGombeSstateBilliri,
      nigeriaGombeSstateDadiya,
      nigeriaGombeSstateDeba,
      nigeriaGombeSstateDukku,
      nigeriaGombeSstateGarko,
      nigeriaGombeSstateGombe,
      nigeriaGombeSstateHinna,
      nigeriaGombeSstateKafarati,
      nigeriaGombeSstateKaltungo,
      nigeriaGombeSstateKumo,
      nigeriaGombeSstateNafada,
      nigeriaGombeSstatePindiga
    ]);
const Region nigeriaImoSstate = Region(
    id: 308,
    parentId: 161,
    longitude: 7.0588219,
    latitude: 5.5720122,
    name: "Imo",
    type: "state",
    stateCode: "IM",
    cities: [
      nigeriaImoSstateIho,
      nigeriaImoSstateOguta,
      nigeriaImoSstateOkigwe,
      nigeriaImoSstateOrlu,
      nigeriaImoSstateOrodo,
      nigeriaImoSstateOwerri
    ]);
const Region nigeriaJigawaSstate = Region(
    id: 288,
    parentId: 161,
    longitude: 9.5615867,
    latitude: 12.228012,
    name: "Jigawa",
    type: "state",
    stateCode: "JI",
    cities: [
      nigeriaJigawaSstateBabura,
      nigeriaJigawaSstateBirninKudu,
      nigeriaJigawaSstateBirniwa,
      nigeriaJigawaSstateDutse,
      nigeriaJigawaSstateGagarawa,
      nigeriaJigawaSstateGumel,
      nigeriaJigawaSstateGwaram,
      nigeriaJigawaSstateHadejia,
      nigeriaJigawaSstateKafinHausa,
      nigeriaJigawaSstateKazaure,
      nigeriaJigawaSstateKiyawa,
      nigeriaJigawaSstateMallammaduri,
      nigeriaJigawaSstateRingim,
      nigeriaJigawaSstateSamamiya
    ]);
const Region nigeriaKadunaSstate = Region(
    id: 294,
    parentId: 161,
    longitude: 7.7094537,
    latitude: 10.3764006,
    name: "Kaduna",
    type: "state",
    stateCode: "KD",
    cities: [
      nigeriaKadunaSstateAnchau,
      nigeriaKadunaSstateBurumburum,
      nigeriaKadunaSstateDutsenWai,
      nigeriaKadunaSstateHunkuyi,
      nigeriaKadunaSstateKachia,
      nigeriaKadunaSstateKaduna,
      nigeriaKadunaSstateKafanchan,
      nigeriaKadunaSstateKagoro,
      nigeriaKadunaSstateKajuru,
      nigeriaKadunaSstateKujama,
      nigeriaKadunaSstateLere,
      nigeriaKadunaSstateMando,
      nigeriaKadunaSstateSaminaka,
      nigeriaKadunaSstateSoba,
      nigeriaKadunaSstateSofoHypBirninHypGwari,
      nigeriaKadunaSstateZaria
    ]);
const Region nigeriaKanoSstate = Region(
    id: 300,
    parentId: 161,
    longitude: 8.5247107,
    latitude: 11.7470698,
    name: "Kano",
    type: "state",
    stateCode: "KN",
    cities: [
      nigeriaKanoSstateDanGora,
      nigeriaKanoSstateGaya,
      nigeriaKanoSstateKano
    ]);
const Region nigeriaKatsinaSstate = Region(
    id: 313,
    parentId: 161,
    longitude: 7.6305748,
    latitude: 12.3796707,
    name: "Katsina",
    type: "state",
    stateCode: "KT",
    cities: [
      nigeriaKatsinaSstateDanja,
      nigeriaKatsinaSstateDankama,
      nigeriaKatsinaSstateDaura,
      nigeriaKatsinaSstateDutsinHypMa,
      nigeriaKatsinaSstateFuntua,
      nigeriaKatsinaSstateGora,
      nigeriaKatsinaSstateJibia,
      nigeriaKatsinaSstateJikamshi,
      nigeriaKatsinaSstateKankara,
      nigeriaKatsinaSstateKatsina,
      nigeriaKatsinaSstateMashi,
      nigeriaKatsinaSstateRuma,
      nigeriaKatsinaSstateRunka,
      nigeriaKatsinaSstateWagini
    ]);
const Region nigeriaKebbiSstate = Region(
    id: 290,
    parentId: 161,
    longitude: 4.2333355,
    latitude: 11.4942003,
    name: "Kebbi",
    type: "state",
    stateCode: "KE",
    cities: [
      nigeriaKebbiSstateArgungu,
      nigeriaKebbiSstateBagudo,
      nigeriaKebbiSstateBena,
      nigeriaKebbiSstateBinYauri,
      nigeriaKebbiSstateBirninKebbi,
      nigeriaKebbiSstateDabai,
      nigeriaKebbiSstateDakingari,
      nigeriaKebbiSstateGulma,
      nigeriaKebbiSstateGwandu,
      nigeriaKebbiSstateJega,
      nigeriaKebbiSstateKamba,
      nigeriaKebbiSstateKangiwa,
      nigeriaKebbiSstateKende,
      nigeriaKebbiSstateMahuta,
      nigeriaKebbiSstateMaiyama,
      nigeriaKebbiSstateShanga,
      nigeriaKebbiSstateWasagu,
      nigeriaKebbiSstateZuru
    ]);
const Region nigeriaKogiSstate = Region(
    id: 298,
    parentId: 161,
    longitude: 6.6905836,
    latitude: 7.7337325,
    name: "Kogi",
    type: "state",
    stateCode: "KO",
    cities: [
      nigeriaKogiSstateAbocho,
      nigeriaKogiSstateAdoru,
      nigeriaKogiSstateAnkpa,
      nigeriaKogiSstateBugana,
      nigeriaKogiSstateDekina,
      nigeriaKogiSstateEgbe,
      nigeriaKogiSstateIcheu,
      nigeriaKogiSstateIdah,
      nigeriaKogiSstateIsanluHypItedoijowa,
      nigeriaKogiSstateKabba,
      nigeriaKogiSstateKotonHypKarfe,
      nigeriaKogiSstateLokoja,
      nigeriaKogiSstateOgaminana,
      nigeriaKogiSstateOgurugu,
      nigeriaKogiSstateOkene
    ]);
const Region nigeriaKwaraSstate = Region(
    id: 295,
    parentId: 161,
    longitude: 4.3874051,
    latitude: 8.9668961,
    name: "Kwara",
    type: "state",
    stateCode: "KW",
    cities: [
      nigeriaKwaraSstateAjasseIpo,
      nigeriaKwaraSstateBodeSaadu,
      nigeriaKwaraSstateGwasero,
      nigeriaKwaraSstateIlorin,
      nigeriaKwaraSstateJebba,
      nigeriaKwaraSstateKaiama,
      nigeriaKwaraSstateLafiagi,
      nigeriaKwaraSstateOffa,
      nigeriaKwaraSstateOkuta,
      nigeriaKwaraSstateOmuHypAran,
      nigeriaKwaraSstatePatigi,
      nigeriaKwaraSstateSuya,
      nigeriaKwaraSstateYashikera
    ]);
const Region nigeriaLagosSstate = Region(
    id: 306,
    parentId: 161,
    longitude: 3.3792057,
    latitude: 6.5243793,
    name: "Lagos",
    type: "state",
    stateCode: "LA",
    cities: [
      nigeriaLagosSstateApapa,
      nigeriaLagosSstateBadagry,
      nigeriaLagosSstateEbuteIkorodu,
      nigeriaLagosSstateEjirin,
      nigeriaLagosSstateEpe,
      nigeriaLagosSstateIkeja,
      nigeriaLagosSstateLagos,
      nigeriaLagosSstateMakoko
    ]);
const Region nigeriaNasarawaSstate = Region(
    id: 301,
    parentId: 161,
    longitude: 8.1996937,
    latitude: 8.4997908,
    name: "Nasarawa",
    type: "state",
    stateCode: "NA",
    cities: [
      nigeriaNasarawaSstateBuga,
      nigeriaNasarawaSstateDoma,
      nigeriaNasarawaSstateKeffi,
      nigeriaNasarawaSstateLafia,
      nigeriaNasarawaSstateNasarawa,
      nigeriaNasarawaSstateWamba
    ]);
const Region nigeriaNigerSstate = Region(
    id: 317,
    parentId: 161,
    longitude: 5.598321,
    latitude: 9.9309224,
    name: "Niger",
    type: "state",
    stateCode: "NI",
    cities: [
      nigeriaNigerSstateAuna,
      nigeriaNigerSstateBabana,
      nigeriaNigerSstateBadeggi,
      nigeriaNigerSstateBaro,
      nigeriaNigerSstateBokani,
      nigeriaNigerSstateDuku,
      nigeriaNigerSstateIbeto,
      nigeriaNigerSstateKonkwesso,
      nigeriaNigerSstateKontagora,
      nigeriaNigerSstateKusheriki,
      nigeriaNigerSstateKuta,
      nigeriaNigerSstateLapai,
      nigeriaNigerSstateMinna,
      nigeriaNigerSstateNewShagunnu,
      nigeriaNigerSstateSuleja,
      nigeriaNigerSstateTegina,
      nigeriaNigerSstateUkata,
      nigeriaNigerSstateWawa,
      nigeriaNigerSstateZungeru
    ]);
const Region nigeriaOgunSstate = Region(
    id: 323,
    parentId: 161,
    longitude: 3.4737378,
    latitude: 6.9979747,
    name: "Ogun",
    type: "state",
    stateCode: "OG",
    cities: [
      nigeriaOgunSstateAbeokuta,
      nigeriaOgunSstateAdoOdo,
      nigeriaOgunSstateIdiIroko,
      nigeriaOgunSstateIfo,
      nigeriaOgunSstateIjebuHypIfe,
      nigeriaOgunSstateIjebuHypIgbo,
      nigeriaOgunSstateIjebuHypOde,
      nigeriaOgunSstateIlaro,
      nigeriaOgunSstateImeko,
      nigeriaOgunSstateIperu,
      nigeriaOgunSstateIsara,
      nigeriaOgunSstateOwode
    ]);
const Region nigeriaOndoSstate = Region(
    id: 321,
    parentId: 161,
    longitude: 5.1478144,
    latitude: 6.9148682,
    name: "Ondo",
    type: "state",
    stateCode: "ON",
    cities: [
      nigeriaOndoSstateAgbabu,
      nigeriaOndoSstateAkure,
      nigeriaOndoSstateIdanre,
      nigeriaOndoSstateIfon,
      nigeriaOndoSstateIlare,
      nigeriaOndoSstateOde,
      nigeriaOndoSstateOndo,
      nigeriaOndoSstateOre,
      nigeriaOndoSstateOwo
    ]);
const Region nigeriaOsunSstate = Region(
    id: 322,
    parentId: 161,
    longitude: 4.5199593,
    latitude: 7.5628964,
    name: "Osun",
    type: "state",
    stateCode: "OS",
    cities: [
      nigeriaOsunSstateApomu,
      nigeriaOsunSstateEjigbo,
      nigeriaOsunSstateGbongan,
      nigeriaOsunSstateIjebuHypJesa,
      nigeriaOsunSstateIkire,
      nigeriaOsunSstateIkirun,
      nigeriaOsunSstateIlaOrangun,
      nigeriaOsunSstateIleHypIfe,
      nigeriaOsunSstateIlesa,
      nigeriaOsunSstateIlobu,
      nigeriaOsunSstateInisa,
      nigeriaOsunSstateIwo,
      nigeriaOsunSstateModakeke,
      nigeriaOsunSstateOkeMesi,
      nigeriaOsunSstateOlupona,
      nigeriaOsunSstateOsogbo,
      nigeriaOsunSstateOtanAyegbaju,
      nigeriaOsunSstateOyan
    ]);
const Region nigeriaOyoSstate = Region(
    id: 296,
    parentId: 161,
    longitude: 3.6146534,
    latitude: 8.1573809,
    name: "Oyo",
    type: "state",
    stateCode: "OY",
    cities: [
      nigeriaOyoSstateAgoAre,
      nigeriaOyoSstateAlapa,
      nigeriaOyoSstateFiditi,
      nigeriaOyoSstateIbadan,
      nigeriaOyoSstateIgbeti,
      nigeriaOyoSstateIgboHypOra,
      nigeriaOyoSstateIgboho,
      nigeriaOyoSstateKisi,
      nigeriaOyoSstateLalupon,
      nigeriaOyoSstateOgbomoso,
      nigeriaOyoSstateOkeho,
      nigeriaOyoSstateOritaEruwa,
      nigeriaOyoSstateOyo,
      nigeriaOyoSstateSaki
    ]);
const Region nigeriaPlateauSstate = Region(
    id: 302,
    parentId: 161,
    longitude: 9.5179488,
    latitude: 9.2182093,
    name: "Plateau",
    type: "state",
    stateCode: "PL",
    cities: [
      nigeriaPlateauSstateAmper,
      nigeriaPlateauSstateBukuru,
      nigeriaPlateauSstateDengi,
      nigeriaPlateauSstateJos,
      nigeriaPlateauSstateKwolla,
      nigeriaPlateauSstateLangtang,
      nigeriaPlateauSstatePankshin,
      nigeriaPlateauSstatePanyam,
      nigeriaPlateauSstateVom,
      nigeriaPlateauSstateYelwa
    ]);
const Region nigeriaRiversSstate = Region(
    id: 4926,
    parentId: 161,
    longitude: 6.4376022,
    latitude: 5.021342,
    name: "Rivers",
    type: "state",
    stateCode: "RI",
    cities: [
      nigeriaRiversSstateAbalama,
      nigeriaRiversSstateAbonnema,
      nigeriaRiversSstateAhoada,
      nigeriaRiversSstateBori,
      nigeriaRiversSstateBuguma,
      nigeriaRiversSstateChokocho,
      nigeriaRiversSstateElele,
      nigeriaRiversSstateObonoma,
      nigeriaRiversSstateOmoku,
      nigeriaRiversSstateOnne,
      nigeriaRiversSstateOpobo,
      nigeriaRiversSstatePortHarcourt,
      nigeriaRiversSstateRumuokoro
    ]);
const Region nigeriaSokotoSstate = Region(
    id: 292,
    parentId: 161,
    longitude: 5.3222722,
    latitude: 13.0533143,
    name: "Sokoto",
    type: "state",
    stateCode: "SO",
    cities: [
      nigeriaSokotoSstateBinji,
      nigeriaSokotoSstateDange,
      nigeriaSokotoSstateGandi,
      nigeriaSokotoSstateGoronyo,
      nigeriaSokotoSstateGwadabawa,
      nigeriaSokotoSstateIllela,
      nigeriaSokotoSstateRabah,
      nigeriaSokotoSstateSokoto,
      nigeriaSokotoSstateTambuwal,
      nigeriaSokotoSstateWurno
    ]);
const Region nigeriaTarabaSstate = Region(
    id: 319,
    parentId: 161,
    longitude: 10.7739863,
    latitude: 7.9993616,
    name: "Taraba",
    type: "state",
    stateCode: "TA",
    cities: [
      nigeriaTarabaSstateBaissa,
      nigeriaTarabaSstateBeli,
      nigeriaTarabaSstateGassol,
      nigeriaTarabaSstateGembu,
      nigeriaTarabaSstateIbi,
      nigeriaTarabaSstateJalingo,
      nigeriaTarabaSstateLau,
      nigeriaTarabaSstateMutumBiyu,
      nigeriaTarabaSstateRiti,
      nigeriaTarabaSstateWukari
    ]);
const Region nigeriaYobeSstate = Region(
    id: 297,
    parentId: 161,
    longitude: 11.4390411,
    latitude: 12.293876,
    name: "Yobe",
    type: "state",
    stateCode: "YO",
    cities: [
      nigeriaYobeSstateDamaturu,
      nigeriaYobeSstateDankalwa,
      nigeriaYobeSstateDapchi,
      nigeriaYobeSstateDaura,
      nigeriaYobeSstateFika,
      nigeriaYobeSstateGashua,
      nigeriaYobeSstateGeidam,
      nigeriaYobeSstateGoniri,
      nigeriaYobeSstateGorgoram,
      nigeriaYobeSstateGujba,
      nigeriaYobeSstateGwioKura,
      nigeriaYobeSstateKumagunnam,
      nigeriaYobeSstateLajere,
      nigeriaYobeSstateMachina,
      nigeriaYobeSstateNguru,
      nigeriaYobeSstatePotiskum
    ]);
const Region nigeriaZamfaraSstate = Region(
    id: 299,
    parentId: 161,
    longitude: 6.2235819,
    latitude: 12.1221805,
    name: "Zamfara",
    type: "state",
    stateCode: "ZA",
    cities: [
      nigeriaZamfaraSstateAnka,
      nigeriaZamfaraSstateDanSadau,
      nigeriaZamfaraSstateGummi,
      nigeriaZamfaraSstateGusau,
      nigeriaZamfaraSstateKauraNamoda,
      nigeriaZamfaraSstateKwatarkwashi,
      nigeriaZamfaraSstateMaru,
      nigeriaZamfaraSstateMoriki,
      nigeriaZamfaraSstateSauri,
      nigeriaZamfaraSstateTsafe
    ]);

const nigeriaStates = <int, Region>{
  303: nigeriaAbiaSstate,
  293: nigeriaAbujaFederalCapitalTerritoryCcapitalTterritory,
  320: nigeriaAdamawaSstate,
  304: nigeriaAkwaIbomSstate,
  315: nigeriaAnambraSstate,
  312: nigeriaBauchiSstate,
  305: nigeriaBayelsaSstate,
  291: nigeriaBenueSstate,
  307: nigeriaBornoSstate,
  314: nigeriaCrossRiverSstate,
  316: nigeriaDeltaSstate,
  311: nigeriaEbonyiSstate,
  318: nigeriaEdoSstate,
  309: nigeriaEkitiSstate,
  289: nigeriaEnuguSstate,
  310: nigeriaGombeSstate,
  308: nigeriaImoSstate,
  288: nigeriaJigawaSstate,
  294: nigeriaKadunaSstate,
  300: nigeriaKanoSstate,
  313: nigeriaKatsinaSstate,
  290: nigeriaKebbiSstate,
  298: nigeriaKogiSstate,
  295: nigeriaKwaraSstate,
  306: nigeriaLagosSstate,
  301: nigeriaNasarawaSstate,
  317: nigeriaNigerSstate,
  323: nigeriaOgunSstate,
  321: nigeriaOndoSstate,
  322: nigeriaOsunSstate,
  296: nigeriaOyoSstate,
  302: nigeriaPlateauSstate,
  4926: nigeriaRiversSstate,
  292: nigeriaSokotoSstate,
  319: nigeriaTarabaSstate,
  297: nigeriaYobeSstate,
  299: nigeriaZamfaraSstate
};
