/// Access to known geographies in Norway and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'norway_cities.dart';

/// The 21 regions of `🇳🇴 Norway`
const Region norwayAkershus = Region(
    id: 1017,
    parentId: 165,
    longitude: -81.5468058,
    latitude: 28.3704203,
    name: "Akershus",
    type: null,
    stateCode: "02",
    cities: [
      norwayAkershusAneby,
      norwayAkershusArnes,
      norwayAkershusAs,
      norwayAkershusAsk,
      norwayAkershusAsker,
      norwayAkershusAuli,
      norwayAkershusAurskogHypHoland,
      norwayAkershusAursmoen,
      norwayAkershusBaerum,
      norwayAkershusBillingstad,
      norwayAkershusBjorkelangen,
      norwayAkershusBlakstad,
      norwayAkershusDrobak,
      norwayAkershusEidsvoll,
      norwayAkershusEnebakk,
      norwayAkershusFagerstrand,
      norwayAkershusFet,
      norwayAkershusFetsund,
      norwayAkershusFjellfoten,
      norwayAkershusFlateby,
      norwayAkershusFrogn,
      norwayAkershusFrogner,
      norwayAkershusGjerdrum,
      norwayAkershusHurdal,
      norwayAkershusJessheim,
      norwayAkershusKlofta,
      norwayAkershusLeirsund,
      norwayAkershusLillestrom,
      norwayAkershusLorenskog,
      norwayAkershusLysaker,
      norwayAkershusMaura,
      norwayAkershusNannestad,
      norwayAkershusNes,
      norwayAkershusNeskollen,
      norwayAkershusNesodden,
      norwayAkershusNesoddtangen,
      norwayAkershusNittedal,
      norwayAkershusOppegard,
      norwayAkershusRaholt,
      norwayAkershusRaelingen,
      norwayAkershusRotnes,
      norwayAkershusSkedsmo,
      norwayAkershusSki,
      norwayAkershusSkui,
      norwayAkershusSorum,
      norwayAkershusSorumsand,
      norwayAkershusUllensaker,
      norwayAkershusVestby
    ]);
const Region norwayBuskerud = Region(
    id: 1011,
    parentId: 165,
    longitude: 8.6983764,
    latitude: 60.4846025,
    name: "Buskerud",
    type: null,
    stateCode: "06",
    cities: [
      norwayBuskerudAl,
      norwayBuskerudAros,
      norwayBuskerudDrammen,
      norwayBuskerudFla,
      norwayBuskerudFlesberg,
      norwayBuskerudGeilo,
      norwayBuskerudGol,
      norwayBuskerudHemsedal,
      norwayBuskerudHol,
      norwayBuskerudHole,
      norwayBuskerudHonefoss,
      norwayBuskerudHurum,
      norwayBuskerudHvittingfoss,
      norwayBuskerudKongsberg,
      norwayBuskerudKrodsherad,
      norwayBuskerudLier,
      norwayBuskerudModum,
      norwayBuskerudNedreEiker,
      norwayBuskerudNes,
      norwayBuskerudNesbyen,
      norwayBuskerudNoreOogUvdal,
      norwayBuskerudNoresund,
      norwayBuskerudOvreEiker,
      norwayBuskerudPrestfoss,
      norwayBuskerudRingerike,
      norwayBuskerudRollag,
      norwayBuskerudRoyken,
      norwayBuskerudSaetre,
      norwayBuskerudSigdal,
      norwayBuskerudSkoger,
      norwayBuskerudTofte,
      norwayBuskerudTranby,
      norwayBuskerudVikersund
    ]);
const Region norwayFinnmark = Region(
    id: 1016,
    parentId: 165,
    longitude: 26.0135107,
    latitude: 70.4830388,
    name: "Finnmark",
    type: null,
    stateCode: "20",
    cities: [
      norwayFinnmarkAlta,
      norwayFinnmarkAvanuorri,
      norwayFinnmarkBatsfjord,
      norwayFinnmarkBerlevag,
      norwayFinnmarkBjornevatn,
      norwayFinnmarkGamvik,
      norwayFinnmarkHammerfest,
      norwayFinnmarkHasvik,
      norwayFinnmarkHonningsvag,
      norwayFinnmarkKarasjohka,
      norwayFinnmarkKarasjok,
      norwayFinnmarkKautokeino,
      norwayFinnmarkKirkenes,
      norwayFinnmarkKjollefjord,
      norwayFinnmarkKvalsund,
      norwayFinnmarkLakselv,
      norwayFinnmarkLebesby,
      norwayFinnmarkLoppa,
      norwayFinnmarkMasoy,
      norwayFinnmarkMehamn,
      norwayFinnmarkNesseby,
      norwayFinnmarkNordkapp,
      norwayFinnmarkOksfjord,
      norwayFinnmarkPorsanger,
      norwayFinnmarkRypefjord,
      norwayFinnmarkSorHypVaranger,
      norwayFinnmarkTana,
      norwayFinnmarkVadso,
      norwayFinnmarkVardo
    ]);
const Region norwayHedmark = Region(
    id: 1019,
    parentId: 165,
    longitude: 11.5627369,
    latitude: 61.3967311,
    name: "Hedmark",
    type: null,
    stateCode: "04",
    cities: [
      norwayHedmarkAlvdal,
      norwayHedmarkAmot,
      norwayHedmarkAsnes,
      norwayHedmarkBrumunddal,
      norwayHedmarkEidskog,
      norwayHedmarkElverum,
      norwayHedmarkEngerdal,
      norwayHedmarkFolldal,
      norwayHedmarkGrue,
      norwayHedmarkHamar,
      norwayHedmarkInnbygda,
      norwayHedmarkKirkenaer,
      norwayHedmarkKongsvinger,
      norwayHedmarkKoppang,
      norwayHedmarkLoten,
      norwayHedmarkMoelv,
      norwayHedmarkNordHypOdal,
      norwayHedmarkOs,
      norwayHedmarkRena,
      norwayHedmarkRendalen,
      norwayHedmarkRingsaker,
      norwayHedmarkSand,
      norwayHedmarkSkarnes,
      norwayHedmarkSkotterud,
      norwayHedmarkSorHypOdal,
      norwayHedmarkSpetalen,
      norwayHedmarkStange,
      norwayHedmarkStorHypElvdal,
      norwayHedmarkTolga,
      norwayHedmarkTrysil,
      norwayHedmarkTynset,
      norwayHedmarkValer
    ]);
const Region norwayHordaland = Region(
    id: 1023,
    parentId: 165,
    longitude: 5.7220194,
    latitude: 60.2733674,
    name: "Hordaland",
    type: null,
    stateCode: "12",
    cities: [
      norwayHordalandAgotnes,
      norwayHordalandAskoy,
      norwayHordalandAustevoll,
      norwayHordalandAustrheim,
      norwayHordalandBergen,
      norwayHordalandBomlo,
      norwayHordalandDale,
      norwayHordalandEidfjord,
      norwayHordalandEikelandsosen,
      norwayHordalandEspeland,
      norwayHordalandEtne,
      norwayHordalandFedje,
      norwayHordalandFitjar,
      norwayHordalandFjell,
      norwayHordalandFrekhaug,
      norwayHordalandFusa,
      norwayHordalandGranvin,
      norwayHordalandHagavik,
      norwayHordalandHylkje,
      norwayHordalandIndreArna,
      norwayHordalandJondal,
      norwayHordalandKinsarvik,
      norwayHordalandKnappskog,
      norwayHordalandKnarvik,
      norwayHordalandKvam,
      norwayHordalandKvinnherad,
      norwayHordalandLeirvik,
      norwayHordalandLindas,
      norwayHordalandLonevag,
      norwayHordalandManger,
      norwayHordalandMasfjorden,
      norwayHordalandMeland,
      norwayHordalandModalen,
      norwayHordalandMosterhamn,
      norwayHordalandNorheimsund,
      norwayHordalandOdda,
      norwayHordalandOs,
      norwayHordalandOsteroy,
      norwayHordalandOygarden,
      norwayHordalandOystese,
      norwayHordalandRadoy,
      norwayHordalandRosendal,
      norwayHordalandRubbestadneset,
      norwayHordalandSagvag,
      norwayHordalandSamnanger,
      norwayHordalandSandsli,
      norwayHordalandSkogsvagen,
      norwayHordalandStord,
      norwayHordalandStorebo,
      norwayHordalandStraume,
      norwayHordalandSund,
      norwayHordalandSveio,
      norwayHordalandSyfteland,
      norwayHordalandTysnes,
      norwayHordalandUllensvang,
      norwayHordalandUlvik,
      norwayHordalandVaksdal,
      norwayHordalandVoss,
      norwayHordalandYtreArna,
      norwayHordalandYtrebygda
    ]);
const Region norwayJanMayen = Region(
    id: 1026,
    parentId: 165,
    longitude: -8.2920346,
    latitude: 71.031818,
    name: "Jan Mayen",
    type: null,
    stateCode: "22",
    cities: []);
const Region norwayMoreOogRomsdal = Region(
    id: 1020,
    parentId: 165,
    longitude: 7.007143,
    latitude: 62.8406833,
    name: "Møre og Romsdal",
    type: null,
    stateCode: "15",
    cities: [
      norwayMoreOogRomsdalAlesund,
      norwayMoreOogRomsdalAndalsnes,
      norwayMoreOogRomsdalAukra,
      norwayMoreOogRomsdalAure,
      norwayMoreOogRomsdalAveroy,
      norwayMoreOogRomsdalBatnfjordsora,
      norwayMoreOogRomsdalBrattvag,
      norwayMoreOogRomsdalEide,
      norwayMoreOogRomsdalEidsvag,
      norwayMoreOogRomsdalElnesvagen,
      norwayMoreOogRomsdalFraena,
      norwayMoreOogRomsdalGiske,
      norwayMoreOogRomsdalGjemnes,
      norwayMoreOogRomsdalHalsa,
      norwayMoreOogRomsdalHaram,
      norwayMoreOogRomsdalHareid,
      norwayMoreOogRomsdalHeroy,
      norwayMoreOogRomsdalHjelset,
      norwayMoreOogRomsdalHopen,
      norwayMoreOogRomsdalKristiansund,
      norwayMoreOogRomsdalLarsnes,
      norwayMoreOogRomsdalMidsund,
      norwayMoreOogRomsdalMolde,
      norwayMoreOogRomsdalNesset,
      norwayMoreOogRomsdalNorddal,
      norwayMoreOogRomsdalNordstranda,
      norwayMoreOogRomsdalOrskog,
      norwayMoreOogRomsdalOrsta,
      norwayMoreOogRomsdalRauma,
      norwayMoreOogRomsdalRensvik,
      norwayMoreOogRomsdalSande,
      norwayMoreOogRomsdalSandoy,
      norwayMoreOogRomsdalSjoholt,
      norwayMoreOogRomsdalSkodje,
      norwayMoreOogRomsdalSmola,
      norwayMoreOogRomsdalSteinshamn,
      norwayMoreOogRomsdalStordal,
      norwayMoreOogRomsdalStranda,
      norwayMoreOogRomsdalSula,
      norwayMoreOogRomsdalSunndal,
      norwayMoreOogRomsdalSunndalsora,
      norwayMoreOogRomsdalSurnadal,
      norwayMoreOogRomsdalSykkylven,
      norwayMoreOogRomsdalTingvoll,
      norwayMoreOogRomsdalTomra,
      norwayMoreOogRomsdalUlstein,
      norwayMoreOogRomsdalUlsteinvik,
      norwayMoreOogRomsdalUlsteinvikWweatherPpwsSstation,
      norwayMoreOogRomsdalVanylven,
      norwayMoreOogRomsdalVatne,
      norwayMoreOogRomsdalVestnes,
      norwayMoreOogRomsdalVolda
    ]);
const Region norwayNordHypTrondelag = Region(
    id: 1012,
    parentId: 165,
    longitude: 11.746295,
    latitude: 64.4370792,
    name: "Nord-Trøndelag",
    type: null,
    stateCode: "17",
    cities: []);
const Region norwayNordland = Region(
    id: 1025,
    parentId: 165,
    longitude: 12.7073936,
    latitude: 67.693058,
    name: "Nordland",
    type: null,
    stateCode: "18",
    cities: [
      norwayNordlandAlstahaug,
      norwayNordlandAndenes,
      norwayNordlandAndoy,
      norwayNordlandBallangen,
      norwayNordlandBeiarn,
      norwayNordlandBindal,
      norwayNordlandBjerkvik,
      norwayNordlandBodo,
      norwayNordlandBogen,
      norwayNordlandBo,
      norwayNordlandBronnoy,
      norwayNordlandBronnoysund,
      norwayNordlandDonna,
      norwayNordlandEvenes,
      norwayNordlandEvjen,
      norwayNordlandFauske,
      norwayNordlandFlakstad,
      norwayNordlandGildeskal,
      norwayNordlandGladstad,
      norwayNordlandGlomfjord,
      norwayNordlandGrane,
      norwayNordlandGravdal,
      norwayNordlandHadsel,
      norwayNordlandHamaroy,
      norwayNordlandHattfjelldal,
      norwayNordlandHauknes,
      norwayNordlandHemnes,
      norwayNordlandHemnesberget,
      norwayNordlandHeroy,
      norwayNordlandInndyr,
      norwayNordlandKabelvag,
      norwayNordlandKjopsvik,
      norwayNordlandKorgen,
      norwayNordlandLeirfjord,
      norwayNordlandLeknes,
      norwayNordlandLeland,
      norwayNordlandLoding,
      norwayNordlandLodingen,
      norwayNordlandLopsmarka,
      norwayNordlandLuroy,
      norwayNordlandMelbu,
      norwayNordlandMeloy,
      norwayNordlandMoIiRana,
      norwayNordlandMosjoen,
      norwayNordlandMoskenes,
      norwayNordlandMyre,
      norwayNordlandNarvik,
      norwayNordlandNesna,
      norwayNordlandOksnes,
      norwayNordlandOrnes,
      norwayNordlandRana,
      norwayNordlandReine,
      norwayNordlandRognan,
      norwayNordlandRodoy,
      norwayNordlandRost,
      norwayNordlandSaltdal,
      norwayNordlandSandnessjoen,
      norwayNordlandSortland,
      norwayNordlandSomna,
      norwayNordlandSorfold,
      norwayNordlandSorland,
      norwayNordlandSteigen,
      norwayNordlandStokmarknes,
      norwayNordlandStraume,
      norwayNordlandStraumen,
      norwayNordlandSvolvaer,
      norwayNordlandTerrak,
      norwayNordlandTjeldsund,
      norwayNordlandTraena,
      norwayNordlandTrofors,
      norwayNordlandTysfjord,
      norwayNordlandVagan,
      norwayNordlandVaeroy,
      norwayNordlandVefsn,
      norwayNordlandVega,
      norwayNordlandVestvagoy,
      norwayNordlandVevelstad,
      norwayNordlandVik
    ]);
const Region norwayOppland = Region(
    id: 1009,
    parentId: 165,
    longitude: 9.7166315,
    latitude: 61.5422752,
    name: "Oppland",
    type: null,
    stateCode: "05",
    cities: [
      norwayOpplandBagn,
      norwayOpplandDokka,
      norwayOpplandDombas,
      norwayOpplandDovre,
      norwayOpplandEtnedal,
      norwayOpplandFagernes,
      norwayOpplandFossbergom,
      norwayOpplandGausdal,
      norwayOpplandGjovik,
      norwayOpplandGran,
      norwayOpplandGrua,
      norwayOpplandHov,
      norwayOpplandHundorp,
      norwayOpplandJevnaker,
      norwayOpplandLena,
      norwayOpplandLesja,
      norwayOpplandLillehammer,
      norwayOpplandLom,
      norwayOpplandLunner,
      norwayOpplandNordHypAurdal,
      norwayOpplandNordHypFron,
      norwayOpplandNordreLand,
      norwayOpplandOtta,
      norwayOpplandOstreToten,
      norwayOpplandOyer,
      norwayOpplandOystreSlidre,
      norwayOpplandRaufoss,
      norwayOpplandReinsvoll,
      norwayOpplandRingebu,
      norwayOpplandSel,
      norwayOpplandSkjak,
      norwayOpplandSkreia,
      norwayOpplandSondreLand,
      norwayOpplandSorHypAurdal,
      norwayOpplandSorHypFron,
      norwayOpplandTretten,
      norwayOpplandVaga,
      norwayOpplandVagamo,
      norwayOpplandVang,
      norwayOpplandVestreSlidre,
      norwayOpplandVestreToten,
      norwayOpplandVinstra
    ]);
const Region norwayOslo = Region(
    id: 1007,
    parentId: 165,
    longitude: 10.7522454,
    latitude: 59.9138688,
    name: "Oslo",
    type: null,
    stateCode: "03",
    cities: [norwayOsloOslo, norwayOsloSjolyststranda]);
const Region norwayOstfold = Region(
    id: 1022,
    parentId: 165,
    longitude: 11.3279006,
    latitude: 59.2558286,
    name: "Østfold",
    type: null,
    stateCode: "01",
    cities: [
      norwayOstfoldAremark,
      norwayOstfoldAskim,
      norwayOstfoldEidsberg,
      norwayOstfoldFossby,
      norwayOstfoldFredrikstad,
      norwayOstfoldHalden,
      norwayOstfoldHobol,
      norwayOstfoldHvaler,
      norwayOstfoldKarlshus,
      norwayOstfoldKnappstad,
      norwayOstfoldLarkollen,
      norwayOstfoldLervik,
      norwayOstfoldMarker,
      norwayOstfoldMoss,
      norwayOstfoldMysen,
      norwayOstfoldOrje,
      norwayOstfoldRade,
      norwayOstfoldRakkestad,
      norwayOstfoldRomskog,
      norwayOstfoldRygge,
      norwayOstfoldRyggebyen,
      norwayOstfoldSarpsborg,
      norwayOstfoldSkiptvet,
      norwayOstfoldSkjaerhalden,
      norwayOstfoldSkjeberg,
      norwayOstfoldSpydeberg,
      norwayOstfoldTomter,
      norwayOstfoldTrogstad,
      norwayOstfoldValer
    ]);
const Region norwayRogaland = Region(
    id: 1021,
    parentId: 165,
    longitude: 6.0143432,
    latitude: 59.1489544,
    name: "Rogaland",
    type: null,
    stateCode: "11",
    cities: [
      norwayRogalandAkrehamn,
      norwayRogalandBjerkreim,
      norwayRogalandBokn,
      norwayRogalandBryne,
      norwayRogalandEgersund,
      norwayRogalandEigersund,
      norwayRogalandEike,
      norwayRogalandFinnoy,
      norwayRogalandForsand,
      norwayRogalandGjesdal,
      norwayRogalandHa,
      norwayRogalandHaugeIiDalane,
      norwayRogalandHaugesund,
      norwayRogalandHjelmeland,
      norwayRogalandHommersak,
      norwayRogalandJorpeland,
      norwayRogalandJudaberg,
      norwayRogalandKarmoy,
      norwayRogalandKlepp,
      norwayRogalandKopervik,
      norwayRogalandKvitsoy,
      norwayRogalandLund,
      norwayRogalandLyefjell,
      norwayRogalandMoi,
      norwayRogalandNaerbo,
      norwayRogalandOlen,
      norwayRogalandRandaberg,
      norwayRogalandRennesoy,
      norwayRogalandSandnes,
      norwayRogalandSauda,
      norwayRogalandSaeveland,
      norwayRogalandSkudeneshavn,
      norwayRogalandSokndal,
      norwayRogalandSola,
      norwayRogalandStavanger,
      norwayRogalandStrand,
      norwayRogalandSuldal,
      norwayRogalandTananger,
      norwayRogalandTau,
      norwayRogalandTime,
      norwayRogalandTysvaer,
      norwayRogalandUtsira,
      norwayRogalandVarhaug,
      norwayRogalandVedavagen,
      norwayRogalandVigrestad,
      norwayRogalandVikesa,
      norwayRogalandVikevag,
      norwayRogalandVindafjord,
      norwayRogalandVormedal
    ]);
const Region norwaySognOogFjordane = Region(
    id: 1018,
    parentId: 165,
    longitude: 6.3325879,
    latitude: 61.5539435,
    name: "Sogn og Fjordane",
    type: null,
    stateCode: "14",
    cities: [
      norwaySognOogFjordaneArdal,
      norwaySognOogFjordaneArdalstangen,
      norwaySognOogFjordaneAskvoll,
      norwaySognOogFjordaneAurland,
      norwaySognOogFjordaneBalestrand,
      norwaySognOogFjordaneBremanger,
      norwaySognOogFjordaneDale,
      norwaySognOogFjordaneEid,
      norwaySognOogFjordaneEivindvik,
      norwaySognOogFjordaneFarnes,
      norwaySognOogFjordaneFjaler,
      norwaySognOogFjordaneFlora,
      norwaySognOogFjordaneFloro,
      norwaySognOogFjordaneForde,
      norwaySognOogFjordaneGaular,
      norwaySognOogFjordaneGaupne,
      norwaySognOogFjordaneGloppen,
      norwaySognOogFjordaneGulen,
      norwaySognOogFjordaneHardbakke,
      norwaySognOogFjordaneHermansverk,
      norwaySognOogFjordaneHornindal,
      norwaySognOogFjordaneHoyanger,
      norwaySognOogFjordaneHyllestad,
      norwaySognOogFjordaneJolster,
      norwaySognOogFjordaneLaerdal,
      norwaySognOogFjordaneLaerdalsoyri,
      norwaySognOogFjordaneLeikanger,
      norwaySognOogFjordaneLuster,
      norwaySognOogFjordaneMaloy,
      norwaySognOogFjordaneNaustdal,
      norwaySognOogFjordaneNordfjordeid,
      norwaySognOogFjordaneSandane,
      norwaySognOogFjordaneSande,
      norwaySognOogFjordaneSelje,
      norwaySognOogFjordaneSogndal,
      norwaySognOogFjordaneSolund,
      norwaySognOogFjordaneStryn,
      norwaySognOogFjordaneSvelgen,
      norwaySognOogFjordaneVagsoy,
      norwaySognOogFjordaneVik
    ]);
const Region norwaySorHypTrondelag = Region(
    id: 1010,
    parentId: 165,
    longitude: 10.3487136,
    latitude: 63.0136823,
    name: "Sør-Trøndelag",
    type: null,
    stateCode: "16",
    cities: []);
const Region norwaySvalbard = Region(
    id: 1013,
    parentId: 165,
    longitude: 20.9751821,
    latitude: 77.8749725,
    name: "Svalbard",
    type: null,
    stateCode: "21",
    cities: []);
const Region norwayTelemark = Region(
    id: 1024,
    parentId: 165,
    longitude: 8.3211209,
    latitude: 59.3913985,
    name: "Telemark",
    type: null,
    stateCode: "08",
    cities: [
      norwayTelemarkBamble,
      norwayTelemarkBo,
      norwayTelemarkDalen,
      norwayTelemarkDrangedal,
      norwayTelemarkFyresdal,
      norwayTelemarkGvarv,
      norwayTelemarkHerre,
      norwayTelemarkHjartdal,
      norwayTelemarkKragero,
      norwayTelemarkKviteseid,
      norwayTelemarkLunde,
      norwayTelemarkNissedal,
      norwayTelemarkNome,
      norwayTelemarkNotodden,
      norwayTelemarkPorsgrunn,
      norwayTelemarkPrestestranda,
      norwayTelemarkRjukan,
      norwayTelemarkSauherad,
      norwayTelemarkSeljord,
      norwayTelemarkSiljan,
      norwayTelemarkSkien,
      norwayTelemarkTinn,
      norwayTelemarkTokke,
      norwayTelemarkUlefoss,
      norwayTelemarkVinje
    ]);
const Region norwayTroms = Region(
    id: 1015,
    parentId: 165,
    longitude: 18.7819365,
    latitude: 69.8178242,
    name: "Troms",
    type: null,
    stateCode: "19",
    cities: [
      norwayTromsBalsfjord,
      norwayTromsBardu,
      norwayTromsBerg,
      norwayTromsBorkenes,
      norwayTromsDyroy,
      norwayTromsEvenskjer,
      norwayTromsFinnsnes,
      norwayTromsGratangen,
      norwayTromsGryllefjord,
      norwayTromsHansnes,
      norwayTromsHarstad,
      norwayTromsIbestad,
      norwayTromsKafjord,
      norwayTromsKarlsoy,
      norwayTromsKvaefjord,
      norwayTromsKvaenangen,
      norwayTromsLavangen,
      norwayTromsLenvik,
      norwayTromsLyngen,
      norwayTromsLyngseidet,
      norwayTromsMalselv,
      norwayTromsMoen,
      norwayTromsNordreisa,
      norwayTromsOlderdalen,
      norwayTromsSalangen,
      norwayTromsSetermoen,
      norwayTromsSjovegan,
      norwayTromsSkanland,
      norwayTromsSkjervoy,
      norwayTromsSorreisa,
      norwayTromsStorfjord,
      norwayTromsStorslett,
      norwayTromsStorsteinnes,
      norwayTromsTorsken,
      norwayTromsTranoy,
      norwayTromsTromso
    ]);
const Region norwayTrondelag = Region(
    id: 1006,
    parentId: 165,
    longitude: 10.9369267,
    latitude: 63.5420125,
    name: "Trøndelag",
    type: null,
    stateCode: "50",
    cities: [
      norwayTrondelagAIiAfjord,
      norwayTrondelagAfjord,
      norwayTrondelagAgdenes,
      norwayTrondelagBerkak,
      norwayTrondelagBjugn,
      norwayTrondelagBotngard,
      norwayTrondelagBrekstad,
      norwayTrondelagFillan,
      norwayTrondelagFlatanger,
      norwayTrondelagFosnes,
      norwayTrondelagFrosta,
      norwayTrondelagFroya,
      norwayTrondelagGrong,
      norwayTrondelagHemne,
      norwayTrondelagHitra,
      norwayTrondelagHoltalen,
      norwayTrondelagHommelvik,
      norwayTrondelagHoylandet,
      norwayTrondelagInderoy,
      norwayTrondelagIndreFosen,
      norwayTrondelagKlaebu,
      norwayTrondelagKolvereid,
      norwayTrondelagKyrksaeterora,
      norwayTrondelagLauvsnes,
      norwayTrondelagLeka,
      norwayTrondelagLevanger,
      norwayTrondelagLierne,
      norwayTrondelagLundamo,
      norwayTrondelagMalm,
      norwayTrondelagMalvik,
      norwayTrondelagMeldal,
      norwayTrondelagMelhus,
      norwayTrondelagMeraker,
      norwayTrondelagMidtreGauldal,
      norwayTrondelagNamdalseid,
      norwayTrondelagNamsos,
      norwayTrondelagNamsskogan,
      norwayTrondelagNaeroy,
      norwayTrondelagOppdal,
      norwayTrondelagOrkdal,
      norwayTrondelagOsen,
      norwayTrondelagOverhalla,
      norwayTrondelagOrland,
      norwayTrondelagRaarvihkeHypRoyrvik,
      norwayTrondelagRanemsletta,
      norwayTrondelagRennebu,
      norwayTrondelagRindal,
      norwayTrondelagRoan,
      norwayTrondelagRoros,
      norwayTrondelagRorvik,
      norwayTrondelagRoyrvik,
      norwayTrondelagSelbu,
      norwayTrondelagSistranda,
      norwayTrondelagSkaun,
      norwayTrondelagSkogn,
      norwayTrondelagSnaase,
      norwayTrondelagSnaaseHypSnasa,
      norwayTrondelagSnillfjord,
      norwayTrondelagSteinkjer,
      norwayTrondelagStjordal,
      norwayTrondelagStjordalshalsen,
      norwayTrondelagStraumen,
      norwayTrondelagTrondheim,
      norwayTrondelagTydal,
      norwayTrondelagVerdal,
      norwayTrondelagVerran,
      norwayTrondelagVikna
    ]);
const Region norwayVestHypAgder = Region(
    id: 1014,
    parentId: 165,
    longitude: 6.5869809,
    latitude: 58.0999081,
    name: "Vest-Agder",
    type: null,
    stateCode: "10",
    cities: [
      norwayVestHypAgderAseral,
      norwayVestHypAgderAudnedal,
      norwayVestHypAgderFarsund,
      norwayVestHypAgderFlekkefjord,
      norwayVestHypAgderHaegebostad,
      norwayVestHypAgderJustvik,
      norwayVestHypAgderKristiansand,
      norwayVestHypAgderKvinesdal,
      norwayVestHypAgderLiknes,
      norwayVestHypAgderLindesnes,
      norwayVestHypAgderLyngdal,
      norwayVestHypAgderMandal,
      norwayVestHypAgderMarnardal,
      norwayVestHypAgderNodeland,
      norwayVestHypAgderSirdal,
      norwayVestHypAgderSkalevik,
      norwayVestHypAgderSongdalen,
      norwayVestHypAgderSogne,
      norwayVestHypAgderStrai,
      norwayVestHypAgderTonstad,
      norwayVestHypAgderTveit,
      norwayVestHypAgderVanse,
      norwayVestHypAgderVennesla,
      norwayVestHypAgderVestbygd,
      norwayVestHypAgderVigeland
    ]);
const Region norwayVestfold = Region(
    id: 1008,
    parentId: 165,
    longitude: 10.1144355,
    latitude: 59.1707862,
    name: "Vestfold",
    type: null,
    stateCode: "07",
    cities: [
      norwayVestfoldAroysund,
      norwayVestfoldAsgardstrand,
      norwayVestfoldBarkaker,
      norwayVestfoldBerger,
      norwayVestfoldFaerder,
      norwayVestfoldGullhaug,
      norwayVestfoldHolmestrand,
      norwayVestfoldHorten,
      norwayVestfoldLarvik,
      norwayVestfoldMelsomvik,
      norwayVestfoldRe,
      norwayVestfoldSande,
      norwayVestfoldSandefjord,
      norwayVestfoldSelvik,
      norwayVestfoldSem,
      norwayVestfoldSkoppum,
      norwayVestfoldStavern,
      norwayVestfoldStokke,
      norwayVestfoldSvelvik,
      norwayVestfoldTjome,
      norwayVestfoldTonsberg
    ]);

const norwayStates = <int, Region>{
  1017: norwayAkershus,
  1011: norwayBuskerud,
  1016: norwayFinnmark,
  1019: norwayHedmark,
  1023: norwayHordaland,
  1026: norwayJanMayen,
  1020: norwayMoreOogRomsdal,
  1012: norwayNordHypTrondelag,
  1025: norwayNordland,
  1009: norwayOppland,
  1007: norwayOslo,
  1022: norwayOstfold,
  1021: norwayRogaland,
  1018: norwaySognOogFjordane,
  1010: norwaySorHypTrondelag,
  1013: norwaySvalbard,
  1024: norwayTelemark,
  1015: norwayTroms,
  1006: norwayTrondelag,
  1014: norwayVestHypAgder,
  1008: norwayVestfold
};
