/// Access to known geographies in Pakistan and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'pakistan_cities.dart';

/// The 8 regions of `🇵🇰 Pakistan`
const Region pakistanAzadKashmir = Region(
    id: 3172,
    parentId: 167,
    longitude: 73.7810334,
    latitude: 33.9259055,
    name: "Azad Kashmir",
    type: null,
    stateCode: "JK",
    cities: [
      pakistanAzadKashmirBhimbar,
      pakistanAzadKashmirKotli,
      pakistanAzadKashmirKotliDistrict,
      pakistanAzadKashmirMirpurDistrict,
      pakistanAzadKashmirMuzaffarabad,
      pakistanAzadKashmirNewMirpur,
      pakistanAzadKashmirRawalaKot
    ]);
const Region pakistanBalochistan = Region(
    id: 3174,
    parentId: 167,
    longitude: 65.0957792,
    latitude: 28.4907332,
    name: "Balochistan",
    type: null,
    stateCode: "BA",
    cities: [
      pakistanBalochistanAlikGhund,
      pakistanBalochistanAwaranDistrict,
      pakistanBalochistanBarkhan,
      pakistanBalochistanBarkhanDistrict,
      pakistanBalochistanBela,
      pakistanBalochistanBhag,
      pakistanBalochistanChagaiDistrict,
      pakistanBalochistanChaman,
      pakistanBalochistanChowkiJamali,
      pakistanBalochistanDadhar,
      pakistanBalochistanDalbandin,
      pakistanBalochistanDeraBugti,
      pakistanBalochistanDeraBugtiDistrict,
      pakistanBalochistanDuki,
      pakistanBalochistanGadani,
      pakistanBalochistanGarhiKhairo,
      pakistanBalochistanGwadar,
      pakistanBalochistanHarnai,
      pakistanBalochistanJafarabadDistrict,
      pakistanBalochistanJhalMagsiDistrict,
      pakistanBalochistanJiwani,
      pakistanBalochistanKalat,
      pakistanBalochistanKalatDistrict,
      pakistanBalochistanKhadanKhak,
      pakistanBalochistanKharan,
      pakistanBalochistanKharanDistrict,
      pakistanBalochistanKhuzdar,
      pakistanBalochistanKhuzdarDistrict,
      pakistanBalochistanKohlu,
      pakistanBalochistanKotMalikBarkhurdar,
      pakistanBalochistanLasbelaDistrict,
      pakistanBalochistanLoralai,
      pakistanBalochistanLoralaiDistrict,
      pakistanBalochistanMach,
      pakistanBalochistanMastung,
      pakistanBalochistanMastungDistrict,
      pakistanBalochistanMehrabpur,
      pakistanBalochistanMusaKhelDistrict,
      pakistanBalochistanNasirabadDistrict,
      pakistanBalochistanNushki,
      pakistanBalochistanOrmara,
      pakistanBalochistanPanjgurDistrict,
      pakistanBalochistanPasni,
      pakistanBalochistanPishin,
      pakistanBalochistanQilaSaifullahDistrict,
      pakistanBalochistanQuetta,
      pakistanBalochistanQuettaDistrict,
      pakistanBalochistanSibi,
      pakistanBalochistanSohbatpur,
      pakistanBalochistanSurab,
      pakistanBalochistanTurbat,
      pakistanBalochistanUstaMuhammad,
      pakistanBalochistanUthal,
      pakistanBalochistanZhob,
      pakistanBalochistanZhobDistrict,
      pakistanBalochistanZiarat,
      pakistanBalochistanZiaratDistrict
    ]);
const Region pakistanFederallyAdministeredTribalAreas = Region(
    id: 3173,
    parentId: 167,
    longitude: 69.8597406,
    latitude: 32.667476,
    name: "Federally Administered Tribal Areas",
    type: null,
    stateCode: "TA",
    cities: [
      pakistanFederallyAdministeredTribalAreasAlizai,
      pakistanFederallyAdministeredTribalAreasGulishahKach,
      pakistanFederallyAdministeredTribalAreasLandiKotal,
      pakistanFederallyAdministeredTribalAreasMiranShah,
      pakistanFederallyAdministeredTribalAreasNorthWaziristanAgency,
      pakistanFederallyAdministeredTribalAreasShinpokh,
      pakistanFederallyAdministeredTribalAreasSouthWaziristanAgency,
      pakistanFederallyAdministeredTribalAreasWana
    ]);
const Region pakistanGilgitHypBaltistan = Region(
    id: 3170,
    parentId: 167,
    longitude: 74.9831808,
    latitude: 35.8025667,
    name: "Gilgit-Baltistan",
    type: null,
    stateCode: "GB",
    cities: [
      pakistanGilgitHypBaltistanBarishal,
      pakistanGilgitHypBaltistanGilgit,
      pakistanGilgitHypBaltistanSkardu
    ]);
const Region pakistanIslamabadCapitalTerritory = Region(
    id: 3169,
    parentId: 167,
    longitude: 73.0405277,
    latitude: 33.7204997,
    name: "Islamabad Capital Territory",
    type: null,
    stateCode: "IS",
    cities: [pakistanIslamabadCapitalTerritoryIslamabad]);
const Region pakistanKhyberPakhtunkhwa = Region(
    id: 3171,
    parentId: 167,
    longitude: 72.331113,
    latitude: 34.9526205,
    name: "Khyber Pakhtunkhwa",
    type: null,
    stateCode: "KP",
    cities: [
      pakistanKhyberPakhtunkhwaAbbottabad,
      pakistanKhyberPakhtunkhwaAkora,
      pakistanKhyberPakhtunkhwaAmanGarh,
      pakistanKhyberPakhtunkhwaAmirabad,
      pakistanKhyberPakhtunkhwaAshanagroKoto,
      pakistanKhyberPakhtunkhwaBaffa,
      pakistanKhyberPakhtunkhwaBannu,
      pakistanKhyberPakhtunkhwaBatKhela,
      pakistanKhyberPakhtunkhwaBattagram,
      pakistanKhyberPakhtunkhwaBattagramDistrict,
      pakistanKhyberPakhtunkhwaBunerDistrict,
      pakistanKhyberPakhtunkhwaCharsadda,
      pakistanKhyberPakhtunkhwaCheratCantonement,
      pakistanKhyberPakhtunkhwaChitral,
      pakistanKhyberPakhtunkhwaDeraIsmailKhan,
      pakistanKhyberPakhtunkhwaDeraIsmailKhanDistrict,
      pakistanKhyberPakhtunkhwaDoaba,
      pakistanKhyberPakhtunkhwaHangu,
      pakistanKhyberPakhtunkhwaHaripur,
      pakistanKhyberPakhtunkhwaHavelian,
      pakistanKhyberPakhtunkhwaKakadWariDirUpper,
      pakistanKhyberPakhtunkhwaKarak,
      pakistanKhyberPakhtunkhwaKhalabat,
      pakistanKhyberPakhtunkhwaKohat,
      pakistanKhyberPakhtunkhwaKulachi,
      pakistanKhyberPakhtunkhwaLachi,
      pakistanKhyberPakhtunkhwaLakki,
      pakistanKhyberPakhtunkhwaMansehra,
      pakistanKhyberPakhtunkhwaMardan,
      pakistanKhyberPakhtunkhwaMingora,
      pakistanKhyberPakhtunkhwaNoorabad,
      pakistanKhyberPakhtunkhwaNowshera,
      pakistanKhyberPakhtunkhwaNowsheraCantonment,
      pakistanKhyberPakhtunkhwaPabbi,
      pakistanKhyberPakhtunkhwaPaharpur,
      pakistanKhyberPakhtunkhwaPeshawar,
      pakistanKhyberPakhtunkhwaRisalpurCantonment,
      pakistanKhyberPakhtunkhwaSaraiNaurang,
      pakistanKhyberPakhtunkhwaShabqadar,
      pakistanKhyberPakhtunkhwaShingliBala,
      pakistanKhyberPakhtunkhwaShorkot,
      pakistanKhyberPakhtunkhwaSwabi,
      pakistanKhyberPakhtunkhwaTangi,
      pakistanKhyberPakhtunkhwaTank,
      pakistanKhyberPakhtunkhwaThal,
      pakistanKhyberPakhtunkhwaTopi,
      pakistanKhyberPakhtunkhwaUpperDir,
      pakistanKhyberPakhtunkhwaUtmanzai,
      pakistanKhyberPakhtunkhwaZaida
    ]);
const Region pakistanPunjab = Region(
    id: 3176,
    parentId: 167,
    longitude: 75.3412179,
    latitude: 31.1471305,
    name: "Punjab",
    type: null,
    stateCode: "PB",
    cities: [
      pakistanPunjabAhmadpurSial,
      pakistanPunjabAhmedpurEast,
      pakistanPunjabAlipurChatha,
      pakistanPunjabArifwala,
      pakistanPunjabAttockTehsil,
      pakistanPunjabBaddomalhi,
      pakistanPunjabBahawalnagar,
      pakistanPunjabBahawalpur,
      pakistanPunjabBakhriAhmadKhan,
      pakistanPunjabBasirpur,
      pakistanPunjabBastiDosa,
      pakistanPunjabBegowala,
      pakistanPunjabBhakkar,
      pakistanPunjabBhalwal,
      pakistanPunjabBhawana,
      pakistanPunjabBhera,
      pakistanPunjabBhopalwala,
      pakistanPunjabBurewala,
      pakistanPunjabChakAzamSaffo,
      pakistanPunjabChakJhumra,
      pakistanPunjabChakOneHundredTwentyNineLeft,
      pakistanPunjabChakThirtyHyponeHypElevenLeft,
      pakistanPunjabChakTwoHundredFortyHypNineTDA,
      pakistanPunjabChakwal,
      pakistanPunjabChawinda,
      pakistanPunjabChichawatni,
      pakistanPunjabChiniot,
      pakistanPunjabChishtian,
      pakistanPunjabChoaSaidanshah,
      pakistanPunjabChuharKana,
      pakistanPunjabChunian,
      pakistanPunjabDairaDinPanah,
      pakistanPunjabDajal,
      pakistanPunjabDandotRS,
      pakistanPunjabDaryaKhan,
      pakistanPunjabDaska,
      pakistanPunjabDaudKhel,
      pakistanPunjabDaultala,
      pakistanPunjabDeraGhaziKhan,
      pakistanPunjabDhanot,
      pakistanPunjabDhaunkal,
      pakistanPunjabDhokAwan,
      pakistanPunjabDijkot,
      pakistanPunjabDinanBashnoianWala,
      pakistanPunjabDinga,
      pakistanPunjabDipalpur,
      pakistanPunjabDullewala,
      pakistanPunjabDungaBunga,
      pakistanPunjabDunyapur,
      pakistanPunjabEminabad,
      pakistanPunjabFaisalabad,
      pakistanPunjabFaqirwali,
      pakistanPunjabFaruka,
      pakistanPunjabFazilpur,
      pakistanPunjabFerozewala,
      pakistanPunjabFortAbbas,
      pakistanPunjabGarhMaharaja,
      pakistanPunjabGojra,
      pakistanPunjabGujarKhan,
      pakistanPunjabGujranwala,
      pakistanPunjabGujranwalaDivision,
      pakistanPunjabGujrat,
      pakistanPunjabHadali,
      pakistanPunjabHafizabad,
      pakistanPunjabHarnoli,
      pakistanPunjabHarunabad,
      pakistanPunjabHasanAbdal,
      pakistanPunjabHasilpur,
      pakistanPunjabHaveliLakha,
      pakistanPunjabHazro,
      pakistanPunjabHujraShahMuqeem,
      pakistanPunjabJahanianShah,
      pakistanPunjabJalalpurJattan,
      pakistanPunjabJalalpurPirwala,
      pakistanPunjabJampur,
      pakistanPunjabJand,
      pakistanPunjabJandialaSherKhan,
      pakistanPunjabJaranwala,
      pakistanPunjabJatoiShimali,
      pakistanPunjabJauharabad,
      pakistanPunjabJhang,
      pakistanPunjabJhangSadar,
      pakistanPunjabJhawarian,
      pakistanPunjabJhelum,
      pakistanPunjabKabirwala,
      pakistanPunjabKahnaNau,
      pakistanPunjabKahuta,
      pakistanPunjabKalabagh,
      pakistanPunjabKalaswala,
      pakistanPunjabKalekeMandi,
      pakistanPunjabKallarKahar,
      pakistanPunjabKalurKot,
      pakistanPunjabKamalia,
      pakistanPunjabKamarMushani,
      pakistanPunjabKamoke,
      pakistanPunjabKamra,
      pakistanPunjabKanganpur,
      pakistanPunjabKaror,
      pakistanPunjabKasur,
      pakistanPunjabKeshupur,
      pakistanPunjabKhairpurTamiwali,
      pakistanPunjabKhandowa,
      pakistanPunjabKhanewal,
      pakistanPunjabKhangaDogran,
      pakistanPunjabKhangarh,
      pakistanPunjabKhanpur,
      pakistanPunjabKharian,
      pakistanPunjabKhewra,
      pakistanPunjabKhurrianwala,
      pakistanPunjabKhushab,
      pakistanPunjabKohrorPakka,
      pakistanPunjabKotAdduTehsil,
      pakistanPunjabKotGhulamMuhammad,
      pakistanPunjabKotMumin,
      pakistanPunjabKotRadhaKishan,
      pakistanPunjabKotRajkour,
      pakistanPunjabKotSamaba,
      pakistanPunjabKotSultan,
      pakistanPunjabKotliLoharan,
      pakistanPunjabKundian,
      pakistanPunjabKunjah,
      pakistanPunjabLadhewalaWaraich,
      pakistanPunjabLahore,
      pakistanPunjabLalaMusa,
      pakistanPunjabLalian,
      pakistanPunjabLayyah,
      pakistanPunjabLayyahDistrict,
      pakistanPunjabLiliani,
      pakistanPunjabLodhran,
      pakistanPunjabMailsi,
      pakistanPunjabMalakwal,
      pakistanPunjabMalakwalCity,
      pakistanPunjabMamuKanjan,
      pakistanPunjabMananwala,
      pakistanPunjabMandiBahauddin,
      pakistanPunjabMandiBahauddinDistrict,
      pakistanPunjabMangla,
      pakistanPunjabMankera,
      pakistanPunjabMehmandChak,
      pakistanPunjabMianChannun,
      pakistanPunjabMiankeMor,
      pakistanPunjabMianwali,
      pakistanPunjabMinchinabad,
      pakistanPunjabMithaTiwana,
      pakistanPunjabMozaShahwala,
      pakistanPunjabMultan,
      pakistanPunjabMultanDistrict,
      pakistanPunjabMuridke,
      pakistanPunjabMurree,
      pakistanPunjabMustafabad,
      pakistanPunjabMuzaffargarh,
      pakistanPunjabNankanaSahib,
      pakistanPunjabNarangMandi,
      pakistanPunjabNarowal,
      pakistanPunjabNaushahraVirkan,
      pakistanPunjabNazirTown,
      pakistanPunjabOkara,
      pakistanPunjabPakkiShagwanwali,
      pakistanPunjabPakpattan,
      pakistanPunjabPasrur,
      pakistanPunjabPattoki,
      pakistanPunjabPhalia,
      pakistanPunjabPindDadanKhan,
      pakistanPunjabPindiBhattian,
      pakistanPunjabPindiGheb,
      pakistanPunjabPirMahal,
      pakistanPunjabQadirpurRan,
      pakistanPunjabQilaDidarSingh,
      pakistanPunjabRabwah,
      pakistanPunjabRahimYarKhan,
      pakistanPunjabRahimyarKhanDistrict,
      pakistanPunjabRaiwind,
      pakistanPunjabRajaJang,
      pakistanPunjabRajanpur,
      pakistanPunjabRasulnagar,
      pakistanPunjabRawalpindi,
      pakistanPunjabRawalpindiDistrict,
      pakistanPunjabRenalaKhurd,
      pakistanPunjabRojhan,
      pakistanPunjabSadiqabad,
      pakistanPunjabSahiwal,
      pakistanPunjabSambrial,
      pakistanPunjabSanglaHill,
      pakistanPunjabSanjwal,
      pakistanPunjabSaraiAlamgir,
      pakistanPunjabSaraiSidhu,
      pakistanPunjabSargodha,
      pakistanPunjabShahkotTehsil,
      pakistanPunjabShahpur,
      pakistanPunjabShahrSultan,
      pakistanPunjabShakargarh,
      pakistanPunjabSharqpur,
      pakistanPunjabSheikhupura,
      pakistanPunjabShorkot,
      pakistanPunjabShujaabad,
      pakistanPunjabSialkot,
      pakistanPunjabSillanwali,
      pakistanPunjabSodhra,
      pakistanPunjabSukhekeMandi,
      pakistanPunjabSurkhpur,
      pakistanPunjabTalagang,
      pakistanPunjabTalamba,
      pakistanPunjabTandlianwala,
      pakistanPunjabTaunsa,
      pakistanPunjabTobaTekSingh,
      pakistanPunjabUmerkot,
      pakistanPunjabVihari,
      pakistanPunjabWah,
      pakistanPunjabWarburton,
      pakistanPunjabWazirabad,
      pakistanPunjabWestPunjab,
      pakistanPunjabYazman,
      pakistanPunjabZafarwal,
      pakistanPunjabZahirPir
    ]);
const Region pakistanSindh = Region(
    id: 3175,
    parentId: 167,
    longitude: 68.5247149,
    latitude: 25.8943018,
    name: "Sindh",
    type: null,
    stateCode: "SD",
    cities: [
      pakistanSindhAdilpur,
      pakistanSindhBadin,
      pakistanSindhBagarji,
      pakistanSindhBandhi,
      pakistanSindhBerani,
      pakistanSindhBhan,
      pakistanSindhBhiria,
      pakistanSindhBhitShah,
      pakistanSindhBozdarWada,
      pakistanSindhBulri,
      pakistanSindhChak,
      pakistanSindhChamber,
      pakistanSindhChhor,
      pakistanSindhChuharJamali,
      pakistanSindhDadu,
      pakistanSindhDaromehar,
      pakistanSindhDaryaKhanMarri,
      pakistanSindhDaulatpur,
      pakistanSindhDaur,
      pakistanSindhDhoroNaro,
      pakistanSindhDigri,
      pakistanSindhDiplo,
      pakistanSindhDokri,
      pakistanSindhGambat,
      pakistanSindhGarhiyasin,
      pakistanSindhGharo,
      pakistanSindhGhauspur,
      pakistanSindhGhotki,
      pakistanSindhGothGarelo,
      pakistanSindhGothPhulji,
      pakistanSindhGothRadhan,
      pakistanSindhHala,
      pakistanSindhHingorja,
      pakistanSindhHyderabad,
      pakistanSindhIslamkot,
      pakistanSindhJacobabad,
      pakistanSindhJamSahib,
      pakistanSindhJamshoro,
      pakistanSindhJati,
      pakistanSindhJhol,
      pakistanSindhJohi,
      pakistanSindhKadhan,
      pakistanSindhKambar,
      pakistanSindhKandhkot,
      pakistanSindhKandiari,
      pakistanSindhKandiaro,
      pakistanSindhKarachi,
      pakistanSindhKaraundi,
      pakistanSindhKarioGhanwar,
      pakistanSindhKashmor,
      pakistanSindhKetiBandar,
      pakistanSindhKhadro,
      pakistanSindhKhairpur,
      pakistanSindhKhairpurMirs,
      pakistanSindhKhairpurNathanShah,
      pakistanSindhKhanpurMahar,
      pakistanSindhKotDiji,
      pakistanSindhKotri,
      pakistanSindhKunri,
      pakistanSindhLakhi,
      pakistanSindhLarkana,
      pakistanSindhMadeji,
      pakistanSindhMalirCantonment,
      pakistanSindhMatiari,
      pakistanSindhMatli,
      pakistanSindhMehar,
      pakistanSindhMiroKhan,
      pakistanSindhMirpurBhtoro,
      pakistanSindhMirpurKhas,
      pakistanSindhMirpurMathelo,
      pakistanSindhMirpurSakro,
      pakistanSindhMirwahGorchani,
      pakistanSindhMithi,
      pakistanSindhMoro,
      pakistanSindhNabisar,
      pakistanSindhNasirabad,
      pakistanSindhNaudero,
      pakistanSindhNaukot,
      pakistanSindhNaushahroFiroz,
      pakistanSindhNawabshah,
      pakistanSindhNewBadah,
      pakistanSindhPadIdan,
      pakistanSindhPanoAqil,
      pakistanSindhPirJoGoth,
      pakistanSindhPithoro,
      pakistanSindhRajoKhanani,
      pakistanSindhRanipur,
      pakistanSindhRatodero,
      pakistanSindhRohri,
      pakistanSindhRustam,
      pakistanSindhSakrand,
      pakistanSindhSamaro,
      pakistanSindhSanghar,
      pakistanSindhSann,
      pakistanSindhSehwan,
      pakistanSindhSetharjaOld,
      pakistanSindhShahdadKot,
      pakistanSindhShahdadpur,
      pakistanSindhShahpurChakar,
      pakistanSindhShikarpur,
      pakistanSindhSinjhoro,
      pakistanSindhSitaRoad,
      pakistanSindhSobhodero,
      pakistanSindhSukkur,
      pakistanSindhTalhar,
      pakistanSindhTandoAdam,
      pakistanSindhTandoAllahyar,
      pakistanSindhTandoBago,
      pakistanSindhTandoJam,
      pakistanSindhTandoMithaKhan,
      pakistanSindhTandoMuhammadKhan,
      pakistanSindhTangwani,
      pakistanSindhTharuShah,
      pakistanSindhThatta,
      pakistanSindhThul,
      pakistanSindhUbauro,
      pakistanSindhUmarkot,
      pakistanSindhUmerkotDistrict,
      pakistanSindhWarah
    ]);

const pakistanStates = <int, Region>{
  3172: pakistanAzadKashmir,
  3174: pakistanBalochistan,
  3173: pakistanFederallyAdministeredTribalAreas,
  3170: pakistanGilgitHypBaltistan,
  3169: pakistanIslamabadCapitalTerritory,
  3171: pakistanKhyberPakhtunkhwa,
  3176: pakistanPunjab,
  3175: pakistanSindh
};
