/// Access to known geographies in Panama and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'panama_cities.dart';

/// The 13 regions of `🇵🇦 Panama`
const Region panamaBocasDdelToroProvince = Region(
    id: 1393,
    parentId: 170,
    longitude: -82.5207787,
    latitude: 9.4165521,
    name: "Bocas del Toro Province",
    type: null,
    stateCode: "1",
    cities: [
      panamaBocasDdelToroProvinceAlmirante,
      panamaBocasDdelToroProvinceBarranco,
      panamaBocasDdelToroProvinceBarrancoAdentro,
      panamaBocasDdelToroProvinceBastimentos,
      panamaBocasDdelToroProvinceBocasDdelToro,
      panamaBocasDdelToroProvinceCauchero,
      panamaBocasDdelToroProvinceChanguinola,
      panamaBocasDdelToroProvinceChiriquiGrande,
      panamaBocasDdelToroProvinceDistritoChiriquiGrande,
      panamaBocasDdelToroProvinceDistritoDdeBocasDdelToro,
      panamaBocasDdelToroProvinceDistritoDdeChanguinola,
      panamaBocasDdelToroProvinceElEmpalme,
      panamaBocasDdelToroProvinceElSilencio,
      panamaBocasDdelToroProvinceGuabito,
      panamaBocasDdelToroProvinceIslaBastimentos,
      panamaBocasDdelToroProvinceLaMesa,
      panamaBocasDdelToroProvinceMiramar,
      panamaBocasDdelToroProvincePuntaLaurel,
      panamaBocasDdelToroProvincePuntaPena,
      panamaBocasDdelToroProvincePuntaRobalo,
      panamaBocasDdelToroProvinceValleDdelRisco
    ]);
const Region panamaChiriquiProvince = Region(
    id: 1397,
    parentId: 170,
    longitude: -82.3885783,
    latitude: 8.584898,
    name: "Chiriquí Province",
    type: null,
    stateCode: "4",
    cities: [
      panamaChiriquiProvinceAlanje,
      panamaChiriquiProvinceAlgarrobosArriba,
      panamaChiriquiProvinceAltoBoquete,
      panamaChiriquiProvinceAserrioDdeGariche,
      panamaChiriquiProvinceBagala,
      panamaChiriquiProvinceBajoBoquete,
      panamaChiriquiProvinceBarrioGuadalupe,
      panamaChiriquiProvinceBijagual,
      panamaChiriquiProvinceBocaChica,
      panamaChiriquiProvinceBocaDdelMonte,
      panamaChiriquiProvinceBoqueron,
      panamaChiriquiProvinceBoquete,
      panamaChiriquiProvinceBrenon,
      panamaChiriquiProvinceBugaba,
      panamaChiriquiProvinceBugabitaArriba,
      panamaChiriquiProvinceCaimito,
      panamaChiriquiProvinceCaldera,
      panamaChiriquiProvinceCanasGordas,
      panamaChiriquiProvinceCelmira,
      panamaChiriquiProvinceCerroPunta,
      panamaChiriquiProvinceCerroViejo,
      panamaChiriquiProvinceChiriqui,
      panamaChiriquiProvinceCocheaAbajo,
      panamaChiriquiProvinceCordillera,
      panamaChiriquiProvinceDavid,
      panamaChiriquiProvinceDistritoDdeAlanje,
      panamaChiriquiProvinceDistritoDdeBaru,
      panamaChiriquiProvinceDistritoDdeBoqueron,
      panamaChiriquiProvinceDistritoDdeBoquete,
      panamaChiriquiProvinceDistritoDdeBugaba,
      panamaChiriquiProvinceDistritoDdeDavid,
      panamaChiriquiProvinceDistritoDdeDolega,
      panamaChiriquiProvinceDistritoDdeGualaca,
      panamaChiriquiProvinceDistritoDdeRemedios,
      panamaChiriquiProvinceDistritoDdeRenacimiento,
      panamaChiriquiProvinceDistritoDdeSanFelix,
      panamaChiriquiProvinceDistritoDdeSanLorenzo,
      panamaChiriquiProvinceDistritoDdeTole,
      panamaChiriquiProvinceDivala,
      panamaChiriquiProvinceDolegaDistrict,
      panamaChiriquiProvinceElNancito,
      panamaChiriquiProvinceElPalmar,
      panamaChiriquiProvinceElPorvenir,
      panamaChiriquiProvinceElTejar,
      panamaChiriquiProvinceFincaBlanco,
      panamaChiriquiProvinceGomez,
      panamaChiriquiProvinceGuabal,
      panamaChiriquiProvinceGuacaArriba,
      panamaChiriquiProvinceGualaca,
      panamaChiriquiProvinceGuarumal,
      panamaChiriquiProvinceGuayabal,
      panamaChiriquiProvinceHorconcitos,
      panamaChiriquiProvinceLaConcepcion,
      panamaChiriquiProvinceLaEsperanza,
      panamaChiriquiProvinceLaEstrella,
      panamaChiriquiProvinceLajasAdentro,
      panamaChiriquiProvinceLajasDdeTole,
      panamaChiriquiProvinceLasLajas,
      panamaChiriquiProvinceLasLomas,
      panamaChiriquiProvinceLimones,
      panamaChiriquiProvinceLosAlgarrobos,
      panamaChiriquiProvinceLosAnastacios,
      panamaChiriquiProvinceLosAngeles,
      panamaChiriquiProvinceLosNaranjos,
      panamaChiriquiProvinceManacaCivil,
      panamaChiriquiProvinceManacaNorte,
      panamaChiriquiProvinceMataDdelNance,
      panamaChiriquiProvinceMonteLirio,
      panamaChiriquiProvinceNuevoSanCarlitos,
      panamaChiriquiProvincePajaDdeSombrero,
      panamaChiriquiProvincePalmira,
      panamaChiriquiProvincePalmiraCentro,
      panamaChiriquiProvinceParaiso,
      panamaChiriquiProvincePasoCanoasArriba,
      panamaChiriquiProvincePedregal,
      panamaChiriquiProvincePlazaDdeCaisan,
      panamaChiriquiProvincePotrerillosAbajo,
      panamaChiriquiProvincePotrerillosArriba,
      panamaChiriquiProvinceProgreso,
      panamaChiriquiProvincePuebloViejo,
      panamaChiriquiProvincePuertoArmuelles,
      panamaChiriquiProvincePuntaDdeBurica,
      panamaChiriquiProvinceQuebradaDdePiedra,
      panamaChiriquiProvinceQuerevalo,
      panamaChiriquiProvinceQuinteno,
      panamaChiriquiProvinceRemedios,
      panamaChiriquiProvinceRincon,
      panamaChiriquiProvinceRioSereno,
      panamaChiriquiProvinceRoviraArriba,
      panamaChiriquiProvinceSanAndres,
      panamaChiriquiProvinceSanCarlos,
      panamaChiriquiProvinceSanFelix,
      panamaChiriquiProvinceSanIsidro,
      panamaChiriquiProvinceSanLorenzo,
      panamaChiriquiProvinceSanPabloNuevoAbajo,
      panamaChiriquiProvinceSanPabloViejoAbajo,
      panamaChiriquiProvinceSantaClara,
      panamaChiriquiProvinceSantaCruz,
      panamaChiriquiProvinceSantaMarta,
      panamaChiriquiProvinceSantaRosa,
      panamaChiriquiProvinceSantoDomingo,
      panamaChiriquiProvinceSantoTomas,
      panamaChiriquiProvinceSioguiAbajo,
      panamaChiriquiProvinceSioguiArriba,
      panamaChiriquiProvinceSortova,
      panamaChiriquiProvinceTijeras,
      panamaChiriquiProvinceTinajas,
      panamaChiriquiProvinceTole,
      panamaChiriquiProvinceVeladero,
      panamaChiriquiProvinceVolcan
    ]);
const Region panamaCocleProvince = Region(
    id: 1387,
    parentId: 170,
    longitude: -80.365865,
    latitude: 8.6266068,
    name: "Coclé Province",
    type: null,
    stateCode: "2",
    cities: [
      panamaCocleProvinceAguadulce,
      panamaCocleProvinceAguasBlancas,
      panamaCocleProvinceAltoDdeLaEstancia,
      panamaCocleProvinceAnton,
      panamaCocleProvinceBarrancoColorado,
      panamaCocleProvinceCaballero,
      panamaCocleProvinceCabuya,
      panamaCocleProvinceCaimito,
      panamaCocleProvinceCanaveral,
      panamaCocleProvinceCapellania,
      panamaCocleProvinceChigore,
      panamaCocleProvinceChiguiriArriba,
      panamaCocleProvinceChuruquitaChiquita,
      panamaCocleProvinceChuruquitaGrande,
      panamaCocleProvinceCocle,
      panamaCocleProvinceDistritoDdeAguadulce,
      panamaCocleProvinceDistritoDdeAnton,
      panamaCocleProvinceDistritoDdeLaPintada,
      panamaCocleProvinceDistritoDdeNata,
      panamaCocleProvinceDistritoDdeOla,
      panamaCocleProvinceDistritoPenonome,
      panamaCocleProvinceElCano,
      panamaCocleProvinceElChiru,
      panamaCocleProvinceElCoco,
      panamaCocleProvinceElCope,
      panamaCocleProvinceElCortezo,
      panamaCocleProvinceElCristo,
      panamaCocleProvinceElPotrero,
      panamaCocleProvinceElRetiro,
      panamaCocleProvinceElRoble,
      panamaCocleProvinceEntradero,
      panamaCocleProvinceFarallon,
      panamaCocleProvinceGuzman,
      panamaCocleProvinceJuanDiaz,
      panamaCocleProvinceLaLoma,
      panamaCocleProvinceLaPintada,
      panamaCocleProvinceLasHuacasDdelQuije,
      panamaCocleProvinceLasMarias,
      panamaCocleProvinceLasMinas,
      panamaCocleProvinceLasSabanas,
      panamaCocleProvinceLlanoGrande,
      panamaCocleProvinceLlanoMarin,
      panamaCocleProvinceLosPollos,
      panamaCocleProvinceNata,
      panamaCocleProvinceNuestroAmo,
      panamaCocleProvinceOla,
      panamaCocleProvincePenonome,
      panamaCocleProvincePiedrasGordas,
      panamaCocleProvincePocri,
      panamaCocleProvinceRioGrande,
      panamaCocleProvinceRioHato,
      panamaCocleProvinceSanJuanDdeDios,
      panamaCocleProvinceToabre,
      panamaCocleProvinceToza,
      panamaCocleProvinceVistaHermosa
    ]);
const Region panamaColonProvince = Region(
    id: 1386,
    parentId: 170,
    longitude: -80.0534923,
    latitude: 9.1851989,
    name: "Colón Province",
    type: null,
    stateCode: "3",
    cities: [
      panamaColonProvinceBuenaVista,
      panamaColonProvinceCativa,
      panamaColonProvinceCocleDdelNorte,
      panamaColonProvinceColon,
      panamaColonProvinceCristobal,
      panamaColonProvinceDistritoDdeChagres,
      panamaColonProvinceDistritoDdeColon,
      panamaColonProvinceDistritoDdeDonoso,
      panamaColonProvinceDistritoDdePortobelo,
      panamaColonProvinceDistritoDdeSantaIsabel,
      panamaColonProvinceElGiral,
      panamaColonProvinceElGuabo,
      panamaColonProvinceElValleDdeLlaUnion,
      panamaColonProvinceEscobal,
      panamaColonProvinceGatun,
      panamaColonProvinceGatuncillo,
      panamaColonProvinceLasMargaritas,
      panamaColonProvinceMariaChiquita,
      panamaColonProvinceMiramar,
      panamaColonProvinceNombreDdeDios,
      panamaColonProvinceNuevoChagres,
      panamaColonProvinceNuevoSanJuan,
      panamaColonProvinceNuevoVigia,
      panamaColonProvincePalenque,
      panamaColonProvincePalmasBellas,
      panamaColonProvincePalmira,
      panamaColonProvincePlayaChiquita,
      panamaColonProvincePortobelo,
      panamaColonProvincePuertoEscondido,
      panamaColonProvincePuertoPilon,
      panamaColonProvinceQuebradaBonitaAdentro,
      panamaColonProvinceRioAlejandro,
      panamaColonProvinceRioDuque,
      panamaColonProvinceRioRita,
      panamaColonProvinceSabanitas,
      panamaColonProvinceSantaIsabel,
      panamaColonProvinceSantaRitaArriba,
      panamaColonProvinceVientoFrio
    ]);
const Region panamaDarienProvince = Region(
    id: 1385,
    parentId: 170,
    longitude: -77.8367282,
    latitude: 7.8681713,
    name: "Darién Province",
    type: null,
    stateCode: "5",
    cities: [
      panamaDarienProvinceBocaDdeCupe,
      panamaDarienProvinceCamoganti,
      panamaDarienProvinceCucunati,
      panamaDarienProvinceDistritoDdeChepigana,
      panamaDarienProvinceDistritoDdePinogana,
      panamaDarienProvinceGarachine,
      panamaDarienProvinceJaque,
      panamaDarienProvinceLaPalma,
      panamaDarienProvinceMeteti,
      panamaDarienProvinceMorti,
      panamaDarienProvincePucuro,
      panamaDarienProvinceSantaFe,
      panamaDarienProvinceYaviza
    ]);
const Region panamaEmberaHypWounaanComarca = Region(
    id: 1396,
    parentId: 170,
    longitude: -77.6536125,
    latitude: 8.3766983,
    name: "Emberá-Wounaan Comarca",
    type: null,
    stateCode: "EM",
    cities: [
      panamaEmberaHypWounaanComarcaBayamon,
      panamaEmberaHypWounaanComarcaCemaco,
      panamaEmberaHypWounaanComarcaCorozal,
      panamaEmberaHypWounaanComarcaSambu,
      panamaEmberaHypWounaanComarcaUnionChoco,
      panamaEmberaHypWounaanComarcaYape
    ]);
const Region panamaGunaYala = Region(
    id: 1388,
    parentId: 170,
    longitude: -78.192625,
    latitude: 9.2344395,
    name: "Guna Yala",
    type: null,
    stateCode: "KY",
    cities: [
      panamaGunaYalaAchutupo,
      panamaGunaYalaAiligandi,
      panamaGunaYalaCartiSugdup,
      panamaGunaYalaElPorvenir,
      panamaGunaYalaMulatupo,
      panamaGunaYalaNargana,
      panamaGunaYalaPlayonChico,
      panamaGunaYalaPuertoObaldia,
      panamaGunaYalaSanIgnacioDdeTupile,
      panamaGunaYalaTubuala,
      panamaGunaYalaUstupo
    ]);
const Region panamaHerreraProvince = Region(
    id: 1389,
    parentId: 170,
    longitude: -80.7214417,
    latitude: 7.7704282,
    name: "Herrera Province",
    type: null,
    stateCode: "6",
    cities: [
      panamaHerreraProvinceBocaDdeParita,
      panamaHerreraProvinceCabuya,
      panamaHerreraProvinceCerroLargo,
      panamaHerreraProvinceChitre,
      panamaHerreraProvinceChumical,
      panamaHerreraProvinceChupampa,
      panamaHerreraProvinceDistritoDdeChitre,
      panamaHerreraProvinceDistritoDdeLasMinas,
      panamaHerreraProvinceDistritoDdeLosPozos,
      panamaHerreraProvinceDistritoDdeOcu,
      panamaHerreraProvinceDistritoDdeParita,
      panamaHerreraProvinceDistritoDdePese,
      panamaHerreraProvinceDistritoDdeSantaMaria,
      panamaHerreraProvinceElCalabacito,
      panamaHerreraProvinceElCapuri,
      panamaHerreraProvinceElCedro,
      panamaHerreraProvinceElPedregoso,
      panamaHerreraProvinceElRincon,
      panamaHerreraProvinceElToro,
      panamaHerreraProvinceLaArena,
      panamaHerreraProvinceLaTrinidad,
      panamaHerreraProvinceLasGuabas,
      panamaHerreraProvinceLasMinas,
      panamaHerreraProvinceLeonesArriba,
      panamaHerreraProvinceLimonDdeTijeras,
      panamaHerreraProvinceLlanoBonito,
      panamaHerreraProvinceLlanoDdeLaCruz,
      panamaHerreraProvinceLlanoGrande,
      panamaHerreraProvinceLosCanelos,
      panamaHerreraProvinceLosCastillos,
      panamaHerreraProvinceLosCerritos,
      panamaHerreraProvinceLosCerrosDdePaja,
      panamaHerreraProvinceLosPozos,
      panamaHerreraProvinceMonagrillo,
      panamaHerreraProvinceOcu,
      panamaHerreraProvinceParis,
      panamaHerreraProvinceParita,
      panamaHerreraProvincePenasChatas,
      panamaHerreraProvincePese,
      panamaHerreraProvincePitalozaArriba,
      panamaHerreraProvincePortobelillo,
      panamaHerreraProvincePotuga,
      panamaHerreraProvinceQuebradaDdelRosario,
      panamaHerreraProvinceRinconHondo,
      panamaHerreraProvinceSabanaGrande,
      panamaHerreraProvinceSanJuanBautista,
      panamaHerreraProvinceSantaMaria
    ]);
const Region panamaLosSantosProvince = Region(
    id: 1390,
    parentId: 170,
    longitude: -80.365865,
    latitude: 7.5909302,
    name: "Los Santos Province",
    type: null,
    stateCode: "7",
    cities: [
      panamaLosSantosProvinceAguaBuena,
      panamaLosSantosProvinceAveMaria,
      panamaLosSantosProvinceBahiaHonda,
      panamaLosSantosProvinceBajoCorral,
      panamaLosSantosProvinceBayano,
      panamaLosSantosProvinceBellaVista,
      panamaLosSantosProvinceCambutal,
      panamaLosSantosProvinceCanas,
      panamaLosSantosProvinceCedroArriba,
      panamaLosSantosProvinceDistritoDdeGuarare,
      panamaLosSantosProvinceDistritoDdeLasTablas,
      panamaLosSantosProvinceDistritoDdeLosSantos,
      panamaLosSantosProvinceDistritoDdeMacaracas,
      panamaLosSantosProvinceDistritoDdePedasi,
      panamaLosSantosProvinceDistritoDdePocri,
      panamaLosSantosProvinceDistritoDdeTonosi,
      panamaLosSantosProvinceElCacao,
      panamaLosSantosProvinceElCanafistulo,
      panamaLosSantosProvinceElCarate,
      panamaLosSantosProvinceElCocal,
      panamaLosSantosProvinceElCortezo,
      panamaLosSantosProvinceElEjido,
      panamaLosSantosProvinceElGuasimo,
      panamaLosSantosProvinceElHato,
      panamaLosSantosProvinceElMacano,
      panamaLosSantosProvinceElManantial,
      panamaLosSantosProvinceElMunoz,
      panamaLosSantosProvinceElPedregoso,
      panamaLosSantosProvinceFlores,
      panamaLosSantosProvinceGuarare,
      panamaLosSantosProvinceGuarareArriba,
      panamaLosSantosProvinceLaColorada,
      panamaLosSantosProvinceLaEnea,
      panamaLosSantosProvinceLaEspigadilla,
      panamaLosSantosProvinceLaLaja,
      panamaLosSantosProvinceLaMesa,
      panamaLosSantosProvinceLaMiel,
      panamaLosSantosProvinceLaPalma,
      panamaLosSantosProvinceLaPasera,
      panamaLosSantosProvinceLaTiza,
      panamaLosSantosProvinceLaTronosa,
      panamaLosSantosProvinceLajamina,
      panamaLosSantosProvinceLasCruces,
      panamaLosSantosProvinceLasGuabas,
      panamaLosSantosProvinceLasPalmas,
      panamaLosSantosProvinceLasPalmitas,
      panamaLosSantosProvinceLasTablas,
      panamaLosSantosProvinceLasTrancas,
      panamaLosSantosProvinceLlanoAbajo,
      panamaLosSantosProvinceLlanoDdePiedra,
      panamaLosSantosProvinceLlanoLargo,
      panamaLosSantosProvinceLosAngeles,
      panamaLosSantosProvinceLosAsientos,
      panamaLosSantosProvinceLosOlivos,
      panamaLosSantosProvinceLosSantos,
      panamaLosSantosProvinceMacaracas,
      panamaLosSantosProvinceMogollon,
      panamaLosSantosProvinceNuario,
      panamaLosSantosProvinceOriaArriba,
      panamaLosSantosProvincePalmira,
      panamaLosSantosProvinceParaiso,
      panamaLosSantosProvinceParitilla,
      panamaLosSantosProvincePedasi,
      panamaLosSantosProvincePenaBlanca,
      panamaLosSantosProvincePerales,
      panamaLosSantosProvincePocri,
      panamaLosSantosProvinceRioHondo,
      panamaLosSantosProvinceSabanaGrande,
      panamaLosSantosProvinceSanJose,
      panamaLosSantosProvinceSantaAnaArriba,
      panamaLosSantosProvinceSantoDomingo,
      panamaLosSantosProvinceSesteadero,
      panamaLosSantosProvinceTonosi,
      panamaLosSantosProvinceTresQuebradas,
      panamaLosSantosProvinceValleRico,
      panamaLosSantosProvinceVallerriquito,
      panamaLosSantosProvinceVillaLourdes
    ]);
const Region panamaNgobeHypBugleComarca = Region(
    id: 1391,
    parentId: 170,
    longitude: -81.7787021,
    latitude: 8.6595833,
    name: "Ngöbe-Buglé Comarca",
    type: null,
    stateCode: "NB",
    cities: [
      panamaNgobeHypBugleComarcaBahiaAzul,
      panamaNgobeHypBugleComarcaBesiko,
      panamaNgobeHypBugleComarcaBisira,
      panamaNgobeHypBugleComarcaBocaDdeBalsa,
      panamaNgobeHypBugleComarcaBuenosAires,
      panamaNgobeHypBugleComarcaCamaronArriba,
      panamaNgobeHypBugleComarcaCerroBanco,
      panamaNgobeHypBugleComarcaCerroCana,
      panamaNgobeHypBugleComarcaCerroPlata,
      panamaNgobeHypBugleComarcaChichica,
      panamaNgobeHypBugleComarcaGuayabito,
      panamaNgobeHypBugleComarcaHatoChami,
      panamaNgobeHypBugleComarcaHatoCorotu,
      panamaNgobeHypBugleComarcaKankintu,
      panamaNgobeHypBugleComarcaKusapin,
      panamaNgobeHypBugleComarcaLajeroArriba,
      panamaNgobeHypBugleComarcaLlanoNopo,
      panamaNgobeHypBugleComarcaLomaYuca,
      panamaNgobeHypBugleComarcaMirono,
      panamaNgobeHypBugleComarcaMuna,
      panamaNgobeHypBugleComarcaNoleDuima,
      panamaNgobeHypBugleComarcaNurun,
      panamaNgobeHypBugleComarcaOma,
      panamaNgobeHypBugleComarcaParedonArriba,
      panamaNgobeHypBugleComarcaPlanDdeChorcha,
      panamaNgobeHypBugleComarcaPuebloNuevo,
      panamaNgobeHypBugleComarcaQuebradaCanoa,
      panamaNgobeHypBugleComarcaQuebradaTula,
      panamaNgobeHypBugleComarcaSitioPrado,
      panamaNgobeHypBugleComarcaTobobe
    ]);
const Region panamaPanamaOesteProvince = Region(
    id: 1394,
    parentId: 170,
    longitude: -79.2902133,
    latitude: 9.1196751,
    name: "Panamá Oeste Province",
    type: null,
    stateCode: "10",
    cities: [
      panamaPanamaOesteProvinceAltoDdelEspino,
      panamaPanamaOesteProvinceAltosDdeSanFrancisco,
      panamaPanamaOesteProvinceArenosa,
      panamaPanamaOesteProvinceArosemena,
      panamaPanamaOesteProvinceArraijan,
      panamaPanamaOesteProvinceBejuco,
      panamaPanamaOesteProvinceBuenosAires,
      panamaPanamaOesteProvinceCabuya,
      panamaPanamaOesteProvinceCaimito,
      panamaPanamaOesteProvinceCapira,
      panamaPanamaOesteProvinceCermeno,
      panamaPanamaOesteProvinceCerroCama,
      panamaPanamaOesteProvinceChame,
      panamaPanamaOesteProvinceCiriDdeLosSotos,
      panamaPanamaOesteProvinceDistritoArraijan,
      panamaPanamaOesteProvinceDistritoDdeCapira,
      panamaPanamaOesteProvinceDistritoDdeChame,
      panamaPanamaOesteProvinceDistritoDdeLaChorrera,
      panamaPanamaOesteProvinceDistritoDdeSanCarlos,
      panamaPanamaOesteProvinceElCacao,
      panamaPanamaOesteProvinceElCoco,
      panamaPanamaOesteProvinceElEspave,
      panamaPanamaOesteProvinceElEspino,
      panamaPanamaOesteProvinceElHigo,
      panamaPanamaOesteProvinceElLibano,
      panamaPanamaOesteProvinceGuadalupe,
      panamaPanamaOesteProvinceGuayabito,
      panamaPanamaOesteProvinceHatoMontana,
      panamaPanamaOesteProvinceLaChorrera,
      panamaPanamaOesteProvinceLaErmita,
      panamaPanamaOesteProvinceLaHerradura,
      panamaPanamaOesteProvinceLaLaguna,
      panamaPanamaOesteProvinceLaMitra,
      panamaPanamaOesteProvinceLaPesa,
      panamaPanamaOesteProvinceLasColinas,
      panamaPanamaOesteProvinceLasLajas,
      panamaPanamaOesteProvinceLasUvas,
      panamaPanamaOesteProvinceLlanoLargo,
      panamaPanamaOesteProvinceLosLlanitos,
      panamaPanamaOesteProvinceMendoza,
      panamaPanamaOesteProvinceNuevaArenosa,
      panamaPanamaOesteProvinceNuevaGorgona,
      panamaPanamaOesteProvinceNuevoArraijan,
      panamaPanamaOesteProvinceNuevoEmperador,
      panamaPanamaOesteProvincePlayaLeona,
      panamaPanamaOesteProvincePotreroGrande,
      panamaPanamaOesteProvincePuertoCaimito,
      panamaPanamaOesteProvinceRioCongo,
      panamaPanamaOesteProvinceSanCarlos,
      panamaPanamaOesteProvinceSanJose,
      panamaPanamaOesteProvinceSanVicenteDdeBique,
      panamaPanamaOesteProvinceSantaClara,
      panamaPanamaOesteProvinceSantaRita,
      panamaPanamaOesteProvinceSora,
      panamaPanamaOesteProvinceVeracruz,
      panamaPanamaOesteProvinceVillaCarmen,
      panamaPanamaOesteProvinceVillaRosario,
      panamaPanamaOesteProvinceVistaAlegre
    ]);
const Region panamaPanamaProvince = Region(
    id: 1395,
    parentId: 170,
    longitude: -79.2902133,
    latitude: 9.1196751,
    name: "Panamá Province",
    type: null,
    stateCode: "8",
    cities: [
      panamaPanamaProvinceAlcaldeDiaz,
      panamaPanamaProvinceAncon,
      panamaPanamaProvinceBrujas,
      panamaPanamaProvinceCabraNumeroUno,
      panamaPanamaProvinceCaimitillo,
      panamaPanamaProvinceCalzadaLarga,
      panamaPanamaProvinceCanita,
      panamaPanamaProvinceCerroAzul,
      panamaPanamaProvinceChepillo,
      panamaPanamaProvinceChepo,
      panamaPanamaProvinceChilibre,
      panamaPanamaProvinceChiman,
      panamaPanamaProvinceContadora,
      panamaPanamaProvinceCurundu,
      panamaPanamaProvinceDistritoDdeBalboa,
      panamaPanamaProvinceDistritoDdeChepo,
      panamaPanamaProvinceDistritoDdeChiman,
      panamaPanamaProvinceDistritoDdePanama,
      panamaPanamaProvinceDistritoDdeTaboga,
      panamaPanamaProvinceElChorrillo,
      panamaPanamaProvinceElProgreso,
      panamaPanamaProvinceGonzalillo,
      panamaPanamaProvinceHoward,
      panamaPanamaProvinceJuanDiaz,
      panamaPanamaProvinceLaCabima,
      panamaPanamaProvinceLaColorada,
      panamaPanamaProvinceLaEnsenada,
      panamaPanamaProvinceLaEsmeralda,
      panamaPanamaProvinceLaGuinea,
      panamaPanamaProvinceLaMesa,
      panamaPanamaProvinceLasCumbres,
      panamaPanamaProvinceLasMargaritas,
      panamaPanamaProvinceLidice,
      panamaPanamaProvinceLosLotes,
      panamaPanamaProvinceNuevaEsperanza,
      panamaPanamaProvinceNuevoBelen,
      panamaPanamaProvincePacora,
      panamaPanamaProvincePanama,
      panamaPanamaProvinceParqueLefevre,
      panamaPanamaProvincePasiga,
      panamaPanamaProvincePedregal,
      panamaPanamaProvinceRioAbajo,
      panamaPanamaProvinceSanAntonio,
      panamaPanamaProvinceSanFelipe,
      panamaPanamaProvinceSanMiguel,
      panamaPanamaProvinceSanMiguelito,
      panamaPanamaProvinceSanVicente,
      panamaPanamaProvinceTocumen,
      panamaPanamaProvinceTorti,
      panamaPanamaProvinceUnionDdeAzuero,
      panamaPanamaProvinceUnionSantena,
      panamaPanamaProvinceVillaUnida,
      panamaPanamaProvinceVistaHermosa
    ]);
const Region panamaVeraguasProvince = Region(
    id: 1392,
    parentId: 170,
    longitude: -81.0754657,
    latitude: 8.1231033,
    name: "Veraguas Province",
    type: null,
    stateCode: "9",
    cities: [
      panamaVeraguasProvinceAltoDdeJesus,
      panamaVeraguasProvinceArenas,
      panamaVeraguasProvinceAtalaya,
      panamaVeraguasProvinceBarnizal,
      panamaVeraguasProvinceBisvalles,
      panamaVeraguasProvinceBoqueron,
      panamaVeraguasProvinceBoro,
      panamaVeraguasProvinceCalabacito,
      panamaVeraguasProvinceCalidonia,
      panamaVeraguasProvinceCalobre,
      panamaVeraguasProvinceCalovebora,
      panamaVeraguasProvinceCanazas,
      panamaVeraguasProvinceCantoDdelLlano,
      panamaVeraguasProvinceCorozal,
      panamaVeraguasProvinceDistritoDdeAtalaya,
      panamaVeraguasProvinceDistritoDdeCalobre,
      panamaVeraguasProvinceDistritoDdeCanazas,
      panamaVeraguasProvinceDistritoDdeLaMesa,
      panamaVeraguasProvinceDistritoDdeLasPalmas,
      panamaVeraguasProvinceDistritoDdeMontijo,
      panamaVeraguasProvinceDistritoDdeRioDdeJesus,
      panamaVeraguasProvinceDistritoDdeSanFrancisco,
      panamaVeraguasProvinceDistritoDdeSantaFe,
      panamaVeraguasProvinceDistritoDdeSantiago,
      panamaVeraguasProvinceDistritoDdeSona,
      panamaVeraguasProvinceElAlto,
      panamaVeraguasProvinceElBarrito,
      panamaVeraguasProvinceElCocla,
      panamaVeraguasProvinceElEspinoDdeSantaRosa,
      panamaVeraguasProvinceElMaranon,
      panamaVeraguasProvinceElMaria,
      panamaVeraguasProvinceElPajaro,
      panamaVeraguasProvinceElPantano,
      panamaVeraguasProvinceElPenon,
      panamaVeraguasProvinceElPicador,
      panamaVeraguasProvinceElPotrero,
      panamaVeraguasProvinceElRincon,
      panamaVeraguasProvinceElUvito,
      panamaVeraguasProvinceGuarumal,
      panamaVeraguasProvinceLaColorada,
      panamaVeraguasProvinceLaGarceana,
      panamaVeraguasProvinceLaLaguna,
      panamaVeraguasProvinceLaLoma,
      panamaVeraguasProvinceLaMesa,
      panamaVeraguasProvinceLaMontanuela,
      panamaVeraguasProvinceLaPena,
      panamaVeraguasProvinceLaRayaDdeCalobre,
      panamaVeraguasProvinceLaRayaDdeSantaMaria,
      panamaVeraguasProvinceLaYeguada,
      panamaVeraguasProvinceLasGuiasAbajo,
      panamaVeraguasProvinceLasHuacas,
      panamaVeraguasProvinceLasPalmas,
      panamaVeraguasProvinceLeonesArriba,
      panamaVeraguasProvinceLlanoGrande,
      panamaVeraguasProvinceLola,
      panamaVeraguasProvinceLosAlgarrobos,
      panamaVeraguasProvinceLosCastillos,
      panamaVeraguasProvinceLosHigos,
      panamaVeraguasProvinceMariatoDistrict,
      panamaVeraguasProvinceMonjaras,
      panamaVeraguasProvinceMontijo,
      panamaVeraguasProvincePiedrasGordas,
      panamaVeraguasProvincePonuga,
      panamaVeraguasProvincePuertoVidal,
      panamaVeraguasProvinceQuebradaDdeOro,
      panamaVeraguasProvinceRioDdeJesus,
      panamaVeraguasProvinceRioGrande,
      panamaVeraguasProvinceRodeoViejo,
      panamaVeraguasProvinceSanBartolo,
      panamaVeraguasProvinceSanFrancisco,
      panamaVeraguasProvinceSanJose,
      panamaVeraguasProvinceSanJuan,
      panamaVeraguasProvinceSanMarcelo,
      panamaVeraguasProvinceSanPedroDdelEspino,
      panamaVeraguasProvinceSantaFe,
      panamaVeraguasProvinceSantiagoDdeVeraguas,
      panamaVeraguasProvinceSona,
      panamaVeraguasProvinceTebario,
      panamaVeraguasProvinceUtira,
      panamaVeraguasProvinceVigui,
      panamaVeraguasProvinceZapotillo
    ]);

const panamaStates = <int, Region>{
  1393: panamaBocasDdelToroProvince,
  1397: panamaChiriquiProvince,
  1387: panamaCocleProvince,
  1386: panamaColonProvince,
  1385: panamaDarienProvince,
  1396: panamaEmberaHypWounaanComarca,
  1388: panamaGunaYala,
  1389: panamaHerreraProvince,
  1390: panamaLosSantosProvince,
  1391: panamaNgobeHypBugleComarca,
  1394: panamaPanamaOesteProvince,
  1395: panamaPanamaProvince,
  1392: panamaVeraguasProvince
};
