/// Access to known geographies in `Panama` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.
library;

import '../base.dart';
import 'panama_cities.dart';

/// The `Bocas del Toro Province` region in `Panama`
const Region panamaBocasDelToroProvince = Region(
  id: 1393,
  parentId: 170,
  longitude: -82.5207787,
  latitude: 9.4165521,
  name: "Bocas del Toro Province",
  type: null,
  stateCode: "1",
  cities: [
    bocasDelToroProvinceAlmiranteCity,
    bocasDelToroProvinceBarrancoCity,
    bocasDelToroProvinceBarrancoAdentroCity,
    bocasDelToroProvinceBastimentosCity,
    bocasDelToroProvinceBocasDelToroCity,
    bocasDelToroProvinceCaucheroCity,
    bocasDelToroProvinceChanguinolaCity,
    bocasDelToroProvinceChiriquiGrandeCity,
    bocasDelToroProvinceDistritoChiriquiGrandeCity,
    bocasDelToroProvinceDistritoDeBocasDelToroCity,
    bocasDelToroProvinceDistritoDeChanguinolaCity,
    bocasDelToroProvinceElEmpalmeCity,
    bocasDelToroProvinceElSilencioCity,
    bocasDelToroProvinceGuabitoCity,
    bocasDelToroProvinceIslaBastimentosCity,
    bocasDelToroProvinceLaMesaCity,
    bocasDelToroProvinceMiramarCity,
    bocasDelToroProvincePuntaLaurelCity,
    bocasDelToroProvincePuntaPenaCity,
    bocasDelToroProvincePuntaRobaloCity,
    bocasDelToroProvinceValleDelRiscoCity
  ]);

/// The `Chiriquí Province` region in `Panama`
const Region panamaChiriquiProvince = Region(
  id: 1397,
  parentId: 170,
  longitude: -82.3885783,
  latitude: 8.584898,
  name: "Chiriquí Province",
  type: null,
  stateCode: "4",
  cities: [
    chiriquiProvinceAlanjeCity,
    chiriquiProvinceAlgarrobosArribaCity,
    chiriquiProvinceAltoBoqueteCity,
    chiriquiProvinceAserrioDeGaricheCity,
    chiriquiProvinceBagalaCity,
    chiriquiProvinceBajoBoqueteCity,
    chiriquiProvinceBarrioGuadalupeCity,
    chiriquiProvinceBijagualCity,
    chiriquiProvinceBocaChicaCity,
    chiriquiProvinceBocaDelMonteCity,
    chiriquiProvinceBoqueronCity,
    chiriquiProvinceBoqueteCity,
    chiriquiProvinceBrenonCity,
    chiriquiProvinceBugabaCity,
    chiriquiProvinceBugabitaArribaCity,
    chiriquiProvinceCaimitoCity,
    chiriquiProvinceCalderaCity,
    chiriquiProvinceCanasGordasCity,
    chiriquiProvinceCelmiraCity,
    chiriquiProvinceCerroPuntaCity,
    chiriquiProvinceCerroViejoCity,
    chiriquiProvinceChiriquiCity,
    chiriquiProvinceCocheaAbajoCity,
    chiriquiProvinceCordilleraCity,
    chiriquiProvinceDavidCity,
    chiriquiProvinceDistritoDeAlanjeCity,
    chiriquiProvinceDistritoDeBaruCity,
    chiriquiProvinceDistritoDeBoqueronCity,
    chiriquiProvinceDistritoDeBoqueteCity,
    chiriquiProvinceDistritoDeBugabaCity,
    chiriquiProvinceDistritoDeDavidCity,
    chiriquiProvinceDistritoDeDolegaCity,
    chiriquiProvinceDistritoDeGualacaCity,
    chiriquiProvinceDistritoDeRemediosCity,
    chiriquiProvinceDistritoDeRenacimientoCity,
    chiriquiProvinceDistritoDeSanFelixCity,
    chiriquiProvinceDistritoDeSanLorenzoCity,
    chiriquiProvinceDistritoDeToleCity,
    chiriquiProvinceDivalaCity,
    chiriquiProvinceDolegaDistrictCity,
    chiriquiProvinceElNancitoCity,
    chiriquiProvinceElPalmarCity,
    chiriquiProvinceElPorvenirCity,
    chiriquiProvinceElTejarCity,
    chiriquiProvinceFincaBlancoCity,
    chiriquiProvinceGomezCity,
    chiriquiProvinceGuabalCity,
    chiriquiProvinceGuacaArribaCity,
    chiriquiProvinceGualacaCity,
    chiriquiProvinceGuarumalCity,
    chiriquiProvinceGuayabalCity,
    chiriquiProvinceHorconcitosCity,
    chiriquiProvinceLaConcepcionCity,
    chiriquiProvinceLaEsperanzaCity,
    chiriquiProvinceLaEstrellaCity,
    chiriquiProvinceLajasAdentroCity,
    chiriquiProvinceLajasDeToleCity,
    chiriquiProvinceLasLajasCity,
    chiriquiProvinceLasLomasCity,
    chiriquiProvinceLimonesCity,
    chiriquiProvinceLosAlgarrobosCity,
    chiriquiProvinceLosAnastaciosCity,
    chiriquiProvinceLosAngelesCity,
    chiriquiProvinceLosNaranjosCity,
    chiriquiProvinceManacaCivilCity,
    chiriquiProvinceManacaNorteCity,
    chiriquiProvinceMataDelNanceCity,
    chiriquiProvinceMonteLirioCity,
    chiriquiProvinceNuevoSanCarlitosCity,
    chiriquiProvincePajaDeSombreroCity,
    chiriquiProvincePalmiraCity,
    chiriquiProvincePalmiraCentroCity,
    chiriquiProvinceParaisoCity,
    chiriquiProvincePasoCanoasArribaCity,
    chiriquiProvincePedregalCity,
    chiriquiProvincePlazaDeCaisanCity,
    chiriquiProvincePotrerillosAbajoCity,
    chiriquiProvincePotrerillosArribaCity,
    chiriquiProvinceProgresoCity,
    chiriquiProvincePuebloViejoCity,
    chiriquiProvincePuertoArmuellesCity,
    chiriquiProvincePuntaDeBuricaCity,
    chiriquiProvinceQuebradaDePiedraCity,
    chiriquiProvinceQuerevaloCity,
    chiriquiProvinceQuintenoCity,
    chiriquiProvinceRemediosCity,
    chiriquiProvinceRinconCity,
    chiriquiProvinceRioSerenoCity,
    chiriquiProvinceRoviraArribaCity,
    chiriquiProvinceSanAndresCity,
    chiriquiProvinceSanCarlosCity,
    chiriquiProvinceSanFelixCity,
    chiriquiProvinceSanIsidroCity,
    chiriquiProvinceSanLorenzoCity,
    chiriquiProvinceSanPabloNuevoAbajoCity,
    chiriquiProvinceSanPabloViejoAbajoCity,
    chiriquiProvinceSantaClaraCity,
    chiriquiProvinceSantaCruzCity,
    chiriquiProvinceSantaMartaCity,
    chiriquiProvinceSantaRosaCity,
    chiriquiProvinceSantoDomingoCity,
    chiriquiProvinceSantoTomasCity,
    chiriquiProvinceSioguiAbajoCity,
    chiriquiProvinceSioguiArribaCity,
    chiriquiProvinceSortovaCity,
    chiriquiProvinceTijerasCity,
    chiriquiProvinceTinajasCity,
    chiriquiProvinceToleCity,
    chiriquiProvinceVeladeroCity,
    chiriquiProvinceVolcanCity
  ]);

/// The `Coclé Province` region in `Panama`
const Region panamaCocleProvince = Region(
  id: 1387,
  parentId: 170,
  longitude: -80.365865,
  latitude: 8.6266068,
  name: "Coclé Province",
  type: null,
  stateCode: "2",
  cities: [
    cocleProvinceAguadulceCity,
    cocleProvinceAguasBlancasCity,
    cocleProvinceAltoDeLaEstanciaCity,
    cocleProvinceAntonCity,
    cocleProvinceBarrancoColoradoCity,
    cocleProvinceCaballeroCity,
    cocleProvinceCabuyaCity,
    cocleProvinceCaimitoCity,
    cocleProvinceCanaveralCity,
    cocleProvinceCapellaniaCity,
    cocleProvinceChigoreCity,
    cocleProvinceChiguiriArribaCity,
    cocleProvinceChuruquitaChiquitaCity,
    cocleProvinceChuruquitaGrandeCity,
    cocleProvinceCocleCity,
    cocleProvinceDistritoDeAguadulceCity,
    cocleProvinceDistritoDeAntonCity,
    cocleProvinceDistritoDeLaPintadaCity,
    cocleProvinceDistritoDeNataCity,
    cocleProvinceDistritoDeOlaCity,
    cocleProvinceDistritoPenonomeCity,
    cocleProvinceElCanoCity,
    cocleProvinceElChiruCity,
    cocleProvinceElCocoCity,
    cocleProvinceElCopeCity,
    cocleProvinceElCortezoCity,
    cocleProvinceElCristoCity,
    cocleProvinceElPotreroCity,
    cocleProvinceElRetiroCity,
    cocleProvinceElRobleCity,
    cocleProvinceEntraderoCity,
    cocleProvinceFarallonCity,
    cocleProvinceGuzmanCity,
    cocleProvinceJuanDiazCity,
    cocleProvinceLaLomaCity,
    cocleProvinceLaPintadaCity,
    cocleProvinceLasHuacasDelQuijeCity,
    cocleProvinceLasMariasCity,
    cocleProvinceLasMinasCity,
    cocleProvinceLasSabanasCity,
    cocleProvinceLlanoGrandeCity,
    cocleProvinceLlanoMarinCity,
    cocleProvinceLosPollosCity,
    cocleProvinceNataCity,
    cocleProvinceNuestroAmoCity,
    cocleProvinceOlaCity,
    cocleProvincePenonomeCity,
    cocleProvincePiedrasGordasCity,
    cocleProvincePocriCity,
    cocleProvinceRioGrandeCity,
    cocleProvinceRioHatoCity,
    cocleProvinceSanJuanDeDiosCity,
    cocleProvinceToabreCity,
    cocleProvinceTozaCity,
    cocleProvinceVistaHermosaCity
  ]);

/// The `Colón Province` region in `Panama`
const Region panamaColonProvince = Region(
  id: 1386,
  parentId: 170,
  longitude: -80.0534923,
  latitude: 9.1851989,
  name: "Colón Province",
  type: null,
  stateCode: "3",
  cities: [
    colonProvinceBuenaVistaCity,
    colonProvinceCativaCity,
    colonProvinceCocleDelNorteCity,
    colonProvinceColonCity,
    colonProvinceCristobalCity,
    colonProvinceDistritoDeChagresCity,
    colonProvinceDistritoDeColonCity,
    colonProvinceDistritoDeDonosoCity,
    colonProvinceDistritoDePortobeloCity,
    colonProvinceDistritoDeSantaIsabelCity,
    colonProvinceElGiralCity,
    colonProvinceElGuaboCity,
    colonProvinceElValleDeLaUnionCity,
    colonProvinceEscobalCity,
    colonProvinceGatunCity,
    colonProvinceGatuncilloCity,
    colonProvinceLasMargaritasCity,
    colonProvinceMariaChiquitaCity,
    colonProvinceMiramarCity,
    colonProvinceNombreDeDiosCity,
    colonProvinceNuevoChagresCity,
    colonProvinceNuevoSanJuanCity,
    colonProvinceNuevoVigiaCity,
    colonProvincePalenqueCity,
    colonProvincePalmasBellasCity,
    colonProvincePalmiraCity,
    colonProvincePlayaChiquitaCity,
    colonProvincePortobeloCity,
    colonProvincePuertoEscondidoCity,
    colonProvincePuertoPilonCity,
    colonProvinceQuebradaBonitaAdentroCity,
    colonProvinceRioAlejandroCity,
    colonProvinceRioDuqueCity,
    colonProvinceRioRitaCity,
    colonProvinceSabanitasCity,
    colonProvinceSantaIsabelCity,
    colonProvinceSantaRitaArribaCity,
    colonProvinceVientoFrioCity
  ]);

/// The `Darién Province` region in `Panama`
const Region panamaDarienProvince = Region(
  id: 1385,
  parentId: 170,
  longitude: -77.8367282,
  latitude: 7.8681713,
  name: "Darién Province",
  type: null,
  stateCode: "5",
  cities: [
    darienProvinceBocaDeCupeCity,
    darienProvinceCamogantiCity,
    darienProvinceCucunatiCity,
    darienProvinceDistritoDeChepiganaCity,
    darienProvinceDistritoDePinoganaCity,
    darienProvinceGarachineCity,
    darienProvinceJaqueCity,
    darienProvinceLaPalmaCity,
    darienProvinceMetetiCity,
    darienProvinceMortiCity,
    darienProvincePucuroCity,
    darienProvinceSantaFeCity,
    darienProvinceYavizaCity
  ]);

/// The `Emberá-Wounaan Comarca` region in `Panama`
const Region panamaEmberaHypwounaanComarca = Region(
  id: 1396,
  parentId: 170,
  longitude: -77.6536125,
  latitude: 8.3766983,
  name: "Emberá-Wounaan Comarca",
  type: null,
  stateCode: "EM",
  cities: [
    emberaHypwounaanComarcaBayamonCity,
    emberaHypwounaanComarcaCemacoCity,
    emberaHypwounaanComarcaCorozalCity,
    emberaHypwounaanComarcaSambuCity,
    emberaHypwounaanComarcaUnionChocoCity,
    emberaHypwounaanComarcaYapeCity
  ]);

/// The `Guna Yala` region in `Panama`
const Region panamaGunaYala = Region(
  id: 1388,
  parentId: 170,
  longitude: -78.192625,
  latitude: 9.2344395,
  name: "Guna Yala",
  type: null,
  stateCode: "KY",
  cities: [
    gunaYalaAchutupoCity,
    gunaYalaAiligandiCity,
    gunaYalaCartiSugdupCity,
    gunaYalaElPorvenirCity,
    gunaYalaMulatupoCity,
    gunaYalaNarganaCity,
    gunaYalaPlayonChicoCity,
    gunaYalaPuertoObaldiaCity,
    gunaYalaSanIgnacioDeTupileCity,
    gunaYalaTubualaCity,
    gunaYalaUstupoCity
  ]);

/// The `Herrera Province` region in `Panama`
const Region panamaHerreraProvince = Region(
  id: 1389,
  parentId: 170,
  longitude: -80.7214417,
  latitude: 7.7704282,
  name: "Herrera Province",
  type: null,
  stateCode: "6",
  cities: [
    herreraProvinceBocaDeParitaCity,
    herreraProvinceCabuyaCity,
    herreraProvinceCerroLargoCity,
    herreraProvinceChitreCity,
    herreraProvinceChumicalCity,
    herreraProvinceChupampaCity,
    herreraProvinceDistritoDeChitreCity,
    herreraProvinceDistritoDeLasMinasCity,
    herreraProvinceDistritoDeLosPozosCity,
    herreraProvinceDistritoDeOcuCity,
    herreraProvinceDistritoDeParitaCity,
    herreraProvinceDistritoDePeseCity,
    herreraProvinceDistritoDeSantaMariaCity,
    herreraProvinceElCalabacitoCity,
    herreraProvinceElCapuriCity,
    herreraProvinceElCedroCity,
    herreraProvinceElPedregosoCity,
    herreraProvinceElRinconCity,
    herreraProvinceElToroCity,
    herreraProvinceLaArenaCity,
    herreraProvinceLaTrinidadCity,
    herreraProvinceLasGuabasCity,
    herreraProvinceLasMinasCity,
    herreraProvinceLeonesArribaCity,
    herreraProvinceLimonDeTijerasCity,
    herreraProvinceLlanoBonitoCity,
    herreraProvinceLlanoDeLaCruzCity,
    herreraProvinceLlanoGrandeCity,
    herreraProvinceLosCanelosCity,
    herreraProvinceLosCastillosCity,
    herreraProvinceLosCerritosCity,
    herreraProvinceLosCerrosDePajaCity,
    herreraProvinceLosPozosCity,
    herreraProvinceMonagrilloCity,
    herreraProvinceOcuCity,
    herreraProvinceParisCity,
    herreraProvinceParitaCity,
    herreraProvincePenasChatasCity,
    herreraProvincePeseCity,
    herreraProvincePitalozaArribaCity,
    herreraProvincePortobelilloCity,
    herreraProvincePotugaCity,
    herreraProvinceQuebradaDelRosarioCity,
    herreraProvinceRinconHondoCity,
    herreraProvinceSabanaGrandeCity,
    herreraProvinceSanJuanBautistaCity,
    herreraProvinceSantaMariaCity
  ]);

/// The `Los Santos Province` region in `Panama`
const Region panamaLosSantosProvince = Region(
  id: 1390,
  parentId: 170,
  longitude: -80.365865,
  latitude: 7.5909302,
  name: "Los Santos Province",
  type: null,
  stateCode: "7",
  cities: [
    losSantosProvinceAguaBuenaCity,
    losSantosProvinceAveMariaCity,
    losSantosProvinceBahiaHondaCity,
    losSantosProvinceBajoCorralCity,
    losSantosProvinceBayanoCity,
    losSantosProvinceBellaVistaCity,
    losSantosProvinceCambutalCity,
    losSantosProvinceCanasCity,
    losSantosProvinceCedroArribaCity,
    losSantosProvinceDistritoDeGuarareCity,
    losSantosProvinceDistritoDeLasTablasCity,
    losSantosProvinceDistritoDeLosSantosCity,
    losSantosProvinceDistritoDeMacaracasCity,
    losSantosProvinceDistritoDePedasiCity,
    losSantosProvinceDistritoDePocriCity,
    losSantosProvinceDistritoDeTonosiCity,
    losSantosProvinceElCacaoCity,
    losSantosProvinceElCanafistuloCity,
    losSantosProvinceElCarateCity,
    losSantosProvinceElCocalCity,
    losSantosProvinceElCortezoCity,
    losSantosProvinceElEjidoCity,
    losSantosProvinceElGuasimoCity,
    losSantosProvinceElHatoCity,
    losSantosProvinceElMacanoCity,
    losSantosProvinceElManantialCity,
    losSantosProvinceElMunozCity,
    losSantosProvinceElPedregosoCity,
    losSantosProvinceFloresCity,
    losSantosProvinceGuarareCity,
    losSantosProvinceGuarareArribaCity,
    losSantosProvinceLaColoradaCity,
    losSantosProvinceLaEneaCity,
    losSantosProvinceLaEspigadillaCity,
    losSantosProvinceLaLajaCity,
    losSantosProvinceLaMesaCity,
    losSantosProvinceLaMielCity,
    losSantosProvinceLaPalmaCity,
    losSantosProvinceLaPaseraCity,
    losSantosProvinceLaTizaCity,
    losSantosProvinceLaTronosaCity,
    losSantosProvinceLajaminaCity,
    losSantosProvinceLasCrucesCity,
    losSantosProvinceLasGuabasCity,
    losSantosProvinceLasPalmasCity,
    losSantosProvinceLasPalmitasCity,
    losSantosProvinceLasTablasCity,
    losSantosProvinceLasTrancasCity,
    losSantosProvinceLlanoAbajoCity,
    losSantosProvinceLlanoDePiedraCity,
    losSantosProvinceLlanoLargoCity,
    losSantosProvinceLosAngelesCity,
    losSantosProvinceLosAsientosCity,
    losSantosProvinceLosOlivosCity,
    losSantosProvinceLosSantosCity,
    losSantosProvinceMacaracasCity,
    losSantosProvinceMogollonCity,
    losSantosProvinceNuarioCity,
    losSantosProvinceOriaArribaCity,
    losSantosProvincePalmiraCity,
    losSantosProvinceParaisoCity,
    losSantosProvinceParitillaCity,
    losSantosProvincePedasiCity,
    losSantosProvincePenaBlancaCity,
    losSantosProvincePeralesCity,
    losSantosProvincePocriCity,
    losSantosProvinceRioHondoCity,
    losSantosProvinceSabanaGrandeCity,
    losSantosProvinceSanJoseCity,
    losSantosProvinceSantaAnaArribaCity,
    losSantosProvinceSantoDomingoCity,
    losSantosProvinceSesteaderoCity,
    losSantosProvinceTonosiCity,
    losSantosProvinceTresQuebradasCity,
    losSantosProvinceValleRicoCity,
    losSantosProvinceVallerriquitoCity,
    losSantosProvinceVillaLourdesCity
  ]);

/// The `Ngöbe-Buglé Comarca` region in `Panama`
const Region panamaNgobeHypbugleComarca = Region(
  id: 1391,
  parentId: 170,
  longitude: -81.7787021,
  latitude: 8.6595833,
  name: "Ngöbe-Buglé Comarca",
  type: null,
  stateCode: "NB",
  cities: [
    ngobeHypbugleComarcaBahiaAzulCity,
    ngobeHypbugleComarcaBesikoCity,
    ngobeHypbugleComarcaBisiraCity,
    ngobeHypbugleComarcaBocaDeBalsaCity,
    ngobeHypbugleComarcaBuenosAiresCity,
    ngobeHypbugleComarcaCamaronArribaCity,
    ngobeHypbugleComarcaCerroBancoCity,
    ngobeHypbugleComarcaCerroCanaCity,
    ngobeHypbugleComarcaCerroPlataCity,
    ngobeHypbugleComarcaChichicaCity,
    ngobeHypbugleComarcaGuayabitoCity,
    ngobeHypbugleComarcaHatoChamiCity,
    ngobeHypbugleComarcaHatoCorotuCity,
    ngobeHypbugleComarcaKankintuCity,
    ngobeHypbugleComarcaKusapinCity,
    ngobeHypbugleComarcaLajeroArribaCity,
    ngobeHypbugleComarcaLlanoNopoCity,
    ngobeHypbugleComarcaLomaYucaCity,
    ngobeHypbugleComarcaMironoCity,
    ngobeHypbugleComarcaMunaCity,
    ngobeHypbugleComarcaNoleDuimaCity,
    ngobeHypbugleComarcaNurunCity,
    ngobeHypbugleComarcaOmaCity,
    ngobeHypbugleComarcaParedonArribaCity,
    ngobeHypbugleComarcaPlanDeChorchaCity,
    ngobeHypbugleComarcaPuebloNuevoCity,
    ngobeHypbugleComarcaQuebradaCanoaCity,
    ngobeHypbugleComarcaQuebradaTulaCity,
    ngobeHypbugleComarcaSitioPradoCity,
    ngobeHypbugleComarcaTobobeCity
  ]);

/// The `Panamá Oeste Province` region in `Panama`
const Region panamaPanamaOesteProvince = Region(
  id: 1394,
  parentId: 170,
  longitude: -79.2902133,
  latitude: 9.1196751,
  name: "Panamá Oeste Province",
  type: null,
  stateCode: "10",
  cities: [
    panamaOesteProvinceAltoDelEspinoCity,
    panamaOesteProvinceAltosDeSanFranciscoCity,
    panamaOesteProvinceArenosaCity,
    panamaOesteProvinceArosemenaCity,
    panamaOesteProvinceArraijanCity,
    panamaOesteProvinceBejucoCity,
    panamaOesteProvinceBuenosAiresCity,
    panamaOesteProvinceCabuyaCity,
    panamaOesteProvinceCaimitoCity,
    panamaOesteProvinceCapiraCity,
    panamaOesteProvinceCermenoCity,
    panamaOesteProvinceCerroCamaCity,
    panamaOesteProvinceChameCity,
    panamaOesteProvinceCiriDeLosSotosCity,
    panamaOesteProvinceDistritoArraijanCity,
    panamaOesteProvinceDistritoDeCapiraCity,
    panamaOesteProvinceDistritoDeChameCity,
    panamaOesteProvinceDistritoDeLaChorreraCity,
    panamaOesteProvinceDistritoDeSanCarlosCity,
    panamaOesteProvinceElCacaoCity,
    panamaOesteProvinceElCocoCity,
    panamaOesteProvinceElEspaveCity,
    panamaOesteProvinceElEspinoCity,
    panamaOesteProvinceElHigoCity,
    panamaOesteProvinceElLibanoCity,
    panamaOesteProvinceGuadalupeCity,
    panamaOesteProvinceGuayabitoCity,
    panamaOesteProvinceHatoMontanaCity,
    panamaOesteProvinceLaChorreraCity,
    panamaOesteProvinceLaErmitaCity,
    panamaOesteProvinceLaHerraduraCity,
    panamaOesteProvinceLaLagunaCity,
    panamaOesteProvinceLaMitraCity,
    panamaOesteProvinceLaPesaCity,
    panamaOesteProvinceLasColinasCity,
    panamaOesteProvinceLasLajasCity,
    panamaOesteProvinceLasUvasCity,
    panamaOesteProvinceLlanoLargoCity,
    panamaOesteProvinceLosLlanitosCity,
    panamaOesteProvinceMendozaCity,
    panamaOesteProvinceNuevaArenosaCity,
    panamaOesteProvinceNuevaGorgonaCity,
    panamaOesteProvinceNuevoArraijanCity,
    panamaOesteProvinceNuevoEmperadorCity,
    panamaOesteProvincePlayaLeonaCity,
    panamaOesteProvincePotreroGrandeCity,
    panamaOesteProvincePuertoCaimitoCity,
    panamaOesteProvinceRioCongoCity,
    panamaOesteProvinceSanCarlosCity,
    panamaOesteProvinceSanJoseCity,
    panamaOesteProvinceSanVicenteDeBiqueCity,
    panamaOesteProvinceSantaClaraCity,
    panamaOesteProvinceSantaRitaCity,
    panamaOesteProvinceSoraCity,
    panamaOesteProvinceVeracruzCity,
    panamaOesteProvinceVillaCarmenCity,
    panamaOesteProvinceVillaRosarioCity,
    panamaOesteProvinceVistaAlegreCity
  ]);

/// The `Panamá Province` region in `Panama`
const Region panamaPanamaProvince = Region(
  id: 1395,
  parentId: 170,
  longitude: -79.2902133,
  latitude: 9.1196751,
  name: "Panamá Province",
  type: null,
  stateCode: "8",
  cities: [
    panamaProvinceAlcaldeDiazCity,
    panamaProvinceAnconCity,
    panamaProvinceBrujasCity,
    panamaProvinceCabraNumeroUnoCity,
    panamaProvinceCaimitilloCity,
    panamaProvinceCalzadaLargaCity,
    panamaProvinceCanitaCity,
    panamaProvinceCerroAzulCity,
    panamaProvinceChepilloCity,
    panamaProvinceChepoCity,
    panamaProvinceChilibreCity,
    panamaProvinceChimanCity,
    panamaProvinceContadoraCity,
    panamaProvinceCurunduCity,
    panamaProvinceDistritoDeBalboaCity,
    panamaProvinceDistritoDeChepoCity,
    panamaProvinceDistritoDeChimanCity,
    panamaProvinceDistritoDePanamaCity,
    panamaProvinceDistritoDeTabogaCity,
    panamaProvinceElChorrilloCity,
    panamaProvinceElProgresoCity,
    panamaProvinceGonzalilloCity,
    panamaProvinceHowardCity,
    panamaProvinceJuanDiazCity,
    panamaProvinceLaCabimaCity,
    panamaProvinceLaColoradaCity,
    panamaProvinceLaEnsenadaCity,
    panamaProvinceLaEsmeraldaCity,
    panamaProvinceLaGuineaCity,
    panamaProvinceLaMesaCity,
    panamaProvinceLasCumbresCity,
    panamaProvinceLasMargaritasCity,
    panamaProvinceLidiceCity,
    panamaProvinceLosLotesCity,
    panamaProvinceNuevaEsperanzaCity,
    panamaProvinceNuevoBelenCity,
    panamaProvincePacoraCity,
    panamaProvincePanamaCity,
    panamaProvinceParqueLefevreCity,
    panamaProvincePasigaCity,
    panamaProvincePedregalCity,
    panamaProvinceRioAbajoCity,
    panamaProvinceSanAntonioCity,
    panamaProvinceSanFelipeCity,
    panamaProvinceSanMiguelCity,
    panamaProvinceSanMiguelitoCity,
    panamaProvinceSanVicenteCity,
    panamaProvinceTocumenCity,
    panamaProvinceTortiCity,
    panamaProvinceUnionDeAzueroCity,
    panamaProvinceUnionSantenaCity,
    panamaProvinceVillaUnidaCity,
    panamaProvinceVistaHermosaCity
  ]);

/// The `Veraguas Province` region in `Panama`
const Region panamaVeraguasProvince = Region(
  id: 1392,
  parentId: 170,
  longitude: -81.0754657,
  latitude: 8.1231033,
  name: "Veraguas Province",
  type: null,
  stateCode: "9",
  cities: [
    veraguasProvinceAltoDeJesusCity,
    veraguasProvinceArenasCity,
    veraguasProvinceAtalayaCity,
    veraguasProvinceBarnizalCity,
    veraguasProvinceBisvallesCity,
    veraguasProvinceBoqueronCity,
    veraguasProvinceBoroCity,
    veraguasProvinceCalabacitoCity,
    veraguasProvinceCalidoniaCity,
    veraguasProvinceCalobreCity,
    veraguasProvinceCaloveboraCity,
    veraguasProvinceCanazasCity,
    veraguasProvinceCantoDelLlanoCity,
    veraguasProvinceCorozalCity,
    veraguasProvinceDistritoDeAtalayaCity,
    veraguasProvinceDistritoDeCalobreCity,
    veraguasProvinceDistritoDeCanazasCity,
    veraguasProvinceDistritoDeLaMesaCity,
    veraguasProvinceDistritoDeLasPalmasCity,
    veraguasProvinceDistritoDeMontijoCity,
    veraguasProvinceDistritoDeRioDeJesusCity,
    veraguasProvinceDistritoDeSanFranciscoCity,
    veraguasProvinceDistritoDeSantaFeCity,
    veraguasProvinceDistritoDeSantiagoCity,
    veraguasProvinceDistritoDeSonaCity,
    veraguasProvinceElAltoCity,
    veraguasProvinceElBarritoCity,
    veraguasProvinceElCoclaCity,
    veraguasProvinceElEspinoDeSantaRosaCity,
    veraguasProvinceElMaranonCity,
    veraguasProvinceElMariaCity,
    veraguasProvinceElPajaroCity,
    veraguasProvinceElPantanoCity,
    veraguasProvinceElPenonCity,
    veraguasProvinceElPicadorCity,
    veraguasProvinceElPotreroCity,
    veraguasProvinceElRinconCity,
    veraguasProvinceElUvitoCity,
    veraguasProvinceGuarumalCity,
    veraguasProvinceLaColoradaCity,
    veraguasProvinceLaGarceanaCity,
    veraguasProvinceLaLagunaCity,
    veraguasProvinceLaLomaCity,
    veraguasProvinceLaMesaCity,
    veraguasProvinceLaMontanuelaCity,
    veraguasProvinceLaPenaCity,
    veraguasProvinceLaRayaDeCalobreCity,
    veraguasProvinceLaRayaDeSantaMariaCity,
    veraguasProvinceLaYeguadaCity,
    veraguasProvinceLasGuiasAbajoCity,
    veraguasProvinceLasHuacasCity,
    veraguasProvinceLasPalmasCity,
    veraguasProvinceLeonesArribaCity,
    veraguasProvinceLlanoGrandeCity,
    veraguasProvinceLolaCity,
    veraguasProvinceLosAlgarrobosCity,
    veraguasProvinceLosCastillosCity,
    veraguasProvinceLosHigosCity,
    veraguasProvinceMariatoDistrictCity,
    veraguasProvinceMonjarasCity,
    veraguasProvinceMontijoCity,
    veraguasProvincePiedrasGordasCity,
    veraguasProvincePonugaCity,
    veraguasProvincePuertoVidalCity,
    veraguasProvinceQuebradaDeOroCity,
    veraguasProvinceRioDeJesusCity,
    veraguasProvinceRioGrandeCity,
    veraguasProvinceRodeoViejoCity,
    veraguasProvinceSanBartoloCity,
    veraguasProvinceSanFranciscoCity,
    veraguasProvinceSanJoseCity,
    veraguasProvinceSanJuanCity,
    veraguasProvinceSanMarceloCity,
    veraguasProvinceSanPedroDelEspinoCity,
    veraguasProvinceSantaFeCity,
    veraguasProvinceSantiagoDeVeraguasCity,
    veraguasProvinceSonaCity,
    veraguasProvinceTebarioCity,
    veraguasProvinceUtiraCity,
    veraguasProvinceViguiCity,
    veraguasProvinceZapotilloCity
  ]);

/// The 13 states of `Panama` keyed by their id.
const Map<int, Region> panamaStates = <int, Region>{
    1393: panamaBocasDelToroProvince,
    1397: panamaChiriquiProvince,
    1387: panamaCocleProvince,
    1386: panamaColonProvince,
    1385: panamaDarienProvince,
    1396: panamaEmberaHypwounaanComarca,
    1388: panamaGunaYala,
    1389: panamaHerreraProvince,
    1390: panamaLosSantosProvince,
    1391: panamaNgobeHypbugleComarca,
    1394: panamaPanamaOesteProvince,
    1395: panamaPanamaProvince,
    1392: panamaVeraguasProvince
  };
