/// Access to known geographies in Peru and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'peru_cities.dart';

/// The 25 regions of `🇵🇪 Peru`
const Region peruAmazonas = Region(id: 3685, parentId: 173, longitude: 1.7976931348623157e+308, latitude: 1.7976931348623157e+308,
          name: "Amazonas", type: null, stateCode: "AMA",
          cities: [
            peruAmazonasBaguaGrande,
            peruAmazonasCajaruro,
            peruAmazonasChachapoyas,
            peruAmazonasCondorcanqui,
            peruAmazonasLaPeca,
            peruAmazonasProvinciaDdeBagua,
            peruAmazonasProvinciaDdeBongara,
            peruAmazonasProvinciaDdeChachapoyas,
            peruAmazonasProvinciaDdeLuya,
            peruAmazonasProvinciaDdeRodriguezDdeMendoza,
            peruAmazonasUtcubamba
          ]);
const Region peruAncash = Region(id: 3680, parentId: 173, longitude: -77.5619419, latitude: -9.3250497,
          name: "Áncash", type: null, stateCode: "ANC",
          cities: [
            peruAncashAsuncion,
            peruAncashCaras,
            peruAncashCarhuaz,
            peruAncashCarlosFerminFitzcarrald,
            peruAncashChimbote,
            peruAncashCoishco,
            peruAncashHuaraz,
            peruAncashHuarmey,
            peruAncashPomabamba,
            peruAncashProvinciaDdeAija,
            peruAncashProvinciaDdeAntonioRaymondi,
            peruAncashProvinciaDdeBolognesi,
            peruAncashProvinciaDdeCarhuaz,
            peruAncashProvinciaDdeCasma,
            peruAncashProvinciaDdeCorongo,
            peruAncashProvinciaDdeHuaraz,
            peruAncashProvinciaDdeHuari,
            peruAncashProvinciaDdeHuarmey,
            peruAncashProvinciaDdeHuaylas,
            peruAncashProvinciaDdeMariscalLuzuriaga,
            peruAncashProvinciaDdePallasca,
            peruAncashProvinciaDdePomabamba,
            peruAncashProvinciaDdeRecuay,
            peruAncashProvinciaDdeSanta,
            peruAncashProvinciaDdeSihuas,
            peruAncashProvinciaDdeYungay,
            peruAncashPuertoSanta,
            peruAncashYauya,
            peruAncashYungay
          ]);
const Region peruApurimac = Region(id: 3699, parentId: 173, longitude: -73.087749, latitude: -14.0504533,
          name: "Apurímac", type: null, stateCode: "APU",
          cities: [
            peruApurimacAbancay,
            peruApurimacAndahuaylas,
            peruApurimacProvinciaDdeAbancay,
            peruApurimacProvinciaDdeAndahuaylas,
            peruApurimacProvinciaDdeAntabamba,
            peruApurimacProvinciaDdeAymaraes,
            peruApurimacProvinciaDdeCotabambas,
            peruApurimacProvinciaDdeGrau,
            peruApurimacSanJeronimo,
            peruApurimacTalavera
          ]);
const Region peruArequipa = Region(id: 3681, parentId: 173, longitude: -71.537451, latitude: -16.4090474,
          name: "Arequipa", type: null, stateCode: "ARE",
          cities: [
            peruArequipaAcari,
            peruArequipaArequipa,
            peruArequipaCamana,
            peruArequipaCcolo,
            peruArequipaChivay,
            peruArequipaCocachacra,
            peruArequipaCotahuasi,
            peruArequipaHuarancante,
            peruArequipaHuarichancara,
            peruArequipaJatunOrcochiri,
            peruArequipaJayune,
            peruArequipaLlongasora,
            peruArequipaLluta,
            peruArequipaMollendo,
            peruArequipaOrcopampa,
            peruArequipaProvinciaDdeArequipa,
            peruArequipaProvinciaDdeCamana,
            peruArequipaProvinciaDdeCaraveli,
            peruArequipaProvinciaDdeCastilla,
            peruArequipaProvinciaDdeCaylloma,
            peruArequipaProvinciaDdeCondesuyos,
            peruArequipaProvinciaDdeIslay,
            peruArequipaProvinciaDdeLaUnion,
            peruArequipaPucara,
            peruArequipaPuntaDdeBombon,
            peruArequipaVizcachane,
            peruArequipaYura
          ]);
const Region peruAyacucho = Region(id: 3692, parentId: 173, longitude: -74.2235641, latitude: -13.1638737,
          name: "Ayacucho", type: null, stateCode: "AYA",
          cities: [
            peruAyacuchoAyacucho,
            peruAyacuchoAyna,
            peruAyacuchoCoracora,
            peruAyacuchoHuanta,
            peruAyacuchoPaucarDelSaraSara,
            peruAyacuchoProvinciaDdeCangallo,
            peruAyacuchoProvinciaDdeHuamanga,
            peruAyacuchoProvinciaDdeHuancaSancos,
            peruAyacuchoProvinciaDdeHuanta,
            peruAyacuchoProvinciaDdeLaMar,
            peruAyacuchoProvinciaDdeLucanas,
            peruAyacuchoProvinciaDdeParinacochas,
            peruAyacuchoProvinciaDdeSucre,
            peruAyacuchoProvinciaDdeVictorFajardo,
            peruAyacuchoProvinciaDdeVilcasHuaman,
            peruAyacuchoPuquio,
            peruAyacuchoSanMiguel,
            peruAyacuchoTambo
          ]);
const Region peruCajamarca = Region(id: 3688, parentId: 173, longitude: -78.5127855, latitude: -7.1617465,
          name: "Cajamarca", type: null, stateCode: "CAJ",
          cities: [
            peruCajamarcaBambamarca,
            peruCajamarcaBellavista,
            peruCajamarcaCajabamba,
            peruCajamarcaCajamarca,
            peruCajamarcaCelendin,
            peruCajamarcaChota,
            peruCajamarcaJaen,
            peruCajamarcaProvinciaDdeCajabamba,
            peruCajamarcaProvinciaDdeCajamarca,
            peruCajamarcaProvinciaDdeCelendin,
            peruCajamarcaProvinciaDdeChota,
            peruCajamarcaProvinciaDdeContumaza,
            peruCajamarcaProvinciaDdeCutervo,
            peruCajamarcaProvinciaDdeHualgayoc,
            peruCajamarcaProvinciaDdeJaen,
            peruCajamarcaProvinciaDdeSanIgnacio,
            peruCajamarcaProvinciaDdeSanMiguel,
            peruCajamarcaProvinciaDdeSantaCruz,
            peruCajamarcaSanIgnacio
          ]);
const Region peruCallao = Region(id: 3701, parentId: 173, longitude: -77.1259843, latitude: -12.0508491,
          name: "Callao", type: null, stateCode: "CAL",
          cities: [
            peruCallaoCallao
          ]);
const Region peruCusco = Region(id: 3691, parentId: 173, longitude: -71.9674626, latitude: -13.53195,
          name: "Cusco", type: null, stateCode: "CUS",
          cities: [
            peruCuscoAnta,
            peruCuscoCahuanuyo,
            peruCuscoCalca,
            peruCuscoCallanca,
            peruCuscoCcaquiracunca,
            peruCuscoCcuntuma,
            peruCuscoChecacupe,
            peruCuscoChecca,
            peruCuscoChignayhua,
            peruCuscoChinchero,
            peruCuscoCombapata,
            peruCuscoConchopata,
            peruCuscoCullcuyre,
            peruCuscoCusco,
            peruCuscoHuaynaAlcalde,
            peruCuscoJayobamba,
            peruCuscoLangui,
            peruCuscoLayo,
            peruCuscoLimaPampa,
            peruCuscoMarangani,
            peruCuscoMaras,
            peruCuscoMosocCancha,
            peruCuscoMosocLlacta,
            peruCuscoOllantaytambo,
            peruCuscoOropesa,
            peruCuscoPampamarca,
            peruCuscoPangoa,
            peruCuscoPaucartambo,
            peruCuscoPisac,
            peruCuscoProvinciaDdeAcomayo,
            peruCuscoProvinciaDdeAnta,
            peruCuscoProvinciaDdeCalca,
            peruCuscoProvinciaDdeCanas,
            peruCuscoProvinciaDdeCanchis,
            peruCuscoProvinciaDdeChumbivilcas,
            peruCuscoProvinciaDdeCusco,
            peruCuscoProvinciaDdeEspinar,
            peruCuscoProvinciaDdeLaConvencion,
            peruCuscoProvinciaDdeParuro,
            peruCuscoProvinciaDdePaucartambo,
            peruCuscoProvinciaDdeQuispicanchis,
            peruCuscoProvinciaDdeUrubamba,
            peruCuscoQquea,
            peruCuscoQueromarca,
            peruCuscoSanPablo,
            peruCuscoSantaAna,
            peruCuscoSantoTomas,
            peruCuscoSicuani,
            peruCuscoTinta,
            peruCuscoTungasuca,
            peruCuscoUrcos,
            peruCuscoUrubamba,
            peruCuscoYanaoca
          ]);
const Region peruHuancavelica = Region(id: 3679, parentId: 173, longitude: -74.9764024, latitude: -12.7861978,
          name: "Huancavelica", type: null, stateCode: "HUV",
          cities: [
            peruHuancavelicaHuancavelica,
            peruHuancavelicaHuaytara,
            peruHuancavelicaPampas,
            peruHuancavelicaProvinciaDdeAcobamba,
            peruHuancavelicaProvinciaDdeAngaraes,
            peruHuancavelicaProvinciaDdeCastrovirreyna,
            peruHuancavelicaProvinciaDdeChurcampa,
            peruHuancavelicaProvinciaDdeHuancavelica,
            peruHuancavelicaProvinciaDdeTayacaja
          ]);
const Region peruHuanuco = Region(id: 3687, parentId: 173, longitude: -76.2410843, latitude: -9.9207648,
          name: "Huanuco", type: null, stateCode: "HUC",
          cities: [
            peruHuanucoAmbo,
            peruHuanucoHuacaybamba,
            peruHuanucoHuanuco,
            peruHuanucoLaUnion,
            peruHuanucoLauricocha,
            peruHuanucoLlata,
            peruHuanucoProvinciaDdeAmbo,
            peruHuanucoProvinciaDdeDosDdeMayo,
            peruHuanucoProvinciaDdeHuamalies,
            peruHuanucoProvinciaDdeHuanuco,
            peruHuanucoProvinciaDdeLeoncioPrado,
            peruHuanucoProvinciaDdeMaranon,
            peruHuanucoProvinciaDdePachitea,
            peruHuanucoPuertoInca,
            peruHuanucoSanMiguelDdeCauri,
            peruHuanucoTingoMaria,
            peruHuanucoYanacancha,
            peruHuanucoYarowilca
          ]);
const Region peruIca = Region(id: 3700, parentId: 173, longitude: -71.0430097, latitude: 42.3528832,
          name: "Ica", type: null, stateCode: "ICA",
          cities: [
            peruIcaChinchaAlta,
            peruIcaIca,
            peruIcaLosAquijes,
            peruIcaMinasDdeMarcona,
            peruIcaNazca,
            peruIcaPalpa,
            peruIcaParacas,
            peruIcaPisco,
            peruIcaProvinciaDdeChincha,
            peruIcaProvinciaDdeIca,
            peruIcaProvinciaDdeNazca,
            peruIcaProvinciaDdePalpa,
            peruIcaProvinciaDdePisco,
            peruIcaRioGrande,
            peruIcaSanClemente,
            peruIcaSanJuanBautista,
            peruIcaSantiago,
            peruIcaSubtanjalla,
            peruIcaVillaTupacAmaru
          ]);
const Region peruJunin = Region(id: 3693, parentId: 173, longitude: -75.9926306, latitude: -11.1581925,
          name: "Junín", type: null, stateCode: "JUN",
          cities: [
            peruJuninAcolla,
            peruJuninCarhuamayo,
            peruJuninChanchamayo,
            peruJuninChupaca,
            peruJuninConcepcion,
            peruJuninHuancayo,
            peruJuninHuasahuasi,
            peruJuninHuayucachi,
            peruJuninJauja,
            peruJuninJunin,
            peruJuninLaOroya,
            peruJuninMazamari,
            peruJuninMorococha,
            peruJuninOrcotuna,
            peruJuninPerene,
            peruJuninPilcomay,
            peruJuninProvinciaDdeChupaca,
            peruJuninProvinciaDdeConcepcion,
            peruJuninProvinciaDdeHuancayo,
            peruJuninProvinciaDdeJauja,
            peruJuninProvinciaDdeJunin,
            peruJuninProvinciaDdeSatipo,
            peruJuninProvinciaDdeTarma,
            peruJuninProvinciaDdeYauli,
            peruJuninSanAgustin,
            peruJuninSanJeronimo,
            peruJuninSanPedroDdeCajas,
            peruJuninSanRamon,
            peruJuninSatipo,
            peruJuninSicaya,
            peruJuninTarma
          ]);
const Region peruLaLibertad = Region(id: 3683, parentId: 173, longitude: -89.3084607, latitude: 13.490697,
          name: "La Libertad", type: null, stateCode: "LAL",
          cities: [
            peruLaLibertadAscope,
            peruLaLibertadCascas,
            peruLaLibertadChepen,
            peruLaLibertadChicama,
            peruLaLibertadChocope,
            peruLaLibertadGranChimu,
            peruLaLibertadGuadalupe,
            peruLaLibertadHuamachuco,
            peruLaLibertadJulcan,
            peruLaLibertadLaredo,
            peruLaLibertadMoche,
            peruLaLibertadOtuzco,
            peruLaLibertadPacanga,
            peruLaLibertadPacasmayo,
            peruLaLibertadPaijan,
            peruLaLibertadProvinciaDdeBolivar,
            peruLaLibertadProvinciaDdeOtuzco,
            peruLaLibertadProvinciaDdePacasmayo,
            peruLaLibertadProvinciaDdePataz,
            peruLaLibertadProvinciaDdeSantiagoDdeChuco,
            peruLaLibertadProvinciaDdeTrujillo,
            peruLaLibertadPuebloNuevo,
            peruLaLibertadQuiruvilca,
            peruLaLibertadSalaverry,
            peruLaLibertadSanPedroDdeLloc,
            peruLaLibertadSanchezCarrion,
            peruLaLibertadSantiagoDdeCao,
            peruLaLibertadSantiagoDdeChuco,
            peruLaLibertadTrujillo,
            peruLaLibertadViru
          ]);
const Region peruLambayeque = Region(id: 3702, parentId: 173, longitude: -79.9080757, latitude: -6.7197666,
          name: "Lambayeque", type: null, stateCode: "LAM",
          cities: [
            peruLambayequeChiclayo,
            peruLambayequeChongoyape,
            peruLambayequeEten,
            peruLambayequeFerrenafe,
            peruLambayequeJayanca,
            peruLambayequeLambayeque,
            peruLambayequeMochumi,
            peruLambayequeMonsefu,
            peruLambayequeMorrope,
            peruLambayequeMotupe,
            peruLambayequeOlmos,
            peruLambayequeOyotun,
            peruLambayequePicsi,
            peruLambayequePimentel,
            peruLambayequeProvinciaDdeChiclayo,
            peruLambayequeProvinciaDdeFerrenafe,
            peruLambayequeProvinciaDdeLambayeque,
            peruLambayequePuebloNuevo,
            peruLambayequeReque,
            peruLambayequeSanJose,
            peruLambayequeSana,
            peruLambayequeSantaRosa,
            peruLambayequeTucume
          ]);
const Region peruLima = Region(id: 3695, parentId: 173, longitude: -77.042754, latitude: -12.0463731,
          name: "Lima", type: null, stateCode: "LIM",
          cities: [
            peruLimaAsentamientoHumanoNicolasDdePierola,
            peruLimaBarranca,
            peruLimaCaletaDdeCarquin,
            peruLimaChancay,
            peruLimaChilca,
            peruLimaChosica,
            peruLimaHuacho,
            peruLimaHualmay,
            peruLimaHuaral,
            peruLimaHuaura,
            peruLimaImperial,
            peruLimaIndependencia,
            peruLimaLima,
            peruLimaMala,
            peruLimaMatucana,
            peruLimaNuevoImperial,
            peruLimaOyon,
            peruLimaParamonga,
            peruLimaPativilca,
            peruLimaProvinciaDdeCajatambo,
            peruLimaProvinciaDdeCanete,
            peruLimaProvinciaDdeCanta,
            peruLimaProvinciaDdeHuaral,
            peruLimaProvinciaDdeHuarochiri,
            peruLimaProvinciaDdeYauyos,
            peruLimaPuertoSupe,
            peruLimaQuilmana,
            peruLimaRicardoPalma,
            peruLimaSanBartolo,
            peruLimaSanIsidro,
            peruLimaSanLuis,
            peruLimaSanVicenteDdeCanete,
            peruLimaSantaMaria,
            peruLimaSantiagoDdeSurco,
            peruLimaSayan,
            peruLimaSupe,
            peruLimaUrbDotSantoDomingo,
            peruLimaVegueta
          ]);
const Region peruLoreto = Region(id: 4922, parentId: 173, longitude: -76.1304264, latitude: -4.3741643,
          name: "Loreto", type: null, stateCode: "LOR",
          cities: [
            peruLoretoAndoas,
            peruLoretoBorja,
            peruLoretoCaballococha,
            peruLoretoCapePantoja,
            peruLoretoIndiana,
            peruLoretoIquitos,
            peruLoretoJeberos,
            peruLoretoJenaroHerrera,
            peruLoretoLagunas,
            peruLoretoNauta,
            peruLoretoPunchana,
            peruLoretoRequena,
            peruLoretoSanAntonioDdelEstrecho,
            peruLoretoSanLorenzo,
            peruLoretoSanPablo,
            peruLoretoTamshiyacu,
            peruLoretoYurimaguas
          ]);
const Region peruMadreDdeDios = Region(id: 3678, parentId: 173, longitude: -70.8119953, latitude: -11.7668705,
          name: "Madre de Dios", type: null, stateCode: "MDD",
          cities: [
            peruMadreDdeDiosIberia,
            peruMadreDdeDiosProvinciaDdeManu,
            peruMadreDdeDiosProvinciaDdeTahuamanu,
            peruMadreDdeDiosProvinciaDdeTambopata,
            peruMadreDdeDiosPuertoMaldonado,
            peruMadreDdeDiosSalvacion,
            peruMadreDdeDiosTambopata
          ]);
const Region peruMoquegua = Region(id: 3698, parentId: 173, longitude: -70.9328138, latitude: -17.1927361,
          name: "Moquegua", type: null, stateCode: "MOQ",
          cities: [
            peruMoqueguaIlo,
            peruMoqueguaMoquegua,
            peruMoqueguaPacocha,
            peruMoqueguaProvinciaDdeGeneralSanchezCerro,
            peruMoqueguaProvinciaDdeIlo,
            peruMoqueguaProvinciaDdeMariscalNieto,
            peruMoqueguaTorata
          ]);
const Region peruPasco = Region(id: 3686, parentId: 173, longitude: -119.0922316, latitude: 46.2305049,
          name: "Pasco", type: null, stateCode: "PAS",
          cities: [
            peruPascoCerroDdePasco,
            peruPascoChaupimarca,
            peruPascoOxapampa,
            peruPascoPaucartambo,
            peruPascoProvinciaDdeDanielCarrion,
            peruPascoProvinciaDdeOxapampa,
            peruPascoProvinciaDdePasco,
            peruPascoTinyahuarco,
            peruPascoVillaRica
          ]);
const Region peruPiura = Region(id: 3697, parentId: 173, longitude: -80.6548882, latitude: -5.1782884,
          name: "Piura", type: null, stateCode: "PIU",
          cities: [
            peruPiuraAyabaca,
            peruPiuraBernal,
            peruPiuraBuenosAires,
            peruPiuraCatacaos,
            peruPiuraChulucanas,
            peruPiuraElAlto,
            peruPiuraHuancabamba,
            peruPiuraLaBreita,
            peruPiuraLaHuaca,
            peruPiuraLaUnion,
            peruPiuraLasLomas,
            peruPiuraMancora,
            peruPiuraMarcavelica,
            peruPiuraMorropon,
            peruPiuraPaita,
            peruPiuraPiura,
            peruPiuraProvinciaDdeAyabaca,
            peruPiuraProvinciaDdeHuancabamba,
            peruPiuraProvinciaDdePaita,
            peruPiuraProvinciaDdePiura,
            peruPiuraProvinciaDdeSullana,
            peruPiuraProvinciaDdeTalara,
            peruPiuraQuerecotillo,
            peruPiuraSalineraColan,
            peruPiuraSalitral,
            peruPiuraSechura,
            peruPiuraSullana,
            peruPiuraTalara,
            peruPiuraTamboGrande,
            peruPiuraVice
          ]);
const Region peruPuno = Region(id: 3682, parentId: 173, longitude: -70.0218805, latitude: -15.8402218,
          name: "Puno", type: null, stateCode: "PUN",
          cities: [
            peruPunoAtuncolla,
            peruPunoAyaviri,
            peruPunoAzangaro,
            peruPunoDesaguadero,
            peruPunoElCollao,
            peruPunoHaciendaHuancane,
            peruPunoIlave,
            peruPunoJuli,
            peruPunoJuliaca,
            peruPunoLaRinconada,
            peruPunoLampa,
            peruPunoMacusani,
            peruPunoNunoa,
            peruPunoProvinciaDdeAzangaro,
            peruPunoProvinciaDdeCarabaya,
            peruPunoProvinciaDdeChucuito,
            peruPunoProvinciaDdeHuancane,
            peruPunoProvinciaDdeLampa,
            peruPunoProvinciaDdeMelgar,
            peruPunoProvinciaDdePuno,
            peruPunoProvinciaDdeSandia,
            peruPunoPuno,
            peruPunoSanAntonioDePutina,
            peruPunoSanRoman,
            peruPunoSantaLucia,
            peruPunoTaquile,
            peruPunoYunguyo
          ]);
const Region peruSanMartin = Region(id: 3694, parentId: 173, longitude: -121.6102216, latitude: 37.0849464,
          name: "San Martín", type: null, stateCode: "SAM",
          cities: [
            peruSanMartinBellavista,
            peruSanMartinChazuta,
            peruSanMartinElDorado,
            peruSanMartinHuicungo,
            peruSanMartinJepelacio,
            peruSanMartinJuanjui,
            peruSanMartinLamas,
            peruSanMartinMoyobamba,
            peruSanMartinPicota,
            peruSanMartinProvinciaDdeHuallaga,
            peruSanMartinProvinciaDdeLamas,
            peruSanMartinProvinciaDdeMariscalCaceres,
            peruSanMartinProvinciaDdeMoyobamba,
            peruSanMartinProvinciaDdeRioja,
            peruSanMartinProvinciaDdeSanMartin,
            peruSanMartinRioja,
            peruSanMartinSaposoa,
            peruSanMartinSisa,
            peruSanMartinSoritor,
            peruSanMartinTabalosos,
            peruSanMartinTarapoto,
            peruSanMartinTocache,
            peruSanMartinUchiza
          ]);
const Region peruTacna = Region(id: 3696, parentId: 173, longitude: -70.2462741, latitude: -18.0065679,
          name: "Tacna", type: null, stateCode: "TAC",
          cities: [
            peruTacnaCalana,
            peruTacnaCandarave,
            peruTacnaChipispaya,
            peruTacnaChuquitira,
            peruTacnaIlabaya,
            peruTacnaJorgeBasadre,
            peruTacnaProvinciaDdeTacna,
            peruTacnaProvinciaDdeTarata,
            peruTacnaPujocucho,
            peruTacnaQuilahuani,
            peruTacnaTacna,
            peruTacnaTarata,
            peruTacnaTotoral
          ]);
const Region peruTumbes = Region(id: 3689, parentId: 173, longitude: -80.4270885, latitude: -3.5564921,
          name: "Tumbes", type: null, stateCode: "TUM",
          cities: [
            peruTumbesAguasVerdes,
            peruTumbesPapayal,
            peruTumbesProvinciaDdeContralmiranteVillar,
            peruTumbesProvinciaDdeTumbes,
            peruTumbesProvinciaDdeZarumilla,
            peruTumbesTumbes,
            peruTumbesZarumilla,
            peruTumbesZorritos
          ]);
const Region peruUcayali = Region(id: 3684, parentId: 173, longitude: -73.087749, latitude: -9.8251183,
          name: "Ucayali", type: null, stateCode: "UCA",
          cities: [
            peruUcayaliAtalaya,
            peruUcayaliCampoverde,
            peruUcayaliPadreAbad,
            peruUcayaliProvinciaDdeCoronelPortillo,
            peruUcayaliPucallpa,
            peruUcayaliPurus
          ]);

const peruStates = <int, Region>{
    3685: peruAmazonas,
    3680: peruAncash,
    3699: peruApurimac,
    3681: peruArequipa,
    3692: peruAyacucho,
    3688: peruCajamarca,
    3701: peruCallao,
    3691: peruCusco,
    3679: peruHuancavelica,
    3687: peruHuanuco,
    3700: peruIca,
    3693: peruJunin,
    3683: peruLaLibertad,
    3702: peruLambayeque,
    3695: peruLima,
    4922: peruLoreto,
    3678: peruMadreDdeDios,
    3698: peruMoquegua,
    3686: peruPasco,
    3697: peruPiura,
    3682: peruPuno,
    3694: peruSanMartin,
    3696: peruTacna,
    3689: peruTumbes,
    3684: peruUcayali
  };
