/// Access to known geographies in `Portugal` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.
library;

import '../base.dart';
import 'portugal_cities.dart';

/// The `Açores` region in `Portugal`
const Region portugalAcores = Region(
  id: 2233,
  parentId: 177,
  longitude: -25.6755944,
  latitude: 37.7412488,
  name: "Açores",
  type: null,
  stateCode: "20",
  cities: [
    acoresAguaDePauCity,
    acoresAngraDoHeroismoCity,
    acoresAngustiasCity,
    acoresArrifesCity,
    acoresBiscoitosCity,
    acoresCaboucoCity,
    acoresCaisDoPicoCity,
    acoresCalhetaCity,
    acoresCalhetaDeSaoJorgeCity,
    acoresCasteloBrancoCity,
    acoresCorvoCity,
    acoresFajaDeBaixoCity,
    acoresFenaisDaAjudaCity,
    acoresFenaisDaLuzCity,
    acoresFeteiraCity,
    acoresFonteBastardoCity,
    acoresFurnasCity,
    acoresHortaCity,
    acoresLagoaCity,
    acoresLajesCity,
    acoresLajesDasFloresCity,
    acoresLajesDoPicoCity,
    acoresMadalenaCity,
    acoresMaiaCity,
    acoresMosteirosCity,
    acoresNordesteCity,
    acoresPontaDelgadaCity,
    acoresPontaGarcaCity,
    acoresPortoJudeuCity,
    acoresPortoMartinsCity,
    acoresPovoacaoCity,
    acoresPraiaDaVitoriaCity,
    acoresRaboDePeixeCity,
    acoresRelvaCity,
    acoresRibeiraGrandeCity,
    acoresRibeiraSecaCity,
    acoresRibeirinhaCity,
    acoresRostoDeCaoCity,
    acoresSantaBarbaraCity,
    acoresSantaCruzDaGraciosaCity,
    acoresSantaCruzDasFloresCity,
    acoresSaoBartolomeuCity,
    acoresSaoMateusCity,
    acoresSaoRoqueCity,
    acoresSaoRoqueDoPicoCity,
    acoresSaoSebastiaoCity,
    acoresSaoVicenteCity,
    acoresSenhoraDoRosarioCity,
    acoresVelasCity,
    acoresVilaDoPortoCity,
    acoresVilaFrancaDoCampoCity
  ]);

/// The `Aveiro` region in `Portugal`
const Region portugalAveiro = Region(
  id: 2235,
  parentId: 177,
  longitude: -8.5721016,
  latitude: 40.7209023,
  name: "Aveiro",
  type: null,
  stateCode: "01",
  cities: [
    aveiroAguadaDeCimaCity,
    aveiroAguedaCity,
    aveiroAlbergariaHypaHypvelhaCity,
    aveiroAnadiaCity,
    aveiroAradasCity,
    aveiroArcosCity,
    aveiroArgoncilheCity,
    aveiroAroucaCity,
    aveiroArrifanaCity,
    aveiroAvancaCity,
    aveiroAveiroCity,
    aveiroBeduidoCity,
    aveiroBrancaCity,
    aveiroCasteloDePaivaCity,
    aveiroCortegacaCity,
    aveiroCucujaesCity,
    aveiroEixoCity,
    aveiroEsgueiraCity,
    aveiroEsmorizCity,
    aveiroEspargoCity,
    aveiroEspinhoCity,
    aveiroEstarrejaCity,
    aveiroFeiraCity,
    aveiroFiaesCity,
    aveiroGafanhaDaEncarnacaoCity,
    aveiroGafanhaDaNazareCity,
    aveiroIlhavoCity,
    aveiroLamasCity,
    aveiroLobaoCity,
    aveiroLourosaCity,
    aveiroLusoCity,
    aveiroMacieiraDeCambraCity,
    aveiroMealhadaCity,
    aveiroMilheirosDePoiaresCity,
    aveiroMosteiroCity,
    aveiroMurtosaCity,
    aveiroNogueiraDaRegedouraCity,
    aveiroOiaCity,
    aveiroOliveiraDeAzemeisCity,
    aveiroOliveiraDoBairroCity,
    aveiroOliveirinhaCity,
    aveiroOvarCity,
    aveiroPacosDeBrandaoCity,
    aveiroPampilhosaDoBotaoCity,
    aveiroPardilhoCity,
    aveiroRioMeaoCity,
    aveiroSalreuCity,
    aveiroSanfinsCity,
    aveiroSangalhosCity,
    aveiroSantaMariaDaFeiraCity,
    aveiroSaoJoaoCity,
    aveiroSaoJoaoDaMadeiraCity,
    aveiroSaoJoaoDeVerCity,
    aveiroSaoRoqueCity,
    aveiroSeverDoVougaCity,
    aveiroSilvaldeCity,
    aveiroSoutoCity,
    aveiroVagosCity,
    aveiroValeDeCambraCity,
    aveiroValegaCity,
    aveiroValongoCity,
    aveiroVilaChaCity
  ]);

/// The `Beja` region in `Portugal`
const Region portugalBeja = Region(
  id: 2230,
  parentId: 177,
  longitude: -7.87216,
  latitude: 37.9687786,
  name: "Beja",
  type: null,
  stateCode: "02",
  cities: [
    bejaAldeiaNovaDeSaoBentoCity,
    bejaAljustrelCity,
    bejaAlmodovarCity,
    bejaAlmograveCity,
    bejaAlvitoCity,
    bejaBarrancosCity,
    bejaBejaCity,
    bejaBeringelCity,
    bejaBoavistaDosPinheirosCity,
    bejaCabecaGordaCity,
    bejaCastroVerdeCity,
    bejaCubaCity,
    bejaFerreiraDoAlentejoCity,
    bejaMertolaCity,
    bejaMinasDeSaoDomingosCity,
    bejaMouraCity,
    bejaNevesCity,
    bejaOdemiraCity,
    bejaOuriqueCity,
    bejaPenedoGordoCity,
    bejaSalvadaCity,
    bejaSaoLuisCity,
    bejaSaoTeotonioCity,
    bejaSerpaCity,
    bejaVidigueiraCity,
    bejaVilaNovaDeMilfontesCity,
    bejaZambujeiraDoMarCity
  ]);

/// The `Braga` region in `Portugal`
const Region portugalBraga = Region(
  id: 2244,
  parentId: 177,
  longitude: -8.4261301,
  latitude: 41.550388,
  name: "Braga",
  type: null,
  stateCode: "03",
  cities: [
    bragaAdaufeCity,
    bragaAmaresCity,
    bragaApuliaCity,
    bragaApuliaEFaoCity,
    bragaArcosCity,
    bragaAroesCity,
    bragaAveledaCity,
    bragaBarcelosCity,
    bragaBarqueirosCity,
    bragaBragaCity,
    bragaBritoCity,
    bragaCabeceirasDeBastoCity,
    bragaCaldasDasTaipasCity,
    bragaCaldasDeVizelaCity,
    bragaCaldelasCity,
    bragaCalendarioCity,
    bragaCandosoCity,
    bragaCeloricoDeBastoCity,
    bragaChavaoCity,
    bragaCristeloCity,
    bragaEsporoesCity,
    bragaEsposendeCity,
    bragaFafeCity,
    bragaFariaCity,
    bragaFerreirosCity,
    bragaFradelosCity,
    bragaFrossosCity,
    bragaGalegosCity,
    bragaGandraCity,
    bragaGondizalvesCity,
    bragaGueralCity,
    bragaGuimaraesCity,
    bragaGuisandeCity,
    bragaJoaneCity,
    bragaLagoCity,
    bragaLordeloCity,
    bragaMacieiraDeRatesCity,
    bragaMarinhasCity,
    bragaMarizCity,
    bragaMerelimCity,
    bragaMoreiraDeConegosCity,
    bragaNegreirosCity,
    bragaOliveiraCity,
    bragaPerelhalCity,
    bragaPonteCity,
    bragaPovoaDeLanhosoCity,
    bragaPradoCity,
    bragaRealCity,
    bragaRefojosDeBastoCity,
    bragaRendufeCity,
    bragaRibaDeAveCity,
    bragaRibeiraoCity,
    bragaRonfeCity,
    bragaSandeCity,
    bragaSelhoCity,
    bragaSemelheCity,
    bragaSerzedeloCity,
    bragaSerzedoCity,
    bragaTebosaCity,
    bragaTerrasDeBouroCity,
    bragaUrgesesCity,
    bragaVarzeaCity,
    bragaVieiraDoMinhoCity,
    bragaVilaCovaCity,
    bragaVilaFrescainhaCity,
    bragaVilaNovaDeFamalicaoCity,
    bragaVilaSecaCity,
    bragaVilaVerdeCity,
    bragaVilacaCity,
    bragaVilarDeFigosCity,
    bragaVizelaCity
  ]);

/// The `Bragança` region in `Portugal`
const Region portugalBraganca = Region(
  id: 2229,
  parentId: 177,
  longitude: -6.7567427,
  latitude: 41.8061652,
  name: "Bragança",
  type: null,
  stateCode: "04",
  cities: [
    bragancaAlfandegaDaFeCity,
    bragancaBelverCity,
    bragancaBragancaMunicipalityCity,
    bragancaCarrazedaDeAnciaesCity,
    bragancaCarrazedaDeAnsiaesCity,
    bragancaFreixoDeEspadaACintaCity,
    bragancaMacedoDeCavaleirosCity,
    bragancaMirandaDoDouroCity,
    bragancaMirandelaCity,
    bragancaMogadouroCity,
    bragancaSamilCity,
    bragancaSendimCity,
    bragancaTorreDeMoncorvoCity,
    bragancaVilaFlorCity,
    bragancaVimiosoCity,
    bragancaVinhaisCity
  ]);

/// The `Castelo Branco` region in `Portugal`
const Region portugalCasteloBranco = Region(
  id: 2241,
  parentId: 177,
  longitude: -7.4814163,
  latitude: 39.8631323,
  name: "Castelo Branco",
  type: null,
  stateCode: "05",
  cities: [
    casteloBrancoAldeiaDeJoanesCity,
    casteloBrancoBelmonteCity,
    casteloBrancoCasteloBrancoCity,
    casteloBrancoCovilhaCity,
    casteloBrancoFundaoCity,
    casteloBrancoIdanhaHypaHypnovaCity,
    casteloBrancoOleirosCity,
    casteloBrancoPenamacorCity,
    casteloBrancoProencaHypaHypnovaCity,
    casteloBrancoSertaCity,
    casteloBrancoTeixosoCity,
    casteloBrancoVilaDeReiCity,
    casteloBrancoVilaVelhaDeRodaoCity
  ]);

/// The `Coimbra` region in `Portugal`
const Region portugalCoimbra = Region(
  id: 2246,
  parentId: 177,
  longitude: -8.41369,
  latitude: 40.2057994,
  name: "Coimbra",
  type: null,
  stateCode: "06",
  cities: [
    coimbraAlfarelosCity,
    coimbraAlhadasCity,
    coimbraAncaCity,
    coimbraArazedeCity,
    coimbraArganilCity,
    coimbraAssafargeCity,
    coimbraBuarcosCity,
    coimbraCantanhedeCity,
    coimbraCarapinheiraCity,
    coimbraCoimbraCity,
    coimbraCondeixaHypaHypnovaCity,
    coimbraFigueiraDaFozCity,
    coimbraGoisCity,
    coimbraLavosCity,
    coimbraLorvaoCity,
    coimbraLousaCity,
    coimbraMiraCity,
    coimbraMirandaDoCorvoCity,
    coimbraMontemorHypoHypvelhoCity,
    coimbraOliveiraDoHospitalCity,
    coimbraOliveiraDoMondegoCity,
    coimbraPampilhosaDaSerraCity,
    coimbraPenacovaCity,
    coimbraPenelaCity,
    coimbraPoiaresCity,
    coimbraSantaClaraCity,
    coimbraSantoAntonioDosOlivaisCity,
    coimbraSaoPedroDeAlvaCity,
    coimbraSoureCity,
    coimbraTabuaCity,
    coimbraTavaredeCity,
    coimbraTochaCity,
    coimbraTravancaCity,
    coimbraVilaNovaDePoiaresCity
  ]);

/// The `Évora` region in `Portugal`
const Region portugalEvora = Region(
  id: 2236,
  parentId: 177,
  longitude: -7.9076553,
  latitude: 38.5744468,
  name: "Évora",
  type: null,
  stateCode: "07",
  cities: [
    evoraAlandroalCity,
    evoraArraiolosCity,
    evoraBorbaCity,
    evoraEstremozCity,
    evoraEvoraCity,
    evoraMontemorHypoHypnovoCity,
    evoraMoraCity,
    evoraMouraoCity,
    evoraPortelCity,
    evoraRedondoCity,
    evoraReguengosDeMonsarazCity,
    evoraVendasNovasCity,
    evoraVianaDoAlentejoCity,
    evoraVilaVicosaCity
  ]);

/// The `Faro` region in `Portugal`
const Region portugalFaro = Region(
  id: 2239,
  parentId: 177,
  longitude: -7.9304397,
  latitude: 37.0193548,
  name: "Faro",
  type: null,
  stateCode: "08",
  cities: [
    faroAlbufeiraCity,
    faroAlcantarilhaCity,
    faroAlcoutimCity,
    faroAlgozCity,
    faroAljezurCity,
    faroAlmancilCity,
    faroAlturaCity,
    faroAlvorCity,
    faroArmacaoDePeraCity,
    faroBensafrimCity,
    faroBoliqueimeCity,
    faroCabanasDeTaviraCity,
    faroCarvoeiroCity,
    faroCastroMarimCity,
    faroConceicaoCity,
    faroEstoiCity,
    faroEstombarCity,
    faroFaroCity,
    faroFerragudoCity,
    faroFerreirasCity,
    faroFuzetaCity,
    faroGuiaCity,
    faroLagoaCity,
    faroLagosCity,
    faroLaranjeiroCity,
    faroLouleCity,
    faroLuzCity,
    faroMantaRotaCity,
    faroMarmeleteCity,
    faroMexilhoeiraGrandeCity,
    faroMoncarapachoCity,
    faroMonchiqueCity,
    faroMonteGordoCity,
    faroOlhaoCity,
    faroOlhosDeAguaCity,
    faroPaderneCity,
    faroParchalCity,
    faroPeraCity,
    faroPorchesCity,
    faroPortimaoCity,
    faroQuarteiraCity,
    faroSagresCity,
    faroSantaBarbaraDeNexeCity,
    faroSantaLuziaCity,
    faroSaoBartolomeuDeMessinesCity,
    faroSaoBrasDeAlportelCity,
    faroSaoMarcosDaSerraCity,
    faroSenhoraDaLuzCity,
    faroSilvesCity,
    faroTaviraCity,
    faroTunesCity,
    faroVilaDoBispoCity,
    faroVilaNovaDeCacelaCity,
    faroVilaRealDeSantoAntonioCity,
    faroVilamouraCity
  ]);

/// The `Guarda` region in `Portugal`
const Region portugalGuarda = Region(
  id: 4859,
  parentId: 177,
  longitude: -7.2675772,
  latitude: 40.5385972,
  name: "Guarda",
  type: null,
  stateCode: "09",
  cities: [
    guardaAbrigadaCity,
    guardaAcoresCity,
    guardaAdaoCity,
    guardaAgualvaCity,
    guardaAguasBelasCity,
    guardaAguiarDaBeiraCity,
    guardaAjudaCity,
    guardaAlbardoCity,
    guardaAlcabidecheCity,
    guardaAlcainsCity,
    guardaAlcantaraCity,
    guardaAlcoentreCity,
    guardaAldeiaDaPonteCity,
    guardaAldeiaDaRibeiraCity,
    guardaAldeiaDeSantoAntonioCity,
    guardaAldeiaDoBispoCity,
    guardaAldeiaGalegaDaMerceanaCity,
    guardaAldeiaGavinhaCity,
    guardaAldeiaNovaMirandaDoDouroCity,
    guardaAldeiaVelhaCity,
    guardaAldeiaVicosaCity,
    guardaAldeiasCity,
    guardaAlenquerCity,
    guardaAlfaiatesCity,
    guardaAlfornelosCity,
    guardaAlfragideCity,
    guardaAlgesCity,
    guardaAlgodresCity,
    guardaAlguberCity,
    guardaAlgueiraoCity,
    guardaAlgueiraomemMartinsCity,
    guardaAlhandraCity,
    guardaAlmargemCity,
    guardaAlmargemDoBispoCity,
    guardaAlmeidaCity,
    guardaAlmendraCity,
    guardaAlmofalaCity,
    guardaAltoDoPinaCity,
    guardaAlvaladeCity,
    guardaAlvendreCity,
    guardaAlvercaDaBeiraCity,
    guardaAlvercaDoRibatejoCity,
    guardaAlvocoDaSerraCity,
    guardaAmadoraCity,
    guardaAmeixoeiraCity,
    guardaAmoreiraCity,
    guardaAnjosCity,
    guardaApelacaoCity,
    guardaArcozeloCity,
    guardaArranhoCity,
    guardaArrifanaCity,
    guardaArrudaDosVinhosCity,
    guardaAtalaiaCity,
    guardaAveirasDeBaixoCity,
    guardaAveirasDeCimaCity,
    guardaAvelasDaRibeiraCity,
    guardaAvelosoCity,
    guardaAzambujaCity,
    guardaAzambujatownCity,
    guardaAzenhasDoMarCity,
    guardaAzevoCity,
    guardaAzueiraCity,
    guardaBaracalCity,
    guardaBarcarenaCity,
    guardaBarreiraCity,
    guardaBeatoCity,
    guardaBelasCity,
    guardaBendadaCity,
    guardaBenesperaCity,
    guardaBenficaCity,
    guardaBismulaCity,
    guardaBobadelaCity,
    guardaBoucaCovaCity,
    guardaBrandoaCity,
    guardaBucelasCity,
    guardaBuracaCity,
    guardaCabanasDeTorresCity,
    guardaCabecaCity,
    guardaCacemCity,
    guardaCachoeirasCity,
    guardaCadafaisCity,
    guardaCadafazCity,
    guardaCadavalCity,
    guardaCalhandrizCity,
    guardaCamarateCity,
    guardaCampelosCity,
    guardaCampoGrandeCity,
    guardaCampolideCity,
    guardaCanecasCity,
    guardaCarapitoCity,
    guardaCarcavelosCity,
    guardaCardosasCity,
    guardaCarmoesCity,
    guardaCarnaxideCity,
    guardaCarnicaesCity,
    guardaCarnideCity,
    guardaCarnotaCity,
    guardaCarragozelaCity,
    guardaCarrapichanaCity,
    guardaCarregadoCity,
    guardaCarvalhalCity,
    guardaCarvoeiraCity,
    guardaCasalDeCambraCity,
    guardaCasalDeCinzaCity,
    guardaCasalVascoCity,
    guardaCasasDoSoeiroCity,
    guardaCascaisCity,
    guardaCastanheiraCity,
    guardaCastanheiraDoRibatejoCity,
    guardaCasteicaoCity,
    guardaCasteleiroCity,
    guardaCastelolisbonCity,
    guardaCasteloBomCity,
    guardaCasteloMelhorCity,
    guardaCasteloRodrigoCity,
    guardaCativelosCity,
    guardaCavadoudeCity,
    guardaCaxiasCity,
    guardaCedovimCity,
    guardaCeloricoDaBeiraCity,
    guardaCercalCity,
    guardaCerdeiraCity,
    guardaCerejoCity,
    guardaCharnecaCity,
    guardaChasCity,
    guardaCheleirosCity,
    guardaCodesseiroCity,
    guardaCogulaCity,
    guardaColaresCity,
    guardaCoracaoDeJesusCity,
    guardaCoriscadaCity,
    guardaCorticadaCity,
    guardaCorticoCity,
    guardaCorticoDaSerraCity,
    guardaCorucheCity,
    guardaCorujeiraCity,
    guardaCotimosCity,
    guardaCruzQuebradaHypDafundoCity,
    guardaCustoiasCity,
    guardaDamaiaCity,
    guardaDoisPortosCity,
    guardaDornelasCity,
    guardaEiradoCity,
    guardaEncarnacaoCity,
    guardaEnxaraDoBispoCity,
    guardaEriceiraCity,
    guardaErvasTenrasCity,
    guardaErvedosaCity,
    guardaEscalhaoCity,
    guardaEstorilCity,
    guardaFaiaCity,
    guardaFalagueiraCity,
    guardaFamalicaoCity,
    guardaFamoesCity,
    guardaFanhoesCity,
    guardaFernaoJoanesCity,
    guardaFiaesCity,
    guardaFigueiraDeCasteloRodrigoCity,
    guardaFigueiraDoGuinchoCity,
    guardaFigueiroDaGranjaCity,
    guardaFigueiroDaSerraCity,
    guardaFigueirosCity,
    guardaFoiosCity,
    guardaFolgosinhoCity,
    guardaFolhadosaCity,
    guardaFontanelasCity,
    guardaFonteLongaCity,
    guardaForninhosCity,
    guardaFornoTelheiroCity,
    guardaFornosDeAlgodresCity,
    guardaForteDaCasaCity,
    guardaFrechesCity,
    guardaFreinedaCity,
    guardaFreiriaCity,
    guardaFreixedaDoTorraoCity,
    guardaFreixedasCity,
    guardaFreixoCity,
    guardaFreixoDeNumaoCity,
    guardaFrielasCity,
    guardaGagosCity,
    guardaGirabolhosCity,
    guardaGoncaloCity,
    guardaGoncaloBocasCity,
    guardaGouveiaCity,
    guardaGracaCity,
    guardaGradilCity,
    guardaGradizCity,
    guardaGranjaCity,
    guardaGuardaCity,
    guardaGuilheiroCity,
    guardaHortaCity,
    guardaIgrejaNovaCity,
    guardaInfiasCity,
    guardaJarmeloSaoMiguelCity,
    guardaJarmeloSaoPedroCity,
    guardaJoaoAntaoCity,
    guardaJuncaCity,
    guardaJuncaisCity,
    guardaLagarinhosCity,
    guardaLajeosaCity,
    guardaLajeosaDoMondegoCity,
    guardaLajesCity,
    guardaLamasCity,
    guardaLamegalCity,
    guardaLameirasCity,
    guardaLapaCity,
    guardaLapaDosDinheirosCity,
    guardaLeomilCity,
    guardaLindaHypaHypvelhaCity,
    guardaLinharesceloricoDaBeiraCity,
    guardaLisbonCity,
    guardaLongroivaCity,
    guardaLorigaCity,
    guardaLouresCity,
    guardaLourinhaCity,
    guardaLousaCity,
    guardaLumiarCity,
    guardaMacainhasCity,
    guardaMacalDoChaoCity,
    guardaMaceiraCity,
    guardaMacussaCity,
    guardaMadalenaCity,
    guardaMafraCity,
    guardaMalcataCity,
    guardaMalhadaSordaCity,
    guardaMalpartidaCity,
    guardaMalveiraCity,
    guardaMangualdeDaSerraCity,
    guardaManigotoCity,
    guardaManiqueDoIntendenteCity,
    guardaManteigasCity,
    guardaManteigassaoPedroCity,
    guardaMarialvaCity,
    guardaMarmeleiroCity,
    guardaMarteleiraCity,
    guardaMartiresCity,
    guardaMarvilaCity,
    guardaMassamaCity,
    guardaMataDeLobosCity,
    guardaMatacaesCity,
    guardaMatancaCity,
    guardaMaxialCity,
    guardaMecaCity,
    guardaMedaCity,
    guardaMeiosCity,
    guardaMeloCity,
    guardaMemMartinsCity,
    guardaMercesCity,
    guardaMesquitelaCity,
    guardaMilharadoCity,
    guardaMinaCity,
    guardaMinhocalCity,
    guardaMiraHypsintraCity,
    guardaMiragaiaCity,
    guardaMiuzelaCity,
    guardaMizarelaCity,
    guardaMoimentaDaSerraCity,
    guardaMoimentinhaCity,
    guardaMoitaCity,
    guardaMoitaDosFerreirosCity,
    guardaMoledoCity,
    guardaMonteAbraaoCity,
    guardaMonteEstorilCity,
    guardaMonteRedondoCity,
    guardaMontelavarCity,
    guardaMoreiraDeReiCity,
    guardaMosCity,
    guardaMoscavideCity,
    guardaMurcaCity,
    guardaMuxagataCity,
    guardaNabaisCity,
    guardaNaveCity,
    guardaNaveDeHaverCity,
    guardaNespereiraCity,
    guardaNossaSenhoraDeFatimaCity,
    guardaNumaoCity,
    guardaOdivelasCity,
    guardaOdivelasMunicipalityCity,
    guardaOeirasCity,
    guardaOeirasESaoJuliaoDaBarraCity,
    guardaOlhalvoCity,
    guardaOlivalDeBastoCity,
    guardaOlivalDoBastoCity,
    guardaOtaCity,
    guardaOuteiroDaCabecaCity,
    guardaOuteiroDeGatosCity,
    guardaPacoDeArcosCity,
    guardaPacosDaSerraCity,
    guardaPainhoCity,
    guardaPalaCity,
    guardaPalhaisCity,
    guardaPanoiasDeCimaCity,
    guardaParadaCity,
    guardaParanhosCity,
    guardaParedeCity,
    guardaPegaCity,
    guardaPenaCity,
    guardaPenaLoboCity,
    guardaPenaVerdeCity,
    guardaPenhaDeAguiaCity,
    guardaPenhaDeFrancaCity,
    guardaPeraDoMocoCity,
    guardaPeralCity,
    guardaPereiroCity,
    guardaPereiroDePalhacanaCity,
    guardaPeroMonizCity,
    guardaPeroPinheiroCity,
    guardaPevaCity,
    guardaPinhancosCity,
    guardaPinheiroCity,
    guardaPinhelCity,
    guardaPinzioCity,
    guardaPocoDoCantoCity,
    guardaPomaresCity,
    guardaPonteDoRolCity,
    guardaPontinhaCity,
    guardaPortelaCity,
    guardaPortoDaCarneCity,
    guardaPortoSalvoCity,
    guardaPousadaCity,
    guardaPousafolesDoBispoCity,
    guardaPovoaDeSantaIriaCity,
    guardaPovoaDeSantoAdriaoCity,
    guardaPovoaDoConcelhoCity,
    guardaPradosCity,
    guardaPrazeresCity,
    guardaPriorVelhoCity,
    guardaProvaCity,
    guardaQuadrazaisCity,
    guardaQueijasCity,
    guardaQueirizCity,
    guardaQueluzCity,
    guardaQuintaDePeroMartinsCity,
    guardaQuintasDeSaoBartolomeuCity,
    guardaRabacalCity,
    guardaRamadaCity,
    guardaRamalhalCity,
    guardaRamelaCity,
    guardaRanhadosCity,
    guardaRapaCity,
    guardaRapoulaDoCoaCity,
    guardaRatoeiraCity,
    guardaReboleiraCity,
    guardaReboleiroCity,
    guardaRebolosaCity,
    guardaReguengoGrandeCity,
    guardaReigadaCity,
    guardaRendoCity,
    guardaRibafriaCity,
    guardaRibamarCity,
    guardaRibamondegoCity,
    guardaRibeiraDosCarinhosCity,
    guardaRioDeMelCity,
    guardaRioDeMouroCity,
    guardaRioTortoCity,
    guardaRochosoCity,
    guardaRunaCity,
    guardaRuvinaCity,
    guardaSabugalCity,
    guardaSabugueiroCity,
    guardaSacavemCity,
    guardaSacramentoCity,
    guardaSafurdaoCity,
    guardaSalgueiraisCity,
    guardaSameiceCity,
    guardaSameiroCity,
    guardaSandomilCity,
    guardaSantaBarbaraCity,
    guardaSantaCatarinaCity,
    guardaSantaCombaCity,
    guardaSantaEngraciaCity,
    guardaSantaEufemiaCity,
    guardaSantaEulaliaCity,
    guardaSantaIriaDaAzoiaCity,
    guardaSantaIriaDeAzoiaCity,
    guardaSantaIsabelCity,
    guardaSantaJustaCity,
    guardaSantaMariaCity,
    guardaSantaMariaDeBelemCity,
    guardaSantaMariaDoCasteloESaoMiguelCity,
    guardaSantaMariaDosOlivaisCity,
    guardaSantaMariaESaoMiguelCity,
    guardaSantaMarinhaCity,
    guardaSantanaDaAzinhaCity,
    guardaSantiagoCity,
    guardaSantiagoDosVelhosCity,
    guardaSantoAntaoDoTojalCity,
    guardaSantoAntonioDosCavaleirosCity,
    guardaSantoCondestavelCity,
    guardaSantoEstevaoCity,
    guardaSantoEstevaoDasGalesCity,
    guardaSantoIsidoroCity,
    guardaSantoQuintinoCity,
    guardaSantosHypoHypvelhoCity,
    guardaSaoBartolomeuCity,
    guardaSaoBartolomeuDosGalegosCity,
    guardaSaoBrasCity,
    guardaSaoCristovaoESaoLourencoCity,
    guardaSaoDomingosDeBenficaCity,
    guardaSaoDomingosDeRanaCity,
    guardaSaoFranciscoXavierCity,
    guardaSaoJoaoCity,
    guardaSaoJoaoDaTalhaCity,
    guardaSaoJoaoDasLampasCity,
    guardaSaoJoaoDeBritoCity,
    guardaSaoJoaoDeDeusCity,
    guardaSaoJoaoDosMontesCity,
    guardaSaoJorgeDeArroiosCity,
    guardaSaoJoseCity,
    guardaSaoJuliaoCity,
    guardaSaoJuliaoDoTojalCity,
    guardaSaoMamedeCity,
    guardaSaoMarcosCity,
    guardaSaoMartinhoCity,
    guardaSaoMiguelCity,
    guardaSaoMiguelDaGuardaCity,
    guardaSaoMiguelDeAlcaincaCity,
    guardaSaoNicolauCity,
    guardaSaoPaioCity,
    guardaSaoPauloCity,
    guardaSaoPedroCity,
    guardaSaoPedroDaCadeiraCity,
    guardaSaoPedroDePenaferrimCity,
    guardaSaoPedroDeRioSecoCity,
    guardaSaoRomaoCity,
    guardaSaoSebastiaoDaPedreiraCity,
    guardaSaoVicenteCity,
    guardaSaoVicenteDeForaCity,
    guardaSapatariaCity,
    guardaSazesDaBeiraCity,
    guardaSeCity,
    guardaSebadelheCity,
    guardaSebadelheDaSerraCity,
    guardaSeiaCity,
    guardaSeixasCity,
    guardaSeixoDoCoaCity,
    guardaSequeiraCity,
    guardaSequeirosCity,
    guardaSilveiraCity,
    guardaSintraCity,
    guardaSintratownCity,
    guardaSobralDaAbelheiraCity,
    guardaSobralDaSerraCity,
    guardaSobralDeMonteAgracoCity,
    guardaSobralPichorroCity,
    guardaSobralinhoCity,
    guardaSocorroCity,
    guardaSortelhaCity,
    guardaSouroPiresCity,
    guardaSoutoCity,
    guardaSoutoDeAguiarDaBeiraCity,
    guardaSoutoMaiorCity,
    guardaTamanhosCity,
    guardaTeixeiraCity,
    guardaTerrenhoCity,
    guardaTerrugemCity,
    guardaTorreDoTerrenhoCity,
    guardaTorresCity,
    guardaTorresVedrasCity,
    guardaTorrozeloCity,
    guardaToucaCity,
    guardaTouraisCity,
    guardaTrancosoCity,
    guardaTravancinhaCity,
    guardaTrianaCity,
    guardaTrintaCity,
    guardaTurcifalCity,
    guardaUnhosCity,
    guardaValbomCity,
    guardaValdujoCity,
    guardaValeDaMulaCity,
    guardaValeDeAmoreiraCity,
    guardaValeDeAzaresCity,
    guardaValeDeEspinhoCity,
    guardaValeDeEstrelaCity,
    guardaValeDoParaisoCity,
    guardaValeDoSeixoCity,
    guardaValeFlorCity,
    guardaValezimCity,
    guardaValhelhasCity,
    guardaValverdeCity,
    guardaVarzeaDeMerugeCity,
    guardaVascoveiroCity,
    guardaVelaCity,
    guardaVelosaCity,
    guardaVendaDoPinheiroCity,
    guardaVendaNovaCity,
    guardaVenteiraCity,
    guardaVentosaCity,
    guardaVermelhaCity,
    guardaVermiosaCity,
    guardaVialongaCity,
    guardaVideCity,
    guardaVideEntreVinhasCity,
    guardaVidemonteCity,
    guardaVilaBoaCity,
    guardaVilaBoaDoMondegoCity,
    guardaVilaCortesDaSerraCity,
    guardaVilaCortesDoMondegoCity,
    guardaVilaCovaACoelheiraCity,
    guardaVilaDoTouroCity,
    guardaVilaFernandoCity,
    guardaVilaFrancaDaSerraCity,
    guardaVilaFrancaDasNavesCity,
    guardaVilaFrancaDeXiraCity,
    guardaVilaFrancaDoDeaoCity,
    guardaVilaFrancaDoRosarioCity,
    guardaVilaGarciaCity,
    guardaVilaNovaDaRainhaCity,
    guardaVilaNovaDeFozCoaCity,
    guardaVilaNovaDeSaoPedroCity,
    guardaVilaNovaDeTazemCity,
    guardaVilaRuivaCity,
    guardaVilaSoeiroDoChaoCity,
    guardaVilaVerdeCity,
    guardaVilaVerdeDosFrancosCity,
    guardaVilarCity,
    guardaVilarDeAmargoCity,
    guardaVilarFormosoCity,
    guardaVilarMaiorCity,
    guardaVilarTorpimCity,
    guardaVilaresCity,
    guardaVimeiroCity,
    guardaVinhoCity
  ]);

/// The `Leiria` region in `Portugal`
const Region portugalLeiria = Region(
  id: 2240,
  parentId: 177,
  longitude: -8.7921836,
  latitude: 39.7709532,
  name: "Leiria",
  type: null,
  stateCode: "10",
  cities: [
    leiriaADosFrancosCity,
    leiriaAlcobacaCity,
    leiriaAlfeizeraoCity,
    leiriaAljubarrotaCity,
    leiriaAlvaiazereCity,
    leiriaAlvorninhaCity,
    leiriaAmorCity,
    leiriaAnsiaoCity,
    leiriaAtouguiaDaBaleiaCity,
    leiriaBatalhaCity,
    leiriaBeneditaCity,
    leiriaBombarralCity,
    leiriaCaldasDaRainhaCity,
    leiriaCaranguejeiraCity,
    leiriaCastanheiraDePeraCity,
    leiriaCelaCity,
    leiriaFamalicaoCity,
    leiriaFerrelCity,
    leiriaFigueiroDosVinhosCity,
    leiriaFozDoArelhoCity,
    leiriaLeiriaCity,
    leiriaLouricalCity,
    leiriaMaceiraCity,
    leiriaMarinhaGrandeCity,
    leiriaMiraCity,
    leiriaMonteRealCity,
    leiriaMonteRedondoCity,
    leiriaNadadouroCity,
    leiriaNazareCity,
    leiriaObidosCity,
    leiriaPataiasCity,
    leiriaPedrogaoGrandeCity,
    leiriaPenicheCity,
    leiriaPombalCity,
    leiriaPortoDeMosCity,
    leiriaSalirDeMatosCity,
    leiriaSantaCatarinaDaSerraCity,
    leiriaSaoMartinhoDoPortoCity,
    leiriaSerraDeElHypreiCity,
    leiriaSoutoDaCarpalhosaCity,
    leiriaTurquelCity,
    leiriaValadoDeFradesCity,
    leiriaVestiariaCity,
    leiriaVidaisCity,
    leiriaVieiraDeLeiriaCity
  ]);

/// The `Lisbon` region in `Portugal`
const Region portugalLisbon = Region(
  id: 2228,
  parentId: 177,
  longitude: -9.1392714,
  latitude: 38.7223263,
  name: "Lisbon",
  type: null,
  stateCode: "11",
  cities: [
    lisbonADosCunhadosCity,
    lisbonAbrigadaCity,
    lisbonAlcabidecheCity,
    lisbonAlcoentreCity,
    lisbonAlenquerCity,
    lisbonAlfragideCity,
    lisbonAlgesCity,
    lisbonAlgueiraoCity,
    lisbonAlhandraCity,
    lisbonAlmargemCity,
    lisbonAlvaladeCity,
    lisbonAmadoraCity,
    lisbonApelacaoCity,
    lisbonArranhoCity,
    lisbonArrudaDosVinhosCity,
    lisbonAveirasDeCimaCity,
    lisbonAzambujaCity,
    lisbonBarcarenaCity,
    lisbonBeatoAntonioCity,
    lisbonBelasCity,
    lisbonBenficaCity,
    lisbonBobadelaCity,
    lisbonBucelasCity,
    lisbonCabanasDeTorresCity,
    lisbonCacemCity,
    lisbonCadafaisCity,
    lisbonCadavalCity,
    lisbonCamarateCity,
    lisbonCampelosCity,
    lisbonCanecasCity,
    lisbonCarcavelosCity,
    lisbonCarnaxideCity,
    lisbonCarregadoCity,
    lisbonCascaisCity,
    lisbonCastanheiraDoRibatejoCity,
    lisbonCaxiasCity,
    lisbonCharnecaCity,
    lisbonColaresCity,
    lisbonEriceiraCity,
    lisbonEstorilCity,
    lisbonFamoesCity,
    lisbonFontanelasCity,
    lisbonLindaHypaHypvelhaCity,
    lisbonLisbonCity,
    lisbonLouresCity,
    lisbonLourinhaCity,
    lisbonMafraCity,
    lisbonMalveiraCity,
    lisbonMassamaCity,
    lisbonMecaCity,
    lisbonMemMartinsCity,
    lisbonMilharadoCity,
    lisbonMoitaDosFerreirosCity,
    lisbonMonteEstorilCity,
    lisbonMoscavideEPortelaCity,
    lisbonOdivelasCity,
    lisbonOeirasCity,
    lisbonOlivaisCity,
    lisbonOlivalDoBastoCity,
    lisbonOtaCity,
    lisbonPacoDeArcosCity,
    lisbonParedeCity,
    lisbonPeroPinheiroCity,
    lisbonPontinhaCity,
    lisbonPortoSalvoCity,
    lisbonPovoaDeSantaIriaCity,
    lisbonPovoaDeSantoAdriaoCity,
    lisbonPriorVelhoCity,
    lisbonQueijasCity,
    lisbonQueluzCity,
    lisbonRamadaCity,
    lisbonRioDeMouroCity,
    lisbonSacavemCity,
    lisbonSantaIriaDaAzoiaCity,
    lisbonSantoAntaoDoTojalCity,
    lisbonSantoIsidoroCity,
    lisbonSantosHypoHypvelhoCity,
    lisbonSaoBartolomeuCity,
    lisbonSaoDomingosDeRanaCity,
    lisbonSaoJoaoDaTalhaCity,
    lisbonSaoJoaoDasLampasCity,
    lisbonSaoJoaoDosMontesCity,
    lisbonSaoPedroDaCadeiraCity,
    lisbonSilveiraCity,
    lisbonSintraCity,
    lisbonSobralDeMonteAgracoCity,
    lisbonSobralinhoCity,
    lisbonTerrugemCity,
    lisbonTorresVedrasCity,
    lisbonUnhosCity,
    lisbonVendaDoPinheiroCity,
    lisbonVentosaCity,
    lisbonVialongaCity,
    lisbonVilaFrancaDeXiraCity,
    lisbonVilaVerdeCity,
    lisbonVimeiroCity
  ]);

/// The `Madeira` region in `Portugal`
const Region portugalMadeira = Region(
  id: 2231,
  parentId: 177,
  longitude: -16.9594723,
  latitude: 32.7607074,
  name: "Madeira",
  type: null,
  stateCode: "30",
  cities: [
    madeiraAguaDePenaCity,
    madeiraArcoDaCalhetaCity,
    madeiraBoaventuraCity,
    madeiraCalhetaCity,
    madeiraCamachaCity,
    madeiraCamaraDeLobosCity,
    madeiraCampanarioCity,
    madeiraCanhasCity,
    madeiraCanicalCity,
    madeiraCanicoCity,
    madeiraCurralDasFreirasCity,
    madeiraEstreitoDaCalhetaCity,
    madeiraFaialCity,
    madeiraFajaDaOvelhaCity,
    madeiraFunchalCity,
    madeiraMachicoCity,
    madeiraNossaSenhoraDoMonteCity,
    madeiraPontaDoSolCity,
    madeiraPortoDaCruzCity,
    madeiraPortoMonizCity,
    madeiraPortoSantoCity,
    madeiraRibeiraBravaCity,
    madeiraSantaCruzCity,
    madeiraSantanaCity,
    madeiraSaoJorgeCity,
    madeiraSaoMartinhoCity,
    madeiraSaoRoqueCity,
    madeiraSaoVicenteCity
  ]);

/// The `Portalegre` region in `Portugal`
const Region portugalPortalegre = Region(
  id: 2232,
  parentId: 177,
  longitude: -7.4284755,
  latitude: 39.2967086,
  name: "Portalegre",
  type: null,
  stateCode: "12",
  cities: [
    portalegreAlterDoChaoCity,
    portalegreArronchesCity,
    portalegreAtalaiaCity,
    portalegreAvisCity,
    portalegreCampoMaiorCity,
    portalegreCasteloDeVideCity,
    portalegreCratoCity,
    portalegreElvasCity,
    portalegreFronteiraCity,
    portalegreGaviaoCity,
    portalegreMarvaoCity,
    portalegreMonforteCity,
    portalegreMontargilCity,
    portalegreNisaCity,
    portalegrePonteDeSorCity,
    portalegrePortalegreCity,
    portalegreSantoAndreCity,
    portalegreSouselCity,
    portalegreValeDaAmoreiraCity
  ]);

/// The `Porto` region in `Portugal`
const Region portugalPorto = Region(
  id: 2243,
  parentId: 177,
  longitude: -8.6078973,
  latitude: 41.1476629,
  name: "Porto",
  type: null,
  stateCode: "13",
  cities: [
    portoAguaLongaCity,
    portoAguasSantasCity,
    portoAgucadouraCity,
    portoAlfenaCity,
    portoAlpenduradaCity,
    portoAmaranteCity,
    portoAmorimCity,
    portoAntaCity,
    portoArcozeloCity,
    portoArgivaiCity,
    portoArvoreCity,
    portoAverHypoHypmarCity,
    portoAvesCity,
    portoAvintesCity,
    portoAzenhaCity,
    portoBaguimDoMonteCity,
    portoBaiaoCity,
    portoBalazarCity,
    portoBaltarCity,
    portoBarrosasCity,
    portoBeirizDeBaixoCity,
    portoBougadoCity,
    portoCampoCity,
    portoCanelasCity,
    portoCanideloCity,
    portoCarvalhosaCity,
    portoCasteloesDeCepedaCity,
    portoErmesindeCity,
    portoEstelaCity,
    portoFanzeresCity,
    portoFelgueirasCity,
    portoFerreiraCity,
    portoFigueiroCity,
    portoFozDoDouroCity,
    portoFozDoSousaCity,
    portoFrazaoCity,
    portoFreamundeCity,
    portoGandraCity,
    portoGemundeCity,
    portoGondomarCity,
    portoGrijoCity,
    portoGuifoesCity,
    portoGulpilharesCity,
    portoJovimCity,
    portoLavraCity,
    portoLecaDaPalmeiraCity,
    portoLecaDoBailioCity,
    portoLordeloCity,
    portoLousadaCity,
    portoLustosaCity,
    portoMadalenaCity,
    portoMaiaCity,
    portoMarcoDeCanavesesCity,
    portoMarcoDeCanavezesCity,
    portoMargarideCity,
    portoMatosinhosCity,
    portoMeinedoCity,
    portoMelresCity,
    portoMilheirosCity,
    portoMindeloCity,
    portoMoreiraCity,
    portoNegrelosCity,
    portoNogueiraCity,
    portoOlivalCity,
    portoOliveiraDoDouroCity,
    portoPacosDeFerreiraCity,
    portoParedesCity,
    portoPedrosoCity,
    portoPedroucosCity,
    portoPenafielCity,
    portoPerafitaCity,
    portoPerozinhoCity,
    portoPortoCity,
    portoPovoaDeVarzimCity,
    portoRebordoesCity,
    portoRebordosaCity,
    portoRecareiCity,
    portoRioMauCity,
    portoRioTintoCity,
    portoSandimCity,
    portoSantaCruzDoBispoCity,
    portoSantoIzidoroCity,
    portoSantoTirsoCity,
    portoSaoFelixDaMarinhaCity,
    portoSaoMamedeDeInfestaCity,
    portoSaoMiguelDoCoutoCity,
    portoSaoPedroDaCovaCity,
    portoSaoRomaoDoCoronadoCity,
    portoSenhoraDaHoraCity,
    portoSermondeCity,
    portoSeroaCity,
    portoSerzedoCity,
    portoSobradoCity,
    portoTeloesCity,
    portoTrofaCity,
    portoVairaoCity,
    portoValadaresCity,
    portoValbomCity,
    portoValongoCity,
    portoVilaDoCondeCity,
    portoVilaMeaCity,
    portoVilaNovaDaTelhaCity,
    portoVilaNovaDeGaiaCity,
    portoVilarDeAndorinhoCity,
    portoVilarDoParaisoCity,
    portoVilarinhoCity,
    portoVizelaCity
  ]);

/// The `Santarém` region in `Portugal`
const Region portugalSantarem = Region(
  id: 2238,
  parentId: 177,
  longitude: -8.6859944,
  latitude: 39.2366687,
  name: "Santarém",
  type: null,
  stateCode: "14",
  cities: [
    santaremAbrantesCity,
    santaremAlcanedeCity,
    santaremAlcanenaCity,
    santaremAlcanhoesCity,
    santaremAlferraredeCity,
    santaremAlmeirimCity,
    santaremAlpiarcaCity,
    santaremAmiaesDeBaixoCity,
    santaremAzinhagaCity,
    santaremBemficaCity,
    santaremBenaventeCity,
    santaremCartaxoCity,
    santaremChamuscaCity,
    santaremConstanciaCity,
    santaremCorucheCity,
    santaremEntroncamentoCity,
    santaremFatimaCity,
    santaremFazendasDeAlmeirimCity,
    santaremFerreiraDoZezereCity,
    santaremGolegaCity,
    santaremMacaoCity,
    santaremMadalenaCity,
    santaremMarinhaisCity,
    santaremMindeCity,
    santaremMonsantoCity,
    santaremMontalvinhoCity,
    santaremMontalvoCity,
    santaremOuremCity,
    santaremPaialvoCity,
    santaremPegoCity,
    santaremPinheiroGrandeCity,
    santaremPoceiraoCity,
    santaremPontevelCity,
    santaremPraiaDoRibatejoCity,
    santaremRiachosCity,
    santaremRioMaiorCity,
    santaremSalvaterraDeMagosCity,
    santaremSamoraCorreiaCity,
    santaremSantaMargaridaDaCoutadaCity,
    santaremSantaremCity,
    santaremSaoMiguelDeRioTortoCity,
    santaremSaoVicenteDoPaulCity,
    santaremSardoalCity,
    santaremTomarCity,
    santaremTorresNovasCity,
    santaremTramagalCity,
    santaremValeDeFigueiraCity,
    santaremValeDeSantaremCity,
    santaremVilaChaDeOuriqueCity,
    santaremVilaNovaDaBarquinhaCity
  ]);

/// The `Setúbal` region in `Portugal`
const Region portugalSetubal = Region(
  id: 2242,
  parentId: 177,
  longitude: -8.8925876,
  latitude: 38.5240933,
  name: "Setúbal",
  type: null,
  stateCode: "15",
  cities: [
    setubalAlcacerDoSalCity,
    setubalAlcocheteCity,
    setubalAldeiaDePaioPiresCity,
    setubalAlhosVedrosCity,
    setubalAlmadaCity,
    setubalAmoraCity,
    setubalArrentelaCity,
    setubalAzeitaoCity,
    setubalBarreiroCity,
    setubalCacilhasCity,
    setubalCaparicaCity,
    setubalCercalCity,
    setubalCharnecaDeCaparicaCity,
    setubalComportaCity,
    setubalCorroiosCity,
    setubalCostaDeCaparicaCity,
    setubalGrandolaCity,
    setubalLaranjeiraCity,
    setubalLavradioCity,
    setubalMoitaCity,
    setubalMontijoCity,
    setubalPalmelaCity,
    setubalPiedadeCity,
    setubalPinhalNovoCity,
    setubalPortoCovoCity,
    setubalPragalCity,
    setubalQuintaDoAnjoCity,
    setubalQuintaDoCondeCity,
    setubalRosairinhoCity,
    setubalSamoucoCity,
    setubalSantiagoDoCacemCity,
    setubalSantoAndreCity,
    setubalSantoAntonioDaCharnecaCity,
    setubalSarilhosPequenosCity,
    setubalSeixalCity,
    setubalSesimbraCity,
    setubalSetubalCity,
    setubalSinesCity,
    setubalSobredaCity,
    setubalTrafariaCity
  ]);

/// The `Viana do Castelo` region in `Portugal`
const Region portugalVianaDoCastelo = Region(
  id: 2245,
  parentId: 177,
  longitude: -8.834451,
  latitude: 41.6918046,
  name: "Viana do Castelo",
  type: null,
  stateCode: "16",
  cities: [
    vianaDoCasteloArcosDeValdevezCity,
    vianaDoCasteloCaminhaCity,
    vianaDoCasteloMelgacoCity,
    vianaDoCasteloMoncaoCity,
    vianaDoCasteloParedesDeCouraCity,
    vianaDoCasteloPonteDaBarcaCity,
    vianaDoCasteloPonteDeLimaCity,
    vianaDoCasteloValencaCity,
    vianaDoCasteloVianaDoCasteloCity
  ]);

/// The `Vila Real` region in `Portugal`
const Region portugalVilaReal = Region(
  id: 2234,
  parentId: 177,
  longitude: -7.7457274,
  latitude: 41.3003527,
  name: "Vila Real",
  type: null,
  stateCode: "17",
  cities: [
    vilaRealAlijoCity,
    vilaRealBoticasCity,
    vilaRealChavesCity,
    vilaRealFavaiosCity,
    vilaRealGodimCity,
    vilaRealMesaoFrioCity,
    vilaRealMondimDeBastoCity,
    vilaRealMontalegreCity,
    vilaRealMurcaCity,
    vilaRealPesoDaReguaCity,
    vilaRealRibeiraDePenaCity,
    vilaRealSabrosaCity,
    vilaRealSantaCruzCity,
    vilaRealSantaMartaDePenaguiaoCity,
    vilaRealSobreiraCity,
    vilaRealValpacosCity,
    vilaRealVilaPoucaDeAguiarCity,
    vilaRealVilaRealCity,
    vilaRealVilelaCity
  ]);

/// The `Viseu` region in `Portugal`
const Region portugalViseu = Region(
  id: 2237,
  parentId: 177,
  longitude: -7.914756,
  latitude: 40.6588424,
  name: "Viseu",
  type: null,
  stateCode: "18",
  cities: [
    viseuAbravesesCity,
    viseuArmamarCity,
    viseuCabanasDeViriatoCity,
    viseuCampoCity,
    viseuCampoDeBesteirosCity,
    viseuCanasDeSenhorimCity,
    viseuCarregalDoSalCity,
    viseuCastroDaireCity,
    viseuCinfaesCity,
    viseuErvedosaDoDouroCity,
    viseuLamegoCity,
    viseuMangualdeCity,
    viseuMoimentaDaBeiraCity,
    viseuMortaguaCity,
    viseuNelasCity,
    viseuOliveiraDeFradesCity,
    viseuPenalvaDoCasteloCity,
    viseuPenedonoCity,
    viseuResendeCity,
    viseuRioDeLobaCity,
    viseuSantaCombaDaoCity,
    viseuSaoJoaoDaPesqueiraCity,
    viseuSaoJoaoDeAreiasCity,
    viseuSaoPedroDoSulCity,
    viseuSataoCity,
    viseuSernancelheCity,
    viseuTabuacoCity,
    viseuTaroucaCity,
    viseuTondelaCity,
    viseuTreixedoCity,
    viseuVilaNovaDePaivaCity,
    viseuViseuCity,
    viseuVouzelaCity
  ]);

/// The 20 states of `Portugal` keyed by their id.
const Map<int, Region> portugalStates = <int, Region>{
    2233: portugalAcores,
    2235: portugalAveiro,
    2230: portugalBeja,
    2244: portugalBraga,
    2229: portugalBraganca,
    2241: portugalCasteloBranco,
    2246: portugalCoimbra,
    2236: portugalEvora,
    2239: portugalFaro,
    4859: portugalGuarda,
    2240: portugalLeiria,
    2228: portugalLisbon,
    2231: portugalMadeira,
    2232: portugalPortalegre,
    2243: portugalPorto,
    2238: portugalSantarem,
    2242: portugalSetubal,
    2245: portugalVianaDoCastelo,
    2234: portugalVilaReal,
    2237: portugalViseu
  };
