/// Access to known geographies in Saint Lucia and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'saint_lucia_cities.dart';

/// The 12 regions of `🇱🇨 Saint Lucia`
const Region saintLuciaAnseLlaRayeQuarter = Region(
    id: 3757,
    parentId: 186,
    longitude: -61.0369468,
    latitude: 13.9459424,
    name: "Anse la Raye Quarter",
    type: null,
    stateCode: "01",
    cities: [
      saintLuciaAnseLlaRayeQuarterAnseLaRaye,
      saintLuciaAnseLlaRayeQuarterAuTabor,
      saintLuciaAnseLlaRayeQuarterAuTaborHill,
      saintLuciaAnseLlaRayeQuarterBoisDInde,
      saintLuciaAnseLlaRayeQuarterCaicoMillet,
      saintLuciaAnseLlaRayeQuarterCanaries,
      saintLuciaAnseLlaRayeQuarterChampenEstate,
      saintLuciaAnseLlaRayeQuarterDerriereLagoon,
      saintLuciaAnseLlaRayeQuarterDurandeau,
      saintLuciaAnseLlaRayeQuarterEnbarPwin,
      saintLuciaAnseLlaRayeQuarterJacmel,
      saintLuciaAnseLlaRayeQuarterJeanBaptiste,
      saintLuciaAnseLlaRayeQuarterLaTrielle,
      saintLuciaAnseLlaRayeQuarterMassacre,
      saintLuciaAnseLlaRayeQuarterMillet,
      saintLuciaAnseLlaRayeQuarterMorneCiseaux,
      saintLuciaAnseLlaRayeQuarterMorneDOr,
      saintLuciaAnseLlaRayeQuarterRoseauValley,
      saintLuciaAnseLlaRayeQuarterStLawrence,
      saintLuciaAnseLlaRayeQuarterStLawrenceEstate,
      saintLuciaAnseLlaRayeQuarterTeteChemin,
      saintLuciaAnseLlaRayeQuarterVanard,
      saintLuciaAnseLlaRayeQuarterVenus,
      saintLuciaAnseLlaRayeQuarterVillage,
      saintLuciaAnseLlaRayeQuarterVillagePetiteBourgh
    ]);
const Region saintLuciaCanaries = Region(
    id: 3761,
    parentId: 186,
    longitude: -16.6291304,
    latitude: 28.2915637,
    name: "Canaries",
    type: null,
    stateCode: "12",
    cities: [
      saintLuciaCanariesAnseCochon,
      saintLuciaCanariesAnseGalet,
      saintLuciaCanariesAnseLaVerdue,
      saintLuciaCanariesBelvedere,
      saintLuciaCanariesChalon,
      saintLuciaCanariesRiversideRoad,
      saintLuciaCanariesTheodrine,
      saintLuciaCanariesVillage
    ]);
const Region saintLuciaCastriesQuarter = Region(
    id: 3758,
    parentId: 186,
    longitude: -60.9874687,
    latitude: 14.0101094,
    name: "Castries Quarter",
    type: null,
    stateCode: "02",
    cities: [
      saintLuciaCastriesQuarterActiveHill,
      saintLuciaCastriesQuarterAgardLandsMorneDudon,
      saintLuciaCastriesQuarterAlmondale,
      saintLuciaCastriesQuarterAurendelHill,
      saintLuciaCastriesQuarterBabonneauProper,
      saintLuciaCastriesQuarterBagatelle,
      saintLuciaCastriesQuarterBalata,
      saintLuciaCastriesQuarterBanannesBay,
      saintLuciaCastriesQuarterBarnardHill,
      saintLuciaCastriesQuarterBarreDenis,
      saintLuciaCastriesQuarterBarreDuchaussee,
      saintLuciaCastriesQuarterBarreStDotJoseph,
      saintLuciaCastriesQuarterBelair,
      saintLuciaCastriesQuarterBellaRosa,
      saintLuciaCastriesQuarterBexon,
      saintLuciaCastriesQuarterBisee,
      saintLuciaCastriesQuarterBishopSGap,
      saintLuciaCastriesQuarterBissee,
      saintLuciaCastriesQuarterBlackMallet,
      saintLuciaCastriesQuarterBocage,
      saintLuciaCastriesQuarterBoisCatchet,
      saintLuciaCastriesQuarterBoisPatat,
      saintLuciaCastriesQuarterCabicheBabonneau,
      saintLuciaCastriesQuarterCacoaBabonneau,
      saintLuciaCastriesQuarterCalvary,
      saintLuciaCastriesQuarterCapitalHill,
      saintLuciaCastriesQuarterCarellie,
      saintLuciaCastriesQuarterCastries,
      saintLuciaCastriesQuarterCedars,
      saintLuciaCastriesQuarterChaseGardens,
      saintLuciaCastriesQuarterChassinBabonneau,
      saintLuciaCastriesQuarterChoppinRidgeSarot,
      saintLuciaCastriesQuarterCiceron,
      saintLuciaCastriesQuarterCity,
      saintLuciaCastriesQuarterCityGateLaClery,
      saintLuciaCastriesQuarterConwayWaterfront,
      saintLuciaCastriesQuarterCoolieTown,
      saintLuciaCastriesQuarterCoubaril,
      saintLuciaCastriesQuarterCrownlandsMarc,
      saintLuciaCastriesQuarterCulDeSac,
      saintLuciaCastriesQuarterDarlingRoad,
      saintLuciaCastriesQuarterDeglos,
      saintLuciaCastriesQuarterDerierreFortOldVictoriaRoad,
      saintLuciaCastriesQuarterDubrassay,
      saintLuciaCastriesQuarterEnPoisDouxBabonneau,
      saintLuciaCastriesQuarterEntrepot,
      saintLuciaCastriesQuarterFauxAChaud,
      saintLuciaCastriesQuarterFerrand,
      saintLuciaCastriesQuarterFloissacMarc,
      saintLuciaCastriesQuarterFondAssauBabonneau,
      saintLuciaCastriesQuarterFondCanie,
      saintLuciaCastriesQuarterForestiere,
      saintLuciaCastriesQuarterGeorgeCharlesBoulevard,
      saintLuciaCastriesQuarterGirard,
      saintLuciaCastriesQuarterGoergeville,
      saintLuciaCastriesQuarterGoodlands,
      saintLuciaCastriesQuarterGrassStreet,
      saintLuciaCastriesQuarterGreenGold,
      saintLuciaCastriesQuarterGuesneau,
      saintLuciaCastriesQuarterHill20Babonneau,
      saintLuciaCastriesQuarterHillcrestGardens,
      saintLuciaCastriesQuarterHospitalRoad,
      saintLuciaCastriesQuarterIndependenceCity,
      saintLuciaCastriesQuarterJohnComptonHighway,
      saintLuciaCastriesQuarterLAnseRoad,
      saintLuciaCastriesQuarterLaCarierre,
      saintLuciaCastriesQuarterLaClery,
      saintLuciaCastriesQuarterLaCroixMaingot,
      saintLuciaCastriesQuarterLaPansee,
      saintLuciaCastriesQuarterLaToc,
      saintLuciaCastriesQuarterLabayee,
      saintLuciaCastriesQuarterLasticHill,
      saintLuciaCastriesQuarterLeslieLand,
      saintLuciaCastriesQuarterMarc,
      saintLuciaCastriesQuarterMarchand,
      saintLuciaCastriesQuarterMarigot,
      saintLuciaCastriesQuarterMaynardHill,
      saintLuciaCastriesQuarterMiamiBexon,
      saintLuciaCastriesQuarterMonkeyTownCiceron,
      saintLuciaCastriesQuarterMorneAssauBabonneau,
      saintLuciaCastriesQuarterMorneDudon,
      saintLuciaCastriesQuarterMorneRoad,
      saintLuciaCastriesQuarterMorneRougeMarc,
      saintLuciaCastriesQuarterMountPleasant,
      saintLuciaCastriesQuarterNewVillage,
      saintLuciaCastriesQuarterOdsan,
      saintLuciaCastriesQuarterParkerSHill,
      saintLuciaCastriesQuarterPattersonSGap,
      saintLuciaCastriesQuarterPavee,
      saintLuciaCastriesQuarterPeartSGap,
      saintLuciaCastriesQuarterPerou,
      saintLuciaCastriesQuarterPointeSeraphine,
      saintLuciaCastriesQuarterQuarteChemins,
      saintLuciaCastriesQuarterRavineChabot,
      saintLuciaCastriesQuarterRavinePoisson,
      saintLuciaCastriesQuarterRavineTouterelle,
      saintLuciaCastriesQuarterResinardBabonneau,
      saintLuciaCastriesQuarterRockHall,
      saintLuciaCastriesQuarterRoseHill,
      saintLuciaCastriesQuarterSanSoucis,
      saintLuciaCastriesQuarterSandDeFeu,
      saintLuciaCastriesQuarterSarot,
      saintLuciaCastriesQuarterSummersdale,
      saintLuciaCastriesQuarterSunbilt,
      saintLuciaCastriesQuarterSunnyAcres,
      saintLuciaCastriesQuarterTalvern,
      saintLuciaCastriesQuarterTapion,
      saintLuciaCastriesQuarterTheMorne,
      saintLuciaCastriesQuarterTiColon,
      saintLuciaCastriesQuarterTiRocher,
      saintLuciaCastriesQuarterTroisPiton,
      saintLuciaCastriesQuarterTrouCochanMarc,
      saintLuciaCastriesQuarterTrouFlorentMarc,
      saintLuciaCastriesQuarterTrouRouge,
      saintLuciaCastriesQuarterVideBouteille,
      saintLuciaCastriesQuarterVigie,
      saintLuciaCastriesQuarterWaterworks,
      saintLuciaCastriesQuarterWiltonSYardGraveYard,
      saintLuciaCastriesQuarterYorkeHill
    ]);
const Region saintLuciaChoiseulQuarter = Region(
    id: 3760,
    parentId: 186,
    longitude: -61.048591,
    latitude: 13.7750154,
    name: "Choiseul Quarter",
    type: null,
    stateCode: "03",
    cities: [
      saintLuciaChoiseulQuarterBelleVue,
      saintLuciaChoiseulQuarterBoisDinde,
      saintLuciaChoiseulQuarterCaffiere,
      saintLuciaChoiseulQuarterCedarsChuTigre,
      saintLuciaChoiseulQuarterChoiseul,
      saintLuciaChoiseulQuarterChristianHill,
      saintLuciaChoiseulQuarterDacretin,
      saintLuciaChoiseulQuarterDebreuil,
      saintLuciaChoiseulQuarterDelcer,
      saintLuciaChoiseulQuarterDerriereMorne,
      saintLuciaChoiseulQuarterDugard,
      saintLuciaChoiseulQuarterDupre,
      saintLuciaChoiseulQuarterEsperance,
      saintLuciaChoiseulQuarterFranciou,
      saintLuciaChoiseulQuarterIndustry,
      saintLuciaChoiseulQuarterLaFargue,
      saintLuciaChoiseulQuarterLaPointe,
      saintLuciaChoiseulQuarterLamaze,
      saintLuciaChoiseulQuarterLeRiche,
      saintLuciaChoiseulQuarterMaillyMotete,
      saintLuciaChoiseulQuarterMartin,
      saintLuciaChoiseulQuarterMongouge,
      saintLuciaChoiseulQuarterMonzie,
      saintLuciaChoiseulQuarterMorneJacques,
      saintLuciaChoiseulQuarterMorneSion,
      saintLuciaChoiseulQuarterMotete,
      saintLuciaChoiseulQuarterNewFieldFiette,
      saintLuciaChoiseulQuarterPonyon,
      saintLuciaChoiseulQuarterRaveneau,
      saintLuciaChoiseulQuarterReunion,
      saintLuciaChoiseulQuarterRiverDoree,
      saintLuciaChoiseulQuarterRoblot,
      saintLuciaChoiseulQuarterSauzay,
      saintLuciaChoiseulQuarterSavannesgeorgeConstitution,
      saintLuciaChoiseulQuarterVictoria,
      saintLuciaChoiseulQuarterVillage
    ]);
const Region saintLuciaDauphinQuarter = Region(
    id: 3767,
    parentId: 186,
    longitude: -60.9190988,
    latitude: 14.0103396,
    name: "Dauphin Quarter",
    type: null,
    stateCode: "04",
    cities: []);
const Region saintLuciaDenneryQuarter = Region(
    id: 3756,
    parentId: 186,
    longitude: -60.9190988,
    latitude: 13.9267393,
    name: "Dennery Quarter",
    type: null,
    stateCode: "05",
    cities: [
      saintLuciaDenneryQuarterAnseCanot,
      saintLuciaDenneryQuarterAthens,
      saintLuciaDenneryQuarterAuLeon,
      saintLuciaDenneryQuarterBaraBara,
      saintLuciaDenneryQuarterBazile,
      saintLuciaDenneryQuarterBelmont,
      saintLuciaDenneryQuarterBoisJoli,
      saintLuciaDenneryQuarterBordelais,
      saintLuciaDenneryQuarterBosquetDOr,
      saintLuciaDenneryQuarterDelaide,
      saintLuciaDenneryQuarterDennery,
      saintLuciaDenneryQuarterDenneryByPass,
      saintLuciaDenneryQuarterDenneryByPassGreenMountain,
      saintLuciaDenneryQuarterDenneryByPassRockyLane,
      saintLuciaDenneryQuarterDenneryByPassWhiteRockGardens,
      saintLuciaDenneryQuarterDenneryVillage,
      saintLuciaDenneryQuarterDerniereRiviere,
      saintLuciaDenneryQuarterDerniereRiviereFondMaricient,
      saintLuciaDenneryQuarterDerniereRiviereMardiGrasMorneCacaCochon,
      saintLuciaDenneryQuarterDerniereRiviereMornePanache,
      saintLuciaDenneryQuarterDespinoze,
      saintLuciaDenneryQuarterDubonnaire,
      saintLuciaDenneryQuarterGadette,
      saintLuciaDenneryQuarterGrandeRavine,
      saintLuciaDenneryQuarterGrandeRiviere,
      saintLuciaDenneryQuarterGrandeRiviereDesBranch,
      saintLuciaDenneryQuarterGrandeRiviereEnLeurMorneDiscompere,
      saintLuciaDenneryQuarterGrandeRiviereFunier,
      saintLuciaDenneryQuarterGrandeRiviereMorneCacaCochon,
      saintLuciaDenneryQuarterLaCaye,
      saintLuciaDenneryQuarterLaPelle,
      saintLuciaDenneryQuarterLaPointe,
      saintLuciaDenneryQuarterLaRessource,
      saintLuciaDenneryQuarterLumiere,
      saintLuciaDenneryQuarterMornePanache,
      saintLuciaDenneryQuarterRicheFond,
      saintLuciaDenneryQuarterRicheFondLaBelleVie,
      saintLuciaDenneryQuarterRicheFondNewVillage,
      saintLuciaDenneryQuarterStDotJosephEstate,
      saintLuciaDenneryQuarterThamazo
    ]);
const Region saintLuciaGrosIsletQuarter = Region(
    id: 3766,
    parentId: 186,
    longitude: -60.9452794,
    latitude: 14.0843578,
    name: "Gros Islet Quarter",
    type: null,
    stateCode: "06",
    cities: [
      saintLuciaGrosIsletQuarterBeausejour,
      saintLuciaGrosIsletQuarterBeausejourFostinSDevelopment,
      saintLuciaGrosIsletQuarterBeausejourNdc,
      saintLuciaGrosIsletQuarterBellaRosa,
      saintLuciaGrosIsletQuarterBelleVue,
      saintLuciaGrosIsletQuarterBelleVueEstate,
      saintLuciaGrosIsletQuarterBoguis,
      saintLuciaGrosIsletQuarterBoguisDesaBlond,
      saintLuciaGrosIsletQuarterBoisDOrange,
      saintLuciaGrosIsletQuarterBoisDOrnangeTrouya,
      saintLuciaGrosIsletQuarterBonneterre,
      saintLuciaGrosIsletQuarterBonneterreGardens,
      saintLuciaGrosIsletQuarterCapEstate,
      saintLuciaGrosIsletQuarterCapEstateBecunePoint,
      saintLuciaGrosIsletQuarterCapEstateCaribbeanPark,
      saintLuciaGrosIsletQuarterCapEstateGolfPark,
      saintLuciaGrosIsletQuarterCapEstateLowerSalinePoint,
      saintLuciaGrosIsletQuarterCapEstateMonDuCap,
      saintLuciaGrosIsletQuarterCapEstateRanchSite,
      saintLuciaGrosIsletQuarterCapEstateSaddlecBack,
      saintLuciaGrosIsletQuarterCapEstateUpperSalinePoint,
      saintLuciaGrosIsletQuarterCasEnBas,
      saintLuciaGrosIsletQuarterCayeManje,
      saintLuciaGrosIsletQuarterCorinth,
      saintLuciaGrosIsletQuarterCorinthEstate,
      saintLuciaGrosIsletQuarterCorinthLaBelLair,
      saintLuciaGrosIsletQuarterDauphin,
      saintLuciaGrosIsletQuarterDesBarras,
      saintLuciaGrosIsletQuarterDesBarrasCacolie,
      saintLuciaGrosIsletQuarterDesrameaux,
      saintLuciaGrosIsletQuarterGarrand,
      saintLuciaGrosIsletQuarterGrandRiviere,
      saintLuciaGrosIsletQuarterGrandeRiviereAssouCanal,
      saintLuciaGrosIsletQuarterGrandeRiviereIngleWoods,
      saintLuciaGrosIsletQuarterGrandeRiviereMorneSerpent,
      saintLuciaGrosIsletQuarterGrandeRiviereNorbert,
      saintLuciaGrosIsletQuarterGrandeRivierePiat,
      saintLuciaGrosIsletQuarterGrandeRiviereWhiteRock,
      saintLuciaGrosIsletQuarterGrosIslet,
      saintLuciaGrosIsletQuarterGrosIsletTown,
      saintLuciaGrosIsletQuarterGrosIsletEdgeWater,
      saintLuciaGrosIsletQuarterLHermitage,
      saintLuciaGrosIsletQuarterLaCroixChabourgh,
      saintLuciaGrosIsletQuarterLaGuerre,
      saintLuciaGrosIsletQuarterLaGuerreChickenBackStreet,
      saintLuciaGrosIsletQuarterMarisule,
      saintLuciaGrosIsletQuarterMarisuleBonAir,
      saintLuciaGrosIsletQuarterMarisuleEastWinds,
      saintLuciaGrosIsletQuarterMarisuleLaBrellotte,
      saintLuciaGrosIsletQuarterMarisuleTopOfTheWorld,
      saintLuciaGrosIsletQuarterMarquisEstate,
      saintLuciaGrosIsletQuarterMassade,
      saintLuciaGrosIsletQuarterMonchy,
      saintLuciaGrosIsletQuarterMonchyCareffe,
      saintLuciaGrosIsletQuarterMonchyCletusVillage,
      saintLuciaGrosIsletQuarterMonchyLaBorne,
      saintLuciaGrosIsletQuarterMonchyLaBorneSansSouci,
      saintLuciaGrosIsletQuarterMonchyLaRetraite,
      saintLuciaGrosIsletQuarterMonchyLafeuillee,
      saintLuciaGrosIsletQuarterMonchyLawiFwen,
      saintLuciaGrosIsletQuarterMonchyMalgretoute,
      saintLuciaGrosIsletQuarterMonchyMoulinAVent,
      saintLuciaGrosIsletQuarterMonchyRavineMacock,
      saintLuciaGrosIsletQuarterMonchyRiviereMitan,
      saintLuciaGrosIsletQuarterMonchyTiDauphin,
      saintLuciaGrosIsletQuarterMonchyVieuxSucreic,
      saintLuciaGrosIsletQuarterMonchyVieuxSucreicBoisDInde,
      saintLuciaGrosIsletQuarterMonchyVieuxSucreicCareffe,
      saintLuciaGrosIsletQuarterMongiraud,
      saintLuciaGrosIsletQuarterMonier,
      saintLuciaGrosIsletQuarterMorneCiton,
      saintLuciaGrosIsletQuarterPaixBouche,
      saintLuciaGrosIsletQuarterPigeonIsland,
      saintLuciaGrosIsletQuarterPlateau,
      saintLuciaGrosIsletQuarterReduit,
      saintLuciaGrosIsletQuarterReduitOrchard,
      saintLuciaGrosIsletQuarterReduitPark,
      saintLuciaGrosIsletQuarterRodneyBay,
      saintLuciaGrosIsletQuarterRodneyHeights,
      saintLuciaGrosIsletQuarterUnion,
      saintLuciaGrosIsletQuarterUnionTerrace,
      saintLuciaGrosIsletQuarterUnionTiMorne
    ]);
const Region saintLuciaLaborieQuarter = Region(
    id: 3759,
    parentId: 186,
    longitude: -60.9932889,
    latitude: 13.7522783,
    name: "Laborie Quarter",
    type: null,
    stateCode: "07",
    cities: [
      saintLuciaLaborieQuarterAnnus,
      saintLuciaLaborieQuarterBalca,
      saintLuciaLaborieQuarterBalcaEnLeurBa,
      saintLuciaLaborieQuarterBalembouche,
      saintLuciaLaborieQuarterBanse,
      saintLuciaLaborieQuarterBanseLaGrace,
      saintLuciaLaborieQuarterBongalo,
      saintLuciaLaborieQuarterDaban,
      saintLuciaLaborieQuarterFondBerange,
      saintLuciaLaborieQuarterGayabois,
      saintLuciaLaborieQuarterGentil,
      saintLuciaLaborieQuarterGetrine,
      saintLuciaLaborieQuarterGiraud,
      saintLuciaLaborieQuarterHErelle,
      saintLuciaLaborieQuarterKennedyHighwayLaborieBypass,
      saintLuciaLaborieQuarterLaHaut,
      saintLuciaLaborieQuarterLaPerle,
      saintLuciaLaborieQuarterLaborie,
      saintLuciaLaborieQuarterLondonderry,
      saintLuciaLaborieQuarterMacdomel,
      saintLuciaLaborieQuarterMorneGomier,
      saintLuciaLaborieQuarterMorneLeBlanc,
      saintLuciaLaborieQuarterOlibo,
      saintLuciaLaborieQuarterParcEstate,
      saintLuciaLaborieQuarterPiaye,
      saintLuciaLaborieQuarterSaltibus,
      saintLuciaLaborieQuarterSaphire,
      saintLuciaLaborieQuarterTeteMorne,
      saintLuciaLaborieQuarterVillage,
      saintLuciaLaborieQuarterWarwickDaban
    ]);
const Region saintLuciaMicoudQuarter = Region(
    id: 3762,
    parentId: 186,
    longitude: -60.9001934,
    latitude: 13.8211871,
    name: "Micoud Quarter",
    type: null,
    stateCode: "08",
    cities: [
      saintLuciaMicoudQuarterAnseGer,
      saintLuciaMicoudQuarterBeauchamp,
      saintLuciaMicoudQuarterBlanchard,
      saintLuciaMicoudQuarterCanelles,
      saintLuciaMicoudQuarterCazuca,
      saintLuciaMicoudQuarterChiqueBlanchard,
      saintLuciaMicoudQuarterCoolieTown,
      saintLuciaMicoudQuarterDelomel,
      saintLuciaMicoudQuarterDesBlanchard,
      saintLuciaMicoudQuarterDesruisseaux,
      saintLuciaMicoudQuarterDugard,
      saintLuciaMicoudQuarterEscap,
      saintLuciaMicoudQuarterFondDLorDugard,
      saintLuciaMicoudQuarterFondEstate,
      saintLuciaMicoudQuarterFondDesruisseaux,
      saintLuciaMicoudQuarterGomier,
      saintLuciaMicoudQuarterGouette,
      saintLuciaMicoudQuarterHoneymoonBeach,
      saintLuciaMicoudQuarterLEauMineau,
      saintLuciaMicoudQuarterLaCourville,
      saintLuciaMicoudQuarterLaPointe,
      saintLuciaMicoudQuarterLaTille,
      saintLuciaMicoudQuarterLezy,
      saintLuciaMicoudQuarterLombard,
      saintLuciaMicoudQuarterMahaut,
      saintLuciaMicoudQuarterMalgretoute,
      saintLuciaMicoudQuarterMamiku,
      saintLuciaMicoudQuarterMicoud,
      saintLuciaMicoudQuarterMonRepos,
      saintLuciaMicoudQuarterMoreau,
      saintLuciaMicoudQuarterMorneVient,
      saintLuciaMicoudQuarterMyetteGardens,
      saintLuciaMicoudQuarterNewVillage,
      saintLuciaMicoudQuarterPaixBouche,
      saintLuciaMicoudQuarterPalmisteEstate,
      saintLuciaMicoudQuarterPatience,
      saintLuciaMicoudQuarterPlanard,
      saintLuciaMicoudQuarterPraslin,
      saintLuciaMicoudQuarterRameau,
      saintLuciaMicoudQuarterSaintMarieRoad,
      saintLuciaMicoudQuarterSaut,
      saintLuciaMicoudQuarterSavannes,
      saintLuciaMicoudQuarterStHelenEstate,
      saintLuciaMicoudQuarterTiRiviere,
      saintLuciaMicoudQuarterTiRocher,
      saintLuciaMicoudQuarterTroumassee,
      saintLuciaMicoudQuarterVillage,
      saintLuciaMicoudQuarterVolet
    ]);
const Region saintLuciaPraslinQuarter = Region(
    id: 3765,
    parentId: 186,
    longitude: -60.8994663,
    latitude: 13.8752392,
    name: "Praslin Quarter",
    type: null,
    stateCode: "09",
    cities: []);
const Region saintLuciaSoufriereQuarter = Region(
    id: 3764,
    parentId: 186,
    longitude: -61.0573248,
    latitude: 13.8570986,
    name: "Soufrière Quarter",
    type: null,
    stateCode: "10",
    cities: [
      saintLuciaSoufriereQuarterAnseChastanet,
      saintLuciaSoufriereQuarterBaronsDriveCoinDeLAnse,
      saintLuciaSoufriereQuarterBeasejourMyersBridge,
      saintLuciaSoufriereQuarterBellePlaine,
      saintLuciaSoufriereQuarterBellefond,
      saintLuciaSoufriereQuarterBelvedere,
      saintLuciaSoufriereQuarterBoisDInde,
      saintLuciaSoufriereQuarterBouton,
      saintLuciaSoufriereQuarterCalvaryCalvaire,
      saintLuciaSoufriereQuarterCenac,
      saintLuciaSoufriereQuarterChateauBelair,
      saintLuciaSoufriereQuarterColombette,
      saintLuciaSoufriereQuarterCompar,
      saintLuciaSoufriereQuarterCresslands,
      saintLuciaSoufriereQuarterDeville,
      saintLuciaSoufriereQuarterDiamondDiamondEstate,
      saintLuciaSoufriereQuarterEsperance,
      saintLuciaSoufriereQuarterEtangs,
      saintLuciaSoufriereQuarterFondBernier,
      saintLuciaSoufriereQuarterFondCacoa,
      saintLuciaSoufriereQuarterFondDoux,
      saintLuciaSoufriereQuarterFondGensLibre,
      saintLuciaSoufriereQuarterJalousie,
      saintLuciaSoufriereQuarterLaHaut,
      saintLuciaSoufriereQuarterLaPearle,
      saintLuciaSoufriereQuarterLennyHill,
      saintLuciaSoufriereQuarterMalgretoute,
      saintLuciaSoufriereQuarterMigny,
      saintLuciaSoufriereQuarterMocha,
      saintLuciaSoufriereQuarterMorneBonin,
      saintLuciaSoufriereQuarterMorneLaCroix,
      saintLuciaSoufriereQuarterMorneLasticDesruisseaux,
      saintLuciaSoufriereQuarterNewDevelopment,
      saintLuciaSoufriereQuarterPalmiste,
      saintLuciaSoufriereQuarterPlatPays,
      saintLuciaSoufriereQuarterRabot,
      saintLuciaSoufriereQuarterRavineClaire,
      saintLuciaSoufriereQuarterRubyEstate,
      saintLuciaSoufriereQuarterSoufriere,
      saintLuciaSoufriereQuarterSoufriereEstate,
      saintLuciaSoufriereQuarterStPhillip,
      saintLuciaSoufriereQuarterStonefield,
      saintLuciaSoufriereQuarterSulphurSprings,
      saintLuciaSoufriereQuarterTiBoug,
      saintLuciaSoufriereQuarterTiDelcer,
      saintLuciaSoufriereQuarterToraille,
      saintLuciaSoufriereQuarterTown,
      saintLuciaSoufriereQuarterUnionVale,
      saintLuciaSoufriereQuarterZenon
    ]);
const Region saintLuciaVieuxFortQuarter = Region(
    id: 3763,
    parentId: 186,
    longitude: -60.9496433,
    latitude: 13.720608,
    name: "Vieux Fort Quarter",
    type: null,
    stateCode: "11",
    cities: [
      saintLuciaVieuxFortQuarterAugier,
      saintLuciaVieuxFortQuarterBeaneField,
      saintLuciaVieuxFortQuarterBeausejour,
      saintLuciaVieuxFortQuarterBelleVue,
      saintLuciaVieuxFortQuarterBlackBay,
      saintLuciaVieuxFortQuarterBrucevilleShantyTown,
      saintLuciaVieuxFortQuarterCacoa,
      saintLuciaVieuxFortQuarterCantonement,
      saintLuciaVieuxFortQuarterCarierre,
      saintLuciaVieuxFortQuarterCatin,
      saintLuciaVieuxFortQuarterCocoaDan,
      saintLuciaVieuxFortQuarterCoolieTown,
      saintLuciaVieuxFortQuarterDeMailly,
      saintLuciaVieuxFortQuarterDerierreBois,
      saintLuciaVieuxFortQuarterDerierreMorne,
      saintLuciaVieuxFortQuarterDocamelLaResource,
      saintLuciaVieuxFortQuarterEauPiquantStUrbain,
      saintLuciaVieuxFortQuarterEnBamboo,
      saintLuciaVieuxFortQuarterEsperance,
      saintLuciaVieuxFortQuarterFondCapeche,
      saintLuciaVieuxFortQuarterFondSabot,
      saintLuciaVieuxFortQuarterGrace,
      saintLuciaVieuxFortQuarterHewanorraOrchard,
      saintLuciaVieuxFortQuarterHopeEstate,
      saintLuciaVieuxFortQuarterIndustrialEstate,
      saintLuciaVieuxFortQuarterJoyeux,
      saintLuciaVieuxFortQuarterLaResource,
      saintLuciaVieuxFortQuarterLaRetraite,
      saintLuciaVieuxFortQuarterLaTourneyCedarHeights,
      saintLuciaVieuxFortQuarterMaganier,
      saintLuciaVieuxFortQuarterMorneCayenne,
      saintLuciaVieuxFortQuarterMorneVert,
      saintLuciaVieuxFortQuarterMouleAChique,
      saintLuciaVieuxFortQuarterObrier,
      saintLuciaVieuxFortQuarterPierrot,
      saintLuciaVieuxFortQuarterPlut,
      saintLuciaVieuxFortQuarterPomme,
      saintLuciaVieuxFortQuarterStJudeSHighway,
      saintLuciaVieuxFortQuarterTeteMorneMorneAndrew,
      saintLuciaVieuxFortQuarterTown,
      saintLuciaVieuxFortQuarterVieuxFort,
      saintLuciaVieuxFortQuarterVieuxFortLaborieHighway,
      saintLuciaVieuxFortQuarterVige,
      saintLuciaVieuxFortQuarterWestallGroupTheMangue
    ]);

const saintLuciaStates = <int, Region>{
  3757: saintLuciaAnseLlaRayeQuarter,
  3761: saintLuciaCanaries,
  3758: saintLuciaCastriesQuarter,
  3760: saintLuciaChoiseulQuarter,
  3767: saintLuciaDauphinQuarter,
  3756: saintLuciaDenneryQuarter,
  3766: saintLuciaGrosIsletQuarter,
  3759: saintLuciaLaborieQuarter,
  3762: saintLuciaMicoudQuarter,
  3765: saintLuciaPraslinQuarter,
  3764: saintLuciaSoufriereQuarter,
  3763: saintLuciaVieuxFortQuarter
};
