/// Access to known geographies in `Saudi Arabia` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'saudiarabia_cities.dart';

/// The `'Asir` region in `Saudi Arabia`
const Region saudiArabiaasirRegion = Region(
  id: 2853,
  parentId: 194,
  longitude: 42.8637875,
  latitude: 19.0969062,
  name: "'Asir",
  type: "region",
  stateCode: "14",
  cities: [
    asirRegionAbhaCity,
    asirRegionAlMajaridahCity,
    asirRegionAlQahabCity,
    asirRegionKhamisMushaitCity,
    asirRegionMariyahCity,
    asirRegionMifaCity,
    asirRegionMunayzirCity,
    asirRegionTabalahCity
  ]);

/// The `Al Bahah` region in `Saudi Arabia`
const Region saudiArabiaAlBahahRegion = Region(
  id: 2859,
  parentId: 194,
  longitude: 41.441251,
  latitude: 20.2722739,
  name: "Al Bahah",
  type: "region",
  stateCode: "11",
  cities: [
    alBahahRegionAlBahahCity,
    alBahahRegionAlMindakCity,
    alBahahRegionHajrahCity
  ]);

/// The `Al Jawf` region in `Saudi Arabia`
const Region saudiArabiaAlJawfRegion = Region(
  id: 2857,
  parentId: 194,
  longitude: 39.3206241,
  latitude: 29.887356,
  name: "Al Jawf",
  type: "region",
  stateCode: "12",
  cities: [
    alJawfRegionAlIsawiyahCity,
    alJawfRegionAlHyphadithaCity,
    alJawfRegionHalatAmmarCity,
    alJawfRegionQurayyatCity,
    alJawfRegionSakakahCity,
    alJawfRegionSuwayrCity,
    alJawfRegionTabarjalCity,
    alJawfRegionTubarjalCity
  ]);

/// The `Al Madinah` region in `Saudi Arabia`
const Region saudiArabiaAlMadinahRegion = Region(
  id: 2851,
  parentId: 194,
  longitude: 39.3206241,
  latitude: 24.8403977,
  name: "Al Madinah",
  type: "region",
  stateCode: "03",
  cities: [
    alMadinahRegionajmiyahCity,
    alMadinahRegionalyaCity,
    alMadinahRegionushashCity,
    alMadinahRegionushayrahCity,
    alMadinahRegionAbuShaytanahCity,
    alMadinahRegionAbyaraliCity,
    alMadinahRegionAdDuluCity,
    alMadinahRegionAlawaliCity,
    alMadinahRegionAluqulCity,
    alMadinahRegionAlAkhalCity,
    alMadinahRegionAlBardiyahCity,
    alMadinahRegionAlBiqaCity,
    alMadinahRegionAlBustanCity,
    alMadinahRegionAlFaqirahCity,
    alMadinahRegionAlFurayshCity,
    alMadinahRegionAlJabriyahCity,
    alMadinahRegionAlJissahCity,
    alMadinahRegionAlKharmaCity,
    alMadinahRegionAlMalbanahCity,
    alMadinahRegionAlMufrihatCity,
    alMadinahRegionAlMultasaCity,
    alMadinahRegionAlMusayjidCity,
    alMadinahRegionAlWudayCity,
    alMadinahRegionAlHypjafrCity,
    alMadinahRegionAlHypulaCity,
    alMadinahRegionAsSadayirCity,
    alMadinahRegionAsSafraCity,
    alMadinahRegionAsSumariyahCity,
    alMadinahRegionAsSuwayriqiyahCity,
    alMadinahRegionAshShufayyahCity,
    alMadinahRegionAsiraCity,
    alMadinahRegionBaqaCity,
    alMadinahRegionBartiyahCity,
    alMadinahRegionBirAlMashiCity,
    alMadinahRegionBirkahCity,
    alMadinahRegionFarCity,
    alMadinahRegionFijiCity,
    alMadinahRegionHarthiyahCity,
    alMadinahRegionHaylatRadiAlBahamCity,
    alMadinahRegionHusayniyahCity,
    alMadinahRegionJadidahCity,
    alMadinahRegionKhayfFadilCity,
    alMadinahRegionMadsusCity,
    alMadinahRegionMahattatAlHafahCity,
    alMadinahRegionMaqrahCity,
    alMadinahRegionMaqshushCity,
    alMadinahRegionMasahiliCity,
    alMadinahRegionMawarahCity,
    alMadinahRegionMedinaCity,
    alMadinahRegionMilhahCity,
    alMadinahRegionNujaylCity,
    alMadinahRegionQabaCity,
    alMadinahRegionRayyisCity,
    alMadinahRegionShathaCity,
    alMadinahRegionSidiHamzahCity,
    alMadinahRegionSuqSuwayqCity,
    alMadinahRegionSuqubiyaCity,
    alMadinahRegionSuwadahCity,
    alMadinahRegionWasitahCity,
    alMadinahRegionYanbuCity
  ]);

/// The `Al-Qassim` region in `Saudi Arabia`
const Region saudiArabiaAlHypqassimRegion = Region(
  id: 2861,
  parentId: 194,
  longitude: 43.483738,
  latitude: 26.207826,
  name: "Al-Qassim",
  type: "region",
  stateCode: "05",
  cities: [
    alHypqassimRegionAdhDhibiyahCity,
    alHypqassimRegionAlBukayriyahCity,
    alHypqassimRegionAlFuwayliqCity,
    alHypqassimRegionAlMithnabCity,
    alHypqassimRegionAlThybiyahCity,
    alHypqassimRegionArRassCity,
    alHypqassimRegionBuraidahCity,
    alHypqassimRegionBuraydahCity,
    alHypqassimRegionDukhnahCity,
    alHypqassimRegionQibaCity,
    alHypqassimRegionTanumahCity,
    alHypqassimRegionWedAlnkilCity
  ]);

/// The `Eastern Province` region in `Saudi Arabia`
const Region saudiArabiaEasternProvinceRegion = Region(
  id: 2856,
  parentId: 194,
  longitude: 45.6589225,
  latitude: 24.0439932,
  name: "Eastern Province",
  type: "region",
  stateCode: "04",
  cities: [
    easternProvinceRegionAbqaiqCity,
    easternProvinceRegionAlAwjamCity,
    easternProvinceRegionAlBattaliyahCity,
    easternProvinceRegionAlHufufCity,
    easternProvinceRegionAlJafrCity,
    easternProvinceRegionAlJubaylCity,
    easternProvinceRegionAlKhafjiCity,
    easternProvinceRegionAlMarkazCity,
    easternProvinceRegionAlMubarrazCity,
    easternProvinceRegionAlMunayzilahCity,
    easternProvinceRegionAlMutayrifiCity,
    easternProvinceRegionAlQarahCity,
    easternProvinceRegionAlQatifCity,
    easternProvinceRegionAlQuraynCity,
    easternProvinceRegionAlUbaylahCity,
    easternProvinceRegionAlHypawamiyahCity,
    easternProvinceRegionAlHypawjamCity,
    easternProvinceRegionAlHypmubarrazCity,
    easternProvinceRegionAsSaffaniyahCity,
    easternProvinceRegionAtTarafCity,
    easternProvinceRegionAtTubiCity,
    easternProvinceRegionDammamCity,
    easternProvinceRegionDhahranCity,
    easternProvinceRegionHailCity,
    easternProvinceRegionHafarAlHypbatinCity,
    easternProvinceRegionHaradhCity,
    easternProvinceRegionJulayjilahCity,
    easternProvinceRegionKhobarCity,
    easternProvinceRegionMulayjahCity,
    easternProvinceRegionNariyahCity,
    easternProvinceRegionQaisumahCity,
    easternProvinceRegionRahimahCity,
    easternProvinceRegionSafwaCity,
    easternProvinceRegionSayhatCity,
    easternProvinceRegionTarutCity,
    easternProvinceRegionUdhailiyahCity,
    easternProvinceRegionUmmAsSahikCity,
    easternProvinceRegionUqairCity
  ]);

/// The `Ha'il` region in `Saudi Arabia`
const Region saudiArabiaHailRegion = Region(
  id: 2855,
  parentId: 194,
  longitude: 41.9196471,
  latitude: 27.7076143,
  name: "Ha'il",
  type: "region",
  stateCode: "06",
  cities: [
    hailRegionJubbahCity,
    hailRegionMawqaqCity,
    hailRegionQufarCity,
    hailRegionSimiraCity
  ]);

/// The `Jizan` region in `Saudi Arabia`
const Region saudiArabiaJizanRegion = Region(
  id: 2858,
  parentId: 194,
  longitude: 42.7076107,
  latitude: 17.1738176,
  name: "Jizan",
  type: "region",
  stateCode: "09",
  cities: [
    jizanRegionAbuarishCity,
    jizanRegionAbuRadifCity,
    jizanRegionAdDarbCity,
    jizanRegionAdDuriyahCity,
    jizanRegionAdhDhagharirCity,
    jizanRegionAlulayinCity,
    jizanRegionAlusaylahCity,
    jizanRegionAlBadawiCity,
    jizanRegionAlHadrurCity,
    jizanRegionAlHanashahCity,
    jizanRegionAlHaraniCity,
    jizanRegionAlHasamahCity,
    jizanRegionAlHijfarCity,
    jizanRegionAlJadiCity,
    jizanRegionAlJaradiyahCity,
    jizanRegionAlJawahCity,
    jizanRegionAlJirbahCity,
    jizanRegionAlKarbusCity,
    jizanRegionAlKawahilahCity,
    jizanRegionAlKhadraJizanCity,
    jizanRegionAlKharabahJizanCity,
    jizanRegionAlKharadilahCity,
    jizanRegionAlKhashabiyahCity,
    jizanRegionAlKhubahCity,
    jizanRegionAlKirsCity,
    jizanRegionAlLuqiyahCity,
    jizanRegionAlMaayinCity,
    jizanRegionAlMadayaCity,
    jizanRegionAlMaliCity,
    jizanRegionAlMayasamCity,
    jizanRegionAlQaimCity,
    jizanRegionAlQufulCity,
    jizanRegionAlQuraybCity,
    jizanRegionAlQuwahCity,
    jizanRegionAlWasiliCity,
    jizanRegionAnNajamiyahCity,
    jizanRegionArRukubahCity,
    jizanRegionAshShuqayqCity,
    jizanRegionBakhshatYamaniCity,
    jizanRegionFarasanCity,
    jizanRegionGhawiyahCity,
    jizanRegionHamayyahCity,
    jizanRegionHamdahCity,
    jizanRegionJizanCity,
    jizanRegionJuhaSaudiArabiaCity,
    jizanRegionKalulCity,
    jizanRegionKhabathSaidCity,
    jizanRegionKhalfahCity,
    jizanRegionKhatibSaudiArabiaCity,
    jizanRegionKhumsiyahCity,
    jizanRegionKhushaymCity,
    jizanRegionMahatahCity,
    jizanRegionMalgoctaCity,
    jizanRegionMisliyahCity,
    jizanRegionMizhirahCity,
    jizanRegionMukambalCity,
    jizanRegionMundaraqCity,
    jizanRegionMuwassamCity,
    jizanRegionQitabirCity,
    jizanRegionQuwaydaCity,
    jizanRegionRahwanCity,
    jizanRegionRawkhahCity,
    jizanRegionSabyaCity,
    jizanRegionSadiliyahCity,
    jizanRegionSalamahCity,
    jizanRegionSamitahCity
  ]);

/// The `Makkah` region in `Saudi Arabia`
const Region saudiArabiaMakkahRegion = Region(
  id: 2850,
  parentId: 194,
  longitude: 41.9196471,
  latitude: 21.5235584,
  name: "Makkah",
  type: "region",
  stateCode: "02",
  cities: [
    makkahRegionAbuurwahCity,
    makkahRegionAbuHisaniCity,
    makkahRegionAbuQirfahCity,
    makkahRegionAbuShuaybCity,
    makkahRegionAdDabbahCity,
    makkahRegionAdDawhCity,
    makkahRegionAdDurCity,
    makkahRegionAlAbarCity,
    makkahRegionAlAdlCity,
    makkahRegionAlAshrafCity,
    makkahRegionAlBaladCity,
    makkahRegionAlBarabirCity,
    makkahRegionAlBiarCity,
    makkahRegionAlBirkCity,
    makkahRegionAlBuraykahCity,
    makkahRegionAlFawwarahCity,
    makkahRegionAlFaydahCity,
    makkahRegionAlFazzCity,
    makkahRegionAlGharithCity,
    makkahRegionAlGhassalahCity,
    makkahRegionAlGhulahCity,
    makkahRegionAlHadaCity,
    makkahRegionAlHalaqahCity,
    makkahRegionAlHamimahCity,
    makkahRegionAlHarraMakkahCity,
    makkahRegionAlHawiyahCity,
    makkahRegionAlIskanCity,
    makkahRegionAlJadidahCity,
    makkahRegionAlJamiahCity,
    makkahRegionAlJidCity,
    makkahRegionAlJuranahCity,
    makkahRegionAlJumumCity,
    makkahRegionAlKhadraMakkahCity,
    makkahRegionAlKhalasCity,
    makkahRegionAlKhamrahCity,
    makkahRegionAlKhaydarCity,
    makkahRegionAlKhayfCity,
    makkahRegionAlKhulasahCity,
    makkahRegionAlKidwahCity,
    makkahRegionAlKuraCity,
    makkahRegionAlMarashCity,
    makkahRegionAlMadiqMakkahCity,
    makkahRegionAlMaghalCity,
    makkahRegionAlMahjarCity,
    makkahRegionAlMaqrahCity,
    makkahRegionAlMasarrahCity,
    makkahRegionAlMasfalahCity,
    makkahRegionAlMashayikhCity,
    makkahRegionAlMathnahCity,
    makkahRegionAlMubarakCity,
    makkahRegionAlMudawwarahCity,
    makkahRegionAlMulayhaCity,
    makkahRegionAlMundassahCity,
    makkahRegionAlMuqaytiCity,
    makkahRegionAlMuqrCity,
    makkahRegionAlMuwayhCity,
    makkahRegionAlQadimahCity,
    makkahRegionAlQararahCity,
    makkahRegionAlQaryatCity,
    makkahRegionAlQawbaiyahCity,
    makkahRegionAlQirshanCity,
    makkahRegionAlQutubahCity,
    makkahRegionAlQufayfCity,
    makkahRegionAlQushashiyahCity,
    makkahRegionAlUkhaydirCity,
    makkahRegionAlWahtCity,
    makkahRegionArRabwahAsSuflaCity,
    makkahRegionArRafahCity,
    makkahRegionArRawdahAshShamaliyahCity,
    makkahRegionArRudaymahCity,
    makkahRegionAryaCity,
    makkahRegionAsSadrCity,
    makkahRegionAsSamdAshShamaliCity,
    makkahRegionAsSaylAlKabirCity,
    makkahRegionAsSaylAsSaghirCity,
    makkahRegionAsSifyaniCity,
    makkahRegionAsSudayrahMakkahCity,
    makkahRegionAsSuwadahCity,
    makkahRegionAshShafaCity,
    makkahRegionAshShajwahCity,
    makkahRegionAshShamiyahCity,
    makkahRegionAshSharaiCity,
    makkahRegionAshShaybiCity,
    makkahRegionAshShibCity,
    makkahRegionAshShishahCity,
    makkahRegionAshShumaysiCity,
    makkahRegionAshShuwaybitCity,
    makkahRegionAtTanimCity,
    makkahRegionAtTarfaCity,
    makkahRegionAtTurqiCity,
    makkahRegionAzZaymahCity,
    makkahRegionAzZilalCity,
    makkahRegionAzZughbahCity,
    makkahRegionAzZurraCity,
    makkahRegionAzZuwaybCity,
    makkahRegionBahratAlQadimahCity,
    makkahRegionBahwilCity,
    makkahRegionBaranahCity,
    makkahRegionBarzahCity,
    makkahRegionBashmCity,
    makkahRegionBuraykahCity,
    makkahRegionBuraymanCity,
    makkahRegionCityGhranCity,
    makkahRegionDabyahCity,
    makkahRegionDahabanCity,
    makkahRegionDughaybjahCity,
    makkahRegionFaydCity,
    makkahRegionGhranCity,
    makkahRegionHaddaCity,
    makkahRegionHaddatAshShamCity,
    makkahRegionHadhahCity,
    makkahRegionHajurCity,
    makkahRegionHalamahCity,
    makkahRegionHusnahCity,
    makkahRegionJarwalCity,
    makkahRegionJeddahCity,
    makkahRegionJulayyilCity,
    makkahRegionKhumrahCity,
    makkahRegionKulakhCity,
    makkahRegionMadrakahCity,
    makkahRegionMafruqCity,
    makkahRegionMalakanCity,
    makkahRegionMashajjiCity,
    makkahRegionMasihatMahdAlHaylCity,
    makkahRegionMaskarCity,
    makkahRegionMatiyahCity,
    makkahRegionMeccaCity,
    makkahRegionMinaCity,
    makkahRegionMurshidiyahCity,
    makkahRegionMushrifCity,
    makkahRegionNughayshiyahCity,
    makkahRegionNuzlatAlFaqinCity,
    makkahRegionQiyaCity,
    makkahRegionQuwayzahCity,
    makkahRegionRabighCity,
    makkahRegionRabwahGhranCity,
    makkahRegionRaqiyahCity,
    makkahRegionSabuhahCity,
    makkahRegionShibamirCity,
    makkahRegionShiraaynCity,
    makkahRegionSulaymCity,
    makkahRegionSumaymahCity,
    makkahRegionSuwaysCity,
    makkahRegionTaifCity,
    makkahRegionTharwahCity,
    makkahRegionThuwalCity,
    makkahRegionTurabahCity,
    makkahRegionUsfanCity,
    makkahRegionWadiAlJalilCity
  ]);

/// The `Najran` region in `Saudi Arabia`
const Region saudiArabiaNajranRegion = Region(
  id: 2860,
  parentId: 194,
  longitude: 45.6007108,
  latitude: 18.3514664,
  name: "Najran",
  type: "region",
  stateCode: "10",
  cities: [
    najranRegionNajranCity
  ]);

/// The `Northern Borders` region in `Saudi Arabia`
const Region saudiArabiaNorthernBordersRegion = Region(
  id: 2854,
  parentId: 194,
  longitude: 42.8637875,
  latitude: 30.0799162,
  name: "Northern Borders",
  type: "region",
  stateCode: "08",
  cities: [
    northernBordersRegionArarCity,
    northernBordersRegionNisabCity,
    northernBordersRegionTuraifCity,
    northernBordersRegionUmmRadamahCity
  ]);

/// The `Riyadh` region in `Saudi Arabia`
const Region saudiArabiaRiyadhRegion = Region(
  id: 2849,
  parentId: 194,
  longitude: 46.2091547,
  latitude: 22.7554385,
  name: "Riyadh",
  type: "region",
  stateCode: "01",
  cities: [
    riyadhRegionAdDawadimiCity,
    riyadhRegionAdDilamCity,
    riyadhRegionAfifCity,
    riyadhRegionAinAlbarahaCity,
    riyadhRegionAlArtawiyahCity,
    riyadhRegionAlBirCity,
    riyadhRegionAlHairCity,
    riyadhRegionAlJurayfahCity,
    riyadhRegionAlKharjCity,
    riyadhRegionArRaynCity,
    riyadhRegionAsSalamiyahCity,
    riyadhRegionAsSulayyilCity,
    riyadhRegionAzZulfiCity,
    riyadhRegionDawadmiCity,
    riyadhRegionDiriyahCity,
    riyadhRegionHarmahCity,
    riyadhRegionJalajilCity,
    riyadhRegionLaylaCity,
    riyadhRegionManfuhaCity,
    riyadhRegionMaratCity,
    riyadhRegionNajanCity,
    riyadhRegionRiyadhCity,
    riyadhRegionSajirCity,
    riyadhRegionShokhaibCity,
    riyadhRegionTumayrCity
  ]);

/// The `Tabuk` region in `Saudi Arabia`
const Region saudiArabiaTabukRegion = Region(
  id: 2852,
  parentId: 194,
  longitude: 37.6386622,
  latitude: 28.2453335,
  name: "Tabuk",
  type: "region",
  stateCode: "07",
  cities: [
    tabukRegionAlWajhCity,
    tabukRegionDubaCity,
    tabukRegionTabukCity,
    tabukRegionUmmLajjCity
  ]);

/// The 13 states of `Saudi Arabia` keyed by their id.
const Map<int, Region> saudiArabiaStates = <int, Region>{
    2853: saudiArabiaasirRegion,
    2859: saudiArabiaAlBahahRegion,
    2857: saudiArabiaAlJawfRegion,
    2851: saudiArabiaAlMadinahRegion,
    2861: saudiArabiaAlHypqassimRegion,
    2856: saudiArabiaEasternProvinceRegion,
    2855: saudiArabiaHailRegion,
    2858: saudiArabiaJizanRegion,
    2850: saudiArabiaMakkahRegion,
    2860: saudiArabiaNajranRegion,
    2854: saudiArabiaNorthernBordersRegion,
    2849: saudiArabiaRiyadhRegion,
    2852: saudiArabiaTabukRegion
  };
