/// Access to known geographies in Serbia and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'serbia_cities.dart';

/// The 26 regions of `🇷🇸 Serbia`
const Region serbiaBelgrade = Region(
    id: 3728,
    parentId: 196,
    longitude: 20.4489216,
    latitude: 44.786568,
    name: "Belgrade",
    type: null,
    stateCode: "00",
    cities: []);
const Region serbiaBorDistrict = Region(
    id: 3717,
    parentId: 196,
    longitude: 22.0985086,
    latitude: 44.0698918,
    name: "Bor District",
    type: null,
    stateCode: "14",
    cities: []);
const Region serbiaBranicevoDistrict = Region(
    id: 3732,
    parentId: 196,
    longitude: 21.5446775,
    latitude: 44.6982246,
    name: "Braničevo District",
    type: null,
    stateCode: "11",
    cities: []);
const Region serbiaCentralBanatDistrict = Region(
    id: 3716,
    parentId: 196,
    longitude: 20.6082522,
    latitude: 45.4788485,
    name: "Central Banat District",
    type: null,
    stateCode: "02",
    cities: [
      serbiaCentralBanatDistrictArandelovac,
      serbiaCentralBanatDistrictArilje,
      serbiaCentralBanatDistrictBadovinci,
      serbiaCentralBanatDistrictBajinaBasta,
      serbiaCentralBanatDistrictBanovoPolje,
      serbiaCentralBanatDistrictBaric,
      serbiaCentralBanatDistrictBecmen,
      serbiaCentralBanatDistrictBelgrade,
      serbiaCentralBanatDistrictBelotic,
      serbiaCentralBanatDistrictBiljaca,
      serbiaCentralBanatDistrictBogatic,
      serbiaCentralBanatDistrictBogosavac,
      serbiaCentralBanatDistrictBoljevci,
      serbiaCentralBanatDistrictBor,
      serbiaCentralBanatDistrictBrdarica,
      serbiaCentralBanatDistrictBukor,
      serbiaCentralBanatDistrictCacak,
      serbiaCentralBanatDistrictCajetina,
      serbiaCentralBanatDistrictCicevac,
      serbiaCentralBanatDistrictCokesina,
      serbiaCentralBanatDistrictCrnaBara,
      serbiaCentralBanatDistrictCuprija,
      serbiaCentralBanatDistrictDobanovci,
      serbiaCentralBanatDistrictDobric,
      serbiaCentralBanatDistrictDonjiDobric,
      serbiaCentralBanatDistrictDonjiMilanovac,
      serbiaCentralBanatDistrictDraginje,
      serbiaCentralBanatDistrictDrenovac,
      serbiaCentralBanatDistrictDublje,
      serbiaCentralBanatDistrictDuboka,
      serbiaCentralBanatDistricturici,
      serbiaCentralBanatDistrictGlusci,
      serbiaCentralBanatDistrictGolubac,
      serbiaCentralBanatDistrictGornjaBukovica,
      serbiaCentralBanatDistrictGornjiMilanovac,
      serbiaCentralBanatDistrictGrabovac,
      serbiaCentralBanatDistrictJablanica,
      serbiaCentralBanatDistrictJadranskaLesnica,
      serbiaCentralBanatDistrictJagodina,
      serbiaCentralBanatDistrictJarebice,
      serbiaCentralBanatDistrictJelenca,
      serbiaCentralBanatDistrictJevremovac,
      serbiaCentralBanatDistrictJoseva,
      serbiaCentralBanatDistrictKamenica,
      serbiaCentralBanatDistrictKlenje,
      serbiaCentralBanatDistrictKnjazevac,
      serbiaCentralBanatDistrictKolubara,
      serbiaCentralBanatDistrictKozjak,
      serbiaCentralBanatDistrictKragujevac,
      serbiaCentralBanatDistrictKraljevo,
      serbiaCentralBanatDistrictKrivaja,
      serbiaCentralBanatDistrictKrupanj,
      serbiaCentralBanatDistrictKrusevac,
      serbiaCentralBanatDistrictLagjaEePoshtme,
      serbiaCentralBanatDistrictLapovo,
      serbiaCentralBanatDistrictLazarevac,
      serbiaCentralBanatDistrictLeskovac,
      serbiaCentralBanatDistrictLesnica,
      serbiaCentralBanatDistrictLipnickiSor,
      serbiaCentralBanatDistrictLipolist,
      serbiaCentralBanatDistrictLjig,
      serbiaCentralBanatDistrictLjubovija,
      serbiaCentralBanatDistrictLugavcina,
      serbiaCentralBanatDistrictMacva,
      serbiaCentralBanatDistrictMajdanpek,
      serbiaCentralBanatDistrictMajur,
      serbiaCentralBanatDistrictMalaMostanica,
      serbiaCentralBanatDistrictMaliZvornik,
      serbiaCentralBanatDistrictMetkovic,
      serbiaCentralBanatDistrictMiratovac,
      serbiaCentralBanatDistrictMorava,
      serbiaCentralBanatDistrictNegotin,
      serbiaCentralBanatDistrictNis,
      serbiaCentralBanatDistrictNisava,
      serbiaCentralBanatDistrictNoviPazar,
      serbiaCentralBanatDistrictNovoSelo,
      serbiaCentralBanatDistrictObrenovac,
      serbiaCentralBanatDistrictOsecina,
      serbiaCentralBanatDistrictOsjecenik,
      serbiaCentralBanatDistrictOstruznica,
      serbiaCentralBanatDistrictOvca,
      serbiaCentralBanatDistrictParacin,
      serbiaCentralBanatDistrictPcinja,
      serbiaCentralBanatDistrictPetkovica,
      serbiaCentralBanatDistrictPirot,
      serbiaCentralBanatDistrictPocerskiPricinovic,
      serbiaCentralBanatDistrictPodunavljeDistrict,
      serbiaCentralBanatDistrictPomoravlje,
      serbiaCentralBanatDistrictPozarevac,
      serbiaCentralBanatDistrictPriboj,
      serbiaCentralBanatDistrictPrijepolje,
      serbiaCentralBanatDistrictPrislonica,
      serbiaCentralBanatDistrictPrnjavor,
      serbiaCentralBanatDistrictProkuplje,
      serbiaCentralBanatDistrictRadenka,
      serbiaCentralBanatDistrictRadovnica,
      serbiaCentralBanatDistrictRajince,
      serbiaCentralBanatDistrictRasina,
      serbiaCentralBanatDistrictRaska,
      serbiaCentralBanatDistrictRibari,
      serbiaCentralBanatDistrictRumska,
      serbiaCentralBanatDistrictRusanj,
      serbiaCentralBanatDistrictSabac,
      serbiaCentralBanatDistrictSalasCrnobarski,
      serbiaCentralBanatDistrictSamoljica,
      serbiaCentralBanatDistrictSevarice,
      serbiaCentralBanatDistrictSevica,
      serbiaCentralBanatDistrictSinosevic,
      serbiaCentralBanatDistrictSjenica,
      serbiaCentralBanatDistrictSmederevo,
      serbiaCentralBanatDistrictSmederevskaPalanka,
      serbiaCentralBanatDistrictSokolovica,
      serbiaCentralBanatDistrictSokolovoBrdo,
      serbiaCentralBanatDistrictSremcica,
      serbiaCentralBanatDistrictStepojevac,
      serbiaCentralBanatDistrictStitar,
      serbiaCentralBanatDistrictStubline,
      serbiaCentralBanatDistrictSumadija,
      serbiaCentralBanatDistrictSumulice,
      serbiaCentralBanatDistrictSurcin,
      serbiaCentralBanatDistrictTabanovic,
      serbiaCentralBanatDistrictToplica,
      serbiaCentralBanatDistrictTrsic,
      serbiaCentralBanatDistrictTrstenik,
      serbiaCentralBanatDistrictTurija,
      serbiaCentralBanatDistrictTutin,
      serbiaCentralBanatDistrictUgrinovci,
      serbiaCentralBanatDistrictUmka,
      serbiaCentralBanatDistrictUzice,
      serbiaCentralBanatDistrictUzvece,
      serbiaCentralBanatDistrictValjevo,
      serbiaCentralBanatDistrictVarna,
      serbiaCentralBanatDistrictVelikaMostanica,
      serbiaCentralBanatDistrictVladimirci,
      serbiaCentralBanatDistrictVranic,
      serbiaCentralBanatDistrictVranje,
      serbiaCentralBanatDistrictVrnjackaBanja,
      serbiaCentralBanatDistrictZajecar,
      serbiaCentralBanatDistrictZemun,
      serbiaCentralBanatDistrictZlatibor,
      serbiaCentralBanatDistrictZminjak,
      serbiaCentralBanatDistrictZujince,
      serbiaCentralBanatDistrictZvecka
    ]);
const Region serbiaJablanicaDistrict = Region(
    id: 3715,
    parentId: 196,
    longitude: 21.8129321,
    latitude: 42.948156,
    name: "Jablanica District",
    type: null,
    stateCode: "23",
    cities: []);
const Region serbiaKolubaraDistrict = Region(
    id: 3724,
    parentId: 196,
    longitude: 20.0004305,
    latitude: 44.3509811,
    name: "Kolubara District",
    type: null,
    stateCode: "09",
    cities: []);
const Region serbiaMacvaDistrict = Region(
    id: 3719,
    parentId: 196,
    longitude: 19.5082246,
    latitude: 44.5925314,
    name: "Mačva District",
    type: null,
    stateCode: "08",
    cities: []);
const Region serbiaMoravicaDistrict = Region(
    id: 3727,
    parentId: 196,
    longitude: 20.2904987,
    latitude: 43.84147,
    name: "Moravica District",
    type: null,
    stateCode: "17",
    cities: []);
const Region serbiaNisavaDistrict = Region(
    id: 3722,
    parentId: 196,
    longitude: 21.9322331,
    latitude: 43.3738902,
    name: "Nišava District",
    type: null,
    stateCode: "20",
    cities: []);
const Region serbiaNorthBackaDistrict = Region(
    id: 3714,
    parentId: 196,
    longitude: 19.5907001,
    latitude: 45.9803394,
    name: "North Bačka District",
    type: null,
    stateCode: "01",
    cities: []);
const Region serbiaNorthBanatDistrict = Region(
    id: 3736,
    parentId: 196,
    longitude: 19.9993417,
    latitude: 45.906839,
    name: "North Banat District",
    type: null,
    stateCode: "03",
    cities: []);
const Region serbiaPcinjaDistrict = Region(
    id: 3721,
    parentId: 196,
    longitude: 22.1430215,
    latitude: 42.5836362,
    name: "Pčinja District",
    type: null,
    stateCode: "24",
    cities: []);
const Region serbiaPirotDistrict = Region(
    id: 3712,
    parentId: 196,
    longitude: 22.5983044,
    latitude: 43.0874036,
    name: "Pirot District",
    type: null,
    stateCode: "22",
    cities: []);
const Region serbiaPodunavljeDistrict = Region(
    id: 3741,
    parentId: 196,
    longitude: 20.9901426,
    latitude: 44.4729156,
    name: "Podunavlje District",
    type: null,
    stateCode: "10",
    cities: []);
const Region serbiaPomoravljeDistrict = Region(
    id: 3737,
    parentId: 196,
    longitude: 21.271353,
    latitude: 43.9591379,
    name: "Pomoravlje District",
    type: null,
    stateCode: "13",
    cities: []);
const Region serbiaRasinaDistrict = Region(
    id: 3720,
    parentId: 196,
    longitude: 21.1588178,
    latitude: 43.5263525,
    name: "Rasina District",
    type: null,
    stateCode: "19",
    cities: []);
const Region serbiaRaskaDistrict = Region(
    id: 3725,
    parentId: 196,
    longitude: 20.5734005,
    latitude: 43.3373461,
    name: "Raška District",
    type: null,
    stateCode: "18",
    cities: []);
const Region serbiaSouthBackaDistrict = Region(
    id: 3711,
    parentId: 196,
    longitude: 19.6976187,
    latitude: 45.4890344,
    name: "South Bačka District",
    type: null,
    stateCode: "06",
    cities: []);
const Region serbiaSouthBanatDistrict = Region(
    id: 3713,
    parentId: 196,
    longitude: 21.0542509,
    latitude: 45.0027457,
    name: "South Banat District",
    type: null,
    stateCode: "04",
    cities: []);
const Region serbiaSremDistrict = Region(
    id: 3740,
    parentId: 196,
    longitude: 19.8013773,
    latitude: 45.0029171,
    name: "Srem District",
    type: null,
    stateCode: "07",
    cities: []);
const Region serbiaSumadijaDistrict = Region(
    id: 3734,
    parentId: 196,
    longitude: 20.7856565,
    latitude: 44.2050678,
    name: "Šumadija District",
    type: null,
    stateCode: "12",
    cities: []);
const Region serbiaToplicaDistrict = Region(
    id: 3718,
    parentId: 196,
    longitude: 21.3407762,
    latitude: 43.1906592,
    name: "Toplica District",
    type: null,
    stateCode: "21",
    cities: []);
const Region serbiaVojvodina = Region(
    id: 3733,
    parentId: 196,
    longitude: 19.8319338,
    latitude: 45.2608651,
    name: "Vojvodina",
    type: null,
    stateCode: "VO",
    cities: [
      serbiaVojvodinaAdorjan,
      serbiaVojvodinaAleksandrovo,
      serbiaVojvodinaAlibunar,
      serbiaVojvodinaApatin,
      serbiaVojvodinaAradac,
      serbiaVojvodinaBackaPalanka,
      serbiaVojvodinaBackaTopola,
      serbiaVojvodinaBackiBreg,
      serbiaVojvodinaBackiPetrovac,
      serbiaVojvodinaBackoGradiste,
      serbiaVojvodinaBackoPetrovoSelo,
      serbiaVojvodinaBanatskaTopola,
      serbiaVojvodinaBanatskiDespotovac,
      serbiaVojvodinaBanatskiDvor,
      serbiaVojvodinaBanatskiKarlovac,
      serbiaVojvodinaBanatskoKaradordevo,
      serbiaVojvodinaBanatskoVelikoSelo,
      serbiaVojvodinaBaranda,
      serbiaVojvodinaBarice,
      serbiaVojvodinaBasaid,
      serbiaVojvodinaBecej,
      serbiaVojvodinaBelaCrkva,
      serbiaVojvodinaBelegis,
      serbiaVojvodinaBeloBlato,
      serbiaVojvodinaBeska,
      serbiaVojvodinaBocar,
      serbiaVojvodinaBogojevo,
      serbiaVojvodinaBoka,
      serbiaVojvodinaBosut,
      serbiaVojvodinaBotos,
      serbiaVojvodinaBudanovci,
      serbiaVojvodinaCelarevo,
      serbiaVojvodinaCenta,
      serbiaVojvodinaCestereg,
      serbiaVojvodinaCoka,
      serbiaVojvodinaCortanovci,
      serbiaVojvodinaCrepaja,
      serbiaVojvodinaCurug,
      serbiaVojvodinaDebeljaca,
      serbiaVojvodinaDespotovo,
      serbiaVojvodinaDobrica,
      serbiaVojvodinaDoroslovo,
      serbiaVojvodinaurdevo,
      serbiaVojvodinaEcka,
      serbiaVojvodinaElemir,
      serbiaVojvodinaFarkazdin,
      serbiaVojvodinaGakovo,
      serbiaVojvodinaGardinovci,
      serbiaVojvodinaGlozan,
      serbiaVojvodinaGolubinci,
      serbiaVojvodinaGornjiBreg,
      serbiaVojvodinaGrabovci,
      serbiaVojvodinaGudurica,
      serbiaVojvodinaHajducica,
      serbiaVojvodinaHetin,
      serbiaVojvodinaHrtkovci,
      serbiaVojvodinaIdvor,
      serbiaVojvodinaIlandza,
      serbiaVojvodinaIndija,
      serbiaVojvodinaIrig,
      serbiaVojvodinaIzbiste,
      serbiaVojvodinaJanosik,
      serbiaVojvodinaJarak,
      serbiaVojvodinaJarkovac,
      serbiaVojvodinaJasaTomic,
      serbiaVojvodinaJazovo,
      serbiaVojvodinaJermenovci,
      serbiaVojvodinaKanjiza,
      serbiaVojvodinaKikinda,
      serbiaVojvodinaKisac,
      serbiaVojvodinaKlek,
      serbiaVojvodinaKlenak,
      serbiaVojvodinaKnicanin,
      serbiaVojvodinaKolut,
      serbiaVojvodinaKonak,
      serbiaVojvodinaKovacica,
      serbiaVojvodinaKovilj,
      serbiaVojvodinaKovin,
      serbiaVojvodinaKozjak,
      serbiaVojvodinaKrajisnik,
      serbiaVojvodinaKrcedin,
      serbiaVojvodinaKulpin,
      serbiaVojvodinaKumane,
      serbiaVojvodinaKupinovo,
      serbiaVojvodinaKupusina,
      serbiaVojvodinaKustilj,
      serbiaVojvodinaLazarevo,
      serbiaVojvodinaLjukovo,
      serbiaVojvodinaLok,
      serbiaVojvodinaLokve,
      serbiaVojvodinaLukicevo,
      serbiaVojvodinaMacvanskaMitrovica,
      serbiaVojvodinaMaglic,
      serbiaVojvodinaMargita,
      serbiaVojvodinaMeda,
      serbiaVojvodinaMelenci,
      serbiaVojvodinaMihajlovo,
      serbiaVojvodinaMokrin,
      serbiaVojvodinaMol,
      serbiaVojvodinaMosorin,
      serbiaVojvodinaNakovo,
      serbiaVojvodinaNeuzina,
      serbiaVojvodinaNikinci,
      serbiaVojvodinaNikolinci,
      serbiaVojvodinaNovaCrnja,
      serbiaVojvodinaNovaPazova,
      serbiaVojvodinaNoviBanovci,
      serbiaVojvodinaNoviItebej,
      serbiaVojvodinaNoviKarlovci,
      serbiaVojvodinaNoviKnezevac,
      serbiaVojvodinaNoviKozarci,
      serbiaVojvodinaNoviSad,
      serbiaVojvodinaNoviSlankamen,
      serbiaVojvodinaNovoMilosevo,
      serbiaVojvodinaObrovac,
      serbiaVojvodinaOpovo,
      serbiaVojvodinaOrlovat,
      serbiaVojvodinaOstojicevo,
      serbiaVojvodinaPadej,
      serbiaVojvodinaPadina,
      serbiaVojvodinaPancevo,
      serbiaVojvodinaPavlis,
      serbiaVojvodinaPecinci,
      serbiaVojvodinaPerlez,
      serbiaVojvodinaPetrovaradin,
      serbiaVojvodinaPlandiste,
      serbiaVojvodinaPlaticevo,
      serbiaVojvodinaPrigrevica,
      serbiaVojvodinaPutinci,
      serbiaVojvodinaRadenkovic,
      serbiaVojvodinaRadojevo,
      serbiaVojvodinaRavniTopolovac,
      serbiaVojvodinaRavnje,
      serbiaVojvodinaRavnoSelo,
      serbiaVojvodinaRidica,
      serbiaVojvodinaRuma,
      serbiaVojvodinaRumenka,
      serbiaVojvodinaRuskoSelo,
      serbiaVojvodinaSajan,
      serbiaVojvodinaSajkas,
      serbiaVojvodinaSakule,
      serbiaVojvodinaSalasNocajski,
      serbiaVojvodinaSamos,
      serbiaVojvodinaSanad,
      serbiaVojvodinaSasinci,
      serbiaVojvodinaSecanj,
      serbiaVojvodinaSefkerin,
      serbiaVojvodinaSeleus,
      serbiaVojvodinaSenta,
      serbiaVojvodinaSimanovci,
      serbiaVojvodinaSombor,
      serbiaVojvodinaSonta,
      serbiaVojvodinaSremskaMitrovica,
      serbiaVojvodinaSremskiKarlovci,
      serbiaVojvodinaSrpskaCrnja,
      serbiaVojvodinaSrpskiItebej,
      serbiaVojvodinaStajicevo,
      serbiaVojvodinaStanisic,
      serbiaVojvodinaStaraPazova,
      serbiaVojvodinaStariBanovci,
      serbiaVojvodinaStariLec,
      serbiaVojvodinaStepanovicevo,
      serbiaVojvodinaSubotica,
      serbiaVojvodinaSurduk,
      serbiaVojvodinaSutjeska,
      serbiaVojvodinaTaras,
      serbiaVojvodinaTiszahegyes,
      serbiaVojvodinaTitel,
      serbiaVojvodinaToba,
      serbiaVojvodinaTomasevac,
      serbiaVojvodinaTorak,
      serbiaVojvodinaTorda,
      serbiaVojvodinaUljma,
      serbiaVojvodinaUzdin,
      serbiaVojvodinaVelikaGreda,
      serbiaVojvodinaVelikiGaj,
      serbiaVojvodinaVelikoSrediste,
      serbiaVojvodinaVeternik,
      serbiaVojvodinaVilovo,
      serbiaVojvodinaVisnjicevo,
      serbiaVojvodinaVladimirovac,
      serbiaVojvodinaVlajkovac,
      serbiaVojvodinaVojka,
      serbiaVojvodinaVojvodaStepa,
      serbiaVojvodinaVrbas,
      serbiaVojvodinaVrdnik,
      serbiaVojvodinaVrsac,
      serbiaVojvodinaZabalj,
      serbiaVojvodinaZitiste,
      serbiaVojvodinaZmajevo,
      serbiaVojvodinaZrenjanin
    ]);
const Region serbiaWestBackaDistrict = Region(
    id: 3726,
    parentId: 196,
    longitude: 19.1897364,
    latitude: 45.7355385,
    name: "West Bačka District",
    type: null,
    stateCode: "05",
    cities: []);
const Region serbiaZajecarDistrict = Region(
    id: 3731,
    parentId: 196,
    longitude: 22.2738011,
    latitude: 43.9015048,
    name: "Zaječar District",
    type: null,
    stateCode: "15",
    cities: []);
const Region serbiaZlatiborDistrict = Region(
    id: 3729,
    parentId: 196,
    longitude: 19.7101455,
    latitude: 43.645417,
    name: "Zlatibor District",
    type: null,
    stateCode: "16",
    cities: []);

const serbiaStates = <int, Region>{
  3728: serbiaBelgrade,
  3717: serbiaBorDistrict,
  3732: serbiaBranicevoDistrict,
  3716: serbiaCentralBanatDistrict,
  3715: serbiaJablanicaDistrict,
  3724: serbiaKolubaraDistrict,
  3719: serbiaMacvaDistrict,
  3727: serbiaMoravicaDistrict,
  3722: serbiaNisavaDistrict,
  3714: serbiaNorthBackaDistrict,
  3736: serbiaNorthBanatDistrict,
  3721: serbiaPcinjaDistrict,
  3712: serbiaPirotDistrict,
  3741: serbiaPodunavljeDistrict,
  3737: serbiaPomoravljeDistrict,
  3720: serbiaRasinaDistrict,
  3725: serbiaRaskaDistrict,
  3711: serbiaSouthBackaDistrict,
  3713: serbiaSouthBanatDistrict,
  3740: serbiaSremDistrict,
  3734: serbiaSumadijaDistrict,
  3718: serbiaToplicaDistrict,
  3733: serbiaVojvodina,
  3726: serbiaWestBackaDistrict,
  3731: serbiaZajecarDistrict,
  3729: serbiaZlatiborDistrict
};
