/// Access to known geographies in Slovakia and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'slovakia_cities.dart';

/// The 8 regions of `🇸🇰 Slovakia`
const Region slovakiaBanskaBystricaRegion = Region(
    id: 4352,
    parentId: 200,
    longitude: 19.382874,
    latitude: 48.5312499,
    name: "Banská Bystrica Region",
    type: null,
    stateCode: "BC",
    cities: [
      slovakiaBanskaBystricaRegionBanskaBystrica,
      slovakiaBanskaBystricaRegionBanskaStiavnica,
      slovakiaBanskaBystricaRegionBrezno,
      slovakiaBanskaBystricaRegionCiernyBalog,
      slovakiaBanskaBystricaRegionDetva,
      slovakiaBanskaBystricaRegionDudince,
      slovakiaBanskaBystricaRegionFilakovo,
      slovakiaBanskaBystricaRegionHrinova,
      slovakiaBanskaBystricaRegionHrochotSlovakia,
      slovakiaBanskaBystricaRegionKovacova,
      slovakiaBanskaBystricaRegionKremnica,
      slovakiaBanskaBystricaRegionKrupina,
      slovakiaBanskaBystricaRegionLucenec,
      slovakiaBanskaBystricaRegionNovaBana,
      slovakiaBanskaBystricaRegionOkresBanskaBystrica,
      slovakiaBanskaBystricaRegionOkresBanskaStiavnica,
      slovakiaBanskaBystricaRegionOkresBrezno,
      slovakiaBanskaBystricaRegionOkresDetva,
      slovakiaBanskaBystricaRegionOkresKrupina,
      slovakiaBanskaBystricaRegionOkresLucenec,
      slovakiaBanskaBystricaRegionOkresPoltar,
      slovakiaBanskaBystricaRegionOkresRevuca,
      slovakiaBanskaBystricaRegionOkresVelkyKrtis,
      slovakiaBanskaBystricaRegionOkresZarnovica,
      slovakiaBanskaBystricaRegionOkresZiarNnadHronom,
      slovakiaBanskaBystricaRegionOkresZvolen,
      slovakiaBanskaBystricaRegionPoltar,
      slovakiaBanskaBystricaRegionRevuca,
      slovakiaBanskaBystricaRegionRimavskaSobota,
      slovakiaBanskaBystricaRegionSvatyAnton,
      slovakiaBanskaBystricaRegionTisovec,
      slovakiaBanskaBystricaRegionVelkyKrtis,
      slovakiaBanskaBystricaRegionZarnovica,
      slovakiaBanskaBystricaRegionZiarNnadHronom,
      slovakiaBanskaBystricaRegionZvolen
    ]);
const Region slovakiaBratislavaRegion = Region(
    id: 4356,
    parentId: 200,
    longitude: 17.1973299,
    latitude: 48.3118304,
    name: "Bratislava Region",
    type: null,
    stateCode: "BL",
    cities: [
      slovakiaBratislavaRegionBratislava,
      slovakiaBratislavaRegionBratislavaHypVajnory,
      slovakiaBratislavaRegionDunajskaLuzna,
      slovakiaBratislavaRegionIvankaPpriDunaji,
      slovakiaBratislavaRegionMalacky,
      slovakiaBratislavaRegionMarianka,
      slovakiaBratislavaRegionModra,
      slovakiaBratislavaRegionOkresBratislavaI,
      slovakiaBratislavaRegionOkresBratislavaII,
      slovakiaBratislavaRegionOkresBratislavaIII,
      slovakiaBratislavaRegionOkresBratislavaIV,
      slovakiaBratislavaRegionOkresBratislavaV,
      slovakiaBratislavaRegionOkresMalacky,
      slovakiaBratislavaRegionOkresPezinok,
      slovakiaBratislavaRegionOkresSenec,
      slovakiaBratislavaRegionPezinok,
      slovakiaBratislavaRegionSenec,
      slovakiaBratislavaRegionStupava,
      slovakiaBratislavaRegionSvatyJur,
      slovakiaBratislavaRegionVinosady
    ]);
const Region slovakiaKosiceRegion = Region(
    id: 4353,
    parentId: 200,
    longitude: 21.0834225,
    latitude: 48.6375737,
    name: "Košice Region",
    type: null,
    stateCode: "KI",
    cities: [
      slovakiaKosiceRegionCiernaNnadTisou,
      slovakiaKosiceRegionDobsina,
      slovakiaKosiceRegionGelnica,
      slovakiaKosiceRegionKavecany,
      slovakiaKosiceRegionKosice,
      slovakiaKosiceRegionKosiceI,
      slovakiaKosiceRegionKosiceII,
      slovakiaKosiceRegionKosiceIII,
      slovakiaKosiceRegionKosiceIV,
      slovakiaKosiceRegionKrompachy,
      slovakiaKosiceRegionMedzev,
      slovakiaKosiceRegionMichalovce,
      slovakiaKosiceRegionMoldavaNnadBodvou,
      slovakiaKosiceRegionOkresGelnica,
      slovakiaKosiceRegionOkresKosiceHypokolie,
      slovakiaKosiceRegionOkresMichalovce,
      slovakiaKosiceRegionOkresRoznava,
      slovakiaKosiceRegionOkresSobrance,
      slovakiaKosiceRegionOkresSpisskaNovaVes,
      slovakiaKosiceRegionOkresTrebisov,
      slovakiaKosiceRegionRoznava,
      slovakiaKosiceRegionSecovce,
      slovakiaKosiceRegionSobrance,
      slovakiaKosiceRegionSpisskaNovaVes,
      slovakiaKosiceRegionStrazske,
      slovakiaKosiceRegionTrebisov,
      slovakiaKosiceRegionVinne,
      slovakiaKosiceRegionZehra
    ]);
const Region slovakiaNitraRegion = Region(
    id: 4357,
    parentId: 200,
    longitude: 18.5416504,
    latitude: 48.0143765,
    name: "Nitra Region",
    type: null,
    stateCode: "NI",
    cities: [
      slovakiaNitraRegionHurbanovo,
      slovakiaNitraRegionKolarovo,
      slovakiaNitraRegionKomarno,
      slovakiaNitraRegionLevice,
      slovakiaNitraRegionNitra,
      slovakiaNitraRegionNoveZamky,
      slovakiaNitraRegionOkresKomarno,
      slovakiaNitraRegionOkresLevice,
      slovakiaNitraRegionOkresNitra,
      slovakiaNitraRegionOkresNoveZamky,
      slovakiaNitraRegionOkresSala,
      slovakiaNitraRegionOkresTopolcany,
      slovakiaNitraRegionOkresZlateMoravce,
      slovakiaNitraRegionSahy,
      slovakiaNitraRegionSala,
      slovakiaNitraRegionSturovo,
      slovakiaNitraRegionSurany,
      slovakiaNitraRegionSvodin,
      slovakiaNitraRegionTlmace,
      slovakiaNitraRegionTopolcany,
      slovakiaNitraRegionVrable,
      slovakiaNitraRegionZeliezovce,
      slovakiaNitraRegionZlateMoravce
    ]);
const Region slovakiaPresovRegion = Region(
    id: 4354,
    parentId: 200,
    longitude: 21.3742001,
    latitude: 49.1716773,
    name: "Prešov Region",
    type: null,
    stateCode: "PV",
    cities: [
      slovakiaPresovRegionBardejov,
      slovakiaPresovRegionChlmec,
      slovakiaPresovRegionGiraltovce,
      slovakiaPresovRegionHumenne,
      slovakiaPresovRegionKezmarok,
      slovakiaPresovRegionLevoca,
      slovakiaPresovRegionLipany,
      slovakiaPresovRegionLubica,
      slovakiaPresovRegionMedzilaborce,
      slovakiaPresovRegionNovaLesna,
      slovakiaPresovRegionOkresBardejov,
      slovakiaPresovRegionOkresHumenne,
      slovakiaPresovRegionOkresKezmarok,
      slovakiaPresovRegionOkresLevoca,
      slovakiaPresovRegionOkresMedzilaborce,
      slovakiaPresovRegionOkresPoprad,
      slovakiaPresovRegionOkresPresov,
      slovakiaPresovRegionOkresSabinov,
      slovakiaPresovRegionOkresSnina,
      slovakiaPresovRegionOkresStaraLubovna,
      slovakiaPresovRegionOkresStropkov,
      slovakiaPresovRegionOkresSvidnik,
      slovakiaPresovRegionOkresVranovNnadToplou,
      slovakiaPresovRegionPodolinec,
      slovakiaPresovRegionPoprad,
      slovakiaPresovRegionPresov,
      slovakiaPresovRegionSabinov,
      slovakiaPresovRegionSnina,
      slovakiaPresovRegionSpisskaBela,
      slovakiaPresovRegionSpisskePodhradie,
      slovakiaPresovRegionStaraLubovna,
      slovakiaPresovRegionStrba,
      slovakiaPresovRegionStropkov,
      slovakiaPresovRegionSvidnik,
      slovakiaPresovRegionSvit,
      slovakiaPresovRegionVranovNnadToplou,
      slovakiaPresovRegionVrbov,
      slovakiaPresovRegionVysneRuzbachy,
      slovakiaPresovRegionVysokeTatry,
      slovakiaPresovRegionZdiar
    ]);
const Region slovakiaTrencinRegion = Region(
    id: 4358,
    parentId: 200,
    longitude: 18.2324026,
    latitude: 48.8086758,
    name: "Trenčín Region",
    type: null,
    stateCode: "TC",
    cities: [
      slovakiaTrencinRegionBanovceNnadBebravou,
      slovakiaTrencinRegionBojnice,
      slovakiaTrencinRegionBrezovaPpodBradlom,
      slovakiaTrencinRegionCachtice,
      slovakiaTrencinRegionDubnicaNnadVahom,
      slovakiaTrencinRegionHandlova,
      slovakiaTrencinRegionIlava,
      slovakiaTrencinRegionLehotaPpodVtacnikom,
      slovakiaTrencinRegionMyjava,
      slovakiaTrencinRegionNemsova,
      slovakiaTrencinRegionNovaDubnica,
      slovakiaTrencinRegionNovaky,
      slovakiaTrencinRegionNoveMestoNnadVahom,
      slovakiaTrencinRegionOkresBanovceNnadBebravou,
      slovakiaTrencinRegionOkresIlava,
      slovakiaTrencinRegionOkresMyjava,
      slovakiaTrencinRegionOkresNoveMestoNnadVahom,
      slovakiaTrencinRegionOkresPartizanske,
      slovakiaTrencinRegionOkresPovazskaBystrica,
      slovakiaTrencinRegionOkresPrievidza,
      slovakiaTrencinRegionOkresPuchov,
      slovakiaTrencinRegionOkresTrencin,
      slovakiaTrencinRegionPartizanske,
      slovakiaTrencinRegionPovazskaBystrica,
      slovakiaTrencinRegionPrievidza,
      slovakiaTrencinRegionPuchov,
      slovakiaTrencinRegionStaraTura,
      slovakiaTrencinRegionTrencianskeTeplice,
      slovakiaTrencinRegionTrencin
    ]);
const Region slovakiaTrnavaRegion = Region(
    id: 4355,
    parentId: 200,
    longitude: 17.7216205,
    latitude: 48.3943898,
    name: "Trnava Region",
    type: null,
    stateCode: "TA",
    cities: [
      slovakiaTrnavaRegionDunajskaStreda,
      slovakiaTrnavaRegionGabcikovo,
      slovakiaTrnavaRegionGalanta,
      slovakiaTrnavaRegionGbely,
      slovakiaTrnavaRegionHlohovec,
      slovakiaTrnavaRegionHolic,
      slovakiaTrnavaRegionLeopoldov,
      slovakiaTrnavaRegionOkresDunajskaStreda,
      slovakiaTrnavaRegionOkresGalanta,
      slovakiaTrnavaRegionOkresHlohovec,
      slovakiaTrnavaRegionOkresPiestany,
      slovakiaTrnavaRegionOkresSenica,
      slovakiaTrnavaRegionOkresSkalica,
      slovakiaTrnavaRegionOkresTrnava,
      slovakiaTrnavaRegionPiestany,
      slovakiaTrnavaRegionSamorin,
      slovakiaTrnavaRegionSenica,
      slovakiaTrnavaRegionSkalica,
      slovakiaTrnavaRegionSladkovicovo,
      slovakiaTrnavaRegionSmolenice,
      slovakiaTrnavaRegionTrnava,
      slovakiaTrnavaRegionVelkyMeder,
      slovakiaTrnavaRegionVrbove
    ]);
const Region slovakiaZilinaRegion = Region(
    id: 4359,
    parentId: 200,
    longitude: 19.3645733,
    latitude: 49.2031435,
    name: "Žilina Region",
    type: null,
    stateCode: "ZI",
    cities: [
      slovakiaZilinaRegionBytca,
      slovakiaZilinaRegionCadca,
      slovakiaZilinaRegionDolnyKubin,
      slovakiaZilinaRegionHybe,
      slovakiaZilinaRegionKrasnany,
      slovakiaZilinaRegionKysuckeNoveMesto,
      slovakiaZilinaRegionLiptovskyHradok,
      slovakiaZilinaRegionLiptovskyMikulas,
      slovakiaZilinaRegionLucky,
      slovakiaZilinaRegionMartin,
      slovakiaZilinaRegionNamestovo,
      slovakiaZilinaRegionNizna,
      slovakiaZilinaRegionOkresBytca,
      slovakiaZilinaRegionOkresCadca,
      slovakiaZilinaRegionOkresDolnyKubin,
      slovakiaZilinaRegionOkresKysuckeNoveMesto,
      slovakiaZilinaRegionOkresLiptovskyMikulas,
      slovakiaZilinaRegionOkresMartin,
      slovakiaZilinaRegionOkresNamestovo,
      slovakiaZilinaRegionOkresRuzomberok,
      slovakiaZilinaRegionOkresTurcianskeTeplice,
      slovakiaZilinaRegionOkresTvrdosin,
      slovakiaZilinaRegionOkresZilina,
      slovakiaZilinaRegionOravskaLesna,
      slovakiaZilinaRegionOravskyPodzamok,
      slovakiaZilinaRegionPribylina,
      slovakiaZilinaRegionRajec,
      slovakiaZilinaRegionRuzomberok,
      slovakiaZilinaRegionTerchova,
      slovakiaZilinaRegionTrstena,
      slovakiaZilinaRegionTurcianskeTeplice,
      slovakiaZilinaRegionTurzovka,
      slovakiaZilinaRegionTvrdosin,
      slovakiaZilinaRegionVrutky,
      slovakiaZilinaRegionZilina
    ]);

const slovakiaStates = <int, Region>{
  4352: slovakiaBanskaBystricaRegion,
  4356: slovakiaBratislavaRegion,
  4353: slovakiaKosiceRegion,
  4357: slovakiaNitraRegion,
  4354: slovakiaPresovRegion,
  4358: slovakiaTrencinRegion,
  4355: slovakiaTrnavaRegion,
  4359: slovakiaZilinaRegion
};
