/// Access to known geographies in Slovenia and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.
library;

import '../base.dart';
import 'slovenia_states.dart';

/// The country of `Slovenia`, and its 211 states
const Country slovenia = Country(
  id: 201,
  name: "Slovenia",
  longitude: 14.81666666,
  latitude: 46.11666666,
  capital: "Ljubljana",
  currency: "EUR",
  currencySymbol: "€",
  currencyName: "Euro",
  emoji: "🇸🇮",
  emojiU: "U+1F1F8 U+1F1EE",
  iso2: "SI",
  iso3: "SVN",
  native: "Slovenija",
  numericCode: "705",
  nationality: "Slovenian, Slovene",
  phoneCode: "386",
  region: "Europe",
  subregion: "Southern Europe",
  tld: ".si",
  states: [
    sloveniaAjdovscinaMunicipality,
    sloveniaAnkaranMunicipality,
    sloveniaBeltinciMunicipality,
    sloveniaBenediktMunicipality,
    sloveniaBistricaObSotliMunicipality,
    sloveniaBledMunicipality,
    sloveniaBlokeMunicipality,
    sloveniaBohinjMunicipality,
    sloveniaBorovnicaMunicipality,
    sloveniaBovecMunicipality,
    sloveniaBraslovceMunicipality,
    sloveniaBrdaMunicipality,
    sloveniaBreziceMunicipality,
    sloveniaBrezovicaMunicipality,
    sloveniaCankovaMunicipality,
    sloveniaCerkljeNaGorenjskemMunicipality,
    sloveniaCerknicaMunicipality,
    sloveniaCerknoMunicipality,
    sloveniaCerkvenjakMunicipality,
    sloveniaCityMunicipalityOfCelje,
    sloveniaCityMunicipalityOfNovoMesto,
    sloveniaCrensovciMunicipality,
    sloveniaCrnaNaKoroskemMunicipality,
    sloveniaCrnomeljMunicipality,
    sloveniaDestrnikMunicipality,
    sloveniaDivacaMunicipality,
    sloveniaDobjeMunicipality,
    sloveniaDobrepoljeMunicipality,
    sloveniaDobrnaMunicipality,
    sloveniaDobrovapolhovGradecMunicipality,
    sloveniaDobrovnikMunicipality,
    sloveniaDolPriLjubljaniMunicipality,
    sloveniaDolenjskeTopliceMunicipality,
    sloveniaDomzaleMunicipality,
    sloveniaDornavaMunicipality,
    sloveniaDravogradMunicipality,
    sloveniaDuplekMunicipality,
    sloveniaGorenjaVaspoljaneMunicipality,
    sloveniaGorisnicaMunicipality,
    sloveniaGorjeMunicipality,
    sloveniaGornjaRadgonaMunicipality,
    sloveniaGornjiGradMunicipality,
    sloveniaGornjiPetrovciMunicipality,
    sloveniaGradMunicipality,
    sloveniaGrosupljeMunicipality,
    sloveniaHajdinaMunicipality,
    sloveniaHoceslivnicaMunicipality,
    sloveniaHodosMunicipality,
    sloveniaHorjulMunicipality,
    sloveniaHrastnikMunicipality,
    sloveniaHrpeljekozinaMunicipality,
    sloveniaIdrijaMunicipality,
    sloveniaIgMunicipality,
    sloveniaIvancnaGoricaMunicipality,
    sloveniaIzolaMunicipality,
    sloveniaJeseniceMunicipality,
    sloveniaJezerskoMunicipality,
    sloveniaJursinciMunicipality,
    sloveniaKamnikMunicipality,
    sloveniaKanalObSociMunicipality,
    sloveniaKidricevoMunicipality,
    sloveniaKobaridMunicipality,
    sloveniaKobiljeMunicipality,
    sloveniaKocevjeMunicipality,
    sloveniaKomenMunicipality,
    sloveniaKomendaMunicipality,
    sloveniaKoperCityMunicipality,
    sloveniaKostanjevicaNaKrkiMunicipality,
    sloveniaKostelMunicipality,
    sloveniaKozjeMunicipality,
    sloveniaKranjCityMunicipality,
    sloveniaKranjskaGoraMunicipality,
    sloveniaKrizevciMunicipality,
    sloveniaKungota,
    sloveniaKuzmaMunicipality,
    sloveniaLaskoMunicipality,
    sloveniaLenartMunicipality,
    sloveniaLendavaMunicipality,
    sloveniaLitijaMunicipality,
    sloveniaLjubljanaCityMunicipality,
    sloveniaLjubnoMunicipality,
    sloveniaLjutomerMunicipality,
    sloveniaLogdragomerMunicipality,
    sloveniaLogatecMunicipality,
    sloveniaLoskaDolinaMunicipality,
    sloveniaLoskiPotokMunicipality,
    sloveniaLovrencNaPohorjuMunicipality,
    sloveniaLuceMunicipality,
    sloveniaLukovicaMunicipality,
    sloveniaMajsperkMunicipality,
    sloveniaMakoleMunicipality,
    sloveniaMariborCityMunicipality,
    sloveniaMarkovciMunicipality,
    sloveniaMedvodeMunicipality,
    sloveniaMengesMunicipality,
    sloveniaMetlikaMunicipality,
    sloveniaMezicaMunicipality,
    sloveniaMiklavzNaDravskemPoljuMunicipality,
    sloveniaMirenkostanjevicaMunicipality,
    sloveniaMirnaMunicipality,
    sloveniaMirnaPecMunicipality,
    sloveniaMislinjaMunicipality,
    sloveniaMokronogtrebelnoMunicipality,
    sloveniaMoravceMunicipality,
    sloveniaMoravskeTopliceMunicipality,
    sloveniaMozirjeMunicipality,
    sloveniaMunicipalityOfApace,
    sloveniaMunicipalityOfCirkulane,
    sloveniaMunicipalityOfIlirskaBistrica,
    sloveniaMunicipalityOfKrsko,
    sloveniaMunicipalityOfSkofljica,
    sloveniaMurskaSobotaCityMunicipality,
    sloveniaMutaMunicipality,
    sloveniaNakloMunicipality,
    sloveniaNazarjeMunicipality,
    sloveniaNovaGoricaCityMunicipality,
    sloveniaOdranciMunicipality,
    sloveniaOplotnica,
    sloveniaOrmozMunicipality,
    sloveniaOsilnicaMunicipality,
    sloveniaPesnicaMunicipality,
    sloveniaPiranMunicipality,
    sloveniaPivkaMunicipality,
    sloveniaPodcetrtekMunicipality,
    sloveniaPodlehnikMunicipality,
    sloveniaPodvelkaMunicipality,
    sloveniaPoljcaneMunicipality,
    sloveniaPolzelaMunicipality,
    sloveniaPostojnaMunicipality,
    sloveniaPreboldMunicipality,
    sloveniaPreddvorMunicipality,
    sloveniaPrevaljeMunicipality,
    sloveniaPtujCityMunicipality,
    sloveniaPuconciMunicipality,
    sloveniaRaceframMunicipality,
    sloveniaRadeceMunicipality,
    sloveniaRadenciMunicipality,
    sloveniaRadljeObDraviMunicipality,
    sloveniaRadovljicaMunicipality,
    sloveniaRavneNaKoroskemMunicipality,
    sloveniaRazkrizjeMunicipality,
    sloveniaRecicaObSavinjiMunicipality,
    sloveniaRencevogrskoMunicipality,
    sloveniaRibnicaMunicipality,
    sloveniaRibnicaNaPohorjuMunicipality,
    sloveniaRogaskaSlatinaMunicipality,
    sloveniaRogasovciMunicipality,
    sloveniaRogatecMunicipality,
    sloveniaRuseMunicipality,
    sloveniaSalovciMunicipality,
    sloveniaSelnicaObDraviMunicipality,
    sloveniaSemicMunicipality,
    sloveniaSempetervrtojbaMunicipality,
    sloveniaSencurMunicipality,
    sloveniaSentiljMunicipality,
    sloveniaSentjernejMunicipality,
    sloveniaSentjurMunicipality,
    sloveniaSentrupertMunicipality,
    sloveniaSevnicaMunicipality,
    sloveniaSezanaMunicipality,
    sloveniaSkocjanMunicipality,
    sloveniaSkofjaLokaMunicipality,
    sloveniaSlovenjGradecCityMunicipality,
    sloveniaSlovenskaBistricaMunicipality,
    sloveniaSlovenskeKonjiceMunicipality,
    sloveniaSmarjePriJelsahMunicipality,
    sloveniaSmarjeskeTopliceMunicipality,
    sloveniaSmartnoObPakiMunicipality,
    sloveniaSmartnoPriLitijiMunicipality,
    sloveniaSodrazicaMunicipality,
    sloveniaSolcavaMunicipality,
    sloveniaSostanjMunicipality,
    sloveniaSredisceObDravi,
    sloveniaStarseMunicipality,
    sloveniaStoreMunicipality,
    sloveniaStrazaMunicipality,
    sloveniaSvetaAnaMunicipality,
    sloveniaSvetaTrojicaVSlovenskihGoricahMunicipality,
    sloveniaSvetiAndrazVSlovenskihGoricahMunicipality,
    sloveniaSvetiJurijObScavniciMunicipality,
    sloveniaSvetiJurijVSlovenskihGoricahMunicipality,
    sloveniaSvetiTomazMunicipality,
    sloveniaTaborMunicipality,
    sloveniaTisinaMunicipality,
    sloveniaTolminMunicipality,
    sloveniaTrbovljeMunicipality,
    sloveniaTrebnjeMunicipality,
    sloveniaTrnovskaVasMunicipality,
    sloveniaTrzicMunicipality,
    sloveniaTrzinMunicipality,
    sloveniaTurnisceMunicipality,
    sloveniaVelikaPolanaMunicipality,
    sloveniaVelikeLasceMunicipality,
    sloveniaVerzejMunicipality,
    sloveniaVidemMunicipality,
    sloveniaVipavaMunicipality,
    sloveniaVitanjeMunicipality,
    sloveniaVodiceMunicipality,
    sloveniaVojnikMunicipality,
    sloveniaVranskoMunicipality,
    sloveniaVrhnikaMunicipality,
    sloveniaVuzenicaMunicipality,
    sloveniaZagorjeObSaviMunicipality,
    sloveniaZalecMunicipality,
    sloveniaZavrcMunicipality,
    sloveniaZeleznikiMunicipality,
    sloveniaZetaleMunicipality,
    sloveniaZiriMunicipality,
    sloveniaZirovnicaMunicipality,
    sloveniaZreceMunicipality,
    sloveniaZuzemberkMunicipality
  ],
  timezones: [
    Timezone(
      abbreviation: "CET",
      gmtOffset: 3600,
      gmtOffsetName: "UTC+01:00",
      tzName: "Central European Time",
      zoneName: "Europe/Ljubljana")
  ],
  translations: {
    "kr": "슬로베니아",
    "pt-BR": "Eslovênia",
    "pt": "Eslovénia",
    "nl": "Slovenië",
    "hr": "Slovenija",
    "fa": "اسلوونی",
    "de": "Slowenien",
    "es": "Eslovenia",
    "fr": "Slovénie",
    "ja": "スロベニア",
    "it": "Slovenia",
    "cn": "斯洛文尼亚",
    "tr": "Slovenya"
  });
