/// Access to known geographies in Slovenia and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'slovenia_states.dart';

/// The country of `🇸🇮 Slovenia`, and its 211 states
const Country slovenia = Country(id: 201, name: "Slovenia", longitude: 14.81666666,
          latitude: 46.11666666, capital: "Ljubljana",
          currency: "EUR", currencySymbol: "€",
          emoji: "🇸🇮", emojiU: "U+1F1F8 U+1F1EE",
          iso2: "SI", iso3: "SVN",
          native: "Slovenija", numericCode: "705",
          phoneCode: "386", region: "Europe",
          subregion: "Southern Europe", tld: ".si",
          states: [
            sloveniaAjdovscinaMunicipality,
            sloveniaAnkaranMunicipality,
            sloveniaBeltinciMunicipality,
            sloveniaBenediktMunicipality,
            sloveniaBistricaOobSotliMunicipality,
            sloveniaBledMunicipality,
            sloveniaBlokeMunicipality,
            sloveniaBohinjMunicipality,
            sloveniaBorovnicaMunicipality,
            sloveniaBovecMunicipality,
            sloveniaBraslovceMunicipality,
            sloveniaBrdaMunicipality,
            sloveniaBreziceMunicipality,
            sloveniaBrezovicaMunicipality,
            sloveniaCankovaMunicipality,
            sloveniaCerkljeNnaGorenjskemMunicipality,
            sloveniaCerknicaMunicipality,
            sloveniaCerknoMunicipality,
            sloveniaCerkvenjakMunicipality,
            sloveniaCityMunicipalityOofCelje,
            sloveniaCityMunicipalityOofNovoMesto,
            sloveniaCrensovciMunicipality,
            sloveniaCrnaNnaKoroskemMunicipality,
            sloveniaCrnomeljMunicipality,
            sloveniaDestrnikMunicipality,
            sloveniaDivacaMunicipality,
            sloveniaDobjeMunicipality,
            sloveniaDobrepoljeMunicipality,
            sloveniaDobrnaMunicipality,
            sloveniaDobrovaPolhovGradecMunicipality,
            sloveniaDobrovnikMunicipality,
            sloveniaDolPpriLjubljaniMunicipality,
            sloveniaDolenjskeTopliceMunicipality,
            sloveniaDomzaleMunicipality,
            sloveniaDornavaMunicipality,
            sloveniaDravogradMunicipality,
            sloveniaDuplekMunicipality,
            sloveniaGorenjaVasPoljaneMunicipality,
            sloveniaGorisnicaMunicipality,
            sloveniaGorjeMunicipality,
            sloveniaGornjaRadgonaMunicipality,
            sloveniaGornjiGradMunicipality,
            sloveniaGornjiPetrovciMunicipality,
            sloveniaGradMunicipality,
            sloveniaGrosupljeMunicipality,
            sloveniaHajdinaMunicipality,
            sloveniaHoceSlivnicaMunicipality,
            sloveniaHodosMunicipality,
            sloveniaHorjulMunicipality,
            sloveniaHrastnikMunicipality,
            sloveniaHrpeljeKozinaMunicipality,
            sloveniaIdrijaMunicipality,
            sloveniaIgMunicipality,
            sloveniaIvancnaGoricaMunicipality,
            sloveniaIzolaMunicipality,
            sloveniaJeseniceMunicipality,
            sloveniaJezerskoMunicipality,
            sloveniaJursinciMunicipality,
            sloveniaKamnikMunicipality,
            sloveniaKanalOobSociMunicipality,
            sloveniaKidricevoMunicipality,
            sloveniaKobaridMunicipality,
            sloveniaKobiljeMunicipality,
            sloveniaKocevjeMunicipality,
            sloveniaKomenMunicipality,
            sloveniaKomendaMunicipality,
            sloveniaKoperCityMunicipality,
            sloveniaKostanjevicaNnaKrkiMunicipality,
            sloveniaKostelMunicipality,
            sloveniaKozjeMunicipality,
            sloveniaKranjCityMunicipality,
            sloveniaKranjskaGoraMunicipality,
            sloveniaKrizevciMunicipality,
            sloveniaKungota,
            sloveniaKuzmaMunicipality,
            sloveniaLaskoMunicipality,
            sloveniaLenartMunicipality,
            sloveniaLendavaMunicipality,
            sloveniaLitijaMunicipality,
            sloveniaLjubljanaCityMunicipality,
            sloveniaLjubnoMunicipality,
            sloveniaLjutomerMunicipality,
            sloveniaLogDragomerMunicipality,
            sloveniaLogatecMunicipality,
            sloveniaLoskaDolinaMunicipality,
            sloveniaLoskiPotokMunicipality,
            sloveniaLovrencNnaPohorjuMunicipality,
            sloveniaLuceMunicipality,
            sloveniaLukovicaMunicipality,
            sloveniaMajsperkMunicipality,
            sloveniaMakoleMunicipality,
            sloveniaMariborCityMunicipality,
            sloveniaMarkovciMunicipality,
            sloveniaMedvodeMunicipality,
            sloveniaMengesMunicipality,
            sloveniaMetlikaMunicipality,
            sloveniaMezicaMunicipality,
            sloveniaMiklavzNnaDravskemPoljuMunicipality,
            sloveniaMirenKostanjevicaMunicipality,
            sloveniaMirnaMunicipality,
            sloveniaMirnaPecMunicipality,
            sloveniaMislinjaMunicipality,
            sloveniaMokronogTrebelnoMunicipality,
            sloveniaMoravceMunicipality,
            sloveniaMoravskeTopliceMunicipality,
            sloveniaMozirjeMunicipality,
            sloveniaMunicipalityOofApace,
            sloveniaMunicipalityOofCirkulane,
            sloveniaMunicipalityOofIlirskaBistrica,
            sloveniaMunicipalityOofKrsko,
            sloveniaMunicipalityOofSkofljica,
            sloveniaMurskaSobotaCityMunicipality,
            sloveniaMutaMunicipality,
            sloveniaNakloMunicipality,
            sloveniaNazarjeMunicipality,
            sloveniaNovaGoricaCityMunicipality,
            sloveniaOdranciMunicipality,
            sloveniaOplotnica,
            sloveniaOrmozMunicipality,
            sloveniaOsilnicaMunicipality,
            sloveniaPesnicaMunicipality,
            sloveniaPiranMunicipality,
            sloveniaPivkaMunicipality,
            sloveniaPodcetrtekMunicipality,
            sloveniaPodlehnikMunicipality,
            sloveniaPodvelkaMunicipality,
            sloveniaPoljcaneMunicipality,
            sloveniaPolzelaMunicipality,
            sloveniaPostojnaMunicipality,
            sloveniaPreboldMunicipality,
            sloveniaPreddvorMunicipality,
            sloveniaPrevaljeMunicipality,
            sloveniaPtujCityMunicipality,
            sloveniaPuconciMunicipality,
            sloveniaRaceFramMunicipality,
            sloveniaRadeceMunicipality,
            sloveniaRadenciMunicipality,
            sloveniaRadljeOobDraviMunicipality,
            sloveniaRadovljicaMunicipality,
            sloveniaRavneNnaKoroskemMunicipality,
            sloveniaRazkrizjeMunicipality,
            sloveniaRecicaOobSavinjiMunicipality,
            sloveniaRenceVogrskoMunicipality,
            sloveniaRibnicaMunicipality,
            sloveniaRibnicaNnaPohorjuMunicipality,
            sloveniaRogaskaSlatinaMunicipality,
            sloveniaRogasovciMunicipality,
            sloveniaRogatecMunicipality,
            sloveniaRuseMunicipality,
            sloveniaSalovciMunicipality,
            sloveniaSelnicaOobDraviMunicipality,
            sloveniaSemicMunicipality,
            sloveniaSempeterVrtojbaMunicipality,
            sloveniaSencurMunicipality,
            sloveniaSentiljMunicipality,
            sloveniaSentjernejMunicipality,
            sloveniaSentjurMunicipality,
            sloveniaSentrupertMunicipality,
            sloveniaSevnicaMunicipality,
            sloveniaSezanaMunicipality,
            sloveniaSkocjanMunicipality,
            sloveniaSkofjaLokaMunicipality,
            sloveniaSlovenjGradecCityMunicipality,
            sloveniaSlovenskaBistricaMunicipality,
            sloveniaSlovenskeKonjiceMunicipality,
            sloveniaSmarjePpriJelsahMunicipality,
            sloveniaSmarjeskeTopliceMunicipality,
            sloveniaSmartnoOobPakiMunicipality,
            sloveniaSmartnoPpriLitijiMunicipality,
            sloveniaSodrazicaMunicipality,
            sloveniaSolcavaMunicipality,
            sloveniaSostanjMunicipality,
            sloveniaSredisceOobDravi,
            sloveniaStarseMunicipality,
            sloveniaStoreMunicipality,
            sloveniaStrazaMunicipality,
            sloveniaSvetaAnaMunicipality,
            sloveniaSvetaTrojicaVvSlovenskihGoricahMunicipality,
            sloveniaSvetiAndrazVvSlovenskihGoricahMunicipality,
            sloveniaSvetiJurijOobScavniciMunicipality,
            sloveniaSvetiJurijVvSlovenskihGoricahMunicipality,
            sloveniaSvetiTomazMunicipality,
            sloveniaTaborMunicipality,
            sloveniaTisinaMunicipality,
            sloveniaTolminMunicipality,
            sloveniaTrbovljeMunicipality,
            sloveniaTrebnjeMunicipality,
            sloveniaTrnovskaVasMunicipality,
            sloveniaTrzicMunicipality,
            sloveniaTrzinMunicipality,
            sloveniaTurnisceMunicipality,
            sloveniaVelikaPolanaMunicipality,
            sloveniaVelikeLasceMunicipality,
            sloveniaVerzejMunicipality,
            sloveniaVidemMunicipality,
            sloveniaVipavaMunicipality,
            sloveniaVitanjeMunicipality,
            sloveniaVodiceMunicipality,
            sloveniaVojnikMunicipality,
            sloveniaVranskoMunicipality,
            sloveniaVrhnikaMunicipality,
            sloveniaVuzenicaMunicipality,
            sloveniaZagorjeOobSaviMunicipality,
            sloveniaZalecMunicipality,
            sloveniaZavrcMunicipality,
            sloveniaZeleznikiMunicipality,
            sloveniaZetaleMunicipality,
            sloveniaZiriMunicipality,
            sloveniaZirovnicaMunicipality,
            sloveniaZreceMunicipality,
            sloveniaZuzemberkMunicipality
          ],
          timezones: [
            Timezone(abbreviation: "CET", gmtOffset: 3600, gmtOffsetName: "UTC+01:00",
                    tzName: "Central European Time", zoneName: "Europe/Ljubljana")
          ],
          translations: {
            "kr": "슬로베니아",
            "br": "Eslovênia",
            "pt": "Eslovénia",
            "nl": "Slovenië",
            "hr": "Slovenija",
            "fa": "اسلوونی",
            "de": "Slowenien",
            "es": "Eslovenia",
            "fr": "Slovénie",
            "ja": "スロベニア",
            "it": "Slovenia",
            "cn": "斯洛文尼亚"
          });
