/// Access to known geographies in `Sweden` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'sweden_cities.dart';

/// The `Blekinge` region in `Sweden`
const Region swedenBlekinge = Region(
  id: 1537,
  parentId: 213,
  longitude: 15.0180058,
  latitude: 56.2783837,
  name: "Blekinge",
  type: null,
  stateCode: "K",
  cities: [
    blekingeBrakneHyphobyCity,
    blekingeHallevikCity,
    blekingeHassloCity,
    blekingeJamjoCity,
    blekingeJamshogCity,
    blekingeKallingeCity,
    blekingeKarlshamnCity,
    blekingeKarlskronaCity,
    blekingeMjallbyCity,
    blekingeMorrumCity,
    blekingeNattrabyCity,
    blekingeOlofstromCity,
    blekingeRodebyCity,
    blekingeRonnebyCity,
    blekingeSolvesborgCity,
    blekingeSturkoCity,
    blekingeSvangstaCity
  ]);

/// The `Dalarna County` region in `Sweden`
const Region swedenDalarnaCounty = Region(
  id: 1534,
  parentId: 213,
  longitude: 14.6663653,
  latitude: 61.0917012,
  name: "Dalarna County",
  type: null,
  stateCode: "W",
  cities: [
    dalarnaCountyAbborrbergetCity,
    dalarnaCountyAlvdalenCity,
    dalarnaCountyAvestaCity,
    dalarnaCountyBjursasCity,
    dalarnaCountyBorlangeCity,
    dalarnaCountyBrunnaCity,
    dalarnaCountyDjurasCity,
    dalarnaCountyEnbackaCity,
    dalarnaCountyFalunCity,
    dalarnaCountyGagnefCity,
    dalarnaCountyGrangesbergCity,
    dalarnaCountyGrycksboCity,
    dalarnaCountyHedemoraCity,
    dalarnaCountyHorndalCity,
    dalarnaCountyInsjonCity,
    dalarnaCountyJarnaCity,
    dalarnaCountyKrylboCity,
    dalarnaCountyLangshyttanCity,
    dalarnaCountyLeksandCity,
    dalarnaCountyLudvikaCity,
    dalarnaCountyMalungCity,
    dalarnaCountyMockfjardCity,
    dalarnaCountyMoraCity,
    dalarnaCountyNyhammarCity,
    dalarnaCountyOrnasCity,
    dalarnaCountyOrsaCity,
    dalarnaCountyRattvikCity,
    dalarnaCountyRommeCity,
    dalarnaCountySaterCity,
    dalarnaCountySiljansnasCity,
    dalarnaCountySmedbyCity,
    dalarnaCountySmedjebackenCity,
    dalarnaCountySvardsjoCity,
    dalarnaCountyVansbroCity,
    dalarnaCountyVikarbynCity
  ]);

/// The `Gävleborg County` region in `Sweden`
const Region swedenGavleborgCounty = Region(
  id: 1533,
  parentId: 213,
  longitude: 16.1534214,
  latitude: 61.3011993,
  name: "Gävleborg County",
  type: null,
  stateCode: "X",
  cities: [
    gavleborgCountyAlftaCity,
    gavleborgCountyArbraCity,
    gavleborgCountyArsundaCity,
    gavleborgCountyBergbyCity,
    gavleborgCountyBergsjoCity,
    gavleborgCountyBollnasCity,
    gavleborgCountyDelsboCity,
    gavleborgCountyEdsbynCity,
    gavleborgCountyFarilaCity,
    gavleborgCountyForsbackaCity,
    gavleborgCountyGavleCity,
    gavleborgCountyGnarpCity,
    gavleborgCountyHedesundaCity,
    gavleborgCountyHoforsCity,
    gavleborgCountyHudiksvallCity,
    gavleborgCountyIggesundCity,
    gavleborgCountyJarboCity,
    gavleborgCountyJarvsoCity,
    gavleborgCountyKilaforsCity,
    gavleborgCountyLjusdalCity,
    gavleborgCountyLjusneCity,
    gavleborgCountyOckelboCity,
    gavleborgCountySandarneCity,
    gavleborgCountySandvikenCity,
    gavleborgCountySoderhamnCity,
    gavleborgCountySorforsaCity,
    gavleborgCountyStorvikCity,
    gavleborgCountyValboCity
  ]);

/// The `Gotland County` region in `Sweden`
const Region swedenGotlandCounty = Region(
  id: 1546,
  parentId: 213,
  longitude: 18.4867447,
  latitude: 57.4684121,
  name: "Gotland County",
  type: null,
  stateCode: "I",
  cities: [
    gotlandCountyGotlandCity,
    gotlandCountyHemseCity,
    gotlandCountyKlintehamnCity,
    gotlandCountyVibbleCity,
    gotlandCountyVisbyCity
  ]);

/// The `Halland County` region in `Sweden`
const Region swedenHallandCounty = Region(
  id: 1548,
  parentId: 213,
  longitude: 12.8033993,
  latitude: 56.8966805,
  name: "Halland County",
  type: null,
  stateCode: "N",
  cities: [
    hallandCountyAledCity,
    hallandCountyAsaCity,
    hallandCountyBuaCity,
    hallandCountyFalkenbergCity,
    hallandCountyFjarasKyrkbyCity,
    hallandCountyFrillesasCity,
    hallandCountyFrosakullCity,
    hallandCountyFyllingeCity,
    hallandCountyGetingeCity,
    hallandCountyGlommenCity,
    hallandCountyGullbrandstorpCity,
    hallandCountyHalmstadCity,
    hallandCountyHarplingeCity,
    hallandCountyHaverdalCity,
    hallandCountyHyltebrukCity,
    hallandCountyKnaredCity,
    hallandCountyKungsbackaCity,
    hallandCountyLaholmCity,
    hallandCountyMellbystrandCity,
    hallandCountyMjallbyCity,
    hallandCountyOnsalaCity,
    hallandCountyOskarstromCity,
    hallandCountySaroCity,
    hallandCountySkreaCity,
    hallandCountySteningeCity,
    hallandCountyTorupCity,
    hallandCountyTraslovslageCity,
    hallandCountyTronningeCity,
    hallandCountyTvaakerCity,
    hallandCountyValldaCity,
    hallandCountyVarbergCity,
    hallandCountyVastraHagenCity,
    hallandCountyVeddigeCity,
    hallandCountyVeingeCity
  ]);

/// The `Jämtland County` region in `Sweden`
const Region swedenJamtlandCountySeHypz = Region(
  id: 5117,
  parentId: 213,
  longitude: 14.238281,
  latitude: 63.283062,
  name: "Jämtland County",
  type: "SE-Z",
  stateCode: "0",
  cities: []);

/// The `Jönköping County` region in `Sweden`
const Region swedenJonkopingCounty = Region(
  id: 1550,
  parentId: 213,
  longitude: 14.3439174,
  latitude: 57.3708434,
  name: "Jönköping County",
  type: null,
  stateCode: "F",
  cities: [
    jonkopingCountyAnderstorpCity,
    jonkopingCountyAnebyCity,
    jonkopingCountyBankerydCity,
    jonkopingCountyBodaforsCity,
    jonkopingCountyBorCity,
    jonkopingCountyBredarydCity,
    jonkopingCountyEkenassjonCity,
    jonkopingCountyEksjoCity,
    jonkopingCountyForserumCity,
    jonkopingCountyForshedaCity,
    jonkopingCountyGislavedCity,
    jonkopingCountyGnosjoCity,
    jonkopingCountyGrannaCity,
    jonkopingCountyHaboCity,
    jonkopingCountyHestraCity,
    jonkopingCountyHillerstorpCity,
    jonkopingCountyHuskvarnaCity,
    jonkopingCountyJonkopingCity,
    jonkopingCountyKaxholmenCity,
    jonkopingCountyLandsbroCity,
    jonkopingCountyMalmbackCity,
    jonkopingCountyMariannelundCity,
    jonkopingCountyMarieholmCity,
    jonkopingCountyMullsjoCity,
    jonkopingCountyNassjoCity,
    jonkopingCountyOdensjoCity,
    jonkopingCountyRefteleCity,
    jonkopingCountyRydaholmCity,
    jonkopingCountySavsjoCity,
    jonkopingCountySkillingarydCity,
    jonkopingCountySmalandsstenarCity,
    jonkopingCountyStockarydCity,
    jonkopingCountyTabergCity,
    jonkopingCountyTenhultCity,
    jonkopingCountyTranasCity,
    jonkopingCountyVaggerydCity,
    jonkopingCountyVarnamoCity,
    jonkopingCountyVetlandaCity,
    jonkopingCountyVrigstadCity
  ]);

/// The `Kalmar County` region in `Sweden`
const Region swedenKalmarCounty = Region(
  id: 1544,
  parentId: 213,
  longitude: 16.1849349,
  latitude: 57.2350156,
  name: "Kalmar County",
  type: null,
  stateCode: "H",
  cities: [
    kalmarCountyAnkarsrumCity,
    kalmarCountyBergkvaraCity,
    kalmarCountyBlomstermalaCity,
    kalmarCountyBorgholmCity,
    kalmarCountyEmmabodaCity,
    kalmarCountyFarjestadenCity,
    kalmarCountyGamlebyCity,
    kalmarCountyGunneboCity,
    kalmarCountyHogsbyCity,
    kalmarCountyHultsfredCity,
    kalmarCountyKalmarCity,
    kalmarCountyKristdalaCity,
    kalmarCountyLindsdalCity,
    kalmarCountyLjungbyholmCity,
    kalmarCountyMalillaCity,
    kalmarCountyMonsterasCity,
    kalmarCountyMorbylangaCity,
    kalmarCountyNybroCity,
    kalmarCountyOskarshamnCity,
    kalmarCountyOverumCity,
    kalmarCountyPaskallavikCity,
    kalmarCountyRinkabyholmCity,
    kalmarCountySmedbyCity,
    kalmarCountySodraSandbyCity,
    kalmarCountySodraViCity,
    kalmarCountyStorebroCity,
    kalmarCountyTimmernabbenCity,
    kalmarCountyTorsasCity,
    kalmarCountyTrekantenCity,
    kalmarCountyVastervikCity,
    kalmarCountyVimmerbyCity,
    kalmarCountyVirserumCity
  ]);

/// The `Kronoberg County` region in `Sweden`
const Region swedenKronobergCounty = Region(
  id: 1542,
  parentId: 213,
  longitude: 14.4114673,
  latitude: 56.7183403,
  name: "Kronoberg County",
  type: null,
  stateCode: "G",
  cities: [
    kronobergCountyAlmhultCity,
    kronobergCountyAlvestaCity,
    kronobergCountyAsedaCity,
    kronobergCountyBraasCity,
    kronobergCountyGemlaCity,
    kronobergCountyHovmantorpCity,
    kronobergCountyIngelstadCity,
    kronobergCountyLaganCity,
    kronobergCountyLammhultCity,
    kronobergCountyLenhovdaCity,
    kronobergCountyLesseboCity,
    kronobergCountyLjungbyCity,
    kronobergCountyMarkarydCity,
    kronobergCountyMohedaCity,
    kronobergCountyRottneCity,
    kronobergCountyRydCity,
    kronobergCountyStromsnasbrukCity,
    kronobergCountyTingsrydCity,
    kronobergCountyVaxjoCity,
    kronobergCountyVislandaCity
  ]);

/// The `Norrbotten County` region in `Sweden`
const Region swedenNorrbottenCounty = Region(
  id: 1538,
  parentId: 213,
  longitude: 20.3991966,
  latitude: 66.8309216,
  name: "Norrbotten County",
  type: null,
  stateCode: "BD",
  cities: [
    norrbottenCountyAlvsbynCity,
    norrbottenCountyArjeplogCity,
    norrbottenCountyArvidsjaurCity,
    norrbottenCountyBergnasetCity,
    norrbottenCountyBergsvikenCity,
    norrbottenCountyBjorkskatanCity,
    norrbottenCountyBodenCity,
    norrbottenCountyGallivareCity,
    norrbottenCountyGammelstadCity,
    norrbottenCountyHaparandaCity,
    norrbottenCountyHortlaxCity,
    norrbottenCountyJokkmokkCity,
    norrbottenCountyKalixCity,
    norrbottenCountyKirunaCity,
    norrbottenCountyLuleaCity,
    norrbottenCountyMalmbergetCity,
    norrbottenCountyMarielundCity,
    norrbottenCountyNorrfjardenCity,
    norrbottenCountyOverkalixCity,
    norrbottenCountyOvertorneaCity,
    norrbottenCountyPajalaCity,
    norrbottenCountyPiteaCity,
    norrbottenCountyRaneaCity,
    norrbottenCountyRoknasCity,
    norrbottenCountyRolfsCity,
    norrbottenCountyRosvikCity,
    norrbottenCountySavastCity,
    norrbottenCountySodraSunderbynCity,
    norrbottenCountyToreCity
  ]);

/// The `Örebro County` region in `Sweden`
const Region swedenOrebroCounty = Region(
  id: 1539,
  parentId: 213,
  longitude: 15.0065731,
  latitude: 59.535036,
  name: "Örebro County",
  type: null,
  stateCode: "T",
  cities: [
    orebroCountyAsbroCity,
    orebroCountyAskersundCity,
    orebroCountyDegerforsCity,
    orebroCountyEkebyHypalmbyCity,
    orebroCountyFellingsbroCity,
    orebroCountyFjugestaCity,
    orebroCountyFroviCity,
    orebroCountyGarphyttanCity,
    orebroCountyHallabrottetCity,
    orebroCountyHalleforsCity,
    orebroCountyHallsbergCity,
    orebroCountyHovstaCity,
    orebroCountyKarlskogaCity,
    orebroCountyKopparbergCity,
    orebroCountyKumlaCity,
    orebroCountyLaxaCity,
    orebroCountyLindesbergCity,
    orebroCountyNoraCity,
    orebroCountyOdensbackenCity,
    orebroCountyOrebroCity,
    orebroCountyPalsbodaCity,
    orebroCountySkollerstaCity,
    orebroCountyStoraCity,
    orebroCountyVintrosaCity
  ]);

/// The `Östergötland County` region in `Sweden`
const Region swedenOstergotlandCounty = Region(
  id: 1536,
  parentId: 213,
  longitude: 15.5197844,
  latitude: 58.3453635,
  name: "Östergötland County",
  type: null,
  stateCode: "E",
  cities: [
    ostergotlandCountyAbyCity,
    ostergotlandCountyAtvidabergCity,
    ostergotlandCountyBergCity,
    ostergotlandCountyBorensbergCity,
    ostergotlandCountyBoxholmCity,
    ostergotlandCountyEkangenCity,
    ostergotlandCountyFinspangCity,
    ostergotlandCountyGreboCity,
    ostergotlandCountyGusumCity,
    ostergotlandCountyHerrestadCity,
    ostergotlandCountyJurslaCity,
    ostergotlandCountyKimstadCity,
    ostergotlandCountyKisaCity,
    ostergotlandCountyKrokekCity,
    ostergotlandCountyLindoCity,
    ostergotlandCountyLinghemCity,
    ostergotlandCountyLinkopingCity,
    ostergotlandCountyLjungsbroCity,
    ostergotlandCountyMalmslattCity,
    ostergotlandCountyMantorpCity,
    ostergotlandCountyMjolbyCity,
    ostergotlandCountyMotalaCity,
    ostergotlandCountyNorrkopingCity,
    ostergotlandCountyOdeshogCity,
    ostergotlandCountyOsterbymoCity,
    ostergotlandCountyRimforsaCity,
    ostergotlandCountyRydCity,
    ostergotlandCountySkanningeCity,
    ostergotlandCountySkarblackaCity,
    ostergotlandCountySoderkopingCity,
    ostergotlandCountyStenstorpCity,
    ostergotlandCountyStureforsCity,
    ostergotlandCountySvartingeCity,
    ostergotlandCountyTallbodaCity,
    ostergotlandCountyVadstenaCity,
    ostergotlandCountyValdemarsvikCity,
    ostergotlandCountyVikingstadCity
  ]);

/// The `Skåne County` region in `Sweden`
const Region swedenSkaneCounty = Region(
  id: 1541,
  parentId: 213,
  longitude: 13.5957692,
  latitude: 55.9902572,
  name: "Skåne County",
  type: null,
  stateCode: "M",
  cities: [
    skaneCountyAhusCity,
    skaneCountyAkarpCity,
    skaneCountyAnderslovCity,
    skaneCountyAngelholmCity,
    skaneCountyArlovCity,
    skaneCountyAsmundtorpCity,
    skaneCountyAstorpCity,
    skaneCountyBaraCity,
    skaneCountyBarslovCity,
    skaneCountyBastadCity,
    skaneCountyBillebergaCity,
    skaneCountyBillesholmCity,
    skaneCountyBjarnumCity,
    skaneCountyBjarredCity,
    skaneCountyBjuvCity,
    skaneCountyBlentarpCity,
    skaneCountyBrobyCity,
    skaneCountyBromollaCity,
    skaneCountyBunkeflostrandCity,
    skaneCountyDalbyCity,
    skaneCountyDegebergaCity,
    skaneCountyEkebyCity,
    skaneCountyEslovCity,
    skaneCountyFarlovCity,
    skaneCountyFjalkingeCity,
    skaneCountyForslovCity,
    skaneCountyFurulundCity,
    skaneCountyGantoftaCity,
    skaneCountyGarsnasCity,
    skaneCountyGenarpCity,
    skaneCountyGlimakraCity,
    skaneCountyGlumslovCity,
    skaneCountyHaljarpCity,
    skaneCountyHammarCity,
    skaneCountyHanaskogCity,
    skaneCountyHassleholmCity,
    skaneCountyHastvedaCity,
    skaneCountyHelsingborgCity,
    skaneCountyHittarpCity,
    skaneCountyHjarnarpCity,
    skaneCountyHjarupCity,
    skaneCountyHofterupCity,
    skaneCountyHoganasCity,
    skaneCountyHokopingeCity,
    skaneCountyHollvikenCity,
    skaneCountyHoorCity,
    skaneCountyHorbyCity,
    skaneCountyHyllingeCity,
    skaneCountyJonstorpCity,
    skaneCountyKagerodCity,
    skaneCountyKavlingeCity,
    skaneCountyKlagerupCity,
    skaneCountyKlippanCity,
    skaneCountyKnislingeCity,
    skaneCountyKopingebroCity,
    skaneCountyKristianstadCity,
    skaneCountyKvidingeCity,
    skaneCountyLandskronaCity,
    skaneCountyLjungbyhedCity,
    skaneCountyLjunghusenCity,
    skaneCountyLoberodCity,
    skaneCountyLoddekopingeCity,
    skaneCountyLommaCity,
    skaneCountyLonsbodaCity,
    skaneCountyLundCity,
    skaneCountyMalmoCity,
    skaneCountyMarieholmCity,
    skaneCountyMorarpCity,
    skaneCountyMunkaHypljungbyCity,
    skaneCountyNasumCity,
    skaneCountyNorraAsumCity,
    skaneCountyOdakraCity,
    skaneCountyOnnestadCity,
    skaneCountyOrkelljungaCity,
    skaneCountyOsbyCity,
    skaneCountyOstraLjungbyCity,
    skaneCountyOxieCity,
    skaneCountyPaarpCity,
    skaneCountyPerstorpCity,
    skaneCountyRydebackCity,
    skaneCountyRydsgardCity,
    skaneCountySatoftaCity,
    skaneCountySaxtorpsskogenCity,
    skaneCountySibbhultCity,
    skaneCountySimrishamnCity,
    skaneCountySjoboCity,
    skaneCountySkanorMedFalsterboCity,
    skaneCountySkareCity,
    skaneCountySkegrieCity,
    skaneCountySkivarpCity,
    skaneCountySkurupCity,
    skaneCountySmygehamnCity,
    skaneCountySodraSandbyCity,
    skaneCountySosdalaCity,
    skaneCountyStaffanstorpCity,
    skaneCountyStangbyCity,
    skaneCountyStehagCity,
    skaneCountyStrovelstorpCity,
    skaneCountySvalovCity,
    skaneCountySvedalaCity,
    skaneCountyTeckomatorpCity,
    skaneCountyTollarpCity,
    skaneCountyTollarp1City,
    skaneCountyTomelillaCity,
    skaneCountyTorekovCity,
    skaneCountyTormestorpCity,
    skaneCountyTrelleborgCity,
    skaneCountyTygelsjoCity,
    skaneCountyTyringeCity,
    skaneCountyValjeCity,
    skaneCountyVeberodCity,
    skaneCountyVejbystrandCity,
    skaneCountyVellingeCity,
    skaneCountyVikenCity,
    skaneCountyVinslovCity,
    skaneCountyVittsjoCity,
    skaneCountyYstadCity
  ]);

/// The `Södermanland County` region in `Sweden`
const Region swedenSodermanlandCounty = Region(
  id: 1540,
  parentId: 213,
  longitude: 16.7518899,
  latitude: 59.0336349,
  name: "Södermanland County",
  type: null,
  stateCode: "D",
  cities: [
    sodermanlandCountyAkersStyckebrukCity,
    sodermanlandCountyArlaCity,
    sodermanlandCountyArnoCity,
    sodermanlandCountyBaraCity,
    sodermanlandCountyEskilstunaCity,
    sodermanlandCountyFlenCity,
    sodermanlandCountyGnestaCity,
    sodermanlandCountyHallbybrunnCity,
    sodermanlandCountyHalleforsnasCity,
    sodermanlandCountyKatrineholmCity,
    sodermanlandCountyKvicksundCity,
    sodermanlandCountyMalmkopingCity,
    sodermanlandCountyMariefredCity,
    sodermanlandCountyNykopingCity,
    sodermanlandCountyOlstorpCity,
    sodermanlandCountyOxelosundCity,
    sodermanlandCountySkogstorpCity,
    sodermanlandCountyStallarholmenCity,
    sodermanlandCountyStigtomtaCity,
    sodermanlandCountyStrangnasCity,
    sodermanlandCountySvalstaCity,
    sodermanlandCountyTorshallaCity,
    sodermanlandCountyTrosaCity,
    sodermanlandCountyVagnharadCity,
    sodermanlandCountyVallaCity,
    sodermanlandCountyVingakerCity
  ]);

/// The `Stockholm County` region in `Sweden`
const Region swedenStockholmCounty = Region(
  id: 1551,
  parentId: 213,
  longitude: 18.1384383,
  latitude: 59.6024958,
  name: "Stockholm County",
  type: null,
  stateCode: "AB",
  cities: [
    stockholmCountyAkallaCity,
    stockholmCountyAkersbergaCity,
    stockholmCountyAlbyCity,
    stockholmCountyAlmstaCity,
    stockholmCountyAltaCity,
    stockholmCountyArnoCity,
    stockholmCountyArstaCity,
    stockholmCountyBergshamraCity,
    stockholmCountyBollmoraCity,
    stockholmCountyBooCity,
    stockholmCountyBrevikCity,
    stockholmCountyBroCity,
    stockholmCountyBrommaCity,
    stockholmCountyBrunnCity,
    stockholmCountyBrunnaCity,
    stockholmCountyDalaroCity,
    stockholmCountyDjuroCity,
    stockholmCountyDjursholmCity,
    stockholmCountyEkeroCity,
    stockholmCountyEnebybergCity,
    stockholmCountyEriksbergCity,
    stockholmCountyFisksatraCity,
    stockholmCountyFittjaCity,
    stockholmCountyGamlaStanCity,
    stockholmCountyGustavsbergCity,
    stockholmCountyHallstavikCity,
    stockholmCountyHandenCity,
    stockholmCountyHaningeCity,
    stockholmCountyHemmestaCity,
    stockholmCountyHoloCity,
    stockholmCountyHuddingeCity,
    stockholmCountyJakobsbergCity,
    stockholmCountyJarnaCity,
    stockholmCountyJordbroCity,
    stockholmCountyKistaCity,
    stockholmCountyKopparmoraCity,
    stockholmCountyKummelnasCity,
    stockholmCountyKungsangenCity,
    stockholmCountyKungsholmenCity,
    stockholmCountyLangvikCity,
    stockholmCountyLidingoCity,
    stockholmCountyLindholmenCity,
    stockholmCountyMarstaCity,
    stockholmCountyMolnboCity,
    stockholmCountyMortnasCity,
    stockholmCountyNackaCity,
    stockholmCountyNorrtaljeCity,
    stockholmCountyNykvarnCity,
    stockholmCountyNynashamnCity,
    stockholmCountyOsmoCity,
    stockholmCountyOstermalmCity,
    stockholmCountyPershagenCity,
    stockholmCountyRasundaCity,
    stockholmCountyResaroCity,
    stockholmCountyRimboCity,
    stockholmCountyRindoCity,
    stockholmCountyRonningeCity,
    stockholmCountyRosersbergCity,
    stockholmCountySaltsjobadenCity,
    stockholmCountySegeltorpCity,
    stockholmCountySigtunaCity,
    stockholmCountySkanningeCity,
    stockholmCountySodermalmCity,
    stockholmCountySodertaljeCity,
    stockholmCountySollentunaCity,
    stockholmCountySolnaCity,
    stockholmCountyStavsnasCity,
    stockholmCountyStenhamraCity,
    stockholmCountyStockholmCity,
    stockholmCountyStrommaCity,
    stockholmCountySundbybergCity,
    stockholmCountyTenstaCity,
    stockholmCountyTullingeCity,
    stockholmCountyTumbaCity,
    stockholmCountyUpplandsVasbyCity,
    stockholmCountyVallentunaCity,
    stockholmCountyVarbyCity,
    stockholmCountyVarstaCity,
    stockholmCountyVasastanCity,
    stockholmCountyVaxholmCity
  ]);

/// The `Uppsala County` region in `Sweden`
const Region swedenUppsalaCounty = Region(
  id: 1545,
  parentId: 213,
  longitude: 17.2714588,
  latitude: 60.0092262,
  name: "Uppsala County",
  type: null,
  stateCode: "C",
  cities: [
    uppsalaCountyAlsikeCity,
    uppsalaCountyAlundaCity,
    uppsalaCountyAlvkarlebyCity,
    uppsalaCountyAnnebergCity,
    uppsalaCountyBalingeCity,
    uppsalaCountyBalstaCity,
    uppsalaCountyBjorklingeCity,
    uppsalaCountyEnkopingCity,
    uppsalaCountyGamlaUppsalaCity,
    uppsalaCountyGimoCity,
    uppsalaCountyGrillbyCity,
    uppsalaCountyHebyCity,
    uppsalaCountyIrstaCity,
    uppsalaCountyKarlholmsbrukCity,
    uppsalaCountyKnivstaCity,
    uppsalaCountyLovstalotCity,
    uppsalaCountyMariebergCity,
    uppsalaCountyMorgongavaCity,
    uppsalaCountyOrbyhusCity,
    uppsalaCountyOregrundCity,
    uppsalaCountyOrsundsbroCity,
    uppsalaCountyOsterbybrukCity,
    uppsalaCountyOstervalaCity,
    uppsalaCountyOsthammarCity,
    uppsalaCountySavjaCity,
    uppsalaCountySkutskarCity,
    uppsalaCountySoderforsCity,
    uppsalaCountyStorvretaCity,
    uppsalaCountyTarnsjoCity,
    uppsalaCountyTierpCity,
    uppsalaCountyUppsalaCity,
    uppsalaCountyVattholmaCity
  ]);

/// The `Värmland County` region in `Sweden`
const Region swedenVarmlandCounty = Region(
  id: 1535,
  parentId: 213,
  longitude: 13.2354024,
  latitude: 59.7294065,
  name: "Värmland County",
  type: null,
  stateCode: "S",
  cities: [
    varmlandCountyAmotforsCity,
    varmlandCountyArjangCity,
    varmlandCountyArvikaCity,
    varmlandCountyBjorneborgCity,
    varmlandCountyCharlottenbergCity,
    varmlandCountyDejeCity,
    varmlandCountyEksharadCity,
    varmlandCountyFilipstadCity,
    varmlandCountyForshagaCity,
    varmlandCountyGrumsCity,
    varmlandCountyHagforsCity,
    varmlandCountyKarlstadCity,
    varmlandCountyKilCity,
    varmlandCountyKristinehamnCity,
    varmlandCountyMolkomCity,
    varmlandCountyMunkforsCity,
    varmlandCountyRatorpCity,
    varmlandCountySaffleCity,
    varmlandCountySkareCity,
    varmlandCountySkattkarrCity,
    varmlandCountySkoghallCity,
    varmlandCountySlottsbronCity,
    varmlandCountyStorforsCity,
    varmlandCountySunneCity,
    varmlandCountyTocksforsCity,
    varmlandCountyTorsbyCity,
    varmlandCountyValbergCity
  ]);

/// The `Västerbotten County` region in `Sweden`
const Region swedenVasterbottenCounty = Region(
  id: 1543,
  parentId: 213,
  longitude: 16.5161694,
  latitude: 65.3337311,
  name: "Västerbotten County",
  type: null,
  stateCode: "AC",
  cities: [
    vasterbottenCountyAseleCity,
    vasterbottenCountyBackaCity,
    vasterbottenCountyBjurholmCity,
    vasterbottenCountyBolidenCity,
    vasterbottenCountyBureaCity,
    vasterbottenCountyBurtraskCity,
    vasterbottenCountyByskeCity,
    vasterbottenCountyDoroteaCity,
    vasterbottenCountyErsmarkCity,
    vasterbottenCountyForsbackaCity,
    vasterbottenCountyHolmsundCity,
    vasterbottenCountyHorneforsCity,
    vasterbottenCountyInsjonCity,
    vasterbottenCountyKageCity,
    vasterbottenCountyLangseleCity,
    vasterbottenCountyLyckseleCity,
    vasterbottenCountyMalaCity,
    vasterbottenCountyNordmalingCity,
    vasterbottenCountyNorsjoCity,
    vasterbottenCountyObbolaCity,
    vasterbottenCountyRobackCity,
    vasterbottenCountyRobertsforsCity,
    vasterbottenCountySavarCity,
    vasterbottenCountySkellefteaCity,
    vasterbottenCountySkelleftehamnCity,
    vasterbottenCountySoderforsCity,
    vasterbottenCountySorseleCity,
    vasterbottenCountyStorumanCity,
    vasterbottenCountyStorvikCity,
    vasterbottenCountyTafteaCity,
    vasterbottenCountyUmeaCity,
    vasterbottenCountyUrsvikenCity,
    vasterbottenCountyVannasCity,
    vasterbottenCountyVannasbyCity,
    vasterbottenCountyVikenCity,
    vasterbottenCountyVilhelminaCity,
    vasterbottenCountyVindelnCity
  ]);

/// The `Västernorrland County` region in `Sweden`
const Region swedenVasternorrlandCounty = Region(
  id: 1552,
  parentId: 213,
  longitude: 17.7292444,
  latitude: 63.4276473,
  name: "Västernorrland County",
  type: null,
  stateCode: "Y",
  cities: [
    vasternorrlandCountyAngeCity,
    vasternorrlandCountyAsCity,
    vasternorrlandCountyBergeforsenCity,
    vasternorrlandCountyBjastaCity,
    vasternorrlandCountyBollstabrukCity,
    vasternorrlandCountyBredbynCity,
    vasternorrlandCountyFranstaCity,
    vasternorrlandCountyHarnosandCity,
    vasternorrlandCountyHusumCity,
    vasternorrlandCountyJohannedalCity,
    vasternorrlandCountyKopmanholmenCity,
    vasternorrlandCountyKramforsCity,
    vasternorrlandCountyKvisslebyCity,
    vasternorrlandCountyLangseleCity,
    vasternorrlandCountyMatforsCity,
    vasternorrlandCountyNjurundabommenCity,
    vasternorrlandCountyNolbyCity,
    vasternorrlandCountyOrnskoldsvikCity,
    vasternorrlandCountySkottsundCity,
    vasternorrlandCountySollefteaCity,
    vasternorrlandCountySorakerCity,
    vasternorrlandCountyStockvikCity,
    vasternorrlandCountySundsbrukCity,
    vasternorrlandCountySundsvallCity,
    vasternorrlandCountyTimraCity,
    vasternorrlandCountyViCity
  ]);

/// The `Västmanland County` region in `Sweden`
const Region swedenVastmanlandCounty = Region(
  id: 1549,
  parentId: 213,
  longitude: 16.2158953,
  latitude: 59.6713879,
  name: "Västmanland County",
  type: null,
  stateCode: "U",
  cities: [
    vastmanlandCountyArbogaCity,
    vastmanlandCountyBarkaroCity,
    vastmanlandCountyDingtunaCity,
    vastmanlandCountyEnhagenHypekbackenCity,
    vastmanlandCountyFagerstaCity,
    vastmanlandCountyHallstahammarCity,
    vastmanlandCountyHokasenCity,
    vastmanlandCountyIrstaCity,
    vastmanlandCountyKolbackCity,
    vastmanlandCountyKolsvaCity,
    vastmanlandCountyKopingCity,
    vastmanlandCountyKungsorCity,
    vastmanlandCountyNorbergCity,
    vastmanlandCountyRamnasCity,
    vastmanlandCountySalaCity,
    vastmanlandCountySkinnskattebergCity,
    vastmanlandCountySkultunaCity,
    vastmanlandCountySurahammarCity,
    vastmanlandCountyTillbergaCity,
    vastmanlandCountyVasterasCity
  ]);

/// The `Västra Götaland County` region in `Sweden`
const Region swedenVastraGotalandCounty = Region(
  id: 1547,
  parentId: 213,
  longitude: 13.0596425,
  latitude: 58.2527926,
  name: "Västra Götaland County",
  type: null,
  stateCode: "O",
  cities: [
    vastraGotalandCountyAkarpCity,
    vastraGotalandCountyAlaforsCity,
    vastraGotalandCountyAlingsasCity,
    vastraGotalandCountyAlvangenCity,
    vastraGotalandCountyAmalCity,
    vastraGotalandCountyAndalenCity,
    vastraGotalandCountyAnderstorpCity,
    vastraGotalandCountyAngeredCity,
    vastraGotalandCountyAnnelundCity,
    vastraGotalandCountyAxvallCity,
    vastraGotalandCountyBengtsforsCity,
    vastraGotalandCountyBilldalCity,
    vastraGotalandCountyBillingsforsCity,
    vastraGotalandCountyBjorboholmCity,
    vastraGotalandCountyBjorkoCity,
    vastraGotalandCountyBjorlandaCity,
    vastraGotalandCountyBollebygdCity,
    vastraGotalandCountyBorasCity,
    vastraGotalandCountyBralandaCity,
    vastraGotalandCountyBrastadCity,
    vastraGotalandCountyDalsLangedCity,
    vastraGotalandCountyDalsjoforsCity,
    vastraGotalandCountyDiserodCity,
    vastraGotalandCountyDonsoCity,
    vastraGotalandCountyEdCity,
    vastraGotalandCountyEllosCity,
    vastraGotalandCountyEriksboCity,
    vastraGotalandCountyFalkopingCity,
    vastraGotalandCountyFargelandaCity,
    vastraGotalandCountyFlobyCity,
    vastraGotalandCountyFristadCity,
    vastraGotalandCountyFritslaCity,
    vastraGotalandCountyFurulundCity,
    vastraGotalandCountyGanghesterCity,
    vastraGotalandCountyGardstenCity,
    vastraGotalandCountyGotaCity,
    vastraGotalandCountyGoteborgCity,
    vastraGotalandCountyGoteborgsStadCity,
    vastraGotalandCountyGoteneCity,
    vastraGotalandCountyGraboCity,
    vastraGotalandCountyGrastorpCity,
    vastraGotalandCountyGrebbestadCity,
    vastraGotalandCountyGullspangCity,
    vastraGotalandCountyHammarkullenCity,
    vastraGotalandCountyHenanCity,
    vastraGotalandCountyHerrljungaCity,
    vastraGotalandCountyHindasCity,
    vastraGotalandCountyHjoCity,
    vastraGotalandCountyHjuvikCity,
    vastraGotalandCountyHonoCity,
    vastraGotalandCountyHorredCity,
    vastraGotalandCountyHovaCity,
    vastraGotalandCountyHoviksnasCity,
    vastraGotalandCountyHunnebostrandCity,
    vastraGotalandCountyIngaredCity,
    vastraGotalandCountyJonstorpCity,
    vastraGotalandCountyJorlandaCity,
    vastraGotalandCountyKallbyCity,
    vastraGotalandCountyKalleredCity,
    vastraGotalandCountyKarlsborgCity,
    vastraGotalandCountyKinnaCity,
    vastraGotalandCountyKodeCity,
    vastraGotalandCountyKungalvCity,
    vastraGotalandCountyKungshamnCity,
    vastraGotalandCountyKvanumCity,
    vastraGotalandCountyLandvetterCity,
    vastraGotalandCountyLanghemCity,
    vastraGotalandCountyLerumCity,
    vastraGotalandCountyLidkopingCity,
    vastraGotalandCountyLillaEdetCity,
    vastraGotalandCountyLimmaredCity,
    vastraGotalandCountyLindomeCity,
    vastraGotalandCountyLjungskileCity,
    vastraGotalandCountyLodoseCity,
    vastraGotalandCountyLovgardetCity,
    vastraGotalandCountyLysekilCity,
    vastraGotalandCountyMajornaCity,
    vastraGotalandCountyMariestadCity,
    vastraGotalandCountyMellerudCity,
    vastraGotalandCountyMolltorpCity,
    vastraGotalandCountyMolndalCity,
    vastraGotalandCountyMolnlyckeCity,
    vastraGotalandCountyMunkedalCity,
    vastraGotalandCountyMyggenasCity,
    vastraGotalandCountyNolvikCity,
    vastraGotalandCountyNossebroCity,
    vastraGotalandCountyOckeroCity,
    vastraGotalandCountyOdsmalCity,
    vastraGotalandCountyOjersjoCity,
    vastraGotalandCountyOlofstorpCity,
    vastraGotalandCountyOlstorpCity,
    vastraGotalandCountyOrustCity,
    vastraGotalandCountyPartilleCity,
    vastraGotalandCountyRannebergenCity,
    vastraGotalandCountyRavlandaCity,
    vastraGotalandCountyRonnangCity,
    vastraGotalandCountySalandaCity,
    vastraGotalandCountySandaredCity,
    vastraGotalandCountySatilaCity,
    vastraGotalandCountySjomarkenCity,
    vastraGotalandCountySjuntorpCity,
    vastraGotalandCountySkaraCity,
    vastraGotalandCountySkarhamnCity,
    vastraGotalandCountySkepplandaCity,
    vastraGotalandCountySkovdeCity,
    vastraGotalandCountySkultorpCity,
    vastraGotalandCountySmogenCity,
    vastraGotalandCountySollebrunnCity,
    vastraGotalandCountyStenkullenCity,
    vastraGotalandCountyStenstorpCity,
    vastraGotalandCountyStenungsundCity,
    vastraGotalandCountyStopenCity,
    vastraGotalandCountyStoraHogaCity,
    vastraGotalandCountyStromstadCity,
    vastraGotalandCountyStyrsoCity,
    vastraGotalandCountySurteCity,
    vastraGotalandCountySvanesundCity,
    vastraGotalandCountySvenljungaCity,
    vastraGotalandCountyTanumshedeCity,
    vastraGotalandCountyTibroCity,
    vastraGotalandCountyTidaholmCity,
    vastraGotalandCountyTjuvkilCity,
    vastraGotalandCountyTorebodaCity,
    vastraGotalandCountyTorslandaCity,
    vastraGotalandCountyTranemoCity,
    vastraGotalandCountyTrollhattanCity,
    vastraGotalandCountyUddevallaCity,
    vastraGotalandCountyUlricehamnCity,
    vastraGotalandCountyVanersborgCity,
    vastraGotalandCountyVaraCity,
    vastraGotalandCountyVargardaCity,
    vastraGotalandCountyVargonCity,
    vastraGotalandCountyVastraFrolundaCity,
    vastraGotalandCountyVinningaCity,
    vastraGotalandCountyViskaforsCity
  ]);

/// The 21 states of `Sweden` keyed by their id.
const Map<int, Region> swedenStates = <int, Region>{
    1537: swedenBlekinge,
    1534: swedenDalarnaCounty,
    1533: swedenGavleborgCounty,
    1546: swedenGotlandCounty,
    1548: swedenHallandCounty,
    5117: swedenJamtlandCountySeHypz,
    1550: swedenJonkopingCounty,
    1544: swedenKalmarCounty,
    1542: swedenKronobergCounty,
    1538: swedenNorrbottenCounty,
    1539: swedenOrebroCounty,
    1536: swedenOstergotlandCounty,
    1541: swedenSkaneCounty,
    1540: swedenSodermanlandCounty,
    1551: swedenStockholmCounty,
    1545: swedenUppsalaCounty,
    1535: swedenVarmlandCounty,
    1543: swedenVasterbottenCounty,
    1552: swedenVasternorrlandCounty,
    1549: swedenVastmanlandCounty,
    1547: swedenVastraGotalandCounty
  };
