/// Access to known geographies in `Switzerland` and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.
library;

import '../base.dart';
import 'switzerland_cities.dart';

/// The `Aargau` region in `Switzerland`
const Region switzerlandAargauCanton = Region(
  id: 1639,
  parentId: 214,
  longitude: 8.2554295,
  latitude: 47.3876664,
  name: "Aargau",
  type: "canton",
  stateCode: "AG",
  cities: [
    aargauCantonAarauCity,
    aargauCantonAarburgCity,
    aargauCantonAristauCity,
    aargauCantonAuwCity,
    aargauCantonBadZurzachCity,
    aargauCantonBadenCity,
    aargauCantonBerikonCity,
    aargauCantonBesenburenCity,
    aargauCantonBezirkAarauCity,
    aargauCantonBezirkBadenCity,
    aargauCantonBezirkBremgartenCity,
    aargauCantonBezirkBruggCity,
    aargauCantonBezirkKulmCity,
    aargauCantonBezirkLaufenburgCity,
    aargauCantonBezirkLenzburgCity,
    aargauCantonBezirkMuriCity,
    aargauCantonBezirkRheinfeldenCity,
    aargauCantonBezirkZofingenCity,
    aargauCantonBezirkZurzachCity,
    aargauCantonBirmenstorfCity,
    aargauCantonBirrCity,
    aargauCantonBoniswilCity,
    aargauCantonBremgartenCity,
    aargauCantonBrittnauCity,
    aargauCantonBruggCity,
    aargauCantonBuchsCity,
    aargauCantonButtwilCity,
    aargauCantonDensburenCity,
    aargauCantonDottikonCity,
    aargauCantonDurrenaschCity,
    aargauCantonEgliswilCity,
    aargauCantonEhrendingenCity,
    aargauCantonEikenCity,
    aargauCantonEndingenCity,
    aargauCantonFrickCity,
    aargauCantonGebenstorfCity,
    aargauCantonGipfHypoberfrickCity,
    aargauCantonGontenschwilCity,
    aargauCantonGranichenCity,
    aargauCantonHagglingenCity,
    aargauCantonHausenCity,
    aargauCantonJonenCity,
    aargauCantonKaiseraugstCity,
    aargauCantonKaistenCity,
    aargauCantonKillwangenCity,
    aargauCantonKlingnauCity,
    aargauCantonKoblenzCity,
    aargauCantonKollikenCity,
    aargauCantonKuntenCity,
    aargauCantonKuttigenCity,
    aargauCantonLaufenburgCity,
    aargauCantonLauffohrbruggCity,
    aargauCantonLeibstadtCity,
    aargauCantonLenzburgCity,
    aargauCantonMagdenCity,
    aargauCantonMeisterschwandenCity,
    aargauCantonMellingenCity,
    aargauCantonMenzikenCity,
    aargauCantonMerenschwandCity,
    aargauCantonMohlinCity,
    aargauCantonMuhenCity,
    aargauCantonMumpfCity,
    aargauCantonMurgenthalCity,
    aargauCantonMuriCity,
    aargauCantonNeuenhofCity,
    aargauCantonNiederlenzCity,
    aargauCantonNiederrohrdorfCity,
    aargauCantonOberentfeldenCity,
    aargauCantonOberlunkhofenCity,
    aargauCantonOberrohrdorfCity,
    aargauCantonOberrutiCity,
    aargauCantonObersiggenthalCity,
    aargauCantonOftringenCity,
    aargauCantonOthmarsingenCity,
    aargauCantonReinachCity,
    aargauCantonRheinfeldenCity,
    aargauCantonRothristCity,
    aargauCantonRudolfstettenCity,
    aargauCantonRupperswilCity,
    aargauCantonSafenwilCity,
    aargauCantonSarmenstorfCity,
    aargauCantonSchafisheimCity,
    aargauCantonSchinznachBadCity,
    aargauCantonSchinznachDorfCity,
    aargauCantonSchoftlandCity,
    aargauCantonSchwaderlochCity,
    aargauCantonSeengenCity,
    aargauCantonSeonCity,
    aargauCantonSinsCity,
    aargauCantonSpreitenbachCity,
    aargauCantonStaffelbachCity,
    aargauCantonStaufenCity,
    aargauCantonSteinCity,
    aargauCantonStrengelbachCity,
    aargauCantonSuhrCity,
    aargauCantonSulzCity,
    aargauCantonTegerfeldenCity,
    aargauCantonTeufenthalCity,
    aargauCantonTurgiCity,
    aargauCantonUerkheimCity,
    aargauCantonUnterkulmCity,
    aargauCantonUnterlunkhofenCity,
    aargauCantonUntersiggenthalCity,
    aargauCantonVeltheimCity,
    aargauCantonVilligenCity,
    aargauCantonVillmergenCity,
    aargauCantonVillnachernCity,
    aargauCantonVordemwaldCity,
    aargauCantonWaltenschwilCity,
    aargauCantonWegenstettenCity,
    aargauCantonWettingenCity,
    aargauCantonWindischCity,
    aargauCantonWittnauCity,
    aargauCantonWohlenCity,
    aargauCantonWolflinswilCity,
    aargauCantonWurenlingenCity,
    aargauCantonWurenlosCity,
    aargauCantonZofingenCity
  ]);

/// The `Appenzell Ausserrhoden` region in `Switzerland`
const Region switzerlandAppenzellAusserrhodenCanton = Region(
  id: 1655,
  parentId: 214,
  longitude: 9.3000916,
  latitude: 47.366481,
  name: "Appenzell Ausserrhoden",
  type: "canton",
  stateCode: "AR",
  cities: [
    appenzellAusserrhodenCantonBezirkHinterlandCity,
    appenzellAusserrhodenCantonBezirkMittellandCity,
    appenzellAusserrhodenCantonBezirkVorderlandCity,
    appenzellAusserrhodenCantonBuhlerCity,
    appenzellAusserrhodenCantonGaisCity,
    appenzellAusserrhodenCantonHeidenCity,
    appenzellAusserrhodenCantonHerisauCity,
    appenzellAusserrhodenCantonRehetobelCity,
    appenzellAusserrhodenCantonSchwellbrunnCity,
    appenzellAusserrhodenCantonSpeicherCity,
    appenzellAusserrhodenCantonTeufenCity,
    appenzellAusserrhodenCantonTrogenCity,
    appenzellAusserrhodenCantonUrnaschCity,
    appenzellAusserrhodenCantonWaldstattCity,
    appenzellAusserrhodenCantonWalzenhausenCity
  ]);

/// The `Appenzell Innerrhoden` region in `Switzerland`
const Region switzerlandAppenzellInnerrhodenCanton = Region(
  id: 1649,
  parentId: 214,
  longitude: 9.4316573,
  latitude: 47.3161925,
  name: "Appenzell Innerrhoden",
  type: "canton",
  stateCode: "AI",
  cities: [
    appenzellInnerrhodenCantonAppenzellCity,
    appenzellInnerrhodenCantonGontenCity,
    appenzellInnerrhodenCantonHaslenCity,
    appenzellInnerrhodenCantonObereggCity
  ]);

/// The `Basel-Land` region in `Switzerland`
const Region switzerlandBaselHyplandCanton = Region(
  id: 1641,
  parentId: 214,
  longitude: 7.7644002,
  latitude: 47.4418122,
  name: "Basel-Land",
  type: "canton",
  stateCode: "BL",
  cities: [
    baselHyplandCantonAeschCity,
    baselHyplandCantonAllschwilCity,
    baselHyplandCantonArisdorfCity,
    baselHyplandCantonArlesheimCity,
    baselHyplandCantonBezirkArlesheimCity,
    baselHyplandCantonBezirkLaufenCity,
    baselHyplandCantonBezirkLiestalCity,
    baselHyplandCantonBezirkSissachCity,
    baselHyplandCantonBezirkWaldenburgCity,
    baselHyplandCantonBinningenCity,
    baselHyplandCantonBirsfeldenCity,
    baselHyplandCantonBottmingenCity,
    baselHyplandCantonBrislachCity,
    baselHyplandCantonBubendorfCity,
    baselHyplandCantonBuusCity,
    baselHyplandCantonDiegtenCity,
    baselHyplandCantonEttingenCity,
    baselHyplandCantonFrenkendorfCity,
    baselHyplandCantonFullinsdorfCity,
    baselHyplandCantonGelterkindenCity,
    baselHyplandCantonGrellingenCity,
    baselHyplandCantonHolsteinCity,
    baselHyplandCantonItingenCity,
    baselHyplandCantonLangenbruckCity,
    baselHyplandCantonLaufelfingenCity,
    baselHyplandCantonLaufenCity,
    baselHyplandCantonLausenCity,
    baselHyplandCantonLiesbergCity,
    baselHyplandCantonLiestalCity,
    baselHyplandCantonMunchensteinCity,
    baselHyplandCantonMuttenzCity,
    baselHyplandCantonOberdorfCity,
    baselHyplandCantonOberwilCity,
    baselHyplandCantonOrmalingenCity,
    baselHyplandCantonPfeffingenCity,
    baselHyplandCantonPrattelnCity,
    baselHyplandCantonReigoldswilCity,
    baselHyplandCantonRoschenzCity,
    baselHyplandCantonSchonenbuchCity,
    baselHyplandCantonSeltisbergCity,
    baselHyplandCantonSissachCity,
    baselHyplandCantonTherwilCity,
    baselHyplandCantonWahlenCity,
    baselHyplandCantonWaldenburgCity,
    baselHyplandCantonZunzgenCity,
    baselHyplandCantonZwingenCity
  ]);

/// The `Basel-Stadt` region in `Switzerland`
const Region switzerlandBaselHypstadtCanton = Region(
  id: 4957,
  parentId: 214,
  longitude: 7.6,
  latitude: 47.566667,
  name: "Basel-Stadt",
  type: "canton",
  stateCode: "BS",
  cities: [
    baselHypstadtCantonBaselCity,
    baselHypstadtCantonBettingenCity,
    baselHypstadtCantonRiehenCity
  ]);

/// The `Bern` region in `Switzerland`
const Region switzerlandBernCanton = Region(
  id: 1645,
  parentId: 214,
  longitude: 7.7080701,
  latitude: 46.7988621,
  name: "Bern",
  type: "canton",
  stateCode: "BE",
  cities: [
    bernCantonAarbergCity,
    bernCantonAarwangenCity,
    bernCantonAdelbodenCity,
    bernCantonAeschiBSpiezCity,
    bernCantonArchCity,
    bernCantonAttiswilCity,
    bernCantonBariswilCity,
    bernCantonBatterkindenCity,
    bernCantonBeatenbergCity,
    bernCantonBellmundCity,
    bernCantonBelpCity,
    bernCantonBernCity,
    bernCantonBernHypmittellandDistrictCity,
    bernCantonBevilardCity,
    bernCantonBielbienneCity,
    bernCantonBielbienneDistrictCity,
    bernCantonBiglenCity,
    bernCantonBlumensteinCity,
    bernCantonBolligenCity,
    bernCantonBoltigenCity,
    bernCantonBonigenCity,
    bernCantonBowilCity,
    bernCantonBrienzCity,
    bernCantonBruggCity,
    bernCantonBuchholterbergCity,
    bernCantonBurgdorfCity,
    bernCantonBurgisteinCity,
    bernCantonCorgemontCity,
    bernCantonCourtCity,
    bernCantonCourtelaryCity,
    bernCantonDarligenCity,
    bernCantonDiemtigenCity,
    bernCantonDurrenrothCity,
    bernCantonEggiwilCity,
    bernCantonEmmentalDistrictCity,
    bernCantonEriswilCity,
    bernCantonErlachCity,
    bernCantonErlenbachImSimmentalCity,
    bernCantonErsigenCity,
    bernCantonEvilardCity,
    bernCantonFerenbalmCity,
    bernCantonFraubrunnenCity,
    bernCantonFrauenkappelenCity,
    bernCantonFrutigenCity,
    bernCantonFrutigenHypniedersimmentalDistrictCity,
    bernCantonGrindelwaldCity,
    bernCantonGrossaffolternCity,
    bernCantonGstaadCity,
    bernCantonGuggisbergCity,
    bernCantonHeimbergCity,
    bernCantonHeimiswilCity,
    bernCantonHermiswilCity,
    bernCantonHerzogenbuchseeCity,
    bernCantonHilterfingenCity,
    bernCantonHindelbankCity,
    bernCantonHuttwilCity,
    bernCantonInsCity,
    bernCantonInterlakenCity,
    bernCantonInterlakenHypoberhasliDistrictCity,
    bernCantonJegenstorfCity,
    bernCantonJuraBernoisCity,
    bernCantonKallnachCity,
    bernCantonKanderstegCity,
    bernCantonKappelenCity,
    bernCantonKehrsatzCity,
    bernCantonKirchbergCity,
    bernCantonKirchlindachCity,
    bernCantonKonizCity,
    bernCantonKonolfingenCity,
    bernCantonKoppigenCity,
    bernCantonKrauchthalCity,
    bernCantonLaNeuvevilleCity,
    bernCantonLangenthalCity,
    bernCantonLangnauCity,
    bernCantonLaupenCity,
    bernCantonLauperswilCity,
    bernCantonLauterbrunnenCity,
    bernCantonLengnauCity,
    bernCantonLenkCity,
    bernCantonLeuzigenCity,
    bernCantonLindenCity,
    bernCantonLotzwilCity,
    bernCantonLutzelfluhCity,
    bernCantonLyssCity,
    bernCantonLyssachCity,
    bernCantonMadiswilCity,
    bernCantonMallerayCity,
    bernCantonMattenCity,
    bernCantonMeinisbergCity,
    bernCantonMeiringenCity,
    bernCantonMelchnauCity,
    bernCantonMoutierCity,
    bernCantonMuhlebergCity,
    bernCantonMuhlethurnenCity,
    bernCantonMunchenbuchseeCity,
    bernCantonMunchenwilerCity,
    bernCantonMunsingenCity,
    bernCantonMuntschemierCity,
    bernCantonMuriCity,
    bernCantonNidauCity,
    bernCantonNiederbippCity,
    bernCantonOberaargauCity,
    bernCantonOberbippCity,
    bernCantonOberburgCity,
    bernCantonOberdiessbachCity,
    bernCantonObersimmentalHypsaanenDistrictCity,
    bernCantonOrpundCity,
    bernCantonOrvinCity,
    bernCantonPeryCity,
    bernCantonPieterlenCity,
    bernCantonRadelfingenCity,
    bernCantonReconvilierCity,
    bernCantonRiggisbergCity,
    bernCantonRinggenbergCity,
    bernCantonRoggwilCity,
    bernCantonRohrbachCity,
    bernCantonRubigenCity,
    bernCantonRuderswilCity,
    bernCantonRueggisbergCity,
    bernCantonRuscheggCity,
    bernCantonSaanenCity,
    bernCantonSaintHypimierCity,
    bernCantonSanktStephanCity,
    bernCantonSchupfenCity,
    bernCantonSeebergCity,
    bernCantonSeedorfCity,
    bernCantonSeelandDistrictCity,
    bernCantonSeftigenCity,
    bernCantonSignauCity,
    bernCantonSigriswilCity,
    bernCantonSpiezCity,
    bernCantonSteffisburgCity,
    bernCantonStettlenCity,
    bernCantonSumiswaldCity,
    bernCantonTauffelenCity,
    bernCantonTavannesCity,
    bernCantonThierachernCity,
    bernCantonThunCity,
    bernCantonThunDistrictCity,
    bernCantonToffenCity,
    bernCantonTrachselwaldCity,
    bernCantonTramelanCity,
    bernCantonTrubCity,
    bernCantonTrubschachenCity,
    bernCantonUetendorfCity,
    bernCantonUnterseenCity,
    bernCantonUrtenenCity,
    bernCantonUttigenCity,
    bernCantonUtzenstorfCity,
    bernCantonVechigenCity,
    bernCantonWalkringenCity,
    bernCantonWangenAnDerAareCity,
    bernCantonWattenwilCity,
    bernCantonWichtrachCity,
    bernCantonWiedlisbachCity,
    bernCantonWilderswilCity,
    bernCantonWimmisCity,
    bernCantonWohlenCity,
    bernCantonWorbCity,
    bernCantonWorbenCity,
    bernCantonWynauCity,
    bernCantonWynigenCity,
    bernCantonWyssachenCity,
    bernCantonZaziwilCity,
    bernCantonZollikofenCity,
    bernCantonZweisimmenCity
  ]);

/// The `Fribourg` region in `Switzerland`
const Region switzerlandFribourgCanton = Region(
  id: 1640,
  parentId: 214,
  longitude: 7.1172635,
  latitude: 46.6816748,
  name: "Fribourg",
  type: "canton",
  stateCode: "FR",
  cities: [
    fribourgCantonAlterswilCity,
    fribourgCantonAttalensCity,
    fribourgCantonAvryHypsurHypmatranCity,
    fribourgCantonBasHypvullyCity,
    fribourgCantonBelfauxCity,
    fribourgCantonBosingenCity,
    fribourgCantonBrocCity,
    fribourgCantonBroyeDistrictCity,
    fribourgCantonBulleCity,
    fribourgCantonCharmeyCity,
    fribourgCantonChatelHypsaintHypdenisCity,
    fribourgCantonCorminboeufCity,
    fribourgCantonCourgevauxCity,
    fribourgCantonCugyCity,
    fribourgCantonDomdidierCity,
    fribourgCantonDudingenCity,
    fribourgCantonEcublensCity,
    fribourgCantonEpendesCity,
    fribourgCantonEstavayerHypleHyplacCity,
    fribourgCantonFlamattCity,
    fribourgCantonFribourgCity,
    fribourgCantonGiffersCity,
    fribourgCantonGivisiezCity,
    fribourgCantonGlaneDistrictCity,
    fribourgCantonGrolleyCity,
    fribourgCantonGruyereDistrictCity,
    fribourgCantonGruyeresCity,
    fribourgCantonHeitenriedCity,
    fribourgCantonKerzersCity,
    fribourgCantonLaRocheCity,
    fribourgCantonLaTourHypdeHyptremeCity,
    fribourgCantonLakeDistrictCity,
    fribourgCantonMarlyCity,
    fribourgCantonMarsensCity,
    fribourgCantonMezieresCity,
    fribourgCantonMurtenmoratCity,
    fribourgCantonOberschrotCity,
    fribourgCantonPlaffeienCity,
    fribourgCantonPraromanCity,
    fribourgCantonRechthaltenCity,
    fribourgCantonRiazCity,
    fribourgCantonRomontCity,
    fribourgCantonRueCity,
    fribourgCantonSalesCity,
    fribourgCantonSanktAntoniCity,
    fribourgCantonSarineDistrictCity,
    fribourgCantonSchmittenCity,
    fribourgCantonSenseDistrictCity,
    fribourgCantonTafersCity,
    fribourgCantonTreyvauxCity,
    fribourgCantonUeberstorfCity,
    fribourgCantonVeveyseDistrictCity,
    fribourgCantonVillarsHypsurHypglaneCity,
    fribourgCantonVillazHypsaintHyppierreCity,
    fribourgCantonVuadensCity
  ]);

/// The `Geneva` region in `Switzerland`
const Region switzerlandGenevaCanton = Region(
  id: 1647,
  parentId: 214,
  longitude: 6.1216925,
  latitude: 46.2180073,
  name: "Geneva",
  type: "canton",
  stateCode: "GE",
  cities: [
    genevaCantonAireHyplaHypvilleCity,
    genevaCantonAnieresCity,
    genevaCantonBellevueCity,
    genevaCantonBernexCity,
    genevaCantonCarougeCity,
    genevaCantonChancyCity,
    genevaCantonCheneHypbougeriesCity,
    genevaCantonCheneHypbourgCity,
    genevaCantonConfignonCity,
    genevaCantonCorsierCity,
    genevaCantonDardagnyCity,
    genevaCantonGeneveCity,
    genevaCantonJussyCity,
    genevaCantonLancyCity,
    genevaCantonLeGrandHypsaconnexCity,
    genevaCantonLesAvanchetsCity,
    genevaCantonMeinierCity,
    genevaCantonMeyrinCity,
    genevaCantonOnexCity,
    genevaCantonPlanHyplesHypouatesCity,
    genevaCantonPuplingeCity,
    genevaCantonSatignyCity,
    genevaCantonThonexCity,
    genevaCantonTroinexCity,
    genevaCantonVandoeuvresCity,
    genevaCantonVernierCity,
    genevaCantonVersoixCity,
    genevaCantonVeyrierCity
  ]);

/// The `Glarus` region in `Switzerland`
const Region switzerlandGlarusCanton = Region(
  id: 1661,
  parentId: 214,
  longitude: 9.0679,
  latitude: 47.0411232,
  name: "Glarus",
  type: "canton",
  stateCode: "GL",
  cities: [
    glarusCantonBiltenCity,
    glarusCantonEnnendaCity,
    glarusCantonGlarusCity,
    glarusCantonLinthalCity,
    glarusCantonLuchsingenCity,
    glarusCantonMollisCity,
    glarusCantonNafelsCity,
    glarusCantonNetstalCity,
    glarusCantonNiederurnenCity,
    glarusCantonOberurnenCity,
    glarusCantonSchwandenCity
  ]);

/// The `Graubünden` region in `Switzerland`
const Region switzerlandGraubundenCanton = Region(
  id: 1660,
  parentId: 214,
  longitude: 9.5780257,
  latitude: 46.6569871,
  name: "Graubünden",
  type: "canton",
  stateCode: "GR",
  cities: [
    graubundenCantonArosaCity,
    graubundenCantonArvigoCity,
    graubundenCantonBonaduzCity,
    graubundenCantonBreilCity,
    graubundenCantonBrusioCity,
    graubundenCantonBusenoCity,
    graubundenCantonCaucoCity,
    graubundenCantonCazisCity,
    graubundenCantonCelerinaCity,
    graubundenCantonChurCity,
    graubundenCantonChurwaldenCity,
    graubundenCantonDavosCity,
    graubundenCantonDisentisCity,
    graubundenCantonDomatCity,
    graubundenCantonFelsbergCity,
    graubundenCantonFlimsCity,
    graubundenCantonGruschCity,
    graubundenCantonHinterrheinCity,
    graubundenCantonIgisCity,
    graubundenCantonIlanzCity,
    graubundenCantonJenazCity,
    graubundenCantonKlostersSerneusCity,
    graubundenCantonLaPuntChamuesHypchCity,
    graubundenCantonLaaxCity,
    graubundenCantonLandquartCity,
    graubundenCantonLenzerheideCity,
    graubundenCantonLuzeinCity,
    graubundenCantonMaienfeldCity,
    graubundenCantonMalansCity,
    graubundenCantonMesoccoCity,
    graubundenCantonPontresinaCity,
    graubundenCantonPoschiavoCity,
    graubundenCantonRegionAlbulaCity,
    graubundenCantonRegionBerninaCity,
    graubundenCantonRegionEngiadinaBassaValMustairCity,
    graubundenCantonRegionImbodenCity,
    graubundenCantonRegionLandquartCity,
    graubundenCantonRegionMalojaCity,
    graubundenCantonRegionMoesaCity,
    graubundenCantonRegionPlessurCity,
    graubundenCantonRegionPrattigauDavosCity,
    graubundenCantonRegionSurselvaCity,
    graubundenCantonRegionViamalaCity,
    graubundenCantonRhazunsCity,
    graubundenCantonSamedanCity,
    graubundenCantonScharansCity,
    graubundenCantonSchiersCity,
    graubundenCantonScuolCity,
    graubundenCantonSilvaplanaCity,
    graubundenCantonStMoritzCity,
    graubundenCantonTaminsCity,
    graubundenCantonThusisCity,
    graubundenCantonTiefencastelCity,
    graubundenCantonTrimmisCity,
    graubundenCantonTrunCity,
    graubundenCantonUntervazCity,
    graubundenCantonValsPlatzCity,
    graubundenCantonZernezCity,
    graubundenCantonZizersCity,
    graubundenCantonZuozCity
  ]);

/// The `Jura` region in `Switzerland`
const Region switzerlandJuraCanton = Region(
  id: 1658,
  parentId: 214,
  longitude: 7.1430608,
  latitude: 47.3444474,
  name: "Jura",
  type: "canton",
  stateCode: "JU",
  cities: [
    juraCantonAlleCity,
    juraCantonBassecourtCity,
    juraCantonBoncourtCity,
    juraCantonCourfaivreCity,
    juraCantonCourgenayCity,
    juraCantonCourrendlinCity,
    juraCantonCourrouxCity,
    juraCantonCourtetelleCity,
    juraCantonDelemontCity,
    juraCantonDelemontDistrictCity,
    juraCantonFontenaisCity,
    juraCantonFranchesHypmontagnesDistrictCity,
    juraCantonGlovelierCity,
    juraCantonLeNoirmontCity,
    juraCantonLesBoisCity,
    juraCantonLesBreuleuxCity,
    juraCantonPorrentruyCity,
    juraCantonPorrentruyDistrictCity,
    juraCantonSaignelegierCity,
    juraCantonVicquesCity
  ]);

/// The `Lucerne` region in `Switzerland`
const Region switzerlandLucerneCanton = Region(
  id: 1663,
  parentId: 214,
  longitude: 8.1662445,
  latitude: 47.0795671,
  name: "Lucerne",
  type: "canton",
  stateCode: "LU",
  cities: [
    lucerneCantonAdligenswilCity,
    lucerneCantonAltishofenCity,
    lucerneCantonBallwilCity,
    lucerneCantonBeromunsterCity,
    lucerneCantonBuchrainCity,
    lucerneCantonBuronCity,
    lucerneCantonButtisholzCity,
    lucerneCantonDagmersellenCity,
    lucerneCantonEbikonCity,
    lucerneCantonEichCity,
    lucerneCantonEmmenCity,
    lucerneCantonEntlebuchCity,
    lucerneCantonEntlebuchDistrictCity,
    lucerneCantonEscholzmattCity,
    lucerneCantonEttiswilCity,
    lucerneCantonFluhliCity,
    lucerneCantonGeuenseeCity,
    lucerneCantonGrosswangenCity,
    lucerneCantonGunzwilCity,
    lucerneCantonHasleCity,
    lucerneCantonHildisriedenCity,
    lucerneCantonHitzkirchCity,
    lucerneCantonHochdorfCity,
    lucerneCantonHochdorfDistrictCity,
    lucerneCantonHohenrainCity,
    lucerneCantonHorwCity,
    lucerneCantonInwilCity,
    lucerneCantonKnutwilCity,
    lucerneCantonKriensCity,
    lucerneCantonLittauCity,
    lucerneCantonLucerneHyplandDistrictCity,
    lucerneCantonLucerneHypstadtDistrictCity,
    lucerneCantonLuthernCity,
    lucerneCantonLuzernCity,
    lucerneCantonMaltersCity,
    lucerneCantonMauenseeCity,
    lucerneCantonMeggenCity,
    lucerneCantonMeierskappelCity,
    lucerneCantonMenznauCity,
    lucerneCantonNebikonCity,
    lucerneCantonNeudorfCity,
    lucerneCantonNeuenkirchCity,
    lucerneCantonNottwilCity,
    lucerneCantonOberkirchCity,
    lucerneCantonPfaffnauCity,
    lucerneCantonReidenCity,
    lucerneCantonRomerswilCity,
    lucerneCantonRootCity,
    lucerneCantonRuswilCity,
    lucerneCantonSchenkonCity,
    lucerneCantonSchotzCity,
    lucerneCantonSchupfheimCity,
    lucerneCantonSchwarzenbergCity,
    lucerneCantonSempachCity,
    lucerneCantonSurseeCity,
    lucerneCantonSurseeDistrictCity,
    lucerneCantonTriengenCity,
    lucerneCantonUdligenswilCity,
    lucerneCantonVitznauCity,
    lucerneCantonWauwilCity,
    lucerneCantonWeggisCity,
    lucerneCantonWerthensteinCity,
    lucerneCantonWikonCity,
    lucerneCantonWillisauCity,
    lucerneCantonWillisauDistrictCity,
    lucerneCantonWolhusenCity,
    lucerneCantonZellCity
  ]);

/// The `Neuchâtel` region in `Switzerland`
const Region switzerlandNeuchatelCanton = Region(
  id: 1659,
  parentId: 214,
  longitude: 6.9292732,
  latitude: 46.9899874,
  name: "Neuchâtel",
  type: "canton",
  stateCode: "NE",
  cities: [
    neuchatelCantonAuvernierCity,
    neuchatelCantonBevaixCity,
    neuchatelCantonBoudryCity,
    neuchatelCantonBoudryDistrictCity,
    neuchatelCantonCernierCity,
    neuchatelCantonChezardHypsaintHypmartinCity,
    neuchatelCantonCornauxCity,
    neuchatelCantonCortaillodCity,
    neuchatelCantonCouvetCity,
    neuchatelCantonDombressonCity,
    neuchatelCantonFleurierCity,
    neuchatelCantonFontainemelonCity,
    neuchatelCantonGorgierCity,
    neuchatelCantonGrandHypsavagnierCity,
    neuchatelCantonLaChauxHypdeHypfondsCity,
    neuchatelCantonLaChauxHypdeHypfondsDistrictCity,
    neuchatelCantonLeLanderonCity,
    neuchatelCantonLeLocleCity,
    neuchatelCantonLeLocleDistrictCity,
    neuchatelCantonLesBrenetsCity,
    neuchatelCantonLesGeneveysHypsurHypcoffraneCity,
    neuchatelCantonLesPontsHypdeHypmartelCity,
    neuchatelCantonMarinHypepagnierCity,
    neuchatelCantonNeuchatelCity,
    neuchatelCantonNeuchatelDistrictCity,
    neuchatelCantonPeseuxCity,
    neuchatelCantonSaintHypaubinHypsaugesCity,
    neuchatelCantonSaintHypblaiseCity,
    neuchatelCantonTraversCity,
    neuchatelCantonValHypdeHypruzDistrictCity,
    neuchatelCantonValHypdeHyptraversDistrictCity
  ]);

/// The `Nidwalden` region in `Switzerland`
const Region switzerlandNidwaldenCanton = Region(
  id: 1652,
  parentId: 214,
  longitude: 8.3849982,
  latitude: 46.9267016,
  name: "Nidwalden",
  type: "canton",
  stateCode: "NW",
  cities: [
    nidwaldenCantonBeckenriedCity,
    nidwaldenCantonBuochsCity,
    nidwaldenCantonDallenwilCity,
    nidwaldenCantonEmmettenCity,
    nidwaldenCantonEnnetburgenCity,
    nidwaldenCantonHergiswilCity,
    nidwaldenCantonStansCity,
    nidwaldenCantonStansstadCity,
    nidwaldenCantonWolfenschiessenCity
  ]);

/// The `Obwalden` region in `Switzerland`
const Region switzerlandObwaldenCanton = Region(
  id: 1650,
  parentId: 214,
  longitude: 8.251249,
  latitude: 46.877858,
  name: "Obwalden",
  type: "canton",
  stateCode: "OW",
  cities: [
    obwaldenCantonAlpnachCity,
    obwaldenCantonEngelbergCity,
    obwaldenCantonGiswilCity,
    obwaldenCantonKernsCity,
    obwaldenCantonLungernCity,
    obwaldenCantonSachselnCity,
    obwaldenCantonSarnenCity
  ]);

/// The `Schaffhausen` region in `Switzerland`
const Region switzerlandSchaffhausenCanton = Region(
  id: 1654,
  parentId: 214,
  longitude: 8.568004,
  latitude: 47.7009364,
  name: "Schaffhausen",
  type: "canton",
  stateCode: "SH",
  cities: [
    schaffhausenCantonBeringenCity,
    schaffhausenCantonBezirkOberklettgauCity,
    schaffhausenCantonBezirkReiatCity,
    schaffhausenCantonBezirkSchaffhausenCity,
    schaffhausenCantonBezirkSchleitheimCity,
    schaffhausenCantonBezirkSteinCity,
    schaffhausenCantonBezirkUnterklettgauCity,
    schaffhausenCantonHallauCity,
    schaffhausenCantonLohningenCity,
    schaffhausenCantonNeuhausenCity,
    schaffhausenCantonNeunkirchCity,
    schaffhausenCantonRamsenCity,
    schaffhausenCantonSchaffhausenCity,
    schaffhausenCantonSchleitheimCity,
    schaffhausenCantonSteinAmRheinCity,
    schaffhausenCantonStettenCity,
    schaffhausenCantonThayngenCity,
    schaffhausenCantonWilchingenCity
  ]);

/// The `Schwyz` region in `Switzerland`
const Region switzerlandSchwyzCanton = Region(
  id: 1653,
  parentId: 214,
  longitude: 8.6529884,
  latitude: 47.0207138,
  name: "Schwyz",
  type: "canton",
  stateCode: "SZ",
  cities: [
    schwyzCantonAltendorfCity,
    schwyzCantonArthCity,
    schwyzCantonBachCity,
    schwyzCantonBezirkEinsiedelnCity,
    schwyzCantonBezirkGersauCity,
    schwyzCantonBezirkHofeCity,
    schwyzCantonBezirkKussnachtCity,
    schwyzCantonBezirkMarchCity,
    schwyzCantonBezirkSchwyzCity,
    schwyzCantonEinsiedelnCity,
    schwyzCantonFeusisbergCity,
    schwyzCantonFreienbachCity,
    schwyzCantonGersauCity,
    schwyzCantonGoldauCity,
    schwyzCantonIbachCity,
    schwyzCantonIngenbohlCity,
    schwyzCantonKussnachtCity,
    schwyzCantonLachenCity,
    schwyzCantonMuotathalCity,
    schwyzCantonPfaffikonCity,
    schwyzCantonReichenburgCity,
    schwyzCantonRothenthurmCity,
    schwyzCantonSattelCity,
    schwyzCantonSchindellegiCity,
    schwyzCantonSchubelbachCity,
    schwyzCantonSchwyzCity,
    schwyzCantonSiebnenCity,
    schwyzCantonSteinenCity,
    schwyzCantonTuggenCity,
    schwyzCantonUnteribergCity,
    schwyzCantonVorderthalCity,
    schwyzCantonWollerauCity
  ]);

/// The `Solothurn` region in `Switzerland`
const Region switzerlandSolothurnCanton = Region(
  id: 1662,
  parentId: 214,
  longitude: 7.6388385,
  latitude: 47.3320717,
  name: "Solothurn",
  type: "canton",
  stateCode: "SO",
  cities: [
    solothurnCantonBalsthalCity,
    solothurnCantonBettlachCity,
    solothurnCantonBezirkBucheggbergCity,
    solothurnCantonBezirkDorneckCity,
    solothurnCantonBezirkGauCity,
    solothurnCantonBezirkGosgenCity,
    solothurnCantonBezirkLebernCity,
    solothurnCantonBezirkOltenCity,
    solothurnCantonBezirkSolothurnCity,
    solothurnCantonBezirkThalCity,
    solothurnCantonBezirkThiersteinCity,
    solothurnCantonBezirkWasseramtCity,
    solothurnCantonBiberistCity,
    solothurnCantonBreitenbachCity,
    solothurnCantonBusserachCity,
    solothurnCantonDeitingenCity,
    solothurnCantonDerendingenCity,
    solothurnCantonDornachCity,
    solothurnCantonEgerkingenCity,
    solothurnCantonErlinsbachCity,
    solothurnCantonFulenbachCity,
    solothurnCantonGerlafingenCity,
    solothurnCantonGrenchenCity,
    solothurnCantonGunzgenCity,
    solothurnCantonHagendorfCity,
    solothurnCantonHimmelriedCity,
    solothurnCantonHochwaldCity,
    solothurnCantonKleinlutzelCity,
    solothurnCantonKriegstettenCity,
    solothurnCantonLangendorfCity,
    solothurnCantonLaupersdorfCity,
    solothurnCantonLostorfCity,
    solothurnCantonLuterbachCity,
    solothurnCantonMatzendorfCity,
    solothurnCantonMessenCity,
    solothurnCantonNiedergosgenCity,
    solothurnCantonNunningenCity,
    solothurnCantonOberbuchsitenCity,
    solothurnCantonObergosgenCity,
    solothurnCantonOensingenCity,
    solothurnCantonOltenCity,
    solothurnCantonRiedholzCity,
    solothurnCantonRodersdorfCity,
    solothurnCantonRohrCity,
    solothurnCantonSchonenwerdCity,
    solothurnCantonSelzachCity,
    solothurnCantonSolothurnCity,
    solothurnCantonSubingenCity,
    solothurnCantonTrimbachCity,
    solothurnCantonWangenCity,
    solothurnCantonWelschenrohrCity,
    solothurnCantonWolfwilCity,
    solothurnCantonZuchwilCity
  ]);

/// The `St. Gallen` region in `Switzerland`
const Region switzerlandStGallenCanton = Region(
  id: 1644,
  parentId: 214,
  longitude: 9.3504332,
  latitude: 47.1456254,
  name: "St. Gallen",
  type: "canton",
  stateCode: "SG",
  cities: [
    stGallenCantonAltstattenCity,
    stGallenCantonAmdenCity,
    stGallenCantonAndwilCity,
    stGallenCantonAuCity,
    stGallenCantonBadRagazCity,
    stGallenCantonBalgachCity,
    stGallenCantonBenkenCity,
    stGallenCantonBronschhofenCity,
    stGallenCantonBuchsCity,
    stGallenCantonButschwilCity,
    stGallenCantonDegersheimCity,
    stGallenCantonDiepoldsauCity,
    stGallenCantonEbnatHypkappelCity,
    stGallenCantonEggersrietCity,
    stGallenCantonEichbergCity,
    stGallenCantonEschenbachCity,
    stGallenCantonFlawilCity,
    stGallenCantonFlumsCity,
    stGallenCantonGamsCity,
    stGallenCantonGanterschwilCity,
    stGallenCantonGoldachCity,
    stGallenCantonGoldingenCity,
    stGallenCantonGommiswaldCity,
    stGallenCantonGossauCity,
    stGallenCantonGrabsCity,
    stGallenCantonHaagrheintalCity,
    stGallenCantonHaggenschwilCity,
    stGallenCantonHornCity,
    stGallenCantonJonaCity,
    stGallenCantonJonschwilCity,
    stGallenCantonKaltbrunnCity,
    stGallenCantonKirchbergCity,
    stGallenCantonKrummenauCity,
    stGallenCantonLichtensteigCity,
    stGallenCantonLutisburgCity,
    stGallenCantonMogelsbergCity,
    stGallenCantonMorschwilCity,
    stGallenCantonMosnangCity,
    stGallenCantonMuolenCity,
    stGallenCantonNiederburenCity,
    stGallenCantonNiederhelfenschwilCity,
    stGallenCantonOberhelfenschwilCity,
    stGallenCantonOberrietCity,
    stGallenCantonOberuzwilCity,
    stGallenCantonQuartenCity,
    stGallenCantonRapperswilCity,
    stGallenCantonRebsteinCity,
    stGallenCantonRheineckCity,
    stGallenCantonRorschachCity,
    stGallenCantonRuthiCity,
    stGallenCantonSanktGallenCity,
    stGallenCantonSanktGallenkappelCity,
    stGallenCantonSanktMargrethenCity,
    stGallenCantonSanktPeterzellCity,
    stGallenCantonSargansCity,
    stGallenCantonSchanisCity,
    stGallenCantonSchmerikonCity,
    stGallenCantonSennwaldCity,
    stGallenCantonSevelenCity,
    stGallenCantonThalCity,
    stGallenCantonUznachCity,
    stGallenCantonUzwilCity,
    stGallenCantonWahlkreisRheintalCity,
    stGallenCantonWahlkreisRorschachCity,
    stGallenCantonWahlkreisSarganserlandCity,
    stGallenCantonWahlkreisSeeHypgasterCity,
    stGallenCantonWahlkreisStGallenCity,
    stGallenCantonWahlkreisToggenburgCity,
    stGallenCantonWahlkreisWerdenbergCity,
    stGallenCantonWahlkreisWilCity,
    stGallenCantonWaldkirchCity,
    stGallenCantonWalenstadtCity,
    stGallenCantonWattwilCity,
    stGallenCantonWeesenCity,
    stGallenCantonWilCity,
    stGallenCantonWildhausCity,
    stGallenCantonWittenbachCity,
    stGallenCantonZuzwilCity
  ]);

/// The `Thurgau` region in `Switzerland`
const Region switzerlandThurgauCanton = Region(
  id: 1657,
  parentId: 214,
  longitude: 9.0557371,
  latitude: 47.6037856,
  name: "Thurgau",
  type: "canton",
  stateCode: "TG",
  cities: [
    thurgauCantonAadorfCity,
    thurgauCantonAffeltrangenCity,
    thurgauCantonAltnauCity,
    thurgauCantonAmriswilCity,
    thurgauCantonArbonCity,
    thurgauCantonArbonDistrictCity,
    thurgauCantonBergCity,
    thurgauCantonBottighofenCity,
    thurgauCantonBurglenCity,
    thurgauCantonDiessenhofenCity,
    thurgauCantonEgnachCity,
    thurgauCantonErlenCity,
    thurgauCantonErmatingenCity,
    thurgauCantonEschenzCity,
    thurgauCantonEschlikonCity,
    thurgauCantonFischingenCity,
    thurgauCantonFrauenfeldCity,
    thurgauCantonFrauenfeldDistrictCity,
    thurgauCantonGachnangCity,
    thurgauCantonGottliebenCity,
    thurgauCantonGuttingenCity,
    thurgauCantonHomburgCity,
    thurgauCantonHuttwilenCity,
    thurgauCantonKreuzlingenCity,
    thurgauCantonKreuzlingenDistrictCity,
    thurgauCantonLangrickenbachCity,
    thurgauCantonMarstettenHypdorfCity,
    thurgauCantonMatzingenCity,
    thurgauCantonMullheimCity,
    thurgauCantonMunchwilenCity,
    thurgauCantonMunchwilenDistrictCity,
    thurgauCantonMunsterlingenCity,
    thurgauCantonPfynCity,
    thurgauCantonRickenbachBeiWilCity,
    thurgauCantonRoggwilCity,
    thurgauCantonRomanshornCity,
    thurgauCantonSalmsachCity,
    thurgauCantonSirnachCity,
    thurgauCantonSteckbornCity,
    thurgauCantonStettfurtCity,
    thurgauCantonSulgenCity,
    thurgauCantonTagerwilenCity,
    thurgauCantonThundorfCity,
    thurgauCantonUttwilCity,
    thurgauCantonWagenhausenCity,
    thurgauCantonWangiCity,
    thurgauCantonWeinfeldenCity,
    thurgauCantonWeinfeldenDistrictCity,
    thurgauCantonWigoltingenCity
  ]);

/// The `Ticino` region in `Switzerland`
const Region switzerlandTicinoCanton = Region(
  id: 1643,
  parentId: 214,
  longitude: 8.8004529,
  latitude: 46.331734,
  name: "Ticino",
  type: "canton",
  stateCode: "TI",
  cities: [
    ticinoCantonAcquarossaCity,
    ticinoCantonAgnoCity,
    ticinoCantonAiroloCity,
    ticinoCantonArzoCity,
    ticinoCantonAsconaCity,
    ticinoCantonBalernaCity,
    ticinoCantonBellinzonaCity,
    ticinoCantonBellinzonaDistrictCity,
    ticinoCantonBiascaCity,
    ticinoCantonBioggioCity,
    ticinoCantonBlenioDistrictCity,
    ticinoCantonBodioCity,
    ticinoCantonBrissagoCity,
    ticinoCantonCadempinoCity,
    ticinoCantonCadenazzoCity,
    ticinoCantonCadroCity,
    ticinoCantonCamorinoCity,
    ticinoCantonCanobbioCity,
    ticinoCantonCaslanoCity,
    ticinoCantonCastelSanPietroCity,
    ticinoCantonCevioCity,
    ticinoCantonChiassoCity,
    ticinoCantonClaroCity,
    ticinoCantonComanoCity,
    ticinoCantonCugnascoCity,
    ticinoCantonFaidoCity,
    ticinoCantonGiubiascoCity,
    ticinoCantonGordolaCity,
    ticinoCantonGravesanoCity,
    ticinoCantonLavertezzoCity,
    ticinoCantonLeventinaDistrictCity,
    ticinoCantonLigornettoCity,
    ticinoCantonLocarnoCity,
    ticinoCantonLocarnoDistrictCity,
    ticinoCantonLodrinoCity,
    ticinoCantonLosoneCity,
    ticinoCantonLuganoCity,
    ticinoCantonLuganoDistrictCity,
    ticinoCantonLuminoCity,
    ticinoCantonMagadinoCity,
    ticinoCantonMalvagliaCity,
    ticinoCantonMassagnoCity,
    ticinoCantonMelanoCity,
    ticinoCantonMelideCity,
    ticinoCantonMendrisioCity,
    ticinoCantonMendrisioDistrictCity,
    ticinoCantonMinusioCity,
    ticinoCantonMontagnolaCity,
    ticinoCantonMonteCarassoCity,
    ticinoCantonMorbioInferioreCity,
    ticinoCantonMuraltoCity,
    ticinoCantonNovazzanoCity,
    ticinoCantonPregassonaCity,
    ticinoCantonPuraCity,
    ticinoCantonRivaSanVitaleCity,
    ticinoCantonRivieraDistrictCity,
    ticinoCantonSementinaCity,
    ticinoCantonSorengoCity,
    ticinoCantonStabioCity,
    ticinoCantonTessereteCity,
    ticinoCantonVallemaggiaDistrictCity,
    ticinoCantonVerscioCity,
    ticinoCantonViganelloCity
  ]);

/// The `Uri` region in `Switzerland`
const Region switzerlandUriCanton = Region(
  id: 1642,
  parentId: 214,
  longitude: -71.5308537,
  latitude: 41.4860647,
  name: "Uri",
  type: "canton",
  stateCode: "UR",
  cities: [
    uriCantonAltdorfCity,
    uriCantonAndermattCity,
    uriCantonAttinghausenCity,
    uriCantonBauenCity,
    uriCantonBurglenCity,
    uriCantonErstfeldCity,
    uriCantonFluelenCity,
    uriCantonSchattdorfCity,
    uriCantonSeedorfCity,
    uriCantonSilenenCity
  ]);

/// The `Valais` region in `Switzerland`
const Region switzerlandValaisCanton = Region(
  id: 1648,
  parentId: 214,
  longitude: 7.5449226,
  latitude: 46.1904614,
  name: "Valais",
  type: "canton",
  stateCode: "VS",
  cities: [
    valaisCantonArdonCity,
    valaisCantonAyentCity,
    valaisCantonBagnesCity,
    valaisCantonBaltschiederCity,
    valaisCantonBasseHypnendazCity,
    valaisCantonBrigCity,
    valaisCantonBrigDistrictCity,
    valaisCantonChalaisCity,
    valaisCantonChamosonCity,
    valaisCantonChamperyCity,
    valaisCantonCharratCity,
    valaisCantonChermignonHypdenHautCity,
    valaisCantonChippisCity,
    valaisCantonCollombeyCity,
    valaisCantonContheyCity,
    valaisCantonContheyDistrictCity,
    valaisCantonEntremontDistrictCity,
    valaisCantonEvionnazCity,
    valaisCantonEvoleneCity,
    valaisCantonFieschCity,
    valaisCantonFullyCity,
    valaisCantonGampelCity,
    valaisCantonGomsDistrictCity,
    valaisCantonGrachenCity,
    valaisCantonGrimisuatCity,
    valaisCantonGroneCity,
    valaisCantonHeremenceCity,
    valaisCantonHerensDistrictCity,
    valaisCantonLensCity,
    valaisCantonLeukCity,
    valaisCantonLeukDistrictCity,
    valaisCantonLeukerbadCity,
    valaisCantonLeytronCity,
    valaisCantonMartignyDistrictCity,
    valaisCantonMartignyHypcombeCity,
    valaisCantonMartignyHypvilleCity,
    valaisCantonMontanaCity,
    valaisCantonMontheyCity,
    valaisCantonMontheyDistrictCity,
    valaisCantonNatersCity,
    valaisCantonOrsieresCity,
    valaisCantonRandogneCity,
    valaisCantonRaronCity,
    valaisCantonRaronDistrictCity,
    valaisCantonRiddesCity,
    valaisCantonSaasHypfeeCity,
    valaisCantonSaasHypgrundCity,
    valaisCantonSaillonCity,
    valaisCantonSaintHypleonardCity,
    valaisCantonSaintHypmauriceCity,
    valaisCantonSaintHypmauriceDistrictCity,
    valaisCantonSalgeschCity,
    valaisCantonSalvanCity,
    valaisCantonSanktNiklausCity,
    valaisCantonSavieseCity,
    valaisCantonSaxonCity,
    valaisCantonSierreCity,
    valaisCantonSierreDistrictCity,
    valaisCantonSionDistrictCity,
    valaisCantonSittenCity,
    valaisCantonStaldenCity,
    valaisCantonTanayCity,
    valaisCantonTroistorrentsCity,
    valaisCantonTurtmannCity,
    valaisCantonVarenCity,
    valaisCantonVerbierCity,
    valaisCantonVernayazCity,
    valaisCantonVetrozCity,
    valaisCantonVexCity,
    valaisCantonVionnazCity,
    valaisCantonVispCity,
    valaisCantonVispDistrictCity,
    valaisCantonVisperterminenCity,
    valaisCantonVouvryCity,
    valaisCantonZermattCity
  ]);

/// The `Vaud` region in `Switzerland`
const Region switzerlandVaudCanton = Region(
  id: 1651,
  parentId: 214,
  longitude: 6.536765,
  latitude: 46.5613135,
  name: "Vaud",
  type: "canton",
  stateCode: "VD",
  cities: [
    vaudCantonAigleCity,
    vaudCantonAigleDistrictCity,
    vaudCantonApplesCity,
    vaudCantonArzierCity,
    vaudCantonAubonneCity,
    vaudCantonAvenchesCity,
    vaudCantonBallensCity,
    vaudCantonBavoisCity,
    vaudCantonBegninsCity,
    vaudCantonBelmontHypsurHyplausanneCity,
    vaudCantonBerolleCity,
    vaudCantonBexCity,
    vaudCantonBiereCity,
    vaudCantonBlecheretteCity,
    vaudCantonBlonayCity,
    vaudCantonBottensCity,
    vaudCantonBroyeHypvullyDistrictCity,
    vaudCantonBussignyCity,
    vaudCantonCauxCity,
    vaudCantonChardonneCity,
    vaudCantonChateauHypdoexCity,
    vaudCantonChavannesCity,
    vaudCantonChavannesHypleHypveyronCity,
    vaudCantonChavornayCity,
    vaudCantonCheseauxCity,
    vaudCantonChevillyCity,
    vaudCantonChexbresCity,
    vaudCantonColombierCity,
    vaudCantonCoppetCity,
    vaudCantonCossonayCity,
    vaudCantonCrissierCity,
    vaudCantonCuarnensCity,
    vaudCantonCullyCity,
    vaudCantonEchallensCity,
    vaudCantonEcublensCity,
    vaudCantonEpalingesCity,
    vaudCantonFerreyresCity,
    vaudCantonFounexCity,
    vaudCantonFroidevilleCity,
    vaudCantonGenolierCity,
    vaudCantonGimelCity,
    vaudCantonGlandCity,
    vaudCantonGrancyCity,
    vaudCantonGrandsonCity,
    vaudCantonGrosHypdeHypvaudDistrictCity,
    vaudCantonGryonCity,
    vaudCantonJongnyCity,
    vaudCantonJuraHypnordVaudoisDistrictCity,
    vaudCantonLaSarrazCity,
    vaudCantonLaTourHypdeHyppeilzCity,
    vaudCantonLausanneCity,
    vaudCantonLausanneDistrictCity,
    vaudCantonLavauxHyporonDistrictCity,
    vaudCantonLeChenitCity,
    vaudCantonLeMontHypsurHyplausanneCity,
    vaudCantonLeVaudCity,
    vaudCantonLeysinCity,
    vaudCantonLucensCity,
    vaudCantonLutryCity,
    vaudCantonMaurazCity,
    vaudCantonMollensCity,
    vaudCantonMontagnyCity,
    vaudCantonMontreuxCity,
    vaudCantonMorgesCity,
    vaudCantonMorgesDistrictCity,
    vaudCantonMoudonCity,
    vaudCantonNyonCity,
    vaudCantonNyonDistrictCity,
    vaudCantonOllonCity,
    vaudCantonOrbeCity,
    vaudCantonOronHyplaHypvilleCity,
    vaudCantonOuestLausannoisDistrictCity,
    vaudCantonPaillyCity,
    vaudCantonPalezieuxCity,
    vaudCantonPampignyCity,
    vaudCantonPaudexCity,
    vaudCantonPayerneCity,
    vaudCantonPenthalazCity,
    vaudCantonPenthereazCity,
    vaudCantonPerroyCity,
    vaudCantonPompaplesCity,
    vaudCantonPranginsCity,
    vaudCantonPreverengesCity,
    vaudCantonPrillyCity,
    vaudCantonPuidouxCity,
    vaudCantonPullyCity,
    vaudCantonRenensCity,
    vaudCantonRivieraHyppaysHypdenhautDistrictCity,
    vaudCantonRolleCity,
    vaudCantonRomanelHypsurHyplausanneCity,
    vaudCantonSaintHypcergueCity,
    vaudCantonSaintHyplivresCity,
    vaudCantonSaintHypprexCity,
    vaudCantonSainteHypcroixCity,
    vaudCantonSaubrazCity,
    vaudCantonSavignyCity,
    vaudCantonSottensCity,
    vaudCantonTrelexCity,
    vaudCantonVallorbeCity,
    vaudCantonVeveyCity,
    vaudCantonVillarsHypsurHypollonCity,
    vaudCantonVilleneuveCity,
    vaudCantonVuarrensCity,
    vaudCantonYverdonHyplesHypbainsCity,
    vaudCantonYvonandCity
  ]);

/// The `Zug` region in `Switzerland`
const Region switzerlandZugCanton = Region(
  id: 1646,
  parentId: 214,
  longitude: 8.5154749,
  latitude: 47.1661505,
  name: "Zug",
  type: "canton",
  stateCode: "ZG",
  cities: [
    zugCantonBaarCity,
    zugCantonChamCity,
    zugCantonHunenbergCity,
    zugCantonMenzingenCity,
    zugCantonRotkreuzCity,
    zugCantonSteinhausenCity,
    zugCantonUnterageriCity,
    zugCantonWalchwilCity,
    zugCantonZugCity
  ]);

/// The `Zürich` region in `Switzerland`
const Region switzerlandZurichCanton = Region(
  id: 1656,
  parentId: 214,
  longitude: 8.6356452,
  latitude: 47.359536,
  name: "Zürich",
  type: "canton",
  stateCode: "ZH",
  cities: [
    zurichCantonAdliswilCity,
    zurichCantonAdliswilAdliswilstadtkernCity,
    zurichCantonAdliswilHundliHypzopfCity,
    zurichCantonAdliswilOberleimbachCity,
    zurichCantonAdliswilSonnenbergCity,
    zurichCantonAdliswilSoodCity,
    zurichCantonAdliswilTalCity,
    zurichCantonAeschCity,
    zurichCantonAffolternHasenbuelCity,
    zurichCantonAffolternOberdorfCity,
    zurichCantonAffolternSonnenbergCity,
    zurichCantonAffolternUnterdorfCity,
    zurichCantonAffolternAmAlbisCity,
    zurichCantonAndelfingenCity,
    zurichCantonAuCity,
    zurichCantonAuMittelHypdorfCity,
    zurichCantonAuUnterHypdorfCity,
    zurichCantonBachenbulachCity,
    zurichCantonBaretswilCity,
    zurichCantonBassersdorfCity,
    zurichCantonBaumaCity,
    zurichCantonBenglenCity,
    zurichCantonBezirkAffolternCity,
    zurichCantonBezirkAndelfingenCity,
    zurichCantonBezirkBulachCity,
    zurichCantonBezirkDielsdorfCity,
    zurichCantonBezirkDietikonCity,
    zurichCantonBezirkHinwilCity,
    zurichCantonBezirkHorgenCity,
    zurichCantonBezirkMeilenCity,
    zurichCantonBezirkPfaffikonCity,
    zurichCantonBezirkUsterCity,
    zurichCantonBezirkWinterthurCity,
    zurichCantonBezirkZurichCity,
    zurichCantonBinzCity,
    zurichCantonBinzikonCity,
    zurichCantonBirchwilCity,
    zurichCantonBirmensdorfCity,
    zurichCantonBonstettenCity,
    zurichCantonBruttenCity,
    zurichCantonBruttisellenCity,
    zurichCantonBubikonCity,
    zurichCantonBulachCity,
    zurichCantonBulachGstucktCity,
    zurichCantonBulachSeemattCity,
    zurichCantonBulachSoliganterCity,
    zurichCantonDachsenCity,
    zurichCantonDallikonDallikondorfCity,
    zurichCantonDanikonCity,
    zurichCantonDielsdorfCity,
    zurichCantonDietikonCity,
    zurichCantonDietikonAlmendCity,
    zurichCantonDietikonGuggenbuhlCity,
    zurichCantonDietikonHofackerCity,
    zurichCantonDietikonKreuzackerCity,
    zurichCantonDietikonOberdorfCity,
    zurichCantonDietikonSchonenwerdCity,
    zurichCantonDietikonVorstadtCity,
    zurichCantonDietlikonDietlikondorfCity,
    zurichCantonDietlikonEichwiesenCity,
    zurichCantonDorfCity,
    zurichCantonDubendorfCity,
    zurichCantonDubendorfKunklerstrasseCity,
    zurichCantonDubendorfSonnenbergCity,
    zurichCantonDubendorfVogelquartierCity,
    zurichCantonDubendorfWasserfurrenCity,
    zurichCantonDurntenCity,
    zurichCantonEbmatingenCity,
    zurichCantonEffretikonCity,
    zurichCantonEffretikonRappenhaldeHypbannhaldeCity,
    zurichCantonEffretikonRikonCity,
    zurichCantonEffretikonWattCity,
    zurichCantonEggCity,
    zurichCantonElggCity,
    zurichCantonElggStadtchenUndUmgebungCity,
    zurichCantonElsauHypraterschenCity,
    zurichCantonElsauHypraterschenRaterschenCity,
    zurichCantonEmbrachCity,
    zurichCantonEmbrachEmbrachdorfkernCity,
    zurichCantonEmbrachKellersackerCity,
    zurichCantonErlenbachCity,
    zurichCantonErlenbachLinksDesDorfbachsOberhalbBahnlinieCity,
    zurichCantonErlenbachRechtsDesDorfbachsOberhalbBahnlinieCity,
    zurichCantonEsslingenCity,
    zurichCantonFallandenCity,
    zurichCantonFehraltorfCity,
    zurichCantonFeldmeilenCity,
    zurichCantonFeuerthalenCity,
    zurichCantonFlurlingenCity,
    zurichCantonFreiensteinCity,
    zurichCantonGattikonCity,
    zurichCantonGeroldswilCity,
    zurichCantonGlattbruggCity,
    zurichCantonGlattbruggRohrplattenHypbalsbergCity,
    zurichCantonGlattbruggWydackerbettackerlattenwiesenCity,
    zurichCantonGlattfeldenCity,
    zurichCantonGockhausenCity,
    zurichCantonGossauCity,
    zurichCantonGreifenseeCity,
    zurichCantonGreifenseeMullerwisSeilerwisCity,
    zurichCantonGreifenseePfisterholzliCity,
    zurichCantonGrossackeropfikonCity,
    zurichCantonGrutCity,
    zurichCantonGutenswilCity,
    zurichCantonHadlikonCity,
    zurichCantonHausenAmAlbisHausendorfCity,
    zurichCantonHedingenCity,
    zurichCantonHegnauCity,
    zurichCantonHegnauDammbodenHypgrindelCity,
    zurichCantonHegnauSunnebuelHypeichCity,
    zurichCantonHenggartCity,
    zurichCantonHerrlibergCity,
    zurichCantonHettlingenCity,
    zurichCantonHintereggCity,
    zurichCantonHinwilCity,
    zurichCantonHittnauHittnaudorfCity,
    zurichCantonHochfeldenCity,
    zurichCantonHofstettenCity,
    zurichCantonHombrechtikonCity,
    zurichCantonHorgenCity,
    zurichCantonHorgenAllmendCity,
    zurichCantonHorgenHorgendorfkernCity,
    zurichCantonHorgenOberdorfCity,
    zurichCantonHorgenSchellerHypstockerstrasseCity,
    zurichCantonHoriCity,
    zurichCantonIllnauCity,
    zurichCantonIllnauUnterHypillnauCity,
    zurichCantonKilchbergCity,
    zurichCantonKilchbergBachlerHypstockenCity,
    zurichCantonKilchbergKilchbergdorfkernCity,
    zurichCantonKindhausenKindhausendorfCity,
    zurichCantonKleinandelfingenCity,
    zurichCantonKlotenCity,
    zurichCantonKlotenBalsbergCity,
    zurichCantonKlotenFreienbergchanzlerHypchliniChaserenCity,
    zurichCantonKlotenGeissbergCity,
    zurichCantonKlotenHolbergCity,
    zurichCantonKlotenHorainliCity,
    zurichCantonKlotenHostrassCity,
    zurichCantonKlotenKlotenzentrumCity,
    zurichCantonKlotenRutlenCity,
    zurichCantonKlotenSpitzCity,
    zurichCantonKnonauCity,
    zurichCantonKollbrunnCity,
    zurichCantonKollbrunnKollbrunndorfkernCity,
    zurichCantonKusnachtCity,
    zurichCantonKusnachtDorfCity,
    zurichCantonKusnachtGoldbachCity,
    zurichCantonKusnachtHeslibachCity,
    zurichCantonKusnachtItschnachCity,
    zurichCantonKusnachtSchiedhaldenCity,
    zurichCantonLangnauLangnaudorfCity,
    zurichCantonLangnauVitaquartierCity,
    zurichCantonLangnauAmAlbisCity,
    zurichCantonMannedorfCity,
    zurichCantonMannedorfAusserfeldCity,
    zurichCantonMannedorfDorfkernCity,
    zurichCantonMarthalenCity,
    zurichCantonMattenbachkreis7City,
    zurichCantonMattenbachkreis7DeutwegCity,
    zurichCantonMattenbachkreis7EndlikerCity,
    zurichCantonMattenbachkreis7GutschickCity,
    zurichCantonMeilenCity,
    zurichCantonMettmenstettenCity,
    zurichCantonMonchaltorfCity,
    zurichCantonMonchaltorfDorfCity,
    zurichCantonMuhlehaldeCity,
    zurichCantonNanikonCity,
    zurichCantonNanikonNanikondorfkernCity,
    zurichCantonNeerachCity,
    zurichCantonNeftenbachDorfNeftenbachCity,
    zurichCantonNiederglattCity,
    zurichCantonNiederglattNiederglattdorfkernCity,
    zurichCantonNiederhasliCity,
    zurichCantonNurensdorfCity,
    zurichCantonOberengstringenCity,
    zurichCantonOberengstringenRauchacherCity,
    zurichCantonOberengstringenSonnenbergCity,
    zurichCantonOberengstringenZentrumCity,
    zurichCantonOberglattCity,
    zurichCantonOberglattBahnhofquartierCity,
    zurichCantonOberglattOberglattdorfkernCity,
    zurichCantonObermeilenCity,
    zurichCantonOberriedenCity,
    zurichCantonOberriedenBergCity,
    zurichCantonOberriedenMitteCity,
    zurichCantonOberwinterthurkreis2City,
    zurichCantonOberwinterthurkreis2GuggenbuhlCity,
    zurichCantonOberwinterthurkreis2HegiCity,
    zurichCantonOberwinterthurkreis2TalackerCity,
    zurichCantonOberwinterthurkreis2ZinzikonCity,
    zurichCantonObfeldenCity,
    zurichCantonObfeldenOberlunnernCity,
    zurichCantonObfeldenToussenCity,
    zurichCantonOetwilCity,
    zurichCantonOpfikonCity,
    zurichCantonOtelfingenCity,
    zurichCantonOttenbachCity,
    zurichCantonPfaffhausenCity,
    zurichCantonPfaffikonCity,
    zurichCantonPfaffikonIrgenhausenCity,
    zurichCantonPfaffikonPfaffikondorfkernCity,
    zurichCantonPfungenCity,
    zurichCantonRafzCity,
    zurichCantonRegensdorfCity,
    zurichCantonRegensdorfFeldblumenHypriedthofstrasseCity,
    zurichCantonRegensdorfHofacherHypgeerenCity,
    zurichCantonRegensdorfObstgartenCity,
    zurichCantonRichterswilCity,
    zurichCantonRichterswilBurghaldeCity,
    zurichCantonRichterswilDorfkernCity,
    zurichCantonRichterswilRichterswildorfkernCity,
    zurichCantonRorbasCity,
    zurichCantonRumlangCity,
    zurichCantonRumlangRumlangdorfkernCity,
    zurichCantonRuschlikonCity,
    zurichCantonRussikonCity,
    zurichCantonRutiCity,
    zurichCantonRutiDorfzentrumSudlTeilCity,
    zurichCantonRutiOberdorfCity,
    zurichCantonRutiWestlicherDorfteilCity,
    zurichCantonSamstagernCity,
    zurichCantonSchachenCity,
    zurichCantonSchlierenCity,
    zurichCantonSchlierenBodenCity,
    zurichCantonSchlierenEngstingerquartierCity,
    zurichCantonSchlierenFreiestrasseCity,
    zurichCantonSchlierenKampCity,
    zurichCantonSchlierenSpitalCity,
    zurichCantonSchlierenZentrumCity,
    zurichCantonSchwerzenbachCity,
    zurichCantonSchwerzenbachBlattenCity,
    zurichCantonSchwerzenbachChimliCity,
    zurichCantonSeenkreis3City,
    zurichCantonSeenkreis3BuelwiesenCity,
    zurichCantonSeenkreis3GanzenbuhlCity,
    zurichCantonSeenkreis3OberseenCity,
    zurichCantonSeenkreis3WaldeggCity,
    zurichCantonSeenkreis3WaserCity,
    zurichCantonSeglingenCity,
    zurichCantonSellenburenCity,
    zurichCantonSeuzachSeuzachdorfCity,
    zurichCantonSeuzachDorfCity,
    zurichCantonSeuzachDorfBreiteHypweidCity,
    zurichCantonSonnhaldeCity,
    zurichCantonStadtWinterthurkreis1City,
    zurichCantonStadtWinterthurkreis1AltstadtCity,
    zurichCantonStadtWinterthurkreis1BruhlbergCity,
    zurichCantonStadtWinterthurkreis1HeiligbergCity,
    zurichCantonStadtWinterthurkreis1LindCity,
    zurichCantonStadtWinterthurkreis1NeuwiesenCity,
    zurichCantonStadtWinterthurkreis1TossfeldCity,
    zurichCantonStafaCity,
    zurichCantonSteinmaurCity,
    zurichCantonSulzCity,
    zurichCantonTagelswangenCity,
    zurichCantonTannCity,
    zurichCantonTannTanndorfkernCity,
    zurichCantonThalwilCity,
    zurichCantonThalwilBergCity,
    zurichCantonThalwilDorfkernCity,
    zurichCantonThalwilNordCity,
    zurichCantonThalwilSeeCity,
    zurichCantonThalwilSudCity,
    zurichCantonTosskreis4City,
    zurichCantonTosskreis4EichliackerCity,
    zurichCantonTosskreis4SchlosstalCity,
    zurichCantonTosskreis4VorderHypdattnauCity,
    zurichCantonTurbenthalCity,
    zurichCantonUerikonCity,
    zurichCantonUetikonCity,
    zurichCantonUetikonGrossdorfCity,
    zurichCantonUhwiesenCity,
    zurichCantonUitikonCity,
    zurichCantonUnterengstringenCity,
    zurichCantonUrdorfCity,
    zurichCantonUrdorfBodenfeldCity,
    zurichCantonUrdorfMoosCity,
    zurichCantonUrdorfOberurdorfCity,
    zurichCantonUsterCity,
    zurichCantonUsterGschwaderCity,
    zurichCantonUsterKirchHypusterCity,
    zurichCantonUsterNiederHypusterCity,
    zurichCantonUsterNossikonCity,
    zurichCantonUsterOberHypusterCity,
    zurichCantonVeltheimkreis5City,
    zurichCantonVeltheimkreis5BlumenauCity,
    zurichCantonVeltheimkreis5RosenbergCity,
    zurichCantonVolketswilVolketswildorfCity,
    zurichCantonWadenswilCity,
    zurichCantonWadenswilBollerHypgiessenCity,
    zurichCantonWadenswilBuelenCity,
    zurichCantonWadenswilDorfwadenswilCity,
    zurichCantonWadenswilEichweidCity,
    zurichCantonWadenswilHangenmoosCity,
    zurichCantonWadenswilLeihofHypmuhlebachCity,
    zurichCantonWadenswilUntermosenHypfuhrCity,
    zurichCantonWaldCity,
    zurichCantonWallisellenCity,
    zurichCantonWallisellenRiedenCity,
    zurichCantonWallisellenWallisellenHypostCity,
    zurichCantonWallisellenWallisellenHypwestCity,
    zurichCantonWangenCity,
    zurichCantonWeiningenCity,
    zurichCantonWeisslingenCity,
    zurichCantonWettswilAusserHypdorfCity,
    zurichCantonWettswilWettswildorfCity,
    zurichCantonWetzikonCity,
    zurichCantonWetzikonKemptenCity,
    zurichCantonWetzikonOberHypwetzikonCity,
    zurichCantonWetzikonRobenhausenCity,
    zurichCantonWetzikonUnterHypwetzikonCity,
    zurichCantonWiesendangenWiesendangendorfCity,
    zurichCantonWilaCity,
    zurichCantonWinterthurCity,
    zurichCantonWolfhausenCity,
    zurichCantonWulflingenkreis6City,
    zurichCantonWulflingenkreis6HartiCity,
    zurichCantonWulflingenkreis6LindenplatzCity,
    zurichCantonWulflingenkreis6NiederfeldCity,
    zurichCantonWulflingenkreis6OberfeldCity,
    zurichCantonZollikerbergCity,
    zurichCantonZollikonCity,
    zurichCantonZumikonCity,
    zurichCantonZurichCity,
    zurichCantonZurichkreis1City,
    zurichCantonZurichkreis1CityCity,
    zurichCantonZurichkreis1LindenhofCity,
    zurichCantonZurichkreis1RathausCity,
    zurichCantonZurichkreis10City,
    zurichCantonZurichkreis10HonggCity,
    zurichCantonZurichkreis10RutihofCity,
    zurichCantonZurichkreis10WipkingenCity,
    zurichCantonZurichkreis11City,
    zurichCantonZurichkreis11AffolternCity,
    zurichCantonZurichkreis11OerlikonCity,
    zurichCantonZurichkreis11SchwandenholzCity,
    zurichCantonZurichkreis11SeebachCity,
    zurichCantonZurichkreis12City,
    zurichCantonZurichkreis12AuzelgCity,
    zurichCantonZurichkreis12HirzenbachCity,
    zurichCantonZurichkreis12SaatlenCity,
    zurichCantonZurichkreis12SchwamendingenHypmitteCity,
    zurichCantonZurichkreis2City,
    zurichCantonZurichkreis2EngeCity,
    zurichCantonZurichkreis2MittelHypleimbachCity,
    zurichCantonZurichkreis2UnterHypleimbachCity,
    zurichCantonZurichkreis2WollishofenCity,
    zurichCantonZurichkreis3City,
    zurichCantonZurichkreis3AltHypwiedikonCity,
    zurichCantonZurichkreis3FriesenbergCity,
    zurichCantonZurichkreis3SihlfeldCity,
    zurichCantonZurichkreis4AussersihlCity,
    zurichCantonZurichkreis4HardCity,
    zurichCantonZurichkreis4LangstrasseCity,
    zurichCantonZurichkreis4WerdCity,
    zurichCantonZurichkreis5City,
    zurichCantonZurichkreis5EscherHypwyssCity,
    zurichCantonZurichkreis5GewerbeschuleCity,
    zurichCantonZurichkreis6City,
    zurichCantonZurichkreis6OberstrassCity,
    zurichCantonZurichkreis6UnterstrassCity,
    zurichCantonZurichkreis7City,
    zurichCantonZurichkreis7FlunternCity,
    zurichCantonZurichkreis7HirslandenCity,
    zurichCantonZurichkreis7HottingenCity,
    zurichCantonZurichkreis7WitikonCity,
    zurichCantonZurichkreis8City,
    zurichCantonZurichkreis8MuhlebachCity,
    zurichCantonZurichkreis8SeefeldCity,
    zurichCantonZurichkreis8WeineggCity,
    zurichCantonZurichkreis9City,
    zurichCantonZurichkreis9AlbisriedenCity,
    zurichCantonZurichkreis9AltstettenCity
  ]);

/// The 26 states of `Switzerland` keyed by their id.
const Map<int, Region> switzerlandStates = <int, Region>{
    1639: switzerlandAargauCanton,
    1655: switzerlandAppenzellAusserrhodenCanton,
    1649: switzerlandAppenzellInnerrhodenCanton,
    1641: switzerlandBaselHyplandCanton,
    4957: switzerlandBaselHypstadtCanton,
    1645: switzerlandBernCanton,
    1640: switzerlandFribourgCanton,
    1647: switzerlandGenevaCanton,
    1661: switzerlandGlarusCanton,
    1660: switzerlandGraubundenCanton,
    1658: switzerlandJuraCanton,
    1663: switzerlandLucerneCanton,
    1659: switzerlandNeuchatelCanton,
    1652: switzerlandNidwaldenCanton,
    1650: switzerlandObwaldenCanton,
    1654: switzerlandSchaffhausenCanton,
    1653: switzerlandSchwyzCanton,
    1662: switzerlandSolothurnCanton,
    1644: switzerlandStGallenCanton,
    1657: switzerlandThurgauCanton,
    1643: switzerlandTicinoCanton,
    1642: switzerlandUriCanton,
    1648: switzerlandValaisCanton,
    1651: switzerlandVaudCanton,
    1646: switzerlandZugCanton,
    1656: switzerlandZurichCanton
  };
