/// Access to known geographies in Thailand and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'thailand_cities.dart';

/// The 78 regions of `🇹🇭 Thailand`
const Region thailandAmnatCharoen = Region(
    id: 3523,
    parentId: 219,
    longitude: 104.6257774,
    latitude: 15.8656783,
    name: "Amnat Charoen",
    type: null,
    stateCode: "37",
    cities: [
      thailandAmnatCharoenAmnatCharoen,
      thailandAmnatCharoenAmphoeChanuman,
      thailandAmnatCharoenAmphoeHuaTaphan,
      thailandAmnatCharoenAmphoeLueAmnat,
      thailandAmnatCharoenAmphoeMueangAmnatCharoen,
      thailandAmnatCharoenAmphoePathumRatchawongsa,
      thailandAmnatCharoenAmphoePhana,
      thailandAmnatCharoenAmphoeSenangkhanikhom
    ]);
const Region thailandAngThong = Region(
    id: 3519,
    parentId: 219,
    longitude: 100.455052,
    latitude: 14.5896054,
    name: "Ang Thong",
    type: null,
    stateCode: "15",
    cities: [
      thailandAngThongAmphoeChaiyo,
      thailandAngThongAmphoeMueangAngThong,
      thailandAngThongAmphoePaMok,
      thailandAngThongAmphoePhoThong,
      thailandAngThongAmphoeSawaengHa,
      thailandAngThongAmphoeWisetChaiChan,
      thailandAngThongAngThong,
      thailandAngThongBanThaiTan,
      thailandAngThongChaiyo,
      thailandAngThongPhoThong,
      thailandAngThongWisetChaichan
    ]);
const Region thailandBangkok = Region(
    id: 3554,
    parentId: 219,
    longitude: 100.5017651,
    latitude: 13.7563309,
    name: "Bangkok",
    type: null,
    stateCode: "10",
    cities: [
      thailandBangkokBangBon,
      thailandBangkokBangKapi,
      thailandBangkokBangKhae,
      thailandBangkokBangKhen,
      thailandBangkokBangKhoLlaen,
      thailandBangkokBangKhunTthain,
      thailandBangkokBangNa,
      thailandBangkokBangPhlat,
      thailandBangkokBangRak,
      thailandBangkokBangSue,
      thailandBangkokBangkok,
      thailandBangkokBangkokNoi,
      thailandBangkokBangkokYai,
      thailandBangkokBuengKum,
      thailandBangkokChatuChak,
      thailandBangkokChomThong,
      thailandBangkokDinDaeng,
      thailandBangkokDonMueang,
      thailandBangkokDusit,
      thailandBangkokHuaiKhwang,
      thailandBangkokKhanNaYao,
      thailandBangkokKhlongSamWa,
      thailandBangkokKhlongSan,
      thailandBangkokKhlongToei,
      thailandBangkokLakSi,
      thailandBangkokLatKrabang,
      thailandBangkokLatPhrao,
      thailandBangkokMinBuri,
      thailandBangkokNongChok,
      thailandBangkokNongKhaem,
      thailandBangkokParthumWan,
      thailandBangkokPhasiCharoen,
      thailandBangkokPhayaThai,
      thailandBangkokPhraKhanong,
      thailandBangkokPhraNakhon,
      thailandBangkokPomPrapSattruPhai,
      thailandBangkokPraWet,
      thailandBangkokRatBurana,
      thailandBangkokRatchathewi,
      thailandBangkokSaiMai,
      thailandBangkokSamphanthawong,
      thailandBangkokSaphanSung,
      thailandBangkokSathon,
      thailandBangkokSuanluang,
      thailandBangkokTalingChan,
      thailandBangkokThawiWatthana,
      thailandBangkokThonBburi,
      thailandBangkokThungKkhru,
      thailandBangkokVadhana,
      thailandBangkokWangThongLang,
      thailandBangkokYanNnaWwa
    ]);
const Region thailandBuengKan = Region(
    id: 3533,
    parentId: 219,
    longitude: 103.6464463,
    latitude: 18.3609104,
    name: "Bueng Kan",
    type: null,
    stateCode: "38",
    cities: [
      thailandBuengKanAmphoeBuengKhongLong,
      thailandBuengKanAmphoeBungKhla,
      thailandBuengKanAmphoeMueangBuengKan,
      thailandBuengKanAmphoePakKhat,
      thailandBuengKanAmphoePhonCharoen,
      thailandBuengKanAmphoeSeka,
      thailandBuengKanAmphoeSiWilai,
      thailandBuengKanAmphoeSoPhisai,
      thailandBuengKanBuengKan,
      thailandBuengKanSeka
    ]);
const Region thailandBuriRam = Region(
    id: 3534,
    parentId: 219,
    longitude: 103.1115915,
    latitude: 14.9951003,
    name: "Buri Ram",
    type: null,
    stateCode: "31",
    cities: [
      thailandBuriRamAmphoeBanDan,
      thailandBuriRamAmphoeBanKruat,
      thailandBuriRamAmphoeBanMaiChaiyaphot,
      thailandBuriRamAmphoeChaloemPhraKiat,
      thailandBuriRamAmphoeChamni,
      thailandBuriRamAmphoeHuaiRat,
      thailandBuriRamAmphoeKhaenDong,
      thailandBuriRamAmphoeKhuMueang,
      thailandBuriRamAmphoeKrasang,
      thailandBuriRamAmphoeLahanSai,
      thailandBuriRamAmphoeLamPlaiMat,
      thailandBuriRamAmphoeMueangBuriram,
      thailandBuriRamAmphoeNaPho,
      thailandBuriRamAmphoeNangRong,
      thailandBuriRamAmphoeNonDinDaeng,
      thailandBuriRamAmphoeNonSuwan,
      thailandBuriRamAmphoeNongHong,
      thailandBuriRamAmphoeNongKi,
      thailandBuriRamAmphoePaKham,
      thailandBuriRamAmphoePhlapphlaChai,
      thailandBuriRamAmphoePhutthaisong,
      thailandBuriRamAmphoePrakhonChai,
      thailandBuriRamAmphoeSatuek,
      thailandBuriRamBuriRam,
      thailandBuriRamNangRong,
      thailandBuriRamNongKi,
      thailandBuriRamPrakhonChai,
      thailandBuriRamSatuek
    ]);
const Region thailandChachoengsao = Region(
    id: 3552,
    parentId: 219,
    longitude: 101.0779596,
    latitude: 13.6904194,
    name: "Chachoengsao",
    type: null,
    stateCode: "24",
    cities: [
      thailandChachoengsaoAmphoeBanPho,
      thailandChachoengsaoAmphoeBangKhla,
      thailandChachoengsaoAmphoeBangNamPriao,
      thailandChachoengsaoAmphoeBangPakong,
      thailandChachoengsaoAmphoeKhlongKhuean,
      thailandChachoengsaoAmphoeMueangChachoengsao,
      thailandChachoengsaoAmphoePhanomSarakham,
      thailandChachoengsaoAmphoePlaengYao,
      thailandChachoengsaoAmphoeRatchasan,
      thailandChachoengsaoAmphoeSanamChaiKhet,
      thailandChachoengsaoAmphoeThaTakiap,
      thailandChachoengsaoBangKhla,
      thailandChachoengsaoBangNamPriao,
      thailandChachoengsaoBangPakong,
      thailandChachoengsaoChachoengsao,
      thailandChachoengsaoKhlongKhuean,
      thailandChachoengsaoPhanomSarakham
    ]);
const Region thailandChaiNat = Region(
    id: 3522,
    parentId: 219,
    longitude: 100.125125,
    latitude: 15.1851971,
    name: "Chai Nat",
    type: null,
    stateCode: "18",
    cities: [
      thailandChaiNatAmphoeHankha,
      thailandChaiNatAmphoeManorom,
      thailandChaiNatAmphoeMueangChainat,
      thailandChaiNatAmphoeNoenKham,
      thailandChaiNatAmphoeNongMamong,
      thailandChaiNatAmphoeSankhaburi,
      thailandChaiNatAmphoeSapphaya,
      thailandChaiNatAmphoeWatSing,
      thailandChaiNatChaiNat
    ]);
const Region thailandChaiyaphum = Region(
    id: 4954,
    parentId: 219,
    longitude: 101.6129172,
    latitude: 16.0074974,
    name: "Chaiyaphum",
    type: null,
    stateCode: "36",
    cities: [
      thailandChaiyaphumBamnetNarong,
      thailandChaiyaphumChaiyaphum,
      thailandChaiyaphumKaengKhro,
      thailandChaiyaphumKasetSombun,
      thailandChaiyaphumNakhonNayok,
      thailandChaiyaphumPhuKhiao
    ]);
const Region thailandChanthaburi = Region(
    id: 3486,
    parentId: 219,
    longitude: 102.1037806,
    latitude: 12.6112485,
    name: "Chanthaburi",
    type: null,
    stateCode: "22",
    cities: [
      thailandChanthaburiAmphoeKaengHangMaeo,
      thailandChanthaburiAmphoeKhaoKhitchakut,
      thailandChanthaburiAmphoeKhlung,
      thailandChanthaburiAmphoeLaemSing,
      thailandChanthaburiAmphoeMakham,
      thailandChanthaburiAmphoeMueangChanthaburi,
      thailandChanthaburiAmphoeNaYaiAm,
      thailandChanthaburiAmphoePongNamRon,
      thailandChanthaburiAmphoeSoiDao,
      thailandChanthaburiAmphoeThaMai,
      thailandChanthaburiChanthaburi,
      thailandChanthaburiKhlung,
      thailandChanthaburiLaemSing,
      thailandChanthaburiPongNamRon,
      thailandChanthaburiThaMai
    ]);
const Region thailandChiangMai = Region(
    id: 3491,
    parentId: 219,
    longitude: 98.9853008,
    latitude: 18.7883439,
    name: "Chiang Mai",
    type: null,
    stateCode: "50",
    cities: [
      thailandChiangMaiAmphoeChaiPrakan,
      thailandChiangMaiAmphoeChiangDao,
      thailandChiangMaiAmphoeChomThong,
      thailandChiangMaiAmphoeDoiLo,
      thailandChiangMaiAmphoeDoiSaket,
      thailandChiangMaiAmphoeDoiTao,
      thailandChiangMaiAmphoeFang,
      thailandChiangMaiAmphoeGalyaniVadhana,
      thailandChiangMaiAmphoeHangDong,
      thailandChiangMaiAmphoeHot,
      thailandChiangMaiAmphoeMaeAi,
      thailandChiangMaiAmphoeMaeChaem,
      thailandChiangMaiAmphoeMaeOn,
      thailandChiangMaiAmphoeMaeRim,
      thailandChiangMaiAmphoeMaeTaeng,
      thailandChiangMaiAmphoeMaeWang,
      thailandChiangMaiAmphoeMueangChiangMai,
      thailandChiangMaiAmphoeOmKoi,
      thailandChiangMaiAmphoePhrao,
      thailandChiangMaiAmphoeSamoeng,
      thailandChiangMaiAmphoeSanKamphaeng,
      thailandChiangMaiAmphoeSanPaTong,
      thailandChiangMaiAmphoeSanSai,
      thailandChiangMaiAmphoeSaraphi,
      thailandChiangMaiAmphoeWiangHaeng,
      thailandChiangMaiChaiPrakan,
      thailandChiangMaiChiangMai,
      thailandChiangMaiChomThong,
      thailandChiangMaiFang,
      thailandChiangMaiHangDong,
      thailandChiangMaiPai,
      thailandChiangMaiSanKamphaeng,
      thailandChiangMaiSanPaTong
    ]);
const Region thailandChiangRai = Region(
    id: 3498,
    parentId: 219,
    longitude: 99.840576,
    latitude: 19.9104798,
    name: "Chiang Rai",
    type: null,
    stateCode: "57",
    cities: [
      thailandChiangRaiAmphoeChiangKhong,
      thailandChiangRaiAmphoeChiangSaen,
      thailandChiangRaiAmphoeDoiLuang,
      thailandChiangRaiAmphoeKhunTan,
      thailandChiangRaiAmphoeMaeChan,
      thailandChiangRaiAmphoeMaeFaLuang,
      thailandChiangRaiAmphoeMaeLao,
      thailandChiangRaiAmphoeMaeSai,
      thailandChiangRaiAmphoeMaeSuai,
      thailandChiangRaiAmphoeMueangChiangRai,
      thailandChiangRaiAmphoePaDaet,
      thailandChiangRaiAmphoePhan,
      thailandChiangRaiAmphoePhayaMengrai,
      thailandChiangRaiAmphoeThoeng,
      thailandChiangRaiAmphoeWiangChai,
      thailandChiangRaiAmphoeWiangChiangRung,
      thailandChiangRaiAmphoeWiangKaen,
      thailandChiangRaiAmphoeWiangPaPao,
      thailandChiangRaiChiangKhong,
      thailandChiangRaiChiangRai,
      thailandChiangRaiChiangSaen,
      thailandChiangRaiMaeChan,
      thailandChiangRaiMaeSai,
      thailandChiangRaiPaDaet
    ]);
const Region thailandChonBuri = Region(
    id: 3513,
    parentId: 219,
    longitude: 100.9846717,
    latitude: 13.3611431,
    name: "Chon Buri",
    type: null,
    stateCode: "20",
    cities: [
      thailandChonBuriAmphoeBanBueng,
      thailandChonBuriAmphoeBoThong,
      thailandChonBuriAmphoeKoChan,
      thailandChonBuriAmphoeKoSiChang,
      thailandChonBuriAmphoeNongYai,
      thailandChonBuriAmphoePhanThong,
      thailandChonBuriAmphoePhanatNikhom,
      thailandChonBuriAmphoeSattahip,
      thailandChonBuriAmphoeSiRacha,
      thailandChonBuriBanBueng,
      thailandChonBuriBanKoLan,
      thailandChonBuriBanTalatBueng,
      thailandChonBuriBangLamung,
      thailandChonBuriBangLamungDistrict,
      thailandChonBuriChonBuri,
      thailandChonBuriKoSiChang,
      thailandChonBuriMueangChonburiDistrict,
      thailandChonBuriPattaya,
      thailandChonBuriPhanThong,
      thailandChonBuriPhanatNikhom,
      thailandChonBuriSattahip,
      thailandChonBuriSiRacha
    ]);
const Region thailandChumphon = Region(
    id: 3526,
    parentId: 219,
    longitude: 99.1800199,
    latitude: 10.4930496,
    name: "Chumphon",
    type: null,
    stateCode: "86",
    cities: [
      thailandChumphonAmphoeLamae,
      thailandChumphonAmphoeLangSuan,
      thailandChumphonAmphoeMueangChumphon,
      thailandChumphonAmphoePathio,
      thailandChumphonAmphoePhato,
      thailandChumphonAmphoeSawi,
      thailandChumphonAmphoeThaSae,
      thailandChumphonAmphoeThungTako,
      thailandChumphonBanNamYuen,
      thailandChumphonChumphon,
      thailandChumphonLangSuan
    ]);
const Region thailandKalasin = Region(
    id: 3550,
    parentId: 219,
    longitude: 103.5060994,
    latitude: 16.438508,
    name: "Kalasin",
    type: null,
    stateCode: "46",
    cities: [
      thailandKalasinAmphoeDonChan,
      thailandKalasinAmphoeHuaiMek,
      thailandKalasinAmphoeHuaiPhueng,
      thailandKalasinAmphoeKamalasai,
      thailandKalasinAmphoeKhamMuang,
      thailandKalasinAmphoeKhaoWong,
      thailandKalasinAmphoeKhongChai,
      thailandKalasinAmphoeKuchinarai,
      thailandKalasinAmphoeMueangKalasin,
      thailandKalasinAmphoeNaKhu,
      thailandKalasinAmphoeNaMon,
      thailandKalasinAmphoeNongKungSi,
      thailandKalasinAmphoeRongKham,
      thailandKalasinAmphoeSahatsakhan,
      thailandKalasinAmphoeSamChai,
      thailandKalasinAmphoeSomdet,
      thailandKalasinAmphoeThaKhantho,
      thailandKalasinAmphoeYangTalat,
      thailandKalasinHuaiMek,
      thailandKalasinKalasin,
      thailandKalasinKamalasai,
      thailandKalasinKhaoWong,
      thailandKalasinKuchinarai,
      thailandKalasinNongKungSi,
      thailandKalasinYangTalat
    ]);
const Region thailandKamphaengPhet = Region(
    id: 3516,
    parentId: 219,
    longitude: 99.5226618,
    latitude: 16.4827798,
    name: "Kamphaeng Phet",
    type: null,
    stateCode: "62",
    cities: [
      thailandKamphaengPhetAmphoeBuengSamakkhi,
      thailandKamphaengPhetAmphoeKhanuWoralaksaburi,
      thailandKamphaengPhetAmphoeKhlongKhlung,
      thailandKamphaengPhetAmphoeKhlongLan,
      thailandKamphaengPhetAmphoeKosamphiNakhon,
      thailandKamphaengPhetAmphoeLanKrabue,
      thailandKamphaengPhetAmphoeMueangKamphaengPhet,
      thailandKamphaengPhetAmphoePangSilaThong,
      thailandKamphaengPhetAmphoePhranKratai,
      thailandKamphaengPhetAmphoeSaiNgam,
      thailandKamphaengPhetAmphoeSaiThongWatthana,
      thailandKamphaengPhetKamphaengPhet,
      thailandKamphaengPhetKhanuWoralaksaburi,
      thailandKamphaengPhetLanKrabue
    ]);
const Region thailandKanchanaburi = Region(
    id: 3511,
    parentId: 219,
    longitude: 99.4179431,
    latitude: 14.1011393,
    name: "Kanchanaburi",
    type: null,
    stateCode: "71",
    cities: [
      thailandKanchanaburiAmphoeBoPhloi,
      thailandKanchanaburiAmphoeDanMakhamTia,
      thailandKanchanaburiAmphoeHuaiKrachao,
      thailandKanchanaburiAmphoeLaoKhwan,
      thailandKanchanaburiAmphoeMueangKanchanaburi,
      thailandKanchanaburiAmphoeNongPrue,
      thailandKanchanaburiAmphoePhanomThuan,
      thailandKanchanaburiAmphoeSaiYok,
      thailandKanchanaburiAmphoeSangkhlaBuri,
      thailandKanchanaburiAmphoeSiSawat,
      thailandKanchanaburiAmphoeThaMaka,
      thailandKanchanaburiAmphoeThaMuang,
      thailandKanchanaburiAmphoeThongPhaPhum,
      thailandKanchanaburiBoPhloi,
      thailandKanchanaburiKanchanaburi,
      thailandKanchanaburiPhanomThuan,
      thailandKanchanaburiSangkhlaBuri,
      thailandKanchanaburiThaMaka,
      thailandKanchanaburiThaMuang
    ]);
const Region thailandKhonKaen = Region(
    id: 3485,
    parentId: 219,
    longitude: 102.8236214,
    latitude: 16.4321938,
    name: "Khon Kaen",
    type: null,
    stateCode: "40",
    cities: [
      thailandKhonKaenAmphoeBanFang,
      thailandKhonKaenAmphoeBanHaet,
      thailandKhonKaenAmphoeBanPhai,
      thailandKhonKaenAmphoeChonnabot,
      thailandKhonKaenAmphoeChumPhae,
      thailandKhonKaenAmphoeKhaoSuanKwang,
      thailandKhonKaenAmphoeKhokPhoChai,
      thailandKhonKaenAmphoeKranuan,
      thailandKhonKaenAmphoeManchaKhiri,
      thailandKhonKaenAmphoeMueangKhonKaen,
      thailandKhonKaenAmphoeNamPhong,
      thailandKhonKaenAmphoeNonSila,
      thailandKhonKaenAmphoeNongNaKham,
      thailandKhonKaenAmphoeNongRuea,
      thailandKhonKaenAmphoeNongSongHong,
      thailandKhonKaenAmphoePhon,
      thailandKhonKaenAmphoePhraYuen,
      thailandKhonKaenAmphoePhuPhaMan,
      thailandKhonKaenAmphoePhuWiang,
      thailandKhonKaenAmphoePueaiNoi,
      thailandKhonKaenAmphoeSamSung,
      thailandKhonKaenAmphoeSiChomPhu,
      thailandKhonKaenAmphoeUbolratana,
      thailandKhonKaenAmphoeWaengNoi,
      thailandKhonKaenAmphoeWaengYai,
      thailandKhonKaenAmphoeWiangKao,
      thailandKhonKaenBanPhai,
      thailandKhonKaenChumPhae,
      thailandKhonKaenKhonKaen,
      thailandKhonKaenKranuan,
      thailandKhonKaenPhon,
      thailandKhonKaenPueaiNoi
    ]);
const Region thailandKrabi = Region(
    id: 3478,
    parentId: 219,
    longitude: 98.9062835,
    latitude: 8.0862997,
    name: "Krabi",
    type: null,
    stateCode: "81",
    cities: [
      thailandKrabiAmphoeAoLuek,
      thailandKrabiAmphoeKhaoPhanom,
      thailandKrabiAmphoeKhlongThom,
      thailandKrabiAmphoeKoLanta,
      thailandKrabiAmphoeLamThap,
      thailandKrabiAmphoeMueangKrabi,
      thailandKrabiAmphoeNueaKhlong,
      thailandKrabiAmphoePlaiPhraya,
      thailandKrabiAoLuek,
      thailandKrabiKoLanta,
      thailandKrabiKrabi,
      thailandKrabiNueaKhlong,
      thailandKrabiSaladan
    ]);
const Region thailandLampang = Region(
    id: 3544,
    parentId: 219,
    longitude: 99.5127895,
    latitude: 18.2855395,
    name: "Lampang",
    type: null,
    stateCode: "52",
    cities: [
      thailandLampangAmphoeChaeHom,
      thailandLampangAmphoeHangChat,
      thailandLampangAmphoeKoKha,
      thailandLampangAmphoeMaeMo,
      thailandLampangAmphoeMaePhrik,
      thailandLampangAmphoeMaeTha,
      thailandLampangAmphoeMueangLampang,
      thailandLampangAmphoeMueangPan,
      thailandLampangAmphoeNgao,
      thailandLampangAmphoeSoemNgam,
      thailandLampangAmphoeSopPrap,
      thailandLampangAmphoeThoen,
      thailandLampangAmphoeWangNuea,
      thailandLampangLampang,
      thailandLampangThoen,
      thailandLampangWangNuea
    ]);
const Region thailandLamphun = Region(
    id: 3483,
    parentId: 219,
    longitude: 99.0087221,
    latitude: 18.5744606,
    name: "Lamphun",
    type: null,
    stateCode: "51",
    cities: [
      thailandLamphunAmphoeBanHong,
      thailandLamphunAmphoeBanThi,
      thailandLamphunAmphoeLi,
      thailandLamphunAmphoeMaeTha,
      thailandLamphunAmphoeMueangLamphun,
      thailandLamphunAmphoePaSang,
      thailandLamphunAmphoeThungHuaChang,
      thailandLamphunAmphoeWiangNongLong,
      thailandLamphunLamphun,
      thailandLamphunMaeTha,
      thailandLamphunPaSang
    ]);
const Region thailandLoei = Region(
    id: 3509,
    parentId: 219,
    longitude: 101.7223002,
    latitude: 17.4860232,
    name: "Loei",
    type: null,
    stateCode: "42",
    cities: [
      thailandLoeiAmphoeChiangKhan,
      thailandLoeiAmphoeDanSai,
      thailandLoeiAmphoeErawan,
      thailandLoeiAmphoeMueangLoei,
      thailandLoeiAmphoeNaDuang,
      thailandLoeiAmphoeNaHaeo,
      thailandLoeiAmphoeNongHin,
      thailandLoeiAmphoePakChom,
      thailandLoeiAmphoePhaKhao,
      thailandLoeiAmphoePhuKradueng,
      thailandLoeiAmphoePhuLuang,
      thailandLoeiAmphoePhuRuea,
      thailandLoeiAmphoeThaLi,
      thailandLoeiAmphoeWangSaphung,
      thailandLoeiLoei,
      thailandLoeiPhuKradueng,
      thailandLoeiWangSaphung
    ]);
const Region thailandLopBuri = Region(
    id: 3543,
    parentId: 219,
    longitude: 100.6533706,
    latitude: 14.7995081,
    name: "Lop Buri",
    type: null,
    stateCode: "16",
    cities: [
      thailandLopBuriAmphoeBanMi,
      thailandLopBuriAmphoeChaiBadan,
      thailandLopBuriAmphoeKhokCharoen,
      thailandLopBuriAmphoeKhokSamrong,
      thailandLopBuriAmphoeLamSonthi,
      thailandLopBuriAmphoeNongMuang,
      thailandLopBuriAmphoePhatthanaNikhom,
      thailandLopBuriAmphoeSaBot,
      thailandLopBuriAmphoeThaLuang,
      thailandLopBuriAmphoeThaWung,
      thailandLopBuriChaiBadan,
      thailandLopBuriLopBuri,
      thailandLopBuriMuangLopBuriDistrict
    ]);
const Region thailandMaeHongSon = Region(
    id: 3505,
    parentId: 219,
    longitude: 97.9654368,
    latitude: 19.3020296,
    name: "Mae Hong Son",
    type: null,
    stateCode: "58",
    cities: [
      thailandMaeHongSonAmphoeKhunYuam,
      thailandMaeHongSonAmphoeMaeLaNoi,
      thailandMaeHongSonAmphoeMaeSariang,
      thailandMaeHongSonAmphoeMueangMaeHongSon,
      thailandMaeHongSonAmphoePai,
      thailandMaeHongSonAmphoePangMapha,
      thailandMaeHongSonAmphoeSopMoei,
      thailandMaeHongSonMaeHongSon
    ]);
const Region thailandMahaSarakham = Region(
    id: 3517,
    parentId: 219,
    longitude: 103.1615169,
    latitude: 16.0132015,
    name: "Maha Sarakham",
    type: null,
    stateCode: "44",
    cities: [
      thailandMahaSarakhamAmphoeBorabue,
      thailandMahaSarakhamAmphoeChiangYuen,
      thailandMahaSarakhamAmphoeChuenChom,
      thailandMahaSarakhamAmphoeKaeDam,
      thailandMahaSarakhamAmphoeKantharawichai,
      thailandMahaSarakhamAmphoeKosumPhisai,
      thailandMahaSarakhamAmphoeKutRang,
      thailandMahaSarakhamAmphoeMueangMahaSarakham,
      thailandMahaSarakhamAmphoeNaChueak,
      thailandMahaSarakhamAmphoeNaDun,
      thailandMahaSarakhamAmphoePhayakkhaphumPhisai,
      thailandMahaSarakhamAmphoeWapiPathum,
      thailandMahaSarakhamAmphoeYangSiSurat,
      thailandMahaSarakhamKosumPhisai,
      thailandMahaSarakhamMahaSarakham,
      thailandMahaSarakhamPhayakkhaphumPhisai,
      thailandMahaSarakhamWapiPathum
    ]);
const Region thailandMukdahan = Region(
    id: 3546,
    parentId: 219,
    longitude: 104.7024121,
    latitude: 16.5435914,
    name: "Mukdahan",
    type: null,
    stateCode: "49",
    cities: [
      thailandMukdahanAmphoeDonTan,
      thailandMukdahanAmphoeDongLuang,
      thailandMukdahanAmphoeKhamchaHypi,
      thailandMukdahanAmphoeMueangMukdahan,
      thailandMukdahanAmphoeNikhomKhamSoi,
      thailandMukdahanAmphoeNongSung,
      thailandMukdahanAmphoeWanYai,
      thailandMukdahanMukdahan
    ]);
const Region thailandNakhonNayok = Region(
    id: 3535,
    parentId: 219,
    longitude: 101.2130511,
    latitude: 14.2069466,
    name: "Nakhon Nayok",
    type: null,
    stateCode: "26",
    cities: [
      thailandNakhonNayokAmphoeBanNa,
      thailandNakhonNayokAmphoeMueangNakhonNayok,
      thailandNakhonNayokAmphoeOngkharak,
      thailandNakhonNayokAmphoePakPhli,
      thailandNakhonNayokNakhonNayok
    ]);
const Region thailandNakhonPathom = Region(
    id: 3503,
    parentId: 219,
    longitude: 100.0372929,
    latitude: 13.8140293,
    name: "Nakhon Pathom",
    type: null,
    stateCode: "73",
    cities: [
      thailandNakhonPathomAmphoeBangLen,
      thailandNakhonPathomAmphoeDonTum,
      thailandNakhonPathomAmphoeMueangNakhonPathom,
      thailandNakhonPathomAmphoeNakhonChaiSi,
      thailandNakhonPathomAmphoePhutthamonthon,
      thailandNakhonPathomAmphoeSamPhran,
      thailandNakhonPathomBangLen,
      thailandNakhonPathomKamphaengSaenDistrict,
      thailandNakhonPathomNakhonPathom,
      thailandNakhonPathomSamPhran
    ]);
const Region thailandNakhonPhanom = Region(
    id: 3548,
    parentId: 219,
    longitude: 104.7695508,
    latitude: 17.392039,
    name: "Nakhon Phanom",
    type: null,
    stateCode: "48",
    cities: [
      thailandNakhonPhanomAmphoeBanPhaeng,
      thailandNakhonPhanomAmphoeMueangNakhonPhanom,
      thailandNakhonPhanomAmphoeNaKae,
      thailandNakhonPhanomAmphoeNaThom,
      thailandNakhonPhanomAmphoeNaWa,
      thailandNakhonPhanomAmphoePhonSawan,
      thailandNakhonPhanomAmphoePlaPak,
      thailandNakhonPhanomAmphoeRenuNakhon,
      thailandNakhonPhanomAmphoeSiSongkhram,
      thailandNakhonPhanomAmphoeThaUthen,
      thailandNakhonPhanomAmphoeThatPhanom,
      thailandNakhonPhanomAmphoeWangyang,
      thailandNakhonPhanomNaWa,
      thailandNakhonPhanomNakhonPhanom,
      thailandNakhonPhanomThatPhanom
    ]);
const Region thailandNakhonRatchasima = Region(
    id: 3497,
    parentId: 219,
    longitude: 102.083652,
    latitude: 14.9738493,
    name: "Nakhon Ratchasima",
    type: null,
    stateCode: "30",
    cities: [
      thailandNakhonRatchasimaAmphoeBanLueam,
      thailandNakhonRatchasimaAmphoeBuaLai,
      thailandNakhonRatchasimaAmphoeBuaYai,
      thailandNakhonRatchasimaAmphoeChakkarat,
      thailandNakhonRatchasimaAmphoeChaloemPhraKiat,
      thailandNakhonRatchasimaAmphoeChokChai,
      thailandNakhonRatchasimaAmphoeChumPhuang,
      thailandNakhonRatchasimaAmphoeDanKhunThot,
      thailandNakhonRatchasimaAmphoeHuaiThalaeng,
      thailandNakhonRatchasimaAmphoeKaengSanamNang,
      thailandNakhonRatchasimaAmphoeKhamSakaeSaeng,
      thailandNakhonRatchasimaAmphoeKhamThaleSo,
      thailandNakhonRatchasimaAmphoeKhonBuri,
      thailandNakhonRatchasimaAmphoeKhong,
      thailandNakhonRatchasimaAmphoeLamThamenChai,
      thailandNakhonRatchasimaAmphoeMueangNakhonRatchasima,
      thailandNakhonRatchasimaAmphoeMueangYang,
      thailandNakhonRatchasimaAmphoeNonDaeng,
      thailandNakhonRatchasimaAmphoeNonSung,
      thailandNakhonRatchasimaAmphoeNonThai,
      thailandNakhonRatchasimaAmphoeNongBunMak,
      thailandNakhonRatchasimaAmphoePakChong,
      thailandNakhonRatchasimaAmphoePakThongChai,
      thailandNakhonRatchasimaAmphoePhimai,
      thailandNakhonRatchasimaAmphoePhraThongKham,
      thailandNakhonRatchasimaAmphoePrathai,
      thailandNakhonRatchasimaAmphoeSida,
      thailandNakhonRatchasimaAmphoeSikhio,
      thailandNakhonRatchasimaAmphoeSikhiu,
      thailandNakhonRatchasimaAmphoeSoengSang,
      thailandNakhonRatchasimaAmphoeSungNoen,
      thailandNakhonRatchasimaAmphoeThepharak,
      thailandNakhonRatchasimaAmphoeWangNamKhiao,
      thailandNakhonRatchasimaBanHuaiThalaeng,
      thailandNakhonRatchasimaBuaYai,
      thailandNakhonRatchasimaChokChai,
      thailandNakhonRatchasimaDanKhunThot,
      thailandNakhonRatchasimaKhamSakaeSaeng,
      thailandNakhonRatchasimaKhonBuri,
      thailandNakhonRatchasimaNakhonRatchasima,
      thailandNakhonRatchasimaNonSung,
      thailandNakhonRatchasimaNonThai,
      thailandNakhonRatchasimaPakChong,
      thailandNakhonRatchasimaPakThongChai,
      thailandNakhonRatchasimaPhimai,
      thailandNakhonRatchasimaSoengSang,
      thailandNakhonRatchasimaSungNoen
    ]);
const Region thailandNakhonSawan = Region(
    id: 3492,
    parentId: 219,
    longitude: 100.11996,
    latitude: 15.6987382,
    name: "Nakhon Sawan",
    type: null,
    stateCode: "60",
    cities: [
      thailandNakhonSawanAmphoeBanphotPhisai,
      thailandNakhonSawanAmphoeChumTaBong,
      thailandNakhonSawanAmphoeChumsaeng,
      thailandNakhonSawanAmphoeKaoLiao,
      thailandNakhonSawanAmphoeKrokPhra,
      thailandNakhonSawanAmphoeLatYao,
      thailandNakhonSawanAmphoeMaePoen,
      thailandNakhonSawanAmphoeMaeWong,
      thailandNakhonSawanAmphoeMueangNakhonSawan,
      thailandNakhonSawanAmphoeNongBua,
      thailandNakhonSawanAmphoePhaiSali,
      thailandNakhonSawanAmphoePhayuhaKhiri,
      thailandNakhonSawanAmphoeTakFa,
      thailandNakhonSawanAmphoeTakhli,
      thailandNakhonSawanAmphoeThaTako,
      thailandNakhonSawanKaoLiao,
      thailandNakhonSawanLatYao,
      thailandNakhonSawanNakhonSawan,
      thailandNakhonSawanNongBua,
      thailandNakhonSawanPhaiSali,
      thailandNakhonSawanPhayuhaKhiri,
      thailandNakhonSawanTakhli
    ]);
const Region thailandNakhonSiThammarat = Region(
    id: 3520,
    parentId: 219,
    longitude: 99.9599033,
    latitude: 8.4324831,
    name: "Nakhon Si Thammarat",
    type: null,
    stateCode: "80",
    cities: [
      thailandNakhonSiThammaratAmphoeBangKhan,
      thailandNakhonSiThammaratAmphoeChaHypuat,
      thailandNakhonSiThammaratAmphoeChaloemPhraKiat,
      thailandNakhonSiThammaratAmphoeChangKlang,
      thailandNakhonSiThammaratAmphoeChawang,
      thailandNakhonSiThammaratAmphoeChianYai,
      thailandNakhonSiThammaratAmphoeChulabhorn,
      thailandNakhonSiThammaratAmphoeHuaSai,
      thailandNakhonSiThammaratAmphoeKhanom,
      thailandNakhonSiThammaratAmphoeLanSaka,
      thailandNakhonSiThammaratAmphoeMueangNakhonSiThammarat,
      thailandNakhonSiThammaratAmphoeNaBon,
      thailandNakhonSiThammaratAmphoeNopphitam,
      thailandNakhonSiThammaratAmphoePakPhanang,
      thailandNakhonSiThammaratAmphoePhipun,
      thailandNakhonSiThammaratAmphoePhraPhrom,
      thailandNakhonSiThammaratAmphoePhromKhiri,
      thailandNakhonSiThammaratAmphoeRonPhibun,
      thailandNakhonSiThammaratAmphoeSichon,
      thailandNakhonSiThammaratAmphoeThaSala,
      thailandNakhonSiThammaratAmphoeThamPhannara,
      thailandNakhonSiThammaratAmphoeThungSong,
      thailandNakhonSiThammaratAmphoeThungYai,
      thailandNakhonSiThammaratChawang,
      thailandNakhonSiThammaratNakhonSiThammarat,
      thailandNakhonSiThammaratPakPhanang,
      thailandNakhonSiThammaratRonPhibun,
      thailandNakhonSiThammaratThamPhannara,
      thailandNakhonSiThammaratThungSong
    ]);
const Region thailandNan = Region(
    id: 3530,
    parentId: 219,
    longitude: -122.9863281,
    latitude: 45.522208,
    name: "Nan",
    type: null,
    stateCode: "55",
    cities: [
      thailandNanAmphoeBanLuang,
      thailandNanAmphoeBoKluea,
      thailandNanAmphoeChaloemPhraKiat,
      thailandNanAmphoeChiangKlang,
      thailandNanAmphoeMaeCharim,
      thailandNanAmphoeMueangNan,
      thailandNanAmphoeNaMuen,
      thailandNanAmphoeNaNoi,
      thailandNanAmphoePhuPhiang,
      thailandNanAmphoePua,
      thailandNanAmphoeSantiSuk,
      thailandNanAmphoeSongKhwae,
      thailandNanAmphoeThaWangPha,
      thailandNanAmphoeThungChang,
      thailandNanAmphoeWiangSa,
      thailandNanChiangKlang,
      thailandNanNan
    ]);
const Region thailandNarathiwat = Region(
    id: 3553,
    parentId: 219,
    longitude: 101.8253143,
    latitude: 6.4254607,
    name: "Narathiwat",
    type: null,
    stateCode: "96",
    cities: [
      thailandNarathiwatAmphoeBaCho,
      thailandNarathiwatAmphoeChanae,
      thailandNarathiwatAmphoeChoHypairong,
      thailandNarathiwatAmphoeMueangNarathiwat,
      thailandNarathiwatAmphoeRaHypngae,
      thailandNarathiwatAmphoeRueso,
      thailandNarathiwatAmphoeSiSakhon,
      thailandNarathiwatAmphoeSuHypngaiKolok,
      thailandNarathiwatAmphoeSuHypngaiPadi,
      thailandNarathiwatAmphoeSukhirin,
      thailandNarathiwatAmphoeTakBai,
      thailandNarathiwatAmphoeWaeng,
      thailandNarathiwatAmphoeYiHypngo,
      thailandNarathiwatBanSuHypngaiPaDi,
      thailandNarathiwatNarathiwat,
      thailandNarathiwatRaHypngae,
      thailandNarathiwatSuHypngaiKolok,
      thailandNarathiwatTakBai
    ]);
const Region thailandNongBuaLamPhu = Region(
    id: 3480,
    parentId: 219,
    longitude: 102.4260368,
    latitude: 17.2218247,
    name: "Nong Bua Lam Phu",
    type: null,
    stateCode: "39",
    cities: [
      thailandNongBuaLamPhuAmphoeMueangNongBuaLamphu,
      thailandNongBuaLamPhuAmphoeNaKlang,
      thailandNongBuaLamPhuAmphoeNaWang,
      thailandNongBuaLamPhuAmphoeNonSang,
      thailandNongBuaLamPhuAmphoeSiBunRueang,
      thailandNongBuaLamPhuAmphoeSuwannakhuha,
      thailandNongBuaLamPhuNaKlang,
      thailandNongBuaLamPhuNonSang,
      thailandNongBuaLamPhuNongBuaLamphu,
      thailandNongBuaLamPhuSiBunRueang
    ]);
const Region thailandNongKhai = Region(
    id: 3484,
    parentId: 219,
    longitude: 102.7412638,
    latitude: 17.8782803,
    name: "Nong Khai",
    type: null,
    stateCode: "43",
    cities: [
      thailandNongKhaiAmphoeFaoRai,
      thailandNongKhaiAmphoeMueangNongKhai,
      thailandNongKhaiAmphoePhoTak,
      thailandNongKhaiAmphoePhonphisai,
      thailandNongKhaiAmphoeRattanawapi,
      thailandNongKhaiAmphoeSaKhrai,
      thailandNongKhaiAmphoeSangkhom,
      thailandNongKhaiAmphoeSiChiangMai,
      thailandNongKhaiAmphoeThaBo,
      thailandNongKhaiNongKhai,
      thailandNongKhaiPhonCharoen,
      thailandNongKhaiSangkhom,
      thailandNongKhaiSiChiangMai,
      thailandNongKhaiThaBo
    ]);
const Region thailandNonthaburi = Region(
    id: 3495,
    parentId: 219,
    longitude: 100.5216508,
    latitude: 13.8591084,
    name: "Nonthaburi",
    type: null,
    stateCode: "12",
    cities: [
      thailandNonthaburiAmphoeBangBuaThong,
      thailandNonthaburiAmphoeBangKruai,
      thailandNonthaburiAmphoeBangYai,
      thailandNonthaburiAmphoeMueangNonthaburi,
      thailandNonthaburiAmphoePakKret,
      thailandNonthaburiAmphoeSaiNoi,
      thailandNonthaburiBangBuaThong,
      thailandNonthaburiBangKruai,
      thailandNonthaburiBangYai,
      thailandNonthaburiMueangNonthaburi,
      thailandNonthaburiPakKret
    ]);
const Region thailandPathumThani = Region(
    id: 3500,
    parentId: 219,
    longitude: 100.5250276,
    latitude: 14.0208391,
    name: "Pathum Thani",
    type: null,
    stateCode: "13",
    cities: [
      thailandPathumThaniAmphoeKhlongLuang,
      thailandPathumThaniAmphoeLamLukKa,
      thailandPathumThaniAmphoeLatLumKaeo,
      thailandPathumThaniAmphoeMueangPathumThani,
      thailandPathumThaniAmphoeNongSuea,
      thailandPathumThaniAmphoeThanyaburi,
      thailandPathumThaniBanLamLukKa,
      thailandPathumThaniKhlongLuang,
      thailandPathumThaniPathumThani
    ]);
const Region thailandPattani = Region(
    id: 3540,
    parentId: 219,
    longitude: 101.3232549,
    latitude: 6.7618308,
    name: "Pattani",
    type: null,
    stateCode: "94",
    cities: [
      thailandPattaniAmphoeKapho,
      thailandPattaniAmphoeKhokPho,
      thailandPattaniAmphoeMaeLan,
      thailandPattaniAmphoeMaiKaen,
      thailandPattaniAmphoeMayo,
      thailandPattaniAmphoeMueangPattani,
      thailandPattaniAmphoeNongChik,
      thailandPattaniAmphoePanare,
      thailandPattaniAmphoeSaiBuri,
      thailandPattaniAmphoeThungYangDaeng,
      thailandPattaniAmphoeYarang,
      thailandPattaniAmphoeYaring,
      thailandPattaniNongChik,
      thailandPattaniPattani,
      thailandPattaniSaiBuri,
      thailandPattaniYaring
    ]);
const Region thailandPattaya = Region(
    id: 3507,
    parentId: 219,
    longitude: 100.8824551,
    latitude: 12.9235557,
    name: "Pattaya",
    type: null,
    stateCode: "S",
    cities: []);
const Region thailandPhangnga = Region(
    id: 3549,
    parentId: 219,
    longitude: 98.5255317,
    latitude: 8.4501414,
    name: "Phangnga",
    type: null,
    stateCode: "82",
    cities: [
      thailandPhangngaAmphoeKapong,
      thailandPhangngaAmphoeKhuraBuri,
      thailandPhangngaAmphoeKoYao,
      thailandPhangngaAmphoeMueangPhangnga,
      thailandPhangngaAmphoeTakuaPa,
      thailandPhangngaAmphoeTakuaThung,
      thailandPhangngaAmphoeThaiMueang,
      thailandPhangngaAmphoeThapPut,
      thailandPhangngaBanAoNang,
      thailandPhangngaBanKhaoLak,
      thailandPhangngaBanPhruNai,
      thailandPhangngaPhangNga
    ]);
const Region thailandPhatthalung = Region(
    id: 3488,
    parentId: 219,
    longitude: 100.0740231,
    latitude: 7.6166823,
    name: "Phatthalung",
    type: null,
    stateCode: "93",
    cities: [
      thailandPhatthalungAmphoeBangKaeo,
      thailandPhatthalungAmphoeKhaoChaison,
      thailandPhatthalungAmphoeKhuanKhanun,
      thailandPhatthalungAmphoeKongRa,
      thailandPhatthalungAmphoeMueangPhatthalung,
      thailandPhatthalungAmphoePaBon,
      thailandPhatthalungAmphoePaPhayom,
      thailandPhatthalungAmphoePakPhayun,
      thailandPhatthalungAmphoeSiBanphot,
      thailandPhatthalungAmphoeSrinagarindra,
      thailandPhatthalungAmphoeTamot,
      thailandPhatthalungPhatthalung
    ]);
const Region thailandPhayao = Region(
    id: 3538,
    parentId: 219,
    longitude: 100.2023692,
    latitude: 19.2154367,
    name: "Phayao",
    type: null,
    stateCode: "56",
    cities: [
      thailandPhayaoAmphoeChiangKham,
      thailandPhayaoAmphoeChiangMuan,
      thailandPhayaoAmphoeChun,
      thailandPhayaoAmphoeDokKhamTai,
      thailandPhayaoAmphoeMaeChai,
      thailandPhayaoAmphoeMueangPhayao,
      thailandPhayaoAmphoePhuKamYao,
      thailandPhayaoAmphoePhuSang,
      thailandPhayaoAmphoePong,
      thailandPhayaoChiangKham,
      thailandPhayaoDokKhamTai,
      thailandPhayaoMaeChai,
      thailandPhayaoPhayao,
      thailandPhayaoPong
    ]);
const Region thailandPhetchabun = Region(
    id: 3515,
    parentId: 219,
    longitude: 101.1192804,
    latitude: 16.301669,
    name: "Phetchabun",
    type: null,
    stateCode: "67",
    cities: [
      thailandPhetchabunAmphoeBuengSamPhan,
      thailandPhetchabunAmphoeChonDaen,
      thailandPhetchabunAmphoeKhaoKho,
      thailandPhetchabunAmphoeLomKao,
      thailandPhetchabunAmphoeLomSak,
      thailandPhetchabunAmphoeMueangPhetchabun,
      thailandPhetchabunAmphoeNamNao,
      thailandPhetchabunAmphoeNongPhai,
      thailandPhetchabunAmphoeSiThep,
      thailandPhetchabunAmphoeWangPong,
      thailandPhetchabunAmphoeWichianBuri,
      thailandPhetchabunChonDaen,
      thailandPhetchabunLomSak,
      thailandPhetchabunNongPhai,
      thailandPhetchabunPhetchabun,
      thailandPhetchabunWichianBuri
    ]);
const Region thailandPhetchaburi = Region(
    id: 3532,
    parentId: 219,
    longitude: 99.6425883,
    latitude: 12.9649215,
    name: "Phetchaburi",
    type: null,
    stateCode: "76",
    cities: [
      thailandPhetchaburiAmphoeBanLaem,
      thailandPhetchaburiAmphoeBanLat,
      thailandPhetchaburiAmphoeChaHypam,
      thailandPhetchaburiAmphoeKaengKrachan,
      thailandPhetchaburiAmphoeKhaoYoi,
      thailandPhetchaburiAmphoeMueangPhetchaburi,
      thailandPhetchaburiAmphoeNongYaPlong,
      thailandPhetchaburiAmphoeThaYang,
      thailandPhetchaburiChaHypam,
      thailandPhetchaburiKhaoYoi,
      thailandPhetchaburiPhetchaburi,
      thailandPhetchaburiThaYang
    ]);
const Region thailandPhichit = Region(
    id: 3514,
    parentId: 219,
    longitude: 100.3346991,
    latitude: 16.2740876,
    name: "Phichit",
    type: null,
    stateCode: "66",
    cities: [
      thailandPhichitAmphoeBangMunNak,
      thailandPhichitAmphoeBuengNaRang,
      thailandPhichitAmphoeDongCharoen,
      thailandPhichitAmphoeMueangPhichit,
      thailandPhichitAmphoePhoPrathapChang,
      thailandPhichitAmphoePhoThale,
      thailandPhichitAmphoeSakLek,
      thailandPhichitAmphoeTaphanHin,
      thailandPhichitAmphoeThapKhlo,
      thailandPhichitAmphoeWachiraBarami,
      thailandPhichitAmphoeWangSaiPhun,
      thailandPhichitBangMunNak,
      thailandPhichitBuengNaRang,
      thailandPhichitPhichit,
      thailandPhichitTaphanHin,
      thailandPhichitThapKhlo,
      thailandPhichitWangSaiPhun
    ]);
const Region thailandPhitsanulok = Region(
    id: 3506,
    parentId: 219,
    longitude: 100.2658516,
    latitude: 16.8211238,
    name: "Phitsanulok",
    type: null,
    stateCode: "65",
    cities: [
      thailandPhitsanulokAmphoeBangKrathum,
      thailandPhitsanulokAmphoeBangRakam,
      thailandPhitsanulokAmphoeChatTrakan,
      thailandPhitsanulokAmphoeMueangPhitsanulok,
      thailandPhitsanulokAmphoeNakhonThai,
      thailandPhitsanulokAmphoeNoenMaprang,
      thailandPhitsanulokAmphoePhromPhiram,
      thailandPhitsanulokAmphoeWangThong,
      thailandPhitsanulokAmphoeWatBot,
      thailandPhitsanulokBangKrathum,
      thailandPhitsanulokBangRakam,
      thailandPhitsanulokChatTrakan,
      thailandPhitsanulokNakhonThai,
      thailandPhitsanulokPhitsanulok
    ]);
const Region thailandPhraNakhonSiAyutthaya = Region(
    id: 3494,
    parentId: 219,
    longitude: 100.5876634,
    latitude: 14.3692325,
    name: "Phra Nakhon Si Ayutthaya",
    type: null,
    stateCode: "14",
    cities: [
      thailandPhraNakhonSiAyutthayaAmphoeBanPhraek,
      thailandPhraNakhonSiAyutthayaAmphoeBangBan,
      thailandPhraNakhonSiAyutthayaAmphoeBangPaHypin,
      thailandPhraNakhonSiAyutthayaAmphoeBangPahan,
      thailandPhraNakhonSiAyutthayaAmphoeBangSai,
      thailandPhraNakhonSiAyutthayaAmphoeLatBuaLuang,
      thailandPhraNakhonSiAyutthayaAmphoeMahaRat,
      thailandPhraNakhonSiAyutthayaAmphoeNakhonLuang,
      thailandPhraNakhonSiAyutthayaAmphoePhachi,
      thailandPhraNakhonSiAyutthayaAmphoePhakHai,
      thailandPhraNakhonSiAyutthayaAmphoePhraNakhonSiAyutthaya,
      thailandPhraNakhonSiAyutthayaAmphoeSena,
      thailandPhraNakhonSiAyutthayaAmphoeThaRuea,
      thailandPhraNakhonSiAyutthayaAmphoeUthai,
      thailandPhraNakhonSiAyutthayaAmphoeWangNoi,
      thailandPhraNakhonSiAyutthayaBanBangKadiPathumThani,
      thailandPhraNakhonSiAyutthayaBangBan,
      thailandPhraNakhonSiAyutthayaBangPaHypin,
      thailandPhraNakhonSiAyutthayaNakhonLuang,
      thailandPhraNakhonSiAyutthayaPhakHai,
      thailandPhraNakhonSiAyutthayaPhraNakhonSiAyutthaya,
      thailandPhraNakhonSiAyutthayaThaRuea,
      thailandPhraNakhonSiAyutthayaWangNoi
    ]);
const Region thailandPhrae = Region(
    id: 3528,
    parentId: 219,
    longitude: 100.1402831,
    latitude: 18.1445774,
    name: "Phrae",
    type: null,
    stateCode: "54",
    cities: [
      thailandPhraeAmphoeDenChai,
      thailandPhraeAmphoeLong,
      thailandPhraeAmphoeMueangPhrae,
      thailandPhraeAmphoeNongMuangKhai,
      thailandPhraeAmphoeRongKwang,
      thailandPhraeAmphoeSong,
      thailandPhraeAmphoeSungMen,
      thailandPhraeAmphoeWangChin,
      thailandPhraeDenChai,
      thailandPhraeLong,
      thailandPhraePhrae,
      thailandPhraeRongKwang
    ]);
const Region thailandPhuket = Region(
    id: 3536,
    parentId: 219,
    longitude: 98.3922504,
    latitude: 7.8804479,
    name: "Phuket",
    type: null,
    stateCode: "83",
    cities: [
      thailandPhuketAmphoeKathu,
      thailandPhuketAmphoeMueangPhuket,
      thailandPhuketAmphoeThalang,
      thailandPhuketBanChalong,
      thailandPhuketBanKaron,
      thailandPhuketBanKata,
      thailandPhuketBanKoKaeo,
      thailandPhuketBanMaiKhao,
      thailandPhuketBanRatsada,
      thailandPhuketBanTalatNua,
      thailandPhuketBanTalatYai,
      thailandPhuketKathu,
      thailandPhuketNaiHarn,
      thailandPhuketPatong,
      thailandPhuketPhuket,
      thailandPhuketRawai,
      thailandPhuketWichit
    ]);
const Region thailandPrachinBuri = Region(
    id: 3542,
    parentId: 219,
    longitude: 101.6600874,
    latitude: 14.0420699,
    name: "Prachin Buri",
    type: null,
    stateCode: "25",
    cities: [
      thailandPrachinBuriAmphoeBanSang,
      thailandPrachinBuriAmphoeKabinBuri,
      thailandPrachinBuriAmphoeMueangPrachinBuri,
      thailandPrachinBuriAmphoeNaDi,
      thailandPrachinBuriAmphoePrachantakham,
      thailandPrachinBuriAmphoeSiMahaPhot,
      thailandPrachinBuriAmphoeSiMahosot,
      thailandPrachinBuriKabinBuri,
      thailandPrachinBuriPrachinBuri
    ]);
const Region thailandPrachuapKhiriKhan = Region(
    id: 3508,
    parentId: 219,
    longitude: 99.7957564,
    latitude: 11.7938389,
    name: "Prachuap Khiri Khan",
    type: null,
    stateCode: "77",
    cities: [
      thailandPrachuapKhiriKhanAmphoeBangSaphan,
      thailandPrachuapKhiriKhanAmphoeBangSaphanNoi,
      thailandPrachuapKhiriKhanAmphoeHuaHin,
      thailandPrachuapKhiriKhanAmphoeKuiBuri,
      thailandPrachuapKhiriKhanAmphoeMueangPrachuapKhiriKhan,
      thailandPrachuapKhiriKhanAmphoePranBuri,
      thailandPrachuapKhiriKhanAmphoeSamRoiYot,
      thailandPrachuapKhiriKhanAmphoeThapSakae,
      thailandPrachuapKhiriKhanBangSaphan,
      thailandPrachuapKhiriKhanHuaHin,
      thailandPrachuapKhiriKhanKuiBuri,
      thailandPrachuapKhiriKhanPrachuapKhiriKhan,
      thailandPrachuapKhiriKhanPranBuri,
      thailandPrachuapKhiriKhanSamRoiYot
    ]);
const Region thailandRanong = Region(
    id: 3479,
    parentId: 219,
    longitude: 98.6084641,
    latitude: 9.9528702,
    name: "Ranong",
    type: null,
    stateCode: "85",
    cities: [
      thailandRanongAmphoeKapoe,
      thailandRanongAmphoeKraBuri,
      thailandRanongAmphoeLaHypun,
      thailandRanongAmphoeMueangRanong,
      thailandRanongAmphoeSukSamran,
      thailandRanongRanong
    ]);
const Region thailandRatchaburi = Region(
    id: 3499,
    parentId: 219,
    longitude: 99.8134211,
    latitude: 13.5282893,
    name: "Ratchaburi",
    type: null,
    stateCode: "70",
    cities: [
      thailandRatchaburiAmphoeBanKha,
      thailandRatchaburiAmphoeBanPong,
      thailandRatchaburiAmphoeBangPhae,
      thailandRatchaburiAmphoeChomBueng,
      thailandRatchaburiAmphoeDamnoenSaduak,
      thailandRatchaburiAmphoeMueangRatchaburi,
      thailandRatchaburiAmphoePakTho,
      thailandRatchaburiAmphoePhotharam,
      thailandRatchaburiAmphoeSuanPhueng,
      thailandRatchaburiAmphoeWatPhleng,
      thailandRatchaburiBanPong,
      thailandRatchaburiBangPhae,
      thailandRatchaburiChomBueng,
      thailandRatchaburiDamnoenSaduak,
      thailandRatchaburiPhotharam,
      thailandRatchaburiRatchaburi
    ]);
const Region thailandRayong = Region(
    id: 3518,
    parentId: 219,
    longitude: 101.2816261,
    latitude: 12.6813957,
    name: "Rayong",
    type: null,
    stateCode: "21",
    cities: [
      thailandRayongAmphoeBanChang,
      thailandRayongAmphoeBanKhai,
      thailandRayongAmphoeKhaoChamao,
      thailandRayongAmphoeKlaeng,
      thailandRayongAmphoeMueangRayong,
      thailandRayongAmphoeNikhomPhattana,
      thailandRayongAmphoePluakDaeng,
      thailandRayongAmphoeWangChan,
      thailandRayongBanChang,
      thailandRayongBanPhe,
      thailandRayongKlaeng,
      thailandRayongRayong
    ]);
const Region thailandRoiEt = Region(
    id: 3510,
    parentId: 219,
    longitude: 103.6520036,
    latitude: 16.0538196,
    name: "Roi Et",
    type: null,
    stateCode: "45",
    cities: [
      thailandRoiEtAmphoeAtSamat,
      thailandRoiEtAmphoeChanghan,
      thailandRoiEtAmphoeChaturaphakPhiman,
      thailandRoiEtAmphoeChiangKhwan,
      thailandRoiEtAmphoeKasetWisai,
      thailandRoiEtAmphoeMoeiwadi,
      thailandRoiEtAmphoeMueangRoiEt,
      thailandRoiEtAmphoeMueangSuang,
      thailandRoiEtAmphoeNongHi,
      thailandRoiEtAmphoeNongPhok,
      thailandRoiEtAmphoePathumRat,
      thailandRoiEtAmphoePhanomPhrai,
      thailandRoiEtAmphoePhoChai,
      thailandRoiEtAmphoePhonSai,
      thailandRoiEtAmphoePhonThong,
      thailandRoiEtAmphoeSelaphum,
      thailandRoiEtAmphoeSiSomdet,
      thailandRoiEtAmphoeSuwannaphum,
      thailandRoiEtAmphoeThawatchaburi,
      thailandRoiEtAmphoeThungKhaoLuang,
      thailandRoiEtBanSelaphum,
      thailandRoiEtKasetWisai,
      thailandRoiEtMoeiwadi,
      thailandRoiEtPhoChai,
      thailandRoiEtRoiEt,
      thailandRoiEtSuwannaphum,
      thailandRoiEtWaeng
    ]);
const Region thailandSaKaeo = Region(
    id: 3529,
    parentId: 219,
    longitude: 102.0645839,
    latitude: 13.824038,
    name: "Sa Kaeo",
    type: null,
    stateCode: "27",
    cities: [
      thailandSaKaeoAmphoeAranyaprathet,
      thailandSaKaeoAmphoeKhaoChakan,
      thailandSaKaeoAmphoeKhlongHat,
      thailandSaKaeoAmphoeKhokSung,
      thailandSaKaeoAmphoeMueangSaKaeo,
      thailandSaKaeoAmphoeTaPhraya,
      thailandSaKaeoAmphoeWangNamYen,
      thailandSaKaeoAmphoeWangSombun,
      thailandSaKaeoAmphoeWatthanaNakhon,
      thailandSaKaeoAranyaprathet,
      thailandSaKaeoSaKaeo,
      thailandSaKaeoWangNamYen
    ]);
const Region thailandSakonNakhon = Region(
    id: 3501,
    parentId: 219,
    longitude: 104.1486055,
    latitude: 17.1664211,
    name: "Sakon Nakhon",
    type: null,
    stateCode: "47",
    cities: [
      thailandSakonNakhonAmphoeAkatAmnuai,
      thailandSakonNakhonAmphoeBanMuang,
      thailandSakonNakhonAmphoeCharoenSin,
      thailandSakonNakhonAmphoeKhamTaKla,
      thailandSakonNakhonAmphoeKhokSiSuphan,
      thailandSakonNakhonAmphoeKusuman,
      thailandSakonNakhonAmphoeKutBak,
      thailandSakonNakhonAmphoeMueangSakonNakhon,
      thailandSakonNakhonAmphoeNikhomNamUn,
      thailandSakonNakhonAmphoePhangKhon,
      thailandSakonNakhonAmphoePhannaNikhom,
      thailandSakonNakhonAmphoePhonNaKaeo,
      thailandSakonNakhonAmphoePhuPhan,
      thailandSakonNakhonAmphoeSawangDaenDin,
      thailandSakonNakhonAmphoeSongDao,
      thailandSakonNakhonAmphoeTaoNgoi,
      thailandSakonNakhonAmphoeWanonNiwat,
      thailandSakonNakhonAmphoeWaritchaphum,
      thailandSakonNakhonSakonNakhon,
      thailandSakonNakhonSawangDaenDin
    ]);
const Region thailandSamutPrakan = Region(
    id: 3481,
    parentId: 219,
    longitude: 100.5998319,
    latitude: 13.5990961,
    name: "Samut Prakan",
    type: null,
    stateCode: "11",
    cities: [
      thailandSamutPrakanAmphoeBangBo,
      thailandSamutPrakanAmphoeBangPhli,
      thailandSamutPrakanAmphoeBangSaoThong,
      thailandSamutPrakanAmphoeMueangSamutPrakan,
      thailandSamutPrakanAmphoePhraPradaeng,
      thailandSamutPrakanAmphoePhraSamutChedi,
      thailandSamutPrakanBanKhlongBangSaoThong,
      thailandSamutPrakanBangBoDistrict,
      thailandSamutPrakanPhraPradaeng,
      thailandSamutPrakanSamutPrakan
    ]);
const Region thailandSamutSakhon = Region(
    id: 3504,
    parentId: 219,
    longitude: 100.2743956,
    latitude: 13.5475216,
    name: "Samut Sakhon",
    type: null,
    stateCode: "74",
    cities: [
      thailandSamutSakhonAmphoeBanPhaeo,
      thailandSamutSakhonAmphoeKrathumBaen,
      thailandSamutSakhonAmphoeMueangSamutSakhon,
      thailandSamutSakhonBanPhaeo,
      thailandSamutSakhonKrathumBaen,
      thailandSamutSakhonSamutSakhon
    ]);
const Region thailandSamutSongkhram = Region(
    id: 3502,
    parentId: 219,
    longitude: 100.0022645,
    latitude: 13.4098217,
    name: "Samut Songkhram",
    type: null,
    stateCode: "75",
    cities: [
      thailandSamutSongkhramAmphoeAmphawa,
      thailandSamutSongkhramAmphoeBangKhonthi,
      thailandSamutSongkhramAmphoeMueangSamutSongkhram,
      thailandSamutSongkhramSamutSongkhram
    ]);
const Region thailandSaraburi = Region(
    id: 3487,
    parentId: 219,
    longitude: 100.9101421,
    latitude: 14.5289154,
    name: "Saraburi",
    type: null,
    stateCode: "19",
    cities: [
      thailandSaraburiAmphoeBanMo,
      thailandSaraburiAmphoeChaloemPhraKiat,
      thailandSaraburiAmphoeDonPhut,
      thailandSaraburiAmphoeKaengKhoi,
      thailandSaraburiAmphoeMuakLek,
      thailandSaraburiAmphoeMueangSaraBuri,
      thailandSaraburiAmphoeNongDon,
      thailandSaraburiAmphoeNongKhae,
      thailandSaraburiAmphoeNongSaeng,
      thailandSaraburiAmphoePhraPhutthabat,
      thailandSaraburiAmphoeSaoHai,
      thailandSaraburiAmphoeWangMuang,
      thailandSaraburiAmphoeWihanDaeng,
      thailandSaraburiBanMo,
      thailandSaraburiKaengKhoi,
      thailandSaraburiNongKhae,
      thailandSaraburiPhraPhutthabat,
      thailandSaraburiSaraburi
    ]);
const Region thailandSatun = Region(
    id: 3537,
    parentId: 219,
    longitude: 100.0673744,
    latitude: 6.6238158,
    name: "Satun",
    type: null,
    stateCode: "91",
    cities: [
      thailandSatunAmphoeKhuanDon,
      thailandSatunAmphoeKhuanKalong,
      thailandSatunAmphoeLaHypNgu,
      thailandSatunAmphoeManang,
      thailandSatunAmphoeMueangSatun,
      thailandSatunAmphoeThaPhae,
      thailandSatunAmphoeThungWa,
      thailandSatunSatun
    ]);
const Region thailandSiSaKet = Region(
    id: 3547,
    parentId: 219,
    longitude: 104.3220095,
    latitude: 15.1186009,
    name: "Si Sa Ket",
    type: null,
    stateCode: "33",
    cities: [
      thailandSiSaKetAmphoeBenchalak,
      thailandSiSaKetAmphoeBuengBun,
      thailandSiSaKetAmphoeHuaiThapThan,
      thailandSiSaKetAmphoeKantharalak,
      thailandSiSaKetAmphoeKanthararom,
      thailandSiSaKetAmphoeKhukhan,
      thailandSiSaKetAmphoeKhunHan,
      thailandSiSaKetAmphoeMueangChan,
      thailandSiSaKetAmphoeMueangSisaket,
      thailandSiSaKetAmphoeNamKliang,
      thailandSiSaKetAmphoeNonKhun,
      thailandSiSaKetAmphoePhayu,
      thailandSiSaKetAmphoePhoSiSuwan,
      thailandSiSaKetAmphoePhraiBueng,
      thailandSiSaKetAmphoePhuSing,
      thailandSiSaKetAmphoePrangKu,
      thailandSiSaKetAmphoeRasiSalai,
      thailandSiSaKetAmphoeSiRattana,
      thailandSiSaKetAmphoeSilaLat,
      thailandSiSaKetAmphoeUthumphonPhisai,
      thailandSiSaKetAmphoeWangHin,
      thailandSiSaKetAmphoeYangChumNoi,
      thailandSiSaKetKantharalak,
      thailandSiSaKetPhraiBueng,
      thailandSiSaKetSiSaKet
    ]);
const Region thailandSingBuri = Region(
    id: 3490,
    parentId: 219,
    longitude: 100.3967314,
    latitude: 14.8936253,
    name: "Sing Buri",
    type: null,
    stateCode: "17",
    cities: [
      thailandSingBuriAmphoeBangRachan,
      thailandSingBuriAmphoeInBuri,
      thailandSingBuriAmphoeKhaiBangRachan,
      thailandSingBuriAmphoeMueangSingBuri,
      thailandSingBuriAmphoePhromBuri,
      thailandSingBuriAmphoeThaChang,
      thailandSingBuriBangRacham,
      thailandSingBuriInBuri,
      thailandSingBuriSingBuri
    ]);
const Region thailandSongkhla = Region(
    id: 3539,
    parentId: 219,
    longitude: 100.5953813,
    latitude: 7.1897659,
    name: "Songkhla",
    type: null,
    stateCode: "90",
    cities: [
      thailandSongkhlaAmphoeBangKlam,
      thailandSongkhlaAmphoeChana,
      thailandSongkhlaAmphoeHatYai,
      thailandSongkhlaAmphoeKhlongHoiKhong,
      thailandSongkhlaAmphoeKhuanNiang,
      thailandSongkhlaAmphoeKrasaeSin,
      thailandSongkhlaAmphoeMueangSongkhla,
      thailandSongkhlaAmphoeNaMom,
      thailandSongkhlaAmphoeNaThawi,
      thailandSongkhlaAmphoeRanot,
      thailandSongkhlaAmphoeRattaphum,
      thailandSongkhlaAmphoeSabaYoi,
      thailandSongkhlaAmphoeSadao,
      thailandSongkhlaAmphoeSathingPhra,
      thailandSongkhlaAmphoeSinghanakhon,
      thailandSongkhlaAmphoeThepha,
      thailandSongkhlaBanMai,
      thailandSongkhlaHatYai,
      thailandSongkhlaNaMom,
      thailandSongkhlaRanot,
      thailandSongkhlaSadao,
      thailandSongkhlaSongkhla
    ]);
const Region thailandSukhothai = Region(
    id: 3545,
    parentId: 219,
    longitude: -79.3746639,
    latitude: 43.6485556,
    name: "Sukhothai",
    type: null,
    stateCode: "64",
    cities: [
      thailandSukhothaiAmphoeBanDanLanHoi,
      thailandSukhothaiAmphoeKhiriMat,
      thailandSukhothaiAmphoeKongKrailat,
      thailandSukhothaiAmphoeMueangSukhothai,
      thailandSukhothaiAmphoeSawankhalok,
      thailandSukhothaiAmphoeSiNakhon,
      thailandSukhothaiAmphoeSiSamrong,
      thailandSukhothaiAmphoeSiSatchanalai,
      thailandSukhothaiAmphoeThungSaliam,
      thailandSukhothaiBanDanLanHoi,
      thailandSukhothaiBanNa,
      thailandSukhothaiKhiriMat,
      thailandSukhothaiSawankhalok,
      thailandSukhothaiSiSatchanalai,
      thailandSukhothaiSukhothai
    ]);
const Region thailandSuphanBuri = Region(
    id: 3524,
    parentId: 219,
    longitude: 100.1177128,
    latitude: 14.4744892,
    name: "Suphan Buri",
    type: null,
    stateCode: "72",
    cities: [
      thailandSuphanBuriAmphoeBangPlaMa,
      thailandSuphanBuriAmphoeDanChang,
      thailandSuphanBuriAmphoeDoembangNangbuat,
      thailandSuphanBuriAmphoeDonChedi,
      thailandSuphanBuriAmphoeMueangSuphanBuri,
      thailandSuphanBuriAmphoeNongYasai,
      thailandSuphanBuriAmphoeSiPrachan,
      thailandSuphanBuriAmphoeSongPhiNong,
      thailandSuphanBuriAmphoeUThong,
      thailandSuphanBuriBanSamChuk,
      thailandSuphanBuriDoembangNangbuat,
      thailandSuphanBuriSuphanBuri
    ]);
const Region thailandSuratThani = Region(
    id: 3482,
    parentId: 219,
    longitude: 99.3334198,
    latitude: 9.1341949,
    name: "Surat Thani",
    type: null,
    stateCode: "84",
    cities: [
      thailandSuratThaniAmphoeBanNaDoem,
      thailandSuratThaniAmphoeBanNaSan,
      thailandSuratThaniAmphoeBanTakhun,
      thailandSuratThaniAmphoeChaiBuri,
      thailandSuratThaniAmphoeChaiya,
      thailandSuratThaniAmphoeDonSak,
      thailandSuratThaniAmphoeKanchanadit,
      thailandSuratThaniAmphoeKhianSa,
      thailandSuratThaniAmphoeKhiriRatNikhom,
      thailandSuratThaniAmphoeKoPhaHypngan,
      thailandSuratThaniAmphoeKoSamui,
      thailandSuratThaniAmphoeMueangSuratThani,
      thailandSuratThaniAmphoePhanom,
      thailandSuratThaniAmphoePhrasaeng,
      thailandSuratThaniAmphoePhunphin,
      thailandSuratThaniAmphoeThaChana,
      thailandSuratThaniAmphoeThaChang,
      thailandSuratThaniAmphoeWiangSa,
      thailandSuratThaniAmphoeWiphawadi,
      thailandSuratThaniBanNaSan,
      thailandSuratThaniChaiBuri,
      thailandSuratThaniChaiya,
      thailandSuratThaniDonSak,
      thailandSuratThaniKanchanadit,
      thailandSuratThaniKoPhaNgan,
      thailandSuratThaniKoSamui,
      thailandSuratThaniKohTao,
      thailandSuratThaniSuratThani,
      thailandSuratThaniThaKham,
      thailandSuratThaniThaKhanon,
      thailandSuratThaniWiangSa
    ]);
const Region thailandSurin = Region(
    id: 3531,
    parentId: 219,
    longitude: -95.6276367,
    latitude: 37.0358271,
    name: "Surin",
    type: null,
    stateCode: "32",
    cities: [
      thailandSurinAmphoeBuaChet,
      thailandSurinAmphoeChomPhra,
      thailandSurinAmphoeChumphonBuri,
      thailandSurinAmphoeKapChoeng,
      thailandSurinAmphoeKhwaoSinarin,
      thailandSurinAmphoeLamduan,
      thailandSurinAmphoeMueangSurin,
      thailandSurinAmphoeNonNarai,
      thailandSurinAmphoePhanomDongRak,
      thailandSurinAmphoePrasat,
      thailandSurinAmphoeRattanaburi,
      thailandSurinAmphoeSamrongThap,
      thailandSurinAmphoeSangkha,
      thailandSurinAmphoeSanom,
      thailandSurinAmphoeSiKhoraphum,
      thailandSurinAmphoeSiNarong,
      thailandSurinAmphoeThaTum,
      thailandSurinSurin
    ]);
const Region thailandTak = Region(
    id: 3525,
    parentId: 219,
    longitude: -93.1049815,
    latitude: 45.0299646,
    name: "Tak",
    type: null,
    stateCode: "63",
    cities: [
      thailandTakAmphoeBanTak,
      thailandTakAmphoeMaeRamat,
      thailandTakAmphoeMaeSot,
      thailandTakAmphoeMueangTak,
      thailandTakAmphoePhopPhra,
      thailandTakAmphoeThaSongYang,
      thailandTakAmphoeUmphang,
      thailandTakAmphoeWangChao,
      thailandTakBanTak,
      thailandTakMaeRamat,
      thailandTakMaeSot,
      thailandTakTak
    ]);
const Region thailandTrang = Region(
    id: 3541,
    parentId: 219,
    longitude: 99.6239334,
    latitude: 7.5644833,
    name: "Trang",
    type: null,
    stateCode: "92",
    cities: [
      thailandTrangAmphoeHatSamran,
      thailandTrangAmphoeHuaiYot,
      thailandTrangAmphoeKantang,
      thailandTrangAmphoeMueangTrang,
      thailandTrangAmphoeNaYong,
      thailandTrangAmphoePalian,
      thailandTrangAmphoeRatsada,
      thailandTrangAmphoeSikao,
      thailandTrangAmphoeWangWiset,
      thailandTrangAmphoeYanTaKhao,
      thailandTrangHuaiYot,
      thailandTrangKantang,
      thailandTrangTrang
    ]);
const Region thailandTrat = Region(
    id: 3496,
    parentId: 219,
    longitude: 102.5174734,
    latitude: 12.2427563,
    name: "Trat",
    type: null,
    stateCode: "23",
    cities: [
      thailandTratAmphoeBoRai,
      thailandTratAmphoeKhaoSaming,
      thailandTratAmphoeKhlongYai,
      thailandTratAmphoeKoChang,
      thailandTratAmphoeKoKut,
      thailandTratAmphoeLaemNgop,
      thailandTratAmphoeMueangTrat,
      thailandTratBoRai,
      thailandTratKhlongYai,
      thailandTratKoChangTai,
      thailandTratTrat
    ]);
const Region thailandUbonRatchathani = Region(
    id: 3512,
    parentId: 219,
    longitude: 104.8472995,
    latitude: 15.2448453,
    name: "Ubon Ratchathani",
    type: null,
    stateCode: "34",
    cities: [
      thailandUbonRatchathaniAmphoeBuntharik,
      thailandUbonRatchathaniAmphoeDetUdom,
      thailandUbonRatchathaniAmphoeDonMotDaeng,
      thailandUbonRatchathaniAmphoeKhemmarat,
      thailandUbonRatchathaniAmphoeKhongChiam,
      thailandUbonRatchathaniAmphoeKhueangNai,
      thailandUbonRatchathaniAmphoeKutKhaopun,
      thailandUbonRatchathaniAmphoeLaoSueaKok,
      thailandUbonRatchathaniAmphoeMuangSamSip,
      thailandUbonRatchathaniAmphoeMueangUbonRatchathani,
      thailandUbonRatchathaniAmphoeNaChaluai,
      thailandUbonRatchathaniAmphoeNaTan,
      thailandUbonRatchathaniAmphoeNaYia,
      thailandUbonRatchathaniAmphoeNamKhun,
      thailandUbonRatchathaniAmphoeNamYuen,
      thailandUbonRatchathaniAmphoePhibunMangsahan,
      thailandUbonRatchathaniAmphoePhoSai,
      thailandUbonRatchathaniAmphoeSamrong,
      thailandUbonRatchathaniAmphoeSawangWirawong,
      thailandUbonRatchathaniAmphoeSiMueangMai,
      thailandUbonRatchathaniAmphoeSirindhorn,
      thailandUbonRatchathaniAmphoeTanSum,
      thailandUbonRatchathaniAmphoeThungSiUdom,
      thailandUbonRatchathaniAmphoeTrakanPhuetPhon,
      thailandUbonRatchathaniAmphoeWarinChamrap,
      thailandUbonRatchathaniDetUdom,
      thailandUbonRatchathaniPhibunMangsahan,
      thailandUbonRatchathaniSawangWirawong,
      thailandUbonRatchathaniUbonRatchathani,
      thailandUbonRatchathaniWarinChamrap
    ]);
const Region thailandUdonThani = Region(
    id: 3527,
    parentId: 219,
    longitude: 102.8158924,
    latitude: 17.3646969,
    name: "Udon Thani",
    type: null,
    stateCode: "41",
    cities: [
      thailandUdonThaniAmphoeBanDung,
      thailandUdonThaniAmphoeBanPhue,
      thailandUdonThaniAmphoeChaiWan,
      thailandUdonThaniAmphoeKuKaeo,
      thailandUdonThaniAmphoeKumphawapi,
      thailandUdonThaniAmphoeKutChap,
      thailandUdonThaniAmphoeMueangUdonThani,
      thailandUdonThaniAmphoeNaYung,
      thailandUdonThaniAmphoeNamSom,
      thailandUdonThaniAmphoeNonSaHypat,
      thailandUdonThaniAmphoeNongHan,
      thailandUdonThaniAmphoeNongSaeng,
      thailandUdonThaniAmphoeNongWuaSo,
      thailandUdonThaniAmphoePhen,
      thailandUdonThaniAmphoePhibunRak,
      thailandUdonThaniAmphoePrachakSinlapakhom,
      thailandUdonThaniAmphoeSangKhom,
      thailandUdonThaniAmphoeSiThat,
      thailandUdonThaniAmphoeThungFon,
      thailandUdonThaniAmphoeWangSamMo,
      thailandUdonThaniBanDung,
      thailandUdonThaniBanNongWuaSo,
      thailandUdonThaniBanPhanDon,
      thailandUdonThaniKumphawapi,
      thailandUdonThaniKutChap,
      thailandUdonThaniNamSom,
      thailandUdonThaniNongWuaSo,
      thailandUdonThaniUdonThani
    ]);
const Region thailandUthaiThani = Region(
    id: 3551,
    parentId: 219,
    longitude: 100.0245527,
    latitude: 15.3835001,
    name: "Uthai Thani",
    type: null,
    stateCode: "61",
    cities: [
      thailandUthaiThaniAmphoeBanRai,
      thailandUthaiThaniAmphoeHuaiKhot,
      thailandUthaiThaniAmphoeLanSak,
      thailandUthaiThaniAmphoeMueangUthaiThani,
      thailandUthaiThaniAmphoeNongChang,
      thailandUthaiThaniAmphoeNongKhayang,
      thailandUthaiThaniAmphoeSawangArom,
      thailandUthaiThaniAmphoeThapThan,
      thailandUthaiThaniHuaiKhot,
      thailandUthaiThaniLanSak,
      thailandUthaiThaniThapThan,
      thailandUthaiThaniUthaiThani
    ]);
const Region thailandUttaradit = Region(
    id: 3489,
    parentId: 219,
    longitude: 100.0992942,
    latitude: 17.6200886,
    name: "Uttaradit",
    type: null,
    stateCode: "53",
    cities: [
      thailandUttaraditAmphoeBanKhok,
      thailandUttaraditAmphoeFakTha,
      thailandUttaraditAmphoeLapLae,
      thailandUttaraditAmphoeMueangUttaradit,
      thailandUttaraditAmphoeNamPat,
      thailandUttaraditAmphoePhichai,
      thailandUttaraditAmphoeThaPla,
      thailandUttaraditAmphoeThongSaenKhan,
      thailandUttaraditAmphoeTron,
      thailandUttaraditUttaradit
    ]);
const Region thailandYala = Region(
    id: 3493,
    parentId: 219,
    longitude: -123.1653848,
    latitude: 44.0579117,
    name: "Yala",
    type: null,
    stateCode: "95",
    cities: [
      thailandYalaAmphoeBannangSata,
      thailandYalaAmphoeBetong,
      thailandYalaAmphoeKabang,
      thailandYalaAmphoeKrongPinang,
      thailandYalaAmphoeMueangYala,
      thailandYalaAmphoeRaman,
      thailandYalaAmphoeThanTo,
      thailandYalaAmphoeYaha,
      thailandYalaBetong,
      thailandYalaYala
    ]);
const Region thailandYasothon = Region(
    id: 3521,
    parentId: 219,
    longitude: 104.1452827,
    latitude: 15.792641,
    name: "Yasothon",
    type: null,
    stateCode: "35",
    cities: [
      thailandYasothonAmphoeKhamKhuanKaeo,
      thailandYasothonAmphoeKhoWang,
      thailandYasothonAmphoeKutChum,
      thailandYasothonAmphoeLoengNokTha,
      thailandYasothonAmphoeMahaChanaChai,
      thailandYasothonAmphoeMueangYasothon,
      thailandYasothonAmphoePaTio,
      thailandYasothonAmphoeSaiMun,
      thailandYasothonAmphoeThaiCharoen,
      thailandYasothonYasothon
    ]);

const thailandStates = <int, Region>{
  3523: thailandAmnatCharoen,
  3519: thailandAngThong,
  3554: thailandBangkok,
  3533: thailandBuengKan,
  3534: thailandBuriRam,
  3552: thailandChachoengsao,
  3522: thailandChaiNat,
  4954: thailandChaiyaphum,
  3486: thailandChanthaburi,
  3491: thailandChiangMai,
  3498: thailandChiangRai,
  3513: thailandChonBuri,
  3526: thailandChumphon,
  3550: thailandKalasin,
  3516: thailandKamphaengPhet,
  3511: thailandKanchanaburi,
  3485: thailandKhonKaen,
  3478: thailandKrabi,
  3544: thailandLampang,
  3483: thailandLamphun,
  3509: thailandLoei,
  3543: thailandLopBuri,
  3505: thailandMaeHongSon,
  3517: thailandMahaSarakham,
  3546: thailandMukdahan,
  3535: thailandNakhonNayok,
  3503: thailandNakhonPathom,
  3548: thailandNakhonPhanom,
  3497: thailandNakhonRatchasima,
  3492: thailandNakhonSawan,
  3520: thailandNakhonSiThammarat,
  3530: thailandNan,
  3553: thailandNarathiwat,
  3480: thailandNongBuaLamPhu,
  3484: thailandNongKhai,
  3495: thailandNonthaburi,
  3500: thailandPathumThani,
  3540: thailandPattani,
  3507: thailandPattaya,
  3549: thailandPhangnga,
  3488: thailandPhatthalung,
  3538: thailandPhayao,
  3515: thailandPhetchabun,
  3532: thailandPhetchaburi,
  3514: thailandPhichit,
  3506: thailandPhitsanulok,
  3494: thailandPhraNakhonSiAyutthaya,
  3528: thailandPhrae,
  3536: thailandPhuket,
  3542: thailandPrachinBuri,
  3508: thailandPrachuapKhiriKhan,
  3479: thailandRanong,
  3499: thailandRatchaburi,
  3518: thailandRayong,
  3510: thailandRoiEt,
  3529: thailandSaKaeo,
  3501: thailandSakonNakhon,
  3481: thailandSamutPrakan,
  3504: thailandSamutSakhon,
  3502: thailandSamutSongkhram,
  3487: thailandSaraburi,
  3537: thailandSatun,
  3547: thailandSiSaKet,
  3490: thailandSingBuri,
  3539: thailandSongkhla,
  3545: thailandSukhothai,
  3524: thailandSuphanBuri,
  3482: thailandSuratThani,
  3531: thailandSurin,
  3525: thailandTak,
  3541: thailandTrang,
  3496: thailandTrat,
  3512: thailandUbonRatchathani,
  3527: thailandUdonThani,
  3551: thailandUthaiThani,
  3489: thailandUttaradit,
  3493: thailandYala,
  3521: thailandYasothon
};
