/// Access to known geographies in The Bahamas and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'thebahamas_states.dart';

/// The country of `The Bahamas`, and its 42 states
const Country theBahamas = Country(
  id: 17,
  name: "The Bahamas",
  longitude: -76.0,
  latitude: 24.25,
  capital: "Nassau",
  currency: "BSD",
  currencySymbol: "B\$",
  currencyName: "Bahamian dollar",
  emoji: "🇧🇸",
  emojiU: "U+1F1E7 U+1F1F8",
  iso2: "BS",
  iso3: "BHS",
  native: "Bahamas",
  numericCode: "044",
  nationality: "Bahamian",
  phoneCode: "+1-242",
  region: "Americas",
  subregion: "Caribbean",
  tld: ".bs",
  states: [
    theBahamasAcklins,
    theBahamasAcklinsAndCrookedIslands,
    theBahamasBerryIslands,
    theBahamasBimini,
    theBahamasBlackPoint,
    theBahamasCatIsland,
    theBahamasCentralAbaco,
    theBahamasCentralAndros,
    theBahamasCentralEleuthera,
    theBahamasCrookedIsland,
    theBahamasEastGrandBahama,
    theBahamasExuma,
    theBahamasFreeport,
    theBahamasFreshCreek,
    theBahamasGovernorsHarbour,
    theBahamasGrandCay,
    theBahamasGreenTurtleCay,
    theBahamasHarbourIsland,
    theBahamasHighRock,
    theBahamasHopeTown,
    theBahamasInagua,
    theBahamasKempsBay,
    theBahamasLongIsland,
    theBahamasMangroveCay,
    theBahamasMarshHarbour,
    theBahamasMayaguanaDistrict,
    theBahamasNewProvidence,
    theBahamasNichollstownAndBerryIslands,
    theBahamasNorthAbaco,
    theBahamasNorthAndros,
    theBahamasNorthEleuthera,
    theBahamasRaggedIsland,
    theBahamasRockSound,
    theBahamasRumCayDistrict,
    theBahamasSanSalvadorAndRumCay,
    theBahamasSanSalvadorIsland,
    theBahamasSandyPoint,
    theBahamasSouthAbaco,
    theBahamasSouthAndros,
    theBahamasSouthEleuthera,
    theBahamasSpanishWells,
    theBahamasWestGrandBahama
  ],
  timezones: [
    Timezone(
      abbreviation: "EST",
      gmtOffset: -18000,
      gmtOffsetName: "UTC-05:00",
      tzName: "Eastern Standard Time (North America)",
      zoneName: "America/Nassau")
  ],
  translations: {
    "kr": "바하마",
    "pt-BR": "Bahamas",
    "pt": "Baamas",
    "nl": "Bahama’s",
    "hr": "Bahami",
    "fa": "باهاما",
    "de": "Bahamas",
    "es": "Bahamas",
    "fr": "Bahamas",
    "ja": "バハマ",
    "it": "Bahamas",
    "cn": "巴哈马",
    "tr": "Bahamalar"
  });
