/// Access to known geographies in Turkey and their meta data.
///
/// NOTICE: This file is auto-generated and should not be changed manually.

import '../base.dart';
import 'turkey_cities.dart';

/// The 81 regions of `🇹🇷 Turkey`
const Region turkeyAdanaPprovince = Region(
    id: 2212,
    parentId: 225,
    longitude: 35.3905046,
    latitude: 37.2612315,
    name: "Adana",
    type: "province",
    stateCode: "01",
    cities: [
      turkeyAdanaPprovinceAdana,
      turkeyAdanaPprovinceAladag,
      turkeyAdanaPprovinceBahce,
      turkeyAdanaPprovinceCeyhan,
      turkeyAdanaPprovinceCukurova,
      turkeyAdanaPprovinceFeke,
      turkeyAdanaPprovinceImamoglu,
      turkeyAdanaPprovinceKaraisali,
      turkeyAdanaPprovinceKaratas,
      turkeyAdanaPprovinceKozan,
      turkeyAdanaPprovincePozanti,
      turkeyAdanaPprovinceSaimbeyli,
      turkeyAdanaPprovinceSaricam,
      turkeyAdanaPprovinceSeyhan,
      turkeyAdanaPprovinceTufanbeyli,
      turkeyAdanaPprovinceYumurtalik,
      turkeyAdanaPprovinceYuregir
    ]);
const Region turkeyAdiyamanPprovince = Region(
    id: 2155,
    parentId: 225,
    longitude: 38.4849923,
    latitude: 37.9078291,
    name: "Adıyaman",
    type: "province",
    stateCode: "02",
    cities: [
      turkeyAdiyamanPprovinceAdiyaman,
      turkeyAdiyamanPprovinceAralikIlcesi,
      turkeyAdiyamanPprovinceBesni,
      turkeyAdiyamanPprovinceCelikhan,
      turkeyAdiyamanPprovinceGerger,
      turkeyAdiyamanPprovinceGolbasi,
      turkeyAdiyamanPprovinceKahta,
      turkeyAdiyamanPprovinceMerkez,
      turkeyAdiyamanPprovinceSamsat,
      turkeyAdiyamanPprovinceSincik,
      turkeyAdiyamanPprovinceTut
    ]);
const Region turkeyAfyonkarahisarPprovince = Region(
    id: 2179,
    parentId: 225,
    longitude: 30.7120023,
    latitude: 38.7391099,
    name: "Afyonkarahisar",
    type: "province",
    stateCode: "03",
    cities: [
      turkeyAfyonkarahisarPprovinceAfyonkarahisar,
      turkeyAfyonkarahisarPprovinceBasmakci,
      turkeyAfyonkarahisarPprovinceBayat,
      turkeyAfyonkarahisarPprovinceBolvadin,
      turkeyAfyonkarahisarPprovinceCay,
      turkeyAfyonkarahisarPprovinceCobanlarIlcesi,
      turkeyAfyonkarahisarPprovinceDazkiri,
      turkeyAfyonkarahisarPprovinceDinar,
      turkeyAfyonkarahisarPprovinceEmirdag,
      turkeyAfyonkarahisarPprovinceEvciler,
      turkeyAfyonkarahisarPprovinceHocalar,
      turkeyAfyonkarahisarPprovinceIhsaniye,
      turkeyAfyonkarahisarPprovinceIscehisar,
      turkeyAfyonkarahisarPprovinceIsiklar,
      turkeyAfyonkarahisarPprovinceKiziloren,
      turkeyAfyonkarahisarPprovinceMerkez,
      turkeyAfyonkarahisarPprovinceSandikli,
      turkeyAfyonkarahisarPprovinceSinanpasa,
      turkeyAfyonkarahisarPprovinceSuhut,
      turkeyAfyonkarahisarPprovinceSultandagi
    ]);
const Region turkeyAgriPprovince = Region(
    id: 2193,
    parentId: 225,
    longitude: 43.0215965,
    latitude: 39.6269218,
    name: "Ağrı",
    type: "province",
    stateCode: "04",
    cities: [
      turkeyAgriPprovinceAgri,
      turkeyAgriPprovinceDiyadin,
      turkeyAgriPprovinceDogubayazit,
      turkeyAgriPprovinceEleskirt,
      turkeyAgriPprovinceHamur,
      turkeyAgriPprovincePatnos,
      turkeyAgriPprovinceTaslicay,
      turkeyAgriPprovinceTutakIlcesi
    ]);
const Region turkeyAksarayPprovince = Region(
    id: 2210,
    parentId: 225,
    longitude: 33.9750018,
    latitude: 38.3352043,
    name: "Aksaray",
    type: "province",
    stateCode: "68",
    cities: [
      turkeyAksarayPprovinceAgacoren,
      turkeyAksarayPprovinceAksaray,
      turkeyAksarayPprovinceEskilIlcesi,
      turkeyAksarayPprovinceGulagacIlcesi,
      turkeyAksarayPprovinceGuzelyurt,
      turkeyAksarayPprovinceMerkez,
      turkeyAksarayPprovinceOrtakoy,
      turkeyAksarayPprovinceSariyahsi,
      turkeyAksarayPprovinceSultanhani
    ]);
const Region turkeyAmasyaPprovince = Region(
    id: 2161,
    parentId: 225,
    longitude: 35.9037966,
    latitude: 40.6516608,
    name: "Amasya",
    type: "province",
    stateCode: "05",
    cities: [
      turkeyAmasyaPprovinceAmasya,
      turkeyAmasyaPprovinceDedekoy,
      turkeyAmasyaPprovinceGoynucek,
      turkeyAmasyaPprovinceGumushacikoy,
      turkeyAmasyaPprovinceHamamozuIlcesi,
      turkeyAmasyaPprovinceMerkez,
      turkeyAmasyaPprovinceMerzifonIlcesi,
      turkeyAmasyaPprovinceSuluova,
      turkeyAmasyaPprovinceTasova
    ]);
const Region turkeyAnkaraPprovince = Region(
    id: 2217,
    parentId: 225,
    longitude: 32.7181375,
    latitude: 39.7805245,
    name: "Ankara",
    type: "province",
    stateCode: "06",
    cities: [
      turkeyAnkaraPprovinceAkyurt,
      turkeyAnkaraPprovinceAltindag,
      turkeyAnkaraPprovinceAltpinar,
      turkeyAnkaraPprovinceAnkara,
      turkeyAnkaraPprovinceAyas,
      turkeyAnkaraPprovinceBalaIlcesi,
      turkeyAnkaraPprovinceBatikent,
      turkeyAnkaraPprovinceBeypazari,
      turkeyAnkaraPprovinceBeypazari,
      turkeyAnkaraPprovinceCamlidere,
      turkeyAnkaraPprovinceCankaya,
      turkeyAnkaraPprovinceCubuk,
      turkeyAnkaraPprovinceElmadag,
      turkeyAnkaraPprovinceEtimesgutIlcesi,
      turkeyAnkaraPprovinceEvren,
      turkeyAnkaraPprovinceGolbasi,
      turkeyAnkaraPprovinceGudul,
      turkeyAnkaraPprovinceHaymana,
      turkeyAnkaraPprovinceKahramankazan,
      turkeyAnkaraPprovinceKalecik,
      turkeyAnkaraPprovinceKazan,
      turkeyAnkaraPprovinceKecioren,
      turkeyAnkaraPprovinceKizilcahamam,
      turkeyAnkaraPprovinceMamakIlcesi,
      turkeyAnkaraPprovinceNallihan,
      turkeyAnkaraPprovincePolatli,
      turkeyAnkaraPprovincePursaklar,
      turkeyAnkaraPprovinceSereflikochisar,
      turkeyAnkaraPprovinceSincanIlcesi,
      turkeyAnkaraPprovinceYenimahalle
    ]);
const Region turkeyAntalyaPprovince = Region(
    id: 2169,
    parentId: 225,
    longitude: 31.0793705,
    latitude: 37.0951672,
    name: "Antalya",
    type: "province",
    stateCode: "07",
    cities: [
      turkeyAntalyaPprovinceAkseki,
      turkeyAntalyaPprovinceAksu,
      turkeyAntalyaPprovinceAlanya,
      turkeyAntalyaPprovinceAntalya,
      turkeyAntalyaPprovinceAvsallar,
      turkeyAntalyaPprovinceBelek,
      turkeyAntalyaPprovinceBeykonak,
      turkeyAntalyaPprovinceBogazkent,
      turkeyAntalyaPprovinceDemre,
      turkeyAntalyaPprovinceDosemealtiIlcesi,
      turkeyAntalyaPprovinceEksere,
      turkeyAntalyaPprovinceElmali,
      turkeyAntalyaPprovinceEvrenseki,
      turkeyAntalyaPprovinceFinike,
      turkeyAntalyaPprovinceGazipasa,
      turkeyAntalyaPprovinceGoynuk,
      turkeyAntalyaPprovinceGundogmusIlcesi,
      turkeyAntalyaPprovinceIbradi,
      turkeyAntalyaPprovinceKalkan,
      turkeyAntalyaPprovinceKas,
      turkeyAntalyaPprovinceKemer,
      turkeyAntalyaPprovinceKepezIlcesi,
      turkeyAntalyaPprovinceKizilagac,
      turkeyAntalyaPprovinceKonyaalti,
      turkeyAntalyaPprovinceKorkuteli,
      turkeyAntalyaPprovinceKumkoy,
      turkeyAntalyaPprovinceKumluca,
      turkeyAntalyaPprovinceMahmutlar,
      turkeyAntalyaPprovinceManavgat,
      turkeyAntalyaPprovinceMuratpasa,
      turkeyAntalyaPprovinceOkurcalar,
      turkeyAntalyaPprovincePayallar,
      turkeyAntalyaPprovinceSerik,
      turkeyAntalyaPprovinceSide,
      turkeyAntalyaPprovinceTekirova,
      turkeyAntalyaPprovinceTurkler,
      turkeyAntalyaPprovinceTuruncova
    ]);
const Region turkeyArdahanPprovince = Region(
    id: 2185,
    parentId: 225,
    longitude: 42.7831674,
    latitude: 41.1112964,
    name: "Ardahan",
    type: "province",
    stateCode: "75",
    cities: [
      turkeyArdahanPprovinceArdahan,
      turkeyArdahanPprovinceCildirIlcesi,
      turkeyArdahanPprovinceDamal,
      turkeyArdahanPprovinceGole,
      turkeyArdahanPprovinceHanak,
      turkeyArdahanPprovincePosof
    ]);
const Region turkeyArtvinPprovince = Region(
    id: 2191,
    parentId: 225,
    longitude: 41.7628223,
    latitude: 41.078664,
    name: "Artvin",
    type: "province",
    stateCode: "08",
    cities: [
      turkeyArtvinPprovinceArdanuc,
      turkeyArtvinPprovinceArhavi,
      turkeyArtvinPprovinceArtvin,
      turkeyArtvinPprovinceBorcka,
      turkeyArtvinPprovinceHopa,
      turkeyArtvinPprovinceKemalpasa,
      turkeyArtvinPprovinceMurgul,
      turkeyArtvinPprovinceSavsat,
      turkeyArtvinPprovinceSeyitler,
      turkeyArtvinPprovinceYusufeli
    ]);
const Region turkeyAydinPprovince = Region(
    id: 2187,
    parentId: 225,
    longitude: 28.4863963,
    latitude: 37.8117033,
    name: "Aydın",
    type: "province",
    stateCode: "09",
    cities: [
      turkeyAydinPprovinceAcarlar,
      turkeyAydinPprovinceAtca,
      turkeyAydinPprovinceAydin,
      turkeyAydinPprovinceBozdogan,
      turkeyAydinPprovinceBuharkent,
      turkeyAydinPprovinceCine,
      turkeyAydinPprovinceDalama,
      turkeyAydinPprovinceDavutlar,
      turkeyAydinPprovinceDidim,
      turkeyAydinPprovinceEfeler,
      turkeyAydinPprovinceGermencik,
      turkeyAydinPprovinceIncirliova,
      turkeyAydinPprovinceIsabeyli,
      turkeyAydinPprovinceKaracasu,
      turkeyAydinPprovinceKarpuzlu,
      turkeyAydinPprovinceKocarli,
      turkeyAydinPprovinceKosk,
      turkeyAydinPprovinceKusadasi,
      turkeyAydinPprovinceKuyucak,
      turkeyAydinPprovinceNazilli,
      turkeyAydinPprovinceSarikemer,
      turkeyAydinPprovinceSoke,
      turkeyAydinPprovinceSultanhisar,
      turkeyAydinPprovinceTepecik,
      turkeyAydinPprovinceYenipazar
    ]);
const Region turkeyBalikesirPprovince = Region(
    id: 2175,
    parentId: 225,
    longitude: 28.1122679,
    latitude: 39.7616782,
    name: "Balıkesir",
    type: "province",
    stateCode: "10",
    cities: [
      turkeyBalikesirPprovinceAltieylulIlcesi,
      turkeyBalikesirPprovinceAltinoluk,
      turkeyBalikesirPprovinceAyvalik,
      turkeyBalikesirPprovinceBalikesir,
      turkeyBalikesirPprovinceBalya,
      turkeyBalikesirPprovinceBandirma,
      turkeyBalikesirPprovinceBigadic,
      turkeyBalikesirPprovinceBurhaniye,
      turkeyBalikesirPprovinceDursunbey,
      turkeyBalikesirPprovinceEdremit,
      turkeyBalikesirPprovinceErdek,
      turkeyBalikesirPprovinceGomec,
      turkeyBalikesirPprovinceGonen,
      turkeyBalikesirPprovinceHavran,
      turkeyBalikesirPprovinceIvrindi,
      turkeyBalikesirPprovinceKepsut,
      turkeyBalikesirPprovinceManyas,
      turkeyBalikesirPprovinceMarmara,
      turkeyBalikesirPprovinceSavastepe,
      turkeyBalikesirPprovinceSindirgi,
      turkeyBalikesirPprovinceSusurluk
    ]);
const Region turkeyBartinPprovince = Region(
    id: 2148,
    parentId: 225,
    longitude: 32.4609794,
    latitude: 41.5810509,
    name: "Bartın",
    type: "province",
    stateCode: "74",
    cities: [
      turkeyBartinPprovinceAmasra,
      turkeyBartinPprovinceBartin,
      turkeyBartinPprovinceKurucasile,
      turkeyBartinPprovinceUlusIlcesi
    ]);
const Region turkeyBatmanPprovince = Region(
    id: 2194,
    parentId: 225,
    longitude: 41.3605739,
    latitude: 37.8362496,
    name: "Batman",
    type: "province",
    stateCode: "72",
    cities: [
      turkeyBatmanPprovinceAviski,
      turkeyBatmanPprovinceAydinkonak,
      turkeyBatmanPprovinceBalpinar,
      turkeyBatmanPprovinceBatman,
      turkeyBatmanPprovinceBesiri,
      turkeyBatmanPprovinceBespinar,
      turkeyBatmanPprovinceBinatli,
      turkeyBatmanPprovinceCevrimova,
      turkeyBatmanPprovinceDemiryol,
      turkeyBatmanPprovinceDogankavak,
      turkeyBatmanPprovinceErkoklu,
      turkeyBatmanPprovinceGercusIlcesi,
      turkeyBatmanPprovinceGerdzhyush,
      turkeyBatmanPprovinceHasankeyf,
      turkeyBatmanPprovinceHisar,
      turkeyBatmanPprovinceKayapinar,
      turkeyBatmanPprovinceKozlukIlcesi,
      turkeyBatmanPprovinceMerkez,
      turkeyBatmanPprovinceOymatas,
      turkeyBatmanPprovinceSason,
      turkeyBatmanPprovinceYenikoy,
      turkeyBatmanPprovinceYenipinar,
      turkeyBatmanPprovinceYolagzi
    ]);
const Region turkeyBayburtPprovince = Region(
    id: 2177,
    parentId: 225,
    longitude: 40.228048,
    latitude: 40.26032,
    name: "Bayburt",
    type: "province",
    stateCode: "69",
    cities: [
      turkeyBayburtPprovinceAydintepe,
      turkeyBayburtPprovinceBayburt,
      turkeyBayburtPprovinceDemirozuIlcesi,
      turkeyBayburtPprovincePulur
    ]);
const Region turkeyBilecikPprovince = Region(
    id: 2221,
    parentId: 225,
    longitude: 30.0665236,
    latitude: 40.0566555,
    name: "Bilecik",
    type: "province",
    stateCode: "11",
    cities: [
      turkeyBilecikPprovinceBilecik,
      turkeyBilecikPprovinceBozuyuk,
      turkeyBilecikPprovinceDodurga,
      turkeyBilecikPprovinceGolpazari,
      turkeyBilecikPprovinceInhisar,
      turkeyBilecikPprovinceKuplu,
      turkeyBilecikPprovinceOsmaneli,
      turkeyBilecikPprovincePazaryeri,
      turkeyBilecikPprovinceSogutIlcesi,
      turkeyBilecikPprovinceVezirhan,
      turkeyBilecikPprovinceYenipazar
    ]);
const Region turkeyBingolPprovince = Region(
    id: 2153,
    parentId: 225,
    longitude: 40.7696095,
    latitude: 39.0626354,
    name: "Bingöl",
    type: "province",
    stateCode: "12",
    cities: [
      turkeyBingolPprovinceAdakliIlcesi,
      turkeyBingolPprovinceBingol,
      turkeyBingolPprovinceGenc,
      turkeyBingolPprovinceKarliova,
      turkeyBingolPprovinceKigiIlcesi,
      turkeyBingolPprovinceMerkez,
      turkeyBingolPprovinceSolhan,
      turkeyBingolPprovinceYayladere,
      turkeyBingolPprovinceYedisu
    ]);
const Region turkeyBitlisPprovince = Region(
    id: 2215,
    parentId: 225,
    longitude: 42.4202028,
    latitude: 38.6523133,
    name: "Bitlis",
    type: "province",
    stateCode: "13",
    cities: [
      turkeyBitlisPprovinceAdilcevaz,
      turkeyBitlisPprovinceAhlat,
      turkeyBitlisPprovinceBegendik,
      turkeyBitlisPprovinceBitlis,
      turkeyBitlisPprovinceGuroymak,
      turkeyBitlisPprovinceHizan,
      turkeyBitlisPprovinceMerkez,
      turkeyBitlisPprovinceMutki,
      turkeyBitlisPprovinceTatvan
    ]);
const Region turkeyBoluPprovince = Region(
    id: 2172,
    parentId: 225,
    longitude: 31.5788086,
    latitude: 40.5759766,
    name: "Bolu",
    type: "province",
    stateCode: "14",
    cities: [
      turkeyBoluPprovinceBolu,
      turkeyBoluPprovinceDortdivan,
      turkeyBoluPprovinceGerede,
      turkeyBoluPprovinceGoynuk,
      turkeyBoluPprovinceKibriscik,
      turkeyBoluPprovinceMengen,
      turkeyBoluPprovinceMudurnu,
      turkeyBoluPprovinceSeben,
      turkeyBoluPprovinceYenicaga
    ]);
const Region turkeyBurdurPprovince = Region(
    id: 2209,
    parentId: 225,
    longitude: 30.0665236,
    latitude: 37.4612669,
    name: "Burdur",
    type: "province",
    stateCode: "15",
    cities: [
      turkeyBurdurPprovinceAglasun,
      turkeyBurdurPprovinceAltinyayla,
      turkeyBurdurPprovinceBucak,
      turkeyBurdurPprovinceBurdur,
      turkeyBurdurPprovinceCavdirIlcesi,
      turkeyBurdurPprovinceCeltikciIlcesi,
      turkeyBurdurPprovinceGolhisar,
      turkeyBurdurPprovinceKaramanli,
      turkeyBurdurPprovinceKemer,
      turkeyBurdurPprovinceKizilkaya,
      turkeyBurdurPprovinceKocaaliler,
      turkeyBurdurPprovinceMerkez,
      turkeyBurdurPprovinceTefenni,
      turkeyBurdurPprovinceYesilova
    ]);
const Region turkeyBursaPprovince = Region(
    id: 2163,
    parentId: 225,
    longitude: 29.2320784,
    latitude: 40.0655459,
    name: "Bursa",
    type: "province",
    stateCode: "16",
    cities: [
      turkeyBursaPprovinceAlanyurt,
      turkeyBursaPprovinceBalarim,
      turkeyBursaPprovinceBoyalica,
      turkeyBursaPprovinceBursa,
      turkeyBursaPprovinceBuyukorhanIlcesi,
      turkeyBursaPprovinceCakirca,
      turkeyBursaPprovinceCakirli,
      turkeyBursaPprovinceCerrah,
      turkeyBursaPprovinceDemirtas,
      turkeyBursaPprovinceElbeyli,
      turkeyBursaPprovinceGemlik,
      turkeyBursaPprovinceGursu,
      turkeyBursaPprovinceHamzabey,
      turkeyBursaPprovinceHarmancikIlcesi,
      turkeyBursaPprovinceInegol,
      turkeyBursaPprovinceIznik,
      turkeyBursaPprovinceKaracabey,
      turkeyBursaPprovinceKarincali,
      turkeyBursaPprovinceKeles,
      turkeyBursaPprovinceKestel,
      turkeyBursaPprovinceKirazli,
      turkeyBursaPprovinceKucukkumla,
      turkeyBursaPprovinceKursunlu,
      turkeyBursaPprovinceMudanya,
      turkeyBursaPprovinceMustafakemalpasa,
      turkeyBursaPprovinceNarlica,
      turkeyBursaPprovinceNilufer,
      turkeyBursaPprovinceOrhaneli,
      turkeyBursaPprovinceOrhangazi,
      turkeyBursaPprovinceOsmangazi,
      turkeyBursaPprovinceSoloz,
      turkeyBursaPprovinceTacir,
      turkeyBursaPprovinceTahtakopru,
      turkeyBursaPprovinceTatkavakli,
      turkeyBursaPprovinceUmurbey,
      turkeyBursaPprovinceYenice,
      turkeyBursaPprovinceYenikoy,
      turkeyBursaPprovinceYenisehir,
      turkeyBursaPprovinceYildirimIlcesi
    ]);
const Region turkeyCanakkalePprovince = Region(
    id: 2216,
    parentId: 225,
    longitude: 26.9852422,
    latitude: 40.0510104,
    name: "Çanakkale",
    type: "province",
    stateCode: "17",
    cities: [
      turkeyCanakkalePprovinceAyvacik,
      turkeyCanakkalePprovinceBayramicIlcesi,
      turkeyCanakkalePprovinceBehram,
      turkeyCanakkalePprovinceBiga,
      turkeyCanakkalePprovinceBozcaada,
      turkeyCanakkalePprovinceCan,
      turkeyCanakkalePprovinceCanakkale,
      turkeyCanakkalePprovinceEceabat,
      turkeyCanakkalePprovinceEzine,
      turkeyCanakkalePprovinceGelibolu,
      turkeyCanakkalePprovinceGeyikli,
      turkeyCanakkalePprovinceGokceada,
      turkeyCanakkalePprovinceHamdibey,
      turkeyCanakkalePprovinceKalkim,
      turkeyCanakkalePprovinceLapseki,
      turkeyCanakkalePprovinceLapsekiIlcesi,
      turkeyCanakkalePprovinceMerkez,
      turkeyCanakkalePprovinceYenice
    ]);
const Region turkeyCankiriPprovince = Region(
    id: 2168,
    parentId: 225,
    longitude: 33.5883893,
    latitude: 40.5369073,
    name: "Çankırı",
    type: "province",
    stateCode: "18",
    cities: [
      turkeyCankiriPprovinceAtkaracalar,
      turkeyCankiriPprovinceBayramoren,
      turkeyCankiriPprovinceCerkes,
      turkeyCankiriPprovinceEldivan,
      turkeyCankiriPprovinceIlgaz,
      turkeyCankiriPprovinceKhanjarah,
      turkeyCankiriPprovinceKizilirmak,
      turkeyCankiriPprovinceKorgun,
      turkeyCankiriPprovinceKursunlu,
      turkeyCankiriPprovinceOrta,
      turkeyCankiriPprovinceSabanozu,
      turkeyCankiriPprovinceYaprakli
    ]);
const Region turkeyCorumPprovince = Region(
    id: 2173,
    parentId: 225,
    longitude: 34.5986263,
    latitude: 40.4998211,
    name: "Çorum",
    type: "province",
    stateCode: "19",
    cities: [
      turkeyCorumPprovinceAlaca,
      turkeyCorumPprovinceBayat,
      turkeyCorumPprovinceBogazkaleIlcesi,
      turkeyCorumPprovinceCorum,
      turkeyCorumPprovinceDodurga,
      turkeyCorumPprovinceIskilip,
      turkeyCorumPprovinceKargiIlcesi,
      turkeyCorumPprovinceLacin,
      turkeyCorumPprovinceMecitozu,
      turkeyCorumPprovinceMerkez,
      turkeyCorumPprovinceOguzlarIlcesi,
      turkeyCorumPprovinceOrtakoy,
      turkeyCorumPprovinceOsmancik,
      turkeyCorumPprovinceSungurlu,
      turkeyCorumPprovinceUgurludag
    ]);
const Region turkeyDenizliPprovince = Region(
    id: 2157,
    parentId: 225,
    longitude: 29.2320784,
    latitude: 37.6128395,
    name: "Denizli",
    type: "province",
    stateCode: "20",
    cities: [
      turkeyDenizliPprovinceAcipayam,
      turkeyDenizliPprovinceAkkent,
      turkeyDenizliPprovinceAkkoy,
      turkeyDenizliPprovinceBabadag,
      turkeyDenizliPprovinceBaklan,
      turkeyDenizliPprovinceBekilli,
      turkeyDenizliPprovinceBeyagacIlcesi,
      turkeyDenizliPprovinceBozkurt,
      turkeyDenizliPprovinceBuldan,
      turkeyDenizliPprovinceCalIlcesi,
      turkeyDenizliPprovinceCameliIlcesi,
      turkeyDenizliPprovinceCardak,
      turkeyDenizliPprovinceCivril,
      turkeyDenizliPprovinceDenizli,
      turkeyDenizliPprovinceGozler,
      turkeyDenizliPprovinceGuneyIlcesi,
      turkeyDenizliPprovinceHonaz,
      turkeyDenizliPprovinceKale,
      turkeyDenizliPprovinceMerkezefendi,
      turkeyDenizliPprovinceNikfer,
      turkeyDenizliPprovincePamukkale,
      turkeyDenizliPprovinceSaraykoy,
      turkeyDenizliPprovinceSerinhisar,
      turkeyDenizliPprovinceTavas
    ]);
const Region turkeyDiyarbakirPprovince = Region(
    id: 2226,
    parentId: 225,
    longitude: 40.5426896,
    latitude: 38.1066372,
    name: "Diyarbakır",
    type: "province",
    stateCode: "21",
    cities: [
      turkeyDiyarbakirPprovinceAlacakayaIlcesi,
      turkeyDiyarbakirPprovinceAltinkum,
      turkeyDiyarbakirPprovinceAmbar,
      turkeyDiyarbakirPprovinceAralik,
      turkeyDiyarbakirPprovinceBaglar,
      turkeyDiyarbakirPprovinceBismil,
      turkeyDiyarbakirPprovinceCermik,
      turkeyDiyarbakirPprovinceCinarIlcesi,
      turkeyDiyarbakirPprovinceCungus,
      turkeyDiyarbakirPprovinceDicle,
      turkeyDiyarbakirPprovinceDiyarbakir,
      turkeyDiyarbakirPprovinceEgil,
      turkeyDiyarbakirPprovinceErgani,
      turkeyDiyarbakirPprovinceHani,
      turkeyDiyarbakirPprovinceHazro,
      turkeyDiyarbakirPprovinceKayapinar,
      turkeyDiyarbakirPprovinceKazanci,
      turkeyDiyarbakirPprovinceKerh,
      turkeyDiyarbakirPprovinceKocakoy,
      turkeyDiyarbakirPprovinceKoseli,
      turkeyDiyarbakirPprovinceKulp,
      turkeyDiyarbakirPprovinceLice,
      turkeyDiyarbakirPprovinceSalat,
      turkeyDiyarbakirPprovinceSilvan,
      turkeyDiyarbakirPprovinceSinankoy,
      turkeyDiyarbakirPprovinceSur,
      turkeyDiyarbakirPprovinceYaprakbasi,
      turkeyDiyarbakirPprovinceYenisehir
    ]);
const Region turkeyDuzcePprovince = Region(
    id: 2202,
    parentId: 225,
    longitude: 31.3192713,
    latitude: 40.8770531,
    name: "Düzce",
    type: "province",
    stateCode: "81",
    cities: [
      turkeyDuzcePprovinceAkcakoca,
      turkeyDuzcePprovinceCilimliIlcesi,
      turkeyDuzcePprovinceCumayeriIlcesi,
      turkeyDuzcePprovinceDuzce,
      turkeyDuzcePprovinceGolyakaIlcesi,
      turkeyDuzcePprovinceGumusovaIlcesi,
      turkeyDuzcePprovinceKaynasliIlcesi,
      turkeyDuzcePprovinceYigilcaIlcesi
    ]);
const Region turkeyEdirnePprovince = Region(
    id: 2151,
    parentId: 225,
    longitude: 26.5137964,
    latitude: 41.1517222,
    name: "Edirne",
    type: "province",
    stateCode: "22",
    cities: [
      turkeyEdirnePprovinceEdirne,
      turkeyEdirnePprovinceEnez,
      turkeyEdirnePprovinceHavsa,
      turkeyEdirnePprovinceIpsala,
      turkeyEdirnePprovinceKesan,
      turkeyEdirnePprovinceKuplu,
      turkeyEdirnePprovinceLalapasa,
      turkeyEdirnePprovinceMeric,
      turkeyEdirnePprovinceSulogluIlcesi,
      turkeyEdirnePprovinceUzunkopru
    ]);
const Region turkeyElazigPprovince = Region(
    id: 2159,
    parentId: 225,
    longitude: 39.2199029,
    latitude: 38.4964804,
    name: "Elazığ",
    type: "province",
    stateCode: "23",
    cities: [
      turkeyElazigPprovinceAgin,
      turkeyElazigPprovinceAricak,
      turkeyElazigPprovinceBaskil,
      turkeyElazigPprovinceElazig,
      turkeyElazigPprovinceKarakocan,
      turkeyElazigPprovinceKarakocanElazig,
      turkeyElazigPprovinceKeban,
      turkeyElazigPprovinceKovancilar,
      turkeyElazigPprovinceMadenIlcesi,
      turkeyElazigPprovinceMerkez,
      turkeyElazigPprovincePalu,
      turkeyElazigPprovinceSivrice,
      turkeyElazigPprovinceTurluk
    ]);
const Region turkeyErzincanPprovince = Region(
    id: 2160,
    parentId: 225,
    longitude: 39.0501306,
    latitude: 39.7681914,
    name: "Erzincan",
    type: "province",
    stateCode: "24",
    cities: [
      turkeyErzincanPprovinceCayirliIlcesi,
      turkeyErzincanPprovinceCimin,
      turkeyErzincanPprovinceErzincan,
      turkeyErzincanPprovinceIlicIlcesi,
      turkeyErzincanPprovinceKemah,
      turkeyErzincanPprovinceKemaliye,
      turkeyErzincanPprovinceOtlukbeli,
      turkeyErzincanPprovinceRefahiye,
      turkeyErzincanPprovinceTercan,
      turkeyErzincanPprovinceUzumluIlcesi
    ]);
const Region turkeyErzurumPprovince = Region(
    id: 2165,
    parentId: 225,
    longitude: 41.6694562,
    latitude: 40.0746799,
    name: "Erzurum",
    type: "province",
    stateCode: "25",
    cities: [
      turkeyErzurumPprovinceAskale,
      turkeyErzurumPprovinceAziziye,
      turkeyErzurumPprovinceCatIlcesi,
      turkeyErzurumPprovinceErzurum,
      turkeyErzurumPprovinceHinis,
      turkeyErzurumPprovinceHorasan,
      turkeyErzurumPprovinceIlica,
      turkeyErzurumPprovinceIspir,
      turkeyErzurumPprovinceKaracoban,
      turkeyErzurumPprovinceKarayazi,
      turkeyErzurumPprovinceKoprukoyIlcesi,
      turkeyErzurumPprovinceNarman,
      turkeyErzurumPprovinceOltu,
      turkeyErzurumPprovinceOlur,
      turkeyErzurumPprovincePalandoken,
      turkeyErzurumPprovincePasinler,
      turkeyErzurumPprovincePazaryolu,
      turkeyErzurumPprovinceSenkaya,
      turkeyErzurumPprovinceTekman,
      turkeyErzurumPprovinceTortum,
      turkeyErzurumPprovinceUzundere,
      turkeyErzurumPprovinceYakutiye
    ]);
const Region turkeyEskisehirPprovince = Region(
    id: 2164,
    parentId: 225,
    longitude: 31.2626366,
    latitude: 39.6329657,
    name: "Eskişehir",
    type: "province",
    stateCode: "26",
    cities: [
      turkeyEskisehirPprovinceAlpu,
      turkeyEskisehirPprovinceBeylikova,
      turkeyEskisehirPprovinceBozan,
      turkeyEskisehirPprovinceCifteler,
      turkeyEskisehirPprovinceEskisehir,
      turkeyEskisehirPprovinceGunyuzuIlcesi,
      turkeyEskisehirPprovinceHan,
      turkeyEskisehirPprovinceInonu,
      turkeyEskisehirPprovinceKirka,
      turkeyEskisehirPprovinceMahmudiyeIlcesi,
      turkeyEskisehirPprovinceMihalgazi,
      turkeyEskisehirPprovinceMihaliccikIlcesi,
      turkeyEskisehirPprovinceOdunpazari,
      turkeyEskisehirPprovinceSaricakayaIlcesi,
      turkeyEskisehirPprovinceSevinc,
      turkeyEskisehirPprovinceSeyitgazi,
      turkeyEskisehirPprovinceSivrihisar,
      turkeyEskisehirPprovinceTepebasi
    ]);
const Region turkeyGaziantepPprovince = Region(
    id: 2203,
    parentId: 225,
    longitude: 37.3827234,
    latitude: 37.0763882,
    name: "Gaziantep",
    type: "province",
    stateCode: "27",
    cities: [
      turkeyGaziantepPprovinceAraban,
      turkeyGaziantepPprovinceDoganpinar,
      turkeyGaziantepPprovinceGaziantep,
      turkeyGaziantepPprovinceIkizce,
      turkeyGaziantepPprovinceIslahiyeIlcesi,
      turkeyGaziantepPprovinceKarkamis,
      turkeyGaziantepPprovinceNizip,
      turkeyGaziantepPprovinceNurdagi,
      turkeyGaziantepPprovinceOguzeli,
      turkeyGaziantepPprovinceSahinbeyIlcesi,
      turkeyGaziantepPprovinceSehitkamil,
      turkeyGaziantepPprovinceSekili,
      turkeyGaziantepPprovinceUluyatir,
      turkeyGaziantepPprovinceYavuzeli,
      turkeyGaziantepPprovinceYesildere
    ]);
const Region turkeyGiresunPprovince = Region(
    id: 2186,
    parentId: 225,
    longitude: 38.5935511,
    latitude: 40.6461672,
    name: "Giresun",
    type: "province",
    stateCode: "28",
    cities: [
      turkeyGiresunPprovinceAlucraIlcesi,
      turkeyGiresunPprovinceBulancak,
      turkeyGiresunPprovinceCamolukIlcesi,
      turkeyGiresunPprovinceCanakci,
      turkeyGiresunPprovinceDereli,
      turkeyGiresunPprovinceDogankent,
      turkeyGiresunPprovinceEspiye,
      turkeyGiresunPprovinceEynesil,
      turkeyGiresunPprovinceGiresun,
      turkeyGiresunPprovinceGorele,
      turkeyGiresunPprovinceGuceIlcesi,
      turkeyGiresunPprovinceKesap,
      turkeyGiresunPprovinceMerkez,
      turkeyGiresunPprovincePiraziz,
      turkeyGiresunPprovinceSebinKarahisar,
      turkeyGiresunPprovinceTirebolu,
      turkeyGiresunPprovinceYaglidereIlcesi
    ]);
const Region turkeyGumushanePprovince = Region(
    id: 2204,
    parentId: 225,
    longitude: 39.3143253,
    latitude: 40.2803673,
    name: "Gümüşhane",
    type: "province",
    stateCode: "29",
    cities: [
      turkeyGumushanePprovinceEvren,
      turkeyGumushanePprovinceGumushkhane,
      turkeyGumushanePprovinceKelkit,
      turkeyGumushanePprovinceKose,
      turkeyGumushanePprovinceKurtun,
      turkeyGumushanePprovinceMerkez,
      turkeyGumushanePprovinceSiran,
      turkeyGumushanePprovinceTorul,
      turkeyGumushanePprovinceYaglidere
    ]);
const Region turkeyHakkariPprovince = Region(
    id: 2190,
    parentId: 225,
    longitude: 43.7449841,
    latitude: 37.4459319,
    name: "Hakkâri",
    type: "province",
    stateCode: "30",
    cities: [
      turkeyHakkariPprovinceCukurca,
      turkeyHakkariPprovinceHakkari,
      turkeyHakkariPprovinceKarsani,
      turkeyHakkariPprovinceSemdinli,
      turkeyHakkariPprovinceSemdinniIlcesi,
      turkeyHakkariPprovinceYuksekova
    ]);
const Region turkeyHatayPprovince = Region(
    id: 2211,
    parentId: 225,
    longitude: 36.3498097,
    latitude: 36.4018488,
    name: "Hatay",
    type: "province",
    stateCode: "31",
    cities: [
      turkeyHatayPprovinceAcikdere,
      turkeyHatayPprovinceAltinozu,
      turkeyHatayPprovinceAnayazi,
      turkeyHatayPprovinceAntakya,
      turkeyHatayPprovinceArsuz,
      turkeyHatayPprovinceAsagiKarafakili,
      turkeyHatayPprovinceAsagiokcular,
      turkeyHatayPprovinceBaliklidere,
      turkeyHatayPprovinceBelen,
      turkeyHatayPprovinceBoynuyogun,
      turkeyHatayPprovinceBuyukDalyan,
      turkeyHatayPprovinceBuyukcat,
      turkeyHatayPprovinceCirtiman,
      turkeyHatayPprovinceDefne,
      turkeyHatayPprovinceDenizciler,
      turkeyHatayPprovinceDortyol,
      turkeyHatayPprovinceDursunlu,
      turkeyHatayPprovinceErzin,
      turkeyHatayPprovinceGumusgoze,
      turkeyHatayPprovinceGunyazi,
      turkeyHatayPprovinceHacipasa,
      turkeyHatayPprovinceHassa,
      turkeyHatayPprovinceIskenderun,
      turkeyHatayPprovinceKarasuleymanli,
      turkeyHatayPprovinceKastal,
      turkeyHatayPprovinceKirikhan,
      turkeyHatayPprovinceKislak,
      turkeyHatayPprovinceKizkalesi,
      turkeyHatayPprovinceKumluIlcesi,
      turkeyHatayPprovinceKuzeytepe,
      turkeyHatayPprovinceMahmutlar,
      turkeyHatayPprovincePayas,
      turkeyHatayPprovinceReyhanli,
      turkeyHatayPprovinceSamankaya,
      turkeyHatayPprovinceSerinyol,
      turkeyHatayPprovinceTepehan,
      turkeyHatayPprovinceToygarli,
      turkeyHatayPprovinceUzunbag,
      turkeyHatayPprovinceUzunkavak,
      turkeyHatayPprovinceYayladagi
    ]);
const Region turkeyIgdirPprovince = Region(
    id: 2166,
    parentId: 225,
    longitude: 44.0048365,
    latitude: 39.8879841,
    name: "Iğdır",
    type: "province",
    stateCode: "76",
    cities: [
      turkeyIgdirPprovinceIgdir,
      turkeyIgdirPprovinceKarakoyunlu,
      turkeyIgdirPprovinceTuzlucaIlcesi
    ]);
const Region turkeyIspartaPprovince = Region(
    id: 2222,
    parentId: 225,
    longitude: 31.0793705,
    latitude: 38.0211464,
    name: "Isparta",
    type: "province",
    stateCode: "32",
    cities: [
      turkeyIspartaPprovinceAksu,
      turkeyIspartaPprovinceAnamas,
      turkeyIspartaPprovinceAtabey,
      turkeyIspartaPprovinceEgirdir,
      turkeyIspartaPprovinceGelendost,
      turkeyIspartaPprovinceGonen,
      turkeyIspartaPprovinceIsparta,
      turkeyIspartaPprovinceKeciborlu,
      turkeyIspartaPprovincePavluCebel,
      turkeyIspartaPprovinceSarkikaraagac,
      turkeyIspartaPprovinceSenirkent,
      turkeyIspartaPprovinceSutculerIlcesi,
      turkeyIspartaPprovinceUluborlu,
      turkeyIspartaPprovinceYalvac,
      turkeyIspartaPprovinceYenisarbademli
    ]);
const Region turkeyIstanbulPprovince = Region(
    id: 2170,
    parentId: 225,
    longitude: 28.7664408,
    latitude: 41.1634302,
    name: "Istanbul",
    type: "province",
    stateCode: "34",
    cities: [
      turkeyIstanbulPprovinceAdalar,
      turkeyIstanbulPprovinceArnavutkoy,
      turkeyIstanbulPprovinceAtasehir,
      turkeyIstanbulPprovinceAvcilar,
      turkeyIstanbulPprovinceBagcilar,
      turkeyIstanbulPprovinceBahcelievler,
      turkeyIstanbulPprovinceBakirkoy,
      turkeyIstanbulPprovinceBasaksehir,
      turkeyIstanbulPprovinceBayrampasa,
      turkeyIstanbulPprovinceBesiktas,
      turkeyIstanbulPprovinceBeykoz,
      turkeyIstanbulPprovinceBeylikduzu,
      turkeyIstanbulPprovinceBeyoglu,
      turkeyIstanbulPprovinceBuyukcekmece,
      turkeyIstanbulPprovinceCatalca,
      turkeyIstanbulPprovinceCekmekoy,
      turkeyIstanbulPprovinceEminonu,
      turkeyIstanbulPprovinceEsenler,
      turkeyIstanbulPprovinceEsenyurt,
      turkeyIstanbulPprovinceEyupsultan,
      turkeyIstanbulPprovinceFatih,
      turkeyIstanbulPprovinceGaziosmanpasa,
      turkeyIstanbulPprovinceGungoren,
      turkeyIstanbulPprovinceKadikoy,
      turkeyIstanbulPprovinceKagithane,
      turkeyIstanbulPprovinceKartal,
      turkeyIstanbulPprovinceKucukcekmece,
      turkeyIstanbulPprovinceMaltepe,
      turkeyIstanbulPprovincePendik,
      turkeyIstanbulPprovinceSancaktepe,
      turkeyIstanbulPprovinceSariyer,
      turkeyIstanbulPprovinceSile,
      turkeyIstanbulPprovinceSilivri,
      turkeyIstanbulPprovinceSisli,
      turkeyIstanbulPprovinceSultanbeyli,
      turkeyIstanbulPprovinceSultangazi,
      turkeyIstanbulPprovinceTuzla,
      turkeyIstanbulPprovinceUmraniye,
      turkeyIstanbulPprovinceUskudar,
      turkeyIstanbulPprovinceZeytinburnu
    ]);
const Region turkeyIzmirPprovince = Region(
    id: 2205,
    parentId: 225,
    longitude: 27.2676116,
    latitude: 38.3591693,
    name: "İzmir",
    type: "province",
    stateCode: "35",
    cities: [
      turkeyIzmirPprovinceAlacati,
      turkeyIzmirPprovinceAliaga,
      turkeyIzmirPprovinceBademli,
      turkeyIzmirPprovinceBalcova,
      turkeyIzmirPprovinceBayindir,
      turkeyIzmirPprovinceBayrakli,
      turkeyIzmirPprovinceBelevi,
      turkeyIzmirPprovinceBergama,
      turkeyIzmirPprovinceBeydag,
      turkeyIzmirPprovinceBornova,
      turkeyIzmirPprovinceBuca,
      turkeyIzmirPprovinceCandarli,
      turkeyIzmirPprovinceCayli,
      turkeyIzmirPprovinceCesme,
      turkeyIzmirPprovinceCigli,
      turkeyIzmirPprovinceDikili,
      turkeyIzmirPprovinceFoca,
      turkeyIzmirPprovinceGaziemir,
      turkeyIzmirPprovinceGokcen,
      turkeyIzmirPprovinceGuzelbahce,
      turkeyIzmirPprovinceIzmir,
      turkeyIzmirPprovinceKarabaglar,
      turkeyIzmirPprovinceKaraburun,
      turkeyIzmirPprovinceKarsiyakaIlcesi,
      turkeyIzmirPprovinceKaymakci,
      turkeyIzmirPprovinceKemalpasa,
      turkeyIzmirPprovinceKiraz,
      turkeyIzmirPprovinceKinik,
      turkeyIzmirPprovinceKonak,
      turkeyIzmirPprovinceKonakli,
      turkeyIzmirPprovinceMenderes,
      turkeyIzmirPprovinceMenemen,
      turkeyIzmirPprovinceNarlidere,
      turkeyIzmirPprovinceOdemis,
      turkeyIzmirPprovinceOzdere,
      turkeyIzmirPprovinceSeferihisar,
      turkeyIzmirPprovinceSelcuk,
      turkeyIzmirPprovinceTire,
      turkeyIzmirPprovinceTorbali,
      turkeyIzmirPprovinceUrla,
      turkeyIzmirPprovinceYenifoca,
      turkeyIzmirPprovinceYenisakran,
      turkeyIzmirPprovinceZeytindag
    ]);
const Region turkeyKahramanmarasPprovince = Region(
    id: 2227,
    parentId: 225,
    longitude: 36.954107,
    latitude: 37.7503036,
    name: "Kahramanmaraş",
    type: "province",
    stateCode: "46",
    cities: [
      turkeyKahramanmarasPprovinceAfsin,
      turkeyKahramanmarasPprovinceAndirin,
      turkeyKahramanmarasPprovinceCaglayancerit,
      turkeyKahramanmarasPprovinceCeleyke,
      turkeyKahramanmarasPprovinceDulkadiroglu,
      turkeyKahramanmarasPprovinceEkinozuIlcesi,
      turkeyKahramanmarasPprovinceElbistan,
      turkeyKahramanmarasPprovinceGoksun,
      turkeyKahramanmarasPprovinceKahramanmaras,
      turkeyKahramanmarasPprovinceNurhak,
      turkeyKahramanmarasPprovinceOnikisubat,
      turkeyKahramanmarasPprovincePazarcik,
      turkeyKahramanmarasPprovinceSuleymanli,
      turkeyKahramanmarasPprovinceTurkogluIlcesi
    ]);
const Region turkeyKarabukPprovince = Region(
    id: 2223,
    parentId: 225,
    longitude: 32.7417419,
    latitude: 41.187489,
    name: "Karabük",
    type: "province",
    stateCode: "78",
    cities: [
      turkeyKarabukPprovinceEflani,
      turkeyKarabukPprovinceEskipazarIlcesi,
      turkeyKarabukPprovinceGozyeri,
      turkeyKarabukPprovinceKarabuk,
      turkeyKarabukPprovinceOvacikIlcesi,
      turkeyKarabukPprovinceSafranbolu,
      turkeyKarabukPprovinceYenice
    ]);
const Region turkeyKaramanPprovince = Region(
    id: 2184,
    parentId: 225,
    longitude: 33.617577,
    latitude: 37.2436336,
    name: "Karaman",
    type: "province",
    stateCode: "70",
    cities: [
      turkeyKaramanPprovinceAyranciIlcesi,
      turkeyKaramanPprovinceBasyayla,
      turkeyKaramanPprovinceErmenek,
      turkeyKaramanPprovinceInonu,
      turkeyKaramanPprovinceKaraman,
      turkeyKaramanPprovinceKazimkarabekir,
      turkeyKaramanPprovinceSariveliler
    ]);
const Region turkeyKarsPprovince = Region(
    id: 2208,
    parentId: 225,
    longitude: 42.9919527,
    latitude: 40.2807636,
    name: "Kars",
    type: "province",
    stateCode: "36",
    cities: [
      turkeyKarsPprovinceAkyaka,
      turkeyKarsPprovinceArpacay,
      turkeyKarsPprovinceDigorIlcesi,
      turkeyKarsPprovinceKagizman,
      turkeyKarsPprovinceKars,
      turkeyKarsPprovinceSarikamis,
      turkeyKarsPprovinceSelim,
      turkeyKarsPprovinceSusuz
    ]);
const Region turkeyKastamonuPprovince = Region(
    id: 2197,
    parentId: 225,
    longitude: 33.6998334,
    latitude: 41.4103863,
    name: "Kastamonu",
    type: "province",
    stateCode: "37",
    cities: [
      turkeyKastamonuPprovinceAbana,
      turkeyKastamonuPprovinceAgliIlcesi,
      turkeyKastamonuPprovinceArac,
      turkeyKastamonuPprovinceAzdavay,
      turkeyKastamonuPprovinceBozkurt,
      turkeyKastamonuPprovinceCatalzeytinIlcesi,
      turkeyKastamonuPprovinceCide,
      turkeyKastamonuPprovinceDaday,
      turkeyKastamonuPprovinceDevrekani,
      turkeyKastamonuPprovinceDoganyurt,
      turkeyKastamonuPprovinceHanonu,
      turkeyKastamonuPprovinceIhsangazi,
      turkeyKastamonuPprovinceInebolu,
      turkeyKastamonuPprovinceKastamonu,
      turkeyKastamonuPprovinceKure,
      turkeyKastamonuPprovincePinarbasi,
      turkeyKastamonuPprovinceSenpazarIlcesi,
      turkeyKastamonuPprovinceSeydiler,
      turkeyKastamonuPprovinceTaskopru,
      turkeyKastamonuPprovinceTosya
    ]);
const Region turkeyKayseriPprovince = Region(
    id: 2200,
    parentId: 225,
    longitude: 35.7406882,
    latitude: 38.6256854,
    name: "Kayseri",
    type: "province",
    stateCode: "38",
    cities: [
      turkeyKayseriPprovinceAkkisla,
      turkeyKayseriPprovinceBunyan,
      turkeyKayseriPprovinceDeveli,
      turkeyKayseriPprovinceFelahiye,
      turkeyKayseriPprovinceHacilar,
      turkeyKayseriPprovinceIncesu,
      turkeyKayseriPprovinceKayseri,
      turkeyKayseriPprovinceKocasinan,
      turkeyKayseriPprovinceMelikgazi,
      turkeyKayseriPprovinceOzvatanIlcesi,
      turkeyKayseriPprovincePinarbasi,
      turkeyKayseriPprovinceSarioglan,
      turkeyKayseriPprovinceSariz,
      turkeyKayseriPprovinceTalas,
      turkeyKayseriPprovinceTomarza,
      turkeyKayseriPprovinceYahyali,
      turkeyKayseriPprovinceYahyali,
      turkeyKayseriPprovinceYesilhisar
    ]);
const Region turkeyKilisPprovince = Region(
    id: 2154,
    parentId: 225,
    longitude: 37.1687339,
    latitude: 36.8204775,
    name: "Kilis",
    type: "province",
    stateCode: "79",
    cities: [
      turkeyKilisPprovinceElbeyli,
      turkeyKilisPprovinceKilis,
      turkeyKilisPprovinceMusabeyli,
      turkeyKilisPprovincePolateliIlcesi
    ]);
const Region turkeyKirikkalePprovince = Region(
    id: 2178,
    parentId: 225,
    longitude: 33.7555248,
    latitude: 39.8876878,
    name: "Kırıkkale",
    type: "province",
    stateCode: "71",
    cities: [
      turkeyKirikkalePprovinceBahsiliIlcesi,
      turkeyKirikkalePprovinceBaliseyh,
      turkeyKirikkalePprovinceCelebiIlcesi,
      turkeyKirikkalePprovinceDelice,
      turkeyKirikkalePprovinceKarakecili,
      turkeyKirikkalePprovinceKeskin,
      turkeyKirikkalePprovinceKirikkale,
      turkeyKirikkalePprovinceSulakyurt,
      turkeyKirikkalePprovinceYahsihanIlcesi
    ]);
const Region turkeyKirklareliPprovince = Region(
    id: 2176,
    parentId: 225,
    longitude: 27.483839,
    latitude: 41.7259795,
    name: "Kırklareli",
    type: "province",
    stateCode: "39",
    cities: [
      turkeyKirklareliPprovinceBabaeski,
      turkeyKirklareliPprovinceDemirkoyIlcesi,
      turkeyKirklareliPprovinceKirklareli,
      turkeyKirklareliPprovinceKofcaz,
      turkeyKirklareliPprovinceLuleburgazIlcesi,
      turkeyKirklareliPprovincePehlivankoy,
      turkeyKirklareliPprovincePinarhisar,
      turkeyKirklareliPprovinceUskup,
      turkeyKirklareliPprovinceVize
    ]);
const Region turkeyKirsehirPprovince = Region(
    id: 2180,
    parentId: 225,
    longitude: 33.9750018,
    latitude: 39.2268905,
    name: "Kırşehir",
    type: "province",
    stateCode: "40",
    cities: [
      turkeyKirsehirPprovinceAkcakentIlcesi,
      turkeyKirsehirPprovinceAkpinar,
      turkeyKirsehirPprovinceBoztepeIlcesi,
      turkeyKirsehirPprovinceCicekdagi,
      turkeyKirsehirPprovinceKaman,
      turkeyKirsehirPprovinceKirsehir,
      turkeyKirsehirPprovinceMucur
    ]);
const Region turkeyKocaeliPprovince = Region(
    id: 2195,
    parentId: 225,
    longitude: 29.8815203,
    latitude: 40.8532704,
    name: "Kocaeli",
    type: "province",
    stateCode: "41",
    cities: [
      turkeyKocaeliPprovinceBahcecik,
      turkeyKocaeliPprovinceBalcik,
      turkeyKocaeliPprovinceBasiskele,
      turkeyKocaeliPprovinceCayirova,
      turkeyKocaeliPprovinceDarica,
      turkeyKocaeliPprovinceDerince,
      turkeyKocaeliPprovinceDilovasi,
      turkeyKocaeliPprovinceGebze,
      turkeyKocaeliPprovinceGolcuk,
      turkeyKocaeliPprovinceHalidere,
      turkeyKocaeliPprovinceIhsaniye,
      turkeyKocaeliPprovinceIzmit,
      turkeyKocaeliPprovinceKandira,
      turkeyKocaeliPprovinceKaramursel,
      turkeyKocaeliPprovinceKarsiyaka,
      turkeyKocaeliPprovinceKartepe,
      turkeyKocaeliPprovinceKefken,
      turkeyKocaeliPprovinceKorfez,
      turkeyKocaeliPprovinceKosekoy,
      turkeyKocaeliPprovinceKullar,
      turkeyKocaeliPprovinceTavsancil,
      turkeyKocaeliPprovinceTavsanli,
      turkeyKocaeliPprovinceUlasli,
      turkeyKocaeliPprovinceYalakdere,
      turkeyKocaeliPprovinceYuvacik
    ]);
const Region turkeyKonyaPprovince = Region(
    id: 2171,
    parentId: 225,
    longitude: 32.7181375,
    latitude: 37.9838134,
    name: "Konya",
    type: "province",
    stateCode: "42",
    cities: [
      turkeyKonyaPprovinceAhirliIlcesi,
      turkeyKonyaPprovinceAkorenIlcesi,
      turkeyKonyaPprovinceAksehir,
      turkeyKonyaPprovinceAltinekin,
      turkeyKonyaPprovinceBeysehir,
      turkeyKonyaPprovinceBozkir,
      turkeyKonyaPprovinceCatalhoyuk,
      turkeyKonyaPprovinceCeltikIlcesi,
      turkeyKonyaPprovinceCihanbeyli,
      turkeyKonyaPprovinceCihanbeyliDistrict,
      turkeyKonyaPprovinceCumra,
      turkeyKonyaPprovinceDerbent,
      turkeyKonyaPprovinceDerebucak,
      turkeyKonyaPprovinceDoganhisar,
      turkeyKonyaPprovinceEmirgazi,
      turkeyKonyaPprovinceEregli,
      turkeyKonyaPprovinceGuneysinirIlcesi,
      turkeyKonyaPprovinceHadim,
      turkeyKonyaPprovinceHalkapinar,
      turkeyKonyaPprovinceHuyuk,
      turkeyKonyaPprovinceIlgin,
      turkeyKonyaPprovinceKadinhani,
      turkeyKonyaPprovinceKarapinar,
      turkeyKonyaPprovinceKaratay,
      turkeyKonyaPprovinceKonya,
      turkeyKonyaPprovinceKulu,
      turkeyKonyaPprovinceKuyulusebil,
      turkeyKonyaPprovinceMeramIlcesi,
      turkeyKonyaPprovinceOvakavagi,
      turkeyKonyaPprovinceSarayonu,
      turkeyKonyaPprovinceSelcuklu,
      turkeyKonyaPprovinceSeydisehir,
      turkeyKonyaPprovinceTaskent,
      turkeyKonyaPprovinceTuzlukcu,
      turkeyKonyaPprovinceYalihuyuk,
      turkeyKonyaPprovinceYarma,
      turkeyKonyaPprovinceYeniceoba,
      turkeyKonyaPprovinceYunak
    ]);
const Region turkeyKutahyaPprovince = Region(
    id: 2149,
    parentId: 225,
    longitude: 29.6035495,
    latitude: 39.358137,
    name: "Kütahya",
    type: "province",
    stateCode: "43",
    cities: [
      turkeyKutahyaPprovinceAltintasIlcesi,
      turkeyKutahyaPprovinceAslanapa,
      turkeyKutahyaPprovinceCavdarhisarIlcesi,
      turkeyKutahyaPprovinceDomanic,
      turkeyKutahyaPprovinceDumlupinar,
      turkeyKutahyaPprovinceEmet,
      turkeyKutahyaPprovinceGediz,
      turkeyKutahyaPprovinceHisarcikIlcesi,
      turkeyKutahyaPprovinceKutahya,
      turkeyKutahyaPprovincePazarlar,
      turkeyKutahyaPprovinceSaphane,
      turkeyKutahyaPprovinceSimav,
      turkeyKutahyaPprovinceTavsanli
    ]);
const Region turkeyMalatyaPprovince = Region(
    id: 2158,
    parentId: 225,
    longitude: 37.9536298,
    latitude: 38.4015057,
    name: "Malatya",
    type: "province",
    stateCode: "44",
    cities: [
      turkeyMalatyaPprovinceAkcadag,
      turkeyMalatyaPprovinceArapgir,
      turkeyMalatyaPprovinceArguvan,
      turkeyMalatyaPprovinceBattalgazi,
      turkeyMalatyaPprovinceDarende,
      turkeyMalatyaPprovinceDogansehir,
      turkeyMalatyaPprovinceDoganyol,
      turkeyMalatyaPprovinceHekimhan,
      turkeyMalatyaPprovinceKale,
      turkeyMalatyaPprovinceKuluncak,
      turkeyMalatyaPprovinceMalatya,
      turkeyMalatyaPprovincePuturge,
      turkeyMalatyaPprovinceYazihan,
      turkeyMalatyaPprovinceYesilyurt
    ]);
const Region turkeyManisaPprovince = Region(
    id: 2198,
    parentId: 225,
    longitude: 28.1122679,
    latitude: 38.8419373,
    name: "Manisa",
    type: "province",
    stateCode: "45",
    cities: [
      turkeyManisaPprovinceAhmetli,
      turkeyManisaPprovinceAkhisar,
      turkeyManisaPprovinceAlasehir,
      turkeyManisaPprovinceDemirci,
      turkeyManisaPprovinceGolmarmara,
      turkeyManisaPprovinceGordes,
      turkeyManisaPprovinceKirkagac,
      turkeyManisaPprovinceKoprubasi,
      turkeyManisaPprovinceKula,
      turkeyManisaPprovinceManisa,
      turkeyManisaPprovinceSalihliIlcesi,
      turkeyManisaPprovinceSarigol,
      turkeyManisaPprovinceSaruhanli,
      turkeyManisaPprovinceSehzadeler,
      turkeyManisaPprovinceSelendi,
      turkeyManisaPprovinceSoma,
      turkeyManisaPprovinceTurgutluIlcesi,
      turkeyManisaPprovinceYunusemre,
      turkeyManisaPprovinceZeytinliova
    ]);
const Region turkeyMardinPprovince = Region(
    id: 2224,
    parentId: 225,
    longitude: 40.6196487,
    latitude: 37.3442929,
    name: "Mardin",
    type: "province",
    stateCode: "47",
    cities: [
      turkeyMardinPprovinceAcirli,
      turkeyMardinPprovinceAkarsu,
      turkeyMardinPprovinceAlakamis,
      turkeyMardinPprovinceAran,
      turkeyMardinPprovinceArtuklu,
      turkeyMardinPprovinceAvine,
      turkeyMardinPprovinceBaglica,
      turkeyMardinPprovinceBaristepe,
      turkeyMardinPprovinceBaskavak,
      turkeyMardinPprovinceCalpinar,
      turkeyMardinPprovinceCavuslu,
      turkeyMardinPprovinceCinatamiho,
      turkeyMardinPprovinceCinaralti,
      turkeyMardinPprovinceCiplak,
      turkeyMardinPprovinceDara,
      turkeyMardinPprovinceDargecit,
      turkeyMardinPprovinceDereyani,
      turkeyMardinPprovinceDerikIlcesi,
      turkeyMardinPprovinceDuruca,
      turkeyMardinPprovinceEbish,
      turkeyMardinPprovinceEsme,
      turkeyMardinPprovinceEymirli,
      turkeyMardinPprovinceGelinkaya,
      turkeyMardinPprovinceGulveren,
      turkeyMardinPprovinceGyundyukoru,
      turkeyMardinPprovinceHaberli,
      turkeyMardinPprovinceKabala,
      turkeyMardinPprovinceKaralar,
      turkeyMardinPprovinceKavsan,
      turkeyMardinPprovinceKayalipinar,
      turkeyMardinPprovinceKaynakkaya,
      turkeyMardinPprovinceKindirip,
      turkeyMardinPprovinceKilavuz,
      turkeyMardinPprovinceKiziltepe,
      turkeyMardinPprovinceKumlu,
      turkeyMardinPprovinceKutlubey,
      turkeyMardinPprovinceMardin,
      turkeyMardinPprovinceMardinMerkez,
      turkeyMardinPprovinceMazidagi,
      turkeyMardinPprovinceMidyat,
      turkeyMardinPprovinceNusaybin,
      turkeyMardinPprovinceOmerli,
      turkeyMardinPprovinceOrtaca,
      turkeyMardinPprovinceOrtakoy,
      turkeyMardinPprovinceOyali,
      turkeyMardinPprovinceOzbek,
      turkeyMardinPprovincePinardere,
      turkeyMardinPprovinceReshidi,
      turkeyMardinPprovinceSavur,
      turkeyMardinPprovinceSelah,
      turkeyMardinPprovinceSenocak,
      turkeyMardinPprovinceSenyurt,
      turkeyMardinPprovinceSeri,
      turkeyMardinPprovinceSerkan,
      turkeyMardinPprovinceSivrice,
      turkeyMardinPprovinceTeffi,
      turkeyMardinPprovinceTelminar,
      turkeyMardinPprovinceTepealti,
      turkeyMardinPprovinceToptepe,
      turkeyMardinPprovinceYayli,
      turkeyMardinPprovinceYayvantepe,
      turkeyMardinPprovinceYesilalan,
      turkeyMardinPprovinceYesilli,
      turkeyMardinPprovinceYolbasi
    ]);
const Region turkeyMersinPprovince = Region(
    id: 2156,
    parentId: 225,
    longitude: 34.641475,
    latitude: 36.8120858,
    name: "Mersin",
    type: "province",
    stateCode: "33",
    cities: [
      turkeyMersinPprovinceAkdeniz,
      turkeyMersinPprovinceAkdere,
      turkeyMersinPprovinceAnamur,
      turkeyMersinPprovinceAydincik,
      turkeyMersinPprovinceBozyazi,
      turkeyMersinPprovinceCamliyaylaIlcesi,
      turkeyMersinPprovinceElvanli,
      turkeyMersinPprovinceErdemli,
      turkeyMersinPprovinceGulnar,
      turkeyMersinPprovinceKocahasanli,
      turkeyMersinPprovinceMersin,
      turkeyMersinPprovinceMezitliIlcesi,
      turkeyMersinPprovinceMut,
      turkeyMersinPprovincePinarbasi,
      turkeyMersinPprovinceSilifke,
      turkeyMersinPprovinceTarsus,
      turkeyMersinPprovinceToroslar,
      turkeyMersinPprovinceYenisehir
    ]);
const Region turkeyMuglaPprovince = Region(
    id: 2182,
    parentId: 225,
    longitude: 28.4863963,
    latitude: 37.1835819,
    name: "Muğla",
    type: "province",
    stateCode: "48",
    cities: [
      turkeyMuglaPprovinceBayir,
      turkeyMuglaPprovinceBodrum,
      turkeyMuglaPprovinceBozarmut,
      turkeyMuglaPprovinceDalaman,
      turkeyMuglaPprovinceDalyan,
      turkeyMuglaPprovinceDatca,
      turkeyMuglaPprovinceFethiye,
      turkeyMuglaPprovinceGocek,
      turkeyMuglaPprovinceGuvercinlik,
      turkeyMuglaPprovinceKargi,
      turkeyMuglaPprovinceKavaklidere,
      turkeyMuglaPprovinceKoycegizIlcesi,
      turkeyMuglaPprovinceMarmaris,
      turkeyMuglaPprovinceMentese,
      turkeyMuglaPprovinceMilas,
      turkeyMuglaPprovinceMugla,
      turkeyMuglaPprovinceOludeniz,
      turkeyMuglaPprovinceOrtaca,
      turkeyMuglaPprovinceSarigerme,
      turkeyMuglaPprovinceSeydikemer,
      turkeyMuglaPprovinceTurgut,
      turkeyMuglaPprovinceTurgutreis,
      turkeyMuglaPprovinceUla,
      turkeyMuglaPprovinceYalikavak,
      turkeyMuglaPprovinceYaniklar,
      turkeyMuglaPprovinceYatagan
    ]);
const Region turkeyMusPprovince = Region(
    id: 2162,
    parentId: 225,
    longitude: 41.7538931,
    latitude: 38.9461888,
    name: "Muş",
    type: "province",
    stateCode: "49",
    cities: [
      turkeyMusPprovinceBulanik,
      turkeyMusPprovinceHaskoy,
      turkeyMusPprovinceKorkut,
      turkeyMusPprovinceMalazgirt,
      turkeyMusPprovinceMerkez,
      turkeyMusPprovinceMus,
      turkeyMusPprovinceVarto
    ]);
const Region turkeyNevsehirPprovince = Region(
    id: 2196,
    parentId: 225,
    longitude: 34.6856509,
    latitude: 38.6939399,
    name: "Nevşehir",
    type: "province",
    stateCode: "50",
    cities: [
      turkeyNevsehirPprovinceAcigol,
      turkeyNevsehirPprovinceAvanos,
      turkeyNevsehirPprovinceDerinkuyu,
      turkeyNevsehirPprovinceGoreme,
      turkeyNevsehirPprovinceGulsehir,
      turkeyNevsehirPprovinceHacibektas,
      turkeyNevsehirPprovinceKozakliIlcesi,
      turkeyNevsehirPprovinceMerkez,
      turkeyNevsehirPprovinceNevsehir,
      turkeyNevsehirPprovinceUrgup
    ]);
const Region turkeyNigdePprovince = Region(
    id: 2189,
    parentId: 225,
    longitude: 34.6856509,
    latitude: 38.0993086,
    name: "Niğde",
    type: "province",
    stateCode: "51",
    cities: [
      turkeyNigdePprovinceAltunhisar,
      turkeyNigdePprovinceBor,
      turkeyNigdePprovinceCamardiIlcesi,
      turkeyNigdePprovinceCiftlik,
      turkeyNigdePprovinceNigde,
      turkeyNigdePprovinceUlukisla
    ]);
const Region turkeyOrduPprovince = Region(
    id: 2174,
    parentId: 225,
    longitude: 37.3899005,
    latitude: 40.799058,
    name: "Ordu",
    type: "province",
    stateCode: "52",
    cities: [
      turkeyOrduPprovinceAkkus,
      turkeyOrduPprovinceAltinordu,
      turkeyOrduPprovinceAybastiIlcesi,
      turkeyOrduPprovinceCamas,
      turkeyOrduPprovinceCatalpinarIlcesi,
      turkeyOrduPprovinceCaybasiIlcesi,
      turkeyOrduPprovinceFatsa,
      turkeyOrduPprovinceGolkoyIlcesi,
      turkeyOrduPprovinceGulyaliIlcesi,
      turkeyOrduPprovinceGurgentepe,
      turkeyOrduPprovinceIkizce,
      turkeyOrduPprovinceKabaduz,
      turkeyOrduPprovinceKabatas,
      turkeyOrduPprovinceKorgan,
      turkeyOrduPprovinceKumru,
      turkeyOrduPprovinceMesudiye,
      turkeyOrduPprovinceOrdu,
      turkeyOrduPprovincePersembe,
      turkeyOrduPprovincePirazizIlcesi,
      turkeyOrduPprovinceUlubey,
      turkeyOrduPprovinceUnyeIlcesi
    ]);
const Region turkeyOsmaniyePprovince = Region(
    id: 2214,
    parentId: 225,
    longitude: 36.1762615,
    latitude: 37.2130258,
    name: "Osmaniye",
    type: "province",
    stateCode: "80",
    cities: [
      turkeyOsmaniyePprovinceBahceIlcesi,
      turkeyOsmaniyePprovinceDuziciIlcesi,
      turkeyOsmaniyePprovinceHasanbeyli,
      turkeyOsmaniyePprovinceKadirli,
      turkeyOsmaniyePprovinceOsmaniye,
      turkeyOsmaniyePprovinceSumbasIlcesi,
      turkeyOsmaniyePprovinceToprakkale
    ]);
const Region turkeyRizePprovince = Region(
    id: 2219,
    parentId: 225,
    longitude: 40.9226985,
    latitude: 40.9581497,
    name: "Rize",
    type: "province",
    stateCode: "53",
    cities: [
      turkeyRizePprovinceArdesen,
      turkeyRizePprovinceCayeli,
      turkeyRizePprovinceFindikli,
      turkeyRizePprovinceGuneysu,
      turkeyRizePprovinceHemsinIlcesi,
      turkeyRizePprovinceIkizdereIlcesi,
      turkeyRizePprovinceIyidere,
      turkeyRizePprovinceKalkandere,
      turkeyRizePprovinceNurluca,
      turkeyRizePprovincePazar,
      turkeyRizePprovinceRize
    ]);
const Region turkeySakaryaPprovince = Region(
    id: 2150,
    parentId: 225,
    longitude: 30.405954,
    latitude: 40.788855,
    name: "Sakarya",
    type: "province",
    stateCode: "54",
    cities: [
      turkeySakaryaPprovinceAdapazari,
      turkeySakaryaPprovinceAkyazi,
      turkeySakaryaPprovinceArifiye,
      turkeySakaryaPprovinceErenler,
      turkeySakaryaPprovinceFerizli,
      turkeySakaryaPprovinceGeyve,
      turkeySakaryaPprovinceHendek,
      turkeySakaryaPprovinceKarapurcek,
      turkeySakaryaPprovinceKarasuIlcesi,
      turkeySakaryaPprovinceKarasuMahallesi,
      turkeySakaryaPprovinceKaynarca,
      turkeySakaryaPprovinceKocaali,
      turkeySakaryaPprovincePamukova,
      turkeySakaryaPprovinceSapanca,
      turkeySakaryaPprovinceSerdivan,
      turkeySakaryaPprovinceSogutlu,
      turkeySakaryaPprovinceTarakli
    ]);
const Region turkeySamsunPprovince = Region(
    id: 2220,
    parentId: 225,
    longitude: 36.1322678,
    latitude: 41.1864859,
    name: "Samsun",
    type: "province",
    stateCode: "55",
    cities: [
      turkeySamsunPprovinceAlacamIlcesi,
      turkeySamsunPprovinceAsarcik,
      turkeySamsunPprovinceAtakum,
      turkeySamsunPprovinceAyvacik,
      turkeySamsunPprovinceBafra,
      turkeySamsunPprovinceCanik,
      turkeySamsunPprovinceCarsamba,
      turkeySamsunPprovinceHavza,
      turkeySamsunPprovinceIlkadim,
      turkeySamsunPprovinceKavak,
      turkeySamsunPprovinceLadik,
      turkeySamsunPprovinceOndokuzmayisIlcesi,
      turkeySamsunPprovinceSalipazariIlcesi,
      turkeySamsunPprovinceSamsun,
      turkeySamsunPprovinceTekkekoy,
      turkeySamsunPprovinceTerme,
      turkeySamsunPprovinceVezirkopru,
      turkeySamsunPprovinceYakakent
    ]);
const Region turkeySanliurfaPprovince = Region(
    id: 2183,
    parentId: 225,
    longitude: 39.1543677,
    latitude: 37.3569102,
    name: "Şanlıurfa",
    type: "province",
    stateCode: "63",
    cities: [
      turkeySanliurfaPprovinceAkcakale,
      turkeySanliurfaPprovinceAkdiken,
      turkeySanliurfaPprovinceAsagiBegdes,
      turkeySanliurfaPprovinceBirecik,
      turkeySanliurfaPprovinceBozova,
      turkeySanliurfaPprovinceBulutlu,
      turkeySanliurfaPprovinceCeylanpinar,
      turkeySanliurfaPprovinceDorumali,
      turkeySanliurfaPprovinceEyyubiye,
      turkeySanliurfaPprovinceGuneren,
      turkeySanliurfaPprovinceHalfeti,
      turkeySanliurfaPprovinceHaliliye,
      turkeySanliurfaPprovinceHankoy,
      turkeySanliurfaPprovinceHarran,
      turkeySanliurfaPprovinceHilvan,
      turkeySanliurfaPprovinceIsiklar,
      turkeySanliurfaPprovinceKarakopru,
      turkeySanliurfaPprovinceKoyunluca,
      turkeySanliurfaPprovinceKucukkendirci,
      turkeySanliurfaPprovinceMagarali,
      turkeySanliurfaPprovinceMeydankapi,
      turkeySanliurfaPprovinceMinare,
      turkeySanliurfaPprovinceMuratli,
      turkeySanliurfaPprovinceOncul,
      turkeySanliurfaPprovincePekmezli,
      turkeySanliurfaPprovinceSanliurfa,
      turkeySanliurfaPprovinceSeksenoren,
      turkeySanliurfaPprovinceSiverek,
      turkeySanliurfaPprovinceSuruc,
      turkeySanliurfaPprovinceViransehir,
      turkeySanliurfaPprovinceYukariTasyalak
    ]);
const Region turkeySiirtPprovince = Region(
    id: 2207,
    parentId: 225,
    longitude: 42.1494523,
    latitude: 37.8658862,
    name: "Siirt",
    type: "province",
    stateCode: "56",
    cities: [
      turkeySiirtPprovinceBaykan,
      turkeySiirtPprovinceCivankan,
      turkeySiirtPprovinceDoganca,
      turkeySiirtPprovinceDogankoy,
      turkeySiirtPprovinceEruh,
      turkeySiirtPprovinceGokbudak,
      turkeySiirtPprovinceGokcekoru,
      turkeySiirtPprovinceGolgelikonak,
      turkeySiirtPprovinceGozpinar,
      turkeySiirtPprovinceGulecler,
      turkeySiirtPprovinceKayabaglar,
      turkeySiirtPprovinceKurtalan,
      turkeySiirtPprovinceLodi,
      turkeySiirtPprovinceOkcular,
      turkeySiirtPprovincePalamutlu,
      turkeySiirtPprovincePervari,
      turkeySiirtPprovinceSerhatta,
      turkeySiirtPprovinceSiirt,
      turkeySiirtPprovinceSirvan,
      turkeySiirtPprovinceTaliban,
      turkeySiirtPprovinceTasli,
      turkeySiirtPprovinceTillo
    ]);
const Region turkeySinopPprovince = Region(
    id: 4854,
    parentId: 225,
    longitude: 34.8580532,
    latitude: 41.5594749,
    name: "Sinop",
    type: "province",
    stateCode: "57",
    cities: [
      turkeySinopPprovinceBoyabat,
      turkeySinopPprovinceDikmen,
      turkeySinopPprovinceDuragan,
      turkeySinopPprovinceErfelek,
      turkeySinopPprovinceGerze,
      turkeySinopPprovinceMerkez,
      turkeySinopPprovinceSarayduzu,
      turkeySinopPprovinceSinop,
      turkeySinopPprovinceTurkeli
    ]);
const Region turkeySivasPprovince = Region(
    id: 2181,
    parentId: 225,
    longitude: 37.1294497,
    latitude: 39.4488039,
    name: "Sivas",
    type: "province",
    stateCode: "58",
    cities: [
      turkeySivasPprovinceAkincilar,
      turkeySivasPprovinceAksu,
      turkeySivasPprovinceAltinyayla,
      turkeySivasPprovinceDivrigi,
      turkeySivasPprovinceDogansar,
      turkeySivasPprovinceGemerek,
      turkeySivasPprovinceGolova,
      turkeySivasPprovinceGurun,
      turkeySivasPprovinceHafik,
      turkeySivasPprovinceImranli,
      turkeySivasPprovinceKangal,
      turkeySivasPprovinceKoyulhisar,
      turkeySivasPprovinceMerkez,
      turkeySivasPprovinceSarkisla,
      turkeySivasPprovinceSivas,
      turkeySivasPprovinceSusehri,
      turkeySivasPprovinceUlas,
      turkeySivasPprovinceYildizeliIlcesi,
      turkeySivasPprovinceZara
    ]);
const Region turkeySirnakPprovince = Region(
    id: 2225,
    parentId: 225,
    longitude: 42.4918338,
    latitude: 37.4187481,
    name: "Şırnak",
    type: "province",
    stateCode: "73",
    cities: [
      turkeySirnakPprovinceAndac,
      turkeySirnakPprovinceBaglica,
      turkeySirnakPprovinceBalli,
      turkeySirnakPprovinceBalveren,
      turkeySirnakPprovinceBaraniferho,
      turkeySirnakPprovinceBasaran,
      turkeySirnakPprovinceBecuh,
      turkeySirnakPprovinceBeytussebap,
      turkeySirnakPprovinceBisbin,
      turkeySirnakPprovinceBogazoren,
      turkeySirnakPprovinceBostanci,
      turkeySirnakPprovinceBozalan,
      turkeySirnakPprovinceCaliskan,
      turkeySirnakPprovinceCardakli,
      turkeySirnakPprovinceCizre,
      turkeySirnakPprovinceDicle,
      turkeySirnakPprovinceDoruklu,
      turkeySirnakPprovinceDuzova,
      turkeySirnakPprovinceGirikbedro,
      turkeySirnakPprovinceGuclukonakIlcesi,
      turkeySirnakPprovinceHilal,
      turkeySirnakPprovinceIdil,
      turkeySirnakPprovinceKizilsu,
      turkeySirnakPprovinceKumcati,
      turkeySirnakPprovinceMezraa,
      turkeySirnakPprovinceOrtabag,
      turkeySirnakPprovinceOrtakoy,
      turkeySirnakPprovincePinarbasi,
      turkeySirnakPprovinceRazvalinyAyinvan,
      turkeySirnakPprovinceSenoba,
      turkeySirnakPprovinceSilopi,
      turkeySirnakPprovinceSirnak,
      turkeySirnakPprovinceSulak,
      turkeySirnakPprovinceTililan,
      turkeySirnakPprovinceUludere,
      turkeySirnakPprovinceUzungecit,
      turkeySirnakPprovinceYemisli,
      turkeySirnakPprovinceYenikoy
    ]);
const Region turkeyTekirdagPprovince = Region(
    id: 2167,
    parentId: 225,
    longitude: 27.2676116,
    latitude: 41.1121227,
    name: "Tekirdağ",
    type: "province",
    stateCode: "59",
    cities: [
      turkeyTekirdagPprovinceCerkezkoy,
      turkeyTekirdagPprovinceCorlu,
      turkeyTekirdagPprovinceErgene,
      turkeyTekirdagPprovinceHayrabolu,
      turkeyTekirdagPprovinceKapakli,
      turkeyTekirdagPprovinceKumbag,
      turkeyTekirdagPprovinceMalkara,
      turkeyTekirdagPprovinceMarmaraEreglisi,
      turkeyTekirdagPprovinceMarmaracik,
      turkeyTekirdagPprovinceMuratliIlcesi,
      turkeyTekirdagPprovinceSaray,
      turkeyTekirdagPprovinceSarkoyIlcesi,
      turkeyTekirdagPprovinceSuleymanpasa,
      turkeyTekirdagPprovinceSultankoy,
      turkeyTekirdagPprovinceTekirdag,
      turkeyTekirdagPprovinceVelimese
    ]);
const Region turkeyTokatPprovince = Region(
    id: 2199,
    parentId: 225,
    longitude: 36.6251863,
    latitude: 40.3902713,
    name: "Tokat",
    type: "province",
    stateCode: "60",
    cities: [
      turkeyTokatPprovinceAlmus,
      turkeyTokatPprovinceArtova,
      turkeyTokatPprovinceBasciftlik,
      turkeyTokatPprovinceErbaa,
      turkeyTokatPprovinceNiksar,
      turkeyTokatPprovincePazar,
      turkeyTokatPprovinceResadiye,
      turkeyTokatPprovinceSulusaray,
      turkeyTokatPprovinceTokat,
      turkeyTokatPprovinceTurhal,
      turkeyTokatPprovinceYesilyurtIlcesi,
      turkeyTokatPprovinceZile
    ]);
const Region turkeyTrabzonPprovince = Region(
    id: 2206,
    parentId: 225,
    longitude: 39.5847944,
    latitude: 40.799241,
    name: "Trabzon",
    type: "province",
    stateCode: "61",
    cities: [
      turkeyTrabzonPprovinceAkcaabat,
      turkeyTrabzonPprovinceArakli,
      turkeyTrabzonPprovinceArsin,
      turkeyTrabzonPprovinceBesikduzu,
      turkeyTrabzonPprovinceCarsibasi,
      turkeyTrabzonPprovinceCaykara,
      turkeyTrabzonPprovinceDernekpazari,
      turkeyTrabzonPprovinceDuzkoy,
      turkeyTrabzonPprovinceHayrat,
      turkeyTrabzonPprovinceKoprubasi,
      turkeyTrabzonPprovinceMacka,
      turkeyTrabzonPprovinceOf,
      turkeyTrabzonPprovinceOrtahisar,
      turkeyTrabzonPprovinceSalpazari,
      turkeyTrabzonPprovinceSurmene,
      turkeyTrabzonPprovinceTonya,
      turkeyTrabzonPprovinceTrabzon,
      turkeyTrabzonPprovinceVakfikebir,
      turkeyTrabzonPprovinceYomra
    ]);
const Region turkeyTunceliPprovince = Region(
    id: 2192,
    parentId: 225,
    longitude: 39.4387778,
    latitude: 39.3073554,
    name: "Tunceli",
    type: "province",
    stateCode: "62",
    cities: [
      turkeyTunceliPprovinceCemisgezekIlcesi,
      turkeyTunceliPprovinceHozat,
      turkeyTunceliPprovinceMazgirt,
      turkeyTunceliPprovinceMerkez,
      turkeyTunceliPprovinceNazimiye,
      turkeyTunceliPprovinceNazimiyeIlcesi,
      turkeyTunceliPprovinceOvacik,
      turkeyTunceliPprovincePertek,
      turkeyTunceliPprovincePulumer,
      turkeyTunceliPprovincePulumurIlcesi,
      turkeyTunceliPprovinceTunceli
    ]);
const Region turkeyUsakPprovince = Region(
    id: 2201,
    parentId: 225,
    longitude: 29.2320784,
    latitude: 38.5431319,
    name: "Uşak",
    type: "province",
    stateCode: "64",
    cities: [
      turkeyUsakPprovinceBanaz,
      turkeyUsakPprovinceBolme,
      turkeyUsakPprovinceEsme,
      turkeyUsakPprovinceGullu,
      turkeyUsakPprovinceIlyasli,
      turkeyUsakPprovinceKarahalli,
      turkeyUsakPprovinceKizilcasogut,
      turkeyUsakPprovinceMerkez,
      turkeyUsakPprovinceSelcikler,
      turkeyUsakPprovinceSivasli,
      turkeyUsakPprovinceUlubey,
      turkeyUsakPprovinceUsak
    ]);
const Region turkeyVanPprovince = Region(
    id: 2152,
    parentId: 225,
    longitude: 43.7182787,
    latitude: 38.3679417,
    name: "Van",
    type: "province",
    stateCode: "65",
    cities: [
      turkeyVanPprovinceBahcesaray,
      turkeyVanPprovinceBaskale,
      turkeyVanPprovinceCaldiran,
      turkeyVanPprovinceCatakIlcesi,
      turkeyVanPprovinceEdremit,
      turkeyVanPprovinceErcis,
      turkeyVanPprovinceGevas,
      turkeyVanPprovinceGurpinar,
      turkeyVanPprovinceIpekyolu,
      turkeyVanPprovinceKonalga,
      turkeyVanPprovinceMuradiye,
      turkeyVanPprovinceOzalp,
      turkeyVanPprovinceSaray,
      turkeyVanPprovinceTuspa,
      turkeyVanPprovinceVan
    ]);
const Region turkeyYalovaPprovince = Region(
    id: 2218,
    parentId: 225,
    longitude: 29.2088303,
    latitude: 40.5775986,
    name: "Yalova",
    type: "province",
    stateCode: "77",
    cities: [
      turkeyYalovaPprovinceAltinova,
      turkeyYalovaPprovinceArmutluIlcesi,
      turkeyYalovaPprovinceCiftlikkoy,
      turkeyYalovaPprovinceCinarcik,
      turkeyYalovaPprovinceKadikoy,
      turkeyYalovaPprovinceKaytazdere,
      turkeyYalovaPprovinceKilic,
      turkeyYalovaPprovinceKocadere,
      turkeyYalovaPprovinceKorukoy,
      turkeyYalovaPprovinceTaskopru,
      turkeyYalovaPprovinceTermalIlcesi,
      turkeyYalovaPprovinceYalova
    ]);
const Region turkeyYozgatPprovince = Region(
    id: 2188,
    parentId: 225,
    longitude: 35.1077858,
    latitude: 39.7271979,
    name: "Yozgat",
    type: "province",
    stateCode: "66",
    cities: [
      turkeyYozgatPprovinceAkdagmadeni,
      turkeyYozgatPprovinceAydincik,
      turkeyYozgatPprovinceBogazliyanIlcesi,
      turkeyYozgatPprovinceCandirIlcesi,
      turkeyYozgatPprovinceCayiralan,
      turkeyYozgatPprovinceCekerek,
      turkeyYozgatPprovinceKadisehri,
      turkeyYozgatPprovinceSaraykent,
      turkeyYozgatPprovinceSarikaya,
      turkeyYozgatPprovinceSefaatliIlcesi,
      turkeyYozgatPprovinceSefaatli,
      turkeyYozgatPprovinceSorgun,
      turkeyYozgatPprovinceYenifakili,
      turkeyYozgatPprovinceYerkoy,
      turkeyYozgatPprovinceYozgat
    ]);
const Region turkeyZonguldakPprovince = Region(
    id: 2213,
    parentId: 225,
    longitude: 31.8598251,
    latitude: 41.3124917,
    name: "Zonguldak",
    type: "province",
    stateCode: "67",
    cities: [
      turkeyZonguldakPprovinceAlapli,
      turkeyZonguldakPprovinceCaycuma,
      turkeyZonguldakPprovinceDevrek,
      turkeyZonguldakPprovinceEregli,
      turkeyZonguldakPprovinceGokcebeyIlcesi,
      turkeyZonguldakPprovinceKilimli,
      turkeyZonguldakPprovinceKozlu,
      turkeyZonguldakPprovinceZonguldak
    ]);

const turkeyStates = <int, Region>{
  2212: turkeyAdanaPprovince,
  2155: turkeyAdiyamanPprovince,
  2179: turkeyAfyonkarahisarPprovince,
  2193: turkeyAgriPprovince,
  2210: turkeyAksarayPprovince,
  2161: turkeyAmasyaPprovince,
  2217: turkeyAnkaraPprovince,
  2169: turkeyAntalyaPprovince,
  2185: turkeyArdahanPprovince,
  2191: turkeyArtvinPprovince,
  2187: turkeyAydinPprovince,
  2175: turkeyBalikesirPprovince,
  2148: turkeyBartinPprovince,
  2194: turkeyBatmanPprovince,
  2177: turkeyBayburtPprovince,
  2221: turkeyBilecikPprovince,
  2153: turkeyBingolPprovince,
  2215: turkeyBitlisPprovince,
  2172: turkeyBoluPprovince,
  2209: turkeyBurdurPprovince,
  2163: turkeyBursaPprovince,
  2216: turkeyCanakkalePprovince,
  2168: turkeyCankiriPprovince,
  2173: turkeyCorumPprovince,
  2157: turkeyDenizliPprovince,
  2226: turkeyDiyarbakirPprovince,
  2202: turkeyDuzcePprovince,
  2151: turkeyEdirnePprovince,
  2159: turkeyElazigPprovince,
  2160: turkeyErzincanPprovince,
  2165: turkeyErzurumPprovince,
  2164: turkeyEskisehirPprovince,
  2203: turkeyGaziantepPprovince,
  2186: turkeyGiresunPprovince,
  2204: turkeyGumushanePprovince,
  2190: turkeyHakkariPprovince,
  2211: turkeyHatayPprovince,
  2166: turkeyIgdirPprovince,
  2222: turkeyIspartaPprovince,
  2170: turkeyIstanbulPprovince,
  2205: turkeyIzmirPprovince,
  2227: turkeyKahramanmarasPprovince,
  2223: turkeyKarabukPprovince,
  2184: turkeyKaramanPprovince,
  2208: turkeyKarsPprovince,
  2197: turkeyKastamonuPprovince,
  2200: turkeyKayseriPprovince,
  2154: turkeyKilisPprovince,
  2178: turkeyKirikkalePprovince,
  2176: turkeyKirklareliPprovince,
  2180: turkeyKirsehirPprovince,
  2195: turkeyKocaeliPprovince,
  2171: turkeyKonyaPprovince,
  2149: turkeyKutahyaPprovince,
  2158: turkeyMalatyaPprovince,
  2198: turkeyManisaPprovince,
  2224: turkeyMardinPprovince,
  2156: turkeyMersinPprovince,
  2182: turkeyMuglaPprovince,
  2162: turkeyMusPprovince,
  2196: turkeyNevsehirPprovince,
  2189: turkeyNigdePprovince,
  2174: turkeyOrduPprovince,
  2214: turkeyOsmaniyePprovince,
  2219: turkeyRizePprovince,
  2150: turkeySakaryaPprovince,
  2220: turkeySamsunPprovince,
  2183: turkeySanliurfaPprovince,
  2207: turkeySiirtPprovince,
  4854: turkeySinopPprovince,
  2181: turkeySivasPprovince,
  2225: turkeySirnakPprovince,
  2167: turkeyTekirdagPprovince,
  2199: turkeyTokatPprovince,
  2206: turkeyTrabzonPprovince,
  2192: turkeyTunceliPprovince,
  2201: turkeyUsakPprovince,
  2152: turkeyVanPprovince,
  2218: turkeyYalovaPprovince,
  2188: turkeyYozgatPprovince,
  2213: turkeyZonguldakPprovince
};
