/// Access to known geographies in United Kingdom and their metadata.
///
/// NOTICE: This file is auto-generated and should not be changed manually.
library;

import '../base.dart';
import 'unitedkingdom_states.dart';

/// The country of `United Kingdom`, and its 247 states
const Country unitedKingdom = Country(
  id: 232,
  name: "United Kingdom",
  longitude: -2.0,
  latitude: 54.0,
  capital: "London",
  currency: "GBP",
  currencySymbol: "£",
  currencyName: "British pound",
  emoji: "🇬🇧",
  emojiU: "U+1F1EC U+1F1E7",
  iso2: "GB",
  iso3: "GBR",
  native: "United Kingdom",
  numericCode: "826",
  nationality: "British, UK",
  phoneCode: "44",
  region: "Europe",
  subregion: "Northern Europe",
  tld: ".uk",
  states: [
    unitedKingdomAberdeen,
    unitedKingdomAberdeenshire,
    unitedKingdomAngus,
    unitedKingdomAntrim,
    unitedKingdomAntrimAndNewtownabbey,
    unitedKingdomArds,
    unitedKingdomArdsAndNorthDown,
    unitedKingdomArgyllAndBute,
    unitedKingdomArmaghCityAndDistrictCouncil,
    unitedKingdomArmaghBanbridgeAndCraigavon,
    unitedKingdomAscensionIsland,
    unitedKingdomBallymenaBorough,
    unitedKingdomBallymoney,
    unitedKingdomBanbridge,
    unitedKingdomBarnsley,
    unitedKingdomBathAndNorthEastSomerset,
    unitedKingdomBedford,
    unitedKingdomBelfastDistrict,
    unitedKingdomBirmingham,
    unitedKingdomBlackburnWithDarwen,
    unitedKingdomBlackpool,
    unitedKingdomBlaenauGwentCountyBorough,
    unitedKingdomBolton,
    unitedKingdomBournemouth,
    unitedKingdomBracknellForest,
    unitedKingdomBradford,
    unitedKingdomBridgendCountyBorough,
    unitedKingdomBrightonAndHove,
    unitedKingdomBuckinghamshire,
    unitedKingdomBury,
    unitedKingdomCaerphillyCountyBorough,
    unitedKingdomCalderdale,
    unitedKingdomCambridgeshire,
    unitedKingdomCarmarthenshire,
    unitedKingdomCarrickfergusBoroughCouncil,
    unitedKingdomCastlereagh,
    unitedKingdomCausewayCoastAndGlens,
    unitedKingdomCentralBedfordshire,
    unitedKingdomCeredigion,
    unitedKingdomCheshireEast,
    unitedKingdomCheshireWestAndChester,
    unitedKingdomCityAndCountyOfCardiff,
    unitedKingdomCityAndCountyOfSwansea,
    unitedKingdomCityOfBristol,
    unitedKingdomCityOfDerby,
    unitedKingdomCityOfKingstonUponHull,
    unitedKingdomCityOfLeicester,
    unitedKingdomCityOfLondon,
    unitedKingdomCityOfNottingham,
    unitedKingdomCityOfPeterborough,
    unitedKingdomCityOfPlymouth,
    unitedKingdomCityOfPortsmouth,
    unitedKingdomCityOfSouthampton,
    unitedKingdomCityOfStokeHyponHyptrent,
    unitedKingdomCityOfSunderland,
    unitedKingdomCityOfWestminster,
    unitedKingdomCityOfWolverhampton,
    unitedKingdomCityOfYork,
    unitedKingdomClackmannanshire,
    unitedKingdomColeraineBoroughCouncil,
    unitedKingdomConwyCountyBorough,
    unitedKingdomCookstownDistrictCouncil,
    unitedKingdomCornwall,
    unitedKingdomCountyDurham,
    unitedKingdomCoventry,
    unitedKingdomCraigavonBoroughCouncil,
    unitedKingdomCumbria,
    unitedKingdomDarlington,
    unitedKingdomDenbighshire,
    unitedKingdomDerbyshire,
    unitedKingdomDerryCityAndStrabane,
    unitedKingdomDerryCityCouncil,
    unitedKingdomDevon,
    unitedKingdomDoncaster,
    unitedKingdomDorset,
    unitedKingdomDownDistrictCouncil,
    unitedKingdomDudley,
    unitedKingdomDumfriesAndGalloway,
    unitedKingdomDundee,
    unitedKingdomDungannonAndSouthTyroneBoroughCouncil,
    unitedKingdomEastAyrshire,
    unitedKingdomEastDunbartonshire,
    unitedKingdomEastLothian,
    unitedKingdomEastRenfrewshire,
    unitedKingdomEastRidingOfYorkshire,
    unitedKingdomEastSussex,
    unitedKingdomEdinburgh,
    unitedKingdomEngland,
    unitedKingdomEssex,
    unitedKingdomFalkirk,
    unitedKingdomFermanaghAndOmagh,
    unitedKingdomFermanaghDistrictCouncil,
    unitedKingdomFife,
    unitedKingdomFlintshire,
    unitedKingdomGateshead,
    unitedKingdomGlasgow,
    unitedKingdomGloucestershire,
    unitedKingdomGwynedd,
    unitedKingdomHalton,
    unitedKingdomHampshire,
    unitedKingdomHartlepool,
    unitedKingdomHerefordshire,
    unitedKingdomHertfordshire,
    unitedKingdomHighland,
    unitedKingdomInverclyde,
    unitedKingdomIsleOfWight,
    unitedKingdomIslesOfScilly,
    unitedKingdomKent,
    unitedKingdomKirklees,
    unitedKingdomKnowsley,
    unitedKingdomLancashire,
    unitedKingdomLarneBoroughCouncil,
    unitedKingdomLeeds,
    unitedKingdomLeicestershire,
    unitedKingdomLimavadyBoroughCouncil,
    unitedKingdomLincolnshire,
    unitedKingdomLisburnAndCastlereagh,
    unitedKingdomLisburnCityCouncil,
    unitedKingdomLiverpool,
    unitedKingdomLondonBoroughOfBarkingAndDagenham,
    unitedKingdomLondonBoroughOfBarnet,
    unitedKingdomLondonBoroughOfBexley,
    unitedKingdomLondonBoroughOfBrent,
    unitedKingdomLondonBoroughOfBromley,
    unitedKingdomLondonBoroughOfCamden,
    unitedKingdomLondonBoroughOfCroydon,
    unitedKingdomLondonBoroughOfEaling,
    unitedKingdomLondonBoroughOfEnfield,
    unitedKingdomLondonBoroughOfHackney,
    unitedKingdomLondonBoroughOfHammersmithAndFulham,
    unitedKingdomLondonBoroughOfHaringey,
    unitedKingdomLondonBoroughOfHarrow,
    unitedKingdomLondonBoroughOfHavering,
    unitedKingdomLondonBoroughOfHillingdon,
    unitedKingdomLondonBoroughOfHounslow,
    unitedKingdomLondonBoroughOfIslington,
    unitedKingdomLondonBoroughOfLambeth,
    unitedKingdomLondonBoroughOfLewisham,
    unitedKingdomLondonBoroughOfMerton,
    unitedKingdomLondonBoroughOfNewham,
    unitedKingdomLondonBoroughOfRedbridge,
    unitedKingdomLondonBoroughOfRichmondUponThames,
    unitedKingdomLondonBoroughOfSouthwark,
    unitedKingdomLondonBoroughOfSutton,
    unitedKingdomLondonBoroughOfTowerHamlets,
    unitedKingdomLondonBoroughOfWalthamForest,
    unitedKingdomLondonBoroughOfWandsworth,
    unitedKingdomMagherafeltDistrictCouncil,
    unitedKingdomManchester,
    unitedKingdomMedway,
    unitedKingdomMerthyrTydfilCountyBorough,
    unitedKingdomMetropolitanBoroughOfWigan,
    unitedKingdomMidAndEastAntrim,
    unitedKingdomMidUlster,
    unitedKingdomMiddlesbrough,
    unitedKingdomMidlothian,
    unitedKingdomMiltonKeynes,
    unitedKingdomMonmouthshire,
    unitedKingdomMoray,
    unitedKingdomMoyleDistrictCouncil,
    unitedKingdomNeathPortTalbotCountyBorough,
    unitedKingdomNewcastleUponTyne,
    unitedKingdomNewport,
    unitedKingdomNewryAndMourneDistrictCouncil,
    unitedKingdomNewryMourneAndDown,
    unitedKingdomNewtownabbeyBoroughCouncil,
    unitedKingdomNorfolk,
    unitedKingdomNorthAyrshire,
    unitedKingdomNorthDownBoroughCouncil,
    unitedKingdomNorthEastLincolnshire,
    unitedKingdomNorthLanarkshire,
    unitedKingdomNorthLincolnshire,
    unitedKingdomNorthSomerset,
    unitedKingdomNorthTyneside,
    unitedKingdomNorthYorkshire,
    unitedKingdomNorthamptonshire,
    unitedKingdomNorthernIreland,
    unitedKingdomNorthumberland,
    unitedKingdomNottinghamshire,
    unitedKingdomOldham,
    unitedKingdomOmaghDistrictCouncil,
    unitedKingdomOrkneyIslands,
    unitedKingdomOuterHebrides,
    unitedKingdomOxfordshire,
    unitedKingdomPembrokeshire,
    unitedKingdomPerthAndKinross,
    unitedKingdomPoole,
    unitedKingdomPowys,
    unitedKingdomReading,
    unitedKingdomRedcarAndCleveland,
    unitedKingdomRenfrewshire,
    unitedKingdomRhonddaCynonTaf,
    unitedKingdomRochdale,
    unitedKingdomRotherham,
    unitedKingdomRoyalBoroughOfGreenwich,
    unitedKingdomRoyalBoroughOfKensingtonAndChelsea,
    unitedKingdomRoyalBoroughOfKingstonUponThames,
    unitedKingdomRutland,
    unitedKingdomSaintHelena,
    unitedKingdomSalford,
    unitedKingdomSandwell,
    unitedKingdomScotland,
    unitedKingdomScottishBorders,
    unitedKingdomSefton,
    unitedKingdomSheffield,
    unitedKingdomShetlandIslands,
    unitedKingdomShropshire,
    unitedKingdomSlough,
    unitedKingdomSolihull,
    unitedKingdomSomerset,
    unitedKingdomSouthAyrshire,
    unitedKingdomSouthGloucestershire,
    unitedKingdomSouthLanarkshire,
    unitedKingdomSouthTyneside,
    unitedKingdomSouthendHyponHypsea,
    unitedKingdomStHelens,
    unitedKingdomStaffordshire,
    unitedKingdomStirling,
    unitedKingdomStockport,
    unitedKingdomStocktonHyponHyptees,
    unitedKingdomStrabaneDistrictCouncil,
    unitedKingdomSuffolk,
    unitedKingdomSurrey,
    unitedKingdomSwindon,
    unitedKingdomTameside,
    unitedKingdomTelfordAndWrekin,
    unitedKingdomThurrock,
    unitedKingdomTorbay,
    unitedKingdomTorfaen,
    unitedKingdomTrafford,
    unitedKingdomUnitedKingdom,
    unitedKingdomValeOfGlamorgan,
    unitedKingdomWakefield,
    unitedKingdomWales,
    unitedKingdomWalsall,
    unitedKingdomWarrington,
    unitedKingdomWarwickshire,
    unitedKingdomWestBerkshire,
    unitedKingdomWestDunbartonshire,
    unitedKingdomWestLothian,
    unitedKingdomWestSussex,
    unitedKingdomWiltshire,
    unitedKingdomWindsorAndMaidenhead,
    unitedKingdomWirral,
    unitedKingdomWokingham,
    unitedKingdomWorcestershire,
    unitedKingdomWrexhamCountyBorough
  ],
  timezones: [
    Timezone(
      abbreviation: "GMT",
      gmtOffset: 0,
      gmtOffsetName: "UTC±00",
      tzName: "Greenwich Mean Time",
      zoneName: "Europe/London")
  ],
  translations: {
    "kr": "영국",
    "pt-BR": "Reino Unido",
    "pt": "Reino Unido",
    "nl": "Verenigd Koninkrijk",
    "hr": "Ujedinjeno Kraljevstvo",
    "fa": "بریتانیای کبیر و ایرلند شمالی",
    "de": "Vereinigtes Königreich",
    "es": "Reino Unido",
    "fr": "Royaume-Uni",
    "ja": "イギリス",
    "it": "Regno Unito",
    "cn": "英国",
    "tr": "Birleşik Krallik"
  });
